### ISSUE TITLE
chore: UI should say "me" instead of "user"

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#100]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb1orIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7684f0066ebf009c0ced9eb9a1474f0d39f74565/image.png)

**Comment by 0xSage** [comment]
this looks done in new version
