### ISSUE TITLE
feat: let users publish models (and jsons) to the hub

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1003]
**Problem**
- `model.json` is easily packageable /exportable. Let users share it via the hub

**Success Criteria**
- Users can share their models via hub (just the download URL, as we dont host models yet)
- Users can share their model configs via hub

**Additional context**

**Comment by imtuyethan** [comment]
Moving this to Notion til it is confirmed: https://www.notion.so/jan-ai/Let-users-publish-models-and-jsons-to-the-hub-e5ee0e29e91e4e9b975c55c2e938a2f9?pvs=4
