### ISSUE TITLE
docs: Jan x Continue x VSCode integration

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1004]
**Pages**
- https://jan.ai/guides/integrations/continue

**Success Criteria**
A step-by-step guide on how to integrate Jan with Continue

**Additional context**
Examples, reference pages, resources

**Comment by clement-igonet** [comment]
Support is not complete.
Indeed, Continue dev also has a code autocompletion feature that does not work as it relies on `/v1/completions`, not supported by Jan.

**Comment by 0xSage** [comment]
> Support is not complete. Indeed, Continue dev also has a code autocompletion feature that does not work as it relies on `/v1/completions`, not supported by Jan.

Hey it works - I'm currently using Jan x continue. We do support an OAI compatible endpoint. 
https://jan.ai/api-reference/
https://jan.ai/guides/integrations/continue/

**Comment by clement-igonet** [comment]
Not for Continue code autocompletion, that relies on /v1/completions.
