### ISSUE TITLE
bug: Jan uses only half of my CPU resource

### ISSUE THREAD

**Issue by linhtran174** [janhq/jan#1016]
**Describe the bug**
My system has 2 equal CPUs with its own memory. Jan only seem to run on 1 out of 2. 

**To Reproduce**
- Start mistral-ins-7b-q4
- Chat with the Jan assistant 
- 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Window 10
 - CPU: 2 CPUs - Xeon E5 2678v3 12 cores 
 - RAM: 128GB

**Additional context**

**Comment by vuonghoainam** [comment]
@linhtran174  This is expected behavior for current nitro/ llama.cpp version.
A.I running on multiple hardware (CPUs/ GPUs) needs:
- A good bandwidth between those
- Adding `tensor parallel` to distribute the computation carefully

**Comment by linhtran174** [comment]
I got the point. 
Llama.cpp already has OpenMPI support for distributed system (clusters, multiple machines), but its nature is to solve loading very large models, but not improving inference speed. This is to differentiate with OpenMP, which is designed for less distributed system (like shared memory, high bandwidth interconnect). 

Closing this for now.
