### ISSUE TITLE
epic: Jan can search the OS

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1025]
## Motivation
- Local AIs should sit atop Kernel and "understand" drivers and applications
- Users want to do knowledge searches using Jan into their entire computer

## Success Criteria
- Users can opt in to `index` / `sync` their computer
- Users can set certain folders & paths to be indexed, or conversely ignored
- Indexing progress and fail states are properly communicated
- Users can toggle settings to auto-index
- Users can talk to a Desktop/OS assistant/Jan, with OS-search turned on (or some other manifestation)

## Resources

_Similar Work_
- Rewind AI
- https://www.theverge.com/2023/11/29/23981802/software-applications-inc-workflow-shortcuts-apple-employees-startup

## Dependencies
- #362

**Comment by imtuyethan** [comment]
Moving to Notion til it is confirmed: https://www.notion.so/jan-ai/a8dace5a55f34f9493dcef8844a56f87?pvs=4
