### ISSUE TITLE
feat: model.json doesn't have any required params

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1028]
**Problem**
[Per spec](https://jan.ai/specs/models/#modeljson), users should only have to modify 1 field for a model to work

```js
source_url: //techincally, the only required field
```

**Success Criteria**
- Have a global default for model.json
- Maybe just a fallback via `/model-extensions/src/model.json`
- Maybe design a future compatible name i.e. `/model-extension/src/gguf-model.json`

**Additional context**

Once this is the case, this issue would be a breeze: https://github.com/janhq/jan/issues/678

**Comment by namchuai** [comment]
Hmm, let's say user import the model locally, which is drag and drop to Jan. Then, `source_url` might not be relevant, right?

**Comment by 0xSage** [comment]
> Hmm, let's say user import the model locally, which is drag and drop to Jan. Then, `source_url` might not be relevant, right?

I think we still have to think about this from the perspective of technical users who directly mv & edit files. 

Then what is absolutely required for models to run - it should be as little fields required as possible. 

And we have a global `model.json` that has the default values as a fallback. It is also very clear to the user what the default settings are. 

Scenarios:
- User has 1 model binary, but has 2 configurations, e.g. folders `model-a-with-params-a` and `model-a-with-params-b`. It doesnt make sense for users to create copies of large model binaries.
- User decides they want all downloaded models to have `max_tokens: 2048` (or some other global default preference), in this case, they'd only have to edit the `default model.json` once, instead editting every single `model.json` in every model download folder.

Happy to chat/debate about this further tomorrow! cc @dan-jan

**Comment by 0xSage** [comment]
Update, for RAG `/files`, we decided to copy over each file upload directly into `/thread-id` folder.

**Comment by 0xSage** [comment]
woot
