### ISSUE TITLE
bug: 0.4.2 does not recreate `/models` folder if it does not exist

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1037]
**Describe the bug**

**To Reproduce**
1. Download `0.4.2` from https://jan.ai (https://github.com/janhq/jan/releases/tag/v0.4.2)
2. Blow away existing contents of `/jan` folder
3. Run Jan
4. See empty Hub
5. Jan does not re-create `/models` folder

This seems to happen in both the following scenarios:
1. Deleting the contents of `/jan` (but keeping `/jan`)
2. Deleting the entire `/jan` folder

It seems that our logic to recreate the `/jan` folder is not working? See the Finder screenshot below. 

**Screenshots**
![image](https://github.com/janhq/jan/assets/101145494/d9b42829-a274-4aa2-9cb6-17a0bea0abe3)

![image](https://github.com/janhq/jan/assets/101145494/6bd4e6c2-fb70-4938-956b-caa2c3cdade5)

**Desktop (please complete the following information):**
 - OS: Mac OSX

**Additional context**

**Comment by louis-jan** [comment]
Addressed
