### ISSUE TITLE
bug: Unable to detect manually imported Model 

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1039]
**Describe the bug**

**To Reproduce**
- JasonB from Discord is unable to get Jan to detect manually imported model (from creating folder and pasting GGUF file in)

**Expected behavior**

**Screenshots**

<img width="545" alt="image" src="https://github.com/janhq/jan/assets/101145494/c46f1c2e-f161-46b8-bd0d-862b4fcd5cf6">
<img width="539" alt="image" src="https://github.com/janhq/jan/assets/101145494/af354297-aa65-4f0e-afea-d21c3bb43283">
<img width="972" alt="image" src="https://github.com/janhq/jan/assets/101145494/23daf992-3db6-4403-8f5c-754d04a0f14c">
<img width="541" alt="image" src="https://github.com/janhq/jan/assets/101145494/b7bbc29a-943d-4d30-8830-aae4500e9c04">

**Desktop (please complete the following information):**

**Additional context**

- [ ] Dan's note: Need to have better documentation than the Quickstart
- [ ] Dan's note: Need to have very clear instructions for how to "manually import" a Model to Jan

**Comment by dan-jan** [comment]
Fix from @louis-jan:

Add: 

```
"state": "ready",
"engine": "nitro"
```

**Comment by dan-jan** [comment]
On second thoughts, I'm re-opening this as I think this is a logic error. We should be scanning the `/models` directory and indicating `state: ready` if there is a valid GGUF or .bin file. 

We should not need the user to manually update the `model.json` for a state variable.

**Comment by ddh0** [comment]
I'm having a similar issue. I'm following the [guide](https://jan.ai/guides/quickstart/#1-create-a-model-folder) and I'm unable to get my model to show up in Jan, either on the models page or on the Hub. And now when I open the hub the app crashes 😅

I'm trying to add my own model, **orcamaid-v2-13b** from TheBloke's GGUF release. I've attached the `model.json`, a screenshot of the **./jan** folder, and a screenshot of the **./orcamaid-v2-13b** folder.

Let me know if there's anything I can do.

<img width="372" alt="jan_crashed" src="https://github.com/janhq/jan/assets/40664579/b8370cd8-b59d-4f41-999e-0ed8c535a17c">
<img width="1208" alt="jan_folder" src="https://github.com/janhq/jan/assets/40664579/cdb177db-9620-4ab6-9e71-7509d08299ca">
[model.json](https://github.com/janhq/jan/files/13687775/model.json)
<img width="1208" alt="orcamaid_folder" src="https://github.com/janhq/jan/assets/40664579/85f0bc1a-04ba-43bc-af91-786150835dd0">

**Comment by louis-jan** [comment]
Here is the corrected version @ddh0. The "state" should only have one value
[model.json](https://github.com/janhq/jan/files/13687996/model.json)

**Comment by louis-jan** [comment]
Should be addressed by this #1028

**Comment by 0xSage** [comment]
fixed
