### ISSUE TITLE
feat: Jan can detect or use default proxy (needed for Corporate network)

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1040]
**Problem**
- jasonB from Discord is unable to download models using the Hub as Electron does not use the default proxy
- Not possible to authenticate proxy and connecting is refused

**Success Criteria**
- Jan should be able to detect default proxy (common on corporate networks)

**Additional context**

**Comment by vuonghoainam** [comment]
@dan-jan actually I'm quite opposed to automatically detect and use default proxy because in some niche cases, there are proxies for different purposes. Solving it by the settings specifically for e.g: Connecting to HuggingFace, Git, etc would solve a lot of pain.

**Comment by dan-jan** [comment]
Makes sense - btw, I'll be closing this issue in favor of yours. It's a lot better written!

https://github.com/janhq/jan/issues/1074
