### ISSUE TITLE
docs: Manually importing models into Jan

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1041]
**Pages**
- Users who want to manually import models into Jan by copy-pasting the GGUF into the `/models` folder structure
- See https://github.com/janhq/jan/issues/1039
- See [conversation with JasonB](https://discord.com/channels/1107178041848909847/1149558035971321886/1185220986891681822) in Discord:

**Success Criteria**
Content that should be covered

**Additional context**
Examples, reference pages, resources

**Comment by 0xSage** [comment]
done
