### ISSUE TITLE
bug: UI chatbox doesn't resize back down

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1045]
**Describe the bug**

<img width="1351" alt="image" src="https://github.com/janhq/jan/assets/69952136/58c836ad-8823-4adc-abb3-15f096280085">

**To Reproduce**
1. Type a lot of text
2. See chatbox grow vertically
3. Delete all text
4. Expect chatbox to shrink back down
5. But the height stays the same

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by KossBoii** [comment]
@0xSage I cannot produce back this problem. Can you double-check again?
