### ISSUE TITLE
bug: cache hallucinations leading to major usability regression

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1046]
**Describe the bug**

https://github.com/janhq/jan/assets/69952136/ee10511e-aab5-464a-ac32-0dc4c8624e0e

**To Reproduce**
1. Use model A (Trinity), ask a question
2. Start a new thread
3. Switch to model B, and ask a different question
4. Model B immediately responds with the same response from step (1)

Sometimes this happens without even switching models. 
1. Use mistral
2. Start new thread
3. Use mistral again, ask a different question
4. Get the answer from step (1)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by 0xSage** [comment]
Regression in usability here fyi @tikikun . Any insights as to what's causing this?

**Comment by louis-jan** [comment]
![Screenshot 2023-12-18 at 11 55 43](https://github.com/janhq/jan/assets/133622055/4bf9cfaf-10b9-4bff-afdf-920b89364abe)
![Screenshot 2023-12-18 at 11 55 55](https://github.com/janhq/jan/assets/133622055/b8f03466-1301-4b6a-8650-c20f5f23d709)

This is the issue you noticed before @tikikun, there is a cache when switching between models. As I remember you fixed it already

**Comment by louis-jan** [comment]
Second attempt, cache issue 
![Screenshot 2023-12-18 at 12 04 45](https://github.com/janhq/jan/assets/133622055/a48b8a37-9130-4e90-a4b3-1979a9b30bed)
![Screenshot 2023-12-18 at 12 05 01](https://github.com/janhq/jan/assets/133622055/010ecfd2-ddcc-4d22-8dca-08f803888bd4)

**Comment by louis-jan** [comment]
Restart Nitro process every time user switches to another model does fix the issue. The case to reproduce: 
1. Stop a streaming message on Model A at T1
2. Switch to Model B at T2
3. Send a message to Model B at T3
4. Nitro flushes cached response (T1) to T3 request.
5. Go back Model A and send message at T4, get T3 response with T4 request
