### ISSUE TITLE
bug: Trinity-v1 produces strange responses in Jan (hallucinations, etc)

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1048]
**Describe the bug**
- Trinity v1 works well in Nitro, but produces strange responses in Jan (e.g. hallucinations, etc)
- Likely related to Prompt Template or System Prompt

**Screenshots**

1. Speaks Dutch: Mac OSX 64gb, 0.4.2
<img width="1488" alt="image" src="https://github.com/janhq/jan/assets/101145494/2810f931-6ecd-42e5-ae73-ad4db4f0782d">

1. Speaks Dutch? Mac OSX 64gb, 0.4.2
<img width="1491" alt="image" src="https://github.com/janhq/jan/assets/101145494/34dadee8-c9c1-4f48-8ea5-c32415e57697">

1. Weird formatting, hallucination: Ubuntu on X1 Nano Thinkpad, 0.4.2
![image](https://github.com/janhq/jan/assets/101145494/d41f318c-cb5b-40ff-9b88-fce6e3730f9a)

1. Weird formatting: Ubuntu on X1 Nano Thinkpad, 0.4.2
![image](https://github.com/janhq/jan/assets/101145494/8c0df754-03e0-4390-9612-d65c5489e384)

**Desktop (please complete the following information):**
- Version: 0.4.2

**Additional context**

**Comment by tikikun** [comment]
<img width="1006" alt="image" src="https://github.com/janhq/jan/assets/22268502/c102da1e-dd99-4996-978e-18a6b6dacf59">
<img width="1001" alt="image" src="https://github.com/janhq/jan/assets/22268502/ecb9f2ad-6088-439b-9625-c280344400f2">


@hahuyhoang411 we need to add a simple role message in system prompt for this model

**Comment by dan-jan** [comment]
Seems to be experienced by others in llama.cpp itself. 

![Uploading image.png…]()

**Comment by hahuyhoang411** [comment]
Working on this https://github.com/janhq/jan/pull/1053

**Comment by hahuyhoang411** [comment]
Update the trinity to v1.2 for better alignment and stop giberishing
