### ISSUE TITLE
Discussion: Updated `model.json` for multiple model artifacts

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1049]
**Motivation**
- Jan App is adding multi-modality features: Vision (llava with 2 models), Talk Llama (whisper + llama)
- The current `model.json` only supports 1 model binary

**Discussion**
- What should we add in order to add more model downloads/ usage

**Alternatives**

**Resources**
- To unblock #1023

**Comment by 0xSage** [comment]
Closing this issue in favor of just tracking 1023. If you are introducing any breaking changes @hiro-v , please inform app pod.
