### ISSUE TITLE
architecture: Jan Cloud multi-tenancy

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#105]
## Overview

- `cloud.jan.ai` should be a multi-tenant version of Jan
- Cater to users who want a 'managed' Jan
- Cater to users who don't have as high privacy requirements (e.g. share OpenAI key, access cheap open source AI inference)
- Some customers might need LDAP for realm

## Architecture Decisions

- [ ] What should the approach be for Keycloak? (should we implement this as multi-tenant Keycloak?)

**Comment by 0xSage** [comment]
archiecture changed
