### ISSUE TITLE
feat: users can restore Jan app to `factory settings` in Settings

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1052]
**Problem**
- when we ship breaking changes, sometimes the `/models` `assistant` folders need to be overwritten/deleted/purged
- I have to manually reset app right now
- Edge case: #1072 
- `rm -rf /application support`
- `rm -rf /janroot`

**Success Criteria**
- A "danger!" `factory reset` button in settings to make this step easier for users
- All models, assistants, threads folders are reset to what you would get via a new installation
- Delete cache & app support folders

**Additional context**

**Comment by imtuyethan** [comment]
Design link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2303-39294&mode=design&t=P76QcZnZBvoxZEgk-4

cc @hiro-v @louis-jan @urmauur
