### ISSUE TITLE
feat: Missing guidance when start Jan

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1055]
**Problem**
We are missing a bubble or notification for the user to use the app after they reopen it

See the image:
![image](https://github.com/janhq/jan/assets/64120343/f8f577bb-52aa-4bfa-a0c9-be4b281bc151)

Users can't click on the enter your message and are quite confused on how to use it (since we block it)

**Success Criteria**
We should have a bubble or something to let users know what they should do. Somewhat like this

![Capture](https://github.com/janhq/jan/assets/64120343/d0b17f75-72b7-429f-9a9d-7c37c347fd8a)

**Comment by 0xSage** [comment]
@hahuyhoang411 ashley and I are thinking through a better onboarding experience as a whole. Sorting this issue into that milestone for now and unassigning from eng. 

**it should only go to eng when we have clear specs and designs**

**Comment by 0xSage** [comment]
Closing, tracking it in Discord as part of a larger epic: https://discord.com/channels/1107178041848909847/1187643022532431983
