### ISSUE TITLE
bug: app does not sync state with nitro process

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1067]
**Describe the bug**
Somehow Nitro could be crashed or stopped working, app does not handle the process status properly, there should be an event from extension to app so the next message send will trigger model load

**To Reproduce**
1. Start a thread
2. Send message 
3. Kill nitro from terminal
4. App failed to send message instead of loading model again

**Expected behavior**
App shows error message when nitro process is exit and next message send should spawn nitro and load model again

**Comment by namchuai** [comment]
@Van-QA @louis-jan , please help to test this ticket after #1493 merged.

Here's the steps:
1. Start chatting with any model
2. Wait until model successfully loaded (responded)
3. Kill the nitro process, you can use Task manager or activity monitor.
4. After sometimes (maximum 5 secs), continue chat in the same thread.
5. You can see that Jan is automatically load the model again.

**Comment by Van-QA** [comment]
Tested on [nightly build](https://github.com/janhq/nitro/actions/runs/7493910286) for both macOS and Windows (192.168.100.13) ✅ 
Jan reloads the model again after the Nitro process has been killed.
