### ISSUE TITLE
feat: Support for HTTP proxy

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1074]
**Problem**
- User request - [Discussion](https://discord.com/channels/1107178041848909847/1149558035971321886/1185221927426605127)
- Tried to use Jan in enterprise network with air-gapped environment. This network has firewall that blocks huggingface. However, they can only see the proxies settings but not able to change it (requires Windows Administrator password)

**Success Criteria**
- An extension that can be toggled on or off
- A json file in `HOME/jan` for proxies settings
![CleanShot 2023-12-19 at 08 40 21@2x](https://github.com/janhq/jan/assets/22463238/9baeb4a3-7420-432a-bdfc-ce5bdf68a8f1)

**Additional context**
![CleanShot 2023-12-19 at 08 36 35@2x](https://github.com/janhq/jan/assets/22463238/1fa17041-44f8-4ab9-9d1e-c52730acd9b2)
![CleanShot 2023-12-19 at 08 37 43@2x](https://github.com/janhq/jan/assets/22463238/d220017d-c27c-411f-b4e9-8f77719ee780)
![CleanShot 2023-12-19 at 08 37 58@2x](https://github.com/janhq/jan/assets/22463238/ec8bd208-2eac-4b9b-8b61-7cf3a50bccf4)

**Comment by dan-jan** [comment]
@vuonghoainam Great job writing a clear spec. I actually created an issue for this a couple of days ago - will close it in favor of this. 

https://github.com/janhq/jan/issues/1040

Great job!

**Comment by 0xSage** [comment]
Nit: removed direct references to name/pronouns/"customer" in issue description.

**Comment by Van-QA** [comment]
tested and looking good via the testing on Jan v0.4.4-160 ✅ 
<img width="1891" alt="image" src="https://github.com/janhq/jan/assets/64197333/4fd059a4-cae8-4b65-9453-fe33bfd57caf">
