### ISSUE TITLE
bug: Windows update app failed

### ISSUE THREAD

**Issue by hiento09** [janhq/jan#1075]
**Describe the bug**
The auto-update feature on my windows machine not works
- OS: Windows 11
- Jan app version: update from 0.4.1 to 0.4.2

**To Reproduce**
1. Install an old version of jan app on windows machine
2. Open the app
3. The auto updater notification will show up
4. Click update
5. No thing happend next

**Expected behavior**
A restart notification button should be pop up like windows and linux

**Screenshots**
![image](https://github.com/janhq/jan/assets/136591877/acb4cfde-9f4e-4cfc-b583-15bc85c2d6b4)
![image](https://github.com/janhq/jan/assets/136591877/92a13ffb-dc5e-4519-bbe3-f744169f2dcc)
![image](https://github.com/janhq/jan/assets/136591877/00deedef-ce70-4af8-99ee-036aec7de59c)

**Comment by louis-jan** [comment]
Great find as always. Thank you @hiento09 🙏
