### ISSUE TITLE
bug: inconsistent model version

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1080]
**Describe the bug**
Version format is not consistent, v1 vs v1.0, let's update all remote models.

**To Reproduce**
1. Go to settings
2. Access models section
3. See the model version

**Expected behavior**
The model version format should be the same across models.

**Screenshots**
![Screenshot 2023-12-19 at 10 10 06](https://github.com/janhq/jan/assets/133622055/e4cb5aa1-1abf-4aa4-a1e4-8ade9e39deea)

**Desktop (please complete the following information):**

**Additional context**

**Comment by louis-jan** [comment]
@urmauur a minor fix: empty model size should be hidden

**Comment by hahuyhoang411** [comment]
https://github.com/janhq/jan/pull/1086 Fix here
