### ISSUE TITLE
bug: Remote models should be always active

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1091]
**Describe the bug**
Given the engine file is properly configured. Remote models such as OpenAI should be presented as active models and user would not need to do anything to start / stop. Do not allow user to delete remote models.

![Screenshot 2023-12-19 at 10 10 06](https://github.com/janhq/jan/assets/133622055/00bd235e-afca-415b-9bae-c187b3e4fac0)

**To Reproduce**
1. Go to Settings
2. Click on Models
3. Scroll down to OpenAI models
4. All remote models should be all activated

**Expected behavior**
Please see #997

**Comment by namchuai** [comment]
I think those should be `N/A` or hide it.
<img width="98" alt="Screenshot 2023-12-19 at 12 22 04" src="https://github.com/janhq/jan/assets/10397206/05591502-d36d-443e-a889-9f133e144bf0">

**Comment by urmauur** [comment]
> I think those should be `N/A` or hide it.
> 
> <img width="98" alt="Screenshot 2023-12-19 at 12 22 04" src="https://github.com/janhq/jan/assets/10397206/05591502-d36d-443e-a889-9f133e144bf0">
> 
> 

Fixed on latest main branch @namchuai 🙏🏻
