### ISSUE TITLE
bug: stacked chat/completions does not work

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1096]
**Describe the bug**
As a user I would like to send chat/completions requests across threads. Tested with latest Nitro 0.1.32, the second request will yield empty response. I'd like to have it stacked and response a valid response according to my request.

**To Reproduce**
1. Open Nitro 0.1.32
2. Open Jan App and send message to thread A
3. Send message to thread B
4. Thread B shows blank message immediately 

**Expected behavior**
Should have valid message response in thread B after thread A message stream is done

**Screenshots**
![Screenshot 2023-12-19 at 14 34 16](https://github.com/janhq/jan/assets/133622055/f0db7950-ce69-4aad-8cea-3d29aed17f6b)
![Screenshot 2023-12-19 at 14 34 32](https://github.com/janhq/jan/assets/133622055/ad07d8af-b974-44ff-9a95-b4d655a218aa)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Jan Electron latest main
 - Nitro 0.1.32

**Additional context**

**Comment by imtuyethan** [comment]
Can we:
Users input message 1 in threads A -> show message has been sent + response loading  (LLM streaming for message 1)
Users input message 2 in threads B -> show message has been sent + response loading (LLM still streaming for message 1 -> done & sent response -> continue to stream message 2)

As long as we replace empty response with loading, it should be fine.
