### ISSUE TITLE
bug: TheBloke WhiteRabbitNeo GGUF model doesn't work on Jan

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1166]
TheBloke WhiteRabbitNeo GGUF model, specifically, doesn't work on Jan. 

Other models seem to work for user. 

OS: m1/16GB mac

<img width="1067" alt="image" src="https://github.com/janhq/jan/assets/69952136/0349a45f-dcd0-4b64-bb8c-3b591f224e28">

_Username redacted for privacy_

**Comment by 0xSage** [comment]
Can you investigate it this week @hiro-v , and help to triage this issue appropriately?

**Comment by tikikun** [comment]
investigating now

**Comment by hahuyhoang411** [comment]
tried this model in Mac m1/16gb and windows, everything works fine

![image](https://github.com/janhq/jan/assets/64120343/42a617ac-b8d8-4605-8c3b-e54fca0b8009)

**Comment by tikikun** [comment]
tried on mac work fine for me too

**Comment by tikikun** [comment]
the issue maybe related to this https://github.com/janhq/nitro/issues/267, some user also reporting frozen computer without metal lib, will close this one
