### ISSUE TITLE
feat: new threads should default to previous threads configurations

### ISSUE THREAD

**Issue by dillfrescott** [janhq/jan#1175]
I am always sliding the slider to 4096 tokens every new chat from the default. It should 100% remember what you set it to and persist.

**Comment by 0xSage** [comment]
Threads should indeed default to the same settings as the previous `thread.json`

**Comment by 0xSage** [comment]
🙏

**Comment by Van-QA** [comment]
Need Co‌‌rtex support as in https://github.com/janhq/cortex/issues/616
