### ISSUE TITLE
feat: Magicoder-S-DS-6.7B

### ISSUE THREAD

**Issue by MrBenzWorld** [janhq/jan#1177]
Magicoder-S-DS-6.7B , please add this model . this is great for code generation. 
LM studio, TeX generation web ui are not supporting this model.

**Comment by hahuyhoang411** [comment]
https://github.com/janhq/jan/pull/1213 Please follow this PR for the issue

**Comment by MrBenzWorld** [comment]
> https://github.com/janhq/jan/pull/1213 Please follow this PR for the issue

Magicoder model is added but it is not working. Please check. @hahuyhoang411

**Comment by hahuyhoang411** [comment]
I've just found that problem too. I am working on it

**Comment by hahuyhoang411** [comment]
The problem is related to GGUF converted version of it. So I think you can try `codeninja` or `deepseek coder`. I will add this model back when it can be converted correctly.
