### ISSUE TITLE
epic: Jan Hub recommends easiest and suitable Models, prevents OOM errors

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1179]
## Objective

- WIP Spec

## Braindump

- Most people have only heard of Llama2, Mistral (i.e. the "brand names")
- Should we have a "Getting Started" section, that recommends very small models that they can download and use quickly?
- Should we have a "Foundational Models" section, that recommends by famous models (i.e. Llama2, Mistral)

## Tasklist

- [ ] #1008
-

**Comment by dan-jan** [comment]
Suggestion from `jawenforcement` from Discord

![Image](https://github.com/janhq/jan/assets/101145494/b120e0f3-5ea5-4f36-acde-b987e0b55d2d)

**Comment by 0xSage** [comment]
Closing as dupe of #850
