### ISSUE TITLE
feat: Apple Ferret and MLX

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1181]
## Objective

- WIP spec

## Resources

- Apple Ferret
- Need to support MLX
- Support Quantization
- https://www.reddit.com/r/LocalLLaMA/comments/18oke4y/apples_mlx_framework_adds_quantization_support/

**Comment by tikikun** [comment]
blocked by Python runtime

**Comment by 0xSage** [comment]
dupe of https://github.com/janhq/cortex/issues/678
