### ISSUE TITLE
bug: Reveal in Finder does not work in Windows, it has wrong slashes in the dir path

### ISSUE THREAD

**Issue by linkinxp** [janhq/jan#1183]
**Describe the bug**
Clicking on Reveal in Finder does not work, throws and error saying that it can't find, if you look at the path is trying to go, it has backwards slashes

**To Reproduce**
1. Go to 3 dots next to thread
2. Click on Reveal in inder
3. See error

**Expected behavior**
I would expect windows explorer would open to the right directory

**Screenshots**
![image](https://github.com/janhq/jan/assets/66175003/ee1fb170-1018-40b8-841b-c4e1485b39a4)
Correct Path:
![image](https://github.com/janhq/jan/assets/66175003/24be3ae9-087c-42ef-8c95-da8ece69531e)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Version 0.4.3

**Comment by dan-jan** [comment]
Ah man, our bad! You can guess what OS the Jan Team prefers ;)
