### ISSUE TITLE
epic: User can add alternative Model folder to scan for GGUF files

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1185]
## Objective
- User should be able to add additional Model folder, that Jan imports models from
- Why: power users tend to have existing folder full of model files (structure may be different)

## Open Questions
- [ ] How do we adapt to different types of Model folders?
- [ ] We may need to pare down how "opinionated" our Models directory is

## Resources

<img width="1197" alt="image" src="https://github.com/janhq/jan/assets/101145494/9a8683ff-17f9-47d9-82b3-2c60f03b4ef8">
<img width="1192" alt="image" src="https://github.com/janhq/jan/assets/101145494/875a150f-a5a6-48c8-9edf-87d999bd33c7">

**Comment by hexbinoct** [comment]
hi, there seems to be a trend where llm UIs each are requiring their own folders, some have format of /repo/model, some simply have /models etc.
Why make multiple copies of the gguf files, the model should just be picked up by the llm UI.
For example a feature that lets add gguf file from a list of directories. You keep adding directories, and some grid below keep on showing, live, what models it found there. These are the models that use should see in the chat UI being able to select from the drop down.
most people on reddit localllama sub have 100s of GB of gguf files already downloaded.

**Comment by 0xSage** [comment]
dupe #1381
