### ISSUE TITLE
bug: message should only be interrupted when i start another thread 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1191]
**Describe the bug**
Right now, the message is interrupted even when I click on another thread, while it should only be interrupted when i start another thread.

https://github.com/janhq/jan/assets/89722390/e9de9f29-7b6a-4d71-a079-a40fc0ded686

**To Reproduce**
1. Start thread A
2. Click on another thread
3. Go back to thread A
4. See empty field 

**Expected behavior**
Message should only be interrupted when i start another thread 

**Desktop:**
 - Jan v0.4.3
- Mac Air 16GB Sonoma 14.2

**Comment by louis-jan** [comment]
This would be more correct, as the message should be interrupted if we switch to another thread with a different model. @imtuyethan

**Comment by louis-jan** [comment]
Since its more critical from Nitro side and would break the flow. We will need to investigate more on this so would shift to the next sprint. Will close #1237 since the hacky fix does not work for all cases.

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-273 ✅
