### ISSUE TITLE
feat: allow users to adjust the width of the left & right panels as well as the size of Jan App interface

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1192]
## Problem
Right now users cannot change the size of Jan, compared to Obsidian or LLM studio, it is much more flexible that I can reduce the size of those interfaces to fit my needs. 

https://github.com/janhq/jan/assets/89722390/b86b73ee-fb60-4fc1-8b13-29c5c958f781

## Success Criteria 
Users should be able to adjust the width of the left & right panels as well as the size of Jan App interface

## Design
Here's the design link for this:
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=992-60716&mode=design&t=5KliLuOkCovMioCh-4
<img width="786" alt="Screenshot 2023-12-25 at 6 41 08 PM" src="https://github.com/janhq/jan/assets/89722390/9e56c326-cae7-4c0e-8d7a-953fcf895779">

**Comment by 0xSage** [comment]
This is a User request from users with bigger monitors

**Comment by urmauur** [comment]
@imtuyethan @Van-QA pending this ticket until we finalize the new layout desktop app
