### ISSUE TITLE
feat: Enable global default `model.json` with all the fallback properties

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1196]
**Problem**

**Success Criteria**
- It should be clearly accessible in `./models` folder. 
- Location suggestions: `./models/defaults` `./models/global` `./models/common`
- It should be clearly named to accommodate future model formats: 
- i.e. `default_model.json`, `default_gguf_model.json`

**Additional context**
Blocking: #1028

**Comment by namchuai** [comment]
This issue is implemented in #1314 . The default model.json will be stored at `~/jan/models/config/default-model.json`.

cc @louis-jan
