### ISSUE TITLE
Bitdefender Antivirus Flags Monitoring Extension Files as Malicious

### ISSUE THREAD

**Issue by Nathandomes** [janhq/jan#1198]
### Description

While installing and running `jan.exe`, my antivirus (Bitdefender) flagged several files as potentially malicious and quarantined them. This occurred specifically with files located in the `c:/Users/[name]/jan/extensions/@janhq/monitoring-extension/` directory, and the file `jan.lnk` was also quarantined.

### Steps to Reproduce

1. Downloaded and installed `jan.exe`.
2. Ran the application.
3. Bitdefender antivirus triggered an alert and quarantined multiple files.

### Expected behavior

I did not expect any antivirus alerts from running a trusted open-source application.

### Actual behavior

Bitdefender flagged and quarantined multiple files associated with `jan.exe`, particularly from the monitoring extension.

### Affected files

C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\filesystem.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\internet.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\processes.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\graphics.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\dist\index.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\dist\module.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\network.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\osinfo.js C:\Users\nathan\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Jan.lnk
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\system.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\util.js
C:\Users\nathan\jan\extensions\@janhq\monitoring-extension\node_modules\systeminformation\lib\wifi.js
C:\Users\nathan\Desktop\Jan.lnk

Bitdefender proceeded to block the entire jan.exe and installer.

### Antivirus Software

- Antivirus: Bitdefender
- Build 27.0.25.116

### Additional Information

This is the first report of an antivirus response to `jan.exe` as far as I know. The monitoring extension's role in tracking system resources could potentially be the reason for these flags.

### System Information

- OS: [Windows 10]
- Version: [19045.3803]

Regards,
Nathan

**Comment by hiento09** [comment]
resolved https://github.com/janhq/jan/pull/1282
