### ISSUE TITLE
bug: cleared the thread, but the text is still there under the title

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1200]
**Describe the bug**
Reported by Holy: I cleared the thread, but the text is still there under the title
<img width="815" alt="Screenshot 2023-12-25 at 11 40 53 PM" src="https://github.com/janhq/jan/assets/89722390/b2cc9a25-ebdf-4db3-8b7e-b8037051d0f2">
[
![image](https://github.com/janhq/jan/assets/89722390/012fdc60-0198-4c77-9899-871ef6eea5b6)
](url)

**Expected behavior**
When clear the thread, thread's title & body should be cleared too

**Comment by TC117** [comment]
A Bit more on this, since we are on theme of clearing text, there are some case that I was facing 
![image](https://github.com/janhq/jan/assets/19384189/cc56dfd7-397f-4051-91a3-a852b6dc2aa5)

**Comment by louis-jan** [comment]
Good find! @TC117
