### ISSUE TITLE
feat: users should be able to switch models mid-thread

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1201]
**Problem**
Right now users have to start a new thread to use another model which causes a lot of confusion to our users.

**Success Criteria**
Users should be able to switch models mid-thread.

**Comment by TC117** [comment]
Since this is relate to change model, can we discuss about what if we delete a model 
![image](https://github.com/janhq/jan/assets/19384189/3b97f7cb-f234-468d-a787-b5dda14c4a3f)
