### ISSUE TITLE
feat: Model options are way too limited (make other quants available)

### ISSUE THREAD

**Issue by Me1000** [janhq/jan#1202]
**Problem**
Jan is way too restrictive about which models I'm allowed to use. Since Jan doesn't allow for me to [pick a model I've already downloaded](https://github.com/janhq/jan/issues/1185), I'm forced to download another model. Unfortunately it looks like Jan only allows me to download 4 bit quants, but my computer is capable of most 8 bit quants.

**Success Criteria**
I should be able to download a model and choose which quantization to use. 
I should also be able to pick GGUF model files that I already have downloaded (these files are very large, there's no reason to have to download them multiple times, but that's what #1185 is about).

**Comment by 0xSage** [comment]
Hi @Me1000 You are able to import any GGUF model. Instructions are here: https://jan.ai/guides/using-models/import-manually/

Sorry for the confusion. We'll make this easier via UI soon.
