### ISSUE TITLE
bug: Jan assistant name should be changeable in `assistant.json`

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1203]
**Describe the bug**
I can't change the default assistant properties. The app always writes over any file level changes upon restart.

**To Reproduce**
1. Open `assistant.json`
2. Change `name` field from "Jan" to "Bob"
3. Save json file.
4. Quit Jan app
5. Restart

**Expected behavior**
Assistant to be renamed from Jan to Bob.

Reality: the assistant.json file is overwritten. Asssitant name is still Jan

**Screenshots**

**Desktop (please complete the following information):**
- v0.4.3
- all OSes I image

**Additional context**

**Comment by namchuai** [comment]
Issue has been fixed with #948
