### ISSUE TITLE
bug: Jan app Windows 11, failed to fetch message in thread

### ISSUE THREAD

**Issue by hiento09** [janhq/jan#1204]
**Describe the bug**
An error, "Error occurred: Failed to fetch", appears when switching between threads using different models in the Jan application Windows.

**Steps to reproduce**
1. Launch the Jan application.
2. Start a conversation in the first thread using Model A.
3. During message generation, switch to a different thread and initiate a chat.
4. Observe the error.

**Expected behavior**
The startup of the model should function smoothly, akin to its performance on macOS and Linux platforms.

**Screenshots**
![image](https://github.com/janhq/jan/assets/136591877/6691cea4-260a-4a18-8a3c-39f80a1fc04f)
![image](https://github.com/janhq/jan/assets/136591877/87a737b1-d70d-4860-928c-6d1f7443d0a5)

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.3
- Processor: AMD Ryzen 9 7950x
- RAM: 64GB
- Additional Hardware Details: One GPU 4070ti, Two GPUs 1660ti

**Additional context**
Troubleshooting revealed that the issue is related to Nitro. Below is the Nitro log captured:

``` log
"tokens_predicted":4,"truncated":false} - llamaCPP.cc:143
20231222 07:43:20.815000 UTC 41748 INFO  Resolved request for task_id:1 - llamaCPP.cc:297
20231222 07:43:20.815000 UTC 41748 DEBUG [makeHeaderString] send stream with transfer-encoding chunked - HttpResponseImpl.cc:533
20231222 07:43:25.628000 UTC 41748 INFO  reached result stop - llamaCPP.cc:335
20231222 07:43:25.628000 UTC 41748 INFO  Connection closed or buffer is null. Reset context - llamaCPP.cc:305
20231222 07:46:28.118000 UTC 23092 INFO  Resolved request for task_id:4 - llamaCPP.cc:297
20231222 07:46:28.118000 UTC 23092 DEBUG [makeHeaderString] send stream with transfer-encoding chunked - HttpResponseImpl.cc:533
20231222 07:46:29.618000 UTC 23092 FATAL Unknown error (errno=10053) send stream in loop: return on unexpected error(10053) - TcpConnectionImpl.cc:1115
```

**Comment by louis-jan** [comment]
Thanks @hiento09 for the fix 🚀

**Comment by ThomasMeli** [comment]
As of Jan 4th, 2024, getting the same error on my intel mac 27" 2017, Big Sur 11.7.10 after this bug has been considered solved.  Same steps and expected output as the original message and getting "Error occurred: Failed to fetch" when trying to use any model besides openai.  OpenAI models work fine.  Local models do not.  Thanks!

**Comment by s-haensch** [comment]
Also getting the same error as of Jan 5th 2024, using Mistral Instruct 7B Q4 model under Windows 11 Home, v10.0.22621.

**Comment by niclaserikssonkan** [comment]
Getting the same message bellow when trying to run chat on model "Mixtral 8x7B Instruct Q4" or any model...

"failed to fetch message in thread" 

iMac (Late 2014), intel mac
