### ISSUE TITLE
feat: System Monitor lets users edit engine.json settings (e.g. users can limit Jan V/RAM usage)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1206]
**Problem**
Jan should offer a settings (maybe in system monitor) to not be resource greedy:
<img width="1095" alt="image" src="https://github.com/janhq/jan/assets/69952136/66ea19a1-4bdc-46f9-aab3-b64f380e72e7">

**Success Criteria**
1. In system monitor, I can set max ram usage by Jan.
2. For all intents and purposes, that's how much RAM we detect & consume.

**Additional context**

**Comment by louis-jan** [comment]
@tikikun @Van-QA  @hiro-v I think we deprecated Resources limit settings as described here #1716. 
The issue revolves more around ngl, where users could have the ability to configure GPU layer offloading.
