### ISSUE TITLE
bug: Disable the model selection for new thread when we close or refresh Jan

### ISSUE THREAD

**Issue by TC117** [janhq/jan#1207]
**Describe the bug**

**Steps to reproduce**
Steps to reproduce the behaviour:
1. Open a new thread
2. Change name or add some context to Assistant intructions
3. Close / refresh (CTRL + R) Jan
4. Open Jan again and find the thread above
**Expected behaviour**
4. Since I not selected a model yet, I could change the model to whatever I want but in this case it got disabled

**Screenshots**
![image](https://github.com/janhq/jan/assets/19384189/8740704b-e1fb-41c7-8833-e30c732f52bf)

**Environment details**
- Operating System: Window10
- Jan Version: 0.4.3
- Processor: 10400F 
- RAM: 32 GB
- Any additional relevant hardware specifics: 

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by TC117** [comment]
![image](https://github.com/janhq/jan/assets/19384189/08ba3172-f66e-4537-bef2-a08400a1f228)
after that the chat cant be use anymore

**Comment by louis-jan** [comment]
Fixed in #1176
