### ISSUE TITLE
feat: have users explicitly specify hardware acceleration

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#1208]
**Problem**
The current way of handling hardware automatically causing a lot of edge cases and fail very often

**Success Criteria**
User can specify their hardware and hardware acceleration they want just like Jellyfin app for example.

**Additional context**
<img width="1207" alt="image" src="https://github.com/janhq/jan/assets/22268502/d6ac1334-1beb-453b-86ac-853aac2d7e0e">

**Comment by 0xSage** [comment]
@imtuyethan pls sync up with @tikikun on hwo this should work from settings. quite critical

**Comment by imtuyethan** [comment]
Duplicated https://github.com/orgs/janhq/projects/5/views/26?pane=issue&itemId=48456628
