### ISSUE TITLE
feat: Jan should support latex

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#1211]
**Problem**
Latex is very useful for scientific document and math, useful for high school or university students

Currently
<img width="550" alt="image" src="https://github.com/janhq/jan/assets/22268502/9bc3748d-3dea-4618-a5f6-dce80a169ec4">

**Success Criteria**
Can have latext rendering like below
<img width="911" alt="image" src="https://github.com/janhq/jan/assets/22268502/8f57290a-62d1-4b79-b82e-d80f20ab28be">

**Comment by imtuyethan** [comment]
Will be included in epic: https://github.com/orgs/janhq/projects/5/views/16?pane=issue&itemId=49598400

**Comment by Van-QA** [comment]
![image](https://github.com/janhq/jan/assets/64197333/3a22ea2c-fc48-4469-8a22-ee3b7c8f046d)
