### ISSUE TITLE
bug: System Monitor is lumping VRAM with RAM

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1220]
**Describe the bug**
Reported by Sabin_Stargem from r/localllama. 

- [ ] Reproduce issue
- [ ] Follow up on [r/localllama thread](https://www.reddit.com/r/LocalLLaMA/comments/18pyul4/comment/kezkxpv/?utm_source=share&utm_medium=web2x&context=3)

![Image](https://github.com/janhq/jan/assets/101145494/356e58df-fcd4-4407-b35a-94c19266f791)

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by hiento09** [comment]
Resolved in https://github.com/janhq/jan/issues/1178

**Comment by hiento09** [comment]
Re-open since I link to wrong PR, this issue is not resolved yet

**Comment by hiento09** [comment]
The system manager is showed Gibibyte while Jan app is showed Gigabyte, let me correct the converter function.

**Comment by hiento09** [comment]
Resolved https://github.com/janhq/jan/pull/1286
