### ISSUE TITLE
feat: Jan lets user choose which GPU to run Model on

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1221]
**Problem**
Feature requested by Sabin_Stargem from r/localllama
- I actually think this is a great idea, especially for multi-modal AI
- Niche feature for power users with multi-GPU setups
- UI will need to avoid overcomplicating it for "normie" users

![Image](https://github.com/janhq/jan/assets/101145494/b1301552-da77-42cd-8c96-9bd795ab7816)

**Success Criteria**

**Additional context**

**Comment by imtuyethan** [comment]
Design link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2303-39294&mode=design&t=P76QcZnZBvoxZEgk-4

cc @hiro-v @louis-jan @urmauur

**Comment by imtuyethan** [comment]
Design for review: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2303-39294&mode=design&t=8Ez5jpPsZckcQaU2-4

**Comment by imtuyethan** [comment]
This issue will be solved along with https://github.com/orgs/janhq/projects/5/views/26?pane=issue&itemId=40774459. I'll close this for now.
