### ISSUE TITLE
Discussion:   Jan's name isn't suited for SEO.

### ISSUE THREAD

**Issue by SabinStargem** [janhq/jan#1223]
I tried to find Jan in the LocalLlama Reddit, but couldn't find it.  The name is so short, that Reddit cannot search for it.    Giving a longer name to the tool might be good.

As an alternative name, perhaps "Janus" would be better?  That refers to a Roman deity.  Here is an excerpt from the Wikipedia article:

![image](https://github.com/janhq/jan/assets/38871546/c7e6efde-1b74-46d3-af48-7d98f6b6a01f)

**Comment by 0xSage** [comment]
Thanks for the suggestion! We're definitely open to renaming. 

I'm very immature so I'm not sure about `Janus` given the `index[1,4]` slice of the word  😂 

We also own the domains: `jade.ai` `phil.ai`, among others. Many possibilities!

I'm migrating all Github discussions here btw: https://github.com/janhq/jan/discussions/1270
