### ISSUE TITLE
bug: Can't access API

### ISSUE THREAD

**Issue by gboxxx** [janhq/jan#1224]
**Describe the bug**
API is not accessible at localhost:1337 as localhost refused to connect.

**Steps to reproduce**
1. Run Jan
2. curl https://localhost:1337/v1/models

**Expected behavior**
A 200 response.

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: MacOS Ventura 13.6.1 (22G313)
- Jan Version: 0.4.3 
- Processor: M2 Ultra
- RAM: 64gb

**Additional context**
Also don't see any settings for the server in Jan settings. [Local Server documentation ](https://jan.ai/guides/using-server/server/) mentions being able to change port, but I do not see any related settings.

**Comment by louis-jan** [comment]
@gboxxx The feature is in-progress, you can find the PR and its progress here #948.

**Comment by 0xSage** [comment]
@gboxxx the server should be usable now. OpenAI compatible.
Stay tuned for #1235

**Comment by gboxxx** [comment]
Awesome, thanks!
