### ISSUE TITLE
epic: Better Importing of Custom Models

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1227]
## Motivation
- Number 1 user complaint, as folks often use Jan to test out new models
- Our current `model.json` format and folder based approach has too many requirements leading to bad UX
- Impossible to use for nontechnical users

> Note: Let's use this epic to track shorter term fixes to make the app more usable. 
> See Not in Scope for long term improvements.

## Priorities

This epic can grow huge, so let's prioritize by: 

1. Support `manual import without UX` (untangle all the model.json/folder structure edge cases)
2. Support `single model import via App GUI` (simplify UX for users)
3. Support fancy things via Hub like downloading directly from HF

> Up to app pod to discuss what's in scope

## Specs & Designs
See Tasklist

## Tasklist
- [x] #1028
- [ ] #1228
- [x] #1231 
- [x] #1245 
- [x] Closing this epic automatically closes: #1039 

## Not in Scope
- #1245 engineering implementation
- #1230  (pending designs)
- #1185 
- #678 
- #328 
- #1072

**Comment by imtuyethan** [comment]
Specs should define:
- Where to import model?
- Where to see all required fields when importing model? -> model.json

**Comment by 0xSage** [comment]
This issue only tracks the engineering prereq tasks. See Not in Scope section for the UI level improvements in future sprints.

**Comment by 0xSage** [comment]
closing this epic! well done team
