### ISSUE TITLE
epic: Users can manage local API server via Dashboard

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1235]
## Motivation
- Users sometimes just want a local, OpenAI compatible endpoint, for other app integrations
- Users want to see server logs, change server settings while using this local server

## Specs

- Users can turn on/off servermode, and configure various server settings
- Users are informed through UI, that ServerMode disables other UI level features like Threads
- Users can see server logs
- Users can quickly get linked OUT & access docs 

## Designs
[Figma](https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1053-73219&mode=design&t=EhaNKZOgpQhqHBcd-0)

Preview:
<img width="1162" alt="image" src="https://github.com/janhq/jan/assets/69952136/452c116c-9d1a-4f00-8aae-f8aad078cb21">

## Tasklist
- [x] #1251 

## Not in Scope
- Users can edit model settings in servermode
- Postman like playground for users to construct requests
- Embedding api docs within the dashboard (UX antipattern)

## Appendix

Previous context:

**Model Selection:**

- As a user, I want to choose which model I want to make available at https;//localhost:1337 as an API

**Server Configuration Options:**

- As a user, I want to customize the server port to ensure compatibility with my system's setup.
- As a user, I want to manage Cross-Origin-Resource-Sharing (CORS) settings to control access permissions for security reasons.
- As a user, I want the option to enable or disable verbose server logs for effective debugging and troubleshooting.

**Examples (Request, Response, etc.):**

- As a user, I want access to clear examples of API requests and responses for better understanding and usage guidance; and if possible, a link to Jan's API docs for more details.

**Server Logs:**

- As a user, I want access to detailed and comprehensive server logs, providing in-depth information about each API request and response for thorough debugging and analysis.
- As a user, I want a dedicated section displaying API metrics, offering insights into usage statistics, response times, and other relevant performance indicators for better optimization and monitoring.

**Comment by 0xSage** [comment]
> As a user, I want to be able to run Jan headless so I don't have to set up X11 when I only want to use the API.

Ahhh I think we support headless via docker (see dockerfiles in repo). 
@hiento09 can I double check, where's the entrypoint to set this up? @hieu-jan can then update docs.

**Comment by hiento09** [comment]
@0xSage the Dockerfile was for cloudnative, which is deprecated, we haven't have offical Dockerfile for Jan server yet, let's move this to a Feature request, I will update the Dockerfile later.
