### ISSUE TITLE
epic: System Monitoring & Observability

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1236]
## Motivation
- TODO @0xSage 

## Specs
- 

## Designs
[Figma](link)

## Tasklist
- [ ] #1371 
- [ ] #1306 
- [x] #1838 

## Not in Scope
-

**Comment by 0xSage** [comment]
@imtuyethan would you mind doing a first cut of specs and adding designs here? 🙏  thank you

**Comment by imtuyethan** [comment]
Moving this epic to notion til it is confirmed.

**Comment by imtuyethan** [comment]
Moving this epic to notion til it is confirmed.
