### ISSUE TITLE
bug: failed to fetch

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1243]
![IMG_7173](https://github.com/janhq/jan/assets/89722390/7b70a77d-8fa4-40ea-9106-a0838c8e8588)

**Comment by jasobih** [comment]
have same issue with any model

**Comment by louis-jan** [comment]
related issue: #1289

**Comment by louis-jan** [comment]
related issue: #1187

**Comment by 0xSage** [comment]
How exactly are we solving this common issue @tikikun ?

Namely, are we doing: 
- Better error propagation
- What is the OS support matrix?
- From a docs perspective what needs to be documented for users to download the correct models?

**Comment by louis-jan** [comment]
Case resolved: https://discord.com/channels/1107178041848909847/1189918006978027613
Case resolved: https://discord.com/channels/1107178041848909847/1190900451353309285/1190966272742146148

**Comment by louis-jan** [comment]
Investigated: https://discord.com/channels/1107178041848909847/1190968143334617118

**Comment by louis-jan** [comment]
Hi @jasobih, regarding your case, it seems like this one #1187

**Comment by louis-jan** [comment]
Case resolved: https://discord.com/channels/1107178041848909847/1192366847446753330

**Comment by TheEdgeOfFear** [comment]
Same Issue on Mixtral 8 x 7B Instruct Q4, Latest rev of Jan.AI, Windows 11:
Error:  Same a above on chat:
Error in code:

× POST http://127.0.0.1:3928/inferences/11amaccp/chat_c index.js:2055 
completion net::ERR_CONNECTION_REFUSED
(anonymous)
Observable._trySubscribe index.js:1971
(anonymous)
errorContext index.js:1790
Observable.subscribe index.js:1956
(anonymous)
src_awaiter handleMesssageRequest index.js:2275
(anonymous)
src_awaiter handleMesssageRequest index.js:2419
(anonymous)
emit layout-e26c604d515b7785.js:421
emit layout-e26c604d515b7785.js:420
resendChatMessage 766-0ac4a7e7b205a3b7.js:313
onRegenerateClick page-a61f2038757c5661.js:2149
await in onRegenerateClick (async)
Hi 618f8807-c0370e0f59991ad5.js:209
Ni 618f8807-c0370e0f59991ad5.js:210
Oi 618f8807-c0370e0f59991ad5.js:210
Nn 618f8807-c0370e0f59991ad5.js:347
Zm 618f8807-c0370e0f59991ad5.js:348
(anonymous)
Ak 618f8807-c0370e0f59991ad5.js:259
Il 618f8807-c0370e0f59991ad5.js:261
zm 618f8807-c0370e0f59991ad5.js:304
xm 618f8807-c0370e0f59991ad5.js:351
wm 618f8807-c0370e0f59991ad5.js:325
![Uploading Screenshot 2024-01-07 191310.png…]()
