### ISSUE TITLE
feat: trouble shooting in-app

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1244]
# Problem
Problem #1
Something's amiss error or failed to fetch error

Problem #2
From @tikikun 
As hard as we try, there will always be issues with inference service in the tiniest edge case (some time upstream repo has memory leak issue or some low level issue we might not know) and the inference service will crash in the background. We will try the hardest to avoid this situation but giving user a choice to restart this process is needed to avoid them having to resort to quitting the app.
Suggestion from Alan: 
A red button to restart inference service will be useful for these edge cases.
ex:
"Restart Inference Extension"

# Solution
Standardize trouble shooting in-app for automatic trouble-shooting, let users report their problem directly & we can collect logs, clearer data for bugs 
![Image](https://github.com/janhq/jan/assets/89722390/5be9e5c9-d043-4abb-b9e2-78982cbe487e)

# Design
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2684-175159&mode=design&t=bQyiFG80Dcr1XlBm-4

![Image](https://github.com/janhq/jan/assets/89722390/e08eb477-c235-4018-8c0d-a35fa6b90243)

## Preview

![Image](https://github.com/janhq/jan/assets/89722390/29c9958e-7549-41c3-9bdd-ef4f16f95913)

![Image](https://github.com/janhq/jan/assets/89722390/3e7aece8-a953-44b8-b5eb-7b64e69b8e09)

**Comment by 0xSage** [comment]
needs info

**Comment by imtuyethan** [comment]
Users to send issues:
- Send logs (app, API, nitro)
- Custom message

**Comment by imtuyethan** [comment]
App pod approved.
