### ISSUE TITLE
Seed Hasura db in a separate step

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#126]
## Problem
- Hasura seed apply is its own container right now, with a race condition bug (discussed)
    - Long term, having a separate container script is not idempotent. 
    - Every time I start up docker compose, I re run the seed container, which is wasteful.
- Let's be specific about the purpose of this step
  - Naming is confusing, what are we actually seeding?
  - Where is the seed data?

## Ideal Flow
- Seed data should be in a seed.yaml equivalent somewhere
- Ideal flow
  1. docker compose up
  2. docker exec into the hasura container (is this step necessary?)
  3. run `seed.sh seed_data.yaml`

**Comment by louis-jan** [comment]
@hiento09 just to clarify, you added this service because the current graphql-engine is an existing image, it was not built by ourselves right (no Dockerfile)?

**Comment by louis-jan** [comment]
@hiento09 @0xSage I'm moving the data seed scripts to PostgreSQL's initialization process. This is a native data seeding practice and only runs once when the database is initialized (recommended).

https://dev.to/karanpratapsingh/seeding-postgres-with-docker-19n7

**Comment by 0xSage** [comment]
beautiful - sgtm
