### ISSUE TITLE
bug: Mac - Jan quit unexpectedly on after force quit

### ISSUE THREAD

**Issue by sr-albert** [janhq/jan#1264]
**Steps to reproduce** 
![CleanShot 2023-12-30 at 22 53 13](https://github.com/janhq/jan/assets/41714564/ac58adb9-9410-441e-8c5e-4afc0a899da9)

**Expected behavior**
Nothing must be displayed

**Environment details**
- Operating System: MacOS Sonoma 14.2.1
- Jan Version: 0.4.3
- Processor: Apple M2 Pro
- RAM: 32GB
- Any additional relevant hardware specifics: Apple Silicon

**Log file**
[error-log.txt](https://github.com/janhq/jan/files/13798527/error-log.txt)

**Comment by 0xSage** [comment]
Thank you for the well articulated bug report. We'll address is as soon as we can 🙏

**Comment by hiento09** [comment]
https://stackoverflow.com/questions/68750716/electron-app-throwing-quit-unexpectedly-error-message-on-mac-when-quitting-the-a
