### ISSUE TITLE
Clean up logs for `data-connector-agent` and `graphql-engine`

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#127]
## Problem
- Right now there's are too many low level logs from
  - `jan-data-connector-agent-1` `io.opentelemetry.exporter: failed to export spans` 
  - `jan-graphql-engine-1` `/healthz`

See: [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaitEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--faad49c3e31339144a0e2fdd85255c22602727f3/Screenshot%202023-09-10%20at%209.37.46%20PM.png)
- Hard to see Jan Web service is ready

## Success Criteria
- Reduce or turn off these logs

**Comment by louis-jan** [comment]
- That's not an installation step; you are spinning up Docker containers.
- That's not how docker-compose up should be executed. You should not observe the `docker compose up` foreground logs; detached mode is recommended. A good practice for observing Docker logs is to monitor the status of services and inspect the log of one service at a time (choose the service you want to inspect).
- Log severity should be configured for each service in the docker-compose.yaml file

**Comment by dan-jan** [comment]
Hmm, that makes sense. We should probably recommend the `-d` flag in docs. 

I do think we can deprecate this story if: 

- `docker compose up` becomes a very fast process (i.e. decouple seeding process #126)
- Reduce the amount of `telemetry` and `healthz` logs (especially once we start piping it to ELK in prod instructions)

**Comment by 0xSage** [comment]
Rephrased the task. 

Can we suppress these logs in the containers themselves.
