### ISSUE TITLE
feat: Jan's chat box should allow users to scroll

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1276]
**Problem**
When users input a lot of text, the app doesn't have a scroll for users to navigate through the input

**Success Criteria**
The chatbox should have a scroll bar allowing users to scroll

**Additional context**
Image of Jan when users input long text

![image](https://github.com/janhq/jan/assets/64120343/6cb29794-9489-409e-9462-f470057c2031)

**Comment by hahuyhoang411** [comment]
^ When I want to navigate the the end of my input, I have to use the keyboard which is quite uncomfortable

**Comment by Vijaykv5** [comment]
I would love to work on this issue, if you could add some more info towards it
