### ISSUE TITLE
docs: the developer docs quick link is broken

### ISSUE THREAD

**Issue by Gri-ffin** [janhq/jan#1279]
**Pages**
- README.md

**Success Criteria**
the link should redirect to an existing page.

**Additional context**
When clicking the developer docs link in the Quicklinks section in the README.md, the link redirect to a non existing page with url [https://jan.ai/docs/extensions/](https://jan.ai/docs/extensions/).

**Comment by hieu-jan** [comment]
Hi @Gri-ffin thank you so much for your report this issue. I will update the README.md asap. Temporary, you can access the Developer docs via https://jan.ai/developer/

**Comment by sobkiso** [comment]
https://redccshop.mysellix.io/product/xchkrobot-source-code
