### ISSUE TITLE
bug: Error occurred: Failed to fetch - Model: Wizard Coder Python 13B Q5

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#1289]
**Describe the bug**

**Steps to reproduce**
1.  Download the model Wizard Coder Python 13B Q5 in the Model Hub
2. Start the model and start the conversation

**Expected behavior**
The thread should work normally with model Wizard Coder Python 13B Q5

**Screenshots**
If applicable, add screenshots to help explain your issue.

![image](https://github.com/janhq/jan/assets/150573299/86df7a4d-aadb-4cea-ac72-8f12e4da589e)

![image](https://github.com/janhq/jan/assets/150573299/f4a04d66-36d5-4362-a424-0e0bd296d8e8)

**Environment details**
- Operating System: Windows
- Jan Version: 0.4.3
- Processor: AMD Ryzen 5 4600H 
- RAM: 16GB
- Any additional relevant hardware specifics: GTX 1650 4gb

**Additional context**

**Comment by hmorneau** [comment]
it's working on a M1 Max with 64GB but not on a M1 Max 32GB, so I guess you need minimum 64GB ram for larger model.

**Comment by hieu-jan** [comment]
User can run normally via using the nightly build.

**Comment by pbeens** [comment]
Same issue with Wizard Coder Python 13B Q5. 

Error occurred: Failed to fetch

16 GB on Mac Mini M1. MacOS Sonoma 14.2 (23C64). 

Also tried nightly build jan-mac-arm64-0.4.3-126 with no luck.
