### ISSUE TITLE
feat: recommend models to first-time users

### ISSUE THREAD

**Issue by hamirmahal** [janhq/jan#1300]
**Problem**
People new to open-source models may be overwhelmed by the amount of options available when using this for the first time.

**Success Criteria**
There is at least 1 recommended model for new users.

**Comment by 0xSage** [comment]
In progress. Tracking via #1205 

sneakpeak

<img width="986" alt="image" src="https://github.com/janhq/jan/assets/69952136/3ed1ef8f-c5b2-4eef-a505-1c779429c67e">
