### ISSUE TITLE
bug: app forced me to update twice

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1303]
**Describe the bug**
App forced me to update twice:

https://github.com/janhq/jan/assets/89722390/a6d76686-7227-4301-94f8-d0b783a7cd1f

**Steps to reproduce**
1. Open Jan App
2. It prompts to update
3. Click update

**Expected behavior**
Should update once.

**Environment details**
- Operating System: MacOS Sonoma 14.2.1
- Jan Version: v0.4.3-117
- Processor: M2
- RAM: 16GB

**Comment by louis-jan** [comment]
@imtuyethan its weird since you see the restart option immediately after clicked download option. Have you interrupted it before? I mean quit app even its downloading.
