### ISSUE TITLE
refactor: reduce electron IPCs dependencies

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1308]
**Problem**
There are so many APIs exposed via IPC, that will cost more requests and duplicated code. What could be resolved from the app frontend should be covered by the frontend. E.g.
- set dark / light theme
- app version
- ...

**Success Criteria**
- Reduce IPC handlers and update core APIs by removing irrelevant requests

**Additional context**
This will enhance the web version since there might be so many requests over the internet. Also easier to scale to another host platform.

**Comment by 0xSage** [comment]
outdated
