### ISSUE TITLE
bug: only show `message queue` when users try to enter the 2nd message while the model is loading

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1312]
Only show `message queue` when users try to enter the 2nd message while the model is loading. 

**Current Problem:** 
Right now it show `message queue` whenever I start a new thread with an inactive model, which means the current UX:
- I create new threads -> choose an inactive model
- Send the first message -> show `message queue`

https://github.com/janhq/jan/assets/89722390/0aa72d33-d8fa-46ce-a75b-30b9da82125b

**But the original UX design is:**
- User enter the first message -> starting model
- User try to enter the second message while the model is starting -> show `message queue` 
<img width="874" alt="Screenshot 2024-01-03 at 4 40 35 PM" src="https://github.com/janhq/jan/assets/89722390/825b8ec4-3fc2-4498-a28d-6a3f3371a29b">
<img width="876" alt="Screenshot 2024-01-03 at 4 40 40 PM" src="https://github.com/janhq/jan/assets/89722390/188fece9-0ec9-42c5-8245-f3c3c01cc93e">

So, it should only show when i try to send the **second message** while the model is starting, not the first message.

**Comment by imtuyethan** [comment]
Let's simplify it:
- Remove that message queued
- Type 1st message -> send -> model start -> type 2nd message while model is starting -> cant send

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-273 ✅
Users can no longer send the 2nd msg while the model is loading

![Image](https://github.com/janhq/jan/assets/64197333/83574535-ba1b-4edd-8a9a-018cecfb30bf)
