### ISSUE TITLE
feat: update footer with social icon & update footer component (font size/weight/... with different stages)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1315]
## Problem
- A good suggestion was raised in https://github.com/janhq/jan/pull/1295 that we should add social icons to our app. Let's bring the social to the footer as it matches the app style better, and also the current footer design is not up-to-date, let's update it as well. 
- The current font size & weight is too small & hard to see
<img width="1287" alt="Screenshot 2024-01-03 at 6 09 05 PM" src="https://github.com/janhq/jan/assets/89722390/f1801bac-ebc6-4054-99c9-2457efb62cf5">

 

## Design
Figma: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1-22887&mode=design&t=xl0YyiAOLRICac5p-4

<img width="954" alt="Screenshot 2024-01-03 at 6 11 36 PM" src="https://github.com/janhq/jan/assets/89722390/443aed22-e947-431f-9a26-adb967deaccc">

**List of changes need to be done:** 
- [x]  #1323
- [ ] #1333

**Comment by 0xSage** [comment]
This spec is well written, thank you @imtuyethan
