### ISSUE TITLE
feat: allow users to create multiple threads at the same time as long as these threads have settings changes

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1316]
**Problem**
Based on user feedback, we better allow users to spam thread creation a bit, meaning they can create many new threads at the same time. 

**Success Criteria**
- We should allow that for users who want to customize their many threads before using.
- It does not mean we will throw away the thread finalization check as soon as the user creates a new thread, but allow them to create a new one once any settings change with the current just-created thread.

**Comment by 0xSage** [comment]
This was done, at least in nightly 121
