### ISSUE TITLE
bug: All models respond with junk characters

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1318]
**Describe the bug**
![image](https://github.com/janhq/jan/assets/69952136/0fc883b7-4e7c-45c7-83c2-d682abd9adb1)
![image](https://github.com/janhq/jan/assets/69952136/4dad03d9-97d7-41ec-b376-0d954181a70d)

- On both releases and nightly 113. 
- Across trinity, tinyllama, mistral
- User comp: M1 Pro 32GB
- v0.4.3 

I was not able to reproduce on a fresh install.

**Comment by dbartokthomas** [comment]
I'm the user experiencing this - happy to provide any extra information possible!

**Comment by 0xSage** [comment]
> I'm the user experiencing this - happy to provide any extra information possible!

Can you try updating to the latest OS? @tikikun is suggesting it might be a Metal Lib issue

**Comment by dbartokthomas** [comment]
I'm now running 14.2.1 (23C71), was on 14.0 previously. Downloaded fresh models, same issue.

**Comment by dbartokthomas** [comment]
It works!! Combination of the upgrade and a complete clean (https://jan.ai/troubleshooting/stuck-on-broken-build/).

It now generates terrible jokes for me. Thanks all.

**Comment by 0xSage** [comment]
> It works!! Combination of the upgrade and a complete clean (https://jan.ai/troubleshooting/stuck-on-broken-build/).
> 
> It now generates terrible jokes for me. Thanks all.

Yayy, if you like Jan after using it for a bit. Could I possibly as you to add what you did to fix the issue to our  (https://jan.ai/troubleshooting/stuck-on-broken-build/)?

Thank you and no worries if not! We'll try to get to it soon

Also... Why did the tomato turn red?
