### ISSUE TITLE
bug: app getting stuck at downloading 99% while downloading model

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1319]
**Describe the bug**
![293934611-b249dc7d-8dc1-4f45-b315-9823fb504c6e](https://github.com/janhq/jan/assets/133622055/fb649e01-d9cb-460d-baa8-ec87fc0d3eeb)

**Steps to reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.
![293934611-b249dc7d-8dc1-4f45-b315-9823fb504c6e](https://github.com/janhq/jan/assets/133622055/fb649e01-d9cb-460d-baa8-ec87fc0d3eeb)

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.1.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by 0xSage** [comment]
Didn't experience this issue on v0.4.3-118, on Mac M1 16gb Sonoma 14.
