### ISSUE TITLE
bug: Links open inside Jan

### ISSUE THREAD

**Issue by dbartokthomas** [janhq/jan#1321]
**Describe the bug**
When a response in a model provides a link, clicking on that link then opens it within Jan, instead of using my default browser.

**Steps to reproduce**
1. Create new thread
2. Ask 'give me the link to google'
3. Click the link provided
4. See google.com inside Jan

**Expected behavior**
I expect Jan to use my local default web browser to open the link with

**Screenshots**
Screenshots showing thread and what Google looks like inside Jan :)
![Screenshot 2024-01-03 at 23 22 31](https://github.com/janhq/jan/assets/912985/5479e893-eb7c-4b33-9e83-9906fb289b4c)
![Screenshot 2024-01-03 at 23 22 41](https://github.com/janhq/jan/assets/912985/1cfbecba-832c-44cf-b0c6-981c9f516a8f)

**Environment details**
- Operating System: MacOS Sonoma 14.2.1
- Jan Version: 0.4.3
- Processor: M1 Pro
- RAM: 32gb

**Comment by louis-jan** [comment]
Thanks for reporting the issue @dbartokthomas, its very detailed! 💯
