### ISSUE TITLE
docs: teams page

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1328]
**Pages**
- https://jan.ai/team

**Success Criteria**
Content that should be covered
- A Board of Directors page, with photos of all of our pets.
- And then maybe a screenshot of our Github contributions page or something for the actual humans - not important.
- Use template: https://docusaurus.io/community/team

Example:
![MamaCat (CMO)](https://github.com/janhq/jan/assets/69952136/834f5e4b-bea5-4da2-bdce-59deae611e24)
Chief Meow Officer

![Dobby (CCO)](https://github.com/janhq/jan/assets/69952136/3e27c1dc-2c74-41f1-bad6-3e3257df4abf)
Chief Cuddles Officer

@imtuyethan 's hamster
@Diane0111 's cat
etc.

**Additional context**
Examples, reference pages, resources

**Comment by 0xgokuz** [comment]
Would love to take this 😂

**Comment by 0xSage** [comment]
> Would love to take this 😂

Prob only @Diane0111 can do this one bc ppl are DMing her pet photos. Can I ask you to lend your technical skillz on dev docs? No pressure btw, please dont feel pressured to keep writing docs. It can get exhausting

**Comment by 0xgokuz** [comment]
Absolutely. What do you need to do? @0xSage

**Comment by 0xSage** [comment]
Closing this, its not important
