### ISSUE TITLE
feat: Make default directory configurable

### ISSUE THREAD

**Issue by Helge666** [janhq/jan#1334]
**Problem**
I have a 1TB ssd to boot the system, and an 8TB ssd for large files like models. I suppose similar setups are pretty common.

But on Windows, the app absolutely insists to reside on C:
Even when moving it manually to D: after installation, it'll re-create it's folders on C: again upon next start.
The option to open the model folder doesn't remember the desired folder either.

I deleted the app for the time being, because I allow only software that I absolutely cannot live without to remain on C:

**Success Criteria**
Please make the default folder configurable on installation, or at least, make the models folder configurable.

**Comment by Jexxes** [comment]
Same issue. Got a 250GB SSD and a 2TB one and I really would love to just be able to change install location.

**Comment by WebAtelier47** [comment]
Yes, this will be very useful and necessary.

**Comment by pbeens** [comment]
+1 to this. I was especially disappointed to see that I couldn't download the models to somewhere else. Even if just that could be done in the interim if allowing the default program location to be somewhere else isn't easy, it would be great.

**Comment by 0xSage** [comment]
Yes, we're prioritizing this in #1010 
And also in #1381

**Comment by YoLolo69** [comment]
+1, my C: Win11 SSD of only 128GB will thanks you.

**Comment by imtuyethan** [comment]
@xvsd Yes the team is working on it, please stay tuned for the change

**Comment by imtuyethan** [comment]
I will close this issue as duplicated issue, please see the progress here: https://github.com/janhq/jan/issues/1010
