### ISSUE TITLE
Bug: Duplicate threads created by clicking new thread button many times

### ISSUE THREAD

**Issue by TC117** [janhq/jan#1336]
**Describe the bug**
Click new thread button many times will create some duplicate threads 

**Expected behavior**
Should add some delay time for thread creation? 

**Screenshots**
[threads.webm](https://github.com/janhq/jan/assets/19384189/53b12a95-bd3d-4cf5-aace-441a524021ef)

**Environment details**
- Operating System: Win10
- Jan Version: 0.4.3-118

**Comment by namchuai** [comment]
This issue has been fixed with PR #1538 . Please help to verify it. Thank you!
