### ISSUE TITLE
bug: Installing gets blocked by bitdefender (suspicious app)

### ISSUE THREAD

**Issue by imqqmi** [janhq/jan#1343]
**Describe the bug**
When I install jan.ai on windows with bitdefender installed, the application pops up for a second then shuts down. Bitdefender says it's an application with suspicious activity. It also blocks '90 related apps' one of which was firefox and couldn't load a webpage from then on. After reinstalling firefox I got that working again. Not sure if other apps are malfunctioning. 

**Steps to reproduce**
1. Download installer (jan.ai)
2. Run installer on Windows 10

**Expected behavior**
It should install without bitdefender complaining about suspicious activity. 

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: Windows 10
- Jan Version: 0.4.3
- Processor: 13900K
- RAM: 32GB

**Comment by 0xSage** [comment]
@hiento09 does the latest build fix this issue? Pls close this ticket if so!
The fix will be rolled out in an upcoming release

**Comment by hiento09** [comment]
yes @0xSage, this bug is fixed in the latest nightly build
