### ISSUE TITLE
bug: powershell spam on windows.

### ISSUE THREAD

**Issue by TashaSkyUp** [janhq/jan#1349]
**Describe the bug**
powershell is being ran and terminating many many many times while inference is happening.

**Steps to reproduce**
install wizard coder python 13b Q5
have a conversation
look at task manager in windows while it is inferring
actually looks like its happening even when its not inferring.

**Expected behavior**
Jan should not be running powershell scripts for no good reason in the background repeatedly.over and over.. endlessly

**Screenshots**
![image](https://github.com/janhq/jan/assets/15312630/8fc40022-59da-433c-ad24-93e8e660f0b7)

**Environment details**
- Operating System: windows 10
- Jan Version:  0.4.3
- Processor: amd 3900x nvidia 3090
- RAM: 96/24

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by TashaSkyUp** [comment]
![image](https://github.com/janhq/jan/assets/15312630/1965ef76-de61-4444-a0e1-ce850a153b6d)

**Comment by 0xSage** [comment]
Do we have a process that uses powershell @hiento09 ?

**Comment by hiento09** [comment]
Yes, @0xSage , we fixed this in the latest nightly build, version 0.4.3 which is the latest release now still has this bug

**Comment by hiento09** [comment]
Will be fixed in version 0.4.4, you can try the nightly build (URL in our README.md file) to check it out
