### ISSUE TITLE
bug: Nvidia GPU's not being used on windows.

### ISSUE THREAD

**Issue by TashaSkyUp** [janhq/jan#1350]
**Describe the bug**
I have a 970 and a 3090 installed on my system, but Jan decides to use CPU mode.

**Steps to reproduce**

**Expected behavior**
Jan should use cuda device 0 or allow me to choose which model goes on which device

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: windows 10
- Jan Version: 0.4.3
- Processor: amd 3900x
- RAM: 96gb
- 970 4gb, 3090 24gb

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by DutchyDutch** [comment]
Same here!

Windows 11 pro
RTX 4080 (16 GB)
32 gigs ram.

CPU is at 83% while the GPU flatlines at 0%

I am sure it's user error but there is no obvious way that I can find to correct this.

Very much appreciate time spend to clear this up!

**Comment by bfritscher** [comment]
I had to install cuda toolkit and use the experimental build of Jan to make it work.
This guide heped https://github.com/janhq/jan/blob/main/USAGE.md

**Comment by 0xSage** [comment]
Yeah you gotta install Cuda, bc the app doesn't have permission to do this. 

Btw, our new nightly build auto-prompts you to do this important step.
