### ISSUE TITLE
feat: full chat editing

### ISSUE THREAD

**Issue by TashaSkyUp** [janhq/jan#1352]
**Problem**
lack of simple way to direct model, beyond prompting.

**Success Criteria**
the user should be able to modify the chat history records of the assistant and the user.

**Additional context**
allowing this is very useful.

**Comment by 0xSage** [comment]
Ah you can already do this: 

https://jan.ai/guides/chatting/manage-history/

Context: 

https://jan.ai/developer/file-based/

**Comment by TashaSkyUp** [comment]
I mean, I guess value/work proposition is considered to low. 0% chance of me editing the json file in an external program. I'll just use a different llm front end. But if this is part of the actual Jan UI then it stays more competitive with the openai playground
