### ISSUE TITLE
feat: Simple WebGUI for chat

### ISSUE THREAD

**Issue by tronba** [janhq/jan#1355]
**Problem**
I would love for others in my household to chat with my Jan install using a simple WebGUI.

**Success Criteria**
A simple WebGUI to chat with the same model as is loaded in the client GUI.
WebGUI should preferably not have any controls (be able to change config, download, or select model).
WebGUI should show what model is loaded.
WebGUI feature should be able to turn on/off in client GUI.
WebGUI port should be possible to change in client GUI.
WebGUI chat history should not be visible to others and not shown in client GUI.
The client would have to deal with the possibility of multiple simultaneous chats, maybe possible to do with a timeslot or waitlist system?

**Comment by 0xSage** [comment]
Is this what you have in mind? https://jan.ai/guides/using-models/integrate-with-remote-server/

At the moment, we dont handle concurrent users very well. It could still work.. but you'll see everyone's chat in your own server...

Feel free to fork the repo and customize this though!
