### ISSUE TITLE
bug: App launches on Mac OSX M1, but fails to start

### ISSUE THREAD

**Issue by beergeekdotcom** [janhq/jan#1356]
**Describe the bug**
Blank window is all that shows up -- looking at the console, there's an error listed:

Uncaught (in promise) Error: Error invoking remote method 'installExtension': Error: Package /Applications/Jan.app/Contents/Resources/app.asar.unpacked/pre-install/janhq-assistant-extension-1.0.0.tgz does not contain a valid manifest: Error: EACCES: permission denied, mkdtemp 

**Steps to reproduce**
1. Install app from DMG
2. Launch app

**Expected behavior**
Interface should launch

**Screenshots**
It's a blank window.

**Environment details**
- Operating System: Mac OSX 14.2.1, Mac M1
- Jan Version: 0.4.3, 0.4.2
- Processor: M1
- RAM: 8GB
- Any additional relevant hardware specifics: MacBook Air

**Additional context**
Have a great day!

**Comment by hiento09** [comment]
Hi @beergeekdotcom , could you please try our nightly build version available at this link: https://github.com/janhq/jan?tab=readme-ov-file#download, to check if it resolves the issue? Thank you.

**Comment by beergeekdotcom** [comment]
Did not seem to resolve it - but errors are different:

xxx/decide/?v=3&ip=1&_=1704645732182&ver=1.96.1:1 
Failed to load resource: net::ERR_FILE_NOT_FOUND

layout-dd157c14184b7a88.js:542
Uncaught (in promise) Error: Error invoking remote method 'installExtension': Error: Package /Applications/Jan.app/Contents/Resources/app.asar.unpacked/pre-install/janhq-assistant-extension-1.0.0.tgz does not contain a valid manifest: Error: EACCES: permission denied, mkdtemp '/Users/XXX/.npm/_cacache/tmp/61ZIDA'

51-d008b48ecfe94f3e.js:11 
POST file:///Applications/Jan.app/Contents/Resources/app.asar/renderer/xxx/e/?ip=1&_=1704645735269&ver=1.96.1 net::ERR_FILE_NOT_FOUND
(repeats)

**Comment by beergeekdotcom** [comment]
Update -- I deleted the $USER/.npm/_cacache directory and reloaded Jan and it worked.  Still lots of errors in the console, but the front end loads.
