### ISSUE TITLE
bug: Reveal in Finder (PC) "/" vs "\"

### ISSUE THREAD

**Issue by pbeens** [janhq/jan#1357]
**Describe the bug**
When you click on "Reveal in Finder" for a thread, the path name is not correct on PCs. Example: C:\Users\Peter\jan/threads/jan_1704400975

**Steps to reproduce**
1. Go to Thread menu
2. Click on 'Revel in Finder'
3. Error: Windows cannot find 'C:\Users\Peter\jan/threads/jan_1704400975'. Make sure you typed the name correctly, and then try again.

**Expected behavior**
The Windows file manager should open. 

**Screenshots**
<img width="419" alt="2024-01-04-jan ai json-error" src="https://github.com/janhq/jan/assets/1952535/afcb6639-7e9b-4a50-b5b1-475e77ba6987">

**Environment details**
Device name	XPS-8950
Processor	12th Gen Intel(R) Core(TM) i7-12700   2.10 GHz
Installed RAM	64.0 GB (63.7 GB usable)
System type	64-bit operating system, x64-based processor
Edition	Windows 11 Home
Version	22H2
Installed on	‎2023-‎04-‎05
OS build	22621.2861
Experience	Windows Feature Experience Pack 1000.22681.1000.0

**Additional context**
This should be a simple fix by detecting if the program is being run on a PC or Mac/Linux and changing the path separator.

**Comment by hiento09** [comment]
This bug is fixed, you can check it out in version 0.4.4 (up-comming) or in the latest nightly build version in our README.md file

**Comment by pbeens** [comment]
> This bug is fixed, you can check it out in version 0.4.4 (up-comming) or in the latest nightly build version in our README.md file

I can confirm that this is fixed in jan-win-x64-0.4.3-125. Thank you!
