### ISSUE TITLE
feat: my models: model management

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1363]
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1744-85800&mode=design&t=TJxinYINx8tpYTo3-4

**Comment by 0xSage** [comment]
@imtuyethan what is this issue? Can you elaborate a bit? Or just a draft and I should ignore it for now? ty

**Comment by imtuyethan** [comment]
@0xSage I broke down the user stories for My model page, this ticket is one of the user story where users are able to manage their model (start, stop, delete,...)
