### ISSUE TITLE
bug: very large prompts cause nitro to hang

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1366]
**Describe the bug**

![image](https://github.com/janhq/jan/assets/54515725/c69e3166-11ee-4adb-9ba6-2f116c9016be)
stopping the execution fails (note CPU load remains 100%)
![image](https://github.com/janhq/jan/assets/54515725/e672d600-1b39-421c-8fbe-6db7b92deef7)
subsequent threads broken
![image](https://github.com/janhq/jan/assets/54515725/69596b69-5062-46ec-920c-5d103ff8bc04)
opening a new thread remains broken regardless of model choice
![image](https://github.com/janhq/jan/assets/54515725/5bea873a-c405-4591-8422-e598a08b9bf0)
![image](https://github.com/janhq/jan/assets/54515725/33241df3-5c68-49a3-aba4-af361a821844)
![image](https://github.com/janhq/jan/assets/54515725/7f9fd4a6-d677-480b-823c-0958ef6397fc)
![image](https://github.com/janhq/jan/assets/54515725/eb186c6d-32a4-4f23-b695-94ba761b26f8)
![image](https://github.com/janhq/jan/assets/54515725/86d3a362-83e9-456a-a779-b82688190bf2)
restarting the app fails to clear the issue
![image](https://github.com/janhq/jan/assets/54515725/af56e8ba-8a12-470e-b797-c4f6ad2c2b9c)
![image](https://github.com/janhq/jan/assets/54515725/3e894811-4867-49f1-8c20-125fff895354)
deleting all threads then restarting clears the issue
![image](https://github.com/janhq/jan/assets/54515725/8c3f460a-4a16-4a32-9dc6-4931dfbb61f6)

**Steps to reproduce**
see above

**Expected behavior**
Jan should either not allow large inputs or warn about risk. If app crashes this way user should be prompted to back up threads and clear folder.

**Screenshots**
see above

**Environment details**
- Operating System: Ubuntu 22.04.01
- Jan Version: 0.4.3-118
- Processor: Intel® Core™ i5-2520M CPU @ 2.50GHz × 4
- RAM: 16GB

**Comment by tikikun** [comment]
This is a purely performance issue. We can try to mitigate this with some warning @imtuyethan
