### ISSUE TITLE
feat: folder functions in threads

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1367]
**Problem**
Can only delete threads individually now.

**Success Criteria**
Would like to delete multiple threads at once.

**Additional context**
None.

**Comment by 0xSage** [comment]
cc @hieu-jan we also need docs teaching users how to clear thread history directly via folder

**Comment by hwc0x01** [comment]
Thanks, I've been doing that but this feat req is for convenience and more basic users.

**Comment by 0xSage** [comment]
> Thanks, I've been doing that but this feat req is for convenience and more basic users.

For sure! Keeping this issue open to track new designs for this feat

**Comment by imtuyethan** [comment]
deprecated
