### ISSUE TITLE
bug: if a model returns a url in a response and user clicks it opens in the window that renders jan

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1368]
**Describe the bug**
prompt came back with url, if user left clicks it opens in the jan window and you can't get back. ctrl+click opens a new child browser window.

**Steps to reproduce**
see above

**Expected behavior**
ideally should either open in default system browser. if not should open by default in child window or tab (if tabs are possible).

**Comment by urmauur** [comment]
@pbeens @hwc0x01 thanks for your suggestion, actually we already fix this one by @namchuai, i just improve the link color and hover with underline for better readability user

**Comment by urmauur** [comment]
hi @pbeens @hwc0x01 thank you for suggestion, @namchuai already fix open in default system browser, and i just update UI/UX make the color blue and hover underline so better readability for user
