### ISSUE TITLE
feat: Jan application reload button

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1369]
**Problem**
Jan UI should have a reload model button for people like me who constantly break stuff -- opening a new thread with the same model doesn't reload it so whatever got messed up stays messed up

**Success Criteria**
A button to reload.

**Comment by 0xSage** [comment]
Related: #837
Sort of related: #1052

**Comment by 0xSage** [comment]
control r reloads. We will not provide a separate UI component for this.
