### ISSUE TITLE
epic: ability to point jan to a remote nitro instance (eg I want to run one on baba cloud)

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1370]
## Motivation
Would allow users to host own nitro in cloud and run certain larger/more resource intensive models/tasks. 

## Specs
Duplicate the chatgpt api call to call nitro instance in cloud 

## Designs
just an addition to the model selection drop down?

**Comment by hwc0x01** [comment]
@tikikun tagged because I was told you already do this

**Comment by 0xSage** [comment]
Yep, steps: 
1. https://nitro.jan.ai/docs
2. Point Jan client to this remote server: https://jan.ai/guides/using-models/integrate-with-remote-server/
