### ISSUE TITLE
feat: TPS Report generator (tokens per second)

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1371]
**Problem**
Would be nice to have a history/analytics of tokens/sec performance across all runs in jan over time. Should be called TPS Report because everyone loves office space.

**Comment by 0xSage** [comment]
Can you elaborate? 

What is the main insight here? How fast certain models are? Or to find out about something else?

We can incorporate more metrics in our latest System Monitor designs: 
<img width="796" alt="image" src="https://github.com/janhq/jan/assets/69952136/f1d95d60-fddc-4bf5-8cf0-2dac8a503919">

**Comment by hwc0x01** [comment]
Goals:

1. Compare models vs other models on same prompt/assistant instruction 
2. Compare prompts vs other prompts
3. Compare assistant instructions
4. Jan internal: track any performance improvement/degradation with new versions of Jan/nitro

**Comment by 0xgokuz** [comment]
@0xSage I presume this would be dependent on the implementation of the latest system monitoring design?

**Comment by hwc0x01** [comment]
It would be a great pun if you actually called it a "TPS Report" 🙏

**Comment by imtuyethan** [comment]
Moving this epic to Notion til it is confirmed: https://www.notion.so/jan-ai/System-monitor-Observability-5005bb241cdb4f94a524d20ca049b93a?pvs=4
