### ISSUE TITLE
bug: handle edge case where model folder has json but not binary

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1375]
**Describe the bug**
when model is missing from model folder but json exists jan ui says model active while nitro doesn't load the model, leads to confusing fail to fetch. 

user trying to run a model downloaded from hugging face, made a json but forgot to copy into proper folder. jan ui said model loaded but nitro couldn't find it.

**Steps to reproduce**
See above.

**Expected behavior**
A reminder to the user to copy the model into the folder would be best. 

**Environment details**
- Operating System:windows 10
- Jan Version: Jan v0.4.3-121

**Additional context**
basic check of file size would be good in case the download was busted prompting user to redownload or for jan to automatically re-download from json source address

**Comment by louis-jan** [comment]
We'd address the case in #1430, nitro will emit a proper message to let user know the clearer error message.

**Comment by louis-jan** [comment]
cc @Van-QA for following up.

**Comment by louis-jan** [comment]
We have updated the model lookup mechanism, model.json "state: ready" is deprecated, app would display correct state if the GGUF model is placed accordingly now.
