### ISSUE TITLE
bug: chat reply goes off screen (UI bug)

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1377]
**Describe the bug**
![image](https://github.com/janhq/jan/assets/54515725/933c239b-2ab0-45ad-938a-d26ffbcfadf1)

**Steps to reproduce**
seems to only happen with deepseek coder for now

**Expected behavior**
expected to see text sized properly or a properly formed scroll bar. Scroll bar pops up nicer when right panel is up. 
![image](https://github.com/janhq/jan/assets/54515725/9a1a2959-b985-43fa-9eb0-5662e4fe2b0c)

**Comment by mishrababhishek** [comment]
Can i work on this issue

**Comment by mishrababhishek** [comment]
This is my first open source contribution  hope everything goes well
