### ISSUE TITLE
question: can jan deploy on docker?

### ISSUE THREAD

**Issue by geosmart** [janhq/jan#1397]
## Motivation
I want to deploy jan on my nas server,export jan as a web service, rather than a desktop app

## Specs
- 

## Designs
[Figma](link)

## Tasklist
- [ ] 

## Not in Scope
-

**Comment by 0xSage** [comment]
Yes, it does. https://github.com/janhq/jan/blob/main/Dockerfile

I'd do a quick repo search for Dockerfiles. cmiiw @hiento09 the ui client might also run in docker...

If you get it to work @geosmart , would you mind briefly summarizing the steps here? We'll convert it into docs :)

**Comment by mogwai** [comment]
I would be nice if you could run this remotely on a server with beefy hardware and then access it through ssh port forwarding on your laptops browser.

**Comment by 0xSage** [comment]
> I would be nice if you could run this remotely on a server with beefy hardware and then access it through ssh port forwarding on your laptops browser.

Ah that's supported: 
1. https://jan.ai/guides/using-server/server/
2. https://jan.ai/guides/using-models/integrate-with-remote-server/
