### ISSUE TITLE
feat: Make chat (left) sidebar collapsible

### ISSUE THREAD

**Issue by leitdeux** [janhq/jan#1404]
**Problem**
Always having the left sidebar open leaves less room on vertically-rotated monitors and possibly laptop screens with lower resolutions. Also, it provides more "focus" to the current conversation-- users may not need to have a list of other threads displayed to the left of the main conversation all the time.

**Success Criteria**
The left sidebar (just like the right) should be collapsible with a button found in the navbar.

**Additional context**
Thanks!

**Comment by namchuai** [comment]
@leitdeux , please using command/ctrl + b for toggle left side bar.

**Comment by leitdeux** [comment]
@namchuai Thank you for implementing this so quickly! It's working wonderfully.
