### ISSUE TITLE
feat: users are able to stop LLM responses mid flight

### ISSUE THREAD

**Issue by drakehere** [janhq/jan#141]
**Problem:** 
- Sometimes you just want to stop a long LLM response

**Success Criteria:** 
1. User sends an inference request
2. While LLM is responding
3. User can click `stop` and have LLM responses halt

**Comment by 0xSage** [comment]
Similarly @drakehere please add more description/spec/mocks to this task, if any

**Comment by tikikun** [comment]
Done
