### ISSUE TITLE
feat: nitro hibernation/model unload after X time

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1412]
**Problem**
if a user has jan open but hasn't used it in a bit it's still hogging system RAM. since model loads are super fast nitro may want to unload the model after a period of no use.

**Success Criteria**
new settings option to unload model after a certain sleep time or just a default sleep time.

**Additional context**
nice to have

**Comment by tikikun** [comment]
This should be on nitro inference plugin level

**Comment by hwc0x01** [comment]
Should I post this issue in the nitro GitHub instead?

**Comment by imtuyethan** [comment]
This is related to epic: #1714

**Comment by louis-jan** [comment]
Great one
