### ISSUE TITLE
bug: broken image & audio in reply from model

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1415]
**Describe the bug**
when asking a model to generate an image/audio the reply comes back with a broken/non-displaying image or broken audio player

**Steps to reproduce**
see screenshots

**Expected behavior**
expect either a displayed image/audio file or a link to an image/audio saved locally -- both should have options to save as

**Screenshots**
![image](https://github.com/janhq/jan/assets/54515725/75740fec-f528-4354-8e4c-6f264c1583d6)

**Environment details**

    Operating System: Ubuntu 22.04.01
    Jan Version: 0.4.3-118
    Processor: Intel® Core™ i5-2520M CPU @ 2.50GHz × 4
    RAM: 16GB

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by hwc0x01** [comment]
also causes ui display issue (see gif) for following prompt
![Screencast from 01-06-2024 06 40 00 PM](https://github.com/janhq/jan/assets/54515725/e906c965-6a09-431d-a749-aa5b135176b2)

**Comment by hwc0x01** [comment]
audio generation has a dead player (probably because file doesn't exist) but it's a broken output behavior

![image](https://github.com/janhq/jan/assets/54515725/27182c4a-51d8-4e9b-897b-0e03e6ab86e7)

**Comment by namchuai** [comment]
@hwc0x01 , could you please send me the zip of those threads? 

It can be located under `~/jan/threads`

**Comment by hwc0x01** [comment]
[thread.json](https://github.com/janhq/jan/files/13852286/thread.json)
[problemthread.txt](https://github.com/janhq/jan/files/13852298/problemthread.txt)

**Comment by namchuai** [comment]
The image url for the message is https://www.pexels.com/photo/mountains-landscape-4167306/pexels-photo-4167306.jpeg, which I can't open as well.

I tried with lorem picsum and Jan can display normally.

<img width="694" alt="Screenshot 2024-01-07 at 13 37 36" src="https://github.com/janhq/jan/assets/10397206/b0e30d03-6856-4be2-8748-1f1124b97a6b">

However, I think we need to have better UI for URL we failed to fetch.

**Comment by hiro-v** [comment]
Hi there, I believe at this stage (0.4.3 and 0.4.4) Jan app has not officially supported image/ audio generation.
Given the 2 above comments, I think it's caused by the LLM output which can be malformed/ outdated.
I think this is the expected behavior at the moment, not bug.

Thank you.
