### ISSUE TITLE
feat: chat sidebar shows convo history better

### ISSUE THREAD

**Issue by drakehere** [janhq/jan#142]
Inspo: ChatGPT

Where the `Title` component of chat history is a convo summary.  
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBanF3IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a7970f02133d75491c6608338a3cb983fa954ca1/Screenshot%202023-09-19%20at%2011.45.51%20AM.png)

**Success Criteria**
- Pretitle: Name of model
- Title: Convo summary (max n chars)
- Subtitle: last message sent/received
- Upper Right hand side: timestamp/datestamp

**Comment by 0xSage** [comment]
@drakehere can you create issues with more description please. See suggested fields from Pytorch https://github.com/pytorch/pytorch/issues/new/choose

**Comment by namchuai** [comment]
Issue fixed in #349
