### ISSUE TITLE
bug: UI should allow users to set max tokens variably

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1427]
**Describe the bug**
Various models support up to 16k or more tokens. 
Some models are capped at 4096.

We should let users manually increase the token limit, or allow token max to be the max declared in model.json

**Comment by imtuyethan** [comment]
Can we allow token max to be the max declared in model.json?
Other than that, the UX side, when users enter a number that reaches the max number or below the min number, or other inappropriate input, here are error handles for these cases:
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1976-115351&mode=design&t=YTKXZrVIv0Ro7np2-4
 
 When users enter numbers that exceed the actual max token number allowed...
<img width="561" alt="Screenshot 2024-01-08 at 11 17 53 PM" src="https://github.com/janhq/jan/assets/89722390/bcbcc13a-b6f6-4a0a-a23c-f2eaa2363589">
default it back to the max/min number + show tooltips:
`Automatically set to the maximum allowed tokens`
<img width="643" alt="Screenshot 2024-01-08 at 11 19 16 PM" src="https://github.com/janhq/jan/assets/89722390/0d120fb3-acfb-4729-8a22-422444bdc0d2">

Similarly for minimum number:
`Automatically set to the minimum allowed tokens`
<img width="269" alt="Screenshot 2024-01-08 at 11 20 54 PM" src="https://github.com/janhq/jan/assets/89722390/4bb3de9f-b131-4436-99c8-31c5b7c0ab38">
