### ISSUE TITLE
epic: better error diagnosis and handling

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1430]
## Motivation

Users using Jan might face different problems:
- #1243 
- #1411 
- NVIDIA GPU related issue
- OOM for RAM/ VRAM
- The current indicator to user now is only "Failed to fetch" makes it hard to debug
- Other unknown issues related to Nitro

## Specs

1. **Propagate clear error messages so users can easily report problems**

- Users can see logs
- Users can opt in and send a report

I don't know what (1) entails. What is the correct solution here @louis-jan 

## Tasklist 
Design
- [x] #1244 

Imlementation
- [x] #1278 
- [x] #1243 
- [x] #1425 
- [ ] #1678
- [x] #1708 
- [ ] #1683 
- [x] #1627 
- [ ] #1688 

## Expectation outputs
- Can find the root cause of the Nitro errors
- Sync state with Jan #1067 
- Clearer message to the end user on what is happening (common issues)
- Further investigation through dumped output / error log
- User can send a problem report from the app instead of asking on Discord

## Q&A
- Should we automatically collect the error trace stack with user permissions? e.g. Sentry

**Comment by tikikun** [comment]
For me to debug on nitro part
- Can we have the main process of jan to monitor over stdout of nitro?
- Can we have a UI for user to dump the system information with one click and send to uy for analysis?
- How we store the above information, and where? (should this be a part of analytics or team has any other reommendation)

**Comment by Van-QA** [comment]
Adding more item to the list: 
https://github.com/janhq/jan/issues/1678
 https://github.com/janhq/jan/issues/1708
 https://github.com/janhq/jan/issues/1683

**Comment by imtuyethan** [comment]
I think fixing bugs will be an ongoing roadmap instead of epics because right now there's still a lot of things unsolvable & pending many sides. Closing this epic for now but remaining tickets are gonnabe keep in view.
