### ISSUE TITLE
feat: Memory calculation for different context length when loading model

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1432]
**Problem**
With the same 7B models, big context length could cause OOM

**Success Criteria**
Have a function to calculate memory usage to notice users -> Improve UX

**Final formula**

**Base Model:** (parameters∗4) / (32/quantization) ∗ 1.2

**KV_cache:**  seqlen * (hidden_size/num_attention_heads) * num_hidden_layers * 2 (K and V) * 2 * num_key_value_heads / 1024 / 1024 

**For MistralForCausalLM:**
Total = Base model + KV_cache *2

**For LlamaForCausalLM:**
Total = Base model + KV_cache 

Edgecase (not follow the formula):
Phi-2: This model can be loaded with Q8 2048 at 3.8GB

**Comment by hahuyhoang411** [comment]
We will need to gather information about the model in `config.json`

e.g. Mistral 7B
```
<html>
<body>
<!--StartFragment-->
{
--
  | "architectures": [
  | "MistralForCausalLM"
  | ],
  | "attention_dropout": 0.0,
  | "bos_token_id": 1,
  | "eos_token_id": 2,
  | "hidden_act": "silu",
  | "hidden_size": 4096,
  | "initializer_range": 0.02,
  | "intermediate_size": 14336,
  | "max_position_embeddings": 32768,
  | "model_type": "mistral",
  | "num_attention_heads": 32,
  | "num_hidden_layers": 32,
  | "num_key_value_heads": 8,
  | "rms_norm_eps": 1e-05,
  | "rope_theta": 1000000.0,
  | "sliding_window": null,
  | "tie_word_embeddings": false,
  | "torch_dtype": "bfloat16",
  | "transformers_version": "4.36.0",
  | "use_cache": true,
  | "vocab_size": 32000
  | }

<!--EndFragment-->
</body>
</html>
```

**Comment by hahuyhoang411** [comment]
2. Apply the function
batch_size * seqlen * (hidden_size/num_attention_heads) * num_hidden_layers * 2 (K and V) * 2 (bytes per Float16) * num_key_value_heads
= 1 * 4096 * (4096/32) * 32 * 2 * 2 * 8
= 536870912 (bytes)
= 536870912 / 1024 / 1024 = 5.12 (GB)

**Comment by hahuyhoang411** [comment]
Since for now, I can't find a way to properly calculate Q4_K_M so I did some practical tests to find out. 1 more finding is that every time the second message loads to the model we will see the `300MB` increase in memory at any ctx.

All of these images capture after sending second message to the model.

Before loading model (7B):
![image](https://github.com/janhq/jan/assets/64120343/73e2f39e-1ac7-4b9a-9255-da299637da71)

Load with 128 ctx:
![image](https://github.com/janhq/jan/assets/64120343/2c7e7d09-a6ad-46cb-b3ad-be8fd60e7e38)

Load with 2048 ctx:
![image](https://github.com/janhq/jan/assets/64120343/748afefb-436b-4e58-b20b-7809f309d02d)

Load with 4096 ctx:
![image](https://github.com/janhq/jan/assets/64120343/0d0ebde8-e4ce-4321-b887-eadd8181ce98)

Load with 8192 ctx:
![image](https://github.com/janhq/jan/assets/64120343/dc160f2f-d2a8-4ee0-b2fb-c12f752c5c43)

**Comment by hahuyhoang411** [comment]
With this function, we can calculate more accurately the usage of VRAM / RAM than the requirement from Thebloke


Reference:
https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.2-GGUF#explanation-of-quantisation-methods

**Comment by hahuyhoang411** [comment]
Appendix:
How to calculate the Parameter size of LLM?

**Comment by hahuyhoang411** [comment]
Proof the formula in Mistral Q3

ctx 2048: 4.4 - 0.3 = 4.1 GB
![image](https://github.com/janhq/jan/assets/64120343/c04a9590-09e5-4b1f-9e5a-0f22d4dc4750)

3.3 + 0.25 * 2 = 3.8 GB

**Comment by hahuyhoang411** [comment]
LLama arch
Llama 7B Q4
Base model: same as Mistral = 4.35GB

ctx 4096: 6.7 - 0.3 = 6.4 GB
![image](https://github.com/janhq/jan/assets/64120343/cb4d8037-d80e-4912-919e-11e58133ba5c)

Formula: 4.35 + 2 = 6.35 GB

**Comment by 0xSage** [comment]
@hahuyhoang411 is this issue resolved? If so, pls close it. (movinig to done doesn't resolve it)
