### ISSUE TITLE
feat: wipe out AppData folder - nsis uninstall script

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1435]
**Describe the bug**
Per user requests, Jan app should delete AppData after uninstalled on Windows. 
> Any particular reason why Jan leaves a ton of leftover files in Appdata? It should be a complete and total removal when users uninstall.

**Suggestions**
electron-builder custom nsis installation script example: 

```bash
!macro preInit
 SetRegView 64
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Windows\BSD"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Windows\BSD"
 SetRegView 32
  WriteRegExpandStr HKLM "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Windows\BSD"
  WriteRegExpandStr HKCU "${INSTALL_REGISTRY_KEY}" InstallLocation "C:\Windows\BSD"
!macroend

!macro customUnInstall
  ExecWait "schtasks /Delete /TN BSD-TASK -F"
  ExecWait "del /f C:\Windows\BSD"
!macroend
```

https://www.electron.build/generated/nsisoptions

**Additional context**
Is there any way to prompt the user for confirmation?

**Comment by hiento09** [comment]
windows stuff:
`C:\User\%USERPROFILE%\jan` : janroot
`C:\Users\%USERPROFILE%\AppData\Local\Programs\jan` : app installed folder, will be remove if we uninstall app
`C:\Users\%USERPROFILE%\AppData\Roaming\jan` : cache folder for jan app
`C:\Users\%USERPROFILE%\AppData\Local\electron` : cache folder generated by electron - chromium related

**Comment by imtuyethan** [comment]
@hiento09 to follow up & file tickets for Mac & Linux
