### ISSUE TITLE
ubuntu can not launch jan webui app

### ISSUE THREAD

**Issue by elven2016** [janhq/jan#1445]
**Describe the bug**
after install the deb pkg succesful， the app webui not appear

**Steps to reproduce**
1.  download the ubuntu server version  deb install package
2. Click on 'install'
3. after install，launch the app，the app webui not displayed 

**Environment details**
- Operating System: Ubuntu 22.04
- Jan Version: 0.4.3
- Processor:  Intel Core  i9-13900K
- RAM: 128GB
- Any additional relevant hardware specifics:  NVIDIA RTX4090 ，SSD

**Comment by hiento09** [comment]
Hi @elven2016, could you please try our nightly build version available at this link: https://github.com/janhq/jan?tab=readme-ov-file#download, to check if it resolves the issue? It's very help full if you test with both AppImage and .deb file. Thank you

**Comment by hiento09** [comment]
If you can provide a video of the error occurrence, it will be easier for us to debug and reproduce the issue. Thank you.

**Comment by hiento09** [comment]
The issue seems to be related to Electron, though I'm not entirely sure. Could you try using the AppImage version with the command below to launch the app and send us the error log from the terminal when the app crashes?
```bash
chmod +x jan-linux-x86_64-<version>.AppImage
./jan-linux-x86_64-<version>.AppImage
```

 Also, if possible, please try updating and upgrading the current packages of Ubuntu, restart your machine, and check if the error log changes or the issues is resolved or not. Thank you for spending time on the Jan app.

**Comment by elven2016** [comment]
> The issue seems to be related to Electron, though I'm not entirely sure. Could you try using the AppImage version with the command below to launch the app and send us the error log from the terminal when the app crashes?
> 
> ```shell
> chmod +x jan-linux-x86_64-<version>.AppImage
> ./jan-linux-x86_64-<version>.AppImage
> ```
> 
> Also, if possible, please try updating and upgrading the current packages of Ubuntu, restart your machine, and check if the error log changes or the issues is resolved or not.
> 
> ```shell
> sudo apt update && sudo apt upgrade -y
> ```
> 
> Thank you for spending time on the Jan app.

thanks for you reply，sudo  --no-sandbox can display the  ui ，but it appears some error
![image](https://github.com/janhq/jan/assets/16677082/3a6b5e55-4f5b-4b4b-a178-fd17b4ecbc71)

**Comment by hiento09** [comment]
Hi @elven2016 , these error logs are expected, can you verify that our app work on your end with a small model like tinyllam? Thank you.
