### ISSUE TITLE
LLM Request Lifecycle and Jan vs. Nitro responsibilities

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#145]
## Deliverable

- Architecture for LLM request lifecycle
    - Conversational context
- Clear roles for Jan and Nitro as subcomponents
    - Can Nitro be "stateless"?

## High-level Requirements
- Scale requirements
    - Can be run on a Mac Mini, but scale up to Prod-level deployments
    - Scaling components should be optional (i.e. don't bloat the basic install)
- Latency requirements
     - Latency should be minimized
     - However: AuthZ is necessary 
     - However: Persistence and picking up context is still necessary

**Comment by tikikun** [comment]
Hi some clarifications question:
- What scale we want it to be?
- Do we want fault-tolerant event bust or we just want to stop at single machine local deployment

I think these questions are crucial to make design decision on whether we can include an event bus, message queue or just simple cache or make proxy/middleware

**Comment by dan-jan** [comment]
My very "naive" architecture diagram: 

**Inbound Request**
1.1: Jan receives Client request, runs it through AuthZ
1.2: Jan retrieves conversation context from Postgres (brokered thru Hasura)
1.3: Jan "annotates" request with conversation context 
1.4: Jan sends "annotated" request to Nitro (i.e. Inference Service)

**Outbound Reply**
2.1: Nitro sends server-side events to a "multiplexer"
2.1(a): "Multiplexer" proxies SSEs to the client (i.e. low latency, as fast as possible)
2.1(b): "Multiplexer" collates the reply message SSEs till EOF, then persists it to Postgres

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb3lGIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2ef68f9c8a7c1e399451245bbfe844b703870685/image.png)

**Comment by tikikun** [comment]
we can use redis to share the state between services instead of thinking it in term of push and pull events?

**Comment by 0xSage** [comment]
closing as our arch direction has changed
