### ISSUE TITLE
bug: random selection when I expand & collapse 2 panels

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1461]
**Describe the bug**
Random selection when I expand & collapse 2 panels
https://github.com/janhq/jan/assets/89722390/f82ca537-b054-4b12-882e-39739970a3b6

**Environment details**
- Operating System: Mac Sonoma
- Jan Version: Jan v0.4.3-134
- Processor: Apple M2
- RAM: 16GB

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.4-163 ✅
