### ISSUE TITLE
bug: Typo 'fintuned' in 'finetuned' of Hub Tags

### ISSUE THREAD

**Issue by xvsd** [janhq/jan#1464]
**Describe the bug**
A typo of 'finetuned' in the hub

**Steps to reproduce**
1. Go to Hub
2. Click on a finetuned model, in my case, Dolphin Mixtral 8x7b
4. See error 'fintuned'

**Expected behavior**
'Finetuned'

**Screenshots**
![image](https://github.com/janhq/jan/assets/146020271/b8063212-34d6-4e9b-8528-1b8f291429b2)

**Comment by hahuyhoang411** [comment]
Thank you for reaching out. The meaning of tag `Finetuned` is that it is a fine-tuned model instead of a foundational model like (LLama, Mistral, etc).

In the future, we will have a `Finetune` space for users to fine-tune their own models.
