### ISSUE TITLE
bug: Missing 'Enable API Server' Option in Advanced Settings

### ISSUE THREAD

**Issue by planetoid** [janhq/jan#1470]
**Describe the bug**
Document ( https://jan.ai/guides/using-server/server/ ) mentions "Go to Settings > Advanced > Enable API Server"
However, this option is not seen on the Advanced page.

**Steps to reproduce**
1. Go to Settings > Advanced > Enable API Server
2. Not found the option "Enable API Server"

**Screenshots**
https://imgur.com/oDNWAcs

**Environment details**
- Operating System: MacOS Sonoma 14.0（23A344）
- Jan Version: 0.4.3
- Processor:  Apple M1 Pro
- RAM: 16GB

**Comment by Grzybow** [comment]
me too,wish for fix

**Comment by hieu-jan** [comment]
Hello @planetoid  @Grzybow, thank you for your questions. Currently, the API server feature is not available in the current version `0.4.3`. We will release this feature in the version 0.4.4 soon. 
On the other hand, you can also try this feature by installing lastest nightly build based on this guide https://jan.ai/install/nightly/
