### ISSUE TITLE
feat: put timestamp under thread name in left panel

### ISSUE THREAD

**Issue by hwc0x01** [janhq/jan#1472]
**Problem**
thread name is too truncated with timestamp next to it

**Success Criteria**
timestamp on line below thread name would be great

**Additional context**
screenshot:
![image](https://github.com/janhq/jan/assets/54515725/209e80b8-0ff1-473b-a6c5-57907fc8f1f6)

**Comment by 0xSage** [comment]
hmm I like this suggestion a lot! queueing

**Comment by imtuyethan** [comment]
# Specs & Design
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=3523-276157&mode=design&t=ZlK57CWtREqzmEZu-4

- To put timestamp above the thread name
- The time should be the last use time (not the time the thread was created)

## Time format
- If it's within today: 6:00 AM; 9:08 PM;...
- If it's within the current week: Friday, Thursday,...
- Others: 23 Jan 2023; 15 Sep 2024...

![Image](https://github.com/janhq/jan/assets/89722390/564e47a4-8479-4bf4-b071-ddbf2a3c99d4)

**Comment by Van-QA** [comment]
Tested for the case with full date time ✅ 
<img width="827" alt="image" src="https://github.com/janhq/jan/assets/64197333/1dcbfe33-f4b9-40aa-8f9c-dc75065d6fb9">
Jan v0.4.5-198
