### ISSUE TITLE
bug: UI - Hub - Green color setting makes the download button blend with the use button, causing user confusion.

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1475]
**Describe the bug**
The color of the download button is based on Settings > General > Appearance > Accent Color. When users choose Green as the main color for Jan App, both Download and Use button is in Green.

**Steps to reproduce**
1. Go to Settings > General > Appearance > Accent Color.
2. Click on Green 
3. Go to Hub
4. Observe the color of both button (Use and Download)

**Expected behavior**
We need these two buttons in different colors for easier identification.

**Screenshots**
<img width="1331" alt="image" src="https://github.com/janhq/jan/assets/64197333/321a0c2e-fdaa-471c-a88d-7bac5b420e73">

**Environment details**
Operating System: MacOS
Jan Version: 0.4.3
Processor: Apple M2 Pro
RAM: 16GB

**Additional context**
This is how the button looks when using purple (for reference only)
![image](https://github.com/janhq/jan/assets/64197333/eba3742f-fcb4-4ef0-ba59-47982b0d2936)

**Comment by Van-QA** [comment]
On the other hand, should we make these sliders colored based on the Accent Color setting as well? (currently selecting purple)
<img width="283" alt="image" src="https://github.com/janhq/jan/assets/64197333/88f085ad-8a00-44e9-9dec-870c55813bbe">

**Comment by 0xSage** [comment]
@imtuyethan mentinoed that designs only reflect ONE color for secondary color. More of a frontend fix that needs to happen where we make all colors consistent.

**Comment by Van-QA** [comment]
@urmauur looks like the main issue was fixed in the nightly build recently, can you help us with the sub issue https://github.com/janhq/jan/issues/1475#issuecomment-1882725884 as well? Many thank

**Comment by Van-QA** [comment]
@urmauur, on the other hand, the current Use button **when hovering** makes the text look hidden from the button, can you correct this together with in this ticket as well? many thanks.

<img width="370" alt="image" src="https://github.com/janhq/jan/assets/64197333/aa826a7a-14d0-45b0-99cf-662a6ab0747c">

**Comment by imtuyethan** [comment]
@Van-QA Let's close this issue for now. Many components & colros are not correct and I'm aiming to create another thorough ticket on this for @urmauur. One of these things is this ticket: https://github.com/orgs/janhq/projects/5/views/26?pane=issue&itemId=48450336
