### ISSUE TITLE
feat: Ability to change "Send a message" shortcut to "Cmd/Ctrl+Enter"

### ISSUE THREAD

**Issue by MiracleXYZ** [janhq/jan#1481]
I often send incomplete messages when accidentally hitting "Enter".

It would be nice if there was an option to change the shortcut for sending a message to "Cmd/Ctrl + Enter".

**Comment by 0xSage** [comment]
tagging #760 

We might not get to this for a few sprints

**Comment by imtuyethan** [comment]
It is very common among apps to send by hitting enter & using `shift + enter` for inline message.
