### ISSUE TITLE
bug: 0.4.4 results in Windows Bitdefender flagging Gen:Variant.Tedy.258323 and moving Jan to quarantine

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1483]
**Describe the bug**
- 0.4.4 causes WIndows Bitdefender to flag Nitro as infected with `Gen;Variant.Tedy.258323` and moved to quarantine
- McAfee was not triggered, only BitDefender is triggered

![image](https://github.com/janhq/jan/assets/101145494/4f648cd6-ce3a-406e-afc6-df28eb3a9d6a)

**Incident Log**
- 2:18am SGT: Hawke flags up Malware antivirus errors for 0.4.4 installation on Windows computers
- 2:21am SGT: @0xSage  responds in Discord
- 2:35am SGT: Hawke confirms multiple people have experienced this error on fresh installs
- 2:41am SGT: @louis-jan and @dan-jan revert 0.4.4 out of abundance of caution
- Incident ongoing: to triage and investigate next day

## Follow-ups

- [x] Reproduce 0.4.4 flag in Bitdefender
- [ ] Investigate whether indeed malicious code or false positive (if fp, resolve but flag with Bitdefender)
- [ ] Supply Chain attack?
- [ ] Process improvement: How do we avoid this in the future

**Comment by xvsd** [comment]
Looks like a false positive to me. Check [here](https://stackoverflow.com/questions/75886428/fake-positive-bit-defender-problem-genvariant-tedy-304469)

**Comment by dev2devportal** [comment]
Note: I was the one who reported this in Discord. I am normally on Linux systems, but it did not get flagged on my Windows 11 PC running McAfee and Microsoft Defender.
So far it was flagged on all BitDefender user systems at 3 different companies.. BitDefender automatically "disinfected" it and wouldn't let the users do anything else.
Unfortunately only one user took a screenshot (so far).

**Comment by hiento09** [comment]
https://github.com/janhq/jan/pull/1529
