### ISSUE TITLE
bug: Stable download links in README are still 0.4.4 (404)

### ISSUE THREAD

**Issue by xvsd** [janhq/jan#1485]
**Describe the bug**
The Stable download options in the README are 0.4.4, however, since #1483, 0.4.4 has been reverted and is no longer available.

**Comment by 0xSage** [comment]
This is a great catch. Thank you

**Comment by hiento09** [comment]
I updated the url in REAME.md file, I will check if we can cactch the event change a latest release and update to the CI.
