### ISSUE TITLE
bug: UI rendering blurriness during model operation

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1489]
<img width="890" alt="Screenshot 2024-01-10 at 10 44 25 AM" src="https://github.com/janhq/jan/assets/89722390/5a6b97d1-f80a-4fd0-af93-8e88e3c2d5ab">

**Comment by louis-jan** [comment]
I think we need @hiento09 help on this. It maybe more about OS and Graphic Drivers.

**Comment by urmauur** [comment]
@louis-jan @hiento09 i really can't reproduce this one, i think i really need more help from @louis-jan and @hiento09, while waiting the help i'll ticket move to in review. cc @Van-QA

**Comment by urmauur** [comment]
close, can’t reproduce, please open again once issue still exist
