### ISSUE TITLE
chore: instrument Algolia on jan.ai

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1490]
See email: `Using Algolia for your documentation search`

We have been approved

**Comment by hieu-jan** [comment]
Enabled Agolia search via pull request #1497 based on documentation from:
- https://docusaurus.io/docs/search#using-algolia-docsearch
- https://docsearch.algolia.com/docs/DocSearch-v3
Hien also configured process.env.ALGOLIA_APP_ID and process.env.ALGOLIA_API_KEY in GitHub settings. 
 
 Issue: The search function is currently not working. I am still figuring out the root issue.

**Comment by hieu-jan** [comment]
- [ ] Configure environment #1518 #1517
- [ ] Re-crawling entires websites based on sitemap.xml 
- [ ] Setting up automatically Agolia Crawler to make sure content is update to date in search db when new docs 's coming. 
- [ ] Testing darkmode search bar & Fixed UI issue #1520
