### ISSUE TITLE
Why does performance drop when disconnecting from the network?

### ISSUE THREAD

**Issue by MRQJsfhf** [janhq/jan#1498]
**Describe the bug**

**Steps to reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.1.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by MRQJsfhf** [comment]
Model recovery is stuck and slow. Sometimes loading errors occur

**Comment by Van-QA** [comment]
I tested without the network, and it looks like I cannot reproduce the issue. We will need more information from @MRQJsfhf, otherwise, this ticket will be closed soon. 
Uploading perf.mp4…
