### ISSUE TITLE
bug: Thread - Clean action - After cleaned any thread, the last message value still remain in the thread JSON data

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1501]
**Describe the bug**
The clean thread action did not actually cleanning the thread JSON data, last mesasage value still remain

**Steps to reproduce**
1. Observe any thread with message
2. Attempt to clean the thread
3. Check the JSON data of the thread

**Expected behavior**
When cleaning the thread, the last message value should also removed from the JSON data

**Screenshots**
![image](https://github.com/janhq/jan/assets/64197333/5364dd54-f00b-4c26-af3f-ce04352b35bf)

**Environment details**
Operating System: MacOS
Jan Version: 0.4.3
Processor: Apple M2 Pro
RAM: 16GB

**Comment by 0xSage** [comment]
@Van-QA let's walk through how to triage some of these issues tomorrow.

Increasingly, I'm dropping the ball. And was hoping you can own the Github inbound requests 🙏 

Initial SOP: https://jan.ai/handbook/product/

Very changeable

**Comment by Van-QA** [comment]
tested and looking good on Jan v0.4.4-194 ✅
