### ISSUE TITLE
bug: Can't run on Apple M1 Pro

### ISSUE THREAD

**Issue by iwootten** [janhq/jan#1503]
**Describe the bug**
 
Unable to run a model on my M1 Pro 16GB. Tried both Mistral and TinyLlama on both 0.4.3 and the nightly version.

**Steps to reproduce**
1. Download a model
2. Create a thread using said model
3. Enter a prompt

**Expected behavior**
The model gives some sort of response.

**Screenshots**
<img width="1212" alt="Screenshot 2024-01-10 at 16 42 08" src="https://github.com/janhq/jan/assets/3598161/dc1579a0-f6c3-4793-ab3c-25216756acbb">

**Environment details**
- Operating System: Mac OS 13.4.1
- Jan Version: 0.4.3/0.4.3-137
- Processor: Apple M1 Pro
- RAM: 16GB

**Comment by 0xSage** [comment]
@iwootten you need the lastest macos, e.g sonoma 14

Esp if you want to use mac metal. Also for your personal security reasons!

https://jan.ai/troubleshooting/somethings-amiss/

**Comment by iwootten** [comment]
@0xSage It would be great if this was listed somewhere as a requirement - rather than the error page. Ideally blocking installation or alerting to it within jan when it's first fired up.

**Comment by 0xSage** [comment]
> @0xSage It would be great if this was listed somewhere as a requirement - rather than the error page. Ideally blocking installation or alerting to it within jan when it's first fired up.

Yep, our new nightly build shows this, among other incoming improvements. Thanks for the feedback - pls keep em coming

<img width="1185" alt="image" src="https://github.com/janhq/jan/assets/69952136/03a3b473-a4e3-47f9-8047-98faaa0616b4">
