### ISSUE TITLE
Unable to download model

### ISSUE THREAD

**Issue by MRQJsfhf** [janhq/jan#1504]
Error reminder:
Download Failed
Model mistral-ins-7b-q4 download failed: connect ETIMEDOUT 199.59.148.247:443

The error report shows multiple attempts to make a POST request from a local path (file:///C:/Users/gjjfg/AppData/Local/Programs/jan/resources/app.asar/renderer/xxx/) but encountered net::ERR_FILE_NOT_FOUND error. This means that the program is trying to access a file or path that does not exist.

**Comment by 0xSage** [comment]
@Van-QA to take a first look when shes back tomorrow 🙏

**Comment by Van-QA** [comment]
@MRQJsfhf It looks like you are using Windows.
Can you help us provide more details of the Jan version that you are using? If it's the Stable version, would you mind trying it on the Nightly Build and seeing if the problem still happens?
(The night build version is allowing downloads normally from my side).

**Comment by MRQJsfhf** [comment]
> @MRQJsfhf看来您正在使用 Windows。 您能否帮助我们提供您正在使用的 Jan 版本的更多详细信息？如果是稳定版本，您介意在 Nightly Build 上尝试一下，看看问题是否仍然存在？ （夜间构建版本允许从我这边正常下载）。

Stable version jan-win-x64-0.4.3

**Comment by ougege** [comment]
In china, every model download will failed, even i use v2ray change system agent. How to do ?

**Comment by 0xSage** [comment]
> In china, every model download will failed, even i use v2ray change system agent. I use nightly Jan v0.4.3-143 , How to do ? Tips Like this: Download Failed Model noromaid-7b download failed: connect ECONNREFUSED 124.11.210.175:443

Sorry to hear that. You can download manually, through a different source, then manually import the model: https://jan.ai/guides/using-models/import-manually/

We may host models for faster/accessible download, minimally the proprietary models that we've been training, for the entire Asia region soon.
