### ISSUE TITLE
bug: Formatting is removed from LLM response

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#151]
## Problem

- Formatting is removed from LLM response
- Using Hasura for presentational layer seems to be creating more problems (#43, #38)

## Solution
- Quick fix will be in #143 (?)
- Need to think through how to solve it in #145 
- My sense is that the FE should also "parse" it and amend it (see how OpenAI renders after receiving the SSE)

![image](https://github.com/janhq/jan/assets/101145494/cb91f588-af8a-4fa8-b803-6fdf9e5670c3)

**Comment by namchuai** [comment]
yeah, I think we should have markdown support. I will add it

**Comment by namchuai** [comment]
included in #349
