### ISSUE TITLE
bug: `localhost:1337` Swagger does not work in some cases

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1511]
**Describe the bug**
- I see many bugs/ not working APIs on `localhost:1337` swagger

**Steps to reproduce**
0. Install nightly build: https://discord.com/channels/1107178041848909847/1191638499355537418/1194735991794176031
1. Go to 'Settings' -> Enable API server
2. Go to `localhost:1337` - swagger page
3. Browse every single API, click try

**Expected behavior**
- If user can try to API, there should be no error.
- If the API is not implemented yet, the Swagger should say so in the description. And the API should return so
- Default value needs to be correct (e.g Zephyr 7B does not exist anymore)

**Screenshots**
![CleanShot 2024-01-11 at 08 53 15](https://github.com/janhq/jan/assets/22463238/acf2e522-0e9d-48a5-aa10-c7432391e86f)
![CleanShot 2024-01-11 at 08 53 24](https://github.com/janhq/jan/assets/22463238/149793b0-6af7-4003-b184-7c76cda32139)
![CleanShot 2024-01-11 at 08 53 34](https://github.com/janhq/jan/assets/22463238/539e96b0-da17-44df-8138-d0e5960a03f4)
![CleanShot 2024-01-11 at 08 53 41](https://github.com/janhq/jan/assets/22463238/27289cf3-dbfb-4b19-b069-8070dff2ba4f)
![CleanShot 2024-01-11 at 08 53 50](https://github.com/janhq/jan/assets/22463238/8fac7fa2-96b9-4f83-9c44-14afa78c14a9)
![CleanShot 2024-01-11 at 08 53 58](https://github.com/janhq/jan/assets/22463238/f5352cd9-240d-4cb3-ba06-e33501fc54a0)
![CleanShot 2024-01-11 at 08 54 08](https://github.com/janhq/jan/assets/22463238/70704fff-9940-43f0-90c7-5e79b452d9fe)
![CleanShot 2024-01-11 at 08 54 40](https://github.com/janhq/jan/assets/22463238/56cd268c-c2e8-422a-bc65-d23d0bfa12e3)

**Environment details**
- All platform because this is API logic

**Additional context**

**Comment by 0xSage** [comment]
Should be fixed with #1572.
