### ISSUE TITLE
feat: support network proxy for model downloading

### ISSUE THREAD

**Issue by terasum** [janhq/jan#1512]
**Problem**
Very need http/https proxy configuration for model downloading, I'm living a network control area, then the model downloading processing is very slowly even failed everytime.

**Success Criteria**
Downloading model over the http/https/socks proxy

**Additional context**

Maybe you can put some configuration at `Settings` page.

Thank you for your great work!

**Comment by markmehere** [comment]
No guarantees but I'm just going to link this one to #1558 

And include this StackOverflow here: https://stackoverflow.com/questions/48973288/how-to-use-proxy-in-npms-request-package

**Comment by Van-QA** [comment]
thank @markmehere for your contribution. I am assigning this to @louis-jan to review together with the one @markmehere provided and make further decisions.

**Comment by markmehere** [comment]
@Van-QA That's pretty quick -  I was asleep most of the last 9 hours. 😁

@louis-jan I have now added more general proxy support and the old PR which was proxy support in very limited scenarios is closed.

Take a look at the new PR instead:

#1562

**Comment by louis-jan** [comment]
Thank you for the great contribution! @markmehere.

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.4-163
