### ISSUE TITLE
feat: Auto suggestion for next question

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1527]
**Problem**
- Sometime it's interesting to have the LLM to suggest question for me to ask it
- Sometime I have to think a lot more after having some turns in the discussion

**Success Criteria**
- Suggest new question within the new thread
- Suggest the next follow up questions after assistant response

**Additional context**
- Example for ChatGPT with new thread open
![CleanShot 2024-01-11 at 17 17 56](https://github.com/janhq/jan/assets/22463238/b491f574-65a5-42f9-968a-98ac1f554dd0)
- Example for ChatPDF with the suggestion for next possible question to ask
![CleanShot 2024-01-11 at 17 20 29](https://github.com/janhq/jan/assets/22463238/502633b7-f00f-44ea-a156-cd43df68aab3)

**Comment by imtuyethan** [comment]
@hiro-v this is another epic we already had https://github.com/orgs/janhq/projects/5/views/16?pane=issue&itemId=45941756
