### ISSUE TITLE
CUDA detection broken?

### ISSUE THREAD

**Issue by merc4derp** [janhq/jan#1531]
I'm on Windows 11, latest nvidia driver 546.33, latest cuda 12.3

Using latest Jan release 0.4.3, CUDA is not recognized, there is no option in the UI to turn on/off GPU usage and there is no settings folder created in the installation path, nor settings.json file as expected reading the instructions at https://jan.ai/troubleshooting/gpu-not-used/

I created a settings folder and a settings.json file manually and pasted the template json code that was posted in the link above and despite the settings having nothing in common with my actual setup, CUDA worked. providing a 10x performance increase.

The app didn't seem to try and validate the random settings in that file, nor did it change them to the correct ones. The gpu switch in the UI still isn't there, but at least cuda now works.

What's going on?

**Comment by 0xSage** [comment]
Can you use nightly? This issue will be fixed post 0.4.3 https://jan.ai/install/nightly/

**Comment by merc4derp** [comment]
As I said, cuda works with the manually created settings.json and so far haven't had any problem.
If it's a known issue and you're working on it, all good.

**Comment by 0xSage** [comment]
It should be patched in 0.4.4. Pls do let us know if it occurs for you again

**Comment by lineality** [comment]
Will test with windows and ubuntu (and maybe fedora) when 0.4.4 nightly comes out. Many thanks for working on this! (Jan is so amazing.)

**Comment by 0xSage** [comment]
> Will test with windows and ubuntu (and maybe fedora) when 0.4.4 nightly comes out. Many thanks for working on this! (Jan is so amazing.)

Its out!

You may need to clear cache / kill straggle rprocesses: https://jan.ai/troubleshooting/stuck-on-broken-build/

But restarting the app should do the trick :)
