### ISSUE TITLE
feat: add compatibility tag to model selection in right panel 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1533]
# Problem
Right now users often misclick on models with `not enough RAM` tag, leading to multiple report of something's amiss error
See example here: https://discord.com/channels/1107178041848909847/1110389363809976361/1194644439033979030
# Todo
Add compatibility tag to model selection in threads settings (right panel)

# Design 
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=837-101980&mode=design&t=P76QcZnZBvoxZEgk-4
<img width="487" alt="Screenshot 2024-01-11 at 7 21 20 PM" src="https://github.com/janhq/jan/assets/89722390/3b4b6917-abb4-40fb-be30-a376f8657c84">

<img width="693" alt="Screenshot 2024-01-11 at 7 25 08 PM" src="https://github.com/janhq/jan/assets/89722390/867fd911-754a-4541-88db-f3b6880dc22a">

**Comment by 0xSage** [comment]
@urmauur gentle reminder to close issues because moving them to done doesn't resolve the ticket.
