### ISSUE TITLE
bug: JavaScript errors in the main process

### ISSUE THREAD

**Issue by gaardhus** [janhq/jan#1535]
**Describe the bug**
When I launch the app, and while running it, I get multiple errors saying "A JavaScript error occured in the man process". I can press OK, but a new error pops up very frequently.

**Steps to reproduce**
1. Install the package from AUR with yay.
2. Open the app with rofi.
3. Two errors pop up on launch.
4. Last error repeats frequently.

**Expected behavior**
A functioning app

**Screenshots**
![image](https://github.com/janhq/jan/assets/46934916/95e3dfad-c16b-463e-9671-421dea6d0ecd)
![image](https://github.com/janhq/jan/assets/46934916/8a43eab6-1d10-46e9-aea8-64af58042590)
![image](https://github.com/janhq/jan/assets/46934916/4524c596-6757-4c56-abfd-dce5dd357e7c)

The first two only appears once when opening the app, and then the last keeps repeating.

**Environment details**
- Operating System: Arch Linux 6.6.10-arch1-1
- Jan Version: 0.4.3
- Processor: Ryzen 7 PRO 7840U w/ Radeon 780M Graphics (16)
- RAM: 32GB

**Additional context**
This only happens when I launch jan through the rofi menu, and not when I launch it from a terminal.

Here I only occasionally get the following error:

```
[132794:0111/140950.464800:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[132794:0111/140957.830495:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[132794:0111/140957.832929:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by gaardhus** [comment]
Super weird, but it seems that a system reset has fixed the pop up errors.

**Comment by louis-jan** [comment]
The issues has been fixed in the latest Nightly Build cc @Van-QA
