### ISSUE TITLE
bug: Missing Token speed when stream option is off

### ISSUE THREAD

**Issue by TC117** [janhq/jan#1537]
Per Nicole's request. create a bug ticket to investigate

**Expected behavior**
I really don't know what to expect but at least give me something similar to token speed for me to have an idea of the performance of my prompt

**Screenshots**
[missing token speed.webm](https://github.com/janhq/jan/assets/19384189/456e0b51-91a9-4b07-9f8f-6d41a6b34884)

**Environment details**
- Operating System: Win10
- Jan Version: Jan v0.4.3-139

**Comment by louis-jan** [comment]
Since this is a misleading feature request, not actually a bug. We can close it for now.
