### ISSUE TITLE
docs: Linux AppImage Link redirecting to 404

### ISSUE THREAD

**Issue by thequantumquirk** [janhq/jan#1540]
The Linux AppImage link and Readme redirects to a 404 page as the AppImage link is missing in the Releases

![image](https://github.com/janhq/jan/assets/67329471/9ba633cf-1682-4f41-acd0-64cc357e438c)

**Comment by metoinside** [comment]
Well, according to this [comment](https://github.com/janhq/jan/issues/1462#issuecomment-1883464465) from @hiento09, it seems going to be available going forward with 0.4.4 release. Right now 0.4.3 is the latest as of now

**Comment by imtuyethan** [comment]
Thanks for reporting this. This will be solved once 0.4.4 is release, thank you!
