### ISSUE TITLE
feat: import models via click, drag & drop functionality 

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1542]
**Problem**

**Success Criteria**

1. I go to settings > files (or whatever menu name) > model scan
2. I get a finder popup and select the folder
3. I see the correct progress/error states as this is being done
4. App is updated with these models
5. model.jsons are autogened

**Additional context**

**Comment by imtuyethan** [comment]
Figma link for review: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2160-165286&mode=design&t=TdZv1LIEiCArXNOZ-4

**Comment by imtuyethan** [comment]
Design finalized
