### ISSUE TITLE
bug: Long thread title

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1545]
**Describe the bug**
With long thread title, the text spill all over the client

**Steps to reproduce**
1. Start a new thread
2. Paste any long text into the Title box
3. See error

**Expected behavior**
We should have max cap of letter for title?

**Screenshots**
![image](https://github.com/janhq/jan/assets/64120343/ee72e1c4-16aa-42c7-95ab-8804c1b2c410)

**Environment details**
- Operating System: Windows
- Jan Version: v0.4.3.140
- Processor: Intel
- RAM: 32GB

**Comment by Van-QA** [comment]
Tested and looking good ✅ Jan v0.4.4-163


![Image](https://github.com/janhq/jan/assets/64197333/6c928ecb-339a-4a21-920b-4f64375139a7)
