### ISSUE TITLE
bug: Mistral yarn 7B Q4 doesn't reply

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1549]
**Describe the bug**
Mistral Yarn can't reply

**Steps to reproduce**
1. Download Yarn
2. Chat with it
3. See error

**Additional context**
There is a bug from GGUF format of the model
https://huggingface.co/TheBloke/Yarn-Mistral-7B-128k-GGUF/discussions/3

**Comment by dmatora** [comment]
same issue
