### ISSUE TITLE
bug: Weird space around formatted code blocks in input

### ISSUE THREAD

**Issue by gaardhus** [janhq/jan#1557]
**Describe the bug**
Whenever I create a code block in my input, it is formatted with way too much space around the element in the conversation history.

**Steps to reproduce**
1. Go to a conversation
2. Type an input with:

```
print("Hello world")
```

4. Submit the input
5. See the weird space in the conversation history.

**Expected behavior**
A nicely formatted code block without the weird space.

**Screenshots**
![image](https://github.com/janhq/jan/assets/46934916/b3f87c43-0690-442f-b587-a6c8ab7d3b25)

**Environment details**
- Operating System: Arch Linux 6.6.10-arch1-1
- Jan Version: 0.4.3
- Processor: Ryzen 7 PRO 7840U w/ Radeon 780M Graphics (16)
- RAM: 32GB

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
hi @gaardhus, can you help us provide the model that you are using?

**Comment by gaardhus** [comment]
It happens independently of model (tried with openai gpt4 and mixtral 8x7b), and seems to be a CSS issue I would guess.

**Comment by Van-QA** [comment]
Tested and looking good on the latest Jan app, we were not able to reproduce this from our side, feel free to reopen this if the issue persists.

<img width="1180" alt="image" src="https://github.com/janhq/jan/assets/64197333/760332fe-be9c-4488-bd6d-de0326c70904">

**Comment by gaardhus** [comment]
All looks good for me on version 0.4.4 as well, thanks for the fix!
