### ISSUE TITLE
bug:After all model chat boxes are deleted, new chat boxes cannot be added.

### ISSUE THREAD

**Issue by MRQJsfhf** [janhq/jan#1560]
![屏幕截图 2024-01-13 022916](https://github.com/janhq/jan/assets/136575248/c71b402b-67fb-471f-83b5-05beceebd9c4)
As shown in the picture, I deleted it accidentally and cannot add a chat box when I reopen the software. Version: Experimental jan-win-x64-0.4.3-139.exe

**Comment by Van-QA** [comment]
hi @MRQJsfhf Would you mind updating to the latest version of Jan v0.4.3-142 and retrying? I was not able to reproduce it on our side using the latest nightly build version, Jan v0.4.3-142.

**Comment by MRQJsfhf** [comment]
> 你好@MRQJsfhf您介意更新到最新版本的 Jan v0.4.3-142 并重试吗？我无法使用最新的夜间构建版本 Jan v0.4.3-142 在我们这边重现它。

Well, I'll give it a try

**Comment by 0xSage** [comment]
@MRQJsfhf I'll mark this issue as resolved. If not, pls feel free to reopen it, and give us the exact steps to reproduce it on your computer & your computer os/processor type
