### ISSUE TITLE
bug: All Chat history auto deletes every time i close the Jan App on my computer. when i open it there is no saved chat history. 

### ISSUE THREAD

**Issue by Surfingai1988** [janhq/jan#1565]
**Describe the bug**

WHEN I TYPE IN THE CHAT AND GET A RESPONSE FROM THE DIFFERENT MODELS I EXIT OUT OF THE APP ONLY TO COME BACK TO IT LATER AND THERE IS NO SAVED CHAT HISTORY ON THE RIGHT-HAND SIDE. IT IS AUTO DELETING ALL CHAT UPON CLOSING. I HAVE UNISTALLED AND RE INSTALLED MUTIPLE TIMES TO HAVE THE ISSUES STILL TAKE PLACE. THE VERSION I AM USING IS THE 4.3 NIGHTLY FOR WINDOWS 11. 

**Steps to reproduce**
1. Go to: JAN APP
2. Click on: JAN APP TO OPEN IT 
4. Scroll down to: START NEW CHAT HISTORY, TYPE SOME TEXT, GET A RESPONSE, EXIT OUT
5. See error: NO CHAT HISTORY 

**Expected behavior**
A clear and concise description of what you expected to happen: I EXPECT THERE TO BE SAVED CHAT HISTORY ON THE RIGHT HAND SIDE. 

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [ Windows 11,]
- Jan Version: [e.g., 0.4.3]
- Processor: [AMD Ryzen 7 4800H with Radeon Graphics]
- RAM: [16GB]

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

( I am not typing in all caps because I am angry. I was trying to separate the prompts between the form text and mine.)

![JAN 1](https://github.com/janhq/jan/assets/156174554/ab4336d6-a166-4e5f-bd30-83dab57e0504)

![JAN 2 ](https://github.com/janhq/jan/assets/156174554/e74464b6-fa51-4906-91a7-d35719f78627)

**Comment by Van-QA** [comment]
hi @Surfingai1988, Thank you for highlighting the issue. Unfortunately, I was not able to reproduce it on our side using the same Jan v0.4.3-142 on Windows. The message still exists after we close the app and reopen it.
- @Surfingai1988: would you be able to send us the log from the Jan app on your local?
<img width="697" alt="image" src="https://github.com/janhq/jan/assets/64197333/5cf4ab02-b7d9-4997-950f-0b3b44647b16">

- @louis-jan: I noticed that if we closed the app while the response was being generated, that message would no longer exist after reopening. I am not sure if this is expected or not. Please help me take a look at this.
![closeApp](https://github.com/janhq/jan/assets/64197333/d346e49d-9ec8-48d7-87c0-1bf0c221917e)

**Comment by 0xSage** [comment]
Seems user was able to resolve issue with:
1. complete uninstall
2. restart computer
3. reinstalling Jan
