### ISSUE TITLE
bug: cannot switch model

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1571]
**Describe the bug**
I cannot switch model:

https://github.com/janhq/jan/assets/89722390/d5300490-baed-46a5-8711-db79a027ee45

**Steps to reproduce**
1. Create a new thread
2. Change model GPT 3.5
3. See error

**Expected behavior**
I can switch model

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: Jan v0.4.3-143
- Processor: M2
- RAM: 16GB

**Logs**
- Go to`~/jan/logs` > `app.log`. Or, via UI, click on Settings > Advanced > Open App Directory > `app.log`
- If you are using Jan local api server only, grab the `server.log` instead of `app.log`.

**Comment by 0xSage** [comment]
Hmm, it worked for me. I couldn't repro. @imtuyethan have you tried, restarting computer, restarting the app. Pls close issue if it is fixed by that :)

**Comment by namchuai** [comment]
Hmm I think I met this issue when pairing code with @louis-jan once. IMO, better keep it for sometimes to check.

**Comment by Van-QA** [comment]
Working fine on my end using the latest Jan app release 4.4.0 ✅
