### ISSUE TITLE
bug: can't manually set value in Max Token input box anymore

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1573]
**Describe the bug**
![Export-1705242084368](https://github.com/janhq/jan/assets/69952136/396ab773-0776-4a80-bf57-1f2cbf0d0923)

**Steps to reproduce**
1. Go to Inference params > Max Tokens
2. Try to type 2048
3. It doesn't let me: it either falls to the min or max value with each keystroke
4. Very frustrating, because hte input box UI suggests that I can type any value I want

cc @imtuyethan 

**Expected behavior**
I should be able to adjust the values with slider or text input box.
Minimally, I should be able to type any value in Max Token.

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: macos
- Jan Version: 0.4.3-143

**Comment by louis-jan** [comment]
This is our recent update to avoid some misleading issues, such as:
- Users can input a very large value, which breaks the app.
- Users can set the maximum value via model.json.
cc @urmauur @imtuyethan

**Comment by 0xSage** [comment]
> This is our recent update to avoid some misleading issues, such as:
> 
> * Users can input a very large value, which breaks the app.
> * Users can set the maximum value via model.json.
>   cc @urmauur @imtuyethan

I had a feeling. UX is confusing, feels like a bug, and we'll get more bug reports. We could disable the `input action` or perhaps there is a better solution @imtuyethan

**Comment by dniq** [comment]
Same complaint here. Can not increase Max Tokens beyond 4k.

If max tokens / cix_len can be changed in model.json file - this needs to be exposed in the UI ;)

**Comment by imtuyethan** [comment]
Yeah this is kinda weird, i cannot clear the number @urmauur 

https://github.com/janhq/jan/assets/89722390/86500ea8-a403-4d67-b21e-c3257f49c9d4

**Comment by louis-jan** [comment]
> Yeah this is kinda weird, i cannot clear the number @urmauur
> 
>  Screen.Recording.2024-01-14.at.10.54.51.PM.mov

@imtuyethan that's is minimum threshold

**Comment by imtuyethan** [comment]
@urmauur @louis-jan 
Suggestion: When users enter a number that exceeds min or max number, we only revert to the min/max number + show the tooltip when users leave the input field (by clicking outside or tapping enter)
