### ISSUE TITLE
Typewriter Effect for LLMs with formatting of output

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#158]
## Outcome

- [ ] Jan has a ChatGPT-like Typewriter effect for LLMs
- [ ] Markdown is formatted automatically (at runtime, like OpenAI?)
- [ ] Code snippets are formatted automatically with copy block

We can consider releasing this as a library to deal with SSEs as well, as I'm sure we're not the only ones who need this. 

## Status Quo

- @louis-jan is using https://github.com/SpellcraftAI/nextjs-openai/tree/canary
- @namchuai is working on formatting as https://github.com/janhq/jan/issues/151 but might not be that straightforward

## Resources

- https://dekraker.medium.com/chatgpt-text-streaming-typing-effect-with-openais-api-and-javascript-php-ajax-85bcef4e60eb

**Comment by dan-jan** [comment]
We might be able to use one of these libraries: 

https://github.com/sgwilym/windups

**Comment by 0xSage** [comment]
more or less done.
