### ISSUE TITLE
broken link to AppImage from jan.ai site (github is ok)

### ISSUE THREAD

**Issue by lineality** [janhq/jan#1581]
**Describe the bug**
Link from this page: https://jan.ai/
this link: https://github.com/janhq/jan/releases/download/v0.4.3/jan-linux-x86_64-0.4.3.AppImage
is a broken hard-version link that perhaps refers to an old file that does not exist.

**Steps to reproduce**
1. Go to https://jan.ai/
2. Click on AppImage download link
4. See 404 error

**Expected behavior**
either get an updated link to the appimage, or perhaps a link (with scroll?) to the github page
which also gives the nightly option
https://github.com/janhq/jan

**Screenshots**

**Environment details**
website link, not a browser or OS issue

**Logs**

**Additional context**
your are awsome, please keep going!!!

**Comment by Van-QA** [comment]
hi @lineality, thank for highlighting this, the issue will be resolved right after the release of 0.4.4.
https://github.com/janhq/jan/issues/1540
