### ISSUE TITLE
bug: crashes macOS system on MacBook Pro M1

### ISSUE THREAD

**Issue by Derrick-Edward** [janhq/jan#1582]
**Describe the bug**
Running the MIXTRAL 8X7B model from Jan's hub on a MacBook Pro (16-inch, 2021) leads to a system crash after queuing, necessitating a hard reset.

**Steps to reproduce**
1. Download MIXTRAL 8X7B model from Jan hub.
2. Run the model on MacBook Pro (16-inch, 2021).
3. Observe system entering a queue.
4. Experience MacOS system crash, requiring hard reset.

**Expected behavior**
Expected the MIXTRAL 8X7B model to run without crashing the system.

**Screenshots**
Unable to provide screenshots due to the nature of the crash.

**Environment details**
- Operating System: MacOS 14.2.1
- Jan Version: latest
- Processor: Apple M1 Pro
- RAM: 16GB unified memory (configurable options available)
- Storage: 512GB SSD (configurable options available)
- Display: 16.2-inch Liquid Retina XDR display
- Additional hardware specifics: Up to 16-core GPU (M1 Pro), 100-watt-hour lithium-polymer battery, 140W USB-C Power Adapter

**Comment by hiento09** [comment]
Hello @Derrick-Edward , the MIXTRAL 8X7B model requires 24GB, but your RAM capacity is only 16GB, which is insufficient to run the model. Can you try with a smaller model like tinyllama to check if our app works or not 
![Uploading image.png…]()

**Comment by Derrick-Edward** [comment]
Thanks, the tinyllama works. Will close issue
