### ISSUE TITLE
how can i download mistral-ins-7b-q4 localy

### ISSUE THREAD

**Issue by Lowpower** [janhq/jan#1583]
**Pages**
- Page(s) that need to be done

**Success Criteria**
Content that should be covered

**Additional context**
Examples, reference pages, resources

**Comment by Lowpower** [comment]
or i can set http proxy?

**Comment by Van-QA** [comment]
hi @Lowpower, 
- Can you have a look at this document for how to download / import model? https://jan.ai/guides/using-models/
- The topic related to https proxy is at https://github.com/janhq/jan/issues/1512
