### ISSUE TITLE
feat: Modifiable App Directory

### ISSUE THREAD

**Issue by lumi-git** [janhq/jan#1601]
**Problem**
Can we add a parameter to change the app directory ? I installed the app and i didn't had the choice to install on another drive.

**Success Criteria**
Being able to choose/modify the app directory (folder where the models are stored).

**Additional context**
Under the open app directory, have a button to change app directory.
![image](https://github.com/janhq/jan/assets/74414575/39322cbb-2f26-4819-ae49-f76c511997ca)

**Comment by Van-QA** [comment]
hi @lumi-git, We are working on it, please follow up on this ticket: https://github.com/janhq/jan/issues/1010.
I hope this help.
