### ISSUE TITLE
bug: Dockerfile 'yarn workspace server install' command not working

### ISSUE THREAD

**Issue by accoumar12** [janhq/jan#1604]
I am using the Dockerfile, but when running the build command, I get an error.

Run 'docker build -t interface:1.0 .'

I get the following error:

 => ERROR [builder 4/5] RUN yarn workspace server install                                                                                                                                            
 [builder 4/5] RUN yarn workspace server install:                                                                
#0 0.363 yarn workspace v1.22.19                                                                                   
#0 0.405 info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
#0 0.405 error Unknown workspace "server".

ERROR: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c yarn workspace server install]: runc did not terminate sucessfully

**Comment by hiento09** [comment]
Hi @accoumar12 , apologies for the inconvenience. The Dockerfile in question has been deprecated, leading to some confusion. I will remove it and will come back later to the feature 'Jan Deploy as a Server with Dockerfile'. Thank you.
