### ISSUE TITLE
bug: stoping model show starting model in chat

### ISSUE THREAD

**Issue by TC117** [janhq/jan#1606]
**Steps to reproduce**
1. Start some model
2. Open chat
3. click on the hub at the bottom, click the active model to stop model

**Expected behavior**
Show correct message maybe ??

**Screenshots**
![image](https://github.com/janhq/jan/assets/19384189/b4090248-8c85-41e1-add1-0e60184ea167)

**Environment details**
- Operating System: Win10
- Jan Version: Jan v0.4.3-146

**Comment by Van-QA** [comment]
Tested and looking good ✅
