### ISSUE TITLE
feat: automated release notes for nightly build and publish to discord

### ISSUE THREAD

**Issue by hiento09** [janhq/jan#1612]
**Problem**
This feature introduces an automated system for generating release notes for nightly builds and publishing them directly to a designated Discord channel. It streamlines the communication process, ensuring that the latest developments and changes are promptly shared with the team and community

Related #1471

**Comment by 0xSage** [comment]
Still a nice to have :)

**Comment by imtuyethan** [comment]
Related https://github.com/janhq/jan/issues/1471

**Comment by imtuyethan** [comment]
- Deprecated as #4237
