### ISSUE TITLE
feat: implement new settings update

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1616]
Related design ticket of this: #1579 

# Goal 
To reduce users' confusion with Jan settings by restructuring the information architecture of it. 

# Design
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2462-92892&mode=design&t=bQyiFG80Dcr1XlBm-4

New info hierarchry:
- My models
- My Settings 
- Advanced Settings
- Extensions

<img width="868" alt="Screenshot 2024-01-16 at 12 35 21 PM" src="https://github.com/janhq/jan/assets/89722390/965e79c1-2fce-4800-bb76-eba521c6e29b">

## Preview
<img width="876" alt="Screenshot 2024-01-16 at 12 39 00 PM" src="https://github.com/janhq/jan/assets/89722390/848ea8ec-ca73-45b4-a979-37af58408bda">
<img width="913" alt="Screenshot 2024-01-16 at 12 39 30 PM" src="https://github.com/janhq/jan/assets/89722390/1fba6de6-afaf-4c4c-b807-023d6bd31f56">
<img width="884" alt="Screenshot 2024-01-16 at 12 39 45 PM" src="https://github.com/janhq/jan/assets/89722390/8293a8a9-3f13-429f-a110-8976069e633c">
<img width="895" alt="Screenshot 2024-01-16 at 12 40 00 PM" src="https://github.com/janhq/jan/assets/89722390/7053d685-793b-4968-82da-644790ae789c">

**Comment by imtuyethan** [comment]
to be clear @urmauur this ticket is to just revamp the left panel in settings (no need to change anything inside each setting page or add anything further than what we already had)

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.4-163
