### ISSUE TITLE
bug: Update - Update popup is showing "No Update" after users clicked on download in the "There is Update" popup

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1622]
**Describe the bug**
The update popup is showing "No Update" after users clicked on download in the "There is Update" popup. Then the Jan app started the downloads normally.

**Steps to reproduce**
1. Observe the "There is update" popup.
2. Click download 
3. Observe following pop up => there should be no popup after clicking download, but the UI showing "No Update" popup
4. Observe the download bar.

**Expected behavior**
When user see the "There is update popup", there should be no follow up "No update" pop up regardless of what option selected

**Screenshots**
![update](https://github.com/janhq/jan/assets/64197333/20b72c3a-78ae-40b8-82c3-1954699d2061)

**Environment details**
Operating System: MacOS
Jan Version: 0.4.3
Processor: Apple M2 Pro
RAM: 16GB

**Comment by louis-jan** [comment]
The "No update" popup is not working so I disabled it in the upcoming releases. Will add back later with a correct version update check.

**Comment by louis-jan** [comment]
Added back with corrected version cc @Van-QA

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-274 ✅
