### ISSUE TITLE
feat: decouple nitro inference engine into a library

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#1635]
**Problem**
Right now the way to manage nitro process is directly inside nitro extension, it's very bad for devex and also hard to keep track, debug

**Success Criteria**
Decoupled out into a seperate library so that user can just fix nitro library rather than entire extension

**Comment by tikikun** [comment]
@louis-jan can help on prioritize this one, my suggestion is just to commit directly to nitro repo, i think no need seperate repo

**Comment by InNoobWeTrust** [comment]
Second on this, I'm about to make a Raycast front-end UI for nitro, so I prefer to have official node wrapper to be available on NPM so I can add it as a dependency directly in my project. 🤓

https://github.com/InNoobWeTrust/nitro-raycast

**Comment by tikikun** [comment]
hi @InNoobWeTrust i appreciate the raycast front-end

**Comment by louis-jan** [comment]
Thanks, @InNoobWeTrust. I'm going to close this issue, and we will open new issues if needed for bug fixes or improvements.
