### ISSUE TITLE
feat: Jan uninstall should delete appdata folder on Linux

### ISSUE THREAD

**Issue by hiento09** [janhq/jan#1654]
**Problem**
We need an approach to let users clean the AppData folder when they uninstall our application

**Success Criteria**
When users uninstall our Jan app, an option to clear all data should be available for Linux and MacOS

**Comment by hiento09** [comment]
I have not found any solution for macos yet, let's KIV for macos

**Comment by imtuyethan** [comment]
> I have not found any solution for macos yet, let's KIV for macos

I will create a separate ticket for MacOS

**Comment by imtuyethan** [comment]
Ticket for MacOS: https://github.com/janhq/jan/issues/3943

**Comment by imtuyethan** [comment]
Moved this out of v0.5.8 release as we need more time to implement & test it thoroughly.
