### ISSUE TITLE
feat: when creating new thread, cursor should autofocus on message input box

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1658]
Expected: 
1. I click on pencil / start new thread
2. I see an empty thread
3. Expectation: the text input box is focused & selected

ACtual: 
1. I click on pencil
2. I see empty thread
3. I click message box

**Comment by Van-QA** [comment]
@urmauur can you help me double check this? It's not working, the message input is not auto-focused when user creates a new thread

**Comment by urmauur** [comment]
> @urmauur can you help me double check this? It's not working, the message input is not auto-focused when user creates a new thread

<img width="1312" alt="Screenshot 2024-01-29 at 10 59 02" src="https://github.com/janhq/jan/assets/10354610/401c56e9-dba1-4ecb-b420-ca0becd090da">

Tested and works well on my side 🚀
