### ISSUE TITLE
bug: Imported model do not use GPU

### ISSUE THREAD

**Issue by milen-prg** [janhq/jan#1662]
**Describe the bug**
I install the newest Jan version on Windows 11 Pro 64bit, with NVIDIA RTX 3060 12GB. I installed several models from the hub with the application, some of them up to 9GB and they works on GPU fast ans stable.
But I tried to install manually imported model from huggingface, I made the folder with the gguf file, as in the Manual. It is only 7.5GB
It works! BUT, runs entirely on the CPU - CPU=100%, GPU=0%. It is too slow. Another peculiarity is that on the right pannel on the Jan its size not displayed as for the other models.

**Steps to reproduce**
I install manually this model:
https://huggingface.co/TheBloke/PiVoT-0.1-Evil-a-GGUF/tree/main?not-for-all-audiences=true
pivot-0.1-evil-a.Q8_0.gguf

**Expected behavior**
The mode
**Environment details**
- Operating System: Windows 11 Pro 64bit
- Jan Version: 0.4.4
- Processor: Intel Core i5 13400F
- RAM: 64GB
- Any additional relevant hardware specifics: NVIDIA RTX 3060 12GB with last driver and cuda frameworks (v.12.3)

**Comment by Van-QA** [comment]
hi @milen-prg, 
- We are working on the issue of the imported model size: https://github.com/janhq/jan/issues/1647
- About the GPU issue, we will get back to you after an investigation by the dev team.

**Comment by milen-prg** [comment]
I tried several other manual installed models with the same result. At the settings, right most down of the Jan window, the "Number of GPU lauers (ngl)" is 0, but if I set to 1 (then can't return to 0), the GPU also is loaded as the CPU, but the model continues go ultra slow (on CPU).
But what is the difference between the installed from the hub and from other place model?! May be some settings, because, working with CPU is absolutely useless.

**Comment by milen-prg** [comment]
@Van-QA , I found decision:

In the imported model folder, the Jan generated model.json, in which:

  "settings": {
    "ctx_len": 4096,
    "ngl": 0,
    "embedding": false,
    "prompt_template": "{system_message}\n### Instruction: {prompt}\n### Response:"
  },

But i copied the settings from model.json of normal installed via hub model:

  "settings": {
      "ctx_len": 4096,
      "prompt_template": "<|im_start|>system\n{system_message}<|im_end|>\n<|im_start|>user\n{prompt}<|im_end|>\n<|im_start|>assistant"
  },

And, now the manually installed model works fast with GPU!!! Great!
It's size, as before do not showed, but this is no problem at all.

**Comment by Van-QA** [comment]
Thank you, @milen-prg for finding out the workaround solution. There is a mismatch in the generated model.json file :x: . We will correct the default model.json template ASAP.

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.4-163 
Sample generated model.json for imported model

```
{
  "object": "model",
  "version": 1,
  "format": "gguf",
  "source_url": "N/A",
  "id": "trinity-v1-7b-q3",
  "name": "trinity-v1-7b-q3",
  "created": 1706001923574,
  "description": "trinity-v1-7b-q3 - user self import model",
  "settings": {
    "ctx_len": 4096,
    "embedding": false,
    "prompt_template": "{system_message}\n### Instruction: {prompt}\n### Response:"
  },
  "parameters": {
    "temperature": 0.7,
    "top_p": 0.95,
    "stream": true,
    "max_tokens": 2048,
    "stop": [
      "<endofstring>"
    ],
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "size": 3518985920,
    "author": "User",
    "tags": []
  },
  "engine": "nitro"
}
```

**Comment by milen-prg** [comment]
In the new version: Jan Version: 0.4.5, the problem is the same. The two problems with the manually installed models are not fixed!

**Comment by Van-QA** [comment]
@milen-prg, can you help us remove the existing model.json and see if the issue is resolved? A newly imported model should no longer face the issue.
For old model.json, you can manually resolve the issue simply by removing the ngl in the JSON.

**Comment by milen-prg** [comment]
The new auto generated model.json is:

`{
  "object": "model",
  "version": 1,
  "format": "gguf",
  "source_url": "N/A",
  "id": "pivot-0.1-evil-a.Q8_0",
  "name": "pivot-0.1-evil-a.Q8_0",
  "created": 1706521937011,
  "description": "pivot-0.1-evil-a.Q8_0 - user self import model",
  "settings": {
    "ctx_len": 4096,
    "ngl": 0,
    "embedding": false,
    "prompt_template": "{system_message}\n### Instruction: {prompt}\n### Response:"
  },
  "parameters": {
    "temperature": 0.7,
    "top_p": 0.95,
    "stream": true,
    "max_tokens": 2048,
    "stop": [
      "<endofstring>"
    ],
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "size": 7695875104,
    "author": "User",
    "tags": []
  },
  "engine": "nitro"
}`

If I remove the
"ngl": 0,
it works (uses GPU), but the old Thread must be also deleted and started new.
