### ISSUE TITLE
bug: Jan.ai -  Show all search results return "No results were found"

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1675]
**Describe the bug**
The search function in our https://jan.ai/ is not returning any results when users select show all results.

**Steps to reproduce**
1. Go to https://jan.ai/ 
2. Try to search for any keyword
3. Observe the returned results
4. Select shows all results

**Expected behavior**
A list of all results should be fully displayed to users

**Screenshots**
<img width="1127" alt="image" src="https://github.com/janhq/jan/assets/64197333/9efcfe0b-8c2c-4e1d-a013-0f66531eae22">

![Search](https://github.com/janhq/jan/assets/64197333/16b39e28-173e-490d-9c0b-ebff8d4c3d13)

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Comment by hieu-jan** [comment]
@Van-QA Thanks for reporting it. I am debugging this issue.
