### ISSUE TITLE
bug: Failed to fetch 3221225781

### ISSUE THREAD

**Issue by musulkaka** [janhq/jan#1678]
Apologies, something's amiss!

Jan's in beta. Find troubleshooting guides [here](https://jan.ai/guides/troubleshooting) or reach out to us on [Discord](https://discord.gg/AsJ8krTT3N) for assistance.

![image](https://github.com/janhq/jan/assets/157216377/1f9170b5-044a-419b-9baf-01791ed5ebe5)

**Environment details**
- Operating System: [Windows 10]
- Jan Version: [0.4.4]
- Processor: [Intel(R) Xeon(R) CPU E5-2440 0  @ 2.40GHz 6 Cores]
- RAM: [16GB]
- Any additional relevant hardware specifics: [Radeon RX 570 Series]

![image](https://github.com/janhq/jan/assets/157216377/adec4eb0-f7db-47cd-8721-49ff027c7dc0)

server logs - not enough rights

**Comment by chenfengyanyu** [comment]
I encountered the same problem.

**Comment by imtuyethan** [comment]
I was trying to close epic: #1430 
Is there anything we want from the users to debug this?

**Comment by hahuyhoang411** [comment]
@musulkaka Can you try to delete the model and redownload it? I encounter the same issue when my Internet is not stable and the downloaded model file is corrupted.

cc @chenfengyanyu

**Comment by SVA-dev** [comment]
@hahuyhoang411 This will not help, because the program cannot be such that every damaged model is loaded. I've faced this problem too, and it happens to every model.

**Comment by SVA-dev** [comment]
@Van-QA ←[93m\←[94m/←[93m ←[94m ←[93m ←[94m ←[0m
←[0m20240127 08:34:23.177000 UTC 4936 INFO  Nitro version:  - main.cc:44
20240127 08:34:23.178000 UTC 4936 INFO  Server started, listening at: 127.0.0.1:3928 - main.cc:48
20240127 08:34:23.178000 UTC 4936 INFO  Please load your model - main.cc:49
20240127 08:34:23.178000 UTC 4936 INFO  Number of thread is:12 - main.cc:52
20240127 08:34:23.209000 UTC 4936 INFO  Not found models folder, start server as usual - llamaCPP.h:2510

**Comment by Van-QA** [comment]
@SVA-dev Glad to know that your Nitro can start without any issues. 
Please share with us:
* Your OS
* Your spec: CPU serial, memory
By any chance, have you gone through this document? https://jan.ai/troubleshooting/somethings-amiss/

**Comment by SVA-dev** [comment]
@Van-QA 
Windows 10 Pro - 21H1 (64 bit)
CPU - 12th Gen Intel(R) Core(TM) i5-12400F   2.50 GHz
Memory - 16,0 Gb.
Video - GeForce RTX 3060 ti
Version Video Driver - 551.23

**Comment by Glashkoff** [comment]
> Processor: [Intel(R) Xeon(R) CPU E5-2440 0 @ 2.40GHz 6 Cores]

> CPU - 12th Gen Intel(R) Core(TM) i5-12400F 2.50 GHz

I see that in the thread, there may be different issues. Because in the first case, the error is due to Nitro.exe not starting on a Xeon processor without AVX2 instructions. In the second case, it's something else.

**Comment by louis-jan** [comment]
cc @hiro-v, missing VC++ redistributables component.
Related issue #1683

**Comment by louis-jan** [comment]
Please help try this, we will update the installation step / docs on this.
https://github.com/janhq/jan/issues/1683#issuecomment-1925187154

**Comment by louis-jan** [comment]
Addressed in Nightly Build 0.4.6-273
