### ISSUE TITLE
bug: Integration of Azure OpenAI

### ISSUE THREAD

**Issue by burkovae** [janhq/jan#1680]
**Describe the bug**
Integration of the Azure OpenAI api does not work. 
Probably because of missing parameters.

**Steps to reproduce**

[Create a compatible `models.json`](https://jan.ai/guides/using-models/integrate-with-remote-server/#openai-platform-configuration)

When using the Azure service it might look like this

```json
{
    "source_url": "",
    "id": "custom-gpt-35",
    "object": "model",
    "name": "Azure OpenAI GPT 3.5",
    "version": "1.0",
    "description": "",
    "format": "api",
    "settings": {},
    "parameters": {
    },
    "metadata": {
      "author": "",
      "tags": ["General"]
    },
    "engine": "openai",
    "state": "ready"
}
```

with engine settings `openai.json`

```json
{
	"full_url": "https://<domain>.openai.azure.com/openai/deployments/gpt-35-turbo/chat/completions",
	"api_key": "..."
}
```

1. Start a chat with the model
2. See `Resource not found` error

**Expected behavior**
Starts a chat

**Environment details**
- Jan Version: [0.4.4]

**Additional context**

Imho, the issue is that Azure resources require additional parameter e.g.
```json
"api-version": "2023-07-01-preview"
```

See for example this python code:

*without* additional parameters in the post request:
```
>>> params = {
    #'api-version': '2023-07-01-preview'
  }
  r = requests.post(url=f"{endpoint}/openai/deployments/{deployment}/chat/completions", headers=headers, params=params, json=payload)
  print(f"Status code: {r.status_code}")
  print(f"Response body: {r.json()}")

Output: 
Status code: 404
Response body: {'error': {'code': '404', 'message': 'Resource not found'}}

```

*with* additional parameters in the post request:
```
>>> params = {
    'api-version': '2023-07-01-preview'
  }
  r = requests.post(url=f"{endpoint}/openai/deployments/{deployment}/chat/completions", headers=headers, params=params, json=payload)
  print(f"Status code: {r.status_code}")
  print(f"Response body: {r.json()}")

Output:
Status code: 200
Response body: {'id': '...', ...}
```

I think this can be fixed somewhere here:

https://github.com/janhq/jan/blob/42a86e9cb71a195a58d4050b6f8649d080155382/extensions/inference-openai-extension/src/helpers/sse.ts#L27-L40

I'm not a JS dev, but I think that might work?

```
fetch('https://example.com?' + new URLSearchParams({
    'api-version': '2023-07-01-preview' // or any other string from e.g. `${engine.url_params}` ?
}))
```

But of course the parameters for the post request need to be given in either `openai.json` or `model.json`.

What do you think? Thank you!

**Comment by 0xSage** [comment]
@hiro-v iirc, you supported this? Can you help troubleshoot a bit

**Comment by burkovae** [comment]
Yes, thanks! That works!

And if I browse in the repository [there is a hint](https://github.com/janhq/jan/blob/dev/docs/docs/guides/07-integrations/03-integrate-azure-openai-service.mdx). Unfortunatly, I could not find [this doc page](https://jan.ai/guides/integrations/azure-openai-service/) the first time. So I think everything is cleared now.

Thanks a lot; great project!

(the issue can be closed now?)
