### ISSUE TITLE
bug: error loading model : undefined

### ISSUE THREAD

**Issue by Alias4D** [janhq/jan#1683]
**Describe the bug**
error on loading model : undefined

**Steps to reproduce**
1. run Jan
2. select downloaded model tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf
3. write prompt then run

**Screenshots**
![Image 001](https://github.com/janhq/jan/assets/27604791/67e87087-d15c-456e-baaf-ce30f41f08ef)

**Environment details**
- Operating System: [ Windows 10]64-bit operating system
- Jan Version: [e.g., 0.4.4]
- Device name	Ali-VAIO
Processor	Intel(R) Core(TM) i7 CPU       Q 720  @ 1.60GHz   1.60 GHz
Installed RAM	4.00 GB
![SonyVaio](https://github.com/janhq/jan/assets/27604791/ba8351f4-9c16-453d-8d04-1ef0f2800a43)
![Uploading SonyVaio.png…]()

**Logs**
2024-01-20T20:56:23.370Z [NITRO]::CPU informations - 8
2024-01-20T20:56:23.375Z [NITRO]::Debug: Request to kill Nitro
2024-01-20T20:56:23.651Z [NITRO]::Debug: Nitro process is terminated
2024-01-20T20:56:24.166Z [NITRO]::Debug: Spawning Nitro subprocess...
2024-01-20T20:56:24.167Z [NITRO]::Debug: Spawn nitro at path: C:\Users\xxx\jan\extensions\@janhq\inference-nitro-extension\dist\bin\win-cpu\nitro.exe, and args: 1,127.0.0.1,3928
2024-01-20T20:56:26.992Z [NITRO]::Debug: Nitro exited with code: 3221225794
2024-01-20T20:56:26.993Z [NITRO]::Error: child process exited with code 3221225794

**Comment by 0xSage** [comment]
@Alias4D I think we need a bit more logs to properly diagnose, can you paste a bit more lines? Pls redact any personal info.

**Comment by Van-QA** [comment]
Anyone facing the "undefined" issue, please follow this approach:
1. Try wiping the Jan folder, and reopening the Jan app and see if the issue resolved.
2. Go to jan folder / extensions / @janhq / inference-nitro-extension / dist / bin / your OS / nitro => try to start the nitro manually and see if any errors are displayed.
3. Resolve errors from your side until nitro is properly started with no issue.
4. Reopen and double check the Jan app again.

**Comment by Alias4D** [comment]
Thanks for your time 🙏
I try steps above, but

Nitro.exe Application Error
The application was unable to start correctly (0xc0000142). Click OK to close the application.

**Comment by Alias4D** [comment]
Thanks for your time 🙏
I try steps above, but

Nitro.exe Application Error
The application was unable to start correctly (0xc0000142). Click OK to close the application.

**Comment by Van-QA** [comment]
@Alias4D, can you give us the settings.json?

**Comment by Alias4D** [comment]
Where can I find it?

**Comment by Van-QA** [comment]
In the settings folder
<img width="732" alt="image" src="https://github.com/janhq/jan/assets/64197333/3df8e962-04b9-4171-af75-a4b5d33111cf">

**Comment by Alias4D** [comment]
{
  "notify": true,
  "run_mode": "cpu",
  "nvidia_driver": {
    "exist": false,
    "version": ""
  },
  "cuda": {
    "exist": false,
    "version": ""
  },
  "gpus": [],
  "gpu_highest_vram": ""
}

**Comment by zaphodddd** [comment]
1 data point : diagnosing my system here, starting nitro generates "vcruntime140_1.dll missing". 

I'll chase it down / update the machine and report back.  

(it would be helpful for the program to just pass these types of errors back up.)

**Comment by zaphodddd** [comment]
Reporting back
    installing the vcruntime140_1  fixed the error on my Win10 machine.  

-------
Microsoft page for VC++ redistributable
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by louis-jan** [comment]
Thank you @zaphodddd

**Comment by arukompas** [comment]
Got the "undefined" error on MacOS Sonoma, M1 silicon. Deleting the `~/jan` folder completely and restarting Jan helped!

**Comment by louis-jan** [comment]
> Got the "undefined" error on MacOS Sonoma, M1 silicon. Deleting the `~/jan` folder completely and restarting Jan helped!

Thank you, I guess this is related to the backward incompatible model.json issue that has been addressed on Nightly Build 270. cc @Van-QA

**Comment by louis-jan** [comment]
> Reporting back installing the vcruntime140_1 fixed the error on my Win10 machine.
> 
> Microsoft page for VC++ redistributable https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

cc @hiro-v, regarding VC++ redistributables component. Please help on this.

**Comment by louis-jan** [comment]
> 1 data point : diagnosing my system here, starting nitro generates "vcruntime140_1.dll missing".
> 
> I'll chase it down / update the machine and report back.
> 
> (it would be helpful for the program to just pass these types of errors back up.)

Addressed in Nightly Build 0.4.6-273
