### ISSUE TITLE
feat: Jan supports self extend parameters

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1696]
**Problem**
Nitro supports self-extend function so that users can extend every model beyond 4k tokens.

**Success Criteria**
We will have a UI for users to change the model context windows easily.

**Additional context**
Nitro update: https://github.com/janhq/nitro/pull/351/files
Self extend: https://arxiv.org/pdf/2401.01325.pdf

**Comment by imtuyethan** [comment]
deprecated
