### ISSUE TITLE
feat: [Local API server] follow-up with some UX nits

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1697]
There are 7 issues that needs to work on:

# 1. `bug`: after i click "Got it", the server starts & `small enhancement`: Change tip box copy 
Problem:
<img width="644" alt="Screenshot 2024-01-22 at 2 27 27 PM" src="https://github.com/janhq/jan/assets/89722390/093ba228-6a06-4366-941b-e9d6a0dd2ff9">

- **Bug:** Should not start the server when users click on `Got it`
<img width="771" alt="Screenshot 2024-01-22 at 12 16 22 PM" src="https://github.com/janhq/jan/assets/89722390/b3f94f30-66f8-4deb-9637-f52705f836c9">

- **Small enhancement:**
It seems like the tip box is confusing, let's change the copy to `Once you start the server, you cannot chat with your assistant.`
<img width="1423" alt="Screenshot 2024-01-22 at 2 30 45 PM" src="https://github.com/janhq/jan/assets/89722390/ce77148f-4d48-40be-bdce-4cd89b4a2568">

# 2. Server logs should auto-scroll to bottom
Currently, I have to keep scrolling to see the latest messages -> server logs should auto scroll to the bottom.

# 3. Change name to `Local API Server`
<img width="629" alt="Screenshot 2024-01-22 at 2 59 59 PM" src="https://github.com/janhq/jan/assets/89722390/477ffda5-d97d-4456-8467-021c34fce6cf">

<img width="1428" alt="Screenshot 2024-01-22 at 3 00 38 PM" src="https://github.com/janhq/jan/assets/89722390/9966a05d-8c14-49d4-8636-7d8f4a7090b8">

# 4. `Start server` button should be our primary button & goes with the chosen theme
This button should be blue as my current theme is blue:
<img width="1198" alt="Screenshot 2024-01-22 at 3 18 11 PM" src="https://github.com/janhq/jan/assets/89722390/cdd4c27e-032d-46ad-9561-d62551076b54">

# 5. Add tooltip when users cannot change the settings while the server is running:
`Settings cannot be modified while the server is running`

<img width="505" alt="Screenshot 2024-01-22 at 3 32 12 PM" src="https://github.com/janhq/jan/assets/89722390/0b25bc92-83b4-4e2d-9edd-111265302b3c">

# 6. `Server options` is missing
<img width="227" alt="Screenshot 2024-01-22 at 3 25 41 PM" src="https://github.com/janhq/jan/assets/89722390/ebb8cc86-52be-4eef-9c1a-317c3deb2bd4">

# 7. Remove model drop-down
This is my fault, so sorry ( ˘︹˘ )
@urmauur Can you help me remove the model drop-down in model settings:
<img width="1196" alt="Screenshot 2024-01-22 at 12 13 35 PM" src="https://github.com/janhq/jan/assets/89722390/a1360511-e52d-494e-98ef-567f8521f65f">

So it will look like this:
<img width="1424" alt="Screenshot 2024-01-22 at 12 14 50 PM" src="https://github.com/janhq/jan/assets/89722390/023c7def-c169-4b99-a7d7-3044ba6af393">

# 8 Pencil button shoud be hidden
![image](https://github.com/janhq/jan/assets/64197333/64c20e7d-6b36-48a9-8930-062f4b850eef)

# 9 https://github.com/janhq/jan/issues/1697#issuecomment-1903651613
# 10 https://github.com/janhq/jan/issues/1697#issuecomment-1905242257
# 11 https://github.com/janhq/jan/issues/1697#issuecomment-1907600842
# 12 Port range is incorrect
![image](https://github.com/janhq/jan/assets/64197333/1fe482e8-2cef-4bd6-9ced-2fae0ea38e5d)

# 13 https://github.com/janhq/jan/issues/1697#issuecomment-1909730943

# 14 # 15 https://github.com/janhq/jan/issues/1697#issuecomment-1911459168

# 16 https://github.com/janhq/jan/issues/1697#issuecomment-1911460966

**Comment by Van-QA** [comment]
Adding No. 8 for this issue, the pencil should be hidden. Thank you
![image](https://github.com/janhq/jan/assets/64197333/76763970-df47-4e0d-803e-d72616cf00db)

**Comment by Van-QA** [comment]
Adding No.9 disable the remove option of the model that is being used, so far removing an actively used model (by local server), is causing UI glitch with an empty dropdown while the local server is still running
![image](https://github.com/janhq/jan/assets/64197333/ac69420c-372e-4f20-a161-ed5226eaf6e0)
![image](https://github.com/janhq/jan/assets/64197333/504500cc-992b-4c2a-91dd-d456574fedec)

**Comment by Van-QA** [comment]
Adding No. 10 another issue is the model selected in the dropdown can be different from active model
![image](https://github.com/janhq/jan/assets/64197333/731dcb4a-20b8-4238-a480-99f755bec670)

**Comment by Van-QA** [comment]
Adding No. 11 Since the name of the page is Local API Server, we should correct this as well 
![image](https://github.com/janhq/jan/assets/64197333/04f9aada-952e-409c-9b0e-0de1b7d5bc45)

**Comment by Van-QA** [comment]
# 13 User can input text and start server with no warning / error
<img width="323" alt="image" src="https://github.com/janhq/jan/assets/64197333/4b62f34d-70ad-489b-a09c-0a44c0ecc987">

**Comment by Van-QA** [comment]
No 14: on the first time opening the jan app, and visit the local API server, the model setting looks like this, (can be reproduced by wiping the jan folder and open the app)
![image](https://github.com/janhq/jan/assets/64197333/64fa7738-74b8-4dab-96b0-e68f6e71ef37)

No 15
![image](https://github.com/janhq/jan/assets/64197333/fc69e7fe-8698-4da2-bdfb-f4d6be230d74)

**Comment by Van-QA** [comment]
No 16: this server logs header transparent in darkmode but not light mode 

![image](https://github.com/janhq/jan/assets/64197333/8200e173-b0c9-4aa5-a9ed-0500b0c694cb)

**Comment by Van-QA** [comment]
All mentioned issues are resolved ✅ v.0.4.4.195
