### ISSUE TITLE
bug: Error occurred: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

### ISSUE THREAD

**Issue by aquinary** [janhq/jan#1708]
**Describe the bug**
When I try to use chatgpt 3.5 I get the error:
![image](https://github.com/janhq/jan/assets/13851343/b0e82679-54af-4449-8797-18b9f5981c95)

**Environment details**
- Operating System: NixOS
- Jan Version: v0.4.4 appimage
- Processor: Intel Core i5 7400
- RAM: 16G

**Logs**
~/jan/logs/app.log`:
```
2024-01-22T15:26:59.630Z [NITRO]::Debug: Request to kill Nitro
```
... this is the whole log

**Comment by Van-QA** [comment]
@hieu-jan, please help document this issue and solution on our website, thank you.
