### ISSUE TITLE
epic: Fix idling Jan hogging resources

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1714]
## Motivation
- A few reports of Jan v0.4.4 taking up compute and or ram.
- Related to https://github.com/janhq/jan/issues/1650
- Conversation: https://discord.com/channels/1107178041848909847/1197752008568995941
- Related reddit: https://www.reddit.com/r/opensource/comments/198jamd/comment/kisug4x/?context=3&share_id=LhHNxdiS_h7t4OUSgpZ56&utm_content=1&utm_medium=ios_app&utm_name=ioscss&utm_source=share&utm_term=1

## Expected behavior
- Jan shouldn't actively use RAM & CPU when idle
- It could be that users are confusing System Monitor metrics to mean that "Jan is using 80% of my CPU/RAM"
- When, in fact, we're just measuring all RAM usage across all applications.
- Regardless, let's treat this as a performance regression and investigate it as such.

## Outcomes
- Diagnostic on what is consuming RAM
- Diagnostic on what is consuming CPU
- Overview of Jans main processes and % of utilization (when actively being used)
- A list of Jan processes that can improved (regardless if we are being a resource hog or not)

## Scenarios speculation
A) Windows users, no GPU, Jan is idle, no models started
B) Windows users, no GPU, model is started but not inferencing
C) Windows users, no GPU, model is started and actively inferencing

## Specs
- 

## Tasklist
- [x] #1715
- [x] Should Jan system monitor be shown in bottom bar and polling continuously even user are not using it. - @louis-jan @namchuai - https://github.com/janhq/jan/pull/2097 for not 
- [x] #1717
- [KIV] #1716

**Comment by Van-QA** [comment]
Closing this and following up remaining task in https://github.com/janhq/jan/issues/2164
