### ISSUE TITLE
bug: System monitor hogging resources with `os-utils` even it's idle

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1715]
**Describe the bug**
- The system monitoring with CPU/ memory shown in Jan shows that the CPU/ Memory is used even user do not use Jan, which creates the impression that Jan is using resources even being idle

**Expected behavior**
- Determine exactly the app is idle/ not idle in order to monitor correctly (take chrome/ edge as example)
- Do not monitor actively (0.5s). User might need to open resource monitoring in order to see system monitor (which is expected in OS)
- Determine the code in `node-os-utils` is spinning too much subprocesses to grab information or not.
- Let user change the `interval` from default `0.5s` and explain clearly

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by louis-jan** [comment]
Will be addressed by #2039. Let's close this one.
