### ISSUE TITLE
feat: Add resource limit to Jan

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1716]
# Problem 
- Currently Jan automatically get the `logical`/ `physical` CPU count (in case the machine does not have GPU) for model inference, which causes inefficiency.
   - If it's too little, model inference is slow
   - If it's too much (all cores), it will make the system hung up.

# Success Criteria
- Add `Resource settings` to `Settings` to limit the resource use in terms of CPU, memory
    - CPU max = number of logical core (old Intel/ all AMD => = physical core * 2, new Intel => performance core * 2 + efficient core). The default value is the number of physical core in old Intel or performance core in new Intel
    - Memory: It's what it is, default is totalRam / 2
    - Swap: No need to measure now (however will need to do so as this will affect Local model inference speed (Swap -> memory on disk, so normal disk has lower speed compared to RAM)

# Design 
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=4371-210803&mode=design&t=Bx32hqiQbXJYyUti-4

## User flow
See resource allocation item in Advanced settings:

<img width="703" alt="Screenshot 2024-02-15 at 9 36 17 AM" src="https://github.com/janhq/jan/assets/89722390/caaac33b-6f34-4942-a1a5-4626dbf88919">

Users click on settings icon button to adjust: 

<img width="762" alt="Screenshot 2024-02-15 at 9 37 43 AM" src="https://github.com/janhq/jan/assets/89722390/7904d4b0-f3e0-430a-a4ef-b3e94cd6c952">

`Save` button is active once users make any changes: 

<img width="808" alt="Screenshot 2024-02-15 at 9 39 28 AM" src="https://github.com/janhq/jan/assets/89722390/355cba22-80a9-48d4-993a-efbf0e74814a">

New settings is applied:

<img width="728" alt="Screenshot 2024-02-15 at 9 39 34 AM" src="https://github.com/janhq/jan/assets/89722390/7143801d-f4c1-4248-992b-8246f74ed6d9">

**Comment by imtuyethan** [comment]
# Design 
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=4371-210803&mode=design&t=Bx32hqiQbXJYyUti-4

## User flow
See resource allocation item in Advanced settings:

<img width="703" alt="Screenshot 2024-02-15 at 9 36 17 AM" src="https://github.com/janhq/jan/assets/89722390/caaac33b-6f34-4942-a1a5-4626dbf88919">

Users click on settings icon button to adjust: 

<img width="762" alt="Screenshot 2024-02-15 at 9 37 43 AM" src="https://github.com/janhq/jan/assets/89722390/7904d4b0-f3e0-430a-a4ef-b3e94cd6c952">

`Save` button is active once users make any changes: 

<img width="808" alt="Screenshot 2024-02-15 at 9 39 28 AM" src="https://github.com/janhq/jan/assets/89722390/355cba22-80a9-48d4-993a-efbf0e74814a">

New settings is applied:

<img width="728" alt="Screenshot 2024-02-15 at 9 39 34 AM" src="https://github.com/janhq/jan/assets/89722390/7143801d-f4c1-4248-992b-8246f74ed6d9">

**Comment by dan-jan** [comment]
I am removing Resource Limits from this story
https://www.notion.so/jan-ai/Discussion-Fix-idling-Jan-hogging-resources-f521b2504b0f40048255f13330352ff3?pvs=4

**Comment by dan-jan** [comment]
@Van-QA You can close this once ready

**Comment by louis-jan** [comment]
@Van-QA @imtuyethan @dan-jan should we close this? 

> [@Van-QA](https://github.com/Van-QA) You can close this once ready
