### ISSUE TITLE
bug: All hyperlinks is not open as a website and throwing ERROR_FILE_NOT_FOUND in console log 

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1728]
**Describe the bug**
All hyperlinks is not open as a website and throwing ERROR_FILE_NOT_FOUND in console log 

**Steps to reproduce**
1. Click on any hypelink available in the Jan app
- Hub import model
- API reference in local API server 
- Any other hyperlink in model response
2. See error

**Expected behavior**

**Screenshots**
<img width="1231" alt="image" src="https://github.com/janhq/jan/assets/64197333/b7fa1c89-13ed-4910-aa18-1625c4fbe0cd">
![image](https://github.com/janhq/jan/assets/64197333/d58717c3-31fd-450b-927c-cec2ce89a0ad)

<img width="1338" alt="image" src="https://github.com/janhq/jan/assets/64197333/371052b6-b482-45ff-a7d7-d210bfa5f794">

**Environment details**
- Operating System: MacOS
- Jan Version: latest nightly build
- Processor: Apple M2 Pro
- RAM: 16GB

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by hiento09** [comment]
I have tested on Nightly build 0.4.4-170, it works well from my end
![image](https://github.com/janhq/jan/assets/136591877/3f9337ef-4d0c-4402-8385-8dca0cf3bad1)
![image](https://github.com/janhq/jan/assets/136591877/c7ac20c0-e8a9-41d3-9c0f-072241b7cc05)
![image](https://github.com/janhq/jan/assets/136591877/38755e1e-8c97-4b96-9180-2aae577953d6)
