### ISSUE TITLE
feat: Implement import model via adding or dragging & dropping files

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1735]
Epic: https://github.com/orgs/janhq/projects/5/views/16?pane=issue&itemId=48491606

______
# User Flow

## 1. Import Model via GUI:

1. **Initiate Import:** Access the "Import Model" feature through the Jan application interface whether by clicking to add or drag and drop a model file or folder into the application window.

<img width="688" alt="Screenshot 2024-01-24 at 12 27 34 PM" src="https://github.com/janhq/jan/assets/89722390/cb1f2dea-4629-4933-9256-a819ae74fe7b">

<img width="946" alt="Screenshot 2024-01-24 at 12 27 41 PM" src="https://github.com/janhq/jan/assets/89722390/b7d9d77d-367b-4179-996b-e551280da24e">

2. **Automatic Scan (Folder Import):** (_in case users import a folder)_ If a folder is dropped, Jan automatically scans for multiple model files (GGUF format).
#1541 

<img width="833" alt="Screenshot 2024-01-24 at 12 28 14 PM" src="https://github.com/janhq/jan/assets/89722390/b22055ea-5786-4c17-896d-5f78b449841c">

3. **Choose Import Method:**
   - Prompt users to choose their preferred import method:
      - **a. Duplicate Folder:** 
        - If users want to maintain a separate model folder within Jan (may consume additional storage).
      - **b. Use Symlinks:** (#1381) 
        - If users want to avoid duplicating the model folder to save storage (requires understanding symlinks).

<img width="924" alt="Screenshot 2024-01-24 at 12 28 36 PM" src="https://github.com/janhq/jan/assets/89722390/44b18817-32a2-4a0d-94f7-e08978baf747">

4. **Importing model:** Users are presented with an import interface, showing progress, cancel, and remove file options.

<img width="548" alt="Screenshot 2024-01-24 at 12 29 01 PM" src="https://github.com/janhq/jan/assets/89722390/cbdd5590-1335-4ce3-b166-be01d15da9b8">

5. **Autogenerated `model.json` (Folder Import):** For each model found, Jan generates a corresponding `model.json` in Jan Data Folder.

6. **Optional Model Configuration:** Users have the option to fill in additional properties in the `model.json` for more detailed configurations.

<img width="901" alt="Screenshot 2024-01-24 at 12 29 54 PM" src="https://github.com/janhq/jan/assets/89722390/3439b8fd-4a83-4a16-8688-ecdeca1debd9">

## 2. Import Model Manually 

- For users who manually add models located at specific paths (for example: User opts to add only the model located at /random_path/model to Jan), Jan won't automatically scan these models every time you open the app.

- For this case: Users need to use the "Refresh" button to manually re-scan and integrate any models they have manually added outside of the automatic scanning process.

<img width="853" alt="Screenshot 2024-01-24 at 12 40 27 PM" src="https://github.com/janhq/jan/assets/89722390/e677569f-99fe-42a9-a59c-b595c227ef7e">

# 6. Design
Figma link: 
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2160-165286&mode=design&t=TdZv1LIEiCArXNOZ-4

**Comment by namchuai** [comment]
@Van-QA , please help to validate this issue. Thank you!

**Comment by Van-QA** [comment]
Need updated copy since we no longer support folder import cc: @louis-jan @imtuyethan

**Comment by namchuai** [comment]
@Van-QA , please help to retest this issue. I fixed those.

One note that I checked that we can grab the absolute URL from folder, so I allow user to drag a folder but filter out the blob which not ended with `.gguf`.

**Comment by Van-QA** [comment]
@namchuai 
1. When dragging a folder containing one gguf file and other files, it shows an error message and still allow import only the gguf file. This seems okay, but the message might not be clear enough. So, it should say, "only files with .gguf extension can be imported." If everyone is okay with it, then there's no need to fix it. :x:
![image](https://github.com/janhq/jan/assets/64197333/c1df39f1-c494-42c8-a388-91561803e197)

2. If dragging a folder is possible, you should be able to select as well. But now, when trying to select a folder, it seems to open the folder instead of selecting it. So far users can't select a folder through the file explorer. :x:
![image](https://github.com/janhq/jan/assets/64197333/47dc40c4-ace1-45e6-8618-637e6b41e1f2)

3. Please add a missing space between Format:GGUF :x:
![image](https://github.com/janhq/jan/assets/64197333/3dbdaddc-3f21-44eb-8b55-43b02d3f1eb4)

**Comment by namchuai** [comment]
@Van-QA , please retest. Thank you!

**Comment by Van-QA** [comment]
Tested and looking good on Jan 0.4.7-304 ✅
