### ISSUE TITLE
feat: Import public model via Huggingface URL

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1740]
Specs: https://www.notion.so/jan-ai/Model-Hub-can-Import-from-HuggingFace-225dd4da88944bc183b816922c3333a8?pvs=4

______
# User Flow: Import Model via Huggingface URL

1. **Copy Huggingface URL & Paste into Search Bar:** Copy the link of the model repo from Huggingface, pasting it to search bar in Hub or My models page.

<img width="919" alt="Screenshot 2024-01-24 at 2 00 47 PM" src="https://github.com/janhq/jan/assets/89722390/3f27a279-f17b-452f-bfaa-6deb08b0eb0f">

2. **Repo Search:** Jan will automatically search the repository linked to the provided Huggingface URL.

3. **Scan for GGUF Files:** The application scans for available GGUF files associated with the provided Huggingface model.

<img width="912" alt="Screenshot 2024-01-24 at 2 01 19 PM" src="https://github.com/janhq/jan/assets/89722390/acce64dd-7521-4af2-aaf6-f7a1a2d2d7aa">

4. **Model Card  & Files Preview:** You'll see a nicely-formatted model card reflecting all available model files to decide which one you want to import to Jan.

<img width="866" alt="Screenshot 2024-01-24 at 2 02 11 PM" src="https://github.com/janhq/jan/assets/89722390/a26f0f43-f06e-4b26-9425-3bcb4efe22c5">

5. **Import and Generate `model.json`:** Jan proceeds to download the identified files and generates the necessary `model.json` for seamless integration. 

# 6. Design
Figma link: 
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=3009-127260&mode=design&t=ZlK57CWtREqzmEZu-4

**Comment by Van-QA** [comment]
@namchuai 
1. Correct downloaded to Use button
![image](https://github.com/janhq/jan/assets/64197333/b5c37684-1c6b-492d-8668-6e34da34b6af)

2. Loader icon 
![loadHF](https://github.com/janhq/jan/assets/64197333/d907c6bc-1849-426d-a3a8-9de365e5f883)

3. Allow pressing Enter to reload the URL to view the popup
![image](https://github.com/janhq/jan/assets/64197333/0f82833a-08e5-4879-95ab-457c070047ed)

**Comment by Van-QA** [comment]
Duplicate HF model id input :x: need clearer msg @namchuai, thank you
![image](https://github.com/janhq/jan/assets/64197333/b63fcef8-cf3d-4b00-a2ba-81a85978722f)
