### ISSUE TITLE
feat: Users should be able to edit messages

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1744]
Epic: Threads Improvement #1507 

______
# Specs & Design

Figma link: 
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=3624-167353&mode=design&t=3XalkA6NVYOqVenZ-4

### 1. Users should be able to see the "Edit" option when they **hover** on the messages they have sent.

![Image](https://github.com/janhq/jan/assets/89722390/d10b40c3-4570-4374-8846-5c4e0e398ce3)

### 2. Click edit -> be able to edit the message -> Can submit the revised version or cancel

![Image](https://github.com/janhq/jan/assets/89722390/4154e2ad-5efe-4bce-b910-c549223525a4)

### 3. Once submit, latest messages below the edited message will be gone and the assistant will re-generate the answer based on the edited version of the message

![Image](https://github.com/janhq/jan/assets/89722390/0c9da99c-beae-436f-a221-644a41cf166e)

**Comment by Hugi-R** [comment]
It would be nice if we could also edit the response of the assistant.
It's a very powerful tool: if the assistant got a few facts wrong, it's easier and more efficient to correct manually the response. Then continue the conversation like normal.
It's something I do a lot with llama.cpp server in "Completion" mode, and smaller models really need it to be useful.

**Comment by Van-QA** [comment]
hi @namchuai 
1. Please help correct this issue where trying to edit another message, is only closing the currently editing msg. Users will have to click edit the 2nd time to continue editing :x: 
![Image](https://github.com/janhq/jan/assets/64197333/ab65ab8a-9f09-497e-9b78-692f01338c91)




2. On the other hand, when editing a msg without submission, switching to a new thread and going back, the currently editing message is reverted back to before the edit, so any changes made by users in the edit box will be gone❓is this expected, @imtuyethan

**Comment by imtuyethan** [comment]
1.
- I edit message A -> don't choose "Submit"
- Click on edit message B -> edit message A should be automatically closes

2. This is expected

**Comment by Van-QA** [comment]
for #2 currently users will have to click twice, when moving from one editing box to another.
1st click only close the current editing
2nd click will open new editing
=> need correction as well

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-280 ✅

**Comment by Van-QA** [comment]
@imtuyethan to answers this question, thank you

> > It would be nice if we could also edit the response of the assistant. It's a very powerful tool: if the assistant got a few facts wrong, it's easier and more efficient to correct manually the response. Then continue the conversation like normal. It's something I do a lot with llama.cpp server in "Completion" mode, and smaller models really need it to be useful.
> 
> I wonder if there's another issue tracking this request or if this isn't currently being considered? Checked the latest nightly and I see we can only edit the user's input.
