### ISSUE TITLE
bug: Cannot load gpt-4-turbo

### ISSUE THREAD

**Issue by gaardhus** [janhq/jan#1748]
**Describe the bug**
I'm trying to use the OpenAI gpt-4-turbo endpoint, but I'm getting an error.

**Steps to reproduce**
1. Create a folder named `gpt-4-turbo` in `~/jan/models/` 
2. Create `model.json` with the following content:
```
{
    "source_url": "https://openai.com",
    "id": "gpt-4-turbo",
    "object": "model",
    "name": "OpenAI GPT 4 Turbo",
    "version": "1.0",
    "description": "OpenAI GPT 4 turbo model is extremely good and super fast",
    "format": "api",
    "settings": {},
    "parameters": {},
    "metadata": {
      "author": "OpenAI",
      "tags": ["General", "Big Context Length"]
    },
    "engine": "openai",
    "state": "ready"
}
```
3. Restart jan
4. Create a new conversation and select `OpenAI GPT 4 turbo`
5. The model responds with a message saying that `The model gpt-4-turbo does not exist`

**Expected behavior**
A functioning connection to the openai endpoint.

**Screenshots**
![image](https://github.com/janhq/jan/assets/46934916/a65b30bf-1695-438e-8b61-e287be2831ee)

**Environment details**
- Operating System: Arch Linux 6.7.0-arch3-1
- Jan Version: 0.4.4
- Processor: Ryzen 7 PRO 7840U w/ Radeon 780M Graphics (16)
- RAM: 32GB

**Comment by Van-QA** [comment]
hi @hieu-jan, https://jan.ai/guides/using-models/integrate-with-remote-server/ , can we add the link to the open API version list to our doc?

@gaardhus, you will need to provide the correct name of the openAI GPT version that you want https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

**Comment by gaardhus** [comment]
My bad! I thought that a: they had aliased the endpoint to also include gpt-4-turbo, and that I had also unsuccesfully tried the gpt-4-1106-preview endpoint. It works now however. I would probably suggest including it as a default model though. Thanks for the quick reply.

**Comment by Sneakr** [comment]
> My bad! I thought that a: they had aliased the endpoint to also include gpt-4-turbo, and that I had also unsuccesfully tried the gpt-4-1106-preview endpoint. It works now however. I would probably suggest including it as a default model though. Thanks for the quick reply.

Can you show me your json file? Wierdly I only get response like this when I ask what version of GPT it uses it does not recognize the GPT4:   

"I operate on the same technology, which is based on the GPT-3 model. Is there something specific you'd like to know or do?"

Here's my json file:
{
	"sources": [
		{
			"filename": "openai",
			"url": "https://openai.com"
		}
	],
	"id": "gpt-4-0125-preview",
	"object": "model",
	"name": "OpenAI GPT 4.5 Turbo",
	"version": "1.0",
	"description": "OpenAI GPT 4.5 Turbo model is extremely good",
	"format": "api",
	"settings": {},
	"parameters": {},
	"metadata": {
		"author": "OpenAI",
		"tags": [
			"General",
			"Big Context Length"
		]
	},
	"engine": "openai"
}
