### ISSUE TITLE
Error occurred: Unexpected token '<', "<!DOCTYPE "... is not valid JSON 

### ISSUE THREAD

**Issue by constantin-online** [janhq/jan#1749]
Error occurred: Unexpected token '<', "<!DOCTYPE "... is not valid JSON

Что мне делать?
![image](https://github.com/janhq/jan/assets/83284397/e1c6e4c1-773b-43be-91cd-7a1716aaea04)

**Comment by DarthBarada** [comment]
@constantin-online Привет, тебе нужно выбрать в правой части окна модель и ввести API ключ, либо же установить Open Source модель.

**Comment by constantin-online** [comment]
как мне выбрать Open Source модель?
Я готов помочь с переводом на русский язык ,вашей программы

**Comment by Van-QA** [comment]
@constantin-online  Please try this guideline: https://jan.ai/troubleshooting/unexpected-token/

**Comment by constantin-online** [comment]
я не понимаю какую модель мне скачивать не имея ключа.

**Comment by Van-QA** [comment]
hi @constantin-online the API Key are required for OpenAPI GPT model only (with subscription required).
Feel free to download any model that is suitable for you in our Hub, may be starting with the smallest one 
<img width="1212" alt="image" src="https://github.com/janhq/jan/assets/64197333/3cd19ecb-6b36-4f95-8f82-4e9d83d7478a">

**Comment by constantin-online** [comment]
![image](https://github.com/janhq/jan/assets/83284397/73500f04-3b81-4dfe-b525-db47852e1b4d)

**Comment by Van-QA** [comment]
@constantin-online  please try this: https://jan.ai/troubleshooting/somethings-amiss/

**Comment by imtuyethan** [comment]
@constantin-online Please share your app logs

**Comment by Van-QA** [comment]
@constantin-online Can you double check our nightly build to see if the issue is resolved or not? many thanks
