### ISSUE TITLE
bug: Correct text for Windows

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1758]
**Describe the bug**
In Windows, we don't have `Finder`

**Steps to reproduce**
1. Open App
2. Click on the expand setting of `Threads` or` Asisstant`
3. See error

**Expected behavior**
It should show `Show in File Explorer`

**Screenshots**
![image](https://github.com/janhq/jan/assets/64120343/f3860751-ee9c-41a1-b5e2-8d76f50d27c2)

**Environment details**
- Operating System: Win10
- Jan Version: v0.4.4-171

**Comment by namchuai** [comment]
@Van-QA , please help to verify this issue. Thank you!

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.5-212 ✅ 


<img width="510" alt="image" src="https://github.com/janhq/jan/assets/64197333/adb94d96-07ff-4f80-8fc4-6ae94fbed5c5">
