### ISSUE TITLE
bug: Start model button in My Models doesn't work

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#1770]
**Describe the bug**
I start the downloaded model in My Model tab but it doesn't respond

**Steps to reproduce**
1. Go to `Settings`
2. Go to `My Models`
3. Click on `Start model`
4. Nothing happened

**Expected behavior**
It would start the model

**Screenshots**
![image](https://github.com/janhq/jan/assets/64120343/f9d9c373-1953-4349-a280-1da82c487e1e)

**Environment details**
- Operating System: Win 10
- Jan Version: v0.4.4-176

**Comment by hahuyhoang411** [comment]
Also the `Delete Model` button doesn't work too

![image](https://github.com/janhq/jan/assets/64120343/a64c50c5-9fbe-4a4f-82fb-2e4ea21c309a)

**Comment by Van-QA** [comment]
Tested and looking good using Jan v0.4.4-190 ✅
