### ISSUE TITLE
feat: Install Jan AI using the Homebrew package

### ISSUE THREAD

**Issue by lgrardin** [janhq/jan#1776]
Hello Jan AI Developers,

I hope this message finds you well. I wanted to reach out to express my appreciation for the work you've put into developing Jan AI. It's a fantastic tool that has proven to be invaluable.

I have a quick question regarding the installation process. Is there a way to install Jan AI using the Homebrew package manager with a command like "brew install --cask"?

Thanks !

**Comment by Van-QA** [comment]
Linking to this PR: https://github.com/Homebrew/homebrew-cask/pull/168215

**Comment by Van-QA** [comment]
Currently, our homebrew only supports Mac Silicon ✅, we need:
1. Brew should support multiple architectures:
```
cask "visual-studio-code-insiders" do
  cpu :intel do
    version "1.53.0,6dc779565e1e4a26104002fde340b68c157c3bc5"
    sha256 "ea08cd72f7501223d1c888b300bd961df27e80558e4e51c868740f651f3912ce"
    ""
  end

  cpu :arm do
    version "1.53.0,e17aea136d32fdb06d9b32184b04ccd36bb51e9c"
    sha256 "3f9bdb6867636cc9116d96a09aef53a927e1636609df33bfe23a1275107a04b6"
    "-arm64"
  end

  cpu # Need to call `cpu` method to initialize `version`

  url "https://az764295.vo.msecnd.net/insider/#{version.after_comma}/VSCode-darwin#{cpu}.zip",
      verified: "az764295.vo.msecnd.net/insider/"
  # ...
end
```
2. Cleanup the uninstallation steps, @louis-jan

**Comment by lgrardin** [comment]
Thank you very much, it's great! See you soon.

**Comment by 0xSage** [comment]
stale, and likely wont do

**Comment by o6uoq** [comment]
`brew` is the best and most popular package manager for macOS. When can we see this added? Are you open to forked PRs if someone from the community wants to do this for you?
