### ISSUE TITLE
bug: app log is missing

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1778]
**Describe the bug**
I started a model but could not find my app log in Jan Data Folder
<img width="943" alt="Screenshot 2024-01-25 at 6 34 35 PM" src="https://github.com/janhq/jan/assets/89722390/7105834f-6e67-44f4-b2d5-8ea1edb33ca7">

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: 0.4.4-178
- Processor: Apple M2
- RAM: 6GB

**Comment by Van-QA** [comment]
Tested and looking good using Jan v0.4.4-190 ✅
