### ISSUE TITLE
feat: log file limitation (should only keep logs within 24h)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1785]
# Problem
Regarding this report: https://discord.com/channels/1107178041848909847/1199749558650011688/1199749558650011688
<img width="899" alt="Screenshot 2024-01-25 at 9 11 26 PM" src="https://github.com/janhq/jan/assets/89722390/ff2da876-6196-4780-8519-f1b40bb7d6b2">

# To do
- Limit logs history within 24h 

I think 24h-log is enough to debug any issue if users report it immediately. 
On that note, we will change the "something's amiss" error copy to better inform users via this related ticket: #1784

**Comment by Van-QA** [comment]
Address in #2003 cc: @louis-jan 
Feel free to reopen this if there is any concern.
