### ISSUE TITLE
Other AI models

### ISSUE THREAD

**Issue by Articmar** [janhq/jan#1797]
Please add to the Jan program and the JanHub repository, other AI models. For example: "Deep Image Prior (DIP)", "Deep Artifacts Removal (DARNet)", "ESRGAN", etc. Maybe some more for working with audio or video.

**Comment by 0xgokuz** [comment]
I believe https://github.com/janhq/models is the Repo?

**Comment by Articmar** [comment]
> @Articmar I don't really understand your request. Could you clarify more

The application currently supports only text-based neural networks. But there are neural networks that work with images, audio or video. 
But there are no such neural networks in Jan, so I ask to add such neural networks to the program.

**Comment by Vigilence** [comment]
Support for cog and llava would be great!

**Comment by imtuyethan** [comment]
Hi @Articmar! This will gonna take quite long time to build everything. Short-term roadmap would be RAG (text based) & vision. I move your product request here for further future discussion: https://discord.com/channels/1107178041848909847/1204368788234174534 & closing this ticket. Thanks for using Jan!
