### ISSUE TITLE
bug: Thread History - Focused thread should be preserved when switching back and forth between Jan Pages

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1811]
**Describe the bug**
Focused thread should be preserved when switching back and forth between Jan Pages, currently, it's auto-focusing on the first thread regardless the previous selection of users

**Steps to reproduce**
1. Selected view any old thread
2. Visit another page and go back
3. Observe the focused thread

**Expected behavior**
The selected thread should remain unchanged when users re-visit the thread page

**Screenshots**

<img width="547" alt="image" src="https://github.com/janhq/jan/assets/64197333/a3ea2654-5303-4db9-b9bb-8d75948170c0">

**Environment details**
- Operating System: MacOS
- Jan Version: latest nightly build
- Processor: Apple M2 Pro
- RAM: 16GB

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by namchuai** [comment]
Moving milestone to 0.4.6 since 0.4.5 has been released.

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.5-198 ✅
