### ISSUE TITLE
bug: asterixes (*) in comments are replaced by numbers

### ISSUE THREAD

**Issue by freerider7777** [janhq/jan#1815]
I paste some java code to ask a question and asterixes are replaced by numbers
  /**
   \* Create converter.
   \*
   \* @param objectMapper json converter
   \* @param trustedMessages trusted messages
   \*/

and the submitted result is:

![image](https://github.com/janhq/jan/assets/6572573/24ab8747-c81f-4b3b-acc4-190387b86c21)

**Comment by Van-QA** [comment]
The issue is reproducible, assigning dev to have a look.
<img width="1316" alt="image" src="https://github.com/janhq/jan/assets/64197333/cf97c874-b2e3-4283-931e-e8d86db1e477">

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-267 ✅ 

![Image](https://github.com/janhq/jan/assets/64197333/15b05844-49ea-486b-a64f-48c7db1702f7)
