### ISSUE TITLE
How to install it on disk D in Windows?

### ISSUE THREAD

**Issue by Vladislav2018** [janhq/jan#1816]
I have very limited memory on my C drive. I can’t afford to install programs, much less models, on the C drive, how can I install them on the D drive?

**Comment by fu3fi** [comment]
Another issue
https://github.com/janhq/jan/issues/1010

**Comment by YoLolo69** [comment]
It will be interesting to be able to install jan itself in another drive than default C:, not only moving later the data folder like #1010 track...

**Comment by fu3fi** [comment]
I think the creator understands this, it’s just a beta, don’t judge strictly)

**Comment by 0xSage** [comment]
<img width="1199" alt="image" src="https://github.com/janhq/jan/assets/69952136/6989cc03-e334-44d1-af73-0959e15f4a14">
1. Get on nightly builds
2. Turn on experimental features
3. Voila
