### ISSUE TITLE
Api doesnt respond to created messages(is it must respond?)

### ISSUE THREAD

**Issue by errorman-awful** [janhq/jan#1817]
I've making create message request to thread,get 200 status,but model doesnt generate response,and i cant retreive it,what am i doing wrong?

**Comment by Van-QA** [comment]
@errorman-awful  Can you give us your curl? along with your app.log?

**Comment by imtuyethan** [comment]
Hey please share your app logs, otherwise we will close this issue after 1 month

**Comment by louis-jan** [comment]
Generate response is on another endpoint (/v1/chat/completion), we haven't supported chained requests like this yet.
