### ISSUE TITLE
bug: [Rtx 4050 GPU don't run]

### ISSUE THREAD

**Issue by cccman9194** [janhq/jan#1819]
**Describe the bug**
After installed and download Models,
I was activated Rtx 4050 in advanced.
But can't run prompt.
How can i fix it?

**Comment by freerider7777** [comment]
same on NVIDIA GeForce RTX 3050 4GB Laptop GPU
models not working

![image](https://github.com/janhq/jan/assets/6572573/3f25ec6e-58ad-4967-afe0-ac8021995263)

**Comment by Van-QA** [comment]
Please help us by providing the app.log for troubleshooting: https://jan.ai/troubleshooting/how-to-get-error-logs/

**Comment by imtuyethan** [comment]
Hey please share your app logs, otherwise we will close this issue after 1 month

**Comment by freerider7777** [comment]
Today an update has arrived - seems to work fine! Thanks for your work! :)
Tested on Deepseek coder 1.3 and Openchat-3.5 7B Q4

**Comment by freerider7777** [comment]
Deppseek Coder 33B Q5 not working
[app.log](https://github.com/janhq/jan/files/14184616/app.log)

**Comment by cccman9194** [comment]
I was solved RTX 4050 issue.
Firstly update NVIDIA graphic driver.
Next, install NVIDIA CUDA driver.
Installation of CUDA is essential.

2024년 1월 31일 (수) 오후 4:20, Van Pham ***@***.***>님이 작성:

**Comment by cccman9194** [comment]
I was solved RTX 4050 issue.
Firstly update NVIDIA graphic driver.
Next, install NVIDIA CUDA driver.
Installation of CUDA is essential.

2024년 2월 6일 (화) 오후 8:36, Ashley ***@***.***>님이 작성:

**Comment by cccman9194** [comment]
I was solved RTX 4050 issue.
Firstly update NVIDIA graphic driver.
Next, install NVIDIA CUDA driver.
Installation of CUDA is essential.

**Comment by Van-QA** [comment]
thank @cccman9194, we will make sure the solution is noted in our document. Hence closing this one, as you already created another one for the solution: https://github.com/janhq/jan/issues/1946.
