### ISSUE TITLE
feat: [Adding gpt4-turbo]

### ISSUE THREAD

**Issue by mbido** [janhq/jan#1825]
**Problem**
I wanted to use the new gpt-4-0125-preview model which is a gpt4 turbo model but I can't.

**Success Criteria**
It would be nice if you can add this model to jan

**Comment by Van-QA** [comment]
@mbido  Did you tried this guideline: https://jan.ai/guides/using-models/integrate-with-remote-server/#tag/Threads/operation/deleteThread

**Comment by mbido** [comment]
Thanks a lot it worked ! And sorry for annoying you ;)

**Comment by rorallo** [comment]
I think the link is 404ing now
