### ISSUE TITLE
2 x 4090 setup in Docs -> Hardware

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#183]

**Comment by 0xSage** [comment]
Repro: LinkUp Riser connected to one 4090 only, slot 0

Issue: bandwidth is downgraded due to an incompatibility issue

    LnkCap: Port #0, Speed 16GT/s, Width x16, ASPM L1, Exit Latency L1 <16us
    LnkSta: Speed 2.5GT/s (downgraded), Width x16 (ok)

![image](https://github.com/janhq/jan/assets/69952136/7260a0cb-561f-4869-bdc3-a939f3b869ba)

**Comment by dan-jan** [comment]
May be related to power saving mode. We should run perf tests tomorrow

https://support.lenovo.com/sg/en/solutions/ht513323-gpu-pci-link-speed-downgrades-to-generation-1-lenovo-thinksystem

https://forums.developer.nvidia.com/t/not-getting-full-bandwidth-pcie-transfers/232317

**Comment by 0xSage** [comment]
Closing this issue for now. Not critical, demand not verified.
