### ISSUE TITLE
docs: Jan Server Suite docs (Dockerfiles/Helmchart Deployment)

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1835]
**Pages**
- A way to deploy Jan Server via tool/docs (1 click deployment - 
<img width="368" alt="Screenshot 2024-01-29 at 14 08 27" src="https://github.com/janhq/jan/assets/133622055/005f205c-0c52-4187-80b9-30f65fd5ff86">

**Success Criteria**
Content that should be covered

**Additional context**
Examples, reference pages, resources

**Comment by 0xSage** [comment]
A Jan Homeserver Guide

**Comment by 0xSage** [comment]
@hiento09 are you the one to take this or @hieu-jan ?

**Comment by louis-jan** [comment]
@hiento09, please take ownership of the first draft and collaborate with @hieu-jan afterwards for a publishable version 🚀

**Comment by hiento09** [comment]
Sure @0xSage , @louis-jan
