### ISSUE TITLE
feat: Users can go to `jan.intranet.com` and be able to use Threads/Assistants

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1836]
**Problem**
There would be a homeserver setup step when user accessing jan.intranet.com. Deploy Jan as a GUI client.

<img width="608" alt="Screenshot 2024-01-29 at 14 11 01" src="https://github.com/janhq/jan/assets/133622055/cb4ff560-2972-4f56-a4b1-11eccaeda33c">

**Success Criteria**
Users can go to `jan.intranet.com` and be able to use Threads/Assistants

**Additional context**

**Comment by imtuyethan** [comment]
Close as deprecated
