### ISSUE TITLE
feat: Revamp System monitoring UI - Reduce system information requests

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1838]
# Problem
App displays system informations in the footer bar, which send a lot of requests during app cycle. Should revamp the UI to have expand / collapse section so users can access from anywhere but still ensure the performance.

# Design 
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=4427-325119&mode=design&t=LbqHwgt8zLarODK6-4

- Remove system monitor on the left ribbon
- Move system monitor on the footer 
- Users can only see CPU, mem, GPU metrics when they expand the footer. Reason: to reduce the number of requests sent during app cycle in Jan Server.

#### Users click on `system monitor` to view the metrics:

<img width="638" alt="Screenshot 2024-02-15 at 9 34 38 PM" src="https://github.com/janhq/jan/assets/89722390/264d3851-fde9-4db8-bc3b-b82f446e08c8">

#### System monitor includes running models & activity metrics as below, and users can expand the panel or adjust the size of the panel:

<img width="888" alt="Screenshot 2024-02-15 at 9 34 47 PM" src="https://github.com/janhq/jan/assets/89722390/5ec33457-d470-4046-a072-04f864d4f046">

**Comment by imtuyethan** [comment]
This is also part of the epic #1236

**Comment by imtuyethan** [comment]
Implemented
