### ISSUE TITLE
bug: undefined

### ISSUE THREAD

**Issue by JasonDeving** [janhq/jan#1840]
when try to type something it says undefined.

**Expected behavior**
can't load the llm

**Screenshots**
doesn't work

**Environment details**
- Operating System: windows 10
- Jan Version: 0.4.5
- Processor: AmD ryzen 5600x
- RAM: 16gb
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

![und](https://github.com/janhq/jan/assets/11493917/6b50b375-6afd-4942-975b-bb34449712c1)

**Comment by Van-QA** [comment]
hi @JasonDeving, Please try this workaround solution if your path includes non-latin characters. https://github.com/janhq/jan/issues/1713#issuecomment-1912330258

**Comment by Van-QA** [comment]
Addressed in 0.4.7, feel free to reopen this if the issue persist
