### ISSUE TITLE
feat: Jan API - Add start/stop model apis

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1843]
**Problem**
There are missing APIs and inconsistent with the API docs, please help support this.

**Success Criteria**
- User can make a request to /model/{model_id}/start to load and run a model
- User can make a request to /model/{model_id}/stop to unload and stop a running model

**Additional context**

**Comment by namchuai** [comment]
This issue is fixed. I will close it because we can test the whole epic #1078
