### ISSUE TITLE
HTML Code interpreted instead of shared

### ISSUE THREAD

**Issue by toto-polo** [janhq/jan#1849]
**Describe the bug**
When the user shares html content, or when the user requests to produce html code, some parts are interpreted instead of  just be shared. See above

**Steps to reproduce**
Share html content and see some parts being showed as in a web page.

<img width="774" alt="screenshot code jan" src="https://github.com/janhq/jan/assets/39052403/11d356a8-ebf7-4d07-bdc6-9991352cd3f6">

<img width="1360" alt="screenshot jan" src="https://github.com/janhq/jan/assets/39052403/a55ff49d-ecfd-4464-b381-f8cf5cfaaed3">

**Expected behavior**
Just show the raw code

**Environment details**
- Operating System: MacOS
- Jan Version: [e.g., 0.4.5]
- Processor: intel or mac m3 

- RAM: 40 GB

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-267 ✅


<img width="712" alt="image" src="https://github.com/janhq/jan/assets/64197333/1458ba5c-07b3-482b-bfe1-ff236f4b9af8">

**Comment by GlobalAIVision** [comment]
V0.4.11, the bug still happened to me, while i was using Mixtral 8x7B Instruct Q4 model.
I asked to generate HTML, it generated the code but he also interpreted it, changing the JAN BG color and text color!
Thus, the generated html was invisibile, i can only see it when i click on the copy answer button and paste in notepad.
