### ISSUE TITLE
bug: [API] chat completions

### ISSUE THREAD

**Issue by LeGitHubDeTai** [janhq/jan#1852]
**Steps to reproduce**
Make an API request with the stream mode set to true.

**Expected behavior**
When I make a request to v1/chat/completions with the stream mode set to true, everything works correctly. However, when it is set to false, the computer becomes overloaded, and no response is received from the API (worked in 0.4.4).

**Environment details**
Operating System: Windows 11
Jan Version: 0.4.5
Processor: Intel Core i9
RAM: 64GB
Any additional relevant hardware specifics: RTX 3090

**Comment by Van-QA** [comment]
hi @LeGitHubDeTai, sorry for the inconvenience. The issue may be related to this https://github.com/janhq/jan/issues/1771. which we are still working on it.

**Comment by LeGitHubDeTai** [comment]
ow my bad sorry

**Comment by Van-QA** [comment]
hi @LeGitHubDeTai, we resolved the issue, and I tested both UI and the curl with Stream = false ✅ Jan v0.4.5-215 
<img width="1463" alt="image" src="https://github.com/janhq/jan/assets/64197333/e6373050-6c0f-4a98-abf3-9dc1d70eb36b">
Feel free to reopen this if the issue persists.

**Comment by LeGitHubDeTai** [comment]
thanks !
