### ISSUE TITLE
Jan Desktop App UI

### ISSUE THREAD

**Issue by drakehere** [janhq/jan#186]
**User Story**
Users are able to:
- Download a model
- Run a model
- Uninstall a model

**Figma:**
https://www.figma.com/file/JdK7cNIBeVdYeHxKiYeWtk/JAN---Web?type=design&node-id=2636-39913&mode=design

**Comment by 0xSage** [comment]
@drakehere can you show a loading state from when: 
1. User already has 2-3 model installed
2. User is switching from using 1 model into using another model
3. It takes a few seconds (up to a few minutes) to unload and load a new model into memory. 

Can you render some loading elements into the current design? Thank you

**Comment by 0xSage** [comment]
Thsi is done
