### ISSUE TITLE
bug: RAG - Stuck in generating response and other related glitchs

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1865]
**Describe the bug**

# 1. Pipeline issue - Nightly build are not able to run RAG:

VDB we are using in this MVP - HNSWLib is not universally built to distribute.

# 2. Unable to *regenerate* the RAG response using the reload button:
Stuck in generating w/o any details added to App.log, users stuck in this state indefinitely, can not regenerate the RAG reponse.

# 3. With Retrieval ON - Glitch when switching to another page and back, the selected model does not preserved.
<img width="315" alt="image" src="https://github.com/janhq/jan/assets/64197333/e89d0485-22de-4978-a746-923ea8d491d0">
The model selector also glitched and showed choose model to start when there is already an active model.

# 4. Moving RAG to experimental feature

# 5. Opening the uploaded file:
- The label is "Show in Finder" in Windows
- The file is opened directly instead of just opening the contained folder
![openPDF](https://github.com/janhq/jan/assets/64197333/d4ea976a-994f-4e81-b7f1-f450809f4898)

================================
**Environment details**
- Operating System: MacOS
- Jan Version: latest nightly build
- Processor: Apple M2 Pro
- RAM: 16GB
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by imtuyethan** [comment]
related ticket: https://github.com/janhq/jan/issues/1861

**Comment by louis-jan** [comment]
Issue 2: 
Since Nitro's embedding does not implemented queue mechanism, can reproduce easily when spamming requests. Will keep track in a separated issue
