### ISSUE TITLE
docs: Model Download Failed (teach how to use http proxy)

### ISSUE THREAD

**Issue by Zrs-0523** [janhq/jan#1868]
![image](https://github.com/janhq/jan/assets/125785635/15105ca8-1e7c-40b8-920b-ded6d0304eff)

**Comment by Van-QA** [comment]
hi @Zrs-0523, can you try this? https://github.com/janhq/jan/pull/1562

**Comment by Zrs-0523** [comment]
![image](https://github.com/janhq/jan/assets/125785635/d29c8516-8835-4088-878e-093ff7fb6c3f)
What do I need to set up here? I downloaded it with a VPN on! I'm in China

**Comment by Van-QA** [comment]
if there is an issue with your download, you can try downloading the model manually and importing https://jan.ai/guides/using-models/import-manually/
That is an easier approach, and there is no need to use the proxy.



Dev team will investigate your case further if you can provide the app.log https://jan.ai/troubleshooting/how-to-get-error-logs/

**Comment by Zrs-0523** [comment]
> if there is an issue with your download, you can try downloading the model manually and importing https://jan.ai/guides/using-models/import-manually/
> 
> That is an easier approach, and there is no need to use the proxy.
> 
> 
> 
> 
> 
> 
> 
> Dev team will investigate your case further if you can provide the app.log https://jan.ai/troubleshooting/how-to-get-error-logs/

Thank you very much! That's very helpful!

**Comment by Van-QA** [comment]
Assigning to Hieu to provide the link to the Jan guideline on how to use the HTTP Proxy (whenever the document is available), just in case users need it.
