### ISSUE TITLE
bug: Retrieval turn off 

### ISSUE THREAD

**Issue by TheHyrox** [janhq/jan#1873]
If I touch and want to use the slider in the Retrieval Menu, it turn off automatically. BUT it actually work, the planned action has been registered. 

**Step** 
1 - Turn on Retrieval
2 - Play with sliders
3 - Retrieval turn off by itself.

**Screenshots**
<img width="320" alt="Capture d’écran 2024-01-30 à 12 01 14" src="https://github.com/janhq/jan/assets/61850271/eb6952bd-ca06-44f2-b191-21221c243ae3">
<img width="320" alt="Capture d’écran 2024-01-30 à 12 01 33" src="https://github.com/janhq/jan/assets/61850271/86937f2b-f994-491d-97e7-ea1c5765163f">
<img width="320" alt="Capture d’écran 2024-01-30 à 12 01 42" src="https://github.com/janhq/jan/assets/61850271/7624222b-a862-4b99-a0fd-bc05b971ed5d">

**Environment details**
- Operating System: MacOs Sonoma 14.2.1
- Jan Version: v0.4.5-210
- Processor: Apple M2
- RAM: 16go

**Comment by Van-QA** [comment]
Similar issue with #1848, which was resolved from Jan v0.4.5-212 ✅ 
Thank you for your help 🙏
