### ISSUE TITLE
Jan doesn't save/load chats

### ISSUE THREAD

**Issue by alr888rav** [janhq/jan#1881]
When Jan starts, it always has only one new empty shat.
ps Folder threads has all saved chats.

**Steps to reproduce**
1. Open Jan
2. Have some chat
3. Close Jan
4. Open Jan and see only  new empty chat

**Expected behavior**
I expect to see all chats history.

**Environment details**
- Operating System: Windows 11 23H2
- Jan Version: 0.4.5.0
- Processor: AMD Ryzen 5 7530U
- RAM: 16GB
- AMD Radeon Vega

**Comment by Van-QA** [comment]
I would recommend troubleshooting the issue by creating a new thread with a message/response, and seeing if the JSON data is saved successfully or not.
Please provide the app.log  https://jan.ai/troubleshooting/how-to-get-error-logs/
And try running Jan with administration if possible 🙏

**Comment by alr888rav** [comment]
I had tried this way. 
1 Run Jan,  click clear log and exit
2 Run Jan as administrator, have test chat, exit
3 Run Jan as administrator and saw new empty chat, send another test message and exit
Here are the last two test chats and logs
[logs.zip](https://github.com/janhq/jan/files/14123357/logs.zip)
[threads.zip](https://github.com/janhq/jan/files/14123358/threads.zip)

**Comment by Van-QA** [comment]
Did you check the JSON of that thread during the testing, is it saved?

**Comment by namchuai** [comment]
@alr888rav , sorry for hearing that you having some trouble using Jan.

Jan stored your messages inside `messages.jsonl`. And I can see that your `messages.jsonl` inside `threads.zip` has some data in it.

Applied your threads data in to my Jan data folder, it shows messages as expected

<img width="917" alt="Screenshot 2024-02-02 at 08 19 22" src="https://github.com/janhq/jan/assets/10397206/fdc9083b-d296-4b3d-b3c9-317e0315e2ee">

I'm not entirely sure what's the problem here. Could you please try to do a clean install of Jan to see if it fixed your issue? Please remember to back up your important threads (if any)

Steps:
1. Uninstall Jan
2. Remove Jan data folder `C:\Users\<your username>\jan\`
3. Reinstall and open Jan

**Comment by alr888rav** [comment]
I tried another way, delete old chats one by one and restart Jan. This way problem solved.
Here is broken chat. Without it all OK, with it only one new chat.

**Comment by gaardhus** [comment]
> I tried another way, delete old chats one by one and restart Jan. This way problem solved. Here is broken chat. Without it all OK, with it only one new chat. Thanks for help [jan_1705492536.zip](https://github.com/janhq/jan/files/14139367/jan_1705492536.zip)

Deleting all old chat threads also solved the problem for me. I think the bug for me was introduced in 0.4.5.

**Comment by imtuyethan** [comment]
Seem like the problem is solved. Thank you so much for using Jan guys!

**Comment by iddm** [comment]
I have the same problem right now with a completely fresh installation of Jan on ArchLinux, v0.7.7, either the official AppImage or the AUR package. So, not a single chat is saved in my case.  I don't have many other files, I think, for some reason:

```
ls jan-data/* 
 mcp_config.json   store.json

jan-data/db:

jan-data/extensions:

jan-data/logs:
 app.log
```

I also can't download any model, I get "Initializing download..." all the time.  The assistants I create are not saved.

This is the only error I get in the log:
```
[2026-03-09][18:09:27][app_lib::core::extensions::commands][ERROR] Failed to read extensions.json: No such file or directory (os error 2)
```

**Comment by squassina** [comment]
Mine is in a different directory and I don't have any of that issues. My data resides here: `~ /.local/share/Jan/data/`. I'm running `cachyos/jan-bin 0.7.8-1 [installed: 0.7.7-1]`.

Did you check the General > Data Folder > App Data to confirm the path?

**Comment by iddm** [comment]
> Mine is in a different directory and I don't have any of that issues. My data resides here: `~ /.local/share/Jan/data/`. I'm running `cachyos/jan-bin 0.7.8-1 [installed: 0.7.7-1]`.
> 
> Did you check the General > Data Folder > App Data to confirm the path?

Yes I did and even tried changing it to another directory, initially it was just as yours.

I have all the permissions there, in both the paths, as well as the files can be created and changed by Jan process itself.
