### ISSUE TITLE
feat: feature language specific models in Hub list

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#1885]
**Problem**

Based on usage & direct requests: 
- French (TBA, ask our internal channels)
- Russian (TBA)
- Spanish (aguila or chinchilla)
- Mandarin
- Maybe also: Hindi, German,  Japanese, Bahasa

**Success Criteria**
- wed need to update templates / separate grammar files, etc.
 
**Additional context**

**Comment by hahuyhoang411** [comment]
Here is the list of best language-specific models:
1. Vietnamese: [Vistral](https://huggingface.co/Viet-Mistral/Vistral-7B-Chat) 
2. Chinese: [Qwen](https://huggingface.co/vilm/Quyen-Plus-v0.1)
3. French: [CroissantLLM](https://huggingface.co/croissantllm/CroissantLLMChat-v0.1)
4. Rusian: ?

Do we need to create a new tag or specific design for this cc @imtuyethan

**Comment by 0xSage** [comment]
Thanks for the recommendation! I'd mark this as a P2. 

As a short term patch, @hahuyhoang411 can you make these suggestions in the language channels? Then let's pin those messages so new people can discover them.
