### ISSUE TITLE
bug: weird behavior when i click on thread list; should not allow users to create so many threads at the same time if users don't start any chat or edit settings

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1887]
**Describe the bug**
Jan should not allow users to create so many threads at the same time if users don't start any chat or edit settings:
https://github.com/janhq/jan/assets/89722390/48ec3352-434e-4c40-ab87-f1343980b0b4

Weird behavior when i click on thread list
https://github.com/janhq/jan/assets/89722390/fa4d376f-e939-49a3-afe5-6b1f0e2ac9ca

**Steps to reproduce**
1. Go to Threads
2. Click on create new threads
3. Continue to do so without starting the chat or adjust the settings
5. See error

**Expected behavior**

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: 0.4.5-216
- Processor: Apple M2
- RAM: 16GB

**Comment by Van-QA** [comment]
@urmauur the fix https://github.com/janhq/jan/pull/1930, is blocking user from creating new thread, when the most recent thread is something amiss (no response)
![image](https://github.com/janhq/jan/assets/64197333/2bb35b87-6ca7-4069-b105-5fd909291073)
even renaming didn't allow user to create new thread
![image](https://github.com/janhq/jan/assets/64197333/dcdc6564-6db6-4711-be7a-84861dccba31)

**Comment by urmauur** [comment]
@Van-QA fixed latest issue on #1951

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-270 ✅

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-277 ✅
