### ISSUE TITLE
bug: Mistral isn't detected / Have to redownload it

### ISSUE THREAD

**Issue by TheHyrox** [janhq/jan#1890]
**Describe the bug**
Every Nb update I have to "redownload" Mistral beacause Jan doesn't find it, even if it was in the right folder 

**Steps to reproduce**
I don't know ? Download Mistral, update nightly build and tada...

**Expected behavior**
To use Mistral with no unfind issue.

**Screenshots**
<img width="1370" alt="image" src="https://github.com/janhq/jan/assets/61850271/76602c07-1525-4a9a-8912-d46228161fc6">

**Environment details**
- Operating System: MacOs Sonoma 14.2.1
- Jan Version: 0.4.5-211 (first time I have this issue) and 0.4.5-216 (actually)
- Processor: Apple M2
- RAM: 16Gb

**Additional context**
I've already see this issue in the nb 0.4.5-211 but I didn't notice it.

**Comment by Van-QA** [comment]
hi @TheHyrox,

Can you give us your model.json of the model?
We are suspecting this might be the root cause of the issue. https://github.com/janhq/jan/issues/1922

**Comment by louis-jan** [comment]
I think this issue is addressed, nightly build 270. cc @Van-QA

**Comment by Van-QA** [comment]
@TheHyrox, can you double-check using the latest nightly build? Jan v0.4.6-270
