### ISSUE TITLE
feat: [Local API Server] Revamp UIUX of model selection and indicators

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1893]
# Problems
### Problem #1
Related to this issue: #1910 

Currently, users are allowed to send requests to **multiple models at the same time** (1 active local model + multiple remote models) but the API server GUI does not reflect that:

<img width="1122" alt="Screenshot 2024-02-06 at 3 26 03 PM" src="https://github.com/janhq/jan/assets/89722390/7ddb5fa8-e32d-4460-8d66-65a9570a2173">

### Problem #2
Users can't see model ID to send request 
<img width="683" alt="Screenshot 2024-02-01 at 4 47 31 PM" src="https://github.com/janhq/jan/assets/89722390/e1e00648-39df-4582-abc1-6c271a0c5ba0">

# Solution
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1200-116788&mode=design&t=lvE3hVidcZbbnSpg-4

## 1. Inform users that they can concurrently send requests to one active local model and multiple remote models
<img width="1358" alt="Screenshot 2024-02-06 at 4 24 51 PM" src="https://github.com/janhq/jan/assets/89722390/60b91a01-0923-4439-8735-9c8d27d2cb54">

## 2. Separate local model & remote model & add model ID 
**In-scope:** 
- Separate local model & remote model
- Add `model ID` under model name in model selection menu -> users can click on it to copy model ID
- Add button shortcut `my models` -> this will direct users to `Settings / My models`

**Note that this component will apply to threads as well!**

<img width="808" alt="Screenshot 2024-02-06 at 4 41 45 PM" src="https://github.com/janhq/jan/assets/89722390/fd73ad1d-e579-499b-a4f1-f717cfbb7209">

____
**Out-of-scope:**
In the future we will add more things to this as part of remote model UI revamp: https://github.com/janhq/jan/issues/994

**Comment by Van-QA** [comment]
@urmauur extra scroll arrow displayed when nothing to scroll in the remote tab :x:
The issue occurs only when users visit the Local tab first (with scroll down arrow) and then moving to the Remote tab

![Image](https://github.com/janhq/jan/assets/64197333/2be817b6-b092-4e38-aed0-57fef1c245de)

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-279 ✅
