### ISSUE TITLE
bug: N/A Error Log on loading Hermes Mistral GGUF or other models

### ISSUE THREAD

**Issue by chubshaun** [janhq/jan#1897]
**Describe the bug**

Followed steps to import a model manually
https://jan.ai/guides/using-models/import-manually/

Model breaks with the error `Error loading the model - llamaCPP.cc:565`. I'm confident that this model is not corrupt since I use the same GGUF file with Ollama.

**Steps to reproduce**
Download Hermes 2.5 Mistral model 5-bit KM quant
https://huggingface.co/TheBloke/OpenHermes-2.5-Mistral-7B-GGUF/blob/main/openhermes-2.5-mistral-7b.Q5_K_M.gguf

Copy over as:
```
~/jan/models/openhermes-2.5-mistral-7b/openhermes-2.5-mistral-7b.gguf
```

Shows up but any attempt to load it fails with below log.

**Environment details**

MacOS Sonoma 14.1.1
Jan: Version 0.4.5-219 (0.4.5-219)
Mac M1 Max (32GB Ram)

**Logs**

```
2024-02-01T21:57:52.432Z [NITRO]::Debug: Loading model with params {"ctx_len":4096,"embedding":false,"prompt_template":"{system_message}\n### Instruction: {prompt}\n### Response:","llama_model_path":"~/jan/models/openhermes-2.5-mistral-7b/N/A","system_prompt":"","user_prompt":"\n### Instruction: ","ai_prompt":"\n### Response:","cpu_threads":10,"ngl":100}
2024-02-01T21:57:52.435Z [NITRO]::Debug:       ___                                   ___           ___

20240201 21:57:52.138411 UTC 22043848 INFO  Nitro version:  - main.cc:50
20240201 21:57:52.138776 UTC 22043848 INFO  Server started, listening at: 127.0.0.1:3928 - main.cc:54
20240201 21:57:52.138776 UTC 22043848 INFO  Please load your model - main.cc:55
20240201 21:57:52.138777 UTC 22043848 INFO  Number of thread is:10 - main.cc:62
{"timestamp":1706824672,"level":"INFO","function":"loadModelImpl","line":561,"message":"system info","n_threads":10,"total_threads":10,"system_info":"AVX = 0 | AVX_VNNI = 0 | AVX2 = 0 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 0 | NEON = 1 | ARM_FMA = 1 | F16C = 0 | FP16_VA = 1 | WASM_SIMD = 0 | BLAS = 1 | SSE3 = 0 | SSSE3 = 0 | VSX = 0 | "}

2024-02-01T21:57:52.435Z [NITRO]::Debug: {"timestamp":1706824672,"level":"ERROR","function":"load_model","line":560,"message":"unable to load model","model":"~/jan/models/openhermes-2.5-mistral-7b/N/A"}
20240201 21:57:52.435525 UTC 22043851 ERROR Error loading the model - llamaCPP.cc:565

2024-02-01T21:57:52.435Z [NITRO]::Error: llama_model_load: error loading model: failed to open ~/jan/models/openhermes-2.5-mistral-7b/N/A: No such file or directory
llama_load_model_from_file: failed to load model
llama_init_from_gpt_params: error: failed to load model '~/jan/models/openhermes-2.5-mistral-7b/N/A'
```

**Comment by chubshaun** [comment]
EDIT: I figured it out

<img width="324" alt="image" src="https://github.com/janhq/jan/assets/105888480/1eac1b0e-6a90-4bf7-bb6e-9bd17cfbe9d1">


I don't think these directions are correct for the latest version of Jan. It seems like JAN auto-generates a model.json for the custom gguf, but since it sticks "N/A" in the filename and url parts of the model.json - this causes this file not found issue:

```
'~/jan/models/openhermes-2.5-mistral-7b/N/A'
```

**Comment by Van-QA** [comment]
The issue is reproducible Jan v0.4.5-224
![image](https://github.com/janhq/jan/assets/64197333/934178ea-aa38-4fcf-b660-e5cb59df7b5f)

[app.log](https://github.com/janhq/jan/files/14138617/app.log)

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.5-260 ✅
