### ISSUE TITLE
bug: Start API server successfully even address already in use

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1903]
**Describe the bug**
I can start API server successfully even I have another program already own the port 1337. The API server starting should be failed instead.

**Steps to reproduce**
Given there is an app already own the port 1337
1. Go to Local API Server
2. Click on Start
3. See error

**Expected behavior**
Start API Server button should back to the previous state.

**Screenshots**
![image](https://github.com/janhq/jan/assets/133622055/9398fe80-a390-408d-b405-7f4348e32acd)

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.5
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
Testing failed using Jan v0.4.6-273 :x:

1. When port is in use (:9323),  Users can start the server successfully :x:
2. Click on the API reference button to show the incorrect page at http://localhost:9323/ :x:
![portInuse](https://github.com/janhq/jan/assets/64197333/510118dc-88cd-4859-8330-54704f153aca)

4. Visiting http://127.0.0.1:9323/static/index.html still shows the correct Swagger API page ✅ 

@louis-jan

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-277 ✅

<img width="1193" alt="image" src="https://github.com/janhq/jan/assets/64197333/040f9c8f-595b-4a89-82f9-55536554c4fb">
