### ISSUE TITLE
discussion: Started server with a local model but still send request to OpenAI Models

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1910]
**Describe the bug**
I selected tiny-llama on the GUI. As a user, I expected all of the chat/completions requests to be sent to this model instead of OpenAI endpoints, regardless of the model name defined in the request. The model name in the request should be optional and should not affect the middleware; otherwise, users might get confused.

**Steps to reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/janhq/jan/assets/133622055/5f144b59-33b7-4dcc-888a-57231d4231a3)

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by louis-jan** [comment]
Sorry, @hiro-v, this issue concerns product specs alignment. It's about UI/UX enhancements to reduce user confusion.

<img width="1312" alt="Screenshot 2024-02-05 at 10 37 07" src="https://github.com/janhq/jan/assets/133622055/d5189765-e741-4b1a-902e-dc08647910fc">

**Comment by imtuyethan** [comment]
Will be solved along with this issue: https://github.com/janhq/jan/issues/1893

**Comment by imtuyethan** [comment]
`Happily` agree to allow users to send requests to multiple models at the same time.
