### ISSUE TITLE
bug: [Local API Server] model failed to load but the server started successfully 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1911]
# Describe the bug

I had a `something's amiss` bug in threads, it turned out it was because i didn't have enough RAM. 
Then I went to local API server & started the server & The model showed run successfully but it did not show an active model on the footer:

<img width="1215" alt="Screenshot_2024-02-02_at_3 31 44_PM" src="https://github.com/janhq/jan/assets/89722390/24804fb1-f059-4deb-a1bf-a1aff25896af">

https://github.com/janhq/jan/assets/89722390/6ad1d6e4-daf7-406b-851f-7de0d1c0503d

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: Jan v0.4.5-216
- Processor: Apple M2
- RAM: 16GBelevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
[app.log](https://github.com/janhq/jan/files/14137874/app.log)

# Solution
As investigated with @Van-QA & @louis-jan, API server sometimes doesn't require an active model to be successfully started to be able to run.
So we should handle 2 cases differently:
- Show that the model is not started successfully due to `something's amiss` bug
- Then show that the API server is sucessfully started 

Figma: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=4073-274875&mode=design&t=3u1JkUwg1y1NMCMp-4
1. Starting server + loading model: 
<img width="862" alt="Screenshot 2024-02-06 at 9 46 02 AM" src="https://github.com/janhq/jan/assets/89722390/bd295f45-6397-436a-ac81-2996215ce888">

2. Model failed to load but the API server starts successfully: 
<img width="882" alt="Screenshot 2024-02-06 at 9 46 07 AM" src="https://github.com/janhq/jan/assets/89722390/d4a5d224-9957-4f35-9393-e5970c15cecc">

**Comment by LeGitHubDeTai** [comment]
good evening I just did the new update and I have the same problem

**Comment by Van-QA** [comment]
Minor UI issue, using the My Model popup, when users attempt to start a different model (model B) than the one in the local API Server model dropdown (model A):

1. The loader is still displayed in the name of **model A** when loading **model B**: :x:
![Image](https://github.com/janhq/jan/assets/64197333/71285480-614e-456d-9274-abe019a00385)

2. If failed loading the **model B**, there will be error displayed under the name of **model A**: :x:
![Image](https://github.com/janhq/jan/assets/64197333/ae250800-978b-4b38-871d-a066f8338121)

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-274 ✅
