### ISSUE TITLE
bug: No model showing under AIs on iPhone14 Plus, iOS 17.3

### ISSUE THREAD

**Issue by erima2020** [janhq/jan#1914]
**Describe the bug**
Hi, 
I love Jan on MacOS, it's really great! On my iPhone I don't get the models displayed for download. I can run maybe 7b q3_km models with other apps on the same device and several 3b models in q8.
A suggestion: allow an easy way to choose models already stores on the device so users don't need to download them again (and store twice) when using other apps as well.

**Steps to reproduce**
1. Go to 'AIs'
Blank page is displayed

**Expected behavior**
A page for the selection of models to download

**Screenshots**
Screenshot [added]
![IMG_7602](https://github.com/janhq/jan/assets/63055709/e1c6b232-ccf8-4b73-9969-b7d8596ccb01)

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by cy63rx** [comment]
+1
Same for Android too.

**Comment by Van-QA** [comment]
hi there, 
Jan actually pivoted away from the mobile app some time ago, the mobile app that you are using is out of date and cannot be used. 
Sorry for any inconvenience.

**Comment by RArchi** [comment]
Wow ((( Working on iPhone and iPad is much needed! It's hard to overemphasize this need to have such a tool at hand :D what would it take to get back to implementing a mobile version?
