### ISSUE TITLE
Discussion: [Extension/plugin limitations and their main purpose]

### ISSUE THREAD

**Issue by TrishinVladimir** [janhq/jan#1915]
**Motivation**
A friend of mine have a dyslexia and reading tremendous text amount is kind of hard, so I'm curious to add a possibility to also generate voiced text audio files.

**Discussion**
I already have implemented it with Coqui TTS by their guides, but if I correctly understood (slightly looking into the core code, haven't found much info about the plugins purpose) plugins do not provide possibility to create ther own pages on the Jan Desktop and let extension creators create their own implementation of anything they seem appropriate.

So, what is the purpose of extensions/plugins?

**Comment by TrishinVladimir** [comment]
Read [here](https://jan.ai/developer/ui/) about the things I need. But still please help to understand what the purpose of extensions

**Comment by imtuyethan** [comment]
Hi there! 
- You can read more about our extension framework here: https://jan.ai/docs/
- Our users also created a forum to share extensions with each other & to discuss its use cases further: https://discord.com/channels/1107178041848909847/1190686855704883222
Feel free to drop any message on our Discord for quicker responses, thank you! <3
