### ISSUE TITLE
bug: Model - New model.json causing unable to load old model downloaded from Hub, needs modification / redownloading 

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1922]
**Describe the bug**
New model.json causing unable to load old model downloaded from Hub, needs modification / redownloading

**Steps to reproduce**
1. Model with old model JSON
2. Update Jan app
3. Try to load the same model

**Expected behavior**
After updated, users should be able to use the old model without any issues

**Screenshots**
![image](https://github.com/janhq/jan/assets/64197333/d5a1df29-f449-448d-9704-6cbb9e715088)
![image](https://github.com/janhq/jan/assets/64197333/74bd234a-8d10-40d2-bc80-c219d3708409)

**Environment details**
- Operating System: MacOS
- Jan Version: latest nightly build
- Processor: Apple M2 Pro
- RAM: 16GB

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
Additional fix needed for the schema validation of all model.json files, per each Jan app update @louis-jan

**Comment by 0xSage** [comment]
Can I understand the status of this tomorrow? 🙏

**Comment by louis-jan** [comment]
I have added support for backward compatibility #2018

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-277 ✅

<img width="803" alt="image" src="https://github.com/janhq/jan/assets/64197333/e77082fe-194b-4bc1-90a0-5c080904c44a">
<img width="827" alt="image" src="https://github.com/janhq/jan/assets/64197333/00219b88-c1e9-40d6-b94b-71cf1318e68a">
