### ISSUE TITLE
bug: error copies should not be in a LLM's response

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1932]
**Describe the bug**
When users receive the error message as a LLM's response, then they choose any model, that newly selected model will use the history response (the error message) as a reference & give wrong response later on.

<img width="301" alt="Screenshot_2024-02-05_at_08 39 06" src="https://github.com/janhq/jan/assets/89722390/7145c937-4866-4cc7-a64f-9fd564d280b9">

**Solution**
Separate error message with LLM's response, using the following error component:

<img width="949" alt="Screenshot 2024-02-06 at 9 22 37 AM" src="https://github.com/janhq/jan/assets/89722390/0bf12032-5cd0-423e-8a9e-ce767223ff66">

**Comment by 0xgokuz** [comment]
@imtuyethan I would like to clarify:

1. Using the example that you gave, we want to convert BOTH responses look & feel to use the "error component", correct?

Noticed that the 2nd error response is continuation of the 1st error response. This is expected even if we're using the "error component", correct?

2. We're going to remove the "header response" altogether in the "error responses"?

![IMG_6101](https://github.com/janhq/jan/assets/155065525/4660f5bb-273d-4fec-8399-204682e2e8be)

**Comment by namchuai** [comment]
@Van-QA , please help to verify this issue. Thank you!

**Comment by Van-QA** [comment]
Tested and looking good on Jan 0.4.7-304 ✅
