### ISSUE TITLE
epic: Initialize Playwright for basic run and dashboard report

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#1935]
## Motivation
- Implement automation runs to reduce manual regression testing efforts.
- Shift focus during each release to investigating and troubleshooting potential issues.
- Minimize the need for repetitive manual testing across multiple operating systems.

## Specs
- Apply structure to automation script using Playwright Framework
- Intergrate with [Report Portal](https://reportportal.io/pricing/on-premises) to collect logs for troubleshooting.

## Designs
[Reporters](https://playwright.dev/docs/test-reporters)

## Tasklist
- [x] #1936
- [x] #1937
- [x] #2045
- [x] #2047

## Not in Scope
-

**Comment by 0xSage** [comment]
How do we measure performance degradation/improvements as a part of this?

We get anecdotal reports of slow down / speed up. How do we get concrete visibility?

**Comment by Van-QA** [comment]
hi @0xSage,

This is only for automation regression testing purposes and will run side-by-side with the Jan app (using the Github Action pipeline / workflow).
Automation runs like this have **no impact** on the main Jan app, it's like additional checks (similar to how we ran an antivirus check on a new build).
The test will cover critical functions to highlight breaking changes in the report, we will not measure performance at this stage.

**Comment by imtuyethan** [comment]
- Closed as dup: https://github.com/janhq/jan/issues/3632
