### ISSUE TITLE
bug: HTML tags are not visible after submit

### ISSUE THREAD

**Issue by momentum100** [janhq/jan#1939]
HTML tags are not visible after submit

Steps to reproduce
1. paste 
```
<p><h1>HALLO</h1></p>
```
3. See only HALLOin your history message

**Expected behavior**
visible tags like 
```
<p><h1>HALLO</h1></p> from example
```

![image](https://github.com/janhq/jan/assets/51231797/af78bac2-e841-4f2e-8170-47067d0a47c9)

**Environment details**
- Operating System: Windows

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-267 ✅


<img width="264" alt="image" src="https://github.com/janhq/jan/assets/64197333/c890f38f-ed93-486b-9bd8-695c99a7c07e">
