### ISSUE TITLE
feat: revamp Jan app layout to fix its look on window

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#1943]
**Problem**
<img width="614" alt="Screenshot 2024-02-06 at 9 39 13 PM" src="https://github.com/janhq/jan/assets/89722390/894ed860-f5a6-49c2-be10-0938ecba0004">
<img width="530" alt="Screenshot 2024-02-06 at 9 39 25 PM" src="https://github.com/janhq/jan/assets/89722390/3b8c3379-9c87-4f73-b81a-205653942b22">

**Success Criteria**
Restructure the app:
- ribbon navigation
- left panel
- main section
- right panel
- bottom bar

**Comment by urmauur** [comment]
close this is no longer relate, since we have new layout
