### ISSUE TITLE
feat: Convert long string (more than 4096 tokens) to attached file and use RAG

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#1961]
**Problem**
Context: https://discord.com/channels/1107178041848909847/1187241936302649435/1204776884001439825
Not intended to derail the conversation, but one thing I would be curious about (if it was not raised anywhere).
I have been using claude for a while and one feature that has been really helpful is the ability to copy articles or large pieces of texts and paste into the question panel.

After a certain character limit, they will take the text stream and convert it to a temporary file (which I image they pass as a RAG, but just a guess). If JAN could have similar functionality in the future (leveraging the current RAG features) it would make for quite a powerful experience.

Yes. I sometimes come across internet articles that I am interested in understanding better and asking the AI (In this case Claude) to break it down and explain areas that I struggle with, making it quite helpful.

When I try to do it with JAN (And maybe this is just my spec and limitation of Mistral 7B), the entire article sometimes does not fit (not everything is pasted) and the model struggles to understand what I passed him.

So thought that if it is converted to a file (as you mentioned messages.text for example) and processed as a RAG, then the model won't struggle to communicate with the article text 

**Success Criteria**
- Set max token limit in message box equal to max_token in thread's model
- Add token counter (aa/4096) for example
- If the number of token in the message is lower than the max_token, send it as normal
- If the number of token in the message is equal/ more than the max_token, convert it as attached file upload `messages.txt`, send it and treat it as RAG case

**Additional context**

**Comment by louis-jan** [comment]
Pending backend revamp

**Comment by 0xSage** [comment]
https://github.com/janhq/cortex/issues/680
