### ISSUE TITLE
feat: Hotkeys for stop generating answer, regenerate last answer and stop (unload) model

### ISSUE THREAD

**Issue by Glashkoff** [janhq/jan#1962]
**Problem**
Currently, it is impossible to communicate with AI using the keyboard without a mouse.

**Success Criteria**
It would have been possible to at least:
1. Stop the process of generating a response by hotkey (Esc?).
2. Trigger a new regeneration of the last response (it doesn't matter if it was interrupted or not).
3. Stop the model (for restart after in some cases). This would not only temporarily solve the problem of slow response generation but also generally free up RAM or VRAM on the device for other tasks.

As a maximum:
1. Have the ability to create a new thread from the keyboard, select a model (this hotkey already exists), and quickly switch between dialogs as if they were tabs (Ctrl+Tab?).
2. Have the ability to trigger editing of your last message from the keyboard.

**Comment by 0xSage** [comment]
Neat. Tagging this to #760

**Comment by imtuyethan** [comment]
Moving this to Notion til it is confirmed: https://www.notion.so/jan-ai/Jan-Hotkeys-Keyboard-Shortcut-9df14165c11d487e906e899e72d86ba9?pvs=4
