### ISSUE TITLE
bug: inactive

### ISSUE THREAD

**Issue by gibaoxi** [janhq/jan#1966]
我下载了winjan，然后在hub里下载了1.3g的deepseek-coder-1.3b,
![image](https://github.com/janhq/jan/assets/100911189/a2670cfa-5dba-4a97-a57e-339d9176e7fa)，设置里starting model显示inactive
![image](https://github.com/janhq/jan/assets/100911189/aedbb8f9-03e9-4c14-8b36-8ba95d33343f),聊天返回
Apologies, something's amiss!

Jan's in beta. Find troubleshooting guides [here](https://jan.ai/guides/troubleshooting) or reach out to us on [Discord](https://discord.gg/AsJ8krTT3N) for assistance.
![image](https://github.com/janhq/jan/assets/100911189/69990ead-2312-459c-a7f1-b77e3b3eea42)
怎么解决?
下面有我的电脑信息4gram是不是用不了jan
![image](https://github.com/janhq/jan/assets/100911189/bf6b2c40-3772-4608-8f53-7ff8b51a7b34)

**Comment by gibaoxi** [comment]
![image](https://github.com/janhq/jan/assets/100911189/38a78f41-f680-43b1-a9ce-1555c60ad0e5)
我是不是应该把这个gguf文件改成和文件夹一个名字，然后在model.json文件里加上"stage:ready"这个属性
![image](https://github.com/janhq/jan/assets/100911189/818ec778-3a4d-4af3-a12e-4c5d6f53600a)

**Comment by louis-jan** [comment]
It seems the model failed to download (0KB). Please try to redownload it manually and place it in the folder.

**Comment by gibaoxi** [comment]
> It seems the model failed to download (0KB). Please try to redownload it manually and place it in the folder.模型似乎无法下载（0KB）。请尝试手动重新下载并将其放入文件夹中。

我截错图了，我下的不是这个模型。是deepseed coder,看我第一张图。

**Comment by louis-jan** [comment]
I see, could you please share the app.log. (you can find it in Jan > Settings > Advanced > Jan Data Folder)

**Comment by louis-jan** [comment]
It seems like the computer spec is not meeting the requirement: 4GB of RAM.
