### ISSUE TITLE
feat: Spotlight conversation, like Joy AI (screenshot below - a few other apps have this)

### ISSUE THREAD

**Issue by petruut** [janhq/jan#1978]
**Problem**
AI interactions should be more casual. I found I used Joy AI a lot more by using a keyboard trigger to bring it to the front and then quickly back.

**Success Criteria**
A spotlight type experience, that can be triggered with a shortcut, and that allows you to have a brief conversation on the spot/ select the model, etc. copy the response potentially, and then dismiss the chat with Esc.

**Additional context**
Screenshots where this is implemented well, except that when the keyboard shortcut is triggered, the focus should already be on the typing (you should be able to type straight away).

![image](https://github.com/janhq/jan/assets/15355480/fc3c1a97-d87e-473b-b868-3904cc51c79d)

![image](https://github.com/janhq/jan/assets/15355480/93ec5170-d869-48a2-82e0-076513ca7d46)

**Comment by dan-jan** [comment]
This is a wonderful idea and we have an active discussion in Github on how to implement this: 

https://discord.com/channels/1107178041848909847/1188339923254775859

**Comment by imtuyethan** [comment]
Quick Ask related. Done.
