### ISSUE TITLE
bug: Cant start models

### ISSUE THREAD

**Issue by mike2003** [janhq/jan#1982]
I downloaded the model from the hub (any model)
I run the model, the bar appears and then goes away.
Log:
2024-02-09T16:27:04.967Z [NITRO]::Debug: Nitro is ready
2024-02-09T16:27:04.968Z [NITRO]::Debug: Loading model with params {"ctx_len":4096,"prompt_template":"<|system|>\n{system_message}<|user|>\n{prompt}<|assistant|>","llama_model_path":"C:\\Users\\***\\jan\\models\\tinyllama-1.1b\\tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf","system_prompt":"<|system|>\n","user_prompt":"<|user|>\n","ai_prompt":"<|assistant|>","cpu_threads":5,"ngl":100}
2024-02-09T16:27:04.982Z [NITRO]::Debug: 94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [93m [94m [93m [94m [93m [94m\[93m_[94m_[93m\[94m/[93m [94m [93m [94m [0m
[0m20240209 16:27:04.700000 UTC 9316 INFO  Nitro version:  - main.cc:50
20240209 16:27:04.701000 UTC 9316 INFO  Server started, listening at: 127.0.0.1:3928 - main.cc:54
20240209 16:27:04.701000 UTC 9316 INFO  Please load your model - main.cc:55
20240209 16:27:04.701000 UTC 9316 INFO  Number of thread is:8 - main.cc:62
{"timestamp":1707496024,"level":"INFO","function":"loadModelImpl","line":561,"message":"system info","n_threads":5,"total_threads":8,"system_info":"AVX = 1 | AVX_VNNI = 0 | AVX2 = 1 | AVX512 = 0 | AVX512_VBMI = 0 | AVX512_VNNI = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | SSSE3 = 0 | VSX = 0 | "}

2024-02-09T16:27:05.002Z [NITRO]::Debug: Nitro exited with code: 3221225501
2024-02-09T16:27:06.525Z [NITRO]::Error: TypeError: fetch failed
2024-02-09T16:27:06.524Z [NITRO]::Error: Load model failed with error TypeError: fetch failed

What's wrong?

**Environment details**
Win10x64
- Jan Version: 0.4.6

**Comment by louis-jan** [comment]
@mike2003 Oops, could you please help me find the app.log file and attach it here? You can navigate to the app data folder by going to Settings > Advanced > Jan Data Folder. There should be a folder named logs.

<img width="1312" alt="Screenshot 2024-02-11 at 10 38 33" src="https://github.com/janhq/jan/assets/133622055/159cfc1b-6c03-4f95-9952-24e12d3c51a7">

**Comment by mike2003** [comment]
After some research, here's what I thought - I have an old processor without avx2.
Is avx2 required to work?

**Comment by louis-jan** [comment]
> After some research, here's what I thought - I have an old processor without avx2. Is avx2 required to work?

I think so, cc @tikikun

**Comment by chuckpen** [comment]
Hi, I was told by your Discord mod to post my log file here. 
[jan-nitro.txt](https://github.com/janhq/jan/files/14303798/jan-nitro.txt)

**Comment by mike2003** [comment]
Where is this file?

**Comment by louis-jan** [comment]
> Hi, I was told by your Discord mod to post my log file here. [jan-nitro.txt](https://github.com/janhq/jan/files/14303798/jan-nitro.txt)

It seems you are running with GPU enabled (win-cuda-12-0\nitro.exe), could you help us provide the Nvidia Cuda Driver & Toolkit version on your machine?

**Comment by louis-jan** [comment]
> Where is this file?

You can find the logs under Jan Data Folder (Go to Settings > Advanced Settings > Jan Data Folder)

**Comment by mike2003** [comment]
> You can find
No such file "jan-nitro.txt"

**Comment by chuckpen** [comment]
Hi,

I have CUDA Toolkit 12.3 Update 2 and Nvidia Driver 551.52 installed.

**Comment by louis-jan** [comment]
> > You can find
> 
> 
> 
> No such file "jan-nitro.txt"
It's app.log

**Comment by chuckpen** [comment]
See attached.

**Comment by mike2003** [comment]
where is jan-nitro.txt ?

**Comment by louis-jan** [comment]
> where is jan-nitro.txt ?

It's actually app.log, @mike2003. You can find it in the app's logs folder under the Jan Data Folder (Settings > Advanced Settings > Jan Data Folder).

If you're on the latest Nightly Build, you can quickly copy it with this pop-up.

![Image](https://github.com/janhq/jan/assets/133622055/b23f02ba-22d6-4425-9d88-f698e7b13039)

**Comment by Seedmanc** [comment]
The solution  - https://github.com/janhq/jan/issues/2111#issuecomment-1963755743

**Comment by louis-jan** [comment]
> After some research, here's what I thought - I have an old processor without avx2. Is avx2 required to work?

That is confirmed. Please try the solution that @Seedmanc suggested.
