### ISSUE TITLE
bug: Retrieval + Open API - Stuck at generating response

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#1986]
**Describe the bug**
1. Retrieval is enabled by default, there is no downloaded model -> Open AI GPT is selected by default -> Stuck at generate responding since the request goes throw assistant > tool > embedding
2. Sending message with wrong context since message goes through assistant > tool > embedding (new context is added) 

**Steps to reproduce**
1. Clean app data
2. Start a thread
3. Go to settings
4. Toggle on Experimental Feature toggle
5. Start a new thread & send message
6. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-273 ✅
