### ISSUE TITLE
feat: add some verbosity to server logs

### ISSUE THREAD

**Issue by kha84** [janhq/jan#1989]
**Problem**

Currently "server logs" window does not provide the raw incoming JSON requests. 
That reduces debugging capability, especially if some clients are sending malformed or incomplete JSON requests.

And as you can imagine, with the boost of locally hosted models and OpenAI-compatible local API endpoints, there are more and more such clients and demand to troubleshoot them from community grows :)

I'm currently trying to troubleshoot a number of open source VScode/VSCodium LLM plugins ([Twinny](https://github.com/rjmacarthy/twinny/) and [Privy](https://github.com/srikanth235/privy)) to make them work properly with any OpenAI-compatible servers, one of them is Jan.AI. Having this additional information added to Server Logs will help a lot to troubleshoot any ongoing issues, making them much more solid and stable products for the benefit of community. Having this additional diagnostics printed on Jan side, also makes is much more convenient tool to use for such development. 

One example I have at hands, is that the [Twinny](https://github.com/rjmacarthy/twinny/issues/72) plugin is sending some JSON REST request to a proper endpoint (http://localhost:1337/v1/chat/completions), but it looks like it's missing something in the JSON itself, so Jan responds with just bare "404" without any additional details on what was missing. Here is what I see in "Server logs" on Jan side:

```
{"level":30,"time":1707568286598,"pid":12484,"hostname":"DESKTOP-KM29SIC","reqId":"req-1d","req":{"method":"POST","url":"/v1/chat/completions","hostname":"127.0.0.1:1337","remoteAddress":"127.0.0.1","remotePort":51307},"msg":"incoming request"}

{"level":30,"time":1707568286605,"pid":12484,"hostname":"DESKTOP-KM29SIC","reqId":"req-1d","res":{"statusCode":404},"responseTime":6.850600000470877,"msg":"request completed"}
```

If I manually craft the JSON and send it with `curl`, Jan responds just fine:

```
curl -XPOST http://localhost:1337/v1/chat/completions  -H "Authorization: Bearer mypassword" -H "Content-Type: application/json"   -d '{
    "prompt": "<｜fim▁begin｜> def main(<｜fim▁hole｜> <｜fim▁end｜>",
    "max_tokens": 50,
    "temperature": 0.1,
    "top_p": 0.9,
    "seed": 10,
    "model":"deepseek-coder-1.3b"
  }'
{"choices":[{"finish_reason":null,"index":0,"message":{"content":"\nThe code snippet you provided is a simple Python script that uses the `requests` library to send HTTP requests. Here's how it works:\n\n```python\nimport json\nfrom urllib import parse, request  #","role":"assistant"}}],"created":1707568275,"id":"lGIrDUXyDPZEFeUzr4pL","model":"_","object":"chat.completion","system_fingerprint":"_","usage":{"completion_tokens":50,"prompt_tokens":4,"total_tokens":54}}
```

... and "Server Logs" is having these lines:

```
{"level":30,"time":1707568272476,"pid":12484,"hostname":"DESKTOP-KM29SIC","reqId":"req-1c","req":{"method":"POST","url":"/v1/chat/completions","hostname":"localhost:1337","remoteAddress":"127.0.0.1","remotePort":51305},"msg":"incoming request"}

{"level":30,"time":1707568275926,"pid":12484,"hostname":"DESKTOP-KM29SIC","reqId":"req-1c","res":{"statusCode":200},"responseTime":3450.293600000441,"msg":"request completed"}

```

But without seeing the JSON from the Twinny, I'm unable to guess what was missing there and Jan doesn't tell those details as well. 
It would be great if you can add this extended logging feature. Love you all guys.

**Success Criteria**

"Server logs" should print the raw incoming JSON request. 
Additionally (and ideally) when there's something missing in JSON request and 404 response happens, logs should also have have additional indication on what exactly was missing in client' JSON request.

**Comment by clement-igonet** [comment]
From source code, I see the option `isVerboseEnabled` that is activable...

**Comment by louis-jan** [comment]
@Inchoker could you please attach this as a subtask of Server / Swagger Refactoring?

**Comment by 0xSage** [comment]
@nguyenhoangthuan99  do cortex server logs contain user post request objs? If so , pls feel free to close this task 🙏

**Comment by 0xSage** [comment]
outdated
