### ISSUE TITLE
bug: Jan installed on Linux fails to download Model to fs and exhibits phantom model behavior

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1998]
**Describe the bug**
- Jan on Kubuntu incorrectly shows Model Download status
- Reported by `[\#As_Warp#/]`
- `[\#As_Warp#/]` identified issues when Jan was installed through both Debian and AppImage, indicating some deeper problem with Model Downloads

**Steps to reproduce**
1. When I click on a model to download it shows as downloaded instantly without actually using the network
2. Then when opening a conversation, Jan fails with "something's amiss". 
3. There is no way to resolve this unless deleting the folders manually (rm -rf ~/jan/models). 
4. It may or may not be related with incorrectly setting folder permissions during installation. 
5. There seems to exist some deeper running problem because Jan should not identify an incomplete model download as complete until the whole GGUF file has indeed been downloaded.

Link to Discord Message: https://discord.com/channels/1107178041848909847/1199071224626696198/1205962425468321862

Example: LlaVa got stuck at 0% with the AppImage, but shows up as downloaded in the Hub, and can be "used" (produces gibberish). 
https://discord.com/channels/1107178041848909847/1199071224626696198/1206160647457341450

**Expected behavior**
- Model download should fail if unable to write to filesystem
- Model should not show up as downloaded in the Hub if it was not successfully downloaded. 

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-17-generic (64-bit)
Graphics Platform: X11
Processors: 24 × 12th Gen Intel® Core™ i9-12900F
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
jan-linux-x86_64-0.4.6.AppImage
```

**Logs**

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
I will continue the investigation once this issue is resolved https://github.com/janhq/jan/issues/2033

**Comment by Van-QA** [comment]
Tested and working fine as of Jan v0.4.7-293 ✅ 


<img width="982" alt="image" src="https://github.com/janhq/jan/assets/64197333/0ee6fdab-96b8-4cfd-911e-2418a0d000ea">
