### ISSUE TITLE
feat: Uninstalling Jan on Kubuntu 22.04 does not delete Jan folders at /home

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#1999]
**Describe the bug**
By the way, uninstalling Jan (sudo apt-get remove jan) does not delete jan folders at /home, and it should (rm -rf ~/jan)

**Steps to reproduce**
- By the way, uninstalling Jan (sudo apt-get remove jan) does not delete jan folders at /home, and it should (rm -rf ~/jan)

Link to Discord Message: 
https://discord.com/channels/1107178041848909847/1199071224626696198/1205962425468321862

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
```
Operating System: Kubuntu 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.5.0-17-generic (64-bit)
Graphics Platform: X11
Processors: 24 × 12th Gen Intel® Core™ i9-12900F
Memory: 31.2 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
jan-linux-x86_64-0.4.6.AppImage
```

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
Related to https://github.com/janhq/jan/issues/1654. Hence, I'm closing this to avoid pilling up similar tickets.
