### ISSUE TITLE
Epic: Jan Server

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#200]
Motivation: 
- Users can host a private AI Server and share it via Desktop App & web

**Success Criteria:**

Admin

- Admin can ngrok & share their local server using a public url
- Admin get a warning message that this is for trusted friends/teams
- Out of scope: full on RBAC
- Q: Admin can set a simple server authentication method (shared pw, api key, @hien to research)?

User
- Users can add a remote Jan Server URL
- Users can do the simple authentication (see above)
- Users can select a remote server to chat with
- Users CANNOT edit model settings
- Q: Can users initialize remote models or can only use active models?

**UX Inspo** 
- Element
- Obsidian

**Comment by nam-john-ho** [comment]
Solution:
- **Remote Server Plugin** for Desktop App: store server credential (url, token) in local database(pouchDB), open the new electron window with remote server url
- **Jan Server**: offer sample page to manage users , authenticate requests.
UI:
<img width="1131" alt="Screenshot 2023-10-19 at 11 17 48" src="https://github.com/janhq/jan/assets/146448941/79fab604-1449-4465-9dc2-fbe5bd861f0a">

Flow:
<img width="547" alt="Screenshot 2023-10-19 at 11 17 16" src="https://github.com/janhq/jan/assets/146448941/b2cd66f7-838c-4858-a2d6-90d40ffe742e">
Arch:

<img width="714" alt="Screenshot 2023-10-19 at 11 22 38" src="https://github.com/janhq/jan/assets/146448941/eedccf06-3a08-4638-b2d6-15042065d39d">

**Comment by 0xSage** [comment]
Iced
