### ISSUE TITLE
feat: Multilingual interface

### ISSUE THREAD

**Issue by dev-coco** [janhq/jan#2004]
**Problem**
Are there plans to support multiple languages?

**Comment by hahuyhoang411** [comment]
Hi @dev-coco , normally, models on the hub can understand many languages at certain level. Also we've already added some model specific for some languages.

Chinese: Deepseek, Qwen.
For other languages: Gemma (Google)

If you want to use any models with your favor. Please read through this instruction.

https://jan.ai/guides/using-models/import-manually/
