### ISSUE TITLE
epic: Jan core supports Text to speech extensions

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2006]
**Problem**

Awesome demo from Tessy: https://discord.com/channels/1107178041848909847/1205885629179625503/1205889029766254602

**Success Criteria**

- [ ] incorporate this as an official extension
- [ ] designs needed

**Additional context**

**Comment by imtuyethan** [comment]
Moving this to Notion til it is confirmed: https://www.notion.so/jan-ai/Jan-core-supports-Text-to-speech-extensions-9a65ab722e7848a1904fbbc6b53c31df?pvs=4
