### ISSUE TITLE
feat: fix problem where log files get really big after an app error

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2007]
**Problem**
<img width="1143" alt="image" src="https://github.com/janhq/jan/assets/69952136/8ea74b07-432d-48cf-88ba-cd6a4c4f223d">

**Success Criteria**

A few potential solutions: 
- auto delete logs after 24 hours - but let users turn this off
- preferred: do a error deep dive and actually curate what logs make it to the user, instead of outputing all. 

**Additional context**

**Comment by louis-jan** [comment]
Addressed
https://github.com/janhq/jan/pull/2003

**Comment by Van-QA** [comment]
Tested and looking good on Jan v0.4.6-270 ✅
