### ISSUE TITLE
feat: Quote source in answer using retrieval on

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#2009]
**Problem**
- While chatting with my local file, I find it useful if I can see the references that LLM uses in order to answer me
- See the example I captured from my ChatPDF. It can tell me exactly the portion in file that it uses in order to answer me, which help me a lot in verifying answer.
![CleanShot 2024-02-13 at 14 30 51@2x](https://github.com/janhq/jan/assets/22463238/9ab820d8-9500-41e6-8e76-cfb133aeafb2)

**Success Criteria**
- In the current implementation at https://github.com/janhq/jan/blob/dev/extensions/assistant-extension/src/node/tools/retrieval/index.ts#L74, Jan only return the related string. However, this line returns the location (document with page) as well for reference. By restructuring the result, Jan can show the reference.
- Turn off this by toggling off `Tools -> Retrieval`

**Additional context**
- This might need @imtuyethan for the design!

**Comment by imtuyethan** [comment]
Moving this to Notion til it is confirmed: https://www.notion.so/jan-ai/RAG-enhancement-c609fae1fd7b497f974e387bcce5a71b?pvs=4
