### ISSUE TITLE
Discussion: Is it possible to install Jan in a remote server to use as inference server?

### ISSUE THREAD

**Issue by afanjul** [janhq/jan#2012]
**Motivation**
I'm trying to install Jan as AI inference server in a remote server with 64Gb of RAM and no GPU neither Display at all. Is it possible to install it and use it as remote inference server?

**Discussion**
I have successfully installed the Jan .deb but when I start it executing "jan" it throws the following error:
```
[2817:0213/120053.887084:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
[2817:0213/120053.887152:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
 ```

So maybe is not possible to use it?

**Alternatives**
Maybe I'm crazy but is even possible at all to do what I'm trying to achieve with any software like LM Studio, oobaboga, Jan? I.e. use a remote server with lots of RAM as my AI inference server so offloading the RAM usage to the remote server and just use a light UI client connected to my remote server. I cannot see any tutorials on internet (neither in google nor youtube), all tutorials and guides are towards the installation on local machines.

**Resources**

**Comment by louis-jan** [comment]
> **Motivation** I'm trying to install Jan as AI inference server in a remote server with 64Gb of RAM and no GPU neither Display at all. Is it possible to install it and use it as remote inference server?
> 
> **Discussion** I have successfully installed the Jan .deb but when I start it executing "jan" it throws the following error:
> 
> ```
> [2817:0213/120053.887084:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
> [2817:0213/120053.887152:ERROR:env.cc(257)] The platform failed to initialize.  Exiting.
> ```
> 
> So maybe is not possible to use it?
> 
> **Alternatives** Maybe I'm crazy but is even possible at all to do what I'm trying to achieve with any software like LM Studio, oobaboga, Jan? I.e. use a remote server with lots of RAM as my AI inference server so offloading the RAM usage to the remote server and just use a light UI client connected to my remote server. I cannot see any tutorials on internet (neither in google nor youtube), all tutorials and guides are towards the installation on local machines.
> 
> **Resources**

FYI: We added docker support for hosting inference server here: 
https://github.com/janhq/jan/blob/dev/docker-compose.yml

**Comment by 0xSage** [comment]
Yep! set up instructions here: https://jan.ai/guides/using-models/integrate-with-remote-server/

basically you can do: 
backend: any OAI compatible endpoint (including Jan itself)
frontend: use Jan on your client and point it to the remote server (see docs)

**Comment by afanjul** [comment]
> Yep! Also there are easier set up instructions (without docker) here: https://jan.ai/guides/using-models/integrate-with-remote-server/
> 
> 
> 
> You can explore both to see which suites your needs.
> 
> 
> 
> basically you can do: 
> 
> backend: any OAI compatible endpoint (including Jan itself)
> 
> frontend: use Jan on your client and point it to the remote server (see docs)

In that guide doesn't explain how to run Jan as "only listening" inference server (without the need of a display/GPU)

**Comment by 0xSage** [comment]
> > Yep! Also there are easier set up instructions (without docker) here: https://jan.ai/guides/using-models/integrate-with-remote-server/
> > You can explore both to see which suites your needs.
> > basically you can do:
> > backend: any OAI compatible endpoint (including Jan itself)
> > frontend: use Jan on your client and point it to the remote server (see docs)
> 
> In that guide doesn't explain how to run Jan as "only listening" inference server (without the need of a display/GPU)

Ah, you want headless, then yes you need this: https://github.com/janhq/jan/blob/dev/docker-compose.yml
We don't have a user guide for this yet, but its a `docker compose`, so it should just run
