### ISSUE TITLE
bug: regenerating responses causes Nitro cache error

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2014]
**Describe the bug**

<img width="762" alt="image" src="https://github.com/janhq/jan/assets/69952136/54a68495-661f-430b-843e-13c2acd1c7f8">

This has been a known issue for months. What's our plan to fixing this?

**Comment by louis-jan** [comment]
Addressed, Nitro 0.3.9.
https://github.com/janhq/nitro/releases/tag/v0.3.9

**Comment by 0xSage** [comment]
> Addressed, Nitro 0.3.9. https://github.com/janhq/nitro/releases/tag/v0.3.9

Thank you @Van-QA to QA this with next release 🙏

**Comment by Van-QA** [comment]
The fix from @louis-jan seems to reduce the issue of Nitro crashes a lot ✅ . It would be best if the user could experience the change himself.
<img width="574" alt="image" src="https://github.com/janhq/jan/assets/64197333/46434ec0-95b0-44a0-9195-a940f70dc11a">
