### ISSUE TITLE
style: improve Jan docs/landing page

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#202]
0. Screenshots take too long to load

1. Update light/dark desktop screenshots (right now I pasted in low fi designs as temp placeholders)

2. Color Palette
- Problem: Right now, we use the default Docusaurus green for our landing page & docs site color palete, see: 
https://docusaurus.io/docs/styling-layout#styling-your-site-with-infima
- File location: /docs/src/css/custom.css
- Success criteria: A new color palette, not green, for both :root and data-theme=dark
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaHZQIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf18f856f6c0db59806356ee06a023a5c5ba31f9/image.png)

**Comment by drakehere** [comment]
I have made a draft PR for this issue: https://github.com/janhq/jan/pull/213

**Comment by drakehere** [comment]
Update what to do on Oct 6:
- CTA Buttons' colors should be updated to be consistent with Jan App screenshots
- Improve highlight colors (KIV)

**Comment by 0xSage** [comment]
more or less done
