### ISSUE TITLE
test: Integrate Trace Viewer with Playwright for Jan Electron App

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2047]
In this task, we'll boost our testing capabilities by adding Trace Viewer functionality to our Playwright tests for the Electron desktop application. Trace Viewer offers detailed insights into test performance, aiding in optimization and debugging.
https://playwright.dev/docs/trace-viewer
https://stackoverflow.com/questions/74109625/how-to-create-self-hosted-playwright-trace-viewer

## Key Components:

1. Integration: Configure Trace Viewer to capture detailed traces of Playwright's interactions with the Electron app, including network requests and JavaScript execution.

2. Performance Analysis: Utilize Trace Viewer to analyze metrics like page load times and resource utilization, identifying areas for optimization.

3. Debugging: Leverage Trace Viewer's debugging features to troubleshoot issues encountered during test execution, enhancing efficiency.

4. Continuous Improvement: Incorporate insights from Trace Viewer to refine test scripts and optimize automation, driving ongoing enhancement.

By integrating Trace Viewer with Playwright for our Electron app, we gain valuable performance insights, enabling us to deliver high-quality software efficiently, elevate our testing process, and ensure top-notch user experiences.

By default, trace viewer usually works with browsers, which causes the problem of incorrectly captured output (see screenshot).
this fix will cover the configuration of electron app for Trace viewer
<img width="1513" alt="image" src="https://github.com/janhq/jan/assets/64197333/daedd138-bf06-410b-9eaf-2d7862bf7fa8">

**Comment by dan-homebrew** [comment]
Closing in favor of #3632
