### ISSUE TITLE
download failed: read ECONNRESET

### ISSUE THREAD

**Issue by tyultra** [janhq/jan#2049]
**Describe the bug**
Fail to download all the recommended models, showing that "download failed: read ECONNRESET".

**Screenshots**
<img width="1200" alt="image" src="https://github.com/janhq/jan/assets/36122504/115e7ff9-1b9f-492f-b16e-34c3b27b85ca">

**Environment details**
- MacBook Air M2, MacOS 14.3

**Additional context**
I tried using VPN, but failed again.

Thanks.

**Comment by Van-QA** [comment]
@tyultra  can you try using our http setting within this #1562 
this ticket is related to the document of https://github.com/janhq/jan/issues/1868
