### ISSUE TITLE
[Jan Desktop] App Auto Updater

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#205]
**Success criteria**
- When users open up the desktop app, it should automatically install the latest version
- It should install the latest patch: X.X.X
- Bottom bar should display "installing" with a progress bar
- https://www.figma.com/file/JdK7cNIBeVdYeHxKiYeWtk/JAN---Web?type=design&node-id=2904-4511&mode=design&t=fW5xyCErCHizhoAT-0

**Nice to have:**
- The progress bar

**Not in scope**
- A button in settings to turn off auto install
- Then users should be prompted to manually install the app

**Comment by 0xSage** [comment]
@louis-jan see updated task description. We can keep it simple

**Comment by louis-jan** [comment]
Right after user opens the app:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa0xpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--994bc3a53b9052191c1702351b671e16f7ffea00/Screenshot%202023-09-27%20at%2022.54.39.png)

Confirm to download update & install
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1BpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--26e8daa61faecf05e26461bc6dad3e53bbf9801e/Screenshot%202023-09-27%20at%2022.54.42.png)

App auto restart after installed the update
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3JpIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8a0d3cb5a1b26a031ad033d145fb4a5366874e03/Screenshot%202023-09-27%20at%2022.53.57.png)

**Comment by 0xSage** [comment]
This is done by Louis
