### ISSUE TITLE
 bug: Error invoking remote method 'readdirSync'

### ISSUE THREAD

**Issue by gogojames** [janhq/jan#2055]
Registering events 2835-2cce938d894ae1de.js:213 
Error: Error invoking remote method 'readdirSync': Error: ENOTDIR: not a directory, scandir

**Comment by gogojames** [comment]
Mac mini

**Comment by Van-QA** [comment]
Hi @gogojames, it's Van from eng team
From what you provided, only the error is not enough for us to investigate.

Please share with us:
- Steps to reproduce
- Your OS and spec: CPU serial, memory
- The model you tried
- Your app.log

**Comment by louis-jan** [comment]
I can reproduce this issue by trying to place a raw file, instead of folders, under /threads and /assistants. I think James accidentally created some files there. Could you please try to delete them? We will fix the broken data issue in 0.4.9.

**Comment by Van-QA** [comment]
hi @gogojames, if possible, can you try again using our latest build Jan v0.4.9-345? and see if the issue persists?
