### ISSUE TITLE
I want to know how to fine-tune jan and add new corpus

### ISSUE THREAD

**Issue by lv333ming** [janhq/jan#2058]
**Motivation**
I haven’t seen how to do fine-tuning yet, so I hope you can help.
**Discussion**

**Alternatives**

**Resources**

**Comment by SweetpopcornSimon** [comment]
I too am interested in this? It would be great it we could easily add documents to a model. Instead of having to fine tune a model with hugging face and then import it

**Comment by hahuyhoang411** [comment]
Jan will support finetuning in the future. Please stay tuned.
