### ISSUE TITLE
feat: inference-mistral-extension

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2072]
**Problem**

We ❤️ mistral

**Success Criteria**

- similar to openai remote api 
- lets have a mistral remote api

**Additional context**

**Comment by louis-jan** [comment]
> openai

Is this the one I mentioned earlier for you to refactor, @hiro-v? Would you like to take ownership of this task?

**Comment by louis-jan** [comment]
As a part of Inference Provider revamp epic

**Comment by Van-QA** [comment]
hi @Inchoker, the case of invalid API for Mistral extension, is throwing something amiss :x:

![Image](https://github.com/janhq/jan/assets/64197333/4c47c7d4-695b-4543-99c8-e1e0260f6873)

Expectation ✅ : 
Similar to other extension, to highlight the invalid API key: Invalid API key. Please check your API key from Settings and try again.

![Image](https://github.com/janhq/jan/assets/64197333/6b249582-03c9-41b4-ad4b-fef6bad66060)

**Comment by Van-QA** [comment]
![image](https://github.com/janhq/jan/assets/64197333/c0789510-7afa-40c8-ae95-3f66a127bb25)
looking good on Jan v0.4.10-369 ✅
