### ISSUE TITLE
bug: HTTP Proxy - App is stuck at downloading with error: tunneling socket could not be established

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2080]
**Describe the bug**
Users downloading models from the Hub encounter an error when HTTPS proxy is turned ON and Proxy endpoint is not working.
`Model undefined download failed: tunneling socket could not be established, cause=connect ECONNREFUSED 127.0.0.1:9028
`

**Steps to reproduce**

1. Open Jan and navigate to the Hub.
2. Select a model for download.
3. Enable HTTPS proxy settings.
4. Attempt to download the model.
5. Error occurs.

**Expected behavior**
The model should download successfully even when HTTPS proxy is turned ON.

**Screenshots**
<img width="1271" alt="image" src="https://github.com/janhq/jan/assets/64197333/f999da30-12f8-4685-9dbb-8d1aa9b13c7d">

**Environment details**
- Operating System: MacOS
- Jan Version: latest nightly build
- Processor: Apple M2 Pro
- RAM: 16GB
**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by namchuai** [comment]
@Van-QA , please help to validate this. Thank you!

**Comment by Van-QA** [comment]
Tested and looking good on Jan Jan v0.4.7-295 ✅
