### ISSUE TITLE
Jan has better Error Reporting Process

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#2090]
## Specs

https://www.notion.so/jan-ai/Address-Copious-Nitro-issues-and-Better-Reporting-3d6944c3fb7b41429dee3e44432dc3a8?pvs=4

**Comment by Van-QA** [comment]
Closing this as the issue will be handled in
- https://github.com/janhq/jan/issues/1784
- https://github.com/janhq/nitro/issues/369
