### ISSUE TITLE
How to fix it if it's running slow

### ISSUE THREAD

**Issue by zlzzzlll** [janhq/jan#2095]
My computer configuration is as follows
WIN11, 16 cores 32 threads CPU,64GB RAM, 4090 video card.
Question:
1, can't run 18G and above models
2, With the general model, the speed is up to Token Speed: 100.57/s when answering the first question, and becomes extremely slow when answering the second question
, Is there a problem with my settings somewhere?

**Comment by louis-jan** [comment]
> My computer configuration is as follows WIN11, 16 cores 32 threads CPU,64GB RAM, 4090 video card. Question: 1, can't run 18G and above models 2, With the general model, the speed is up to Token Speed: 100.57/s when answering the first question, and becomes extremely slow when answering the second question , Is there a problem with my settings somewhere?

Hi @zlzzzlll, what version are you on?

**Comment by zlzzzlll** [comment]
> > 我的电脑配置如下WIN11，16核32线程CPU，64GB RAM，4090显卡。问题：1、无法运行18G及以上机箱2、使用通用机箱，回答第一个问题时速度达到Token Speed: 100.57/ s，回答第二个问题的时间变得极慢，我的设置是否在某处有问题？
> 
> 你好@zlzzzlll，你用的是什么版本？

windows 11 professional 22H2,JAN is the latest version 0.46

**Comment by zlzzzlll** [comment]
@louis-jan 
HI,windows 11 professional 22H2,JAN is the latest version 0.46

**Comment by louis-jan** [comment]
I see, could you please try latest nightly build? It seems to be resolved on this build.

**Comment by zlzzzlll** [comment]
@louis-jan Okay, I'll try uninstalling and reinstalling.

**Comment by zlzzzlll** [comment]
@louis-jan Problems remain

**Comment by Van-QA** [comment]
> @louis-jan Problems remain

can you give us the app.log? thanks

**Comment by zlzzzlll** [comment]
@Van-QA It's all an error.2024-02-20T08:46:58.086Z [NITRO]::CPU informations - 172024-02-20T08:46:58.088Z [NITRO]::Debug: Request to kill Nitro
2024-02-20T08:46:58.111Z [NITRO]::Debug: Nitro process is terminated
2024-02-20T08:46:58.619Z [NITRO]::Debug: Spawn nitro at path: C:\Users\LZ\jan\extensions\@janhq\inference-nitro-extension\dist\bin\win-cuda-12-0\nitro.exe, and args: 
2024-02-20T08:46:59.633Z [NITRO]::Error:   Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes
2024-02-20T08:46:59.800Z [NITRO]::Error: llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from C:\Users\LZ\jan\models\openchat-3.5-7b\openchat-3.5-1210.Q4_K_M.gguf (version GGUF V3 (latest))
llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output.
llama_model_loader: - kv   0:                       general.architecture str              = llama
llama_model_loader: - kv   1:                               general.name str              = openchat_openchat-3.5-1210
llama_model_loader: - kv   2:                       llama.context_length u32              = 8192
llama_model_loader: - kv   3:                     llama.embedding_length u32              = 4096
llama_model_loader: - kv   4:                          llama.block_count u32              = 32
llama_model_loader: - kv   5:                  llama.feed_forward_length u32              = 14336
llama_model_loader: - kv   6:                 llama.rope.dimension_count u32              = 128
llama_model_loader: - kv   7:                 llama.attention.head_count u32              = 32
llama_model_loader: - kv   8:              llama.attention.head_count_kv u32              = 8

2024-02-20T08:46:59.800Z [NITRO]::Error: llama_model_loader: - kv   9:     llama.attention.layer_norm_rms_epsilon f32              = 0.000010
llama_model_loader: - kv  10:                       llama.rope.freq_base f32              = 10000.000000
llama_model_loader: - kv  11:                          general.file_type u32              = 15
llama_model_loader: - kv  12:                       tokenizer.ggml.model str              = llama

2024-02-20T08:46:59.809Z [NITRO]::Error: llama_model_loader: - kv  13:                      tokenizer.ggml.tokens arr[str,32002]   = ["<unk>", "<s>", "</s>", "<0x00>", "<...

2024-02-20T08:46:59.829Z [NITRO]::Error: llama_model_loader: - kv  14:                      tokenizer.ggml.scores arr[f32,32002]   = [0.000000, 0.000000, 0.000000, 0.0000...

2024-02-20T08:46:59.832Z [NITRO]::Error: llama_model_loader: - kv  15:                  tokenizer.ggml.token_type arr[i32,32002]   = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ...
llama_model_loader: - kv  16:                tokenizer.ggml.bos_token_id u32              = 1
llama_model_loader: - kv  17:                tokenizer.ggml.eos_token_id u32              = 32000
llama_model_loader: - kv  18:            tokenizer.ggml.padding_token_id u32              = 0
llama_model_loader: - kv  19:               tokenizer.ggml.add_bos_token bool             = true
llama_model_loader: - kv  20:               tokenizer.ggml.add_eos_token bool             = false
llama_model_loader: - kv  21:                    tokenizer.chat_template str              = {{ bos_token }}{% for message in mess...
llama_model_loader: - kv  22:               general.quantization_version u32              = 2
llama_model_loader: - type  f32:   65 tensors
llama_model_loader: - type q4_K:  193 tensors
llama_model_loader: - type q6_K:   33 tensors

2024-02-20T08:46:59.851Z [NITRO]::Error: llm_load_vocab: special tokens definition check successful ( 261/32002 ).

**Comment by louis-jan** [comment]
> @Van-QA It's all an error.2024-02-20T08:46:58.086Z [NITRO]::CPU informations - 172024-02-20T08:46:58.088Z [NITRO]::Debug: Request to kill Nitro 2024-02-20T08:46:58.111Z [NITRO]::Debug: Nitro process is terminated 2024-02-20T08:46:58.619Z [NITRO]::Debug: Spawn nitro at path: C:\Users\LZ\jan\extensions@janhq\inference-nitro-extension\dist\bin\win-cuda-12-0\nitro.exe, and args: 2024-02-20T08:46:59.633Z [NITRO]::Error: Device 0: NVIDIA GeForce RTX 4090, compute capability 8.9, VMM: yes 2024-02-20T08:46:59.800Z [NITRO]::Error: llama_model_loader: loaded meta data with 23 key-value pairs and 291 tensors from C:\Users\LZ\jan\models\openchat-3.5-7b\openchat-3.5-1210.Q4_K_M.gguf (version GGUF V3 (latest)) llama_model_loader: Dumping metadata keys/values. Note: KV overrides do not apply in this output. llama_model_loader: - kv 0: general.architecture str = llama llama_model_loader: - kv 1: general.name str = openchat_openchat-3.5-1210 llama_model_loader: - kv 2: llama.context_length u32 = 8192 llama_model_loader: - kv 3: llama.embedding_length u32 = 4096 llama_model_loader: - kv 4: llama.block_count u32 = 32 llama_model_loader: - kv 5: llama.feed_forward_length u32 = 14336 llama_model_loader: - kv 6: llama.rope.dimension_count u32 = 128 llama_model_loader: - kv 7: llama.attention.head_count u32 = 32 llama_model_loader: - kv 8: llama.attention.head_count_kv u32 = 8
> 
> 2024-02-20T08:46:59.800Z [NITRO]::Error: llama_model_loader: - kv 9: llama.attention.layer_norm_rms_epsilon f32 = 0.000010 llama_model_loader: - kv 10: llama.rope.freq_base f32 = 10000.000000 llama_model_loader: - kv 11: general.file_type u32 = 15 llama_model_loader: - kv 12: tokenizer.ggml.model str = llama
> 
> 2024-02-20T08:46:59.809Z [NITRO]::Error: llama_model_loader: - kv 13: tokenizer.ggml.tokens arr[str,32002] = ["", "", "", "<0x00>", "<...
> 
> 2024-02-20T08:46:59.829Z [NITRO]::Error: llama_model_loader: - kv 14: tokenizer.ggml.scores arr[f32,32002] = [0.000000, 0.000000, 0.000000, 0.0000...
> 
> 2024-02-20T08:46:59.832Z [NITRO]::Error: llama_model_loader: - kv 15: tokenizer.ggml.token_type arr[i32,32002] = [2, 3, 3, 6, 6, 6, 6, 6, 6, 6, 6, 6, ... llama_model_loader: - kv 16: tokenizer.ggml.bos_token_id u32 = 1 llama_model_loader: - kv 17: tokenizer.ggml.eos_token_id u32 = 32000 llama_model_loader: - kv 18: tokenizer.ggml.padding_token_id u32 = 0 llama_model_loader: - kv 19: tokenizer.ggml.add_bos_token bool = true llama_model_loader: - kv 20: tokenizer.ggml.add_eos_token bool = false llama_model_loader: - kv 21: tokenizer.chat_template str = {{ bos_token }}{% for message in mess... llama_model_loader: - kv 22: general.quantization_version u32 = 2 llama_model_loader: - type f32: 65 tensors llama_model_loader: - type q4_K: 193 tensors llama_model_loader: - type q6_K: 33 tensors
> 
> 2024-02-20T08:46:59.851Z [NITRO]::Error: llm_load_vocab: special tokens definition check successful ( 261/32002 ).

I think the log is cleared, no token speed recorded. Could you please try send multiple requests, capture the logs and duplicate it here again?

**Comment by zlzzzlll** [comment]
@louis-jan I have no experience in programming and the APP.LOG file is actually 20 gigs. can you tell me if emptying this file will have any effect on JAN? Thank you!

**Comment by louis-jan** [comment]
> @louis-jan I have no experience in programming and the APP.LOG file is actually 20 gigs. can you tell me if emptying this file will have any effect on JAN? Thank you!

Hey sorry for that, it should be cleared automatically on the latest nightly build. Please feel free to delete this file as anytime.

**Comment by louis-jan** [comment]
@zlzzzlll. Looks like you are still on latest release build.

Could you please try install this build.
https://delta.jan.ai/latest/jan-win-x64-0.4.6-276.exe

Also, based on the log you provided, the token speeds are:
- 105.54
- 114.32
- 91.83
- 114.82
- Last attempt: 65.99. Please help check if this will go back to normal in the next attempts?

**Comment by zlzzzlll** [comment]
@louis-jan After I deleted APP.LOG and repeated typing a word, the speed was improved, but still trending downward

**Comment by louis-jan** [comment]
@zlzzzlll. Please try install nightly build, https://delta.jan.ai/latest/jan-win-x64-0.4.6-276.exe

**Comment by zlzzzlll** [comment]
@louis-jan To install this link you posted, do I have to uninstall the entire previous installation of JAN?

**Comment by louis-jan** [comment]
> @louis-jan It's a direct install, right?
@zlzzzlll, yes it will overwrite the existing version

**Comment by zlzzzlll** [comment]
@louis-jan Okay, I'll try. Thank you.

**Comment by zlzzzlll** [comment]
@louis-jan Hi, seems to have solved my dilemma, thank you! Also, this version you gave me which I have installed, will I be automatically prompted to upgrade in the future? If not, where can I download the latest latest nightly build? Can you give me a link? So that I can still use this method to solve the problem in the future. Thanks again!

**Comment by louis-jan** [comment]
> @louis-jan Hi, seems to have solved my dilemma, thank you! Also, this version you gave me which I have installed, will I be automatically prompted to upgrade in the future? If not, where can I download the latest latest nightly build? Can you give me a link? So that I can still use this method to solve the problem in the future. Thanks again!

It would prompt you to upgrade automatically, or you can go to "Jan" > "Check for Updates" to upgrade. Don't have to download new build manually.

**Comment by louis-jan** [comment]
You can also find the latest nightly build on our website or Discord channel.
