### ISSUE TITLE
Discussion: about jan logs app large

### ISSUE THREAD

**Issue by aidec** [janhq/jan#2100]
I installed it for a few days and used it less than ten times. However, the logs app file is 
over 100 GB. Is this normal?

![螢幕擷取畫面 2024-02-19 232906](https://github.com/janhq/jan/assets/5707556/815b1cbe-f5f0-4b23-b715-ee9e67951b62)

**Comment by Van-QA** [comment]
hi @aidec, If the Jan app is functioning properly on your side, then there is no need to worry.
We resolved the issue with log size recently: https://github.com/janhq/jan/issues/2002 which will be available within the 0.4.7
