### ISSUE TITLE
epic: Rebase Nitro on Llama.cpp (as Jan.cpp)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2103]
## Motivation
- Problem: llama.cpp server has limitations for prod use and as an embedded lib
- Rebase on llama.cpp
- Be a reference implementation for a serious server
- Work with llama.cpp ecosystem, prioritize upstream contributions.

## Specs
- Jan.cpp is a direct fork of llama.cpp
- proper queue system

@louis-jan :
- Rework ggml as a library. 
- Refactor for better exception handler / error events / return codes / general logging

@tikikun 
there are some pending issues that i were planning regarding:
- Remove llama server example nlohmann json use
- Remove thread locking logging of llama cpp server
- Remove llama server cpp queue logic

We have some added features:
- Multiple mount points
- Details thread-pool control
- Custom queue logic

## Tasklist
- [ ] 

## Not in Scope
-

**Comment by louis-jan** [comment]
This one is deprecated @tikikun
