### ISSUE TITLE
bug:  models Inactive

### ISSUE THREAD

**Issue by as0026** [janhq/jan#2107]
Mistral Instruct 7B Q4模型启动失败。
我的电脑是16G内存，RTX 1650显卡。
![微信截图_20240220195337](https://github.com/janhq/jan/assets/16164207/3d3340c8-2f32-4d1e-a791-5fe9c9f129e4)

**Comment by Van-QA** [comment]
hi @as0026, as you can see from the screenshot, there is a three dots button available next to the inactive, where you can use it to start the model, can you try it?
I hope it helps

**Comment by as0026** [comment]
> hi @as0026, as you can see from the screenshot, there is a three dots button available next to the inactive, which you can use it to start the model, can you try it? I hope it helps

Hi, I clicked start multiple times and it still doesn’t work.

**Comment by Van-QA** [comment]
> > hi @as0026, as you can see from the screenshot, there is a three dots button available next to the inactive, which you can use it to start the model, can you try it? I hope it helps
> 
> Hi, I clicked start multiple times and it still doesn’t work.

I see the problem, we are planning to remove that model soon due to some issues, can you try with other models? e.g. tinyllama?

**Comment by as0026** [comment]
> > > hi @as0026, as you can see from the screenshot, there is a three dots button available next to the inactive, which you can use it to start the model, can you try it? I hope it helps
> > 
> > 
> > Hi, I clicked start multiple times and it still doesn’t work.
> 
> I see, can you try with other smaller models? e.g. tinyllama? Can you give us the Jan version that you are using?

It can be activated by changing to tinyllama, thanks
