### ISSUE TITLE
docs: Jan to have an acknowledgements page

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2109]
**Pages**
- /acknowledgements

**Success Criteria**
Content that should be covered
- we should link to it from the app itself.
- inspo: https://www.raycast.com/acknowledgements
- To credit: 
  - llamacpp
  - langchain
  - hsnw?
  - TBA

**Additional context**
Examples, reference pages, resources

**Comment by hieu-jan** [comment]
As we import [`HNSWLib](https://js.langchain.com/docs/integrations/vectorstores/hnswlib), so we also credit together with langchain
