### ISSUE TITLE
总是提示 Download Failed Model mistral-ins-7b-g4 download failed: connect ETIMEDOUT 199.59.149.238:443

### ISSUE THREAD

**Issue by ssomoss** [janhq/jan#2115]
下载模型一直失败 是否可以提供手动下载 然后放入指定文件夹的方式

**Comment by iLern** [comment]
默认下载模型是通过huggle face，在国内不好连接下载，可以修改下载方式为镜像站 https://hf-mirror.com/ 再下载

修改方法：
设置-高级设置-Jan Data Folder
找到你想下载的模型对应的文件夹，修改里面的model.json，把URL改成镜像站
<img width="721" alt="image" src="https://github.com/janhq/jan/assets/43905872/48fefc6d-987f-4216-a401-37f72dd4a8fb">
<img width="498" alt="image" src="https://github.com/janhq/jan/assets/43905872/16cec545-859b-4ec2-96e6-0784c8628236">


重启Jan即可下载

**Comment by ssomoss** [comment]
感谢大佬详细耐心的指点 修改后已经成功下载

**Comment by Van-QA** [comment]
Thank you for your help, cc: @hieu-jan to note this down in our docs

**Comment by hieu-jan** [comment]
For this issue, our proxy docs could solve this issue. #2054

**Comment by axetroy** [comment]
What if there is no HTTP/s proxy?

Should Jan consider setting a mirror address?
