### ISSUE TITLE
bug: Nvidia GPU

### ISSUE THREAD

**Issue by as0026** [janhq/jan#2122]
我的电脑配置是：NVIDIA GEFORCE GTX 1650
安装了的显卡驱动是：551.23
CUDA安装的是11.7

在“Enable GPU acceleration for Nvidia GPUs.”中开启有一个弹框提示“Checking for machine that does not meet the requirements.”
点击之后开关按钮为开启状态。
我在实际使用中，需要较长时间才回答，CPU数字在走高，GPU的却没有怎么变化。
![微信截图_20240221111008](https://github.com/janhq/jan/assets/16164207/c80e248d-9e0b-4851-aa72-858e5c6607ee)
![微信截图_20240222145404](https://github.com/janhq/jan/assets/16164207/cf41c338-d022-43fa-bf03-bdfd0777288c)

**Comment by hiento09** [comment]
hi @as0026, could you help to provide which version of Jan app cause the error and also `logs/app.log`, `settings/settings.json` files in jan folder? Thank you!

**Comment by Van-QA** [comment]
hi @as0026, can you try our latest nightly build and see if the issue is resolved?

**Comment by as0026** [comment]
> hi @as0026, can you try our latest nightly build and see if the issue is resolved?

The NVIDIA GPU can be turned on normally using nightly build, but the activation of the 2 downloaded models fails.
![微信截图_20240223180056](https://github.com/janhq/jan/assets/16164207/009d87f6-cd9e-422b-b686-e28c3a0626ed)
![微信截图_20240223180116](https://github.com/janhq/jan/assets/16164207/783f4511-d2dd-48c4-b701-cb6055350598)
[app.log](https://github.com/janhq/jan/files/14383971/app.log)
[settings.json](https://github.com/janhq/jan/files/14383973/settings.json)

**Comment by Van-QA** [comment]
hi @as0026  can you try turning on the Vulkan support in the settings? 
<img width="1268" alt="image" src="https://github.com/janhq/jan/assets/64197333/50aaeb87-1fbc-47c7-8a9a-97b6c5c1d414">
