### ISSUE TITLE
bug: Can not downlowd models directly

### ISSUE THREAD

**Issue by sun-foundation** [janhq/jan#2126]
**Expected behavior**
Fail to download the model, only can download by self.

**Screenshots**
[
<img width="476" alt="屏幕截图 2024-02-22 194015" src="https://github.com/janhq/jan/assets/62006379/ae3145ba-1f0b-411d-9710-bf97e5eef6b9">
](url)

**Environment details**
- Operating System: Windows 11
- Jan Version:0.4.6
- Processor: Intel 13600k
- RAM: 32GB
- Any additional relevant hardware specifics: NVIDIA 4070Ti

**Comment by Van-QA** [comment]
hi there, can you try this #2049?

**Comment by msjsc001** [comment]
我下载一直也有问题，希望官方能在设置里更换到镜像网站，逐个修改文件很繁琐。
I've been having problems with the download as well, hopefully the officials will replace it in the settings to a mirror site, it's tedious to change the files one by one.
