### ISSUE TITLE
bug: There is no way to load a model from the docker local server

### ISSUE THREAD

**Issue by HyperCrowd** [janhq/jan#2129]
**Describe the bug**
There is no way to load a model into Minio purely from the docker local server

**Steps to reproduce**

- Checkout project from Git
- Go to the `models` folder
- Run `curl -O <url for Mistral model in model.json>`
- Go to the project directory, run `docker-compose --profile cpu-fs up -d`
- Run `curl -X GET http://localhost:1337/v1/models`
- Returns an empty array

Then, run:

- `docker exec -it <containerId> /bin/bash`
- `ls /app/models`

And you see all the models are there.

**Expected behavior**
The models should be there

**Additional context**
Perhaps the model needs to be loaded first?

The Electron app fires `runModel` which calls the inference server on port 3928 (minio) to run the model.  However, there doesn't appear to be a way to tell the local server to do this.

This would defeat the purpose of the `docker-compose` to require the Electron app in order to load the model first.  Any ideas on what to do?

**Comment by HyperCrowd** [comment]
It looks like there are API commands to stop and start models, however, my models are still empty

![Screenshot from 2024-02-22 14-58-00](https://github.com/janhq/jan/assets/76200774/1792c8db-1acb-40b2-9228-b83a01031d6b)

**Comment by HyperCrowd** [comment]
Walking through this code to figure out why `GET /models` returns an empty array.  I'll add console.debugs everywhere and post the result



![Screenshot from 2024-02-22 15-06-01](https://github.com/janhq/jan/assets/76200774/34a2a396-e6fc-4821-a0a7-514f32500ffc)

**Comment by HyperCrowd** [comment]
Never mind, I cannot even get to that function.  I get booted at `getBuilder`:

![Screenshot from 2024-02-22 15-24-44](https://github.com/janhq/jan/assets/76200774/9019ccd4-c2bb-4a1f-b11d-d069d47f9817)

The output of that `console.debug` is the following:

![Screenshot from 2024-02-22 15-24-57](https://github.com/janhq/jan/assets/76200774/39f09f11-afd6-4ee5-8ff5-feed4befef87)

When I `docker exec -it <containerId> /bin/bash` into the instance and run the following command, the `models` folder is not there:

![Screenshot from 2024-02-22 15-27-52](https://github.com/janhq/jan/assets/76200774/1a4f2dcd-d024-4eea-972e-4084527f8759)

Before I ran the docker, I created a symlink in `jan/server/build/models` to point to `jan/models`, yet, it appears they did not copy

![Screenshot from 2024-02-22 15-28-22](https://github.com/janhq/jan/assets/76200774/fba3a638-9914-4c8b-8b8d-c7934aae9195)

**Comment by HyperCrowd** [comment]
I can finally start the Mistral model with the following command:

`curl -X PUT 'http://localhost:1337/v1/models/mistral-ins-7b-q4/start' -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{}'`

Output: `{"message":"Model mistral-ins-7b-q4 started"}`

In summary, to fix this problem at the developer level:

* Add a symlink in `/app/server/build/jan` called models and point it to `/app/models` during the Docker build process (`Dockerfile` and `Dockerfile.gpu`)
* Update Swagger YAMLs and documentation to expose the `PUT /model/:model_id/start' and `PUT /model/:model_id/stop' commands
* Update Getting Started documentation to point out that the models have to be started when in Local Server mode

**Comment by HyperCrowd** [comment]
I'll provide updates on how to bake this solution into the Dockerfiles at some point in the close future

And probably pack that into a Pr

**Comment by louis-jan** [comment]
Could you confirm if you want to modify the container's 'models' folder from the host machine? If so, I think you should consider using a Docker Mount Volume. 

The data within the container should be sandboxed after it is deployed.

**Comment by HyperCrowd** [comment]
> Could you confirm if you want to modify the container's 'models' folder from the host machine? If so, I think you should consider using a Docker Mount Volume.
> 
> The data within the container should be sandboxed after it is deployed.

I'll check to see if VOLUMES works with and without the symlink

**Comment by louis-jan** [comment]
Please let us know if this works, @HyperCrowd. We will close it as not planned for now. Please feel free to reopen it.
