### ISSUE TITLE
Discussion: version 0.4.4 is much faster than 0.4.5+ on my laptop

### ISSUE THREAD

**Issue by gilyovdmitrij** [janhq/jan#2132]
When switching from version 0.4.4 to version 0.4.5, something changed inside Jan. And on a low-power laptop with AMD Ryzen 3 4300U and 20 GB of RAM (Windows), it became impossible to use it. Responses are generated unacceptably slowly or there are model crashes. Rolling back to version 0.4.4 returns the speed to normal, responses are output at a speed approximately equal to or slightly higher than the speed of human typing (on models with a size of 4.07 - 5.92 GB).

If possible, I would like the changes that led to a drop in performance in this case to be localized and become optional.

Thank you for the great program. With respect.

**Comment by Van-QA** [comment]
hi @gilyovdmitrij, we resolved this issue recently at https://github.com/janhq/jan/issues/1823, can you try our latest nightly build?

**Comment by gilyovdmitrij** [comment]
Oh, thank you! Of course I will do it.

**Comment by gilyovdmitrij** [comment]
Unfortunately. The models I use failed to start on version 0.4.6-285. However, I noticed that this version is less demanding on RAM. Probably, in my case, it's not about the amount of RAM.

Is there anything else I can do?

**Comment by Van-QA** [comment]
hi @gilyovdmitrij, can you give us the app.log? 
Also please share with us:
* Your OS version
* Your spec: CPU serial, memory (you can find this info in the troubleshooting assistant tab)
* Jan app version

**Comment by gilyovdmitrij** [comment]
Thanks for the instructions. 

So, I am sending:
ap-0.4.4.log - log version 0.4.4;
app-0.4.6-285.log - log version 0.4.6-285;
app-0.4.6-285- and.log - log version 0.4.6-285 after deleting and reloading the model.

My OS version is: 22H2 build 19045.4046.

Device name LE-LTPC
AMD Ryzen 3 4300U processor with Radeon Graphics 2.70 GHz
RAM 20.0 GB (available: 17.9 GB)
System type 64-bit operating system, x64 processor

My specs are in the file: "My specs.txt"

[app-0.4.4.log](https://github.com/janhq/jan/files/14383836/app-0.4.4.log)
[app-0.4.6-285.log](https://github.com/janhq/jan/files/14383837/app-0.4.6-285.log)
[app-0.4.6-285-ard.log](https://github.com/janhq/jan/files/14383838/app-0.4.6-285-ard.log)
[My specs.txt](https://github.com/janhq/jan/files/14383839/My.specs.txt)
.

I'm glad to help you.

**Comment by Van-QA** [comment]
hi @gilyovdmitrij, since you are on AMD GPU, can you try turning on the Vulkan support in the settings? 
<img width="1268" alt="image" src="https://github.com/janhq/jan/assets/64197333/50aaeb87-1fbc-47c7-8a9a-97b6c5c1d414">

**Comment by gilyovdmitrij** [comment]
Thank you!

With the settings you specified, the model started in version 0.4.6-285 and I received an answer, in my opinion, as quickly as from version 0.4.4.

In case it is necessary, sending you app-0.4.6-ans.log.

[app-0.4.6-285-ans.log](https://github.com/janhq/jan/files/14384054/app-0.4.6-285-ans.log)

I wish you good luck in the development of the project. This and any others. <3
