### ISSUE TITLE
Add GPT4/Gemini model offline

### ISSUE THREAD

**Issue by kacperpaczos** [janhq/jan#2140]
up

**Comment by Heart-eartH** [comment]
wait for Gemini too

**Comment by tikikun** [comment]
We're trying to fix some failed vulkan pipeline, will soon be inside nightly version

**Comment by tikikun** [comment]
This can be closed when vulkan issue resolved @louis-jan

**Comment by louis-jan** [comment]
> This can be closed when vulkan issue resolved [@louis-jan](https://github.com/louis-jan)

There seems to be a misunderstanding here, as this is not a valid feature requerst
