### ISSUE TITLE
bug: Cannot access Nitro on port 3928 in Docker from Host

### ISSUE THREAD

**Issue by HyperCrowd** [janhq/jan#2142]
**Describe the bug**
I should be able to curl `http://localhost:3928/v1/embeddings` from the host, but it isn't possible because nitro binds to port 127.0.0.1

* [Nitro opinion](https://github.com/janhq/nitro/pull/56/files#diff-587cb980af76fdc7e52369fd0b9d926dff266976b6f8ac631e358fecc49ff8cfR4)
* [Jan opinion](https://github.com/janhq/jan/blob/563f37f8848e6b3ea47c1d7dad95a76ef5a99be5/core/src/node/api/restful/helper/consts.ts#L5)

**Steps to reproduce**
1. Run docker-compose up
1. Start a model with a call to `curl -X PUT http://localhost:1337/v1/models/<model>/start -H 'Accept: application/json' -H 'Content-Type: application/json' -d '{}'`
1. Try to this command: `curl http://localhost:3928/v1/embeddings -H 'Content-Type: application/json' -d { "input": "why hardcode the host like this?", "encoding_format": "float" }`

**Expected behavior**
I expect embeddings

**Additional context**
If you `docker exec -it` into the docker and run the following:

```
apt-get update
apt-get install lsof
lsof -Pi4 | grep 3928
```

You'll see nitro keep binding to `localhost`, not `0.0.0.0`

**Comment by HyperCrowd** [comment]
If we change the [line here]() from:

```nodejs
export const LOCAL_HOST = '127.0.0.1'
```

to:

```nodejs
export const LOCAL_HOST = process.env.NITRO_HOST || '127.0.0.1'
```

Then we can have the flexibility needed to account for Docker setups by setting `NITRO_HOST` in the environments block of `docker-compose.yml` to `0.0.0.0`

**Comment by tikikun** [comment]
Nito is an embedded process and not supposed to be exposed to external process due to security concern, i would suggest you just use janAPI server directly on Jan UI
