### ISSUE TITLE
feat: Auto startup server mode

### ISSUE THREAD

**Issue by one0410** [janhq/jan#2146]
When I start JAN, server mode is off every time. Are there any options that I can start API server when I start JAN ?

**Comment by tikikun** [comment]
Or should we have headless jan or jan cli?

**Comment by darkmoonsk** [comment]
Jan cli would be great!

**Comment by Van-QA** [comment]
hi @one0410, can you try this: https://github.com/janhq/jan/issues/2200 and attempts to run the server without the Jan app?

**Comment by 0xSage** [comment]
Done(ish) see https://github.com/janhq/cortex
