### ISSUE TITLE
Serious bugs, disk filled with log files

### ISSUE THREAD

**Issue by msjsc001** [janhq/jan#2148]
Serious bugs, disk filled with log files

I'm using "win11 23H2".
The version of JAN is 0.4.6.
The model used on JAN is "OpenHermes Neural 7B Q4".
I'm using Chinese.

![image](https://github.com/janhq/jan/assets/93178788/85b6a3c9-f8c5-4240-9af1-d6fe0dc14088)
I checked with WizTree and found that the disk where JAN is installed is filled with JAN log files.

**Comment by Van-QA** [comment]
hi @msjsc001, the issue was resolved as of 0.4.7, can you try our latest build? 🙏 many thanks
