### ISSUE TITLE
bug: Unable to create a new thread

### ISSUE THREAD

**Issue by axcornea** [janhq/jan#2157]
**Describe the bug**
After the latest update to v0.4.7, the "Create new thread" button no longer works. No explicit/implicit errors were presented.

**Steps to reproduce**
1. Open the application.
2. Click the "Create new thread" button in the top bar.

**Expected behavior**
A new thread is created, and you get switched into it.

**Screenshots**
![ezgif-6-9227f9ef18](https://github.com/janhq/jan/assets/11795668/475b0596-b580-4abf-96db-57ffb301444d)

**Environment details**
- Operating System: MacOS Sonoma 14.2.1 (23C71)
- Jan Version: v0.4.7
- Processor: Apple M2 Max
- RAM: 32GB

**Logs**
```
# tail -n 50 ~/jan/logs/app.log
2024-02-26T07:04:21.679Z [APP]::Version: 0.4.72024-02-26T07:04:24.868Z [NITRO]::Debug: Request to kill Nitro
2024-02-26T07:04:24.908Z [NITRO]::Debug: Nitro process is terminated
2024-02-26T07:04:29.148Z [APP]::Version: 0.4.7
```

**Additional context**
Works on v0.4.6.

**Comment by Van-QA** [comment]
hi @axcornea, we are blocking multiple creations of blank threads, only 1 empty thread at a time.
You can see that there is 1 thread in the UI, feel free to send a message / modify that thread, and you will be able to create another empty one. 
https://github.com/janhq/jan/issues/1887

**Comment by axcornea** [comment]
@Van-QA, thank you. For some reason, that didn't work immediately after upgrading to v0.4.7, and I was completely unable to create a new one through the application. Now can confirm that it works as expected if there are no other empty threads.
