### ISSUE TITLE
bug: styling code in prompt is rendered in the UI of JanAI

### ISSUE THREAD

**Issue by nelscon538** [janhq/jan#2162]
when pasting styling code in my prompt and press enter, the whole UI of JanAI is altered.

![image](https://github.com/janhq/jan/assets/94167157/e736b47f-40e1-4e8f-900f-bd9425a08ef9)

**Comment by urmauur** [comment]
@nelscon538 can you give me an example pasting styling code in my prompt and broke the layout ?

**Comment by Van-QA** [comment]
hi @urmauur, here is the text provided from users, thank you https://discord.com/channels/1107178041848909847/1211696563659866132/1211961737994047498
