### ISSUE TITLE
epic: Better Nvidia GPU Experience

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2165]
### Motivation

- Inference works on CPU, crashes when GPU is turned on
- Turned out I didn't install one of the Nvidia dependencies

### Takeaways

- Need better error messages (i.e. you haven't installed Cuda Tools,  if crash due to missing Nvidia Driver, ...)
- Turning on Advanced GPU mode should auto-test for these factors

### Specs
- The issue currently output as code: 3221225781 
- Notion specs
https://www.notion.so/jan-ai/Better-Nvidia-GPU-Onboarding-Experience-b04bc3109c2846d58572415125e0a9a5

### Tasks
- [ ] #2565
- [x] https://github.com/janhq/jan/issues/2610
- [x] #2616
- [x] https://github.com/janhq/jan/issues/2619

**Comment by 0xSage** [comment]
issue too vague, tracking in other more detailed issues
