### ISSUE TITLE
Chore: docs.jan.ai is the new jan.ai

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#219]
Success criteria: 
- Set Docusaurus site as the home page
- It has url `jan.ai`
- That's it - thanks!

**Comment by hiento09** [comment]
https://github.com/janhq/jan/pull/220

**Comment by 0xSage** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing 1](https://trello.com/c/UFEAwPJ7/1-testing-1)
