### ISSUE TITLE
Need a function to send pictures

### ISSUE THREAD

**Issue by msjsc001** [janhq/jan#2191]
![image](https://github.com/janhq/jan/assets/93178788/192cb651-2e12-487a-ba7a-4f70c730ea5f)

This is a model that recognizes images, but there is no place in the chat window to send them.

**Comment by Van-QA** [comment]
This feature request is related to the epic #294. Hence, closing this as duplicated.
Thank you and please stay tuned for the Jan can See epic that dev team is working on.
