### ISSUE TITLE
bug: Chatting will get stuck at the 20th entry and will not continue.

### ISSUE THREAD

**Issue by msjsc001** [janhq/jan#2193]
My software version and system version Jan v0.4.7 , win11
Using the model Openchat-3.5 7B Q4 (default settings) chatting every 20th message will be stuck and can not continue, when stuck, the CPU is still occupied but the GPU is not occupied, after about 5 minutes of stuck, it will automatically exit the software, after restarting the software, still have the same problem chatting can not be continued, open the software after nothing to operate immediately automatically exit. The only way to recover is to open a new chat window.
I used Markdown unordered list for the role prompt words as follows (I'm not sure if it's the prompt words or not):
```
- How do I answer the question?
	- How to answer the question? You will play 2 roles to answer the question.
	- How to answer the question? You will play 2 roles to answer the question.
	- Role 1, Role 2 Answer with "🚀" in front of the character's name and a separate paragraph for each character.
	- Role 1 and Role 2 will not talk to each other
	- Role 2 will proofread Role 1's answers
	- Role 1 and Role 2 will simply say no to questions they don't know, without making up answers.
- Role 1
	- Main job is to answer questions
	- Can use emoji to express emotions and will use emoticons for every answer
	- Have emotions of joy, anger, sadness and happiness
- Role 2
	- Role 2's main job is to check and proofread role 1's answers.
	- Checks and proofreads only after character 1 has finished speaking. If there is a mistake in character 1's answer, he will be prompted to add it later.
	- Only the content is checked and proofread, and if there are no redundant words, no additions are made.
```

This problem is especially easy to reproduce when the AI is told to interpret the program code, which can easily happen when the replies become more voluminous.

**Comment by Van-QA** [comment]
hi @msjsc001, can you give us the app.log and your device specs?

**Comment by msjsc001** [comment]
> hi @msjsc001, can you give us the app.log and your device specs? if possible, please give us the thread as well, thank you

@Van-QA 
 I am using WIN11 23H2 22631.3155 , JAN v0.4.7 
The log file has been uploaded
[app.log](https://github.com/janhq/jan/files/14448436/app.log)

**Comment by louis-jan** [comment]
Sounds like a context size issue, @hahuyhoang411?

**Comment by louis-jan** [comment]
Could you please help share the CPU, GPU, and RAM? If the device meets the requirements, you can increase the context length, provided the model supports it.

**Comment by msjsc001** [comment]
> 能否请您分享一下 CPU、GPU 和 RAM？如果设备符合要求，您可以增加上下文长度，前提是机型支持。
@louis-jan 
CPU：AMD Ryzen 7 3700X 8-Core Processor
GPU：NVIDIA GeForce RTX 3060 12G
RAN：32GB 3200MHz

**Comment by hahuyhoang411** [comment]
This is the issue related to the context size of the model.
Typically, each model can answer in ~4000 words conversation. If you exceed that limit, the problem will occur.

I created the feature request for this issue https://github.com/janhq/jan/issues/2320
