### ISSUE TITLE
Model stuck on loading (Windows)

### ISSUE THREAD

**Issue by yudhanjaya** [janhq/jan#2201]
Regardless of what modelfile is selected, this is as far as I get.
LMStudio and Ollama run fine. 

Basic specs:

OS Name:                   Microsoft Windows 11 Pro Education
OS Version:                10.0.22631 N/A Build 22631
Processor: Ryzen 5800X3D
GPU: Nvidia RTX 3090
Total Physical Memory:     49,078 MB
Available Physical Memory: 38,263 MB
Virtual Memory: Max Size:  55,078 MB

Steps to replicate: download any model and attempt to chat with it on default settings. 

![image](https://github.com/janhq/jan/assets/16394240/3c4e125c-9363-4165-8a9a-c06b61a65db8)

**Comment by Van-QA** [comment]
hi @yudhanjaya, can you give us:
* Your app.log
* Your setting.json

**Comment by kwantyk** [comment]
hi, same think for me with mistral. 

![image](https://github.com/janhq/jan/assets/1736340/59a3fcdc-e08e-44f0-a430-8b73d50d8f1a)

[app.log](https://github.com/janhq/jan/files/14473091/app.log)
[settings.json](https://github.com/janhq/jan/files/14473092/settings.json)

**Comment by kwantyk** [comment]
and i have this error in JS console : 
index.js:47 Uncaught (in promise) Error: Error invoking remote method 'invokeExtensionFunc': Error: Command failed: WMIC CPU Get NumberOfCores

**Comment by kwantyk** [comment]
Ok i find the probleme. You have to add wmic path in the Environment Variables. add C:\Windows\System32\Wbem in the path for me

**Comment by 0xSage** [comment]
@Van-QA any follow ups on this?

**Comment by Van-QA** [comment]
hi @0xSage, we are still waiting for the app.log from users, I asked him in the previous comment

> @Van-QA any follow ups on this?



> hi @yudhanjaya, can you give us:
> 
> * Your app.log
> * Your setting.json

**Comment by yudhanjaya** [comment]
@Van-QA sure thing. 
[app.log](https://github.com/janhq/jan/files/
[settings.json](https://github.com/janhq/jan/files/14504353/settings.json)
14504350/app.log)

**Comment by Van-QA** [comment]
> @Van-QA sure thing. [app.log](https://github.com/janhq/jan/files/14504350/app.log) [settings.json](https://github.com/janhq/jan/files/14504353/settings.json)

hi @yudhanjaya, can you try this guideline? it's worked for the users in the previous comment 🙏 

> Solution
> ​To resolve this issue, do the following:
> 
> Open Command Prompt in the machine, where nodeagent has to be started.
> Run the following command for adding folder containing wmic to PATH environment variable:
> SET PATH=C:\Windows\System32\wbem\;%PATH%;
> After setting the path variable using the command above, run the following command to confirm whether wmic is picked properly:
> where wmic
> 
> The command above should return the following as output: 
> "C:\Windows\System32\wbem\WMIC.exe"
> After confirming, navigate to the nodeagent folder, without closing the Command Prompt session.

https://knowledge.informatica.com/s/article/156865?language=en_US

**Comment by yudhanjaya** [comment]
@Van-QA done: 
C:\Users\Yudhanjaya>where wmic now returns
C:\Windows\System32\wbem\WMIC.exe

However, nothing's changed; the model still does not load, and looking at task manager shows me nothing meaningful happening in GPU or RAM.

**Comment by Van-QA** [comment]
> @Van-QA done: `C:\Users\Yudhanjaya>where wmic `now returns `C:\Windows\System32\wbem\WMIC.exe`
> 
> However, nothing's changed; the model still does not load, and looking at task manager shows me nothing meaningful happening in GPU or RAM.

Can you try restarting the machine, and then `where wmic` again? thank you

**Comment by yudhanjaya** [comment]
> > @Van-QA done: `C:\Users\Yudhanjaya>where wmic `now returns `C:\Windows\System32\wbem\WMIC.exe`
> > However, nothing's changed; the model still does not load, and looking at task manager shows me nothing meaningful happening in GPU or RAM.
> 
> Can you try restarting the machine, and then `where wmic` again? thank you

Interesting. Now I get:
`INFO: Could not find files for the given pattern(s).`
Let me try adding the path in the GUI . . .

**Comment by yudhanjaya** [comment]
Update: it worked!
![image](https://github.com/janhq/jan/assets/16394240/a61e8e5d-2371-4c33-8bff-5761b29cbd85)

**Comment by Van-QA** [comment]
@namchuai please help us to fix the issue where the code related to NumberOfCores does not throw any exception to the app.log / UI + stop the model when missing C:\Windows\System32\Wbem in the system's PATH environment variable.

**Comment by hahuyhoang411** [comment]
I will document this @hieu-jan. Will tag you in later for the review

**Comment by hieu-jan** [comment]
Troubleshoot documentation for this issue is added via #2276

**Comment by Van-QA** [comment]
Dev team implemented the BE fix for the issue ✅ 
Pending on the FE ⚠️ 
cc: @namchuai for following up later

**Comment by louis-jan** [comment]
We will likely deprecate the warning when a user's PC is missing environment settings. Instead, we will depend on the node `os.cpus` and allow users to adjust in the GUI, as discussed in <https://github.com/janhq/jan/issues/1716>
- We allocate 70-80% of resources by default. (Don't worry about resource hogging)
- Users can adjust ± on the GUI.

@Van-QA @namchuai
