### ISSUE TITLE
bug: Constant loop and strange response behavior of Mistral Instruct 7B Q4

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2204]
Quoted from users: https://discord.com/channels/1107178041848909847/1212550130209660999
> Windows 11,
>  AMD Ryzen 5 3600 (idk how to find the serial number), 
> 32gb of RAM 3200MHz, 
> GPU: GTX 1660 Super
> 
> Jan v0.4.7 (I first encountered the issue on yesterdays nightly release with Mistral Instruct 7B Q4, then I encountered it again with Openchat-3.5 7B Q4 after downloading the latest version on the website, each time I went into my files and deleted everything associated with Jan, so a fresh install for each.)
> 
> The first thread that gave me issues on Mistral Instruct in the nightly release version; the Instructions were "You are a writing assistant helping me with creative tasks" I had it come up with writing prompts, which I would rank, and then have it combine prompts to write 500 word short stories which I would also grade. After 5 rounds of this it got into a loop of grading itself starting with "GPT4 Correct User" before writing as me, and then answering itself with revisions on its short stories. I had done the same test previously with Openchat, which as a side note, writes much better stories with fewer instructions.
> 
> The second Thread to give me issues had the instructions; "You are a political philosopher taught by John Locke, and Thomas Sowell" I then had it provide arguments for and against various political systems, to see if it would take on the bias of the people in its instructions or if it would continue to try to remain neutral with the "As an AI I have no opinion". I wanted to see if I could give it opinions. After giving responses as each of those 2 individuals; it started to ask me questions and then after I answered twice it started responding to itself with "GPT4 Correct User" again but instead giving itself compliments as me, saying stuff like "You've been a great assistant! I appreciate the thoughtful answers" but it didn't end up in a constant loop like the first time I had the issue. It basically went on a brief loop of complimenting itself as me, and then thanking me for the compliment twice.
> Both of those threads have been deleted, the second one went from a token speed of 9t/s to 0.6 t/s which was just too slow to continue. If I get the issue again I'll keep the thread open

**Comment by hahuyhoang411** [comment]
The response behavior could be related to model's performance. Ask user to modify his/her prompt for more suitable prompt.

About the speed of the model, ask his/her to use GPU (also with 1660 Super (6 GB Vram), the ctx_len should be smaller than 2048).
