### ISSUE TITLE
feat: Support for v1/completions endpoint in OpenAI-compatible server

### ISSUE THREAD

**Issue by sestinj** [janhq/jan#2206]
**Problem**
Continue.dev users are increasingly turning to Jan as their goto method of running a language model. Unfortunately, they can't use it for tab-autocomplete because this requires raw, non-chat-formatted requests. This is only possible through the v1/completions endpoint, which Jan doesn't seem to support.

**Success Criteria**
Jan's OpenAI server adheres to the OpenAI spec for v1/completions. Then users can rely on Jan for local tab-autocomplete : )

**Additional context**

**Comment by clement-igonet** [comment]
I fully agree.

Also, `/v1/completions` is officialy declared as deprecated by the openai API doc, but still supported, and used by many clients of the openai API.

**Comment by clement-igonet** [comment]
Any news to support /v1/completions ?

**Comment by controldev** [comment]
Agreed, many third party applications rely on the completions endpoint. This is a huge blocker.

**Comment by 0xSage** [comment]
Deepest apologies, we will be forward compatible only.
