### ISSUE TITLE
feat: Preserve custom settings and instructions after the update

### ISSUE THREAD

**Issue by takeerdevs** [janhq/jan#2210]
**Problem**
I do have a custom instruction that i set in instructions field and other settings in Jan, unfortunately when the update is applied, all settings are reset to default even instructions are deleted which is a bit annoying to remember how well crafted instruction was so i can retype it again.

**Success Criteria**
Would be better if any update doesn't change settings or if there is a need to change settings in the update let user know so that a user can make a backup of settings + instructions before proceeding with the update.

Thanks :)

**Comment by 0xSage** [comment]
@takeerdevs in the meantime you can still retrieve your instructions: 
1. https://jan.ai/guides/thread/
2. Open up the last thread.json
3. You'll find the old instructions in there :)

**Comment by imtuyethan** [comment]
This will be resolved after Jan x Cortex. We have this scheduled in the next 2-4 weeks. I'll mark this one as duplicated.
