### ISSUE TITLE
feat: Groq API Integration

### ISSUE THREAD

**Issue by metaspartan** [janhq/jan#2227]
- Add GroqCloud Remote API to Jan

https://groq.com

**Success Criteria**
- Add support for Groq models via their Groqcloud API (user can provide key), similar to current OpenAI GPT integration

**Comment by Van-QA** [comment]
I'm not sure if we should allow Groq to support RAG
![image](https://github.com/janhq/jan/assets/64197333/2e050d88-8b6c-4ac2-a08b-3166ddad5e3c)
cc: @louis-jan

**Comment by Van-QA** [comment]
Tested on Jan v0.4.9-344 ✅ 
![image](https://github.com/janhq/jan/assets/64197333/956632ce-dc14-44b7-91fe-1550845a6ad9)

**Comment by iamhenry** [comment]
> I'm not sure if we should allow Groq to support RAG ![image](https://private-user-images.githubusercontent.com/64197333/316771681-2e050d88-8b6c-4ac2-a08b-3166ddad5e3c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNDcxNjMsIm5iZiI6MTcxNDI0Njg2MywicGF0aCI6Ii82NDE5NzMzMy8zMTY3NzE2ODEtMmUwNTBkODgtOGI2Yy00YWMyLWEwOGItMzE2NmRkYWQ1ZTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDE5NDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NjY4Y2M1ZjY0M2YzZWZhNzk4YjUzZTQ4Y2NmMTdhZjNmZjJhMTgyYjFiNDVkYmY4MzE0NTVjMTZhMzlmOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fm_TQCtkGDNf-e1SDiDSac6N3GJOvvQwMP03pSFgRYs) cc: @louis-jan

@Van-QA why wouldnt you want to support rag support for groq? 

i personally would love this feature since groq is extremely fast

**Comment by Van-QA** [comment]
Hi @iamhenry, thank you for the question, as you can see from my screenshot, at first with RAG, it's seem that the model does response, but moving closer to the answer, the model does not recognize the uploaded document.
Atm, RAG x Remote model like Groq is not supported yet, so enabling the settings from Jan app can be confusing 🙏

**Comment by iamhenry** [comment]
thank you for clarifying
