### ISSUE TITLE
bug: clean threads should also delete thread's files and memories

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2232]
**Describe the bug**
After cleaning the thread, I still get old context's messages due to ingested documents

**Steps to reproduce**
1. Ingest pdfs
3. Click on Clean Thread
4. Send new messages
5. See error

**Expected behavior**
Should have a clean thread to start over

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
Looking good on ✅
