### ISSUE TITLE
fix: "Jan cannot be opened because Apple cannot check it for malicious software"

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#224]
To Repro: 
- install for the first time
- open app
- get notification
- users have to open finder, right click open, ignore warning, to use the app

**Comment by dan-jan** [comment]
Also experienced: 
![image](https://github.com/janhq/jan/assets/101145494/4f404639-02f8-42b9-a46b-c555ce1c7e7c)

**Comment by louis-jan** [comment]
Finished. Our app is notarized cc @hiento09

**Comment by 0xSage** [comment]
fixed! thank you @hiento09 @louis-jan
