### ISSUE TITLE
feat: Create a popup to prompt manually download the latest build for users on older versions, only when auto update failed.

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2241]
## Motivation
To assist users on older versions when `the auto update to a higher build fails`, we need to provide a popup functionality that prompts manual download.

## Specs
- Implement a popup feature that prompts manual download only when newer build(s) is available and the auto update is failed. (Focusing on the case of failure caused by certification migration)
- The `manual download pop up` will be applied in 0.4.8. Users will be prompted to automatically update to version 0.4.8 (as usual) along with the `manual download pop up` feature.
- When 0.4.9 is published, the `manual download pop up` popup should appear to ask users to manually download version 0.4.9 (due to the migration of certificates is in 0.4.9 and the auto update will fail).
- In the future, if users encounter any update failures, the `manual download pop up` should suggest that users manually download as the auto update has failed.

## Designs
[Figma](https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App-(version-1)?type=design&node-id=5106-149979&mode=design&t=4mIuDwDuXsAWOCFV-4)

## Tasklist
- [ ] Implement popup feature for manual download prompt, only when a new build is available and the auto update is failed.
- [ ] Certification migration between 0.4.8 and 0.4.9
- [ ] CI update (if any)

## Not in Scope
- Detailed error handling for various update failure scenarios.
- UI redesign beyond the implementation of the popup feature.

## Appendix
**Description**
As the auto-update feature is currently broken for users with versions older than Jan v0.4.7-294, we need to implement a popup that asks these users to manually download the latest build. This will ensure that all users are on an updated version and reduce the number of support requests related to this issue.

**Success Criteria**
Users with older versions than Jan v0.4.7-294 receive a clear popup message when opening the application, prompting them to manually download the latest build.
Users successfully download and update to the latest build after seeing the popup.
The number of support requests related to this issue decreases.

**Additional Context**
https://discord.com/channels/1107178041848909847/1214051677527867422

**Comment by Van-QA** [comment]
hi @imtuyethan, we will need a copy for the pop message 🙏

**Comment by imtuyethan** [comment]
**Design**
Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App-(version-1)?type=design&node-id=5106-149979&mode=design&t=4mIuDwDuXsAWOCFV-4

<img width="909" alt="Screenshot 2024-03-05 at 6 21 01 PM" src="https://github.com/janhq/jan/assets/89722390/359bc54c-adc2-494c-ac32-393f81386788">

**Comment by louis-jan** [comment]
@imtuyethan Since we aligned to have this error handling as a feature rather than a hotfix to ensure further app updates. This should be an error message informing the user that the automatic installation process has failed, and requesting that they manually download the installation files. Such as 

```
Unable To Install Update

An error occurred while installing Jan x.x.x. Please help me download and install the update manually.
```

**Comment by louis-jan** [comment]
Aligned copy:

<img width="1312" alt="Screenshot 2024-03-06 at 23 57 01" src="https://github.com/janhq/jan/assets/133622055/784eaac2-765a-490e-be44-9ea69a3057f7">

**Comment by Van-QA** [comment]
> Aligned copy:
> 
> <img alt="Screenshot 2024-03-06 at 23 57 01" width="1312" src="https://private-user-images.githubusercontent.com/133622055/310586751-784eaac2-765a-490e-be44-9ea69a3057f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDUxNzksIm5iZiI6MTcwOTc0NDg3OSwicGF0aCI6Ii8xMzM2MjIwNTUvMzEwNTg2NzUxLTc4NGVhYWMyLTc2NWEtNDkwZS1iZTQ0LTllYTY5YTMwNTdmNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNlQxNzA3NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDkxZjkyMmZkOWVmMDI3MmFlNzUzMGY4NjUzMzdlNTNlMDAyZDYzNTBmOGJkZTE3MDVhZDZmNTYwNzgwZWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M4kU7o8Oo80oka_vq4Jg6MnBqy_Yt6AUOx84lm1ElRA">

The aligned copy is correct 🙏 however, please help me correct the `Download Now` to `Download now`, many thanks

**Comment by Van-QA** [comment]
Tested and looking good on Jan 0.4.7-304 ✅
