### ISSUE TITLE
bug: Nightly 297 doesn't load any model on macOS

### ISSUE THREAD

**Issue by vlbosch** [janhq/jan#2244]
**Describe the bug**
Try to load any model. Model cannot be loaded manually and won't start after creating a thread with the model.

**Steps to reproduce**
1. Open Jan
2. Create a thread
3. Select model
4. Provide a prompt
5. Watch the "Something's amiss" appear instantly

**Expected behavior**
The model is loaded and can be interacted with.

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: macOS Sonoma 14.4 RC
- Jan Version: 0.4.7-297
- Processor: M3 Max 16c-40c
- RAM: 128GB
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
See: 
[jan297.log](https://github.com/janhq/jan/files/14493387/jan297.log)

**Additional context**
Before some models where loaded, but couldn't be interacted with after (appearing to) being loaded correctly. See issue #2094 But now the models do not even load. None of the previously working models. Redownloading or importing again doesn't work either.

**Comment by Van-QA** [comment]
hi @vlbosch, sorry for the inconvenience, the issue will be resolved if you download the correct version of Jan nighly manually, can you try that? 🙏

**Comment by vlbosch** [comment]
> hi @vlbosch, sorry for the inconvenience, the issue will be resolved if you download yours OS version of Jan nightly manually and try again, can you try that? 🙏

This has indeed resolved the issue, thanks for the quick reply!
