### ISSUE TITLE
feat: Anthropic Claude API Request

### ISSUE THREAD

**Issue by carnivar10** [janhq/jan#2249]
**Problem**
Claude 3, released by Anthropic, is very good, comparable to GPT4. It would be nice to be able to call their API through Jan.ai.

**Success Criteria**
Jan.ai should be able to chat with Claude by calling the Claude API (API documentation: https://docs.anthropic.com/claude/docs/intro-to-claude)

**Additional context**
Anthropic currently prohibits individuals from using the API, but it's easy to use when you make any organization (https://support.anthropic.com/en/articles/8114521-how-can-i-access-the-claude-api)

**Comment by imtuyethan** [comment]
Thank you for your suggestion. We're refactoring Inference Engine Architecture & will keep Anthropic as an add-on feature for this epic: https://www.notion.so/jan-ai/Refactor-Inference-Engine-Architecture-d54448ad5ce34cb2845d986870b9395e?pvs=4
I'm gonna close this ticket & create new one when assigning tasks to devs. Thank you for using Jan!

**Comment by dandv** [comment]
@imtuyethan That Notion page is no longer up. What is the status of this feature? Can we use Github to track progress please?

**Comment by nickdavis** [comment]
Just downloaded Jan.ai and just got wanted to give a +1 here for Anthropic support via API. I think Chatbot UI has this, would be great to get in Jan too, thanks!

**Comment by apasila** [comment]
@nickdavis how did you get it to work?

**Comment by myrtleTree33** [comment]
I want to try Opus 3.5 which is better than GPT 4o on most benchmarks (again, according to Anthropic).

I see docs has it, but not on the actual release: https://jan.ai/docs/remote-models/anthropic#how-to-integrate-anthropic-with-jan

Please support.
