### ISSUE TITLE
bug: pin the docs nav at the top

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2252]
**Describe the bug**
Docs Nav disappears when users click on subpages

**Steps to reproduce**
1. Go to '/guides'
2. Click on any page that is not the top page
3. See the Docs Nav disappear. 
4. Expected: Docs Nav stays pinned.

**Comment by aindrajaya** [comment]
Ok, I will fix it today. Thanks, @0xSage, for checking that.

**Comment by 0xSage** [comment]
> Ok, I will fix it today. Thanks, @0xSage, for checking that.

Sure thanks! Also `Guide` should say `Guides`
![image](https://github.com/janhq/jan/assets/69952136/caca60ed-e7be-47b2-a3db-e2d54cad3c38)

**Comment by 0xSage** [comment]
Also the `docs` dropdown is now in consistent with the Docs Nav.
![image](https://github.com/janhq/jan/assets/69952136/36c26364-3301-415a-96f3-bd7a06bd6028)

**Comment by 0xSage** [comment]
Please also remove Changelog from /guides now that it has its own section
![image](https://github.com/janhq/jan/assets/69952136/e309dde3-3a9f-4718-972b-22a7d1a809f7)
