### ISSUE TITLE
feat: Jan Quick Ask can be accessed via the OS quick menu 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2256]
Apart from the hotkey, Jan Quick Ask should be easily accessed in the OS quick menu.

## Jan in MacOS menu bar:
Figma link: https://www.figma.com/file/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?type=design&node-id=1326-60003&mode=design&t=SLRbEgwa1pZ2Guuz-4

<img width="834" alt="Screenshot 2024-03-06 at 11 09 50 AM" src="https://github.com/janhq/jan/assets/89722390/2e68e912-60f0-40cf-9e45-c8f22e6ac967">

## Jan in Window system stray
Figma link: https://www.figma.com/file/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?type=design&node-id=1327-64511&mode=design&t=SLRbEgwa1pZ2Guuz-4

<img width="816" alt="Screenshot 2024-03-06 at 11 10 24 AM" src="https://github.com/janhq/jan/assets/89722390/d1027a5d-d0b5-4886-b385-40aac3fe2dac">

**Comment by Van-QA** [comment]
Closing this issue for now with a temporally fix by adding it to exp feat ✅
We will following up on the issue using https://github.com/janhq/jan/issues/2356
