### ISSUE TITLE
feat: Pinning a chat

### ISSUE THREAD

**Issue by gaardhus** [janhq/jan#2262]
**Problem**
I often find my self making new threads when asking small technical questions to reduce the context. However, I also often have a single longer thread which acts more like a master thread for the project I'm working on.

**Success Criteria**
It would be nice if I could be able to pin a thread to the top of the list.

**Additional context**

**Comment by 0xSage** [comment]
It's a good idea, but we likely wont get to this for a long time. Closing unless more user demand. Apologies

**Comment by gaardhus** [comment]
No problem, thanks for your consideration :) I guess searching threads could also help on this and is a higher priority.

**Comment by aldinokemal** [comment]
Hi @0xgokuz can we reopen this ?
I believe this feature is importance for user
