### ISSUE TITLE
Please add ibm/merlinite-7b model

### ISSUE THREAD

**Issue by MrBenzWorld** [janhq/jan#2272]
Please add ibm/merlinite-7b model to ollama. It is very good with logic and code.

https://huggingface.co/ibm/merlinite-7b

**Comment by louis-jan** [comment]
Hi @MrBenzWorld, thank you for such a good recommendation. We will add this model soon; in the meantime, you can try importing the model to the app using the GGUF version. 

https://huggingface.co/ibm/merlinite-7b-GGUF

**Comment by hahuyhoang411** [comment]
Hi @MrBenzWorld , thank you for your suggestion. The model will be added in the upcoming version. Please stay tuned.
