### ISSUE TITLE
Bug: Incorrect model settings after switching between threads with the same selected models.

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2274]
**Describe the bug**
The current load mechanism avoids reloading the same model to save time, but this can lead to an issue where threads have different model settings, not just different model files.
e.g. Context Length

**Steps to reproduce**
1. Create thread A with "tinyllama" and a 1024 context length.
2. Create thread B with "tinyllama" and a 2048 context length.
3. Switch between the threads.
4. The models will act with the settings of the first created thread.

**Expected behavior**
Reload the model if the settings are not the same.

**Additional context**
Should we do it from engine side?

**Comment by bogwero** [comment]
After testing it for a while, I can say this is a preview app, only a scaffolding for now. Most things don't work, as of now I wasn't able to talk to GPT-4, only GPT-3 through selecting the remote OpenAI API settings. Happy coding!

**Comment by Van-QA** [comment]
should be resolved via https://github.com/janhq/cortex/issues/617

**Comment by 0xSage** [comment]
@Van-QA can you check and close if fixed?

**Comment by Van-QA** [comment]
to be verified after Jan x Cortex released
