### ISSUE TITLE
epic: users can use an OpenAI API key

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#228]
**Problem**
- Sometimes you just gotta talk to ChatGPT (often beats smaller models)

**Success Criteria:** 
- Users can go to Settings > OpenAI
- Users can paste in an API key (editable field with a submit button)
- Users get a correct error message if their API key doesn’t work
- Users can start a conversation with ChatGPT
- Users can select GPT 4 or 3.5 to chat with (and see the version)
- Users can chat with OpenAI

**Additional context**

**Comment by louis-jan** [comment]
With #361, user can now install OpenAI as a plugin and apply Settings (Plugin Level)

**Comment by louis-jan** [comment]
Limitation: 
User can't switch between versions yet

**Comment by 0xSage** [comment]
Iced
