### ISSUE TITLE
Add ASR + TTS  & Local Document Processing

### ISSUE THREAD

**Issue by Excurl** [janhq/jan#2284]
There are many successfull GUI out there , Jan seems elegant than others..
* Pls integrate Automatic Speech Recognition via Whisper.cpp so that we can talk (with) LLM
* integrate XttsV2 from Coqui, so that it can speak back...

* 1 Hotkey must be assigned to call Whisper

* Another must thing is custom context, pls add a way to chat with custom documents (hoping it's on Langchain) like pdf, TXT etc..

* it's beutifull if we can export talkbacks as audio file, and texts as documents directly from the window..
*

**Comment by 0xSage** [comment]
Related: https://github.com/janhq/cortex/issues/680
