### ISSUE TITLE
Can't model JSON files be automatically generated after version 0.47?

### ISSUE THREAD

**Issue by acergelff** [janhq/jan#2288]
**Problem**
In previous versions, when manually importing a model, all you needed to do was place the gguf file in the directory to automatically recognize and generate a JSON file. We can directly select it in the JAN software to use the model.
Does the current version not have this feature, can only manually configure JSON files?

**Success Criteria**
Can this function be restored? Or is my operation incorrect?

**Comment by Van-QA** [comment]
hi @acergelff, the function remain unchanged, can you provide more context of the issue?
- Screenshot, the model you are using
- app.log....

**Comment by Van-QA** [comment]
Feel free to reopen this if anyone experiencing similar issue. Thank you 🙏
