### ISSUE TITLE
epic: Explore Models page improvements

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#229]
**Problem**

**Success Criteria**
- Users can see nicely styled model cards (showing perf stats)
- Integrate with HuggingFace API to pull down gguf models
  - Users can paste in HF URL in Explore Models
  - We render the GGUF model cards with relevant stats like quantized performance & compatibility
  - Users can download the model locally
- (Optional - Nice to have only) Users can filter models by categories & labels

**Additional context**
- Designs: https://www.figma.com/file/JdK7cNIBeVdYeHxKiYeWtk/JAN---Web?type=design&node-id=3135-7176&mode=design&t=XscMIMPvG2H8djjN-0

**Comment by namchuai** [comment]
Since we know that HF's API is not sufficient for those criteria and we choose to host own on JSON file for compatible models, I will close this ticket.
