### ISSUE TITLE
bug: [DESCRIPTION]

### ISSUE THREAD

**Issue by Diane0111** [janhq/jan#2298]
**Describe the bug**
Tiny Lama Model doesn't give the correct answer. It keeps generate the same message 

**Steps to reproduce**
1. Go to 'Tiny Lama'
2. Type in something
3. See error

**Expected behavior**
Correct answer from the required command

**Screenshots**
<img width="513" alt="0111" src="https://github.com/janhq/jan/assets/141645593/de758654-8063-4447-a662-31a2a312fb69">

**Environment details**
- Operating System: Mac OS 8gb ram, 256 gb
- Jan Version: [v0.4.8]
- Processor: Apple M1
- RAM: 8GB
- Any additional relevant hardware specifics: 

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by hahuyhoang411** [comment]
This is related to "Tinyllama" performance. You might consider exploring our 'LlamaCorn'. It's comparable in size to 'Tinyllama' but offers better performance.

Alternatively, there's the option to upgrade to a larger model for potentially even better results. However, please be mindful of your hardware's capabilities when making your choice.
