### ISSUE TITLE
bug: Jan Quick ask (system tray instance) blocks app update autorestarts

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2308]
**Describe the bug**
The system tray instance of Jan is blocking the auto restart after an update.

**Steps to reproduce**
1. Trigger an update for Jan.
2. Wait for the update to download and install.
3. Observe that Jan prompts for a restart.
4. Attempt to restart Jan using the provided option.
5. Notice that the system tray instance of Jan prevents the auto restart from completing.

**Expected behavior**
After an update, Jan should automatically restart without interference from the system tray instance.

**Environment details**
- Operating System: Windows 11 / Mac

**Additional context**
The interference from the system tray instance may prevent timely application of updates and pose potential security risks due to outdated software.

**Comment by Van-QA** [comment]
Closing this issue for now with a temporally fix by adding it to exp feat ✅
We will following up on the issue using https://github.com/janhq/jan/issues/2356

**Comment by Van-QA** [comment]
> To repro: 
> Mac m1, v0.4.14-459
> Quit the app, open the app
> Click upgrade
> App quits, and sometimes it just doesn't restart.
> If it does restart, or if I manually reopen the app, it is still on the old version.
>  
> 2/3 times I have to manually download the app binary again 
> 
> The issue is: 
> When quick ask is turned on
> The app never really quits
> So a restart is not possible, users are stuck in a loop.

![image](https://github.com/janhq/jan/assets/64197333/e22c956f-cd49-4634-a8e9-0bd93aca1ed7)

Quoted from Nic :pray:

**Comment by louis-jan** [comment]
Is that still a relevant issue? @Van-QA

**Comment by Van-QA** [comment]
The issue persists and continues to block auto-updates when users have them turned ON. While it may not occur in all cases, it remains unstable.

**Comment by 0xSage** [comment]
What triggers the system tray to stick? Can we reliable repro this issue and fix?

**Comment by 0xSage** [comment]
P2 since not many users actually use quick ask - and we may eventually build it differently

**Comment by imtuyethan** [comment]
Close & follow up on this epic instead: https://github.com/janhq/jan/issues/3944
