### ISSUE TITLE
feat: Populate available models from Ollama

### ISSUE THREAD

**Issue by sammcj** [janhq/jan#2318]
**Problem**

I see Ollama support was added in https://github.com/janhq/jan/issues/1795, however this requires manually editing config files for OpenAI and each model.

It would be great if:

1. You could select Ollama from the list of model providers.
2. The list of available models in Ollama could be automatically populated.

This behaviour is what other tools such as Enchanted, Raycast, AnythingLLM, Mindmac etc... provide and would be great to see in Jan.

**Success Criteria**

- A visual config option to select Ollama as a model provider.
- The list of available models be auto populated when Ollama is selected.

**Additional context**

Example in MindMac:

![image](https://github.com/janhq/jan/assets/862951/8af1934e-30d2-4b8d-a6b9-22823214b07a)

Example in AnythingLLM:

<img width="742" alt="image" src="https://github.com/janhq/jan/assets/862951/06c677d9-2dff-4d35-8fb7-97e400328ea9">

<img width="724" alt="image" src="https://github.com/janhq/jan/assets/862951/d9fb484c-eae8-423d-8764-aa5ec7ae89df">

Example in Enchanted:

<img width="503" alt="image" src="https://github.com/janhq/jan/assets/862951/7efad803-c8a2-48c4-89e1-cf60d6867eea">

<img width="650" alt="image" src="https://github.com/janhq/jan/assets/862951/e97d4e37-bfe0-4ab9-8f32-055eadf69931">

**Comment by imtuyethan** [comment]
Duplicated with https://github.com/janhq/jan/issues/2998

**Comment by davidbuzz** [comment]
/me , as a heavy ollama user, its useless to me with out it, uninstalls 'jan' and deleted the installer file.   lets see if anythingllm can do it.

**Comment by edgimar** [comment]
A fix for this is available in https://github.com/menloresearch/jan/issues/5474#issuecomment-3006694325 -- hopefully the gatekeepers will be willing to merge it!
