### ISSUE TITLE
feat: Implement TensorRT-LLM Extension

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2323]
# Specs
https://www.notion.so/jan-ai/TensorRT-LLM-C-Inference-Extension-for-Jan-Desktop-Server-32b5101c595a49489cfe37680e769dd2?pvs=4

# Design
Figma: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App-(version-1)?type=design&node-id=5178-216651&mode=design&t=Ld1o
<img width="774" alt="Screenshot 2024-03-12 at 12 47 34 PM" src="https://github.com/janhq/jan/assets/89722390/fea55b47-df75-4f45-aa23-76302c5050b2">
ytKp1oD4ElKt-4

**Comment by Van-QA** [comment]
@louis-jan, please help us resolve these issues:
1. The extension still appears in Jan Windows on a PC with no GPU :x: clicking on install doesn't install anything + no toast message / warning to users, nothing happen.
![image](https://github.com/janhq/jan/assets/64197333/981466be-e6cc-4adb-97d8-29fd0536ad44)

2. Install UI on dark mode:
![image](https://github.com/janhq/jan/assets/64197333/62f9ced4-3ee1-429f-972c-e7ca85ab9686)

3. Missing label on the new model:
![image](https://github.com/janhq/jan/assets/64197333/c7848a7a-a1cc-4248-9d9c-83b5194069eb)

4. Unclear error toast title :x: only "Failed"
![image](https://github.com/janhq/jan/assets/64197333/08a9de5e-a503-42be-81c2-b3d836ae3a2c)

**Comment by Van-QA** [comment]
5. Missing recommendation label :x:
![image](https://github.com/janhq/jan/assets/64197333/7400541a-509c-49ef-8f18-6b7b4bcd1875)

**Comment by namchuai** [comment]
issue 5&6 is addressed in the PR https://github.com/janhq/jan/pull/2346

**Comment by Van-QA** [comment]
7. TensorRT model does not functioning with RAG or with Stream off :x: 
![image](https://github.com/janhq/jan/assets/64197333/42c104d0-6da6-48f0-bcbb-ff47be247f2a)

**Comment by Van-QA** [comment]
8. Should not allow users to select the TensorRT model for the local API server :x:
<img width="1187" alt="image" src="https://github.com/janhq/jan/assets/64197333/776216f1-33a5-4f36-979d-731082689bd6">

**Comment by Van-QA** [comment]
Tested and looking good using Jan v0.4.8-333 ✅
