### ISSUE TITLE
bug: Jan data folder - Moving to a not empty destination is not functioning

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2326]
**Describe the bug**
The Jan data folder's functionality for moving to a non-empty destination is not working as expected, specifically on Linux systems.

**Steps to reproduce**
1. Attempt to move the Jan data folder to a destination directory that already contains files or folders.
2. Execute the move operation through Jan's interface or using system commands.
3. Note that the operation does not complete successfully.
4. Check the destination directory to see if the Jan data folder has been moved despite the destination not being empty.

**Expected behavior**
The Jan data folder should be able to be moved to a non-empty destination directory on Linux systems without any issues. The existing files and folders in the destination directory should not interfere with the move operation.

**Environment details**
- Operating System: Linux

**Screenshots**
Not functioning on linux with no error in console
![image](https://github.com/janhq/jan/assets/64197333/53b8b413-877b-4a05-915a-12df76e04891)

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local API server
Making sure to redact any private information.

**Additional context**
This bug specifically affects Linux systems and may disrupt user workflows, particularly when organizing files or migrating Jan's data directory to a new location.

**Comment by louis-jan** [comment]
O.o Will this break the app after?

**Comment by riusricardo** [comment]
Hey @louis-jan , I ran into an issue where the app crashed. When you choose a path that cannot be created or does not exist. It then throws an exception saying it couldn't find or create a directory on the new path. This could be true if you have the new path set to an external HDD, and then unplug it. Jan won't work if the HDD isn't plugged in, and there's no way to open it again.

**Comment by riusricardo** [comment]
> Expected behavior
> The Jan data folder should be able to be moved to a non-empty destination directory on Linux systems without any issues. The existing files and folders in the destination directory should not interfere with the move operation.

It would also be convenient if the app could detect whether the new directory is a valid "Jan" directory that already contains all the required files. Alternatively, it could suggest replacing all existing "Jan" files with the new ones.

**Comment by Van-QA** [comment]
Tested and looking good as of Jan v0.4.9-343 ✅ on both linux and windows
