### ISSUE TITLE
update broke everything (? Version: 0.4.8-312?)

### ISSUE THREAD

**Issue by lineality** [janhq/jan#2334]
**Describe the bug**
using Ubuntu 22.04.4 LTS on del inspiron
updated ? Version: 0.4.8-312
- no jan icon
- no jan application
- blank application box under file menues (see pic)

(new top bar menu item with quick query? neat)

**Steps to reproduce**
1. launch jan
2. see empty box

**Expected behavior**
jan...starts?

**Screenshots**
If applicable, add screenshots to help explain your issue.
![Screenshot from 2024-03-12 08-46-40](https://github.com/janhq/jan/assets/26224792/529fdc29-ba2c-479f-b899-58061c0da39a)

**Environment details**
using Ubuntu 22.04.4 LTS on del inspiron

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.
[app.log](https://github.com/janhq/jan/files/14572404/app.log)

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by lineality** [comment]
[app.log](https://github.com/janhq/jan/files/14573814/app.log)

**Comment by lineality** [comment]
![image](https://github.com/janhq/jan/assets/26224792/89a5b681-0c60-4796-bcb9-9025f5a35f2b)

**Comment by Van-QA** [comment]
hi @lineality, thanks for letting us know, we will fix the issue with the icon soon 🙏 
![image](https://github.com/janhq/jan/assets/64197333/c1f29919-e56e-47a3-8167-3613d31bc334)
As for the broken build, we will soon discard it👍 please continue using the newer build than 0.4.8-313 

Would you mind joining our discord? https://discord.com/invite/FTk2MvZwJH
