### ISSUE TITLE
bug: Model recommendation under thread settings is not based on VRAM when GPU is on

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2339]
**Describe the bug**
The model recommendation feature under thread settings in Jan is not accounting for VRAM (Video Random Access Memory) when GPU acceleration is enabled.

**Steps to reproduce**
1. Enable GPU acceleration in Jan.
2. Navigate to thread settings.
3. Observe the model recommendation provided by Jan.
4. Compare the VRAM usage of the recommended model with the available VRAM on the system.
5. Notice that the model recommendation is not optimized based on the available VRAM, it's using RAM for comparison :x:

**Expected behavior**
When GPU acceleration is enabled, the model recommendation under thread settings should consider the available VRAM on the system to suggest models that can run efficiently without exceeding VRAM limitations

**Environment details**
- Operating System: Windows 11

**Screenshots**
The issue in only happening on the recommendation of thread settings
![image](https://github.com/janhq/jan/assets/64197333/ed0a91af-72c6-4d8a-ac7c-4a88cfb38092)
on the other hand, Hub is recommending differently, but not sure which one is correct
![image](https://github.com/janhq/jan/assets/64197333/1a8b777e-4ac4-452d-b0d6-be69f67a7f3c)

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local API server
Making sure to redact any private information.

**Additional context**
Failure to optimize model recommendations based on VRAM usage may lead to inefficient resource allocation, performance degradation, and potential crashes when running models on GPU-accelerated systems.

**Comment by Van-QA** [comment]
chaining this to https://github.com/janhq/jan/issues/2216

**Comment by louis-jan** [comment]
Good find!

**Comment by louis-jan** [comment]
Another issue: In the hub, it currently says "RAM" but we check for "VRAM" instead (GPU is on).

**Comment by Van-QA** [comment]
![image](https://github.com/janhq/jan/assets/64197333/4427e252-5cc2-43eb-8c03-70a21da2e923)
![image](https://github.com/janhq/jan/assets/64197333/1d42e46c-5703-4470-b86b-febcaf19cd83)
Jan v0.4.9-346
