### ISSUE TITLE
Jan crashes during conversation

### ISSUE THREAD

**Issue by lv333ming** [janhq/jan#2340]
I'm in Jan a conversation window. After many rounds of dialogue it becomes impossible to continue. The system is in a crashed state. Sometimes a sentence will be repeated multiple times.

**Comment by lv333ming** [comment]
hi@Van-QA
4000 words is indeed too few for discussing a topic. How can we address the issue of limited word count in conversations?

**Comment by hahuyhoang411** [comment]
Hi @lv333ming I addressed the solution in this thread https://github.com/janhq/jan/issues/2387

Please reopen that if you need further help.
