### ISSUE TITLE
bug: Unable to upload an image to a chat using LlaVa vision model

### ISSUE THREAD

**Issue by ucg8j** [janhq/jan#2341]
**Describe the bug**
I'm not able to upload a file when using the LlaVa 1.5 13B Q5 K vision model.
This https://github.com/janhq/jan/issues/2235 was merged for the 0.4.8 release - so should be available to me. 

Screenshot of what my Jan looks like for me when LlaVa is selected.
![image](https://github.com/janhq/jan/assets/6220504/362ec077-5621-40be-97e7-72d81cff56ab)

**Steps to reproduce**
1. Create new chat thread
2. Select LlaVa 1.5 13B Q5 K model
3. Attempt to drag and drop file FAILS (no other way I can see to upload a file)

**Expected behavior**
Either drag and drop works. Or there is a UI button to upload a file to the thread.

**Environment details**
- Operating System: 13.5 (22G74)
- Jan Version: 0.4.8
- Processor: Apple M1
- RAM: 32gig

**Comment by ucg8j** [comment]
Btw - I really like the work you're doing. Keep it up JanHQ!

**Comment by Van-QA** [comment]
hi @ucg8j, we are still experiencing the vision feature, you can try it out by enabling exp feature:
![image](https://github.com/janhq/jan/assets/64197333/6e4fc1c2-6b2c-4cd5-9dc1-cbb9905e4b35)
After that, enable the retrieval setting:
![image](https://github.com/janhq/jan/assets/64197333/60aa1ad7-72f3-45eb-a180-bc632b9a3edf)
I hope this can help 🙏
