### ISSUE TITLE
feat: improve tensorrt-llm extension description

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2355]
Right now it says: Enables accelerated inference leveraging Nvidia's TensorRT-LLM for optimal GPU hardware optimizations. Compatible with models in TensorRT-LLM format. Requires Nvidia GPU driver and CUDA Toolkit installation.

A bit of a mouthful. 

Just updated it to: 

"This extension enables Nvidia's TensorRT-LLM for the fastest GPU acceleration. See the [setup guide](https://jan.ai/guides/providers/tensorrt-llm) for next steps."

**Comment by namchuai** [comment]
@Van-QA , the PR for this is merged. Please help to validate it. Thank you!
