### ISSUE TITLE
bug: Quickask - Jan processes dangling in background after quitting on Windows

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2356]
**Describe the bug**

-v0.4.8-322
- windows amd ryzen
- 4070s

**Steps to reproduce**
1. Open App
2. Click X
3. 5 Jan processes remain running, as indicated in task manager
<img width="549" alt="image" src="https://github.com/janhq/jan/assets/69952136/f626af24-84f6-4631-a4aa-ea1076ef15db">

5. type `cmd+j`
6. The quick ask loader animation shows for a few seconds
7. Then nothing happens. The app doesn't open, quick ask doesn't finish loading.
<img width="421" alt="image" src="https://github.com/janhq/jan/assets/69952136/c81dd420-f624-4dd4-a513-49c7a71e5302">

8. Open the app from bottom nav again
9. Try Quick Ask
10. Broken Entirely

## Why it's a problem

Jan disappears from TaskManager > Apps, so the app is theoretically not running.
But the 5 dangling processes are forever running as background processes. 
Albeit not taking up much resources

## Questions
- Can we name processes more distinctly? So we can tell from names which one is running
- What is the current expected behavior when users click `x` on windows?

**Comment by namchuai** [comment]
Currently, if we are enabling QuickAsk, we will display Jan in tray. Which means Jan still running even user clicked close on main window.

I think multiple processes shown in task manager is normal for electron app. Visual studio code has same behavior.
![Image](https://github.com/janhq/jan/assets/10397206/cafccc9e-8c1f-4244-a6b2-5b09bbb7a698)

But the issue that you captured (QuickAsk display installing extension) is a bug. We troubleshoot this issue in PR #2543 #2300 

I will retest, follow your steps and update.

**Comment by 0xSage** [comment]
Ah yes, upon checking, most apps have this behavior. I've noticed this with
Notion, 1Pass, Nordvpn, etc. I think having Jan persist as a process when
the window is closed is OK.

Can users click a button to `Quit Jan` in which case we fully terminate the
process?

Re bug; yes that's separate. Thanks!

**Comment by namchuai** [comment]
I can't reproduce this issue after the fix. @Van-QA , please help us to re-validate. Thank you 🙏
