### ISSUE TITLE
bug: Spelling Error in Toast for turning on GPU Acceleration

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#2359]
**Describe the bug**
I'm going to print a T-Shirt saying "Accelertion"

![image](https://github.com/janhq/jan/assets/101145494/6889f974-416d-444a-92b6-6f8e5518e16b)
![image](https://github.com/janhq/jan/assets/101145494/9c6da3c7-5603-4f2e-a082-687924508d58)

**Comment by Van-QA** [comment]
Tested and looking on using Jan v0.4.8-325 ✅
