### ISSUE TITLE
Explore and Install Plugins

### ISSUE THREAD

**Issue by drakehere** [janhq/jan#236]
**USER STORY**
As a user who wants to enhance my experience with AI and customize my experience within the application,
I want to be able to easily explore and install plugins, similar to Visual Studio Code.

**MVP IDEAS**
We will list the plugins in Github and add a button which direct users to Github to manually download and install it by drag n drop.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBb251IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4cf117922a298d7e95a1293e4617400450d7348c/Screenshot%202023-09-29%20at%2017.42.54.png)

**Comment by 0xSage** [comment]
dupe issue. this is being worked on in granular detail. closing
