### ISSUE TITLE
feat: custom url for API server (use as frontend)

### ISSUE THREAD

**Issue by dmatora** [janhq/jan#2365]
**Problem**
Right now you can only select ChatGPT API servers to connect to

**Success Criteria**
Would be great if you could connect to OpenAI compatible API server running on another machine

**Comment by louis-jan** [comment]
@dmatora. Please check this. I hope it's the one you're looking for.
https://jan.ai/guides/models/integrate-remote/#openai-platform-configuration

**Comment by dmatora** [comment]
This must have been moved to https://jan.ai/guides/engines/remote-server/#openai-platform-configuration
I was able to use this to connect to OpenAI compatible server, thank you.
But from what I see this don't allow using multiple different servers without rewriting configs/ restarting app
Is there away to define multiple OpenAI compatible remotes?

**Comment by louis-jan** [comment]
> This must have been moved to https://jan.ai/guides/engines/remote-server/#openai-platform-configuration I was able to use this to connect to OpenAI compatible server, thank you. But from what I see this don't allow using multiple different servers without rewriting configs/ restarting app Is there away to define multiple OpenAI compatible remotes?

We are working on it. Please follow the issue at #2451.

**Comment by louis-jan** [comment]
We can close it now since we supported multiple OpenAI Compatible remotes. @Van-QA 
Follow up: #2721

**Comment by dmatora** [comment]
@louis-jan I don't see any mention of that in the docs
how can this be achieved?
