### ISSUE TITLE
bug: Cannot change from one TRT model to another

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2371]
**Describe the bug**

**Steps to reproduce**
1. Choose Llamacorn
2. Chat
3. Open new thread and choose TinyJensen
4. Chat
5. Get the dreaded `somethings amiss` error
6. Change back to LLamacorn - everything is good

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.8.324
- Processor: AMD Ryzen 9
- VRAM: 8GB 4070

**Logs**
[app.log](https://github.com/janhq/jan/files/14611128/app.log)

**Comment by Van-QA** [comment]
Tested and looking on using Jan v0.4.8-325 ✅
