### ISSUE TITLE
bug: Quick Ask is broken for 324

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2372]
**Describe the bug**

**Steps to reproduce**
1. turn on experimental and quick ask
2. type command j
3. get the qa popup in loading state
4. stuck on loading forever

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

<img width="421" alt="image" src="https://github.com/janhq/jan/assets/69952136/91cf8e2d-ee52-44ce-af5a-a6803e296af1">

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.8.324
- Processor: AMD Ryzen 9
- VRAM: 8GB 4070

**Comment by Van-QA** [comment]
Confirmed that clearing cache resolve the issue ✅ https://jan.ai/guides/common-error/broken-build/#2-delete-application-data-cache-and-user-data
