### ISSUE TITLE
bug: Cannot manually import GGUF models

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2374]
**Describe the bug**

**Steps to reproduce**
1. Go to Model Hub
2. Click import model
3. Choose the correct filepath
4. No models are shown; Jan doesnt seem to detect the GGUF model in the folder

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

Regular Folder View
<img width="440" alt="image" src="https://github.com/janhq/jan/assets/69952136/5802a23d-cd43-435a-8057-27f62e891c2f">

When importing models with Jan
<img width="408" alt="image" src="https://github.com/janhq/jan/assets/69952136/3d01ae25-00df-4f4c-bc84-d9becefd9840">

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.8.324
- Processor: AMD Ryzen 9
- VRAM: 8GB 4070

**Comment by namchuai** [comment]
@0xSage this is actually an issue from electron team: https://github.com/electron/electron/issues/9411

If we showing files inside folder, we can't select to import a folder anymore.

**Comment by namchuai** [comment]
FYI, we are discussing about this.

So @louis-jan thinks that we should have additional step to ask user for the way he/she wants to import model: Select Folder or Select Files.

On Mac/Linux, we can skip this step.

**Comment by Van-QA** [comment]
Testing on Jan v0.4.10-366 ✅ 

When users choose GGUF, we might want to filter only GGUF format, I'm not sure if that is possible, but a nice to have feature cc: @namchuai 
![Image](https://github.com/janhq/jan/assets/64197333/28ade009-f8e5-4b96-8855-025b28d77124)



![Image](https://github.com/janhq/jan/assets/64197333/561429ec-44a5-4c8c-843d-d8e65706c3b5)
