### ISSUE TITLE
bug: Turning off Experimental doesnt turn off Quick Ask

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2378]
**Describe the bug**

**Steps to reproduce**
1. Fresh install, restarted computer
2. Go to settings, toggle Experimental on , turn on quick ask
4. Turn experimental to off
5. command j
6. quick ask opens and is in perpetual loading state

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
As discussed, we need to ensure that all settings that is under exp feat (with an additional switch):
- Vulkan Support
- Jan Quick Ask
to be automatically turned off when experimental feat turned off

**Comment by Van-QA** [comment]
Tested and looking good as of Jan v0.4.8-328 ✅
