### ISSUE TITLE
bug: Blocked during the loading model step, when switching from an active TensorRT model to a previously used TensorRT model

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2403]
**Describe the bug**
Users are blocked during the loading model step, when switching from an active TensorRT model to a previously used TensorRT model.

**Steps to reproduce**
1. Switch from Jensen to Llama corn model in Jan.
2. Note that the transition is smooth and successful.
3. Attempt to switch back from Llama corn to Jensen model.
4. Observe that the transition is not smooth and the application becomes unresponsive.
5. Repeat the process of switching between Jensen and Llama corn models.
6. Notice that switching back to the original model after transitioning to another model results in no error in UI, only app.log error "port not available".
7. Users are forced to close the application and reopen it to resolve the issue.

**Expected behavior**
Switching between TensorRT models in Jan should provide a seamless transition experience without causing the application to freeze or become unresponsive. Users should be able to switch between models smoothly without encountering any disruptions or glitches.

**Environment details**
- Operating System: Windows 11
- Jan Version: Jan v0.4.8-325

**Screenshots**
![image](https://github.com/janhq/jan/assets/64197333/9f2664f3-965b-4752-93de-ced0c0bdf53d)
![image](https://github.com/janhq/jan/assets/64197333/781de932-c1e4-469c-bb68-d2c626d31be3)

**Logs**
[app.log](https://github.com/janhq/jan/files/14627370/app.log)

**Additional context**
The inconsistent behavior observed while switching between TensorRT models may disrupt user workflows and cause frustration. Identifying and resolving the underlying cause of this issue is essential to ensure a seamless user experience in Jan.

**Comment by louis-jan** [comment]
I made a minor change in PR #2400 to address this issue.
