### ISSUE TITLE
Request: support for Cohere Command-R

### ISSUE THREAD

**Issue by vlbosch** [janhq/jan#2405]
Can the llama.cpp version be bumped to the version which has support for Cohere Command-R (b2440+)? A link to the model: https://huggingface.co/CohereForAI/c4ai-command-r-v01 and here for the quants: https://huggingface.co/andrewcanis/c4ai-command-r-v01-GGUF

Thanks in advance!

**Comment by hahuyhoang411** [comment]
Thank you @vlbosch for the suggestion. It will be added in the next version.
