### ISSUE TITLE
Change License

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#241]
## Task

- We are likely to move towards the direction where personal/hobbyist use is free, while requiring commercial use to pay for a license
- Practical decisions required to ensure Jan has a sustainable business model
- Inspiration: Obsidian, etc

## Todos

- [ ] Research Obsidian's license
- [ ] Update LICENSE.md

**Comment by 0xSage** [comment]
@dan-jan pls do this soon

**Comment by dan-jan** [comment]
Closed by #356
