### ISSUE TITLE
not able to activate model "zephyr-7b-gemma-sft-v0.1.Q4_K_M"

### ISSUE THREAD

**Issue by Excurl** [janhq/jan#2433]
not able to activate models 
"[zephyr-7b-gemma-sft-v0.1.Q4_K_M](https://huggingface.co/MaziyarPanahi/zephyr-7b-gemma-sft-v0.1-GGUF/blob/main/zephyr-7b-gemma-sft-v0.1.Q4_K_M.gguf)" , 
"[zephyr-7b-gemma-sft-v0.1.Q4_K_S](https://huggingface.co/MaziyarPanahi/zephyr-7b-gemma-sft-v0.1-GGUF/blob/main/zephyr-7b-gemma-sft-v0.1.Q4_K_S.gguf)"  after import
machine: mac mini m2 pro 16GB
models are from : https://huggingface.co/MaziyarPanahi/zephyr-7b-gemma-sft-v0.1-GGUF..

**Comment by hahuyhoang411** [comment]
Hi @Excurl , can you share me the `model.json` of these 2 models?

I reproduced it and it's working fine on my side.

**Comment by hahuyhoang411** [comment]
Temporarily close the issue. If you have further problem please open again. Thank you.
