### ISSUE TITLE
bug: Route POST:/v1/threads not found

### ISSUE THREAD

**Issue by lasc** [janhq/jan#2435]
When trying to create a threads from API using the example got back 404
curl -X 'POST' \
                                  'http://localhost:1337/v1/threads' \
                                  -H 'accept: application/json' \
                                  -H 'Content-Type: application/json' \
                                  -d '{
                              "object": "threads",
                              "title": "funny physics joke",
                              "assistants": [
                                {
                                  "assistant_id": "jan",
                                  "assistant_name": "Jan",
                                  "instructions": "string",
                                  "model": {
                                    "id": "openchat-3.5-7b",
                                    "settings": {},
                                    "parameters": {},
                                    "engine": "nitro"
                                  }
                                }
                              ],
                              "metadata": {}
                            }'
{"message":"Route POST:/v1/threads not found","error":"Not Found","statusCode":404}⏎

Steps to reproduce the behaviour:
1. enable API server
2. go to Swagger UI/ API reference
3. Click to try on POST threads and click execute 
4.  ,"msg":"Route POST:/v1/threads not found"

**Expected behavior**
New thread created

**Environment details**
- Operating System: MacOS Sonoma 14.2.1]
- Jan Version: 0.4.9
- Processor:  Apple M1
- RAM: 32GB

**Logs**
{"level":30,"time":1710899742388,"pid":40382,"hostname":"-.local","reqId":"req-6","req":{"method":"POST","url":"/v1/threads","hostname":"localhost:1337","remoteAddress":"127.0.0.1","remotePort":53186},"msg":"incoming request"}

{"level":30,"time":1710899742389,"pid":40382,"hostname":"-.local","reqId":"req-6","msg":"Route POST:/v1/threads not found"}

**Comment by aidec** [comment]
try 
http://localhost:1337/v1/threads/

**Comment by lasc** [comment]
YES! POST works with / at the end. GET working only without trailing slash

**Comment by Van-QA** [comment]
Tested and not able to use the thread without trailing slash :x:
![image](https://github.com/janhq/jan/assets/64197333/c05815fe-fbcc-4795-9289-818216630b5a)

**Comment by Propheticus** [comment]
The same might be true for other resources, like /v1/chat/completions
See https://discord.com/channels/1107178041848909847/1219615223569190952

**Comment by Van-QA** [comment]
Tested and looking good using Jan v0.4.9-343 ✅ 

![Image](https://github.com/janhq/jan/assets/64197333/4b49f3bb-4079-4b17-989d-1d88d6393153)

@Propheticus would you mind trying the new version as well? 🙏

**Comment by Propheticus** [comment]
Testing via the swagger ui worked, but the lmstudio style (claiming to follow OpenAI api standard) integration didn't.  
However, I found that the 'Local AI' style integration does work!
![image](https://github.com/janhq/jan/assets/6628064/5def361e-752e-4710-853e-4b534f79dec4)
![image](https://github.com/janhq/jan/assets/6628064/25eddab4-07f5-4630-be92-a2a3d8e360e1)
![image](https://github.com/janhq/jan/assets/6628064/327c1b1a-0f8f-48a7-a72f-787f8fdecd33)
