### ISSUE TITLE
bug: Stop button got stuck

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2440]
**Describe the bug**
Stop button got stuck

https://github.com/janhq/jan/assets/89722390/6fd2eb30-7179-4b42-bcc1-81c1a1bb0859

**Steps to reproduce**
1. Start Mistral Instruct 
2. App got stuck

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: 0.4.8-333
- Processor: M2
- RAM: 16GB

**Logs**

[app.log](https://github.com/janhq/jan/files/14668081/app.log)

**Comment by Engylizium** [comment]
I just solved this on my PC, not sure if you have the same problem but:
In console I saw errors stating that my GPU is not supported (1080Ti) so I had to turn off GPU acceleration in settings and it was solved.
