### ISSUE TITLE
API feature additions 

### ISSUE THREAD

**Issue by aidec** [janhq/jan#2442]
The API can create assistants and threads, but there seems to be no API available to use them.

How to use specified assistants and threads to chat in the API?

**Comment by Van-QA** [comment]
Hi @aidec,
While the API can generate assistants and threads, there doesn't seem to be an available API to utilize them directly. However, you can achieve the desired functionality by generating a chat response using chat completion and then posting it into the thread message.
https://jan.ai/api-reference/#tag/chat/post/chat/completions

**Comment by aidec** [comment]
thanks for your reply

I want to try and see how to apply it

**Comment by Van-QA** [comment]
Feel free to reopen this if any concern 🙏
