### ISSUE TITLE
Paste image as alternative to browsing for file

### ISSUE THREAD

**Issue by glinkot** [janhq/jan#2462]
When asking chatGPT vision (or other model supporting images) to look at something, it would be great to take a screenshot and just hit ctrl-v while entering the prompt, rather than saving the file, choosing a name, then browsing again to find it.

**Comment by imtuyethan** [comment]
Thanks for your suggestion @glinkot. We're moving ahead with this:
- Jan can see is on sprint schedule
- Later on we will have Quick Ask, where users can use Jan inline with other apps by summoning it using a hotkey; and users can paste text snippet, image from their clippboard. 
Figma: https://www.figma.com/file/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?type=design&node-id=0-1&mode=design

![Image](https://github.com/janhq/jan/assets/89722390/dc477bae-647a-4ba4-bbfb-936bff232de7)

(you can take a look at this as reference though we may not have all the features listed in the design)

- It may take us a while to officially release this so stay tuned! I'm gonna close this ticket as duplicated.
