### ISSUE TITLE
Tabs or channels

### ISSUE THREAD

**Issue by glinkot** [janhq/jan#2463]
As many people would, I tend to ask many questions but divided into a handful of general subjects - a game I'm developing, vs personal items, todo organisation or whatever.  In the case of jan.ai, it might even be nice to have a tab per model being used.  It would be great to have separate tabs/threads available to help with organisation.

**Comment by imtuyethan** [comment]
Thanks for your suggestion! @glinkot We're moving ahead with this with Archive/Folders & Custom Tab View:


![Image](https://github.com/janhq/jan/assets/89722390/a0004743-9644-4f09-b360-fe451ad4e890)

Please be patient, it may take us awhile to get there! Thank you for using Jan. I'm gonna close this as duplicated.
