### ISSUE TITLE
feat: Add system requirements for model

### ISSUE THREAD

**Issue by inyutin-maxim** [janhq/jan#2468]
**Problem**
When choosing a model, it is not clear how to determine whether it makes sense to download it if my computer is not suitable for some reason, or everything will work very badly

**Success Criteria**
To description add section with system requirements for works with model

**Comment by Van-QA** [comment]
hi @inyutin-maxim, 
Each model from the Hub will have a model size and a label based on RAM / VRAM, I hope this can help 
![image](https://github.com/janhq/jan/assets/64197333/6615742a-b785-457f-961b-35f90cd8e7c3)
