### ISSUE TITLE
bug: Slowness on Intel Mac

### ISSUE THREAD

**Issue by Janaifan** [janhq/jan#2469]
I have a mac based Intel (I7) and 64 GB of RAM but Jan.ai Mistral is still slow at use.
First versions of Jan were more responsive.

**Comment by hahuyhoang411** [comment]
Hi @Janaifan , Thank you for using Jan.

Can I ask for the whole context of the problem
- What is the t/s?
- Are you using the same thread for a long conversation?

**Comment by Janaifan** [comment]
Hi

    What is the t/s? Could you explain ? If it's max token is 4096
    Are you using the same thread for a long conversation? Yes but it's slow at the first prompt

Thanks

**Comment by Janaifan** [comment]
New test today : Tokens at 2048 : t/s 0,22 / s
Model Mistral Instruct 7B Q4

**Comment by hahuyhoang411** [comment]
Hi, @Janaifan, with the latest version of Jan, do you still have this problem?

**Comment by 0xSage** [comment]
stale issue
