### ISSUE TITLE
can you add chatglm model download url?

### ISSUE THREAD

**Issue by nzky0** [janhq/jan#2472]
like the title,i want use chatglm model or other chinese model??

**Comment by Van-QA** [comment]
hi @nzky0, Can you have a look at these docs?
- Download manually and Import the local model: https://jan.ai/developer/framework/engineering/models/#importing-models
- Import the remote model: https://jan.ai/guides/engines/openai/#step-2-model-configuration
- Advanced: Modify the model.json to include the correct URL along with other info to download model from the hub

**Comment by nzky0** [comment]
but I didn’t find the download address of chatglm in GGUF format.

**Comment by Van-QA** [comment]
Sorry for the inconvenience, @nzky0. When a model is not available in GGUF format, I would suggest bringing this to the attention of Hugging Face, as they may be able to assist with the issue.
They may be able to provide more information and a timeline for when the model will be available in GGUF format: https://huggingface.co/THUDM/chatglm3-6b/discussions/40

**Comment by WainLai** [comment]
There is a link that explains how Hugging Face models can be converted to GGUF. 
Any chance to implement a GGUF converting wizard in Jan?

**Comment by louis-jan** [comment]
#1056

**Comment by 0xSage** [comment]
coming soon
