### ISSUE TITLE
bug: repeat question 

### ISSUE THREAD

**Issue by pascas23** [janhq/jan#2478]
**Describe the bug**
the assistant simply repeats my question instead of answering

**Steps to reproduce**
I downloaded last release from https://jan.ai/download/
I clicked HUB
I downloaded "TinyLlama Chat 1.1B Q4" model
After the download is finished I clicked USE
I make the question in "Enter your message" box
After a few minutes of waiting I saw some text being generated by the assistant. The text simply stated my question identically

**Expected behavior**
I was expecting some kind of answer regarding the question

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.9
- Processor: Intel N95
- RAM: 16GB
- GPU: Intel UHD Graphics
[app.log](https://github.com/janhq/jan/files/14733046/app.log)

**Comment by hahuyhoang411** [comment]
Hi @pascas23 , Thank you for using Jan.

Tinyllama is only a very small model, sometimes it will have unexpected behavior. For a better experience, I recommend trying 7B models like Stealth 7B, Mistral 7B, etc.

Please reopen the issue if you have any further problem.
