### ISSUE TITLE
bug: index.js.DELETE in `conversational-extension` causes Jan to fail

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#2480]
**Describe the bug**

**Steps to reproduce**
1. Auto-update on Windows Nightly
2. Jan Window crashes with net::ERR_FILE_NOT_FOUND for extension://@janhq/conversational-extension/dist/index.js:1 
3. conversational-extension has `index.js.DELETE.368138bae7ccd5dbfae4379cb93908f4`
![image](https://github.com/janhq/jan/assets/101145494/359d8ff8-4844-43ea-bdd8-7082ed3d61fa)
![image](https://github.com/janhq/jan/assets/101145494/6db94c58-1619-417e-84bf-1651f6efc1e2)

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Windows
- Jan v0.4.9-341

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by louis-jan** [comment]
I encountered this issue last Saturday and have been investigating it since then. I still haven't been able to reproduce it, but I noticed that it occurred after I removed the .DELETE-xxxx extension. I will try to reproduce it.

**Comment by Propheticus** [comment]
All sorts of things broke and processes got stuck when I updated nightly 343 to 345 (preparing update ...). Had to do a clean uninstall > install.

**Comment by dan-jan** [comment]
This was fixed with a clean install, including blowing away `%APPDATA%`

We should probably find a way to avoid having to make the user go into %APPDATA%,

**Comment by namchuai** [comment]
I was able to reproduce this issue. Here's the steps:
1. Using Jan version 0.4.9 (can take any build number)
2. Go to `%APPDATA%`, edit `settings.json`. Set `quick_ask` to `true`
3. Remove Jan data folder
4. Observe that Jan can't open and yield issue that Dan mentioned above.

I fixed this issue with #2543 . @Van-QA , please help me to re-validate this issue on nightly build. Thank you very much 🙏
