### ISSUE TITLE
epic: Standardized Error Format for Jan

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2482]
## Motivation
The current error handling system in Jan app has too many edge cases, which is challenging to maintain. Our goal is to implement a simplified, standardized error format within the Jan app, focusing on improving maintainability, and providing better context for error handling.

### Key Results

- **Less hassle:** We'll save time by using a standard template instead of creating unique messages for each scenario.
- **Efficient troubleshooting:** Standardized messages speed up troubleshooting for both users and app pod.

## Specs
https://www.notion.so/jan-ai/Standardized-Error-Format-for-Jan-abea56d32d6648bb8c6835f9176f800c?pvs=4

## Key User Stories
- Users should see a clear & standardized error message
- Users see inline error message in threads
- Error message should be saved in threads so users can look back when they need to
- Errors:
    - For unclear errors, users should see troubleshooting guide & can file Github issue
    - For identified error, we should map it with error code & recommended actions

## Designs
https://www.figma.com/file/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?type=design&node-id=2858-90537&mode=design&t=bjtQNvQF32BiMtU5-4

![Image](https://github.com/janhq/jan/assets/89722390/349a9f26-432c-49e1-b809-95991f71a7bd)

**Comment by louis-jan** [comment]
Duplicated, #2556
