### ISSUE TITLE
bug: doesn't gracefully stop a model

### ISSUE THREAD

**Issue by kundeng** [janhq/jan#2486]
**Describe the bug**
Most of the time, it does not gracefully stop a model.  Causing UI in a limbo state. 

![image](https://github.com/janhq/jan/assets/89032/b18a122e-f96d-4686-9dcf-a52eeb70a1b8)

**Comment by Van-QA** [comment]
hi @kundeng , 
please share with us:
- Your OS version
- Your spec: CPU serial, memory 
- Jan app version
- your app.log

**Comment by Van-QA** [comment]
Thank you, The case of killing Nitro requested every time the context length value changed, is indeed a problem.
Even when Nitro was killed successfully (see below log), can we reduce these duplicate request? @louis-jan 

> 2024-03-26T13:10:05.460Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:05.630Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:05.687Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:05.720Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:05.785Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:05.980Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:06.044Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:06.194Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:06.299Z [NITRO]::Debug: Request to kill Nitro
> 2024-03-26T13:10:07.261Z [NITRO]::Debug: Nitro process is terminated
> 2024-03-26T13:10:07.261Z [NITRO]::Debug: Nitro process is terminated
> 2024-03-26T13:10:07.262Z [NITRO]::Debug: Nitro process is terminated
> 2024-03-26T13:10:07.262Z [NITRO]::Debug: Nitro process is terminated
> 2024-03-26T13:10:07.261Z [NITRO]::Debug: Nitro process is terminated

**Comment by Van-QA** [comment]
looking good on Jan v0.4.10-367 ✅
