### ISSUE TITLE
Does it support a TPU?

### ISSUE THREAD

**Issue by fwartner** [janhq/jan#2492]
I got no real GPU on my homelab so i would be interested if there's support for TPU?

**Comment by Van-QA** [comment]
hi @fwartner, 
Unfortunately, we don't support TPU atm due to a lack of hardware for testing purposes.

@hiro-v would it be possible for us to support this user somehow? thank you

**Comment by fwartner** [comment]
I agree with @Disane87 (Who actually brought me to Jan ^^)..

If needed: I would love to sponsor a Coral TPU for testing purposes!

**Comment by mawoka-myblock** [comment]
As far as I am aware, the Coral TPU won't help here as it is only made for small models, but LLMs are large, as the name implies and by that too big for the ram on the TPU and streaming the model is also too slow.

**Comment by dan-jan** [comment]
Let's continue to keep this discussion thread open. I'm intrigued by the potential of Coral TPU. 

- We currently don't have this on our roadmap
- We are focused on refactoring our existing engines (e.g. TensorRT-LLM, OpenAI, etc) into an Inference Engine SDK
- This should make it possible for the community to build a Coral TPU Inference Engine pretty easily
