### ISSUE TITLE
bug: Troubleshooting Assistance - all log fields should be expandable, allowing users to drag and change the size of log fields for more convenient

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2499]
**Describe the bug**
Make the log fields allow resizing

**Steps to reproduce**
1. In troubleshooting assistance, attempt to modify the size of the log fields

**Expected behavior**
![image](https://github.com/janhq/jan/assets/64197333/21ca0ee9-d86b-4142-bd06-deeb4fbd8498)

**Screenshots**
![image](https://github.com/janhq/jan/assets/64197333/70d9b69c-7a6d-4e0f-9185-226a22ee7da3)

**Comment by urmauur** [comment]
@Van-QA @imtuyethan I think this is impossible on UI bc the log is inside the modal, and we have maximum height and width to the window for the modal, and the log already has maximum width and height, I think we need to think of a better idea for handling this

**Comment by urmauur** [comment]
ad discussed with @Van-QA we'll add a button to toggle the log as a full screen and overlap the step guideline
