### ISSUE TITLE
feat: Better chat sidebar (left)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#250]
**Problem**
- Our current sidebar UX is a bit awk. 

**Success Criteria**
- [x] #142 
- [x] Sidebar can collapse/expand with animation
- [x] Sidebar settings section is fixed at bottom
- [x] Sidebar convo history is scrollable

**Additional context**
Designs: https://www.figma.com/file/JdK7cNIBeVdYeHxKiYeWtk/JAN---Web?type=design&node-id=3300-5820&mode=design&t=XscMIMPvG2H8djjN-0

**Comment by 0xSage** [comment]
No more hover to expand. See updated designs: https://www.figma.com/file/JdK7cNIBeVdYeHxKiYeWtk/JAN---Web?type=design&node-id=3308-11667&mode=design&t=NKTnJyqEy20n6lx6-0

keeping it simple

**Comment by namchuai** [comment]
issue fixed with #349
