### ISSUE TITLE
bug: jan docker server build fails to copy docs from builder

### ISSUE THREAD

**Issue by manschwetus** [janhq/jan#2500]
**Describe the bug**
Dockerfile step 18 fails as source directory in builder is missing.
```make
Step 18/30 : COPY --from=builder /app/docs/openapi ./docs/openapi/
COPY failed: stat app/docs/openapi: file does not exist
```
**Steps to reproduce**
1. clone/checkout dev
2. run `docker build -t jan .`
3. Fails at step 18

**Expected behavior**
Build succeeds

**Environment details**
- Operating System: Gentoo Linux
- Jan Version: git - dev
- Processor: AMD Ryzen 7 8700G
- RAM: 64GB

**Logs**
```make
Step 18/30 : COPY --from=builder /app/docs/openapi ./docs/openapi/
COPY failed: stat app/docs/openapi: file does not exist
```

**Additional context**
Blocks testing of #2394

**Comment by Van-QA** [comment]
hi @manschwetus, can you try again? dev team made a few changes to resolve the issue, thank you
