### ISSUE TITLE
Model is not starting

### ISSUE THREAD

**Issue by ibrahimsayedahmad** [janhq/jan#2503]
![Screenshot (371)](https://github.com/janhq/jan/assets/9349775/f268181f-dff1-4de0-815f-566e48a00ee3)
### Discussed in https://github.com/janhq/jan/discussions/2502

<div type='discussions-op-text'>

<sup>Originally posted by **ibrahimsayedahmad** March 26, 2024</sup>
I downloaded multiple models but non of them is starting.
The status is always Inactive and when trying to start a model it shows starting then goes again to inactive status.
No error messages arised.</div>

**Comment by prsf1233** [comment]
This happened to me after I enabled GPU (Nvidia 600 on my laptop) and had not installed the CUDA Toolkit.

HTH
Graham

**Comment by ibrahimsayedahmad** [comment]
Thanks
This solved the issue

**Comment by Van-QA** [comment]
Thank you for your time, I'm glad to know that the issue was resolved. Feel free to reach out if you have any further questions or concerns in the future.
