### ISSUE TITLE
feat: Rename assistant in Thread Settings

### ISSUE THREAD

**Issue by WainLai** [janhq/jan#2510]
For now, the thread labels are the first few words of the first line of the dialog.
The only options available in the three-dot menu are 'clean thread' or 'delete thread'. Is it possible to add 'rename thread'?

**Comment by Van-QA** [comment]
Hi @WainLai, 
You can rename the thread using thread setting:
![image](https://github.com/janhq/jan/assets/64197333/add5e4ac-d843-497e-a32e-94efd4ac8bdf)

**Comment by WainLai** [comment]
It was too obvious too notice... I'm so stuck with the software I used before that I'm blind to anything novel (to me).
THANKS!

**Comment by WainLai** [comment]
BTW, is there a way to rename the assistant, so that it doesn't appear as 'Assistant' inside the thread?

**Comment by Van-QA** [comment]
hi @WainLai, 
That is indeed not available yet, we will consider it in the future. I will correct the title of this ticket for that request. 
Thank you

**Comment by GenkaOk** [comment]
> hi @imtuyethan,
> When I manually modify the assistant json, it's applied to the assistant settings "123name", Would it be okay if we applied it to the name of the response from the model as well?

#2529

**Comment by imtuyethan** [comment]
Agree to merge
