### ISSUE TITLE
feat: please add cloud-api support for Mistral's 3 models

### ISSUE THREAD

**Issue by lineality** [janhq/jan#2518]
I tried using the openai and groq api code as a template for creating a Mistral api pathway in Jan...but nothing worked. Whoever set these up could probably add mistral in a few seconds. 
As the misral api is modeled closely after openai

 "https://api.mistral.ai/v1/chat/completions" \

[mistral.json](https://github.com/janhq/jan/files/14771936/mistral.json)
[model.json](https://github.com/janhq/jan/files/14771937/model.json)
[extensions.json](https://github.com/janhq/jan/files/14771938/extensions.json)
**Problem**

**Success Criteria**

**Additional context**
[mistral_tiny_cloud_api.zip](https://github.com/janhq/jan/files/14771960/mistral_tiny_cloud_api.zip)

**Comment by Van-QA** [comment]
Closing this and please follow up using the related feature ticket: #2072. 🙏 
Side note: the extension is now ready in the nightly build. Jan v0.4.10-367
