### ISSUE TITLE
bug: Javascript error in the main process

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#253]
**Describe the bug**

**To Reproduce**
1. Use Jan
2. Dont quit it
3. Go to sleep
4. Log in next day
5. Click on Jan dock icon
6. see error

**Expected behavior**

**Screenshots**

![Image](https://github.com/janhq/jan/assets/69952136/49fb5a21-2319-4d06-bf4a-49e23bd9bb5d)

**Desktop (please complete the following information):**
 - OS: Mac 
 - 

![Image](https://github.com/janhq/jan/assets/69952136/7d3c3019-1660-4a41-adc8-23fdcfdcf28f)

**Additional context**

**Comment by louis-jan** [comment]
Fixed in #248 PR
