### ISSUE TITLE
bug: 0.4.9-349 Install does not fully recreate jan folder on Windows

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#2536]
**Describe the bug**
Filing this bug as a follow up to #2480 
I am not sure if this is an edge case, but filing it first before restarting computer to collect full details

**Steps to reproduce**
1. Uninstall 0.4.9-348 (or broken Jan) using Windows Settings
2. Delete `/jan` folder from root
3. Install 0.4.9-349
4. There is no `/jan` folder created

_Restart Computer_
1. Jan went through update process
2. However - same ERR_FILE_NOT_FOUND issue
3. Opening /jan folder only sees two folders
4. `conversational-extension` still has the `index.js.DELETE.2a14f6415918c1e2306afbf96bf2554d`

**Expected behavior**
I would have expected Jan to install and re-create the `/jan` folder from root

**Follow-ups**
- [x] Restart computer and try again
- [ ] Try installing Jan Stable and see if `/jan` folder is created

**Screenshots**

![image](https://github.com/janhq/jan/assets/101145494/80773771-7e29-4335-a77b-8c6b29a3bc61)

![image](https://github.com/janhq/jan/assets/101145494/e4fa0bb4-7ed3-453d-85c4-fd8cd4129042)

![image](https://github.com/janhq/jan/assets/101145494/6c4300bc-d17c-452b-9e09-6f0a0a1707cd)

**Environment details**
- Windows
- Jan: 0.4.9-nightly

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by dan-jan** [comment]
Is related to #2480, I am merging this back to that issue

**Comment by namchuai** [comment]
@dan-jan , could you please attach the content of the setting file for us to troubleshoot please.
1. Open app data
<img width="442" alt="Screenshot 2024-03-29 at 13 16 28" src="https://github.com/janhq/jan/assets/10397206/5c36cf93-efe9-4e21-8870-71562dc7ca7b">
2. Open Jan\settings.json
<img width="839" alt="Screenshot 2024-03-29 at 13 17 41" src="https://github.com/janhq/jan/assets/10397206/98c7dac4-1948-41ae-a603-28323c338047">

**Comment by dan-jan** [comment]
@namchuai Contents below: 

```
{"data_folder":"C:\\Users\\dan\\jan","quick_ask":true}
```

**Comment by dan-jan** [comment]
@namchuai Other data points: 

Multiple Jan.exe in tasklist
![image](https://github.com/janhq/jan/assets/101145494/b51c13af-446f-4313-890a-3f6b3c09e1a1)

**Comment by namchuai** [comment]
if you want a clean install, please also remove Jan inside `%APPDATA%`.
