### ISSUE TITLE
bug: Jan can see does not work when retrieval is on

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#2537]
**Describe the bug**
- If `Retrieval` is ON, even though I upload `image` it does not understand the image content. 
- Upon checking the network, the image content is dropped and `Jan RAG` is used instead

**Steps to reproduce**
1. Enable Experimental
2. Download `Llava` model
3. Turn on Retrieval
4. Upload image (an image with a dog) and ask `What is in the image`
5. Check the network in Inspector, see the prompt, the image base64 content is dropped
6. Turn off Retrieval -> It's normal

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: 0.4.9-350
- Processor: Mac and Windows

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
<img width="1208" alt="Screenshot 2024-04-01 at 11 18 32" src="https://github.com/janhq/jan/assets/64197333/fd61aaa4-cc52-43d5-becb-b2bf7044b39f">
Tested and looking good using Jan v0.4.9-352
