### ISSUE TITLE
feat: distribute as flatpak

### ISSUE THREAD

**Issue by Jak2k** [janhq/jan#2547]
**Problem**
I'm not using debian and AppImages are kind of messy.

**Success Criteria**
Packaging as flatpak.

**Additional context**
Flatpak is a containerized packaging format than can be installed on almost any Linux distribution. It's also safer than an AppImage and can even be published on FlatHub to reach more people.

**Comment by Van-QA** [comment]
Duplicated of https://github.com/janhq/jan/issues/1685
