### ISSUE TITLE
feat: Jan support for Windows ARM64

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#2550]
**Problem**
- There are users using Windows on ARM64 (Windows surface)
- Link https://github.com/janhq/jan/issues/2506

**Success Criteria**
- Support Windows ARM64 for Jan and Nitro

**Additional context**

**Comment by hiento09** [comment]
If we had to choose between supporting Windows ARM64 and Linux ARM64, I'd lean towards Linux ARM64 since it seems more doable and likely to benefit more users. Just wanted to share my two cents on this. Let's focus our efforts where they can have the most impact

**Comment by bogorad** [comment]
arm64 is the future of windows, made clear by the new CPU from Qualcomm and MS's upcoming Surface. too bad such a simple thing - building Electron for ARM64 encounters such resistance.

**Comment by knd775** [comment]
Microsoft is moving their Surface line to ARM64. I'm typing this from a Surface Laptop 7 with a Snapdragon CPU. I think this is shortsighted.
