### ISSUE TITLE
bug: Jan Reset - Users are stuck in the "Factory reset in progress" when Nitro process running in the background

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2555]
**Describe the bug**
Users are unable to abort or bypass the "Factory reset in progress" screen when a Nitro process is running in the background. This issue prevents users from using the Factory reset feature normally.

**Steps to reproduce**
1. With a Nitro process in the background (or file opening).
2. Initiate a factory reset on the application.
3. The "Factory reset in progress" screen remains stuck and cannot be closed or bypassed.

**Expected behavior**
After initiating a factory reset, users should be able to abort or bypass the reset process if needed, even if a Nitro process is running in the background.

**Screenshots**
<img width="1175" alt="Screenshot 2024-04-01 at 14 26 45" src="https://github.com/janhq/jan/assets/64197333/0254afd3-3cfe-4c1d-aeba-a96267113ceb">

**Environment details**
- Windows with latest Jan version

**Comment by namchuai** [comment]
Seems like the issue lie in Nitro. When nitro is busy working on something (e.g. starting model) and we call API kill, the API never return.
