### ISSUE TITLE
epic: Better Error Handing 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2556]
## Motivation
The current error handling system in Jan app has too many edge cases, which is challenging to maintain. 
Our goal is to implement a simplified, standardized error format within the Jan app, focusing on improving maintainability, and providing better context for error handling.

### Key Results
- **Less hassle:** We'll save time by using a standard template instead of creating unique messages for each scenario.
- **Efficient troubleshooting:** Standardized messages speed up troubleshooting for both users and platform.

## Key User Stories
- Users should see a clear & standardized error message
- Users see inline error message in threads
- Error message should be saved in threads so users can look back when they need to
- Users can copy logs & file Github issue or send it to our Discord
- Errors type:
    - For unclear errors, there’s no error code
    - For identified error, we map it with error code
- All errors should be mapped out with recommended docs

![Image](https://github.com/janhq/jan/assets/89722390/e928ee72-30bf-4112-84e9-1e2c642c0472)

![Screenshot 2024-04-16 at 4 36 56 PM](https://github.com/janhq/jan/assets/89722390/c57c0f8c-c121-4403-9220-454a48f27d59)

See error code numbering convention: https://www.notion.so/jan-ai/Error-Code-Numbering-Convention-a3a1e96a93254df3ace6dc93d4cc849e?pvs=4

## Specs
Check Notions spec for more details
https://www.notion.so/jan-ai/Standardized-Error-Format-for-Jan-abea56d32d6648bb8c6835f9176f800c?pvs=4

## Designs
[Figma](https://www.figma.com/file/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?type=design&node-id=2244-39798&mode=design&t=aeQ1xgzie2eq3ycw-4)
<img width="642" alt="Screenshot 2024-04-16 at 4 38 09 PM" src="https://github.com/janhq/jan/assets/89722390/12f240a5-39e0-4426-91c6-985cbaa763e6">

**Comment by imtuyethan** [comment]
Related:
1. Model fails to load models when the file path contains special characters: https://discord.com/channels/1107178041848909847/1294680372264697907
2. Missing Hardware Dependencies → Ask users to download dependencies to turn on GPU acceleration: https://github.com/janhq/jan/issues/3688

**Comment by 0xSage** [comment]
Handled by cortex, this issue is a UI/design issue, which we need to rework
