### ISSUE TITLE
bug: Model download stuck at 0% and cannot be cancelled

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2568]
**Describe the bug**
The model download for "Phind 34B Q4" is stuck at 0%. This prevents the user from cancelling the download.

**Steps to reproduce**
1. Go to Model Hub
2. Download Phind 34B Q4

**Expected behavior**
The download progress should update as the model is downloaded. The "Cancel Download" button should be enabled and allow the user to cancel the download.

**Screenshots**
<img width="1312" alt="Screenshot 2024-04-02 at 11 12 49" src="https://github.com/janhq/jan/assets/133622055/c7bed2ae-5cb3-4a50-902b-6a24ff80cafd">

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
The issue is still reproducible after cleared the extension 
![phi](https://github.com/janhq/jan/assets/64197333/a1719546-636a-4c6f-a803-4de251f6645d)

**Comment by Van-QA** [comment]
![image](https://github.com/janhq/jan/assets/64197333/8eedea98-f46f-4c82-8525-9153297e5410)
