### ISSUE TITLE
bug: jan app launch results in a blank white screen

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2570]
**Describe the bug**
Upon launching the application, I am presented with a completely white screen with no UI elements visible, rendering me unable to interact with the app or access any of its features.

**Steps to reproduce**
1. Go to the application icon on the desktop or application list.
2. Click on the icon to launch the application.

**Expected behavior**
The application should load its main interface upon launch, displaying its contents and features for user interaction.

**Screenshots**
<img width="1205" alt="Screenshot 2024-04-02 at 12 37 25" src="https://github.com/janhq/jan/assets/159995642/6db5f1fd-a2e2-46d4-8285-4bf9add46668">

**Environment details**
- Operating System: MacOS Sonoma 14.0
- Jan Version: 0.4.10
- Processor: Apple M1
- RAM: 8GB

**Logs**
<img width="549" alt="Screenshot 2024-04-02 at 13 01 48" src="https://github.com/janhq/jan/assets/159995642/eb655f8a-39f9-45c3-8c2f-f85d2a28ac3a">

**Comment by dan-jan** [comment]
Seems related to https://github.com/janhq/jan/issues/2480?

**Comment by louis-jan** [comment]
It looks like this is an issue that has been fixed in the latest dev, nightly build 360.
