### ISSUE TITLE
chore: Relocate the TensorRT dependency installation action to its settings page

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2571]
**Description**
Since TensorRT has its own Settings page, we should move "Install/Update Dependencies" to that page. Therefore, the Extensions page should only have the "Uninstall" action.

<img width="400" alt="Screenshot 2024-04-02 at 13 07 06" src="https://github.com/janhq/jan/assets/133622055/5aca428f-6986-4902-be0f-df038f836dfc">
<img width="400" alt="Screenshot 2024-04-02 at 13 07 01" src="https://github.com/janhq/jan/assets/133622055/d63c5506-bf76-4862-a8b1-a8b0983ff074">

**Expected behavior**
The TensorRT Settings page should have the 'Dependency Install' action.

**Comment by Van-QA** [comment]
Tested and looking good Jan v0.4.10-372
