### ISSUE TITLE
bug: Settings redirect is not leading users to the correct sub-page for settings.

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2572]
**Describe the bug**
The hyperlink in the thread's error message should lead the user to a specific setting page, such as the TensorRT Extension (Install Dependency) or Inference Extension (API Key), instead of the default page Settings > My Model.

**Steps to reproduce**
1. Go to Threads; send a message to OpenAI Models (without setting an API key).
2. Click on Settings Hyperlink
3. See error

**Expected behavior**
It should lead to the Settings page and specifically select a certain extension page.

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
looking good on Jan v0.4.10-367 ✅
