### ISSUE TITLE
bug: Wrong toast icon

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2574]
**Describe the bug**
Toast showed failed but icon is green 

https://github.com/janhq/jan/assets/89722390/1ed4dbd1-d5cb-449e-bc7b-2f6bd0d2121c

**Steps to reproduce**
1. Try to run a model that cannot run on your laptop
2. App shows failed to load model
3. See error

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: 0.4.10
- Processor: Apple M1
- RAM: 16GB

**Comment by Van-QA** [comment]
tested and looking good using Jan v0.4.10-361 ✅ 

![Image](https://github.com/janhq/jan/assets/64197333/07e9a17e-d54c-4240-abbf-09443dc9057c)
