### ISSUE TITLE
bug: Cannot remove OpenAI API key

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2577]
**Describe the bug**
I cannot remove my API key

https://github.com/janhq/jan/assets/89722390/e8091856-27a0-494b-80a0-d9da16310d78

**Steps to reproduce**
1. Click on any remote model that has API key
2. Delete API key
3. See error

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: 0.4.10
- Processor: Apple M1
- RAM: 16GB

**Comment by Van-QA** [comment]
New feature would remove this API field, and add a new one in the settings #776
