### ISSUE TITLE
bug: Groq's API key is not saved and response get interrupted while using Groq

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2579]
**Describe the bug**
- Insert Groq API key -> cannot receive full response
- Click on other models -> API key i inserted earlier for Groq is not saved

https://github.com/janhq/jan/assets/89722390/cb033702-9099-48a0-b7bf-b60810057ecf

**Steps to reproduce**
1. Use any groq API key & models
2. See error

**Environment details**
- Operating System: MacOS Sonoma 14.2
- Jan Version: 0.4.10
- Processor: Apple M1
- RAM: 16GB

**Comment by Van-QA** [comment]
New feature would remove this API field, and add a new one in the settings #776
