### ISSUE TITLE
idea: Mac AMD Radeon support

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#2587]
**Problem**
- Context: https://discord.com/channels/1107178041848909847/1222681742712897609
- User with old mac want to use Jan with AMD Radeon GPU, however the current vulkan does not support it

**Success Criteria**
- Just work, we can ask user to test

**Additional context**
- Link to https://github.com/janhq/nitro/issues/476

**Comment by louis-jan** [comment]
Punched back, should be done from cortex-cpp side

**Comment by louis-jan** [comment]
cc @imtuyethan epic request

**Comment by imtuyethan** [comment]
- Closed as dup of https://github.com/janhq/jan/issues/3529
