### ISSUE TITLE
feat: Added ability to copy the download link of a model 

### ISSUE THREAD

**Issue by axetroy** [janhq/jan#2597]
**Problem**

I got a bad network, and I cannot download the model from explorer directly.

So I may want to copy the download link, download it myself, and then import the model.

Or improve the UX of Explorer, It's been stuck at 0% for too long and can't be canceled.

<img width="980" alt="截屏2024-04-03 16 51 39" src="https://github.com/janhq/jan/assets/9758711/507eaea9-1854-4e0c-b6c2-d3694a885c84">

**Success Criteria**

**Additional context**

**Comment by Van-QA** [comment]
Feel free to reopen if any concerns. 🙏
