### ISSUE TITLE
bug: not use it

### ISSUE THREAD

**Issue by shanyunlai** [janhq/jan#2617]
**Describe the bug**

**Steps to reproduce**
Steps to reproduce the beha2024-04-04T08:03:34.553Z [SPECS]::Version: 0.4.102024-04-04T08:03:34.555Z [SPECS]::CPUs: [{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":132937,"nice":0,"sys":150156,"idle":28811234,"irq":11687}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":51218,"nice":0,"sys":81375,"idle":28961515,"irq":9921}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":197171,"nice":0,"sys":174875,"idle":28722062,"irq":16125}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":46859,"nice":0,"sys":44703,"idle":29002546,"irq":2687}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":622625,"nice":0,"sys":529046,"idle":27942421,"irq":26796}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":167171,"nice":0,"sys":160546,"idle":28766375,"irq":9375}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":634250,"nice":0,"sys":550375,"idle":27909468,"irq":29500}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":96140,"nice":0,"sys":146984,"idle":28850968,"irq":2531}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":92609,"nice":0,"sys":79234,"idle":28922250,"irq":2968}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":24562,"nice":0,"sys":24125,"idle":29045390,"irq":796}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":107890,"nice":0,"sys":88984,"idle":28897203,"irq":4671}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":26468,"nice":0,"sys":27390,"idle":29040218,"irq":546}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":151937,"nice":0,"sys":108250,"idle":28833890,"irq":3640}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":212359,"nice":0,"sys":133406,"idle":28748312,"irq":3421}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":140593,"nice":0,"sys":102500,"idle":28850953,"irq":3593}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":162125,"nice":0,"sys":106875,"idle":28825046,"irq":3718}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":146500,"nice":0,"sys":102750,"idle":28844812,"irq":3968}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":149125,"nice":0,"sys":106906,"idle":28838000,"irq":3968}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":163953,"nice":0,"sys":111750,"idle":28818343,"irq":3187}},{"model":"13th Gen Intel(R) Core(TM) i7-13700H","speed":2918,"times":{"user":208265,"nice":0,"sys":130406,"idle":28755375,"irq":3671}}],2024-04-04T08:03:34.558Z [SPECS]::Parallelism: 20,2024-04-04T08:03:34.557Z [SPECS]::Endianness: LE,2024-04-04T08:03:34.556Z [SPECS]::Machine: x86_64,2024-04-04T08:03:34.559Z [SPECS]::Free Mem: 22006132736,2024-04-04T08:03:34.560Z [SPECS]::Total Mem: 34071240704,2024-04-04T08:03:34.560Z [SPECS]::OS Version: Windows 10 Home China,2024-04-04T08:03:34.562Z [SPECS]::OS Release: 10.0.22631,2024-04-04T08:03:34.561Z [SPECS]::OS Platform: win32,vior:

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
hi @shanyunlai, Can you provide more information about the problem you're facing?

**Comment by Van-QA** [comment]
Feel free to reopen if any concerns. 🙏
