### ISSUE TITLE
discussion: Jan Behavior if user quits there are ongoing processes

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2618]
**Description:**
Currently, the Jan app does not notify users of any pending tasks when they attempt to quit or restart the app. This result in interruptions in the users workflow and cause data loss.

**Steps to reproduce:**
1. Open the Jan app
2. Start a task or process that takes a significant amount of time to complete (e.g., model download, generating response, etc.)
3. Attempt to quit or restart the app before the task or process has completed, or any other action that requires reloading or restarting (e.g., Relocate Jan data, Factory reset, other settings that require reloading: quick ask, vulkan ...) 

**Expected behavior:**
The app should display a warning message informing the user that there are pending actions and quitting or restarting will interrupt the process. There should be an option to cancel the quitting or restarting action or proceed with caution.

Sample copy (follow / reuse the reset popup UI): 

> Pending Actions
> 
> You have pending actions [mention the action] that will be interrupted by quitting or restarting the app.
> 
> Do you want to proceed?"
> 
> Cancel: Returns to the app without quitting or restarting
> Proceed: Closes the app and restarts it, interrupting pending actions.
> Note: Interrupting pending actions can lead to data loss. Please save any unsaved work before quitting or restarting the app

Notes:
This is critical as it can lead to data loss and disrupt user flow. It is essential to notify users of any pending actions before quitting or restarting the app to ensure that they can make an informed decision and avoid any potential risk.

This bug should cover all cases where pending actions are interrupted, including quitting the app or restarting the app. The message should be displayed in all cases where pending actions may be interrupted.

**Comment by imtuyethan** [comment]
What is the status of this @Van-QA

**Comment by Van-QA** [comment]
> What is the status of this @Van-QA 

no status, we didn't planned in any sprint. This is a ticket to keep track

**Comment by imtuyethan** [comment]
> > What is the status of this @Van-QA
> 
> no status, we didn't planned in any sprint. This is a ticket to keep track, please put it to sprint whenever pos‌sible

Ok thanks @Van-QA i think this should be a feature request instead of a bug ticket

**Comment by 0xSage** [comment]
Please define the specific processes, because the solution is different on a per process level
