### ISSUE TITLE
feat: Output editing for creative co-writing

### ISSUE THREAD

**Issue by Tominator7** [janhq/jan#2632]
You can currently only easily edit the user input. When using the AI to co-write (fiction for example), it would be very helpful to be able to fix minor mistakes of the AI output on the fly by being able to edit it directly, so the AI will continue from correct context. (Or delete the last paragraph for example, if the AI wrote a finishing paragraph, but you want it to continue from a certain point with new instructions.)
It is currently possible to edit the json files of the threads manually outside Jan, but that is not an efficient or user-friendly workflow.

**Comment by Dalibor-P** [comment]
In addition to this, there should be a "continue" button, which forces the model to continue generating text, without user submitting a new message.

When paired with the feature request above, one could edit the model's response by starting a new paragraph and typing out first few words to steer the generation into a particular direction, and then use the continue button to force the model to continue generating.

**Comment by imtuyethan** [comment]
Thanks for raising this, i'll put this in our plan, i'll mark this ticket as duplicated with #2842
