### ISSUE TITLE
feat: Use Another Jan over LAN

### ISSUE THREAD

**Issue by owenzhao** [janhq/jan#2635]
**Problem**
I have PCs and Macs. However, I found Jan runs more quickly on PC with Nvidia GPU. So when I am using a Mac, I still want to use Jan on the PC. Is that possible Mac's Jan pass question to PC and get answer back instead of run Jan locally?

**Comment by ItsAperoTime** [comment]
Hi ! Same setup for me (a Mac and a Windows PC with a big GPU). Wanted to use Jan UI on my Mac with the service running on my GPU Windows PC. I installed the server on windows with docker/wsl2. On my lan with my Mac I can connect to the API server (1337) but not to the 3000 port UI. I look a little and its appear that some call are to the "server" IP but some are to the localhost. The page stay white blank. (Not sure at all if it's the reason, I'm not a dev and just starting to discover the LLM world).  Thank you and great work ☺️

**Comment by Van-QA** [comment]
Hi there, you might be interested in this part: https://github.com/janhq/jan?tab=readme-ov-file#docker-mode

Note: On windows, please use WSL instead of Windows container because windows container have performance problem + cannot use GPUs
once you deploy it, you can access the Jan web and api from external devices
https://jan.ai/docs/installation/server#step-2-get-jan-server

**Comment by ItsAperoTime** [comment]
> Hi there, you might be interested in this part: https://github.com/janhq/jan?tab=readme-ov-file#docker-mode
> 
> Note: On windows, please use WSL instead of Windows container because windows container have performance problem + cannot use GPUs once you deploy it, you can access the Jan web and api from external devices https://jan.ai/docs/installation/server#step-2-get-jan-server

Thank you for your help Van-QA. Don't know about owenzhao but I my case I have deploy janAI with WSL and docker (with the docker compose of dev and main(the doc says curl the dev)) and I can access to the swagger UI (1337 port) from my devices on the LAN but for the web UI (3000 port) I can't, I have a blank page. However I can access to the web UI from my Windows server (the server host with jan AI on wsl) but cannot with my other computer like my Mac on the LAN. 

I looked in the dev console and see an error like this when the getActiveExtensions page is loader (It seems to try access localhost and not the server's IP in the URL but I don't know if this has to do with the problem or not)
<img width="757" alt="Capture d’écran 2024-04-13 à 14 50 57" src="https://github.com/janhq/jan/assets/63799557/dca96485-0217-46fe-9574-83c0ebe2f1ff">

**Comment by louis-jan** [comment]
Hi @owenzhao, it's possible. You can turn on the API Server and use the exposed `IP://{api_prefix}/chat/completions` endpoint on another Jan client (OpenAI Extension Settings).

**Comment by louis-jan** [comment]
@ItsAperoTime please help update the `API_BASE_URL` from Dockerfile to your real remote server IP address.

**Comment by louis-jan** [comment]
See more here: 
https://discord.com/channels/1107178041848909847/1149558035971321886/1229708106825596999

**Comment by koheiio** [comment]
> Hi @owenzhao, it's possible. You can turn on the API Server and use the exposed `IP://{api_prefix}/chat/completions` endpoint on another Jan client (OpenAI Extension Settings).

That would only allow a single model? would that allow the entirety of the jan backend (model downloading, management, settings, etc)?

If we look at the docker image, we can see it's got a frontend in next, and a backend. I wonder if Jan desktop can be setup to  interface with another backend the similar way: add a URL field in the advanced settings to specify a different backend.

**Comment by koheiio** [comment]
> > Hi there, you might be interested in this part: https://github.com/janhq/jan?tab=readme-ov-file#docker-mode
> > Note: On windows, please use WSL instead of Windows container because windows container have performance problem + cannot use GPUs once you deploy it, you can access the Jan web and api from external devices https://jan.ai/docs/installation/server#step-2-get-jan-server
> 
> Thank you for your help Van-QA. Don't know about owenzhao but I my case I have deploy janAI with WSL and docker (with the docker compose of dev and main(the doc says curl the dev)) and I can access to the swagger UI (1337 port) from my devices on the LAN but for the web UI (3000 port) I can't, I have a blank page. However I can access to the web UI from my Windows server (the server host with jan AI on wsl) but cannot with my other computer like my Mac on the LAN.
> 
> I looked in the dev console and see an error like this when the getActiveExtensions page is loader (It seems to try access localhost and not the server's IP in the URL but I don't know if this has to do with the problem or not) <img alt="Capture d’écran 2024-04-13 à 14 50 57" width="757" src="https://private-user-images.githubusercontent.com/63799557/322206581-dca96485-0217-46fe-9574-83c0ebe2f1ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5Mjg4MTMsIm5iZiI6MTcyMTkyODUxMywicGF0aCI6Ii82Mzc5OTU1Ny8zMjIyMDY1ODEtZGNhOTY0ODUtMDIxNy00NmZlLTk1NzQtODNjMGViZTJmMWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI1VDE3MjgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhODExOTJhZDRiYjQxM2UzNjBmNjgwYzVjMWJiMTc1NGViM2RjZWIyNDM0OGI4ZTE3N2VjZThiMDQ2NDJhZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nZAN4ZgdF9FREhH5qB517hq-8vGJ0ho826b5VxU2xNY">

I'm sorry but this is an entirely different request than OP's. you're looking for troubleshooting and this thread is a feature request.
