### ISSUE TITLE
SUGGESTION: PODMAN INSTRUCTIONS too, as it is the FOSS container application.

### ISSUE THREAD

**Issue by mitcoes** [janhq/jan#2637]
**Problem**
Docker and its tools as Portainer are not FOSS, just their Community editions, that lack features.

When a public administration asks for all FOSS solutions, your software as AI inside a podman container will be offered a lot, and even it is almost 100% compatible with docker, there are some issues, that better be tested and solved from the project if there are any, or show how to use podman instead of docker on the instructions,

**Success Criteria**
There is an alternative to docker almost 100% compatible called PODMAN, with its GUI tools such as podman-dektop and podman-desktop-companion

**Additional context**
It would be nice to add all podman tools needed, as it can be,  nomad-driver-podman, pcp-pmda-podman, cockpit-podman, podman-compose, podman-docker and or others.

**Comment by hiento09** [comment]
Thanks for pointing this out. For those preferring Podman, you can easily set an alias by adding `alias docker='podman'` to your `.bashrc` or `.zshrc` file. This allows you to use Podman with Docker commands. We’ll look into updating our instructions to reflect this option.

Appreciate your suggestion!
