### ISSUE TITLE
feat: A way to remove downloaded models

### ISSUE THREAD

**Issue by owenzhao** [janhq/jan#2638]
**Problem**
This is no way to remove a downloaded model inside Jan. It is better to add a remove model button instead of remove manually in Finder.

**Comment by Van-QA** [comment]
hi @owenzhao, can you try deleting the model using the My Model settings? 
<img width="754" alt="image" src="https://github.com/janhq/jan/assets/64197333/b01b600e-d10c-41e7-a069-588d80d0f922">

**Comment by owenzhao** [comment]
> hi @owenzhao, can you try deleting the model using the My Model settings? <img alt="image" width="754" src="https://private-user-images.githubusercontent.com/64197333/320247437-b01b600e-d10c-41e7-a069-588d80d0f922.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0NzQ5NTQsIm5iZiI6MTcxMjQ3NDY1NCwicGF0aCI6Ii82NDE5NzMzMy8zMjAyNDc0MzctYjAxYjYwMGUtZDEwYy00MWU3LWEwNjktNTg4ZDgwZDBmOTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDA3MjQxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhMDQ0NTAyNDVhNzI0MmYzZmQ0ZGJjZmQ1ZDhhMjYxY2EzOWQzZjEwYzM4ODgyOTA5NDY4ZmI3YmFlYjVhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-Uqi_X6KrpOVhGOFdUh1ekQPbkQSoUONB9YsbJyht4g">

Thank you. I didn't find it in hub. So I suggest add delete model in hub as well.
<img width="1312" alt="截屏2024-04-07 15 29 26" src="https://github.com/janhq/jan/assets/2182896/04797e3f-7d77-485a-b1d2-f79b65ffa208">

The hub and my models are almost the same, why leave both of them?

**Comment by imtuyethan** [comment]
Thanks for your suggestion, we will add this for the next Hub revamp <3
