### ISSUE TITLE
feat: use the LLM to write default thread names

### ISSUE THREAD

**Issue by davidawad** [janhq/jan#2639]
**Problem**
when you create a new thread, the name isn't there, this creates a horde of "new thread" instead of semantically meaningful names to easily find which thread you might want to re-read. 

<img width="448" alt="image" src="https://github.com/janhq/jan/assets/4019054/61137345-65e4-4a4d-a007-9cefebf13b12">

**Success Criteria**
Use the LLM to generate a default thread title. 

This is similar to what GPT / openAI does, it's a good UI feature.

**Comment by Van-QA** [comment]
hi @davidawad,

After the first response from the assistant, the thread title will be auto-generated, if the conversation is clear enough.
![image](https://github.com/janhq/jan/assets/64197333/5b40e485-17c8-4da2-bb3c-d0629dcfe5ed)

Let me know if you have any problems with Jan's auto-generate thread title function.
Many thanks.

**Comment by davidawad** [comment]
I seem to not have had your success (I'm on 4.10). 

Though what you describe is the behavior I would want so it could just be me.

**Comment by Van-QA** [comment]
potentially related to https://github.com/janhq/jan/issues/2694
