### ISSUE TITLE
feat: 'Assistant' as a default name makes sense but could be better

### ISSUE THREAD

**Issue by davidawad** [janhq/jan#2641]
**Problem**
When a new thread is created, I'm able to interact with the AI model of my choice which is great. But every single prompt simply shows Jan as 'Assistant'. We could probably do better than this. 

1. We could just have it say "Jan" which would be a little nicer than 'Assistant' 
2. We could use the name of the model, as it provides more information (especially when referring to old threads later on)
3. We could just make the default name customizable in settings and leave it to the user. 

<img width="557" alt="image" src="https://github.com/janhq/jan/assets/4019054/8a488988-96a3-4e97-b8be-96f87e3c8e85">

**Success Criteria**
My preference would be 2, but 3 would be good as well. 

I'd be happy to make a PR for this as well, if there's any guidance I bet I could pull this one off. 

Thanks as always, I'm a huge fan of the project and am excited to make it better.

**Comment by Van-QA** [comment]
The feature will be available in 0.4.11.
As of now, you can try it using the nightly build https://github.com/janhq/jan?tab=readme-ov-file#download, using the edit threads/edit assistant. (Modify the JSON and app restart is required)
![image](https://github.com/janhq/jan/assets/64197333/bbf75d8b-ddbb-4b6a-8c8c-a2085a1803f5)

Duplicated of https://github.com/janhq/jan/issues/2510
