### ISSUE TITLE
feat: jan.ai should have better support for Mobile

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#265]
**Problem**
- Current Jan.ai landing page does not have good mobile support
- Buttons, etc are not optimized for mobile
- Screenshots do not align well

**Additional context**

- CTA buttons are not mobile optimized
- Hero is out of frame
![Image](https://github.com/janhq/jan/assets/101145494/8261ee3b-101d-4c01-bf09-b0c262b858d4)

- Screenshot is out of frame
![Image](https://github.com/janhq/jan/assets/101145494/79d27559-a3a6-4172-9e72-ef6ac003f6d7)

- Screenshot is out of frame
![Image](https://github.com/janhq/jan/assets/101145494/b9b2b1cc-3188-4eaf-82d7-ec33d841f2eb)

**Comment by 0xSage** [comment]
For the love of llama, charge your phone

**Comment by 0xSage** [comment]
Did the first pass of this. Btns need to be mobile optimized. Closing bc we need to work on site copy as a whole
