### ISSUE TITLE
bug: nightly 0.4.10-367 - conversation breaks down well before max context

### ISSUE THREAD

**Issue by Propheticus** [janhq/jan#2661]
While chatting on this nightly version, with a context size set to 20k tokens, conversations already start to break at the 3rd reply.

When this happens, even new threads are broken at the first prompt and seem to enter an endless loop until stopped.
![image](https://github.com/janhq/jan/assets/6628064/7aa571cf-721a-4564-b181-e7ba0b45dc6f)

```
20240409 09:36:53.563000 UTC 6920 INFO  sent the non stream, waiting for respone - llamaCPP.cc:424
20240409 09:37:00.333000 UTC 6920 INFO  Here is the result:0 - llamaCPP.cc:428
20240409 09:39:40.252000 UTC 14484 INFO  Messages:[
	{
		"content" : "You're a helpful assistant.",
		"role" : "system"
	},
	{
		"content" : "First prompt",
		"role" : "user"
	}
]
 - llamaCPP.cc:211
20240409 09:39:40.252000 UTC 14484 INFO  Stop:[
	"</s>"
]
 - llamaCPP.cc:212
20240409 09:39:40.252000 UTC 14976 INFO  Wait for task to be released:10 - llamaCPP.cc:413
20240409 09:39:40.252000 UTC 14484 DEBUG [makeHeaderString] send stream with transfer-encoding chunked - HttpResponseImpl.cc:535
20240409 09:39:50.817000 UTC 14484 FATAL Unknown error (errno=10053) send node in loop: return on unexpected error(10053) - TcpConnectionImpl.cc:60
```

Win 11 x64,  AMD RX 6800 XT  (Vulkan acceleration), running Mistral 7B Q5

**Comment by Propheticus** [comment]
This does not appear to happen when calling the API endpoint (chat/completions) e.g. from AnythingLLM.

**Comment by hahuyhoang411** [comment]
Can you check your newly added `model.json` file? This might be because of the wrong chat template for Mistral 7B model.

**Comment by Propheticus** [comment]
I compared my model.json to the one that comes with Jan.  My chat template is the same `[INST] {prompt} [/INST]`

Nightly 371 does the same, an shows cross-thread contamination. Here I ask a question in a new thread and the reply continues on a Python topic I had talked about in another:
![image](https://github.com/janhq/jan/assets/6628064/879430ff-a505-42c2-9794-bc72684141e7)

Doing a regen of the answer shows contamination from the summarisation prompt that is done by Jan to create thread titles:
![image](https://github.com/janhq/jan/assets/6628064/625572d5-069b-4d8c-adae-612cd2ceac88)

**Comment by Propheticus** [comment]
nightly-372 as well. By the time I reach question 3, the answers starts repeating the previous answer in a re-worded format:
![image](https://github.com/janhq/jan/assets/6628064/2a189f01-eb5e-4d2a-af85-8388fb10a278)

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
