### ISSUE TITLE
feat: Setting to disable remote APIs

### ISSUE THREAD

**Issue by RichardoC** [janhq/jan#2665]
**Problem**
I'd like there to be a setting in a config file which disables remote APIs such as the OpenAI models. This means that users can download and user local only models, but not remote APIs.

**Success Criteria**
A value can be set in a config file on disk which disables all remote APIs from being available

**Additional context**
It's great that folks are able to run models locally, and for places where only local models can be used, it should be possible to disable non-local models from being shown.

**Comment by davidawad** [comment]
I'd go even further and argue that "open source models only" should probably be the default behavior.

**Comment by RichardoC** [comment]
Yeah, not sure if this needs another request but there are certain types of models (e.g. code gen ones) which aren't appropriate for all users and it'd be good to disable those for them

**Comment by imtuyethan** [comment]
Thank you for your suggestion. We are refactoring inference engines right now (including options to disable remote models). Please stay tuned for the change!
