### ISSUE TITLE
feat: Support Cohere extension

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#2684]
**Problem**
Command R+ is the best open-source model that can surpass GPT-4 in some benchmarks. However, the model is 104B so normal local PC can't run this model.

We should have an API extension for the model.

**Success Criteria**
Easily chat with Command R+ in Jan like ChatGPT

**Additional context**
Link: https://docs.cohere.com/reference/about

**Comment by Van-QA** [comment]
Testing failed on Jan v0.4.12-398

- Unable to chat when stream is on :x:
![image](https://github.com/janhq/jan/assets/64197333/38a3a617-a083-436e-aade-127ae57c77bc)

- Incorrect URL to the API Key :x:
![image](https://github.com/janhq/jan/assets/64197333/e5de0221-048c-4c3f-94a7-4df79aa5ced8)

Moving back to planned, please help us correct above issues @Inchoker

**Comment by Van-QA** [comment]
Waiting to be resolved by dev team

**Comment by Van-QA** [comment]
Working as of Jan v0.4.12-435
