### ISSUE TITLE
bug: nightly-372 Regenerated answers are contaminated with thread title summary prompt

### ISSUE THREAD

**Issue by Propheticus** [janhq/jan#2689]
Regenerating answers leads to strange output
![image](https://github.com/janhq/jan/assets/6628064/dccf78a1-e507-4a24-b350-8f6294750172)
![image](https://github.com/janhq/jan/assets/6628064/73268be5-fa5e-4bd6-94ac-8ed4667dc590)

Using Mistral 7B Instruct v0.2 Q5_K_M  with chat prompt `[INST] {prompt} [/INST]`  running on Vulkan acceleration.

**Comment by louis-jan** [comment]
sus: latest nitro cache issue & gibberish response. Investigating

**Comment by Propheticus** [comment]
I can no longer reproduce this in nightly Jan v0.4.11-386
