### ISSUE TITLE
bug: updating to v0.1.3 crashes

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#269]
**Describe the bug**
see title

**To Reproduce**
1. Open app on v0.1.2
2. Opt into download
3. see download bar progress
4. see error: 
<img width="323" alt="image" src="https://github.com/janhq/jan/assets/69952136/0a71c01c-e261-47c2-b577-1ef16c961214">
5. click ok
6. stuck on v0.1.2
7. REstarting app does not work.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac metal sonoma, 16gb

**Additional context**

**Comment by louis-jan** [comment]
Should be addressed in 0.1.3 release. Mac app is notarized.

**Comment by louis-jan** [comment]
Previous versions are not released with proper code signing & app id. Let's deprecate < 0.1.3 since signed & verified from this version.

**Comment by 0xSage** [comment]
closing this as a `won't fix` since future versions hopefully won't have this issue
