### ISSUE TITLE
bug: Nightly 372 new thread titles are not saved after closing Jan on Mac and some older ones disappeared

### ISSUE THREAD

**Issue by vlbosch** [janhq/jan#2694]
**Describe the bug**
When starting a new thread and interacting with the model, I can see after the first prompt the thread-title changed. However, after closing and reopening Jan, the thread-title goed back to "New thread".

I also noticed that in some old threads, that did had a title, the title is reverted to "New Thread" as well, but not on all chats.

**Expected behavior**
The generated title being saved and correctly reflected after reopening Jan, for both old and new threads.

**Screenshots**
If applicable, add screenshots to help explain your issue.
<img width="281" alt="Scherm­afbeelding 2024-04-11 om 14 40 24" src="https://github.com/janhq/jan/assets/8345602/975238aa-2f0b-4979-84ea-4c027ac80d43">

**Environment details**
- Operating System: macOS 14.4
- Jan Version: 0.4.10-372
- Processor: M3 Max 40C
- RAM: 128GB
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Comment by Van-QA** [comment]
Thank you, I was able to reproduce the issue intermittently:

When the Jan app was not able to generate the title of the previous thread, the new thread with throw error. And restarting the Jan app will wipe the title of all threads.

![image](https://github.com/janhq/jan/assets/64197333/df019e61-9325-49e1-bb76-786a5af2e79a)

![image](https://github.com/janhq/jan/assets/64197333/337ec13d-4b04-4184-a3e7-dcd738edffcc)
[app.log](https://github.com/janhq/jan/files/14946639/app.log)

**Comment by Van-QA** [comment]
attaching the app.log for reference: 
[app.log](https://github.com/janhq/jan/files/14977893/app.log)

**Comment by Van-QA** [comment]
![title](https://github.com/janhq/jan/assets/64197333/fb601b33-3793-41b4-b444-6312b7e876fc) attached video and app.log 
[app.log](https://github.com/janhq/jan/files/15009663/app.log)
