### ISSUE TITLE
bug: -ngl settings should be visible by default in the GUI

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2697]
**Describe the bug**
Context length and NGL are two critical settings that can help users overcome issues with loading heavy models on their machines, such as hogging or OOM errors. However, not all users may be aware of these settings as they are not readily visible in the GUI by default. Editing the model.json and threads.json files can also be challenging for some users

**Expected behavior**
When starting a new thread with local models, the -ngl settings should be accessible via the GUI

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by hahuyhoang411** [comment]
Also, can we make a default config `-ngl` for users with less memory? For example:

User with:
GPU: 8GB VRAM
RAM: 32GB RAM

Normally, 13B models would need `~8GB` but we can offload half of the `-ngl` to RAM instead. This will reduce the memory usage on the GPU.

**Comment by louis-jan** [comment]
A default value of 20 would be great

**Comment by louis-jan** [comment]
Update: 
Model's size > VRAM -> 20, otherwise 35
