### ISSUE TITLE
feat: Enqueue requests from UI

### ISSUE THREAD

**Issue by lorefnon** [janhq/jan#2704]
Hello, thanks for open sourcing Jan. Started using it recently, and it looks really great. 

**Problem**
When a generation is ongoing, entering a new prompt causes the generation to be interrupted. It would be nice if subsequent prompts to the same model be queued instead of resulting in interruptions.  

**Success Criteria**
It would be nice if we could queue up a couple of prompts and then get back to the responses after a while.

**Comment by Van-QA** [comment]
related to https://github.com/janhq/jan/issues/752
