### ISSUE TITLE
bug: after running Jan, OS freezes for 5-10 seconds every 20 seconds or so

### ISSUE THREAD

**Issue by chlimouj** [janhq/jan#2708]
**Describe the bug**
OS will completely freeze for several seconds at a time, and it continues indefinitely until I a) reboot, or b) uninstall/reinstall nvidia drivers.

**Steps to reproduce**
1. Run Jan for several hours (not necessarily interacting the entire time)
2. Notice freezes, even after closing Jan

**Expected behavior**
No freezes, at least stop feezing after closing Jan (seems like it puts the nvidia driver in a strange state)

**Screenshots**
N/A

**Environment details**
- Operating System: Win10
- Jan Version: 0.4.10
- Processor: [e.g., i7 5950HQ
- RAM: 32GB
- dual GTX980M (SLI), tried several recent version of nvidia drivers

**Comment by Van-QA** [comment]
hi @chlimouj, can you give us the app.log? many thanks

**Comment by chlimouj** [comment]
Withdrawing - seems this is a driver issue on my machine
