### ISSUE TITLE
feat: I can group threads in folders

### ISSUE THREAD

**Issue by WainLai** [janhq/jan#2709]
The list of threads gets too long very fast if I try the same prompt with several different models.

A possibility to group threads in folders (similarly to bookmarks in web browsers) would be a great way to arrange threads and make them easier to access.
It would be great help when comparing models' suitability for given tasks.

**Comment by FilterJoe** [comment]
I've only used Jan for a few days and I generated so many threads that I can't find what I'm looking for. Folder structure would be great. I've created an awkward folder structure myself by creating folders within the "threads" folder and moving individual threads to these folder. Do do this I have to awkwardly quit then restart Jan every time I want to switch to a different folder plus having to drop to he OS to moving contents of folders into and out of the threads folder.

**Comment by 0xSage** [comment]
dupe #2956
