### ISSUE TITLE
bug: [Android app] no AI available, blank page

### ISSUE THREAD

**Issue by darkdidi** [janhq/jan#2710]
**Describe the bug**
Download Jan on play store, launcher it and no AI available. Only a blank page.

**Expected behavior**
Expect to see différents AI models to download or local LLMS to assign

**Screenshots**
![Screenshot_20240413-074646.png](https://github.com/janhq/jan/assets/36579078/da6304ee-7ebf-47f3-a04a-de85923d7934)

**Environment details**
Runs on nothing OS 2, Wifi, french
Android 14, more than 50G Space free

**Additional context**
Seems that im not the only one based on thé comment on the play store page

**Comment by Van-QA** [comment]
Sorry, we are no longer maintaining the Jan mobile app. We will deprecate it soon, thank you for your time.
