### ISSUE TITLE
bug: Delist Jan mobile apps

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2720]
We should consider delisting the mobile apps (one of our oldest experiments doing SD locally).

https://apps.apple.com/us/app/jan-on-device-ai-cloud-ais/id6449664703

The app store optimization is not good at this point, it also only does stable diffusion, and looks like a scam relative to our core product.

**Comment by hiento09** [comment]
![image](https://github.com/janhq/jan/assets/136591877/93928057-bde1-4aa9-8050-7254f4ecbaaa)
Done for Apple store @0xSage , It takes about 24 hours for Jan app to be unavailable on apple store.

**Comment by hiento09** [comment]
Done for android app 
![image](https://github.com/janhq/jan/assets/136591877/89ea371f-aa14-48d8-8fc1-e67b0bc4f5a0)
