### ISSUE TITLE
epic: Refactoring of Remote API Extensions (Mistral, Cohere, etc)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2721]
## Motivation
Model from API providers should be more clarifier

## Specs
https://www.notion.so/jan-ai/Refactoring-of-Remote-API-Extensions-Mistral-Cohere-etc-8638a1fa26ca48f3b57822157c11152a?pvs=4

### In-scope
- Cohere extension https://github.com/janhq/jan/issues/2686
- Anthropic extensions https://github.com/janhq/jan/issues/2777
- Deepinfra extensions https://github.com/janhq/jan/issues/2717
- Openrouter https://github.com/janhq/jan/issues/2685

**Comment by bogorad** [comment]
looks like it broke OpenRouter api. where are the new setup instructions?

**Comment by dandv** [comment]
I get "Page not found" on that Notion page.

**Comment by Van-QA** [comment]
please use https://jan.ai/docs/remote-models/anthropic for the ava‌‌ilable remote mode‌ls list
