### ISSUE TITLE
bug: Ollama API broken with new update

### ISSUE THREAD

**Issue by jonathanhecl** [janhq/jan#2736]
Before the update Ollama works, now it does not. Using the same configurations that already worked for ollama and the models.

![image](https://github.com/janhq/jan/assets/1691623/8cf479d8-b5eb-471b-a162-43bd5228baec)

**Message: Invalid API key. Please check your API key from Settings and try again.**

**Comment by Van-QA** [comment]
hi @jonathanhecl, can you check the model.json, and see which engine you are using? and based on that, provide the API key to the correct engine settings 
![image](https://github.com/janhq/jan/assets/64197333/9f47ba10-b818-440a-8752-08954d152e67)

**Comment by jonathanhecl** [comment]
I try change the endpoint in the settings, and now works. Thanks

![image](https://github.com/janhq/jan/assets/1691623/59cf8f3f-58e3-4a6b-9b9d-fb4c79634bb4)

Before I would edit openai.json on jan/engines folder, but don't remember I should need to edit in settings too.
