### ISSUE TITLE
Add a folder path where Jan stores models.

### ISSUE THREAD

**Issue by Mefiseru** [janhq/jan#2739]
**Pages**
Folder to your models -> default -/> choose specified.

**Success Criteria**
Thiss will show people where are models stored, to create links or manage it.

**Additional context**
Right now, Jan doesn't even give you the ability to install it some where else. this will at least give an opportunity to user to choose or delete models folder how he wants  (we doesn't even know where they are stored)

**Comment by Van-QA** [comment]
hi @Mefiseru,
You can try this settings that allow opening the Jan data folder 🙏 

<img width="610" alt="image" src="https://github.com/janhq/jan/assets/64197333/de511de7-c001-423a-89b4-e9a4174b3bca">

**Comment by Van-QA** [comment]
Feel free to reopen if there are more concern 🙏

**Comment by rafaelmadeira** [comment]
I set this to a folder in my D:\ data drive, but it keeps downloading the models to the root C:\ user folder, where I don't have enough space to download the model I want.
