### ISSUE TITLE
bug: cannot seem to add more Openrouter remote models

### ISSUE THREAD

**Issue by lactoseintolerant** [janhq/jan#2752]
Previously, I had added several remote models from Openrouter (Claude, Mistral Large, etc.) using the instructions in the documentation.  I tried adding new models (the WizardLM2 and Mixtral 8x22B Instruct) in the same way, but they failed to show up in my remote model list. I tried adding another random old model as a control, Mistral Tiny, but that also failed to show up. I reverted back one version and repeated with no success.

Did I mess something up, or do all the models have to be on some approved list? Or is there a maximum number of remote models that can appear in the selection list? Any suggestions? Thank you.

Edit: I realize you guys are in the middle of refactoring the whole remote model stuff, so if the answer is to hang on and sit tight, that's cool, too.

**Comment by muchomuchacho** [comment]
Make sure to also edit the name in model.json, it's not mentioned in the docs but that will prevent it from showing up in your hub search. Here's what I have:

```json
{
  "sources": [
    {
      "filename": "openrouter",
      "url": "https://openrouter.ai/"
    }
  ],
  "id": "microsoft/wizardlm-2-8x22b",
  "object": "model",
  "name": "WizardLM-2-8x22b",
  "version": "1.0",
  "description": "This is a 65k context fine-tune of Mixtral-8x22b. It excels at... everything.",
  "format": "api",
  "settings": {},
  "parameters": {},
  "metadata": {
    "tags": ["MoE", "8x22b", "65k Context Lenght"]
  },
  "engine": "openai"
}
```

It works fine once added the API Key, URL, etc.

**Comment by lactoseintolerant** [comment]
I had the name changed but had a missing punctuation mark in the master getting copy-pasted somehow...sigh. Closing.
