### ISSUE TITLE
feat: Model Search should give huggingface results as a fallback

### ISSUE THREAD

**Issue by davidawad** [janhq/jan#2755]
**Problem**
This could be my ignorance to how the file formats work, but I would expect that if I search on Jan for a model (like llama3, I'd expect to have places like huggingface searched for models. (in this case I wanted to try the new llama models)

<img width="1201" alt="image" src="https://github.com/janhq/jan/assets/4019054/6e304838-339e-4a23-8df2-9abf79617f57">

**Success Criteria**
Huggingface should be a fallback so that if I know the name of any given model I might want to use, jan should be able to pull down the gguf, if I understand correctly this is standardized correctly within HF so it should be doable.

**Comment by Van-QA** [comment]
hi @davidawad, with the latest nightly Jan v0.4.11-386, you will be able to search via Hugging Face URL for Hugging Face mode id 🙏 
![image](https://github.com/janhq/jan/assets/64197333/8c0ec8b0-5295-4b79-aa35-aeaed09a4f90)

**Comment by davidawad** [comment]
That's great to hear! 

Could I PR some text around that feature as it looks like it could be really useful.

**Comment by Van-QA** [comment]
Thank @davidawad, I would recommend trying out the feature first (using Jan nightly) and providing feedback if there are any issues or areas for improvement. 
As it is still in the testing phase, your input will be valuable in making the feature the best it can be. After that, your PR be a sneak peek for those who want to try early before the official release next Thursday 🙏
