### ISSUE TITLE
feat: Jan has clipboard and shortcut access to AI prompts

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2757]
I would like to request features that enable using clipboard functions to access the AI and using keyboard shortcuts to initiate AI prompts.

## Suggested implementation
- Clipboard Monitoring: Allow the app to read from and write to the clipboard when specific conditions are met.
- Shortcut Keys: Enable customizable keyboard shortcuts that trigger specific AI responses directly in the app.

[Rodrigo Paiva](https://twitter.com/rodrigopaiva)'s feature request:
<img width="590" alt="Screenshot 2024-04-19 at 17 22 29" src="https://github.com/janhq/jan/assets/159995642/ae7f0094-238c-467c-a55d-91139dbb7ff5">

**Comment by 0xSage** [comment]
@eckartal create separate tickets if it is mulitpel requests pls. 
1. keyboard shortcuts: can you elaborate " trigger specific AI responses ". From which app, Jan? Or a 3rd party app. 
- If Jan, then we are discussing keyboard shortcuts #3555 
- If from external app, then its a ubiquitous ai convo

2. reading from clipboard would be accessibility?

**Comment by aldinokemal** [comment]
It would be great because, as far as I know, there is no Windows app like BoltAI that can do this.

**Comment by imtuyethan** [comment]
- Related #3944

**Comment by imtuyethan** [comment]
Closed as a sub-task of: https://github.com/janhq/jan/issues/3944
