### ISSUE TITLE
feat: Ready-to-use document library

### ISSUE THREAD

**Issue by kalle07** [janhq/jan#2761]
**Problem**
every time i want talk to a document i must search in my folders and load it
if i have found i put it into the chat...
than its needs time to prepare the document every time i use it ...

**Success Criteria**
document library  ;)

and maybe iyou can make some progressbar that i can estimate how long that book need to prepared
i saw that one pdf is only prepared on one core you can do it on all ?
or at least if i choose 4 pdf at the same time (if we have a library) use 4 cores  ?

**Comment by imtuyethan** [comment]
- Closed as a sub-issue of https://github.com/janhq/cortex-internal/issues/20
