### ISSUE TITLE
bug: API Tutorial does not match expected output

### ISSUE THREAD

**Issue by Tadashi-Hikari** [janhq/jan#2763]
**Describe the bug**
Response to template code is incorret

**Steps to reproduce**
1. Run a Jan.ai server using the tinyllama-1.1b model
2. Go to https://jan.ai/api-reference
3. Select either Python or Clojure as the target language
4. Scroll down to the chat completions
5. Copy the template code directly into an IDE and run

**Expected behavior**
A simple JSON response, matching the response shown on the API Reference page

**Actual behavior**
The returned response data is included in the attached text files

**Environment details**
- Operating System: Windows 11
- Jan Version: 4.11  
- Processor: Intel Core i7
- RAM: 32GB
- GPU: Nvidia 2080 TI (12GB)
- VSCode, Behavior happened with multiple models. Using GPU acceleration & Nitro extension

**Logs**
See attached text 
[clojure response.txt](https://github.com/janhq/jan/files/15049818/clojure.response.txt)
[python response.txt](https://github.com/janhq/jan/files/15049819/python.response.txt)
![Screenshot 2024-04-20 173904](https://github.com/janhq/jan/assets/17326267/952d4f9e-8201-4aab-8058-6d8854b7fa48)
![Screenshot 2024-04-20 173952](https://github.com/janhq/jan/assets/17326267/d745a43b-429d-4589-a7ca-0f2e7f9e4d38)

**Comment by Propheticus** [comment]
This is a streaming response. Set stream false and then you get all content in one go instead of separate tokens.

**Comment by Tadashi-Hikari** [comment]
Is there a note we can make on the API section of the website to show this?

**Comment by louis-jan** [comment]
Thank you for the API example bug report. We will update the example request.
