### ISSUE TITLE
what's this?

### ISSUE THREAD

**Issue by namutin** [janhq/jan#2764]
https://github.com/janhq/jan/assets/130255942/5b05e6f2-56b2-43c0-88ff-8328b7008354

**Comment by namutin** [comment]
Something isn't right.

**Comment by louis-jan** [comment]
@namutin Could you please share the version you are on?

**Comment by namutin** [comment]
Jan-v.0.4.11-388

一回消して、もう一回やり直すとこうなります。

**Comment by namutin** [comment]
-
