### ISSUE TITLE
bug: Engine settings are not being updated while switching between models on the API Server screen

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#2767]
**Describe the bug**
Engine settings are not being updated while switching between models on the API Server screen.

e.g. I selected a remote model from the thread screen. Then, I went to the API Server screen and selected a local model, and the Engine Settings are now shown.
<img width="1312" alt="Screenshot 2024-04-21 at 16 59 17" src="https://github.com/janhq/jan/assets/133622055/4acb1188-305f-476e-bca2-38cd3076a00d">

**Steps to reproduce**
1. Go to Thread
2. Select a remote model
3. Go to API Screen
4. Select a local model
5. See Error

Even switching models in the API screen can also reproduce.

**Expected behavior**
When switching to another model, the engine settings should reload and display the corresponding settings from model.json.

**Screenshots**
If applicable, add screenshots to help explain your issue.

**Environment details**
- Operating System: [Specify your OS. e.g., MacOS Sonoma 14.2.1, Windows 11, Ubuntu 22, etc]
- Jan Version: [e.g., 0.4.3]
- Processor: [e.g., Apple M1, Intel Core i7, AMD Ryzen 5, etc]
- RAM: [e.g., 8GB, 16GB]
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]

**Logs**
If the cause of the error is not clear, kindly provide your usage logs:
- `tail -n 50 ~/jan/logs/app.log` if you are using the UI
- `tail -n 50 ~/jan/logs/server.log` if you are using the local api server
Making sure to redact any private information.

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
