### ISSUE TITLE
bug: memory utilization always at 99% (incorrect based on Activity Monitor)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#277]
**Describe the bug**
Bottom bar status shows Memory usage is always 99%. 
My Activity Monitor shows lower mem pressure however. 
Are we counting swap space util as well?

**To Reproduce**
1. Open the app, don't use any models
2. Open Activity Monitor and compare. See following screenshot.

**Expected behavior**
I expected AM vs Jan to match.

**Screenshots**
<img width="886" alt="image" src="https://github.com/janhq/jan/assets/69952136/89c1d9f6-0436-4505-974e-af2030f6afb8">

**Desktop (please complete the following information):**
 - OS: iOS sonoma
 - Jan v0.1.3

**Device (please complete the following information):**
 - Device: Mac M1, 16GB mem

**Additional context**

**Comment by louis-jan** [comment]
It is also count cached files, the same result as `Usage: System Activity Monitor - top search result with keyword "stats"`

**Comment by 0xSage** [comment]
Is it possible to only show memory being used by Jan? 
Always showing memory utilization at 99% doesn't tell the user much.
How can we get the memory metric to dynamically reflect when model is started/inferencing is occuring?

**Comment by louis-jan** [comment]
Yeah, it is possible. The fix is here for a better formula #309. It should be `active/total`: used actively (excl. buffers/cache).
