### ISSUE TITLE
feat: Jan supports model file formats except for GGUF too

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2774]
**Problem**

**Success Criteria**

**Additional context**

<img width="521" alt="Screenshot 2024-04-22 at 11 11 12" src="https://github.com/janhq/jan/assets/159995642/e8c090e0-b029-416e-8c26-6624c9932909">

**Comment by Van-QA** [comment]
Duplicated of: https://github.com/janhq/jan/issues/1056 
We will implement this soon, stay tuned :pray:
