### ISSUE TITLE
feat: Jan supports Google and Claude APIs

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2777]
To enhance the functionality and interoperability of Jan, I propose adding support for both Google and Claude APIs. 

This will allow users to integrate Jan more seamlessly with a wider range of services and technologies.

**Comment by Van-QA** [comment]
Reopen this due to the issue with Anthropic recently :x:
![image](https://github.com/janhq/jan/assets/64197333/79183c0d-1b8f-4ac5-bb26-275def2a72bc)
