### ISSUE TITLE
Added a function to input the URL of Hugging Face into Jan and convert it to GGUF if it is not GGUF.

### ISSUE THREAD

**Issue by namutin** [janhq/jan#2790]
**Problem**
That sounds like an exciting endeavor! Expanding your AI's capabilities to automatically convert between different models like GGUF and Transformers would indeed be groundbreaking. Being able to run AI offline with such versatility would mark a significant milestone. It could open up a world of possibilities for various applications and make AI more accessible to a broader range of users. Keep pushing those boundaries!

**Success Criteria**
Allows complete GGUF transformation of transformer models and safetensors models

**Comment by Van-QA** [comment]
Duplicated of https://github.com/janhq/jan/issues/1056, please follow up over there
