### ISSUE TITLE
feat: Allow users to favorite conversations from the left panel 

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2792]
A feature for favorite conversations is in the left panel - a dedicated tab to display these favorites for quick access.

Implementation suggestions:

- Add a star icon next to each conversation in the left panel, which users can click to mark conversations as favorites.
- Favorites tab creation: Create a new tab within the main navigation area that filters and shows only the conversations marked as favs.

<img width="586" alt="Screenshot 2024-04-24 at 01 49 08" src="https://github.com/janhq/jan/assets/159995642/8236a26a-dcd6-4dbb-bd5f-6d292329057b">

https://twitter.com/soyhenryxyz/status/1782820432531583477

**Comment by iamhenry** [comment]
🙏🏽

**Comment by imtuyethan** [comment]
I'll close as duplicated & make sure to include it in https://github.com/janhq/jan/issues/3133
