### ISSUE TITLE
feat: Jan App has a shortcuts to open app logs

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2796]
**Problem**

I'm always frustrated when I have to get logs. It's obscure and a multi step process: 
1. open finder
2. go to disk > nicole > logs > open

I feel like logs files should be a lot more accessibel , easy to open.

Maybe we can put a shortcut in the System Monitor tray. 
But definitely at least, put it in Advanced Settings > next to Clear Logs. 
Users are prob like, which logs am I clearing ?

**Success Criteria**

**Additional context**

**Comment by 0xSage** [comment]
@imtuyethan can we please get this in. incredibly frustrating to troubleshoot our app otherwise.

**Comment by imtuyethan** [comment]
ADD APP LOG ICON IN SYSTEM MONITOR:

Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=5643-51626&t=6i1M3v0HGOMbWAzl-4
![Screenshot 2024-07-07 at 6 50 20 PM](https://github.com/janhq/jan/assets/89722390/e5c61378-c920-440c-90a4-053f509509e0)

cc @urmauur
