### ISSUE TITLE
bug: Nightly is stuck on 389

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2799]
**Describe the bug**

**Steps to reproduce**
1. I'm on patch 389
2. Currently nightly is 392. 
3. I restart jan
4. install updates
5. restart jan
6. still stuck on v0.4.11-389

**Comment by 0xSage** [comment]
Hm.. nvm the pattern seems to be: 

1. be on patch 389
2. install updates
3. app restarts
4. app is still on 389
5. leave the app alone for 2 minutes
6. app auto restarts, shows the correct version

**Comment by Van-QA** [comment]
Unfortunately, we were unable to reproduce the issue, we will continue to observe this in the future, thank you

**Comment by Propheticus** [comment]
This might be a virusscanner running the (new, unknown, untrusted) app in a sandbox first to monitor for malicious behaviour, before allowing it to play outside the sandbox.
