### ISSUE TITLE
Fully compatible with Phi-3

### ISSUE THREAD

**Issue by namutin** [janhq/jan#2800]
Please support AIPhi-3, which is released by Microsoft and exceeds Llama3-8B. completely

**Comment by Van-QA** [comment]
Tested and not able to find the model Phi-3-mini-4k-instruct-q4 anywhere in the repo. Need further investigation from @hahuyhoang411. Many thanks

**Comment by hahuyhoang411** [comment]
currently, phi-3 is not well supported by llama.cpp. Please stay tuned

https://github.com/ggerganov/llama.cpp/pull/7225
