### ISSUE TITLE
Fully compatible with stabilityai/stablelm-2-12b-chat-GGUF

### ISSUE THREAD

**Issue by namutin** [janhq/jan#2803]
Please make stabilityai's light and high performance model stabilityai/stablelm-2-12b-chat-GGUF fully compatible with Jan.

**Comment by 0xSage** [comment]
@hahuyhoang411 do you know what the incompatibility was?

**Comment by louis-jan** [comment]
[app.log](https://github.com/user-attachments/files/16778592/app.log)

**Comment by 0xSage** [comment]
@louis-jan what was the underlying issue?

**Comment by dan-homebrew** [comment]
I am closing this issue as it's a very outdated model.
