### ISSUE TITLE
bug: Docker brings a blank black website when navigating to IP

### ISSUE THREAD

**Issue by zytoh0** [janhq/jan#2806]
**Describe the bug**
I've attempted to get Jan running on-prem on a remote server and regardless of what browser I use it returns the favicon and just a blank black site. Same issue as: https://github.com/janhq/jan/issues/2005 This hasn't been fixed. Tried running both "docker compose --profile cpu-fs up -d" and "docker compose --profile gpu-fs up -d" both same results.

**Steps to reproduce**
I tried following the steps in the repo as well as https://jan.ai/docs/server-installation/onprem i.e. an additional step of "curl https://raw.githubusercontent.com/janhq/jan/dev/docker-compose.yml -o docker-compose.yml" both results in the same result.

on doing "sudo docker compose --profile cpu-fs up -d"
[+] Running 5/5
 ✔ Network jan_vpcbr              Created                                                                                                                              0.1s 
 ✔ Volume "jan_minio_data"        Created                                                                                                                              0.0s 
 ✔ Container jan-minio-1          Started                                                                                                                              0.1s 
 ✔ Container jan-app_cpu_fs-1     Started                                                                                                                              0.1s 
 ✔ Container jan-createbuckets-1  Started                                                                                                                              0.0s

On doing "sudo docker stats"
[+] Running 15/15
 ✔ minio Pulled                                                                                                                                                       10.0s 
   ✔ 818905591bbf Pull complete                                                                                                                                        3.3s 
CONTAINER ID   NAME               CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O        PIDS
54f8834ef7c2   jan-app_cpu_fs-1   0.00%     449.2MiB / 503.3GiB   0.09%     246kB / 45.6kB    8.19kB / 875MB   35
dcd0f05b49a0   jan-minio-1        0.16%     152MiB / 503.3GiB     0.03%     17.5kB / 6.36kB   0B / 983kB       43

**Screenshots**
![image](https://github.com/janhq/jan/assets/90326544/6dff7430-0168-4d40-bc82-64187dbb9832)

**Environment details**
- Operating System:
- PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
- Jan Version: latest as of 24/4/2024
- Processor:
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 57 bits virtual
  Byte Order:            Little Endian
CPU(s):                  112
  On-line CPU(s) list:   0-111
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz
    CPU family:          6
    Model:               106
    Thread(s) per core:  2
    Core(s) per socket:  28
    Socket(s):           2
    Stepping:            6
    BogoMIPS:            4000.00
- RAM:
                total        used        free      shared  buff/cache   available
Mem:           503Gi       4.3Gi       405Gi       6.0Mi        93Gi       495Gi
Swap:          8.0Gi          0B       8.0Gi
- Any additional relevant hardware specifics: [e.g., Graphics card, SSD/HDD]
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.161.08             Driver Version: 535.161.08   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          Off | 00000000:65:00.0 Off |                    0 |
| N/A   43C    P0              61W / 300W |      0MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          Off | 00000000:CA:00.0 Off |                    0 |
| N/A   39C    P0              66W / 300W |      0MiB / 81920MiB |     24%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by louis-jan** [comment]
@zytoh0 I guess you have to update `API_BASE_URL` as your remote server IP
Please see this https://discord.com/channels/1107178041848909847/1149558035971321886/1229708106825596999
