### ISSUE TITLE
RAG - How to set up to enable model to load picture or word document 

### ISSUE THREAD

**Issue by zlzzzlll** [janhq/jan#2811]
Can you tell me how to set it up so that I can drag in a picture or word document and have the model recognize it and work? Thank you for your help.

**Comment by zlzzzlll** [comment]
> 我认为你必须使用像 Llava 这样支持视觉的 VLM。或者找一个支持的型号。
There is no option to add a document, you said Llava, can not add a document!

**Comment by louis-jan** [comment]
@zlzzzlll, please turn on the Experimental Feature from the settings page then try Llava.

**Comment by Van-QA** [comment]
Feel free to reopen if any concerns 🙏 
Note: the feature only works with Image / PDF
