### ISSUE TITLE
bug: Thread - Long Model Responses Cause UI Lag and Sluggish Scrolling

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2818]
**Describe the bug:**
When the response from the model is long, the UI becomes laggy, particularly due to the scroller while generating the message

**Steps to reproduce:**
1. Using any model
2. Input a query that generates a long response from the model (e.g. a large amount of text).
3. Observe the UI

**Expected behavior:**
The UI should remain responsive and smooth, even when handling long responses from the model. Scrolling through the response should be seamless and not laggy.

**Additional information:**
The laggy UI makes it difficult for users to quickly review and interact with the response. This issue is particularly noticeable when scrolling through long responses, as the UI can freeze or stutter, making it hard to navigate the response efficiently. Optimizing the UI  for handling long responses would greatly improve the user experience.

**Screenshots**
![responseLoad](https://github.com/janhq/jan/assets/64197333/d47dcda4-6f72-47b2-bfa7-779f667233f7)

**Comment by skalien** [comment]
Hi. Is this issue fixed?
I am still facing this issue on the macos version.
Jan v0.4.12.

**Comment by Van-QA** [comment]
hi @skalien, the issue was fixed but only in our nightly build at the moment, you can try it out early, or wait until stable 0.4.13, thank you 🙏https://github.com/janhq/jan?tab=readme-ov-file#download
