### ISSUE TITLE
bug: v0.4.12 Every new thread created is reset to 2048 token context length

### ISSUE THREAD

**Issue by Propheticus** [janhq/jan#2821]
Like the title says the default value is set for every new thread. After picking a model where the model.json defines a ctx_len of e.g. 20000, the context is still set to 2048. After you manually adjust this and load the model, when you open a new thread the default is still reset to 2048. Dragging the slider in the new thread kills nitro and unloads the model. 
![image](https://github.com/janhq/jan/assets/6628064/4b9f7c21-069d-4930-8eb8-e5f512350662)

Related? : https://github.com/janhq/jan/blob/dev/extensions/inference-nitro-extension/resources/default_settings.json

**Comment by louis-jan** [comment]
Hi @Propheticus, this is a minor update to ensure that new models with large context lengths (>8k) do not crash low-spec devices.

We will add a global setting to the extension to check device specs using heuristics to have proper settings.

**Comment by Propheticus** [comment]
I can understand that reason. The main issue I had is that it's done silently for new threads, even after overriding it manually when loading the model. Without checking the model's engine parameters you wouldn't know your setting was undone.

**Comment by louis-jan** [comment]
> I can understand that reason. The main issue I had is that it's done silently for new threads, even after overriding it manually when loading the model. Without checking the model's engine parameters you wouldn't know your setting was undone.

Yeah, that sucks. We'll address this in the next release.

**Comment by Van-QA** [comment]
should be resolved via https://github.com/janhq/cortex/issues/617

**Comment by carbongo** [comment]
Every time I start a thread, I open the model settings, move the context slider to its maximum, and adjust the max tokens to match the documentation. However, the config is now mainly used to bypass a limitation intended for low-spec computers, but it can't preserve my settings, which is disappointing. I just want to create threads with the settings I've already set
