### ISSUE TITLE
feat: Jan labels Remote API models and enhances transparency on Jan Hub

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2825]
**Problem**
[Feedback from a Reddit user](https://www.reddit.com/r/LocalLLaMA/comments/1cclmjk/comment/l172sas/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) has highlighted some confusion around the labeling and usability of our remote API models on the Jan Hub UI. The current "recommended" label is perceived as misleading, with suggestions to replace it with more precise terms like "remote" or "cloud". Plus, there is a need for improved transparency regarding the models' intended use, source websites, and licensing.

**Success Criteria**
Improve user understanding and trust in choosing the appropriate API models.
Enhance overall user experience on the Jan Hub UI by providing clearer information and easier navigation.

**Additional context**

**Comment by Van-QA** [comment]
related to https://github.com/janhq/jan/issues/2590 :pray:

**Comment by imtuyethan** [comment]
This will be resolved after Hub revamp #2590
