### ISSUE TITLE
Discussion: the "Clean Thread" button shouldn't exist

### ISSUE THREAD

**Issue by davidawad** [janhq/jan#2829]
**Motivation**
So we have two primary thread options in jan, deleting a thread and cleaning one. Cleaning one appears to wipe away the thread history, which is functionally equivalent to deleting it, it just seems like we could streamline this, and only show the trash can on hover instead of the three dots. 

<img width="304" alt="image" src="https://github.com/janhq/jan/assets/4019054/c9113f9c-6551-4a1e-b8e1-2c5c481c60bc">

It's possible i'm misunderstanding here but from what I can tell there's no need for these to be two different buttons. 

It would be an easy PR, if you like I could probably write it myself :)

**Comment by Van-QA** [comment]
hi @davidawad, the clean thread will help preserve the thread settings for users, so that they don't have to setup the thread from scratch again :pray:
Thank you for the suggestion, good question 👍
