### ISSUE TITLE
bug: Inactive

### ISSUE THREAD

**Issue by Abenu10** [janhq/jan#2830]
**Describe the bug**
I am unable to start `llama3` on Jan AI Desktop. When I attempt to start `llama3`, I receive an error message indicating that the Nitro subprocess is exiting with the error code `3221225781`. This error code typically indicates a missing DLL that the executable needs.

**Steps to reproduce**
1. Open Jan AI Desktop.
2. Attempt to start `llama3`.
3. See error: `Error: child process exited with code 3221225781`.

**Expected behavior**
I expected `llama3` to start without any errors.

**Environment details**
- Operating System: Windows 10 Pro, version 10.0.19045
- Jan Version: 0.4.122
- Processor: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
- RAM: 16GB
- CUDA Version: 11

**Logs**
Here are the relevant logs:
2024-04-26T02:34:49.000Z [NITRO]::Debug: Nitro exited with code: 3221225781 2024-04-26T02:34:49.001Z [NITRO]::Error: child process exited with code 3221225781 ... (repeat for each instance of the error) ... 2024-04-26T02:59:00.324Z [NITRO]::Debug: Nitro exited with code: 3221225781 2024-04-26T02:59:00.325Z [NITRO]::Error: child process exited with code 3221225781

**Additional context**
I'm not sure which DLL might be missing, or how to resolve this issue. Any assistance would be greatly appreciated.
![image](https://github.com/janhq/jan/assets/86177342/f8990ecd-bb79-48dc-9bcc-36a7aff3b8ed)

**Comment by Van-QA** [comment]
hi @Abenu10, can you give us your settings.json? thank you
![image](https://github.com/janhq/jan/assets/64197333/99487304-44fd-402e-b490-36230245a348)

**Comment by Abenu10** [comment]
hi @Van-QA  here is it 
{
  "notify": true,
  "run_mode": "gpu",
  "nvidia_driver": {
    "exist": false,
    "version": ""
  },
  "cuda": {
    "exist": true,
    "version": "11"
  },
  "gpus": [],
  "gpu_highest_vram": "",
  "gpus_in_use": [
    ""
  ],
  "is_initial": false,
  "vulkan": false
}

**Comment by Van-QA** [comment]
thank @Abenu10, the setting shows run_mode is GPU, which would require this setup in your case, can you try it? https://jan.ai/docs/troubleshooting#troubleshooting-nvidia-gpu

**Comment by Abenu10** [comment]
so  i can't run it with intel gpu? what else options do i have ?

**Comment by Van-QA** [comment]
You can run with Intel GPU, but you need nvidia_driver setup, please follow the guideline and you will be able to use it https://jan.ai/docs/troubleshooting#troubleshooting-nvidia-gpu

Otherwise, you can run with CPU, by turning off this setting for GPU accelerations 
![image](https://github.com/janhq/jan/assets/64197333/73b4a47e-bb1f-4afa-917f-e1eeb64bf9e8)

**Comment by Abenu10** [comment]
Thank you for your detailed response. I understand that the Jan AI software can utilize GPU acceleration when the appropriate NVIDIA drivers and CUDA are installed. However, my system is equipped with an Intel GPU, not an NVIDIA one. 

As I understand it, NVIDIA drivers and CUDA are specifically designed for NVIDIA GPUs and cannot be installed on systems with GPUs from other manufacturers like Intel. Could you please confirm if my understanding is correct?

You also mentioned an alternative solution, which is to run the software in CPU mode by disabling the GPU acceleration setting. Could you please provide more details on how to do this? Is there a specific setting in the `settings.json` file that I need to change?

**Comment by Van-QA** [comment]
thank you for your time
- For intel GPU, you can try these experimental feature => Vulkan support, and then see if the GPU acceleration found your GPU
<img width="676" alt="image" src="https://github.com/janhq/jan/assets/64197333/2cc11831-0b0e-4586-8c17-d179d9c363bc">

- If you are still unable to turn on the GPU settings, and want to run via the CPU, can you try manually modifying the settings.json run_mode to "cpu" and see if it works or not?

**Comment by Abenu10** [comment]
Hey @Van-QA ,
Thank you for your suggestions. changed the `run_mode` to `"cpu"` in the `settings.json` file.
I'm now able to run the application successfully using CPU mode.
I appreciate your time and assistance in helping me troubleshoot this issue.
