### ISSUE TITLE
feat: Jan connects to CustomGPTs  

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2831]
Jan users can also chat with CustomGPTs of their accounts.

**Comment by imtuyethan** [comment]
Can you give more info on this? @eckartal

**Comment by eckartal** [comment]
I mean allowing Jan users to connect their CustomGPT's associated their ChatGPT accounts: https://chatgpt.com/gpts/mine

**Comment by 0xSage** [comment]
wont do. issue poorly defined and doesn't make sense
