### ISSUE TITLE
feat: Jan clarifies model deletion functionality in "My Models"

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2844]
**Problem**
The current model deletion interface under "My Models" is unclear, with some users misunderstanding that the "Delete" action might remove the model files from their storage, whereas it only removes them from the Jan list.

**Success Criteria**
Update the UI and provide clear messaging that explains the "Delete" action only removes the model from Jan's internal list and does not delete the actual files from the user's device. This can be achieved through tooltip enhancements, confirmation dialogs, or updated UI text.

**Additional context**
Detailed feedback: https://www.reddit.com/r/LocalLLaMA/comments/1cclmjk/comment/l1byjva/?context=3

**Comment by imtuyethan** [comment]
This will be resolved after Jan x Cortex & Hub revamp since we will no longer have import models functions in the near future, all models are populated & downloaded from other repo like Cortex or Hugging Face to user's local (on-device models).
