### ISSUE TITLE
bug: Scrolling Issue: Text doesn't stay put after clicking the generated text

### ISSUE THREAD

**Issue by 6eero** [janhq/jan#2847]
**Describe the bug**
Once the text is generated, clicking anywhere on the mouse causes the output text to scroll to the bottom. When I return to the text, I can click freely without any effect. However, if I switch to another window and then return to the text to click on it (e.g., to copy it), the text returns to its original position.

**Steps to reproduce**
1. Generate something
2. Go up with mouse wheel
3. Click anywhere
4. The output text scrolls down to the bottom

**Expected behavior**
After the text is generated, if I click anywhere with the mouse, the output text should remain fixed and not scroll back down.

**Environment details**
- Operating System:  Windows 11
- Jan Version: 0.4.12
- Processor: i5 10600k
- RAM: 16GB
- GPU: RTX 3060

**Comment by takeerdevs** [comment]
I'm having the same issue for this release v0.4.12

**Comment by fdciabdul** [comment]
same issue here

**Comment by Van-QA** [comment]
Looking good as of Jan v0.4.12-409 ✅

**Comment by Flavelius** [comment]
I have 0.4.12 (downloaded from the website), not sure which sub-version, but when scrolling up, changing window focus, and re-focussing the jan window, it also autoscrolls down to the bottom, which is really annoying when trying to copy text fragments or read a previous output.

**Comment by Van-QA** [comment]
hi @Flavelius, the fix is in the nightly build which can be found at https://github.com/janhq/jan?tab=readme-ov-file#download (for those who want to try it early.
For stable, the fix will be released once we publish the new stable release (v0.4.13). Stay tuned 🙏
