### ISSUE TITLE
feat: doclibrary for multible pdf

### ISSUE THREAD

**Issue by kalle07** [janhq/jan#2852]
**Problem**
i have multible folders with at least one or more PDF in it
for now i can only put one or two in a chat and must wait until they get prepared everytime

**Success Criteria**
if i had a library i can choose the lib i want and can instantly start the chat

**Additional context**
for now i think there is a limit without any error mesages, pdf with 300pages dont work, i tryed some and wait 10min, but it doesnt start to chat

**Comment by davidawad** [comment]
not sure I totally understand  the ask here, can you supply PDFs to Jan? 

how were you passing PDFs to it?

**Comment by louis-jan** [comment]
UX update needed @imtuyethan. E.g. Supported files

**Comment by imtuyethan** [comment]
Closed as duplicated with https://github.com/janhq/jan/issues/2761
