### ISSUE TITLE
feat: support Nvidia NIMs remote API

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#2854]
**Problem**

Request from user: 
https://build.nvidia.com/explore/discover
so this is something I came across. With this we can get access to dbrx, mixtral8x22b through nvdia api
will be good to have them 

**Success Criteria**

**Additional context**

**Comment by Realmbird** [comment]
Could I try this first issue I might need help doing this since I will be a beginner

**Comment by Realmbird** [comment]
Mixtral is https://build.nvidia.com/mistralai/mixtral-8x22b-instruct
Dbrx https://docs.api.nvidia.com/nim/reference/databricks-dbrx-instruct-infer

**Comment by Van-QA** [comment]
hi @Realmbird, feel free to pick it up and draft a PR to us 🙏

**Comment by Realmbird** [comment]
Current draft https://github.com/janhq/jan/pull/2882

**Comment by Realmbird** [comment]
Fixed models not holding params currently working on fixing ids with / in name

**Comment by Van-QA** [comment]
Need to correct the ‌URL for API key ‌in the settings: https://discord.com/channels/1107178041848909847/1186884274637516860/1248139642352697375
Please refer‌ to this correct flow, thank you
@namchuai
