### ISSUE TITLE
bug: Impossible to scroll when editing a chat input

### ISSUE THREAD

**Issue by QuentinMacheda** [janhq/jan#2855]
**Describe the bug**
When editing a chat input, the scroll is disabled. The only way to go up and down through the input text is with the keys, which is not really user-friendly and kind of complicated. 

**Steps to reproduce**
1. Create a new thread.
2. Enter a pretty long message.
3. Edit this chat input.
4. Make sure the text is overflowing of the textarea.
4. See that you cannot scroll up or down. 

**Expected behavior**
I expect to be able to scroll up and down so I can edit my chat inputs easily.

**Screenshots**
![image](https://github.com/janhq/jan/assets/69113642/92b9cf60-a4e5-47e5-bb6e-ce3e74934fa3)

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.12
- Processor: Intel Core i7
- RAM: 32GB

**Logs**
If the cause of the error is not clear, kindly provide your usage logs: https://jan.ai/docs/troubleshooting#how-to-get-error-logs

**Additional context**
Add any other context or information that could be helpful in diagnosing the problem.

**Comment by QuentinMacheda** [comment]
I'd like to work on that, could someone assign this issue to me ?

**Comment by amr-cloudforce** [comment]
Jan is unusable with this bug.

**Comment by Van-QA** [comment]
Tested and looking good on Jan Jan v0.4.12-403


![image](https://github.com/janhq/jan/assets/64197333/d6bceafc-cf35-4765-8bbf-2ea958b2142c)

**Comment by xTararAisx** [comment]
still working weirdly when Jan is windowed.

If you try to edit an input message, it will automatically scroll down to the last message every time

**Comment by Van-QA** [comment]
hi @xTararAisx, may I ask, which Jan version are you on? and which OS?
