### ISSUE TITLE
feat: Add NVIDIA GPU monitoring on windows/ linux

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#286]
**Problem**
I want to see my nvidia gpu monitoring (GPU utilization/ VRAM) on Jan to check the resource consumption of models use

**Success Criteria**
- Correctly show the utilization
- Can see the UI at bottom bar

**Additional context**
- https://github.com/RedCarrottt/nvmon/blob/master/nvmon-smi-server.js

**Comment by TashaSkyUp** [comment]
Looking forward to this!

**Comment by imtuyethan** [comment]
# Specs 
Performance Settings
- GPU Monitoring: [ Enable / Disable ]
  - (Info button or tooltip: Monitor GPU usage for improved model performance.)
- GPU Selection: [ Nvidia / AMD ] (visible only when GPU Monitoring is enabled)
  - Default: Auto-select GPU with highest VRAM

### GPU Monitoring Toggle:
- When toggled on, reveal the GPU selection dropdown for Nvidia and AMD.
- Default to the auto-selected GPU with the highest VRAM.

### GPU Monitoring Warning:
- If the user toggles on GPU monitoring, provide a brief explanation of how it can improve model performance.
- Optionally, warn that enabling GPU monitoring may have a slight impact on system resources.

### GPU Selection:
- Use a dropdown to allow users to manually select Nvidia or AMD when GPU monitoring is enabled.
- Default to the auto-selected GPU with the highest VRAM.

### Device Compatibility Check:
- Before applying changes, check if the user's device has a compatible GPU.
- If not, display an error message and prevent the user from enabling GPU monitoring until a compatible GPU is detected.
_(Optional: provide a suggestion or link to update GPU drivers or install a compatible GPU)._

### Feedback:
- Display a success message upon applying changes.
```
GPU monitoring has been successfully enabled.
```
- Or when user disables GPU monitoring without any specific issues.
```
GPU monitoring has been successfully disabled.
```
- In this case, changes don't require a restart.

## Error scenarios: 
### 1. User tries to enable GPU monitoring, but their device doesn't have a compatible GPU
```
GPU Monitoring cannot be enabled on your device.
Your current device does not have a compatible GPU for monitoring. To enable GPU monitoring, please ensure your device has a supported Nvidia or AMD GPU with updated drivers.

```
### 2. GPU Selection with Incompatible GPU
User selects a specific GPU for monitoring, but that GPU is not compatible.

-> Show tag next to compatible & incompatible GPU to infirm selection.

### 3. GPU Monitoring Turned Off with Compatible GPU
User attempts to turn off GPU monitoring when they have a compatible GPU.
Tooltip when hover: 
```
Turning off GPU Monitoring may impact model performance.
```
Confirmation pop-up:
```
[Warning]

Turning off GPU Monitoring may impact model performance.

Your device has a compatible GPU that is currently being used for model acceleration. Disabling GPU monitoring will stop tracking GPU performance, but it may affect the efficiency of your model computations. Consider keeping GPU monitoring enabled for optimal model performance.

To proceed, click "Continue" if you still wish to turn off GPU monitoring.
```


![Image](https://github.com/janhq/jan/assets/89722390/707f38be-935e-4e24-8a99-ac04a4e36da8)

**Out-of-scope:**
- Not support AMD for now.
