### ISSUE TITLE
feat: Electron App auto update for Early Access to Pre-Release build (Experimental mode)

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#2861]
**Problem:**
We want to allow early access to new features and improvements in the Electron app for users who want to test and provide feedback, but currently, they have to manually switch to the-release build every time they want to the latest changes.

**Success Criteria:**
We want to add a to the Electron app that allows automatic updates to the-release build for users who have enabled "experimental mode". This will allow the community to test the latest features and earlier than the official build.
Stable build:
- Users with Stable version A, can automatically update to A-rc1 (once available)
- Users with A-rc1 can automatically update to A-rc2, B (once available)
 
Nightly build: TBU
- Users with nightly A-xxx can automatically update to A-rc1???

Additional Context:**
We have a stable release that is recommended for most users, as well as a pre-release that includes features and improvements but may also have bugs instability.
This approach allows us extra time to address any critical issues identified during the community preview.

Enabling experimental mode in the Electron app will allow developers and users to easily access and test the pre-release version. This will help the Electron team gather early feedback and identify issues before new features are added to the stable channel.

**Comment by 0xSage** [comment]
poorly defined, we will not do this
cc @dan-homebrew
