### ISSUE TITLE
feat: Add MacOS metal monitoring on Mac

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#287]
**Problem**
I want to see my MacOS metal gpu monitoring (GPU utilization/ VRAM) on Jan to check the resource consumption of models use

**Success Criteria**
- Correctly show the utilization
- Can see the UI at bottom bar

**Additional context**
- https://github.com/automation-stack/electron-sudo
- Use `powermetrics` and parse result

`sudo powermetrics -i 1000 --samplers all --show-usage-summary`

**Comment by Foul-Tarnished** [comment]
https://github.com/op06072/NeoAsitop

This would probably be better than powermetrics, because NeoAsitop doesn't require admin privileges (sudo)

**Comment by 0xgokuz** [comment]
Can I take this?

**Comment by 0xgokuz** [comment]
Hi @imtuyethan,
I think we'll need the UI/UX design from you for this issue as well. The big UI/UX question that we have is that whether we should be requesting the User for their `sudo` password every time?

The options for the monitoring tools:
1. https://github.com/dehydratedpotato/socpowerbud
2. https://github.com/op06072/NeoAsitop
3. https://github.com/tlkh/asitop
4. https://github.com/automation-stack/electron-sudo

**Comment by Foul-Tarnished** [comment]
> Can I take this?

Another important metric would be this :
![image](https://github.com/janhq/jan/assets/107711110/f9181bfd-a022-4d15-a692-7991413fbfa8)
By default, MacOS let its GPU only use ~65% of the RAM

in Faraday app, they show this above, useful to know the biggest models that can run on your GPU with Metal backend.

Thankfully, we can increase this with `sudo sysctl iogpu.wired_limit_mb=30720` (set to 0 for default behavior)
sadly it needs admin privileges, but maybe we could at least read and display the value without sudo ? not sure it works


With this tweak, I can run Mixtral8x7b (25GB model) on the gpu, really fast, on a 36GB macbook model (even with +2k context)

**Comment by Foul-Tarnished** [comment]
Another cool metric would be watts usage, especially if you are running on the battery

**Comment by 0xSage** [comment]
Outdated issue
