### ISSUE TITLE
feat: Enable "sticky" scrolling while text is generating

### ISSUE THREAD

**Issue by mr-september** [janhq/jan#2873]
**Problem**
Actually not sure if this is a bug or feature request.

While text is generating/streaming, the window is constantly scrolling down. Usually this is good.

Sometimes I would like to scroll to a point and start reading, while the generation continues. However, this is not possible as the scrolling  immediately and constantly resets to the bottom-most point.

**Success Criteria**
I would like if manual scrolling has happened, then auto-scrolling stops for that single generation.

**Comment by Van-QA** [comment]
Looking good as of Jan v0.4.12-409 ✅

**Comment by mr-september** [comment]
Confirmed working on my end as well. It is absolutely unbelievable how fast you guys are working through issues! Thanks!
