### ISSUE TITLE
bug: being able to set a longer context length for the new llama3-gradient model

### ISSUE THREAD

**Issue by xyproto** [janhq/jan#2875]
**Describe the bug**

Hi! Llama3-gradient is out, and it has support for a larger context window. 256k is [suggested by Ollama](https://ollama.com/library/llama3-gradient).

However, in the Jan UI, the maximum context length appears to be 2048. Being able to set it to 262144 would make it possible to utilize the potential of the llama3-gradient model.

This is the GGUF file I have tested with:

* [Llama-3-8B-Instruct-Gradient-1048k-Q6_K.gguf](https://huggingface.co/bartowski/Llama-3-8B-Instruct-Gradient-1048k-GGUF)

**Steps to reproduce**
1. Start Jan
2. Load and run Llama-3-8B-Instruct-Gradient-1048k-Q6_K.gguf
3. In the Thread Settings on the right hand side, the maximum context length is 2048, even when typing in a number manually.

**Expected behavior**

Be able to specify a longer context length.

**Screenshots**

<img width="327" alt="bilde" src="https://github.com/janhq/jan/assets/52813/256f06c1-cc4b-4ff9-a6db-582248406a44">

**Environment details**
- Operating System: macOS Sonoma 14.4.1
- Jan Version: 0.4.12

**Comment by Van-QA** [comment]
hi @xyproto, 
You can modify the context length via model.json, please refer to the screenshot below, and remember to restart Jan and create new threads afterward. 🙏 
![image](https://github.com/janhq/jan/assets/64197333/1b95e354-1724-41d1-9289-178b7b871a6e)
Feel free to reopen this if any concerns.

**Comment by xyproto** [comment]
It is great that it is possible to do in the config, thanks for the info!

Could the max value for the slider also be a bit higher, at least for models that are known to be useful because of their larger context size?
