### ISSUE TITLE
bug: Tools tab (Retrieval) disappeared in 0.4.12-410

### ISSUE THREAD

**Issue by mr-september** [janhq/jan#2881]
**Describe the bug**
The entire "Tools" tab to enable and tune RAG seems to have disappeared upon updating to 0.4.12-410 nightly.

**Steps to reproduce**
Launch jan.ai

**Expected behavior**
See the "Tools" tab.

**Screenshots**
![image](https://github.com/janhq/jan/assets/45350177/b8e774cc-1d77-43f0-99e1-81907e50bb53)

**Comment by Van-QA** [comment]
hi @mr-september,
Would you mind trying these solution?
- Try turning on the experimental settings ON again.
- Try other models?
- How about creating a new thread?
<img width="531" alt="image" src="https://github.com/janhq/jan/assets/64197333/649363c9-d585-4ce8-b88b-a3c5082f616a">

We need more context to investigate, as it is working fine on both Windows and MacOS on our side. Thank you for your time 🙏

**Comment by mr-september** [comment]
> Try turning on the experimental settings ON again.

Thank you, this worked!
