### ISSUE TITLE
feat: Add nitro-avx to work

### ISSUE THREAD

**Issue by mike2003** [janhq/jan#2884]
**Problem**
Now need a processor with avx2 for nitro
https://github.com/janhq/jan/issues/1982

**Success Criteria**
Add the ability to run on avx

**Additional context**
On the nitro website you can download the avx version, I tried substituting the current avx2 in the extensions and everything works on the avx version. Why not do it in the settings next to GPU? And add the win-cpu-avx folder.

**Comment by Van-QA** [comment]
Please follow up using this ticket 🙏 
https://github.com/janhq/jan/issues/2729#issuecomment-2078586172
