### ISSUE TITLE
feat: Run Jan server and UI on Android / Termux

### ISSUE THREAD

**Issue by iAdanos** [janhq/jan#2886]
**Problem**
Since Android app is not supported anymore, it would be great to make possible running Jan directly on Android / ARM Linux.

It can be possibly done by running Jan as server with Web UI in Termux / proot-distro under Termux.
Going that way, people would be able to use the same upstream app version and maintainers will not have a need to support a separate product.

**Success Criteria**
- There is a clear guide on how to run Jan server with UI (accessible from web browser) on Termux / Linux (e.g. Ubuntu aarch64).
- If required, a proper deb / binary package is provided with other Jan release artifacts

**Additional context**
A good example on what approach is proposed is code-server run instruction:
- https://coder.com/docs/code-server/latest/termux
- https://wiki.termux.com/index.php?title=Node.js
- https://medium.com/@olioxxayo/super-charge-your-coding-ability-with-termux-and-code-server-f6e84a4bd78a

**Comment by imtuyethan** [comment]
Not so sure about this, can you take a look? @namchuai

**Comment by 0xSage** [comment]
You can run the backend for Jan independently using https://github.com/janhq/cortex.cpp
But I don't think we support a web ui right now, cmiiw @louis-jan 
We're more likely to build a mobile app tbh...
