### ISSUE TITLE
Local Models difficult to find and review due to proliferation of API models

### ISSUE THREAD

**Issue by likwidoxigen** [janhq/jan#2887]
**Problem**
It is challenging to search for new available models due to the presence of 14 API "models" cluttering the list, with no option to disable or hide them on an individual or group basis.

**Success Criteria**
Allow API models to be hidden from the model hub.

There are multiple methods that this could be done:
Provide a search filter on the hub page.
Add the ability to disable/hide models individually on the "My Models" page.
Add the ability to disable the api extensions.

**Comment by imtuyethan** [comment]
WIth the latest release, i think we already solved this problem.

**Comment by likwidoxigen** [comment]
Unsure how the problem is solved. Turning off the model providers in extensions  does not remove or hide them from the model  listing.
