### ISSUE TITLE
feat: Ability to delete all threads

### ISSUE THREAD

**Issue by Noam-Br** [janhq/jan#2891]
**Problem**
Right now I have to delete each thread separately, I'd like to clear out all threads

**Success Criteria**
All threads are cleaned at a single click

**Additional context**
Same feature that has in ChatGPT:
![image](https://github.com/janhq/jan/assets/139764378/17485fa6-69f7-4d3d-9f57-158a3d8d55c2)

**Comment by Van-QA** [comment]
We will consider it, for now, you can delete all threads manually by going to the Jan data folder and deleting all of these thread folders 
![image](https://github.com/janhq/jan/assets/64197333/72d2b9f2-7fed-4439-8da5-5e80c977caa7)

**Comment by Noam-Br** [comment]
Got it will do for now. Thanks @Van-QA!

**Comment by nikiluk** [comment]
Upvote for thread deletion feature

**Comment by khanakia** [comment]
Any update on this ?

**Comment by Van-QA** [comment]
will be re‌solved via: https://github.com/janhq/jan/issues/3333
