### ISSUE TITLE
Discussion: Cloning

### ISSUE THREAD

**Issue by iandoug** [janhq/jan#2892]
**Motivation**
Waste of space and bandwidth?

**Discussion**

git clone https://github.com/janhq/jan appears to pull in 31462 objects ... are they all necessary?

**Alternatives**

Get what is needed to build?

**Comment by iandoug** [comment]
Qk I see I was following the steps under "contributing" .. so probably whole tree is desired.

Maybe "build from source" instructions for those wanting to, and not want .deb?

Thanks, Ian

**Comment by iandoug** [comment]
The appimage works fine (Gentoo Linux), so you can close this if you want.

**Comment by Van-QA** [comment]
Thank you, that's right. The entire source code is in the git repository. You can build it from there if you wish to.

However, if you just want a pre-packaged .deb file, that is also available. You don't need to build it yourself.
