### ISSUE TITLE
feat: User can change Assistant name and avatar

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#2894]
# Problem
We got requests from many users to make the assistant field editable:
![Screenshot 2024-05-13 at 12 13 59 PM](https://github.com/janhq/jan/assets/89722390/300c9ead-663d-4a16-81c0-031ab169199a)
# Design
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?node-id=3896-57872&t=dKPqEv1WkJxHKSeY-4
- Allow users to change assistant avatar
- Allow users to change assistant name

<img width="472" alt="Screenshot 2024-05-15 at 1 45 09 AM" src="https://github.com/janhq/jan/assets/89722390/28569cc3-9934-42d1-aff1-87b677d969b4">

**Comment by dan-homebrew** [comment]
I am merging this into https://github.com/janhq/jan/issues/3607
