### ISSUE TITLE
Can't get past loading screen

### ISSUE THREAD

**Issue by bloodyburger** [janhq/jan#2896]
So I deployed using docker on a machine with 64G Ram and started with 
```docker compose --profile cpu-fs up -d```
When I load the page, https://chat.teej.xyz, I cannot get past the loading screen. On docker logs , I just see these
```
Electron is not available
 HTTP  5/13/2024 4:25:27 PM 172.18.0.4 GET /
 HTTP  5/13/2024 4:25:27 PM 172.18.0.4 Returned 200 in 1 ms
Electron is not available
 HTTP  5/13/2024 4:25:31 PM 172.18.0.4 GET /
 HTTP  5/13/2024 4:25:31 PM 172.18.0.4 Returned 200 in 0 ms
Electron is not available
```

**Comment by Van-QA** [comment]
Hi @bloodyburger, can you give us any console log during the stuck in loading screen of the site?
Thank you

**Comment by dylangerdaly** [comment]
I'm also getting this error.

**Comment by Van-QA** [comment]
This issue is reproducible :x:
![image](https://github.com/janhq/jan/assets/64197333/08b27b3d-4328-4beb-ae4f-03e8426e4723)

**Comment by dylangerdaly** [comment]
Any update on this? I'd like to use Jan on my server

**Comment by namchuai** [comment]
For headless Jan, please take a look at Cortex: https://github.com/janhq/cortex
