### ISSUE TITLE
bug: Ubuntu Install fails with error messages

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#290]
**Describe the bug**
- [x] Jan cannot start up on Ubuntu 
- [ ] .deb package is missing key fields, doesn't show up in Software Installer
- [ ] `jan-electron` instead of `jan`

**To Reproduce**
Follow typical `.deb` software install process on Ubuntu
https://phoenixnap.com/kb/install-deb-files-ubuntu

![image](https://github.com/janhq/jan/assets/101145494/a9af676b-8b65-4bb8-b822-b696025a2d2d)

Immediately results in error
![image](https://github.com/janhq/jan/assets/101145494/4b7e4ca7-805c-4c7b-9ba7-d97008f79965)
![image](https://github.com/janhq/jan/assets/101145494/81db4397-d6ed-4f14-b7b1-625ed151c39d)

Clicking "Reload" in Electron results in UI showing up, but same error
![image](https://github.com/janhq/jan/assets/101145494/ccaaeb02-a57a-4294-afaa-fbc26651309d)

**Expected behavior**
- [ ] "Jan" instead of `jan-electron`
- [ ] Package should have description, etc in Software Installer
- [x] Should be able to load without errors

**Comment by hiento09** [comment]
Hey @dan-jan , to rename `jan-electron` to `jan` we may need to delete current 3 release 0.1.1, 0.1.2, 0.1.3, because these version app name are `jan-electron`, it may make user confuse if they download these version.
