### ISSUE TITLE
bug: minimum window's size not usable

### ISSUE THREAD

**Issue by QuentinMacheda** [janhq/jan#2902]
**Describe the bug**
As you know, it is possible to resize the window, but the current minimum width is not big enough to keep the app readable and functional. And there is no defined minimum height.

**Steps to reproduce**
1. Open the application.
2. Resize the window's width as much as you can.
3. Resize the window's height as much as you can too.
4. See that the app is unusable.

**Expected behavior**
I would expect that the window has a minimum size (width and height) set to values that keep the app readable and functional.

**Screenshots**
![image](https://github.com/janhq/jan/assets/69113642/43bebf20-cc5d-42a8-85f7-371c9f403b73)

**Environment details**
- Operating System: Windows 11
- Jan Version: 0.4.12
- Processor: Intel Core i7
- RAM: 32GB

**Comment by QuentinMacheda** [comment]
I can fix it if you want to, there is just 2 lines to add.

**Comment by Van-QA** [comment]
hi @QuentinMacheda, we will revamp the UI soon, I will put this ticket on hold, to avoid duplicate work 🙏 we will verify it in the new UI (WIP) and let you know the result

**Comment by QuentinMacheda** [comment]
Hi @Van-QA, okay thanks! Let me know if I can help in any way on the new UI development

**Comment by Van-QA** [comment]
hi @QuentinMacheda, this is our new UI with the small window (WIP)
![image](https://github.com/janhq/jan/assets/64197333/a231804e-a20e-4712-947b-b6bf585a83cc)

We also have a test build, you can try it out https://github.com/janhq/jan/actions/runs/9089134432
Discord channel for the discussion of the new UI: https://discord.com/channels/1107178041848909847/1213048058955300934
Feel free to provide feedbacks :D or suggest any areas that you want to help.
Thank you
