### ISSUE TITLE
老是显示扩展安装失败

### ISSUE THREAD

**Issue by GaryssWu** [janhq/jan#2919]
**Motivation**
@janhq/monitoring-extension:build: RequestError: tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 10809
@janhq/monitoring-extension:build:     at ClientRequest.<anonymous> (D:\nobushu\jan\extensions\monitoring-extension\node_modules\got\index.js:111:21)
@janhq/monitoring-extension:build:     at Object.onceWrapper (node:events:633:26)
@janhq/monitoring-extension:build:     at ClientRequest.emit (node:events:518:28)
@janhq/monitoring-extension:build:     at ClientRequest.onError (D:\nobushu\jan\extensions\monitoring-extension\node_modules\tunnel-agent\index.js:179:21)
@janhq/monitoring-extension:build:     at Object.onceWrapper (node:events:633:26)
@janhq/monitoring-extension:build:     at ClientRequest.emit (node:events:518:28)
@janhq/monitoring-extension:build:     at Socket.socketErrorListener (node:_http_client:500:9)
@janhq/monitoring-extension:build:     at Socket.emit (node:events:518:28)
@janhq/monitoring-extension:build:     at emitErrorNT (node:internal/streams/destroy:169:8)
@janhq/monitoring-extension:build:     at emitErrorCloseNT (node:internal/streams/destroy:128:3)
@janhq/monitoring-extension:build: error Command failed with exit code 1.
@janhq/monitoring-extension:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@janhq/monitoring-extension:build: npm ERR! Lifecycle script `download-artifacts` failed with error:
@janhq/monitoring-extension:build: npm ERR! Error: command failed
@janhq/monitoring-extension:build: npm ERR!   in workspace: @janhq/monitoring-extension@1.0.10
@janhq/monitoring-extension:build: npm ERR!   at location: D:\nobushu\jan\extensions\monitoring-extension
@janhq/monitoring-extension:build: error Command failed with exit code 1.
@janhq/monitoring-extension:build: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@janhq/monitoring-extension:build: ERROR: command finished with error: command (D:\nobushu\jan\extensions\monitoring-extension) C:\Users\xmdti\AppData\Local\Temp\yarn--1715915176819-0.4569125474623621\yarn.cmd run build exited (1)
@janhq/monitoring-extension#build: command (D:\nobushu\jan\extensions\monitoring-extension) C:\Users\xmdti\AppData\Local\Temp\yarn--1715915176819-0.4569125474623621\yarn.cmd run build exited (1)

 Tasks:    24 successful, 27 total
Cached:    24 cached, 27 total
  Time:    24.701s
Failed:    @janhq/monitoring-extension#build

 ERROR  run failed: command  exited (1)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
make: *** [install-and-build] 错误 1

**Discussion**

**Alternatives**

**Resources**

**Comment by Van-QA** [comment]
hi @GaryssWu,

Can you give us more info on the issue, along with the reproducing steps? 
On the other hand, please also check your connection / VPN 🙏
