### ISSUE TITLE
bug: docker-compose.yml: yaml: line 208: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by sharicov** [janhq/jan#2922]
getting error: docker-compose.yml: yaml: line 208: mapping values are not allowed in this context when running  docker compose --profile cpu-fs up -d with both docker-compose.yml and docker-compose-dev.yml

Ubuntu (kubuntu) 24.04

Docker version 24.0.5, build ced0996

**Comment by imtuyethan** [comment]
@Van-QA Can you take a look at this?

**Comment by Van-QA** [comment]
Hey there! Thanks for trying out Jan. 

We've actually decided to deprecate Jan On-premise. Sorry for any confusion this might have caused.

We're focusing our efforts on improving the main Jan application to better serve our users. If you're looking for alternative solutions, you might want to check out Cortex (https://github.com/janhq/cortex) for headless AI operations.
Appreciate you taking the time to report this. Let us know if you have any other questions!
