### ISSUE TITLE
feat: users can search in threads using keyword/combination/regex

### ISSUE THREAD

**Issue by nikiluk** [janhq/jan#2930]
**Problem**
It's not possible to search for a specific keyword in the Threads. I have to call developer tools and search via dev tools and this is not very user-friendly.

**Success Criteria**
- A search bar that is easily accessible and visible
- A [CTRL+F]/[CMD+F] combination calling a search bar and focusing the cursor in the input field - when the app is open and active
- A Search view that displays threads that contain a search keyword/combination
- Highlighted search keyword/combination
- Jump-scroll to a particular search finding if there are multiple on the same screen + counter.

Example from VS Code:
![image](https://github.com/janhq/jan/assets/6605974/12f38e2e-c13d-4732-a7eb-625ed7d0704c)

**Additional context**
It would be great to implement a RegEx search too as an additional option.

**Comment by 0xSage** [comment]
We need to think through if this is just a thread level search or a global search (e.g. cmd+k)

**Comment by imtuyethan** [comment]
- Closed as a sub-task of https://github.com/janhq/jan/issues/3648
