### ISSUE TITLE
epic: Jan can Hear MVP

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#295]
## Issues

https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+can+Hear%22

**Problem**
- I would like to treat Jan as equal intellectual creature. It currently have the ability to think with LLM, soon to see (#294) but I think there is a missing part is HEAR (i.e TTS, STT)

**Success Criteria**
- Support in Nitro (https://github.com/janhq/nitro/issues/59) and then support in Jan Nitro plugin (as models)
- Augment existing capabilities with Chat

**Additional context**
None

## Linked Tasks

- https://github.com/janhq/nitro/issues/59

**Comment by 0xSage** [comment]
outdated issue given our latest research efforts
