### ISSUE TITLE
feat: a way to organize chats in categories instead of just piling them on top of eachother

### ISSUE THREAD

**Issue by Yasand123** [janhq/jan#2951]
**Problem**
Having chats on the left side without being able to organize them in groups/sub-sections is annoying. As I often want to separate by topic or by model so I can easily find them later.

**Success Criteria**
- Being able to organize chats in collapsible categories/sections.
- Maybe tag support.
- Being able to pin specific chats or categories so they're always at the top.
- Being able o archive chats.

**Additional context**
I'm not sure how it would work, but maybe something like the left panel (file browser) in VSCode would be nice, replace the file name with the chat name.

**Comment by public-daniel** [comment]
Adding on to this, couple ideas. It would be nice to be able to Pin / Save / Bookmark chats. I also like the idea of being able to open multiple "tabs"

**Comment by imtuyethan** [comment]
I'll close as duplicated & make sure to include it in https://github.com/janhq/jan/issues/3133
