### ISSUE TITLE
bug: HuggingFace model downloads creates JSON file that is missing <|eot_id|>

### ISSUE THREAD

**Issue by FilterJoe** [janhq/jan#2954]
**Describe the bug**
Downloading HuggingFace llama 3 Q8_0 model always resulted in a JSON file that was missing <|eot_id|> and therefore resulted in many interactions with lllama 3 Q8_0 models that had nonterminating responses or back and forth conversations with itself. 

The JSON file created during download had stop that looked like this:

"stop": [

"<|end_of_text|>"

],

The Q4 version in the curated Jan Hub looks like this, with the extra line that seems to cause Lllama 3 model to end properly:

"stop": [

"<|end_of_text|>",

"<|eot_id|>"

],

When I manually replaced the stop in JSON file with the Q4 version, it properly terminated.

**Steps to reproduce**
1) Start Jan on Mac OS running on an M-series Mac.
2) Click on Hub
3) Paste any GGUF URL from HuggingFace that is a llama 3 8B Q8_0 model.
4) Download the model. A JSON file will be created
5) Many prompts will result in a response that doesn't properly terminate. One such prompt is:
"Can you write a poem in the style of a villanelle? If so, please write a poem about hiking the Pacific Crest Trail in villanelle style. If you can't write a villanelle, that's ok - just tell me you can't do it."

**Expected behavior**
I expected an attempt at a villanelle, optionally with some explanation of this unusual poetic format.

The actual response would start with this but then go into a conversation with itself, usually not even terminating at all (I had to manually terminate).

**Environment details**
- Operating System: MacOS Ventura 13.6.6
- Jan Version: 0.4.14
- Processor: Apple M2 Pro
- RAM: 16GB

**Additional context**
The solution is simple: whatever code produces default JSON files when downloading from HuggingFace should include the following if it is a llama 3 8B model (I have no idea if this generalizes to all models):

"stop": [

"<|end_of_text|>",

"<|eot_id|>"

],

**Comment by Van-QA** [comment]
sorry for the i‌nconvenience, ‌we will ‌res‌olve the issue via https://github.com/janhq/cortex/issues/617

**Comment by louis-jan** [comment]
@namchuai metadata extraction

**Comment by Van-QA** [comment]
![image](https://github.com/user-attachments/assets/89ff729a-5f94-40f9-a493-6f4762f56d06)
Resolved in Jan v0.5.2-605 (Nightl‌y), feel free to check it out and get ‌bac‌‌k to us if any issue https://github.com/janhq/jan?tab=readme-ov-file#download
