### ISSUE TITLE
feat: better threads grouping and navigation

### ISSUE THREAD

**Issue by PhantomKojima** [janhq/jan#2956]
**Problem**
I have a lot of threads for different topics and it’s very inconvenient to find the right one.

**Success Criteria**
I would like to be able to add threads to favorites, combine them into groups, add tags and search for the desired text between them. 
 Generally speaking, better orientation is needed.

As an option, I suggest that the “Thread” menu item, which is located above the “Hub” item, does not immediately open a list of all threads, but a screen with cards of groups, “favorites” and “All”, when clicked on which the list of threads of the desired card will open as it looks Now. And the search function will be located above the column with a list of threads for searching in all threads of the selected group and above the chat for searching in the selected thread.

**Comment by hyuri** [comment]
Very needed. The one big missing feature for me. It's incredible how most AI chat apps are missing this functionality.

Just wanted to add my word of support, I see it's already planned.

**Comment by imtuyethan** [comment]
I'll close as duplicated & make sure to include it in https://github.com/janhq/jan/issues/3133
