### ISSUE TITLE
feat: list of instruct formats for various models

### ISSUE THREAD

**Issue by Koliham** [janhq/jan#2958]
**Problem**
Sometimes it fells like the instruction format was not correct for a given model.

**Success Criteria**
Embed the instruct format for some models into the application to be chosen in a dropdown menu.
Even better: Jan detects the model and auto-suggests the right instruct format.

**Comment by Van-QA** [comment]
### Default yml:

![image](https://github.com/janhq/jan/assets/64197333/af2930fb-8745-4f16-a8e9-0bbc53b1bb45)

### ‌Different pro‌mpt per family:

Llama 3:
prompt_template: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_message}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{prompt}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

ChatML:
prompt_template: "<|im_start|>system\n{system_message}<|im_end|>\n<|im_start|>user\n{prompt}<|im_end|>\n<|im_start|>assistant"

Alpaca:
prompt_template: "{system_message}\n### Instruction: {prompt}\n### Response:"

Vicuna
prompt_template: "<｜begin_of_sentence｜>{system_prompt}\n\nUser: {prompt}\n\nAssistant:"
