### ISSUE TITLE
bug: hangs on second request

### ISSUE THREAD

**Issue by freerider7777** [janhq/jan#2965]
**Describe the bug**

First request is answered ok, others just hang. Jan for windows (win 11), enable/disable GPU does not change the behavior.

![image](https://github.com/janhq/jan/assets/6572573/501dbd7b-621b-4293-9288-c475c4cb7c41)

**Comment by hahuyhoang411** [comment]
Hi @freerider7777 , can you share me the app.log so I can investigate further?

**Comment by freerider7777** [comment]
Sure, sorry for the delay.
[app.log](https://github.com/user-attachments/files/15569467/app.log)

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
