### ISSUE TITLE
bug: Problems with image uploads under a multimodal model.

### ISSUE THREAD

**Issue by Danielyy** [janhq/jan#2973]
**Describe the bug**
When selecting the GPT-4 multimodal model, it is not possible to upload images in the input box.

**Screenshots**
![image](https://github.com/janhq/jan/assets/236159/170e8d5b-e74d-4882-a92c-5f71d0c82c13)

**Environment details**
MAC M2

**Comment by pkirilin** [comment]
You can try the following:

1. Open `model.json` and set `settings.vision_model` to `true` for gpt 4o (you can do this directly from UI, see the screenshot below)
2. Restart the application
3. Change the model to something else, then select gpt 4o again

It worked for me

<img width="307" alt="Screenshot 2024-05-31 at 22 40 47" src="https://github.com/janhq/jan/assets/42248355/17fad274-7aa9-4c55-b8b0-f0470507e3e5">

**Comment by pkirilin** [comment]
However, there's still something wrong. When I send image with some text prompt, Jan says that my API key is invalid, but it's not true. It works fine without images with the same API key. Seems like sending images are not handled correctly at the moment (v0.4.14).

<img width="542" alt="image" src="https://github.com/janhq/jan/assets/42248355/10e5786e-1d38-4c6f-acf2-63f407ec0289">

**Comment by Van-QA** [comment]
Sor‌ry for th‌e i‌nconvenienc‌e, the GPT-4o API that included in Jan app do‌es not support ‌vision. We will add another API of GPT-4o to support vision function to Jan app soon. Stay tuned 🙏

**Comment by kalle07** [comment]
only our internal llava v1.5 (v1) is working with images ... all models iv downloaded from hugging llava 1.5 or 1.6 or llama3_llava dont work, 
greyed "image symbol" like above...
how i can enable ?

only some models, it give a lot more:
https://huggingface.co/cjpais/llava-1.6-mistral-7b-gguf
https://huggingface.co/PsiPi/liuhaotian_llava-v1.5-13b-GGUF
https://huggingface.co/xtuner/llava-llama-3-8b-v1_1-gguf

**Comment by Van-QA** [comment]
If you are certain that the model support images, you can try m‌‌od‌‌ifyi‌ng the ‌mod‌el json to enable the settin‌, please check out this guideline from https://github.com/janhq/jan/issues/2973#issuecomment-2142889621 🙏

**Comment by kalle07** [comment]
answer is "OK"

how should be the whole file look like for the normal standart llava 1.5

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex, please follow up ‌on issues related to RAG using https://github.com/janhq/jan/issues/3216
