### ISSUE TITLE
bug: Double-click on the window's upper bar does not maximize the window

### ISSUE THREAD

**Issue by danbeibei** [janhq/jan#2988]
**Describe the bug**
Double-click on the window's upper bar does not maximize the window since version 0.5.0.
This was possible until version 0.4.14.

**Environment details**
- Operating System: Windows 10 22H2
- Jan Version: 0.5.0-467

**Comment by urmauur** [comment]
@danbeibei isn't a bug, since on `0.5.0` we are using `frameless` some native functions will be gone, we will try another way, I put this as a feature request instead of bugs 🙏🏻

cc @Van-QA

**Comment by dev-bd** [comment]
> @danbeibei isn't a bug, since on `0.5.0` we are using `frameless` some native functions will be gone, we will try another way, I put this as a feature request instead of bugs 🙏🏻
> 
> cc @Van-QA

Any way you can restore the maximize button while using frameless? Even if the double click method doesn't work, it'd be nice to have the dedicated button. And to any other users viewing this, for the time being using a window manager might allow you to quickly fullscreen. Those on Linux already know what I'm talking about; there are also some open source window managers for Windows and probably Mac.

**Comment by Van-QA** [comment]
Chai‌ning the issue for the maximi‌ze button https://github.com/janhq/jan/issues/3005 @urmauur

**Comment by urmauur** [comment]
@dev-bd Yes agree on this PR we bring back the maximize button https://github.com/janhq/jan/pull/3024

@danbeibei https://www.electronjs.org/docs/latest/tutorial/window-customization#create-transparent-windows Unfortunately we can't work double click bc there are limitations when we use transparent or frameless, but we bring back the button maximize on the top right side so u can still maximize the window with the button 

![Screenshot 2024-06-11 at 18 39 46](https://github.com/janhq/jan/assets/10354610/aeba7353-9457-48ad-85b9-7df05b189b21)

**Comment by sndurkin** [comment]
@urmauur will the `Win` + `Up` shortcut also work to maximize it again?
