### ISSUE TITLE
feat: [Option to Disable Spell Checking]

### ISSUE THREAD

**Issue by Arche151** [janhq/jan#2991]
**Problem**  
I'm always frustrated when writing in multiple languages (English and German) because the spell checker underlines almost everything in red when it is set to the wrong language. For example, with my system language set to English, all German text gets marked as incorrect, and vice versa when set to German.

**Success Criteria**  
An option to disable spell checking entirely within Jan, allowing for a smoother writing experience without constant red underlines regardless of the language being used.

**Additional Context**  
This feature would be particularly beneficial for multilingual users who switch between languages frequently, improving focus and overall user experience.

**Comment by Van-QA** [comment]
@urmauur Copy for the settings to turn off Spell checking (On bydefault)


> Sell checking
> Disable if you prefer to type without spell checking interruptions or if you are using non-standard language or terminology that the spell checker may not recognize.
