### ISSUE TITLE
epic: Feedback on New UI - Font weight and missing parameters

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2992]
We received [a comment praising the new UI but with some suggestions for improvement](https://www.reddit.com/r/LocalLLaMA/comments/1d8n9wr/comment/l77excr/?context=3):

- The font is a bit too bold.
- The model parameters section lacks many options for tweaking.
- Additional feedback like inference stats and context length information would be helpful, similar to LM Studio.

https://github.com/janhq/jan/assets/159995642/46e4953e-dbe8-46df-bbf4-0e88c1b11fe9

**Comment by Van-QA** [comment]
Linking to other feedback from users:
1. Scrollbars are no longer visible for grab and drag action https://discord.com/channels/1107178041848909847/1110389363809976361/1247360389600120863
2. Other issues from Propeticus: https://discord.com/channels/1107178041848909847/1213048058955300934/1247198729820438752

**Comment by 0xSage** [comment]
![image](https://github.com/janhq/jan/assets/69952136/b170d7d2-7c11-4e05-a539-e7fe66f77aa8)

**Comment by urmauur** [comment]
we already merge PR for `font-weight` https://github.com/janhq/jan/pull/3018 I'll closed this ticket feel free to open
