### ISSUE TITLE
feat: Custom path issues for GGUFs

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2995]
**Problem**
Using GGUF files with custom paths has been problematic. Even when following the exact naming scheme and structure, there are issues. Every time Jan is launched, it creates default folders for models that users do not have or want. Setting permissions to 644 prevents this but requires manual ‘sudo ln’ commands to add .gguf models due to import errors caused by permissions.

**Success Criteria**
- Custom path functionality for GGUF files works smoothly
- Prevent Jan from creating default folders for unwanted models or make this behavior configurable.
- Process of adding .gguf models without requiring manual permission adjustments.

**Additional context**
Related Reddit comment to be updated: https://www.reddit.com/r/LocalLLaMA/comments/1d8n9wr/comment/l788tx8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by louis-jan** [comment]
Migrate Jan to use Cortex API could help address this, we are on it. There will be no longer any pre-populated models, and no default model folders will be created.

**Comment by Van-QA** [comment]
related to https://github.com/janhq/cortex/issues/665

**Comment by 0xSage** [comment]
should be fixed with rebase

**Comment by imtuyethan** [comment]
Fixed now.
