### ISSUE TITLE
feat: Easy switching between inference endpoints

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#2997]
**Problem**
Switching between inference endpoints like MSTY and AverythingLLM for general chat is a great feature. Running MLX locally and TabbyAPI from the server by tweaking OpenAI and Anthropic settings is convenient. However, there is a concern that future updates might make these tweaks more difficult.

**Success Criteria**
Ensure that the ability to switch between inference endpoints and tweak settings for OpenAI and Anthropic remains easy and user-friendly in future updates.

**Additional context**
Related Reddit comment to be updated: https://www.reddit.com/r/LocalLLaMA/comments/1d8n9wr/comment/l788tx8/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

**Comment by 0xSage** [comment]
poorly defined issue. wont fix
