### ISSUE TITLE
Refactor installation script to only handle dependency and installation

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#30]
# Deliverables

- [ ] README.md updated
- [ ] `install.sh` script

# Ideal Flow:

1. Checking & installation of OS dependencies
- *All the things Louis already configured*
- homebrew
- Docker
- Docker compose
- (Optional) GPU drivers: `nvidia-smi`, `cuda`, `nvidia-driver`

1. Git clone, submodule pull and other steps

# Do not include:
1. Model(s) installation, e.g. `wget...`
1. Running Jan, e.g. `docker compose up`
1. Running the Hasura seed migration

# Changelog

### Previous Instructions
feat: Install with shell script instead of docker

pros from @louis-jan : 
- less installation steps
- missing dependencies check
- different arch setup
  - On Mac M1s: https://llama-cpp-python.readthedocs.io/en/latest/install/macos/ , faster inference
  - On other architectures: enable other bare metal stuff that we dont get access to from within a container
- nice progress bar during install

**Comment by louis-jan** [comment]
from @vuonghoainam, curl bash script to setup everything & run in place: 
`curl jan.ai/installation/*.sh`

it will does: 
- Check host target 
- Check & install missing dependencies
- docker compose up
- sd & llm up (host target)
- print progress & final instruction (host - port)

cc @janhq/engineer

**Comment by louis-jan** [comment]
Reopen for LLM direct run on host target

**Comment by dan-jan** [comment]
@louis-jan: Running the install script gives me this result, is this intended? 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdTJDIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19-
-1e43f8d57c333997e6631655a1d5765fa57570e6/image.png)

**Comment by louis-jan** [comment]
no, its not @dan-jan. This should be a bug
