### ISSUE TITLE
feat: CPU support 

### ISSUE THREAD

**Issue by AliHaider20** [janhq/jan#3004]
**Problem**
Currently the software only loads the model on CUDA. 

**Success Criteria**
It should support AMD ROCm and CPU as well depending upon the model's size and memory space.

**Comment by TikoTako** [comment]
I have a 13600k with only the i-gpu and works fine

**Comment by AliHaider20** [comment]
What is the above number? 
I've AMD Radeon (TM) graphics. I'm not sure, how can I work with this.

**Comment by TikoTako** [comment]
if you mean 13600k  is my cpu, an intel i5 13th gen with integrated graphics

There is the vulkan support  for AMD GPU/APU and Intel Arc GPU in the settings:
Settings >
Advanced Settings >
Vulkan Support

**Comment by AliHaider20** [comment]
I can't find those settings on my PC.

**Comment by TikoTako** [comment]
![jan settings](https://github.com/janhq/jan/assets/49921594/b8f1c777-cb02-467f-ad30-b4abbc9b0e54)

**Comment by AliHaider20** [comment]
Thanks for the steps. Previously, I looked into my PC settings.

After applying the settings I just tried saying "Hello", but it gave me some application-related response, maybe the context is incorrect somewhere in the code.

Can you also let me know how I can use my GPU without Jan? Like how can I turn on the Vulkan support and use it in my code?

Thanks
