### ISSUE TITLE
No Full Screen button. Bug or feature? 

### ISSUE THREAD

**Issue by konashevich** [janhq/jan#3005]
There is no Full Screen button. 

v0.5.0-469

**Steps to reproduce**
Install v0.5.0-469

**Expected behavior**
Full Screen button.

**Screenshots**
![image](https://github.com/janhq/jan/assets/18244957/4bed7cf6-2152-480d-806a-91f69ac638ea)

**Environment details**
- Operating System: Windows 11 23H2
- Jan Version:  v0.5.0-469 nightly 
- Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz
- RAM: 32.0 GB (31.6 GB usable)
- NVIDIA 3060 6Gb VRAM

**Comment by bogorad** [comment]
this is ridiculous!!!!!! bring it back!
