### ISSUE TITLE
How can I inquire respectfully into the slowing performance?

### ISSUE THREAD

**Issue by tsjslgy** [janhq/jan#3008]
I have several concerns:
1、Each time I open the application after an update, it takes a considerable amount of time, sometimes even displaying nothing on the screen. I'm uncertain if this is a bug or not.
2、Has CPU computation been introduced? Currently, my CUDA usage is below 40%, yet the CPU usage has spiked to 80%. Even though I have a powerful GPU and have selected GPU usage, why is the CPU being utilized for computation? This has led to lagging in other programs.
3、I would appreciate multilingual support.
4、It would be beneficial to incorporate additional features such as image support, article content support, and video support, if feasible.
5、It would be preferable to have the option to choose the installation location. I'd rather not have the application installed on the system drive every time.

**Comment by Van-QA** [comment]
hi @tsjslgy, have you tried turning on the GPU acceleration settings? it's ‌under sett‌‌ings > Advanced sett‌ings
Would you mind giving us the setting‌s.json as well? Th‌a‌nk you

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
