### ISSUE TITLE
feat: Provider Extension - Google API

### ISSUE THREAD

**Issue by Realmbird** [janhq/jan#3010]
**Problem**
Jan only supports openai compatible api. So using https://github.com/zhu327/gemini-openai-proxy/tree/main will convert openai protocol to Gemni 

**Success Criteria**

**Additional context**

**Comment by Realmbird** [comment]
I will try working on this

**Comment by Realmbird** [comment]
Attempting to use https://github.com/janhq/jan/blob/dev/extensions/inference-anthropic-extension/src/index.ts claude  transformation to work for gemni

**Comment by holtskinner** [comment]
Note: you might be able to use this new feature for accessing Gemini on Vertex AI through the Open AI API

https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/call-gemini-using-openai-library

**Comment by Realmbird** [comment]
ok

**Comment by imtuyethan** [comment]
@Realmbird How is it going for you

**Comment by dan-homebrew** [comment]
Closed in favor of #3786
