### ISSUE TITLE
Error API models/download

### ISSUE THREAD

**Issue by liluxdev** [janhq/jan#3013]
curl -X 'GET' \
  'http://localhost:1333/v1/models/download/mistral-ins-7b-q4' \
  -H 'accept: application/json'

Error: Internal Server ErrorResponse bodyDownload{   "statusCode": 500,   "error": "Internal Server Error",   "message": "Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    \|     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle" }

**Comment by Van-QA** [comment]
Po‌‌tentially related to https://github.com/janhq/jan/issues/2944

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
