### ISSUE TITLE
epic: Improved RAG (LARS)

### ISSUE THREAD

**Issue by mr-september** [janhq/jan#3014]
Very cool new implementation of RAG:
- [Reddit post](https://www.reddit.com/r/LocalLLaMA/comments/1db98el/rag_for_documents_with_advanced_source_citations/)
- [Github](https://github.com/abgulati/LARS/tree/main)

Would be great if Jan could partner with them to be a user-friendly frontend GUI, and/or adopt their approaches to expand upon Jan's current retrieval implementation.

**Comment by Van-QA** [comment]
https://github.com/janhq/cortex/issues/680

**Comment by imtuyethan** [comment]
Duplicated
