### ISSUE TITLE
bug: Unable to install TensorRT-LLM (additional dependencies)

### ISSUE THREAD

**Issue by micisse** [janhq/jan#3016]
**Describe the bug**
Unable to install TensorRT-LLM (additional dependencies). It's a bug I've been noticing for a while, and I wanted to be sure before creating a ticket. It's all summed up in the attached video.

https://github.com/janhq/jan/assets/56940294/07495a6c-4c21-4665-9446-b5f7306182de

**Expected behavior**
It must be possible to install model providers (e.g. Nvidia's TensorRT-LLM) (additional dependencies).

**Environment details**
- Operating System: Ubuntu 22.04.4 LTS
- Jan Version: Jan v0.5.0 (not nightly)
- Processor: Intel(R) Core(TM) i7-10870H
- RAM: 32GB
- Any additional relevant hardware specifics: NVIDIA GeForce RTX 3060

**Additional context**
I'm using the .AppImage

**Comment by Van-QA** [comment]
Thank you, the issue is reprod‌uc‌ible on Nightly Jan v0.5.0-476 :x:
![image](https://github.com/janhq/jan/assets/64197333/6217f250-ee20-4f9a-9780-a05014dc0b50)

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.

**Comment by micisse** [comment]
In **nightly** version, i can't open app as before in the **stable** version... it may be related to https://github.com/janhq/jan/issues/3263. In my case, i have "Waiting for cortex", i can't start cortex manually, i've an error... http://localhost:1337/v1 is not accessible... My node version is v22.1.0 on Linux .AppImage


![Capture d’écran_2024-08-05_14-09-52](https://github.com/user-attachments/assets/757df604-7d76-474e-99bd-b38b64d26d7f)
![Capture d’écran_2024-08-05_14-11-00](https://github.com/user-attachments/assets/0bbed924-a5be-41d5-919b-8f7468f5a6eb)
![Capture d’écran_2024-08-05_14-17-13](https://github.com/user-attachments/assets/6bcefda7-30a2-4782-a3b8-6c53c366aa94)
