### ISSUE TITLE
feat: Default Settings For New Thread

### ISSUE THREAD

**Issue by SimplyYourAverageDev** [janhq/jan#3022]
**Problem**
Pretty annoying whenever I open a new Jan thread, I would have to set everything again myself, would be great if I can just have a default settings.

**Success Criteria**
We have a "Default Settings" Option in the Settings configuration to set the default temperature, system prompt, Top_P and etc.

**Comment by Van-QA** [comment]
will be resolved via https://github.com/janhq/cortex/issues/617, stay tuned 🙏
