### ISSUE TITLE
chore: Minor copy edits for model settings section

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3025]
# Key user stories

### 1. Renaming some categories

- Inference Parameters → Inference Settings
- Model Parameters → Model Settings
- Engines Parameters → Engine Settings
<img width="148" alt="Screenshot 2024-06-11 at 8 41 03 PM" src="https://github.com/janhq/jan/assets/89722390/95ce2169-7cac-42b1-821c-7f6df228663d">

- [ ] #3536

**Comment by 0xSage** [comment]
@imtuyethan pls break up into 2 separate tickets
