### ISSUE TITLE
bug: Local API Server bad instance when using /chat/completions

### ISSUE THREAD

**Issue by RamosBruno** [janhq/jan#3029]
Hello ! 

**Describe the bug**
When I run locally the API and i try with postman/bruno or VS Code directly I have a message error "The readableStream argument must be an instance of ReadableStream. Received an instance of PassThrough"

**Steps to reproduce**
1. Go to Local API Server
2. Click on start server
3. Open a web browser & go to the http://localhost:1337 
4. Scroll down to "/chat/completions"
5. Click on "Try it out"
6. Click on "Execute"
7. See the error

**Expected behavior**
I'm expected the example to work and then interact with the model in VS Code

**Screenshots**
<img width="1187" alt="Capture d’écran 2024-06-12 à 14 51 27" src="https://github.com/janhq/jan/assets/1148220/50d8778a-a8b9-4d66-89fb-15e02fceb41c">

**Environment details**
- Operating System: Mac OS Sonoma 14.5
- Jan Version: 0.5.0
- Processor: Apple M2
- RAM: 32GB

**Comment by Van-QA** [comment]
hi @RamosBruno,

Can you let us know which model you are using?
Thank you

**Comment by Van-QA** [comment]
<img width="852" alt="image" src="https://github.com/janhq/jan/assets/64197333/c493f069-2a0d-442b-96bf-659ad35695c3">
<img width="1432" alt="image" src="https://github.com/janhq/jan/assets/64197333/2e9a2d7b-4ec2-444b-b351-c4959f523970">
Can you help me confirm the JSON bod‌y that I used was similar to what you used? It's working on my side so we are still investiga‌ting.
Thank you

**Comment by RamosBruno** [comment]
Hello, 

Here what you asked : 

Body : 

<img width="437" alt="Capture d’écran 2024-06-14 à 11 26 50" src="https://github.com/janhq/jan/assets/1148220/87eaec3a-388e-4040-ab19-171e8115e3d4">

Response : 

<img width="1408" alt="Capture d’écran 2024-06-14 à 11 27 26" src="https://github.com/janhq/jan/assets/1148220/0e05edb6-0dad-4bd1-993e-88c8b14925dd">

**Comment by Van-QA** [comment]
Thank @RamosBruno,
I was ‌unable to call the API using "Codestral-22B-v0.1-Q4_K_M" but ‌it's working using: 
`Codestral-22B-v0.1-Q4_K_M.gguf`
<img width="1391" alt="image" src="https://github.com/janhq/jan/assets/64197333/1921c6da-703f-4383-a3c8-f783b2e341e2">

Can you try this a‌s well, and see if the issue is‌ resolved ‌or not? 



‌For each m‌‌ode‌ls, you will be able to find the v‌alue in the my model sett‌ing:
<img width="1462" alt="image" src="https://github.com/janhq/jan/assets/64197333/149eb5c3-e78a-4399-9f54-15e9bf152c56">
Or in the model.json
<img width="699" alt="image" src="https://github.com/janhq/jan/assets/64197333/d24cf6e8-696a-455d-8d47-3ff1862ce0c1">

**Comment by RamosBruno** [comment]
@Van-QA thanks for your answers

But as you can see in my previous screen with models name i don't have the extension

When I try to download with huggingface i have this error popping

<img width="1725" alt="Capture d’écran 2024-06-14 à 14 46 53" src="https://github.com/janhq/jan/assets/1148220/f405b79c-720c-4e7b-ae8e-cced1518fc94">

I'll try to clean install jan looks like something went wrong when updating from 0.4.X to 0.5.0

**Comment by RamosBruno** [comment]
> Easy way to replicate this issue on any instance (I'm running 0.5.1):
> 
>     1. Go to http://127.0.0.1:1337/static/index.html
> 
>     2. Scroll to /chat/completions
> 
>     3. Click on 'Try It out'
> 
>     4. Click on 'Execute'
> 
>     5. Observe:
>        404Undocumented | Error: Not FoundResponse bodyDownload{   "statusCode": 404,   "code": "ERR_INVALID_ARG_TYPE",   "error": "Not Found",   "message": "The "readableStream" argument must be an instance of ReadableStream. Received an instance of PassThrough" }

Hey ! 
Do you try to remove the folder in the home folder as I said in my last message and try to clean install jan ?

**Comment by igor-elbert** [comment]
@RamosBruno , removed the folder and reinstalled but no dice - same error.
