### ISSUE TITLE
bug: AI responses are going gibberish after few prompts (3-5 prompts) on Windows 10

### ISSUE THREAD

**Issue by msocialdev** [janhq/jan#3030]
**Describe the bug**
AI responses when using UI & API are gibberish after roughly 5 prompts, when I Unload and Reload the model it works again and again goes gibberish very soon.

It actually is working fine on my Macbook pro with an M1 pro, but failing very fast on my windows PC.

**Steps to reproduce**
1. I installed Jan on my Windows PC (downloaded from Github latest release)
2. Downloaded Qwen 1.5 7B Q4 and tried a chat
3. Also tried starting the API and tested on Postman.
4. Responses are fine at start and soon started responding in random words and shorter output lengths
5. same happens when I start a new thread afterword with the model loaded
6. Interestingly same thing happened when i tried other models too (like: Hermes Pro Llama 3 8B Q4)

**Expected behavior**
I was expecting a response with understandable English. I tried same model through a server API on together.ai it responds great even with large contexts and repeated requests. 

**Screenshots**
screen shot of chat going gibberish
![image](https://github.com/janhq/jan/assets/113271868/a0e92f5b-b324-4965-b310-55186ac5fd12)

screenshot of chat in new thread with model still loaded (so you know it is not chat history dependent)
![image](https://github.com/janhq/jan/assets/113271868/52245205-8d01-48e9-a531-6f5f94073872)

**Environment details**
- Operating System: windows 10
- Jan Version: v0.5.0
- Processor: Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz, 4001 Mhz, 4 Core(s), 8 Logical Processor(s)
- RAM:16GB
- GPU - Nvidia RTX 3080Ti
- Jan GPU acceleration is ON
- Model tried Qwen 1.5 7B Q4

**Logs**
Here are the Logs when working with the chat
[app.log](https://github.com/user-attachments/files/15807306/app.log)

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
