### ISSUE TITLE
Unable to load models

### ISSUE THREAD

**Issue by someusernamee** [janhq/jan#3031]
Just installed Jan and downloaded Llama 3 8B through Jan. The model is listed as "inactive" once downloaded, but when I try to set it to Active it refuses to do so. Should I avoid downloading models through Jan and just download them directly through Hugging Face instead?

**Comment by Van-QA** [comment]
hi @someusernamee, can you h‌elp us pro‌‌vide more inf‌o to inves‌ti‌gate? going through this form might help 🙏 https://github.com/janhq/jan/issues/new?assignees=&labels=type%3A+bug&projects=&template=bug_report.yml&title=bug%3A+%5BDESCRIPTION%5D

**Comment by kalle07** [comment]
same issue !!!  v0.5.0
not be able to load any model

V 0.4.9  all works more or less
only v1.0 versions can be loaded

![grafik](https://github.com/janhq/jan/assets/118767589/e3ef08c1-6f0d-445c-b0a2-6443345fa467)

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
