### ISSUE TITLE
feat: Add Model License to Model dropdown in Hub tab

### ISSUE THREAD

**Issue by Sickday** [janhq/jan#3038]
- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's very easy to download and use the models available on the hub, but users will have to search the web to find out what the License is used for the model they download. 

### Describe the solution you'd like

I think it would benefit users to see the License name or hyperlink to the license within the same form where a model is displayed. 

### Teachability, documentation, adoption, migration strategy

As long as it's visible within the model selector, I think this would fit well.
<img width="827" alt="Screenshot 2024-06-13 at 8 33 22 AM" src="https://github.com/janhq/jan/assets/30793532/e4e6fa93-cd8b-4196-8413-c512afd08f87">

### What is the motivation / use case for changing the behavior?

As an example, this would help avoid confusion when the model is used for a creative work that a user then wants to publish. As it currently stands, it will be unclear whether the content generated by the AI is usable in a commercial setting unless the user reviews the License for the model and the content it generates.

**Comment by imtuyethan** [comment]
![Screenshot 2024-07-03 at 12 44 41 AM](https://github.com/janhq/jan/assets/89722390/5b139b7f-46e8-4f2b-b3a3-bbde694a9ea4)
Thanks for raising this! This will be solved once #2590 is completed. I'll mark this ticket as duplicated.
