### ISSUE TITLE
feat: also show undownloaded models in Model Tab > Model Selector Dropdown

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3043]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Right now search result only shows what model i have downloaded

### Describe the solution

I should be able to search by configured model
Ex:
- I search "Llama"
- Show all related models: model i downloaded first -> model i havent downloaded

### What is the motivation / use case for changing the behavior?

Original design was i dont need to go to Hub
Hub is for when i want to read model info more in details
if i already knew what model i want -> search -> download 

![Uploading image.png…]()

**Comment by Van-QA** [comment]
@urmauur, current UI is: **n‌ot‌** downloaded modeld > downloa‌‌‌ded models, can you double che‌ck? I think @imtuyethan w‌ant the downloaded models on top 

![Image](https://github.com/janhq/jan/assets/64197333/2ea8ec27-3949-4093-858b-6d8e0d5d8600)

**Comment by Van-QA** [comment]
Af‌ter the rollback of Jan x Cortex, only whe‌‌n users is not ‌having any m‌odel‌, th‌e‌y can search via the dropdown. But w‌hen there are models a‌‌vailable, then the re‌com‌‌mendation for download is n‌o longer visible :x: @urmauur 
![image](https://github.com/user-attachments/assets/263dd8f0-d601-40bc-b87d-c71924e46c36)

**Comment by imtuyethan** [comment]
> @imtuyethan I think this issue needs a bit more planning and is currently not well thought out.
> 
> It sounds like you want to:
> 
> Goal: improve discoverability from the Model Selector Dropdown , without users having to navigate to Hub.
> 
> Questions:
> 
> 1. Then shouldn't we also allow users to set up remote model API keys in the dropdown?
> 2. When users click download from within dropdown, what does UI look like?
> 3. Do we show all quantizations? It will be a long list...
> 4. What if users want to see more information? How will they get to hub from model selector

Ah this one is done on v0.5.3-628. 

I think this one is a killing feature because of how convenient it is:

### Scenario 1:
- I have a list of available model
- I have a specific model in mind that i don't have yet
- I search for it -> download it directly without having to go to Hub
Hub is for model discovery, not for when i already have a specific model in mind. 

### Scenario 2:
- I want to use Mistral Instruct because i though i had it
- I search for it then realize I haven't downloaded it yet -> Download it directly
Normally when i search for it and don't see it, i have to go to Hub & search & download & then come back to threads, so many steps...

https://github.com/user-attachments/assets/0994c6b2-d434-438d-849e-5600ad76e24e
