### ISSUE TITLE
[spike] plugin repository & versioning

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#305]
Plugins are now delivered to users via app package.

- How we can update a plugin without asking user to update or reinstall the app?
- How we let developers submit their plugins and recommend our users to install (or explore themselves)?

Q: 
- Is it possible to have `npm-install-like` in run time? so we can just upload to npm repo
- If not, does github release help? (same as app update mechanism)

**Comment by louis-jan** [comment]
cc @hiento09 since you will lead this ❤

**Comment by 0xSage** [comment]
@hiento09 any updates on this?

**Comment by hiento09** [comment]
@0xSage , I updated the github workflow in this PR https://github.com/janhq/jan/pull/321

**Comment by hiento09** [comment]
The following task for this issue:

- [ ] Create NPM repository for jan (janhq)
- [ ] Create github action workflow to publish npm package to npm repository
- [ ] Research a method to install plugin using npm

**Comment by 0xSage** [comment]
Nice, can we add documentation to this task as well?

This page is meant to take an OpenAPI spec and autogenerates documentation:
https://jan.ai/api
