### ISSUE TITLE
feat: Request for Persistence of Instructions for Assistant Across New Threads

### ISSUE THREAD

**Issue by flazouh** [janhq/jan#3050]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, when I open a new thread (which I do many times a day to manage token usage and avoid manually clicking "Clean Thread"), the assistant does not retain the instructions from the previous thread. This disrupts my workflow and requires me to re-enter the same instructions repeatedly.

### Describe the solution

I would like to request a feature that allows the instructions for the assistant to persist across new threads. This would streamline the process and save considerable time and effort in my daily usage. Users would benefit from having a setting or option to enable persistence of instructions across new threads. This could be documented in the user guide and would not require a complex migration strategy since it enhances the current functionality without altering the existing workflow.

### What is the motivation / use case for changing the behavior?

Currently, when I open a new thread (which I do many times a day to manage token usage and avoid manually clicking "Clean Thread"), the assistant does not retain the instructions from the previous thread. This disrupts my workflow and requires me to re-enter the same instructions repeatedly.

Workflow Example:

I type a question and receive an answer.
I press Cmd+N to open a new thread.
I type another question.
Each time I open a new thread, the previous instructions are lost, necessitating re-entry.

Request:

I would like to request a feature that allows the instructions for the assistant to persist across new threads. This would streamline the process and save considerable time and effort in my daily usage.

Potential Benefits:

Improved efficiency and ease of use.
Reduced redundancy in re-entering instructions.
Enhanced user experience, especially for those who open multiple threads frequently.
Thank you for considering this request. I believe it would be a valuable addition to the tool and significantly enhance user productivity.

**Comment by Van-QA** [comment]
Resolved as of Jan v0.5.2-578
