### ISSUE TITLE
feat: Jan Hub lists models downloaded from Ollama and OpenRouter

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3065]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Downloading the same models more than once. There is a need to find an efficient way to list AI models downloaded from Ollama and OpenRouter.

Related comment: If you already have the models in Ollama why do you need to use the Jan model hub though? I would have thought I could add my Ollama server(s), be presented with a list of models I can select from, but Jan doesn't seem to do this - you have to add an OpenAI compatible API endpoint, then browse a model hub and download models that you seem to already have downloaded which is confusing?

### Describe the solution

Implement a feature in Jan Hub that allows users to easily list models downloaded from Ollama and OpenRouter.

### What is the motivation / use case for changing the behavior?

This feature would make finding and downloading AI models easy and improve user experience.

**Comment by imtuyethan** [comment]
I'll mark this as duplicated to #2318
