### ISSUE TITLE
bug: CUDA toolkit info bar redirects users to homepage

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3066]
### #

- [ ] I have searched the existing issues

### Current behavior

"The CUDA toolkit may be unavailable. Please use the Install Additional Dependencies setting to proceed with the download / installation process." info redirects users to jan.ai.

### Minimum reproduction step

System Monitor

### Expected behavior

The link should direct the user to the appropriate resource or page to download/install the additional dependencies for the CUDA toolkit.

### Screenshots / Logs

blank

### Jan version

0.5.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
I'm not sure what is the case here, currently, the redirect is navigating users to the settings within Jan app for the installation. Working fine for both Linux and Windows.
Can you elaborate more on the issue? @eckartal 
Thank you
