### ISSUE TITLE
feat: Improve model import functionality with path specification and multiple folder support

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3067]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Users are currently unable to specify a directory path for importing local gguf models, relying instead on drag-and-drop functionality, which may not work with every backend. Additionally, the current system does not support adding multiple pointers to different folders, which could be useful for organizing text vs. vision models.

### Describe the solution

Implement a feature that allows users to specify a directory path for importing local gguf models. Additionally, enable the ability to add multiple pointers to different folders for better organization and ease of access.

### Teachability, documentation, adoption, migration strategy

Provide clear documentation on how to use the new path specification and multiple folder support features. Ensure that the implementation is straightforward and easily adoptable by users.

### What is the motivation / use case for changing the behavior?

This feature would improve the flexibility and usability of the tool - it allows users to import models more efficiently and organize them according to their needs. It'd also reduce the dependency on drag-and-drop functionality.

**Comment by Van-QA** [comment]
should be resolved after https://github.com/janhq/jan/issues/2817
