### ISSUE TITLE
bug: Inaccurate performance info models in Jan Hub

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3068]
### #

- [ ] I have searched the existing issues

### Current behavior

The info boxes that indicate whether a computer can handle an AI model are providing inaccurate information. For example, it incorrectly states that Llama3 8B and tinyllama 1.1B models run slowly, even though Llama3 8B runs at 10 T/s and tinyllama 1.1B performs well.

### Minimum reproduction step

Jan -> Jan Hub

### Expected behavior

Fix the algorithm or criteria used to determine and display the performance of AI models in the info boxes to ensure they accurately reflect the actual performance and capabilities of the user's system.

### Screenshots / Logs

.

### Jan version

0.5.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
depending on https://github.com/janhq/jan/issues/2734
