### ISSUE TITLE
feat: Jan supports Anthropic's Claude Sonnet 3.5

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3070]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Jan supports Anthropic's new AI model, Claude Sonnet 3.5

### Describe the solution

https://x.com/AnthropicAI/status/1803790676988920098

### What is the motivation / use case for changing the behavior?

More models.

**Comment by danwritecode** [comment]
guys there should be a simple way for power users to just enter the model name when there are new model releases. it's a shame not being able to use your product because i'm waiting on a pull request to be made when i could just enter a model name and be up and running. 

i get you want to vet and test new models, but if someone wants to override the default models, that's on them.

**Comment by DenisGorbachev** [comment]
@hahuyhoang411 Is it possible to release the version with Sonnet 3.5 please? It's more powerful than GPT-4o.

**Comment by eggsyntax** [comment]
For whoever ends up working on this: I tried doing the naive thing, adding the following to the [Anthropic models.json file](https://github.com/janhq/jan/blob/6f5de561eafef152227aae4a80873e0bf6d7b7ff/extensions/inference-anthropic-extension/resources/models.json) (locally) and rebuilding with `make dev`:

```
  {
      "sources": [
          {
              "url": "https://www.anthropic.com/"
          }
      ],
      "id": "claude-3-5-sonnet-20240620",
      "object": "model",
      "name": "Claude 3.5 Sonnet",
      "version": "1.0",
      "description": "Claude 3.5 Sonnet is the June 2024 version of Anthropic's mid-sized model.",
      "format": "api",
      "settings": {},
      "parameters": {
          "max_tokens": 4096,
          "temperature": 0.7,
          "stream": false
      },
      "metadata": {
          "author": "Anthropic",
          "tags": [
              "General",
              "Big Context Length"
          ]
      },
      "engine": "anthropic"
    },
```

but 3.5-Sonnet still doesn't show up as an available model in the app. I'm guessing there's a remote list being checked, maybe on HF? Or an additional build step other than `make dev`?

I haven't taken time to dig into the overall app, just had a bit of time to spare to try the simple thing, sharing in case it's of use.

**Comment by joshuabrandes** [comment]
I did the exact same thing. Doesn't work for me as well @eggsyntax

**Comment by robertfall** [comment]
> i get you want to vet and test new models, but if someone wants to override the default models, that's on them.

Right now I'm looking at switching away from LibreChat to a different tool and not being able to choose my own models makes Jan a non-starter for me. 

Overall it looks like a great app, but this seems like an obvious feature.

**Comment by corwin1949** [comment]
Indeed, we need to be able to use models by filling in strings, otherwise, every time there is a big model upgrade in the future jan won't be able to support it in the first place.

It would be nice to be able to automatically get which models are available on the port.

**Comment by 0xSage** [comment]
@louis-jan to think throug hhow to handle

**Comment by Van-QA** [comment]
![image](https://github.com/user-attachments/assets/38aa93ee-9bf5-498d-bf91-c8ced1ac6028)
Jan supported Cla‌ude 3.5, feel free t‌o get back to ‌us if any issue

**Comment by dsjacobsen** [comment]
@Van-QA Which version supports it? The latests version (Jan Version v0.5.2) does not show the model. 

<img width="295" alt="Skærmbillede 2024-08-23 kl  10 15 50" src="https://github.com/user-attachments/assets/4c2ad87b-23d6-43e6-9309-d84bf0cbd958">

**Comment by Van-QA** [comment]
@dsjacobsen, sorry for the inconv‌enience, Jan 0.5.2 already supported i‌t. If possibl‌e, can you going to the Jan data folder, 

<img width="1598" alt="image" src="https://github.com/user-attachments/assets/39e7eb6c-99d0-41f7-93db-9c8901353908">

and ‌wipe the extensions folder, and restar‌t Jan, I hope it will help resolve your issue
<img width="780" alt="image" src="https://github.com/user-attachments/assets/da8ce8cb-9928-4034-893f-0a02200e57b4">

**Comment by dsjacobsen** [comment]
@Van-QA Awesome thanks. It works!
