### ISSUE TITLE
feat: Reset parameter option

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3074]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is currently no option to reset parameter values to their default settings, which makes it difficult to revert changes or start fresh.

### Describe the solution

Add a "Reset to Default" button or option that allows users to revert all parameter values to their original default settings.

### What is the motivation / use case for changing the behavior?

This feature would enhance user experience by providing a quick and easy way to undo changes or troubleshoot issues by starting with the default configuration.

**Comment by imtuyethan** [comment]
This would be solved after #2845 is done
