### ISSUE TITLE
bug: setting for install missing dependencies should be visible for all users with GPU

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3085]
Description:
We have received reports that some users with GPU are not seeing the error message prompting them to install necessary dependencies within Jan app. issue is preventing them from using the app properly.

Expected Behavior:
Make sure that the setting to install are visible by default for all users with GPU 

Screenshots:
![image](https://github.com/janhq/jan/assets/64197333/f0a6894d-bc66-4dd8-a203-02c5d7cf59e3)

**Comment by Van-QA** [comment]
@urmauur, not sure how this is happening :x:
![image](https://github.com/janhq/jan/assets/64197333/fab6462f-b632-4617-a0cf-f8c972c46c92)

**Comment by urmauur** [comment]
will double check @Van-QA

**Comment by Van-QA** [comment]
![image](https://github.com/janhq/jan/assets/64197333/be53645a-7404-412b-b519-f8083b1b21b0)
@urmauur, can you double check the tensorRT as well
