### ISSUE TITLE
feat: Improving Jan's data folder option

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3095]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, there is no option to specify custom install folders for libraries and config files in Jan, requiring users to manually move them and create symbolic links.

### Describe the solution

- Allow users to specify custom install folders for libraries (e.g., C:\Users\UserID\AppData\Local\Programs\jan).
- Allow users to specify custom install folders for config files (e.g., C:\Users\UserID\jan).

### What is the motivation / use case for changing the behavior?

This feature would enhance user convenience by eliminating the need to manually move files and create symbolic links

Related Reddit post: https://www.reddit.com/r/janframework/comments/1dl9r5w/suggestion_custom_install_folders_win/

**Comment by 0xSage** [comment]
This is already supported @eckartal 

Advanced Settings > Jan Data Folder > click pencil

<img width="891" alt="image" src="https://github.com/user-attachments/assets/afa0ee32-027f-47e2-b9d2-5b248b852e99">
