### ISSUE TITLE
feat: jan-git / jan-nightly AUR package

### ISSUE THREAD

**Issue by OmegaLambda1998** [janhq/jan#3099]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently, jan is available in the Arch User Repository as a pre-built [binary](https://aur.archlinux.org/packages/jan-bin), and an [appimage](https://aur.archlinux.org/packages/jan-appimage). The binary is (at the time of posting) jan version 0.5.1-1, whilst the appimage is version 0.4.11-1. It would be great to have a third options, which packages the nightly release too

### Describe the solution

Create and maintain a [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=jan-bin) for the nightly release of jan.

### What is the motivation / use case for changing the behavior?

Easier access to nightly release = faster access to new / experimental features, and faster turn-around for bugs

**Comment by imtuyethan** [comment]
- Deprecated as #4237
