### ISSUE TITLE
feat: add more customization for default color themes

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3100]
@urmauur This ticket is nice to have, let me know when you're about to work on it then i'll explain.

# Motivation
Improve the current settings:
- Allow users to adjust transparency settings
- Allow users to adjust custom colors/themes

# Designs
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=4300-47477&t=AzUvKzZfEs3Ez4nw-4
![Screenshot 2024-06-24 at 8 05 23 PM](https://github.com/janhq/jan/assets/89722390/2e65013c-baec-4f7d-927d-fae1ad914ff3)

**Comment by 0xSage** [comment]
Related #3600

**Comment by imtuyethan** [comment]
- Closed & move it to https://github.com/janhq/jan/issues/3600 as a sub-task
