### ISSUE TITLE
feat: Use OpenRouter Default Model instead of OpenRouter/auto

### ISSUE THREAD

**Issue by RONNCC** [janhq/jan#3110]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Currently Jan defaults to using "openrouter/auto" which costs money.

### Describe the solution

It may be better if Jan instead **does not pass** a model parameter.

This would make OpenRouter fallback to the default model chosen in settings which could be a free model
![image](https://github.com/janhq/jan/assets/1313566/a15fd8b3-671d-4597-9bd0-e98009eafaca) or it also could also be set to `openrouter/auto` which would be the same as the current functionality.

### Teachability, documentation, adoption, migration strategy

Users will be able to use this the same way as the current OpenRouter model.

### What is the motivation / use case for changing the behavior?

So I can use the free models on OpenRouter

**Comment by RONNCC** [comment]
Change would just require removing "openrouter/auto" in the pertinent transformPayload function

**Comment by tmobilon** [comment]
Why not show a dropdown so the user can choose between all the available models in Openrouter?

**Comment by RONNCC** [comment]
@tmobilon Sounds great but seems more complicated to implement?

**Comment by RONNCC** [comment]
@hahuyhoang411 wondering if y'all would be open to the above change? I can write up a PR?

**Comment by josemnbcamacho** [comment]
Why not allow for all the OpenRouter available models? It is possible to list all the available models via API at https://[openrouter.ai/api/v1/models](https://openrouter.ai/api/v1/models)

**Comment by RONNCC** [comment]
@josemnbcamacho @ghz those all require a lot more work and interfacing with the JanHQ UI to make that happen.

**Comment by Van-QA** [comment]
As of nightly Jan v0.5.2-603, the open router now redirected to default instead of auto
