### ISSUE TITLE
feat: support Beam search ("Best of") setting

### ISSUE THREAD

**Issue by walking-octopus** [janhq/jan#3112]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Beam search is a known technique used to enhance LLM inference, especially in tasks requiring reasoning, at a great cost to performance. ChatGPT has been suspected of using it.

### Describe the solution

llama.cpp does support it. All that would be needed is to add somewhere in inference config.

### What is the motivation / use case for changing the behavior?

Example: mathematical problems. Global probability maximization allows the model to catch and prune erroneous paths, since eventually they lead to less probable chains of thought than their incorrect counterparts.

**Comment by dan-homebrew** [comment]
@walking-octopus I am merging this into #3508 (Jan) and https://github.com/janhq/cortex.cpp/issues/1151 (Cortex.cpp)

- If Beam is supported in main branch of llama.cpp, we will support
- See https://github.com/janhq/cortex.cpp/issues/1151#issuecomment-2342666554
