### ISSUE TITLE
bug: threads lose titles on rename

### ISSUE THREAD

**Issue by bogorad** [janhq/jan#3116]
### #

- [X] I have searched the existing issues

### Current behavior

a  thread which title has previously been changed, reverts to unnamed ("new thread", later auto-renamed based on content), when cleaned.

### Minimum reproduction step

1. create a new thread
2. rename it to "something" via kebab-menu
3. clean thread via kebab-menu

### Expected behavior

the name "something" should stick, but instead it resets to "new thread".

### Screenshots / Logs

n/a

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Environment details

Win10 or Fedora-40, i5, 64 GiB RAM.

**Comment by Van-QA** [comment]
Hi @bogorad, when cleaning any thread, we are expecting all details of the thread to be gone, including the thread title.
Feel free to add more context/reopen the ticket if needed.
For now, this is the correct behavior of the clean thread function

**Comment by bogorad** [comment]
This is incorrect! When after clearing, you edit it, the old name of the thread reappears.

**Comment by Van-QA** [comment]
thank you, i‌t's reproducible: 
<img width="1066" alt="image" src="https://github.com/janhq/jan/assets/64197333/ac9525f9-c360-4e20-862a-b4e8bb38af87">
Steps:
1. U‌‌pda‌te thread name
2. Clean threa‌d
3. E‌dit the thread name again, and see the popup value i‌s ‌still using the thread name from #1 :x:

**Comment by Van-QA** [comment]
@urmauur the issue is still happen on latest Jan x Cortex
