### ISSUE TITLE
feat: Privacy Settings Page & Analytics Permission Pop-up

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3119]
# Requirement
Users can opt in & opt out of all analytics collections.

# Design 
@urmauur 
Figma link: 
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=9161-147693&t=51XHlMGjLkW3S7vK-4

## Permission pop-up
3 seconds after opening the app, Jan shows this pop-up to all users:

<img width="705" alt="Screenshot 2024-11-27 at 5 12 57 PM" src="https://github.com/user-attachments/assets/28499f9e-d8f9-4517-bd3c-ac885395d66d">

It is a one-time pop-up. 

## Privacy settings page
- Privacy will have its own page & register on left sidebar
- User can opt in & opt out of all analytics collections
- Move Logs & Clear Logs to this page
<img width="746" alt="Screenshot 2024-11-27 at 5 14 39 PM" src="https://github.com/user-attachments/assets/f32c41c4-13f4-42bc-b6bc-562e75054bf2">

**Comment by dan-homebrew** [comment]
Changing this scope to "Opt-in Analytics and Crash Reporting" to better articulate focus.

**Comment by eckartal** [comment]
https://github.com/janhq/jan/issues/3503#issuecomment-2490036831

**Comment by imtuyethan** [comment]
Archive original specs:
---

# Specs
- users can opt out all analytics collection

<img width="972" alt="Screenshot 2024-11-26 at 12 06 37" src="https://github.com/user-attachments/assets/6fdae364-f2f4-44d0-bd8f-4258d6f50683">

## Copy: in-app Privacy Page

We prioritize your control over your data. Learn more about our Privacy Policy.

To make Jan better, we need to understand how it’s used - but only if you choose to help. You're free to change Jan Analytics settings.

Your choice to opt-in or out doesn’t change our core privacy promises:

- Your chats are never read
- No personal information is collected
- No accounts or logins required
- We don’t access your files
- Your chat history and settings stay on your device

**Performance Reports**
By opting in, you help us make Jan better by sharing anonymous data, like feature usage and user counts. Your chats and personal information are never collected.
