### ISSUE TITLE
bug: Converting circular structure to JSON

### ISSUE THREAD

**Issue by danny-su** [janhq/jan#3120]
### #

- [X] I have searched the existing issues

### Current behavior

```
curl -X 'POST' \
  'http://localhost:1234/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "messages": [
    {
      "content": "You are a helpful assistant.",
      "role": "system"
    },
    {
      "content": "Hello!",
      "role": "user"
    }
  ],
  "model": "command-r-plus",
  "stream": true,
  "max_tokens": 2048,
  "stop": [
    "hello"
  ],
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "temperature": 0.7,
  "top_p": 0.95
}'
```

`{"statusCode":500,"error":"Internal Server Error","message":"Converting circular structure to JSON\n    --> starting at object with constructor 'Socket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle"}`

### Minimum reproduction step

1) Start Server
2) Issue an HTTP request

### Expected behavior

N/A

### Screenshots / Logs

<img width="1055" alt="Arc 2024-06-29 19 07 38" src="https://github.com/janhq/jan/assets/12178855/18f17181-aa01-4b4f-832c-16491b60fccc">

<img width="1102" alt="image" src="https://github.com/janhq/jan/assets/12178855/ace8a924-774c-4e62-bb8b-d19ef9d8c4f7">

### Jan version

v0.5.1

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
Duplicated with #2944. please follow up in that ticket
