### ISSUE TITLE
bug: avoid 2nd remote API request to generate thread titles

### ISSUE THREAD

**Issue by FireCalcPro** [janhq/jan#3121]
## Goal 

- When using remote API, we should not send 2nd inference request to generate thread title (costs $$, especially for long requests)
    - Just use 1st request text as thread title 
- This is different from Local AIs, where the 2nd thread generation request is local and cost-less

## Alternatives considered

- Settings page: rejected b/c introduces complexity

## Original Issue
```
### #

- [X] I have searched the existing issues

### Current behavior

If you do not set a title to a new chat thread before sending a message to the Claude Sonnet 3.5 API, you will be sending duplicate inputs. Please consider adding a check or force user to input a new title before sending a message.

### Minimum reproduction step

Add Claude Sonnet 3.5 Model
Create new chat
Don’t edit the chat title
API shows duplicate inputs

### Expected behavior

Send a single input even if you forget to change the title.

### Screenshots / Logs

Jun 27, 2024, 10:58 AM    claude-3-5-sonnet-20240620    1.41    1046    22    http    None
Jun 27, 2024, 10:58 AM    claude-3-5-sonnet-20240620    3.89    1028    159    http    None
Jun 27, 2024, 10:50 AM    claude-3-5-sonnet-20240620    16.14    22595    1117    http    None
Jun 27, 2024, 10:50 AM    claude-3-5-sonnet-20240620    12.92    25658    853    http    None
Jun 27, 2024, 10:46 AM    claude-3-5-sonnet-20240620    11.73    22595    704    http    None
Jun 27, 2024, 10:46 AM    claude-3-5-sonnet-20240620    12.84    22577    699    http    None
Jun 27, 2024, 10:44 AM    claude-3-5-sonnet-20240620    0.92    401    19    http    None
Jun 27, 2024, 10:44 AM    claude-3-5-sonnet-20240620    6.77    383    401    http    None


### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

_No response_
```

**Comment by Van-QA** [comment]
hi @FireCalcPro, most likely the case is due to the auto generate thread title feature. We will follow up on this, but for now, you can work around by auto providing thread title manually, before chatting with Claude 
![image](https://github.com/janhq/jan/assets/64197333/4af0997f-21af-4d1a-96a0-515b61757f5e)

**Comment by Van-QA** [comment]
We will resolve this issue by i‌‌ntrod‌‌ucing a new settings, that allow users ‌to disable thread title auto gen‌eration for all remote model, so that they can save API key credit‌s.
Settings:
> Automatically generate thread title with all remote models. 
> Turning this off disables the auto-generation feature for any thread title using remote models.
Feel free to make mo‌dification if needed

**Comment by louis-jan** [comment]
cc @imtuyethan for the product roadmap.

**Comment by dan-homebrew** [comment]
I would recommend a clearer Product fix for this: 

- Local Model: we generate Thread Title using 2nd inference request (which is costless)
- Remote model: we just use the initial Prompt as the Thread Title (i.e. no inference cost). The same animation, etc should apply

From my POV this is a more elegant way to solve the problem, without adding more complexity to settings. 

Wdyt? @imtuyethan @louis-jan @Van-QA

**Comment by imtuyethan** [comment]
> I would recommend a simpler Product fix for this:
> 
> * Local Model: we generate Thread Title using 2nd inference request (which is costless)
> * Remote model: we just use the initial Prompt as the Thread Title (i.e. no inference cost). The same animation, etc should apply
> 
> From my POV this is a more elegant way to solve the problem, without adding more complexity to the app.
> 
> Wdyt? [@imtuyethan](https://github.com/imtuyethan) [@louis-jan](https://github.com/louis-jan) [@Van-QA](https://github.com/Van-QA)

I agree!

**Comment by dan-homebrew** [comment]
@urmauur I am assigning this to you for Sprint 20 - would like you to start covering simple full stack JS issues in Jan. 

cc @imtuyethan

**Comment by imtuyethan** [comment]
Works perfectly fine on my end (0.5.4-650)


https://github.com/user-attachments/assets/3eb61f74-f45f-4caa-973e-f93478931614
