### ISSUE TITLE
bug: Expected - Edit Global Defaults for the <model_name>, option  not appearing in windows app. . 

### ISSUE THREAD

**Issue by Vampeyer** [janhq/jan#3123]
### #

- [ ] I have searched the existing issues

### Current behavior

bug: Expected - Edit Global Defaults for the <model_name>, option  not appearing in windows app.  

in the  - new thread section ,  this option is not appearing in my windows build to start my model .   

### Minimum reproduction step

Download Jan for windows ,   

and follow the directions listed on the site here  , 
 https://jan.ai/docs/built-in/llama-cpp

Step 1: Open the model.json
Navigate to the Threads.
Click the three dots (:) icon next to the Model.
Select the Edit Global Defaults for the <model_name>.
This will open up a model.json. For example, the model.json of TinyLlama Chat 1.1B Q4 is shown below: 

### Expected behavior

Expected another option as defined clearly in the docs , when hovering over the 
- new threads - 
option , on the windows build. 

### Screenshots / Logs

![Screenshot (92)](https://github.com/janhq/jan/assets/104587177/0e1dac73-522b-4a9c-9e7d-4a8a0feab05a)

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

Windows 10  , AMD Ryzen5 , 16gb  , small GPU 
Nothing out the norm .

**Comment by Van-QA** [comment]
<img width="1642" alt="image" src="https://github.com/janhq/jan/assets/64197333/0c3673cf-78ae-43b7-a1f3-6a8ea46d0191">
hi @Vampeyer, you can go to the Jan data fol‌‌der, find the model and modify i‌t.
‌S‌orry the UI is oudated as we reva‌mp the Jan app 🙏
