### ISSUE TITLE
bug: Why does my Jan.ai always devolve to gibberish

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3137]
### #

- [x] I have searched the existing issues

### Current behavior

https://www.reddit.com/r/LocalLLaMA/comments/1duw2vy/why_does_my_janai_always_devolve_to_gibberish/

### Minimum reproduction step

-

### Expected behavior

-

### Screenshots / Logs

As the Reddit post

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
We are working on a new ver‌sion of Jan x Cortex. So it's recommended to try it via nightly build https://github.com/janhq/jan?tab=readme-ov-file#download. Feel free to get ‌bac‌k to us if the issue remains.
