### ISSUE TITLE
epic: Essential, advanced parameters are missing

### ISSUE THREAD

**Issue by mockinbirdy** [janhq/jan#3140]
It's disappointing to see that essential, advanced parameters like min-p, repetition penalty range, and sample order (etc) can't be adjusted in Jan. Coming from projects like koboldcpp and tavern, where these settings have been implemented for a long time, it feels like a major oversight. 

Will these settings be implemented in future updates?

Or am I just not getting it - is Jan supposed to be a super simple, plug-and-play kinda thing, ditching advanced customization for ease of use? I just had an impression it's an open-source soft with nice, clean ui, chat history and customisable settings. Honestly, even for coding, setting parameters precisely is crucial, and the current functionality falls short compared to other solutions. 

Maybe you could hide the advanced stuff behind some hidden "Advanced" tab? That way, casual users wouldn't even notice, but pros could still dig in and tweak things.

**Comment by 0xSage** [comment]
Related: 
#3112

**Comment by dan-homebrew** [comment]
@mockinbirdy: We are starting to work on this in https://github.com/janhq/cortex.cpp/issues/1151. 

- Thanks for the honest feedback
- Jan -is- optimized for "non-technical users" (i.e. as a ChatGPT alternative)
- However, at this stage of Local AI I fully agree on the need to set parameters
- We will look into how we can hide this behind an "Advanced" slider, to make Jan useful to both power users and "normal user"

**Comment by dan-homebrew** [comment]
@mockinbirdy I'm merging this issue into https://github.com/janhq/jan/issues/3140 and https://github.com/janhq/cortex.cpp/issues/1151 where we are working on this. 

ETA: this sprint
