### ISSUE TITLE
bug: seams talk to docs not optimized

### ISSUE THREAD

**Issue by kalle07** [janhq/jan#3155]
### #

- [X] I have searched the existing issues

### Current behavior

ok if i talk to an dokument only once, or lets say i dont know when is searched again snips in the DOC

Question: Is it possible to set the snipset size and the number of snipsets?

### Minimum reproduction step

ok i ask a question, probably the doc is searched for what iv asked for.
the answer is more or less okay

second question, it seams the doc is not searched again for my new question ...

### Expected behavior

-

### Screenshots / Logs

-

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
We are working on a better ve‌rsion, please follow up using this ticket https://github.com/janhq/jan/issues/3216
