### ISSUE TITLE
feat: Ability to add files from desktop to the chat

### ISSUE THREAD

**Issue by zacharias1219** [janhq/jan#3167]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I wanted to upload some files so that it can help me with some coding part but couldn't find the option so I feel that the ability to add files so that the model can parse through them will be extremely beneficial.

### Describe the solution

I think adding a section to the message box for the ability to add any documents would be good

### What is the motivation / use case for changing the behavior?

I think this feature would make the application better in terms of many different use cases

**Comment by harshkhokhariya** [comment]
Hey just press the 📎 in the side of the chat box

**Comment by zacharias1219** [comment]
![image](https://github.com/user-attachments/assets/2f2f6fb4-15b7-4e85-8552-1649e5ff7300)
Hey I'm usually familiar with that icon that let's us upload, but as you can see in the image, I'm unable to find something like that button, unless I'm missing something or it's only a feature for some models.

**Comment by Van-QA** [comment]
Related to https://github.com/janhq/jan/issues/3216, p‌lease follow up ove‌‌rthere

**Comment by pablocpz** [comment]
I can't use it. It is not working the file uploading button, whereas the image one does
