### ISSUE TITLE
Jan's new starter screen

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3170]
A part of #2817 
Specs: https://www.notion.so/jan-ai/Starter-screen-e34b9d8453a84a1fa522cf98c342af5c?pvs=4

## Objective

Provide the smoothest / white glove experience that guide users through their initial setup.

## Key User Stories

![Screenshot 2024-09-12 at 4 50 33 PM](https://github.com/user-attachments/assets/f295f83a-2642-41c9-a7c3-b36b4330f01c)

This screen will appear when:

- User first downloads & open the app *(they don’t have or set up any model yet)*
- When there’s no model available *(user deletes their on-device models or remove API key of their cloud models)*

This screen aims to guide users how to start

- User can download an on-device model to use or
- User can set up a cloud model

## Designs
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=3744-5043&t=RLqA4BgF96XYZ053-4

Just implement **the second part:** 
![Screenshot 2024-07-16 at 3 54 32 PM 1](https://github.com/user-attachments/assets/a2f5e2eb-7561-40ff-ab3d-7f9d4e739163)

**Comment by Van-QA** [comment]
@urmauur
This is the current UI when opening Jan app, please help correct this :x: https://drive.google.com/file/d/1dxhZdE9ytYLEm1FlqN9T3LMz0NGswMrw/view?usp=sharing

**Comment by imtuyethan** [comment]
Sorry for the confusion, here's my update:
-----
This screen will appear when:
User doesn't have any model + doesn't any thread
-----
This is the only case, when there's no model but users still have old threads, it should be a separate case, i'm working on it, will let you guys know when it's finalized.

**Comment by dan-homebrew** [comment]
@urmauur I am adding an additional edge case

**Comment by 0xSage** [comment]
@imtuyethan is this issue fixed yet? If not, can you update to reflect what remains to be done.

**Comment by imtuyethan** [comment]
Testing on v0.5.4-649, looking good on my end

**Comment by imtuyethan** [comment]
LGTM (0.5.4-650)
<img width="1120" alt="Screenshot 2024-10-01 at 18 17 51" src="https://github.com/user-attachments/assets/50498bac-1537-4f4c-bfa0-e09d871edc61">
