### ISSUE TITLE
bug: AppImage of version v0.5.2 does not show Claude Sonnet 3.5

### ISSUE THREAD

**Issue by ramonpzg** [janhq/jan#3171]
### #

- [X] I have searched the existing issues

### Current behavior

Hi there -- I am running the AppImage v0.5.2 and tried looking for Sonnet 3.5 to use it but could not find it anywhere. Please refer to the image below for reference.

![image](https://github.com/user-attachments/assets/d54f2a0a-1c9c-4e0a-aebf-570099427da8)

I also made sure I have the latest version. Please see below.

![image](https://github.com/user-attachments/assets/c01a3019-7cd1-4c3b-a699-9ecdd9b47ca3)

### Minimum reproduction step

1. Download the AppImage
2. Look for Sonnet 3.5

### Expected behavior

Usage of Claude Sonnet 3.5

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/d54f2a0a-1c9c-4e0a-aebf-570099427da8)

![image](https://github.com/user-attachments/assets/c01a3019-7cd1-4c3b-a699-9ecdd9b47ca3)

![image](https://github.com/user-attachments/assets/371b5b88-ae47-4c46-852d-45ae6c155844)

### Jan version

v0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Van-QA** [comment]
Hi @ramonpzg, sorry for the inconvenience but the issue will be resolved by deleting the extension folder within the Jan data folder, and restart Jan, can you try it out?
Feel free to reopen if the issue persist.
Thank you

**Comment by ramonpzg** [comment]
Thank you very much for the prompt response, @Van-QA :raised_hands: Problem resolved with your suggestion!
