### ISSUE TITLE
add links to the sources of models when i'm looking at them in Jan

### ISSUE THREAD

**Issue by davidawad** [janhq/jan#3176]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It would be nice to have links to the source pages / huggingface pages of the models. 

<img width="1376" alt="image" src="https://github.com/user-attachments/assets/66c9b5f4-c404-4649-b93b-ac29b4bac0b3">

### Describe the solution

It would be nice if there was a link icon where I could see the huggingface page to look at where the model is coming from, would increase transparency and help a bit. 

it would be nice also to be able to see the filepath of where jan is downloading the models to as well as the checksum that I should be able to confirm and make sure the models aren't getting tampered with on the way down to the machine.

### Teachability, documentation, adoption, migration strategy

n/a 

### What is the motivation / use case for changing the behavior?

I want some more transparency on which model exactly i'm looking at, especially as the names get more complicated I want to see which model, and get the link to the original HF page when / where it was published.

**Comment by Van-QA** [comment]
This one will be resolved along with this https://github.com/janhq/jan/issues/2968. Thank you.
