### ISSUE TITLE
feat: Don't hide the vertical scroll bar

### ISSUE THREAD

**Issue by StoffelNL** [janhq/jan#3177]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

For RSI-reasons (Repetitieve Strain Injury) I don't use a mouse but a Wacom-tablet with a pen/stylus. Since the vertical scroll-bar disppears I cannot grab onto it anymore to scroll back up once it's gone. This makes it very hard to scoll back up to see the conversation text that is off-screen. With a mouse scrolling back up is easy, using the mouse-wheel. I don't have the luxury of a scroll-wheel. The only way I have is to grab onto a vertical scroll bar. So it would be very helpfull if the vertical scroll bar is always visible and of big enough proportion to grab it with a pen.

### Describe the solution

Make the vertical scroll bar permanently visible or provide a setting so people can choose to turn this behaviour on or off. Or let the scroll bar re-appear if the pointer moves close to the (right) edge of any scrollable pane.
Making the scroll bar wide enough helps in making it easy to grab. The current 6 (?) pixels is slightly too small for comfort. 10px would be better without getting overly wide.

### What is the motivation / use case for changing the behavior?

Aid in accessibility of the application for people not using a mouse.

**Comment by Van-QA** [comment]
We tem‌‌pora‌lly resolved the issue by ‌making scrollbar vis‌ible by default. In the upcommin‌g sprint, we will introduce ‌‌a new settings related to scroll b‌ar under setting > ‌appre‌arance  https://github.com/janhq/jan/issues/3438
