### ISSUE TITLE
feat: Save sidebars toggled state

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [janhq/jan#3178]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Side panes do not save toggled/untoggled states for large screen setting.

https://github.com/user-attachments/assets/7fe82223-7a90-40b9-8cc9-df74224f6c48

### Describe the solution

Save the right/left panes toggled state for large screens (e.g., "right_pane_toggled_large_screen"). Default is True. Then, when exceeding the large screen width (e.g., >= 500px) restore these states.

Open to Discussion: Please let me know if you want to discuss it in Discord @ marcodifrancesco, or replying to this thread 🙋.

### What is the motivation / use case for changing the behavior?

I always keep side panes closed since 99% of the times use shortcuts to create new chats.
At the same time, I often decrease/increase window witdth and find myself closing manually side bars very often. I find this mildly annoying.

**Comment by Van-QA** [comment]
The issue was reso‌‌‌‌lved within Jan v0.5.3-622 ✅

**Comment by Van-QA** [comment]
hi @0xSage, actually ‌I changed the ticket to `complet‌ed` on p‌urpose, and only close the ticket once it's released to St‌‌able. This is the approach recomm‌end‌‌ed by ‌Dan 🙏
