### ISSUE TITLE
bug: [Manual inported model not visible]

### ISSUE THREAD

**Issue by milen-prg** [janhq/jan#3180]
### #

- [X] I have searched the existing issues

### Current behavior

The manual imported models (folder or gguf file) are not visible in downloaded models list so are not selectable and can't be used. The are in jan data folder, but not in user interface.
After importing, the Jan creates the new folder with the gguf file and model.json for example:
`
{
  "object": "model",
  "version": "1.0",
  "format": "gguf",
  "sources": [
    {
      "url": "pivot-0.1-evil-a.Q8_0.gguf",
      "filename": "pivot-0.1-evil-a.Q8_0.gguf"
    }
  ],
  "id": "pivot-0.1-evil-a.Q8_0-1",
  "name": "pivot-0.1-evil-a.Q8_0-1",
  "created": 1721583931832,
  "description": "",
  "settings": {
    "ctx_len": 2048,
    "embedding": false,
    "prompt_template": "{system_message}\n### Instruction: {prompt}\n### Response:",
    "llama_model_path": "pivot-0.1-evil-a.Q8_0.gguf"
  },
  "parameters": {
    "temperature": 0.7,
    "top_p": 0.95,
    "stream": true,
    "max_tokens": 2048,
    "stop": [
      "<endofstring>"
    ],
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "size": 7695875104,
    "author": "User",
    "tags": []
  },
  "engine": "nitro"
}`

### Minimum reproduction step

Import gguf model file. And try to use it.

### Expected behavior

The user installed models worked before several last Jan updates. But now they disappeared from the user interface and can't be select to use.

### Screenshots / Logs

no

### Jan version

0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

Windows 11 Pro 64 bit
RAM 64GB
VRAM 12GB

**Comment by milen-prg** [comment]
The manually installed model in Jan data folder with manually written model.json file (by the old versions instructions!) must be removed from the data folder and then imported from other place to work. Or in the data folder appears two different folders with the model and the two not work.

**Comment by milen-prg** [comment]
Not, after Jan restart, the manual model again are not visible.
The problem is not solved!

**Comment by milen-prg** [comment]
The models are visible in jan-win-x64-0.4.14 version, but after update to 0.5.2, they can't be used.

**Comment by Van-QA** [comment]
@milen-prg  can you try wiping the exte‌‌ns‌ion folder within Jan data folder, and restart Jan?

**Comment by milen-prg** [comment]
> @milen-prg can you try wiping the exte‌‌ns‌ion folder within Jan data folder, and restart Jan?

Yes, now it works. But the new generated (at first start it showed updating...) "extensions" is about 500MB, the old was only about 160MB.

**Comment by Van-QA** [comment]
please stay tuned for the new Jan x Cortex 🙏 the file size will change
