### ISSUE TITLE
bug: Downloading a model using huggingface url doesnt work on mac with the latest build.

### ISSUE THREAD

**Issue by rahulunair** [janhq/jan#3185]
### #

- [X] I have searched the existing issues

### Current behavior

When i give the huggingface URL, gets and error message as below:

![Screenshot 2024-07-22 at 12 17 22 PM](https://github.com/user-attachments/assets/a8ba4792-da1a-4a9f-929b-b3ade251a10b)

Tried with both the model repo namespace as well as the full url:huggingface.co/microsoft/Phi-3-mini-4k-instruct-gguf

### Minimum reproduction step

1. Go to Hub
2. Give the hugginface face url for a model
3. Will get an error message on the right sdide

### Expected behavior

Model is downloaded.

### Screenshots / Logs

![Screenshot 2024-07-22 at 12 17 22 PM](https://github.com/user-attachments/assets/557db9f8-5fd0-4671-9502-fe051f9a0a93)

### Jan version

v0.5.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

### Environment details

Mac M1 16 GB

**Comment by Van-QA** [comment]
hi @rahulunair, can you try wiping the extensions fo‌lder (Und‌‌er Jan data folde‌r) and restart?

**Comment by davotoula** [comment]
Had the same issue.

Deleting extensions folder in /Users/<user>/Jan resolved it

thanks

**Comment by Van-QA** [comment]
`
