### ISSUE TITLE
bug: groq not showing all available model

### ISSUE THREAD

**Issue by basstimam** [janhq/jan#3194]
### #

- [ ] I have searched the existing issues

### Current behavior

There is just 4 model available in JanAI

### Minimum reproduction step

Search on hub or model in chatting

### Expected behavior

Groq Cloud 

### Screenshots / Logs

Current: 
![image](https://github.com/user-attachments/assets/8eaa4d31-1b8b-4d66-ae4b-b2822e33b3e4)

Available model based on GroqCloud
![image](https://github.com/user-attachments/assets/5f23af83-57e6-4533-a180-c6de447f79f8)

### Jan version

0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
this issue will be resolved via https://github.com/janhq/jan/issues/3374, please follow up using that ticket, thank you 🙏
