### ISSUE TITLE
bug: docker instance theme is incomplete / transparent

### ISSUE THREAD

**Issue by koheiio** [janhq/jan#3196]
### #

- [x] I have searched the existing issues

### Current behavior

Theming issues in docker:
- Dropdowns have transparent bg (select model in chat)
- Certain modals/sideout sections have transparent bg (press system monitor in settings page footer)
- app has desktop window controls on the header
- Theme selection does not do anything.

### Minimum reproduction step

1. Deploy the app in docker, and visit the web url.
2. press system monitor in settings page footer
3. see popup has transparent bg in popout and overlaid of top of other ui
4. select model in chat sidebar
5. see that text has transparent bg and overlaid on top of other text

### Expected behavior

- Expect web to not contain transparent bg in modals/popups
- Expect web to not have desktop window controls in header
- Expect web to have theme selection

### Screenshots / Logs

![gpt htko ca_(HD)](https://github.com/user-attachments/assets/79aaef24-f73f-4e4f-9a59-b8231b121239)

### Jan version

0.1.0 (docker compose)

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment details

Docker host:
Ubuntu - i7 13900k - 3080 TI FE - 32GB

Web client:
Macbook Pro 14" - M2 Pro - 32GB

**Comment by Van-QA** [comment]
Thank you, the issue was resolved in our new Jan version, stay tuned
![image](https://github.com/user-attachments/assets/9bb8b11a-fa87-451f-9d5a-f886e1223685)

**Comment by gituser** [comment]
> Thank you, the issue was resolved in our new Jan version, stay tuned ![image](https://private-user-images.githubusercontent.com/64197333/352853648-9bb8b11a-fa87-451f-9d5a-f886e1223685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNTQ2MjcsIm5iZiI6MTcyMjI1NDMyNywicGF0aCI6Ii82NDE5NzMzMy8zNTI4NTM2NDgtOWJiOGIxMWEtZmE4Ny00NTFmLTlkNWEtZjg4NmUxMjIzNjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDExNTg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYWY1NTVkOGQ2Yzg4OGYyZWY2MmY4YWYxYWY5OTg5NTZiNGMyZDk5NWY1NTUwZDJmYjBjNmU0YzA0OWEyYzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xHjXlqrv0AeIr_L8jnWSWeXphpIVzpXqE-sN9RHINRM)

@Van-QA Is there a hotfix to apply to the latest `v0.5.2` release ?

**Comment by koheiio** [comment]
> Thank you, the issue was resolved in our new Jan version, stay tuned !
I noticed the on-prem page was removed from the jan website. I assume it's just in (re)development?

**Comment by Van-QA** [comment]
Sorry for the inconvenience, we are deprecating the on-prem for the time being in favor of  Cortex. 

- https://cortex.so/docs/installation/docker (under development)

- https://github.com/janhq/jan/pull/3219

**Comment by gituser** [comment]
@Van-QA very weird, do you plan on providing a WEB build of jan (to use with nginx) instead of the standalone electron app?

**Comment by socialnicheguru** [comment]
> * https://cortex.so/docs/installation/docker

How was this solved? is there a fix?

**Comment by socialnicheguru** [comment]
> Thank you, the issue was resolved in our new Jan version, stay tuned ![image](https://private-user-images.githubusercontent.com/64197333/352853648-9bb8b11a-fa87-451f-9d5a-f886e1223685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5Mzk4NTMsIm5iZiI6MTcyMjkzOTU1MywicGF0aCI6Ii82NDE5NzMzMy8zNTI4NTM2NDgtOWJiOGIxMWEtZmE4Ny00NTFmLTlkNWEtZjg4NmUxMjIzNjg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEwMTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiZjZiMjNmYTIwNDZjYmMwY2FlYmVmYzA4ZWIyYmM2NWQxYjdlYTYwMjQ3ZTQyYjE4MmY0NDgzOGNkZjAxODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QGfSKrGkt6amwJsEZHb4JlC8GWmV43bMKl1vpZqAB-U)

how was this solved? Is there a fix?
