### ISSUE TITLE
feat: Add "Delete Current Chat" shortcut

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [janhq/jan#3204]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

There is no shortcut to delete the current chat I'm working on. 

<kbd>
  <img src="https://github.com/user-attachments/assets/bb2b0d38-24b8-4e66-a889-36058a4829b4" width=500>
</kbd>

### Describe the solution

One option could be following the ChatGPT convertion: Ctrl+Shift+Backspace.

ChatGPT shortcuts:

<kbd>
  <img src="https://github.com/user-attachments/assets/ce3b639d-2232-411c-ad0c-ba2019e186e0" width=500>
</kbd>

**Open to Discussion**: Please let me know if you want to discuss it in Discord @ marcodifrancesco, or replying to this thread 🙋.

### What is the motivation / use case for changing the behavior?

My workflow consists of ~90% deletable chats. Very often I ask short questions that I want to delete immediately and want to keep the history clean with only 1/2 important chats per week that I will need later.

**Comment by urmauur** [comment]
duplicate ticket work on this #3162 instead, thanks @MarcoDiFrancesco and @Van-QA
