### ISSUE TITLE
bug: New chat button not working

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [janhq/jan#3205]
### #

- [ ] I have searched the existing issues

### Current behavior

When the "New Thread" chat exists, the new chat button and ctrl+n do nothing.

![image](https://github.com/user-attachments/assets/0a20252e-5183-4672-8d0f-2c8d03ae59b6)

### Expected behavior

There are 2 options:
- Ctrl+N redirects to the "New Thread" chat
- Ctrl+N creates an empty chat

Solution I suggest is a third option, which follows ChatGPT behaviour: New chat does not create a "New Thread" right away, but waits until we type the prompt and click "Submit".

I'm aware implementing it is a a technical challenge, but would solve the issue beforementioned + Would get rid of the *in my opinion* not good looking "New Thread".

**Open to Discussion**: Please let me know if you want to discuss it in Discord @ marcodifrancesco, or replying to this thread 🙋.

### Jan version

0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by Van-QA** [comment]
hi @MarcoDiFrancesco, sorry for the inconvenience, the current Jan UI is preventing creation of multiple empty threads, we already resolved the issue in the new Jan version that we are working on, stay tuned 🙏
