### ISSUE TITLE
feat: [DESCRIPTION]

### ISSUE THREAD

**Issue by OneHoopyFrood** [janhq/jan#3208]
### #

- [x] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm unsure if this is a bug or if it was an intentional removeal. If this was intentional, this can be re-cast as a feature request.

I'm new to Jan, and I wanted to start managing a few different "Assistant" prompts for different scenarios. I found this page: https://jan.ai/docs/assistants via google, but it seems this is out of date since the UI overhaul. There no longer seems to be any means to manage assistants.

### Describe the solution

I'd like some form of UI or options menu to return so that managing assistants is possible again, like what the documentation says you used to be able to do.

### What is the motivation / use case for changing the behavior?

It seems like a gap. Jan is clearly designed for multiple saved assistants, but has no means to save, load, delete, or otherwise work with them. Instead, each new thread requires copy-pasting the instructions.

**Comment by Van-QA** [comment]
hi @irfanpena, can you help us double check this case? thanks

**Comment by irfanpena** [comment]
@Van-QA Yes, I removed this page: https://jan.ai/docs/assistants because we don't have that in the new UI. This page is already hidden in our docs. The cons of Nextra are that users can still access the hidden page if they have the link to that hidden page. I will redirect this so that users cannot see it.
