### ISSUE TITLE
Jan.ai onpremise server install sidebar gives error: tags and toLowerCase

### ISSUE THREAD

**Issue by socialnicheguru** [janhq/jan#3210]
### #

- [X] I have searched the existing issues

### Current behavior

If I goto the sidebar and click on anything I get errors. 
- click on settings icon - toLowerCase error
- click on local api server - tags error
- click on Hub - toLowerCase error

If I click on appearance icon at the top right the settings icon seems to work. ie you are staying in settings. 
I get the following for everything else:
- click on local api server - tags error
- click on Hub - toLowerCase error
- threads is accessible

### Minimum reproduction step

Install onpremise
Click on any of the items on the left hand sidebar.

If I goto the sidebar and click on anything I get errors. 
- click on settings icon - toLowerCase error
- click on local api server - tags error
- click on Hub - toLowerCase error

If I click on appearance icon at the top right the settings icon seems to work. ie you are staying in settings. 
I get the following for everything else:
- click on local api server - tags error
- click on Hub - toLowerCase error
- threads is accessible
-
<img width="1598" alt="Error-tags" src="https://github.com/user-attachments/assets/9271140e-1bfe-417d-90c6-38415ee24bc8">

<img width="1598" alt="Error-toLowercase" src="https://github.com/user-attachments/assets/f5c0220c-fba7-47f4-81f1-75ece5ce549b">

### Expected behavior

It should goto the menu link destination

### Screenshots / Logs

Error: Cannot read properties of undefined (reading 'tags')
TypeError: Cannot read properties of undefined (reading 'tags')
    at https://mysite/_next/static/chunks/app/page-5333bcaf6dcc0289.js:5199:67
    at Array.filter (<anonymous>)
    at ModelDropdown (https://mysite/_next/static/chunks/app/page-5333bcaf6dcc0289.js:5199:44)
    at Tf (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:114:421)
    at al (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:282:338)
    at Xk (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:270:328)
    at Wk (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:268:30)
    at ke (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:267:315)
    at le (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:261:94)
    at ie (https://mysite/_next/static/chunks/618f8807-b676f4c30b3f7780.js:83:261)

### Jan version

docker pull ghcr.io/janhq/jan-server:dev-cpu-0.5.2-112

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Environment details

Linux Ubuntu 24.04LTS

**Comment by Van-QA** [comment]
Hey there! Thanks for trying out Jan. 

We've actually decided to deprecate Jan On-premise. Sorry for any confusion this might have caused.

We're focusing our efforts on improving the main Jan application to better serve our users. If you're looking for alternative solutions, you might want to check out Cortex (https://github.com/janhq/cortex) for headless AI operations.
Appreciate you taking the time to report this. Let us know if you have any other questions! 😁

**Comment by socialnicheguru** [comment]
https://github.com/janhq/jan/issues/3196
