### ISSUE TITLE
bug: Remove dangling Vercel call

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3211]
### #

- [x] I have searched the existing issues

### Current behavior

Jan app is making external calls to Vercel for some reason. Likely due to a previous feature that we have since deprecated. Let's remove it asap

### Minimum reproduction step

1. open app, interact
2. watch networking io

### Expected behavior

no vercel calls

### Screenshots / Logs

https://x.com/levelsio/status/1817388406789243118

### Jan version

assume latest?

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by namchuai** [comment]
I'm investigating this issue.
Below's the requests popup from app `Little snitch` when open jan. I'm not 
<img width="670" alt="Screenshot 2024-07-29 at 16 21 44" src="https://github.com/user-attachments/assets/7b8c5061-1c83-4ee3-ba2b-ac95d2fd24d4">

<img width="670" alt="Screenshot 2024-07-29 at 16 22 23" src="https://github.com/user-attachments/assets/214a56f3-9f56-4bba-a496-8d6f90a3be3b">

downloading model from jan hub
<img width="670" alt="Screenshot 2024-07-29 at 16 22 54" src="https://github.com/user-attachments/assets/4621f037-623d-4aee-8dc8-48af9e7f1fa3">
<img width="670" alt="Screenshot 2024-07-29 at 16 24 34" src="https://github.com/user-attachments/assets/077b36b5-ac20-4645-9431-682003ce49d6">

**Comment by namchuai** [comment]
My only 4 rules when download and running a model using Jan v0.5.2

<img width="978" alt="Screenshot 2024-07-29 at 16 39 46" src="https://github.com/user-attachments/assets/de942c16-5182-476a-b7d4-c8029048daa6">

**Comment by namchuai** [comment]
We removed Umami from PR #3221

**Comment by namchuai** [comment]
This should be fixed since we removed Umami. Still need to re-validate after Jan x Cortex release though.

**Comment by namchuai** [comment]
@Van-QA please help to verify. The app user is using is called Little Snitch.
