### ISSUE TITLE
feat: RAG and localDocs

### ISSUE THREAD

**Issue by iamiranjbar** [janhq/jan#3216]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Hi Jan.ai Team,

I noticed that the RAG (Retrieval-Augmented Generation) and LocalDocs features, which were previously available, are now missing from the Mac app and local deployment of the codebase on GitHub.

### Describe the solution

Why were the RAG and LocalDocs features removed or are they currently unavailable?
Are there any plans to reintroduce these features in the near future?
Can you provide guidance or documentation on how to add these features back into the codebase?
I appreciate any help you can provide to address this issue. Thank you for your hard work on this project!

### What is the motivation / use case for changing the behavior?

The RAG and LocalDocs features are essential for my work as they significantly enhance my ability to retrieve and utilize local documents effectively. These tools streamline my workflow, improve productivity, and provide a seamless user experience. Their absence requires additional manual steps and third-party tools, which are less efficient and more time-consuming. Reintroducing these features would restore the usability and efficiency that were previously available.

**Comment by Van-QA** [comment]
Hi there, sorry for the inconvenience, 
With a rollback in the Jan nightly, the feature is available again, please check it out, (Jan v0.5.2-591 or higher)
Note that RAG is an experimental feature and only supports local models or OpenAI models for now. 🙏
