### ISSUE TITLE
bug: Unable to start any models

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3230]
### #

- [x] I have searched the existing issues

### Current behavior

When I want to run any model on Jan (locally) the thread starts but the AI model doesn't start, it loads and after a few seconds the loading disappears, sometimes leaving an error message and sometimes no indication at all
 (for example, here I'm using Phi-3 Mini, model ID: phi3-3.8b) 

### Minimum reproduction step

1/  Download the app
2/ Download all driver for the garphic card (CUDA toolkits, ....)
3/ Start the model Phi-3 Mini

### Expected behavior

Model start and i can use it, but actually it don't start.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/6ebd7485-fb39-4dff-b048-e1b0604c8ed4)
![3](https://github.com/user-attachments/assets/2d5612cb-f048-4b06-9e5c-54f66e7abbce)

### Jan version

0.5.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

Its a VM on proxmox with a GPU passthrougt.
Windows 10 Pro

16 Gb of RAM (DDR3)
GPU : Nvidia Quadro M4000
8 Gb of VRAM
Processor : Xeon 5506 2.13 Ghz
2 socket with 3 thread per socket
total 6 thread

**Comment by Van-QA** [comment]
depre‌‌c‌rate‌d - users will need to retry with Jan x C‌ortex
