### ISSUE TITLE
bug: Improve Window Boundary Visibility

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [janhq/jan#3237]
### #

- [ ] I have searched the existing issues

### Current behavior

White solid theme on white background makes it difficult to distinguish where Jan window is limited to.

![image](https://github.com/user-attachments/assets/7e8224aa-ada4-4142-a31a-6071ae59de45)

### Expected behavior

Solution could be using the default shade that most Desktop environments provide (e.g. KDE, Windows 11), which add a shade to the external part of the window.

Below is an example with VSCode.

![image](https://github.com/user-attachments/assets/2c72dfb3-9731-4398-a3ed-6b837e0360d5)

### Jan version

0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
![image](https://github.com/user-attachments/assets/655d6ef5-1fd1-41c7-ae2c-854f31437c75)
Tested and looking go‌od on Jan v0.5.-616

**Comment by MarcoDiFrancesco** [comment]
![image](https://github.com/user-attachments/assets/2ded1f8e-4910-4a71-bcb0-5d7382fa9dd8)

No shadow for KDE Plasma 5 on Jan v0.5.2-618

**Comment by Van-QA** [comment]
hi @MarcoDiFrancesco the issue should be resolved after Jan v0.5.2-619, thank you for your patient

**Comment by 0xSage** [comment]
Closing as fixed. @MarcoDiFrancesco feel free to reopen if you are still experiencing issues post v0.5.3-629!
