### ISSUE TITLE
feat: Multiple window support

### ISSUE THREAD

**Issue by MarcoDiFrancesco** [janhq/jan#3238]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I can't spawn 2 instances of Jan at the same time.

### Describe the solution

Implement Multiple Window Support.
I'm aware it brings up a countless number of issues with syncing between instances, but I would love to even have a setting to enable multi window support under "Experimental mode".

### What is the motivation / use case for changing the behavior?

With ChatGPT I'm often having multiple chats at the same time: opening a new browser tab, asking something super simple, then getting the answer and closing it. With Jan single window support this is not possible if you are already working on some other thread.

**Comment by 0xSage** [comment]
Team will likely enable separate app instances for Jan vs Jan-Nightly
See https://github.com/orgs/janhq/projects/5/views/47?pane=issue&itemId=78691317

**Comment by imtuyethan** [comment]
Quick ask seems like your use case, Jan would be able to have a small window for quick reply & temporarily chat after we complete https://github.com/janhq/jan/issues/3944 Decouple Quick Ask & Its Settings

For the time being, you can install separate versions of Jan (Beta & Stable) once 0.5.8 is released.
