### ISSUE TITLE
feat: UI, Settings: move Jan Quick Ask settings to Keyboard Shortcuts

### ISSUE THREAD

**Issue by nikiluk** [janhq/jan#3239]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

It's not intuitive where the setting is hidden

![image](https://github.com/user-attachments/assets/fde1129e-aa7a-4a40-aaae-39e289e44472)

### Describe the solution

As Jan Quick Ask setting is related to the key CTRL+J combination it makes much more sense to move the setting to Keyboard Shortcuts

### What is the motivation / use case for changing the behavior?

Improvement of the UI and making it more intuitive

**Comment by 0xSage** [comment]
@nikiluk Quick Ask was not well built, so we have hidden it under Experimental. 
Once it is rebuilt & stable, definitely agree that it should be featured in app shortcuts. 

Closing this as a wontfix for now as we're likely to rebuild quick ask differently in the future :)
