### ISSUE TITLE
bug: Nvidia NIM setting is not available

### ISSUE THREAD

**Issue by nikiluk** [janhq/jan#3240]
### #

- [X] I have searched the existing issues

### Current behavior

Nvidia NIM setting is not available on the laptop with no Nvidia driver while available on the other with the Nvidia driver.

### Minimum reproduction step

1. Go to Settings
2. See that the setting for Nvidia NIM is not available on the laptop that does not have Nvidia GPU card

### Expected behavior

Nvidia NIM is used for remote Nvidia API called from the Jan interface. The API calls does not require Nvidia GPU on the client and are not performance-hungry.

Therefore, it's expected to have this setting on any machine regardless of the presence of the Nvidia GPU, in the same way as calls to OpenAI API or Anthropic API.

### Screenshots / Logs

Laptop 1 No discrete GPU
![2024-08-03 2560x1392 bLbqU](https://github.com/user-attachments/assets/29d9c251-cccf-4ab5-be39-38c7b77facab)

Laptop 2 Discrete GPU
![discrete GPU image](https://github.com/user-attachments/assets/6e79f7f8-3634-444c-9877-e5eb356af35c)

### Jan version

0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Thanks @marknguyen1302 for adding the engine support from Cortex

**Comment by nikiluk** [comment]
@Van-QA does not seem to be affecting the UI

Nvidia settings still not present, Jan 0.5.2.

![2024-08-07 263x670 8tgpJ](https://github.com/user-attachments/assets/987f9826-6e63-437c-97c5-6c7ed8f49a85)

**Comment by Van-QA** [comment]
@nikiluk can you try our nightly build?

**Comment by nikiluk** [comment]
@Van-QA after reinstalling it to the nightly build I've realized that the new Model settings are not accepting for example the custom URL of the inference API that was previously possible. For example, I've used Microsoft Azure Open API endpoint but now it's not possible to set it in the new UI. Shall I raise the new ticket? Not doing it given I'm now operating in the nightly build.

![Screenshot 2024-08-08 122952](https://github.com/user-attachments/assets/2d458f77-fc49-46be-a844-aacb484cc6c6)

**Comment by nikiluk** [comment]
@Van-QA yes, via Jan settings UI page

![image](https://github.com/user-attachments/assets/b80c7367-c40e-43ac-bb02-3b2793a1d3e6)

**Comment by Van-QA** [comment]
hi @nikiluk, to workaround for the time being, please temporally modify the url in yaml.
![image](https://github.com/user-attachments/assets/f2170316-3091-464f-a656-11ed9940a0f2)


We will resolve the issue via https://github.com/janhq/jan/issues/3341

**Comment by nikiluk** [comment]
@Van-QA thank you, will try that
