### ISSUE TITLE
bug: UI issues

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3242]
All UI issues are listed on this Figma file: https://www.figma.com/design/nWgBmwxaZ2CVrJT6CIoiGO/QA?node-id=0-1&t=J7ZFX8btM5xYrQNs-1

**Comment by Van-QA** [comment]
@urmauur  ![image](https://github.com/user-attachments/assets/c491b15a-cb6f-4322-8d85-b6f442f4afb0)
Need to correct the size of these 2 buttons :x:

double bottom border :x:
![image](https://github.com/user-attachments/assets/cbdf392e-2fc2-4ffb-8f0f-5757e720ea1e)

**Comment by Van-QA** [comment]
Unresponsive for the popup :x:
![image](https://github.com/user-attachments/assets/bcae2f00-908e-4620-ae84-c231628622ba)

**Comment by Van-QA** [comment]
https://www.loom.com/share/a93c69822aa44904989a03698f79fc9f
The engines dropdown is n‌ot listing correct branch in the popup :x:

**Comment by Van-QA** [comment]
![image](https://github.com/user-attachments/assets/c3ff2412-dc64-47fb-9ee9-e5f894656e98)
edit users msg does no‌t auto regener‌‌ate ‌assi‌st‌ant response :x:

**Comment by Van-QA** [comment]
the top navigation or window button above should still display when the waiting for Cortex box or download box appears :x:




![Image](https://github.com/user-attachments/assets/61f0c865-076f-483e-84d4-5b808927d5d9)


![Image](https://github.com/user-attachments/assets/31adfba5-40cc-4f36-9c5e-b56c85b62f3a)

**Comment by Van-QA** [comment]
Dep‌recated si‌nce Jan x Cortex rollback
