### ISSUE TITLE
bug: Pulling duplicated local model => successfully but not actually adding that model

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3249]
Need support from Cortex => prevent adding duplicated model

**Comment by louis-jan** [comment]
@Van-QA any update needed from Jan?

**Comment by louis-jan** [comment]
I guess it should display the error toast by default after receiving an error.

**Comment by louis-jan** [comment]
2 scenarios

![Image](https://github.com/user-attachments/assets/eb00fc39-e79c-4469-8ebe-e6ffcc68e618)
![Image](https://github.com/user-attachments/assets/2ca5bdbc-9e61-416a-bf5c-ef1dbcd2c036)

**Comment by louis-jan** [comment]
Updated

Error toast message is added

**Comment by Van-QA** [comment]
For some cases importing duplicated models does not show the failed icon

![Image](https://github.com/user-attachments/assets/936315c4-bcd2-4eb0-a3f0-ce8931122837)


![Image](https://github.com/user-attachments/assets/8b0113ee-82c8-43b8-bb74-0c90a4a95f6d)

**Comment by Van-QA** [comment]
Resolved Jan v0.5.2-581

![Image](https://github.com/user-attachments/assets/1bd6a695-93ac-4b01-8bdc-675c8c9b3d4d)
