### ISSUE TITLE
feat: Jan can update Models

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3251]
For now, users will have to remove models and pull again (both remote / local)

We need a UI to update the model within Jan @imtuyethan

**Comment by imtuyethan** [comment]
Just add `Update Model` in `My Models` 
![Screenshot 2024-08-08 at 10 11 28 AM](https://github.com/user-attachments/assets/d5637af3-c2fc-4b49-adc7-fd787cd094a1)

https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=5303-15482&t=xf2rYuvzD97tK6zq-4

**Comment by Van-QA** [comment]
That dropdown is only available for local models, can you help us include the UI for remote models as well? @imtuyethan thank you

**Comment by imtuyethan** [comment]
![Image](https://github.com/user-attachments/assets/c8216cfd-2eea-44a5-a0ad-7095aa893d3e)



> That dropdown is only available for local models, can you help us include the UI for remote models as well? [@imtuyethan](https://github.com/imtuyethan) thank you

Yes should be the same thing as well, please use the same Figma link above.

**Comment by dan-homebrew** [comment]
Deprecating as I don't think model update is the way the industry is going (release under new version name)
