### ISSUE TITLE
feat: Jan supports cache_prompt (HTTP request JSON for llama.cpp)

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3253]
### #

- [ ] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Jan does not support setting cache_prompt in the HTTP request JSON for llama.cpp - resulting in slower processing times for long contexts (8000+ tokens).

### Describe the solution

Ja should support setting the cache_prompt parameter in the HTTP request JSON to enable faster processing times with llama.cpp.

### What is the motivation / use case for changing the behavior?

Currently, the default setting for cache_prompt is off in llama.cpp - leading to significant delays. Manually enabling cache_prompt improves performance.

**Comment by louis-jan** [comment]
DUP: #3320

**Comment by imtuyethan** [comment]
Close as duplicated with #3320
