### ISSUE TITLE
bug: Model versions should have proper names instead of just gguf, 8b-gguf,...

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3260]
Can we figure out a way to have  proper model version names? What is the current problem for this?
Ex: `llama3-8b-instruct-q5_K_M` instead of just `gguf`

![Image](https://github.com/user-attachments/assets/8de19844-c36e-4eab-984e-f7245027183f)

**Comment by Van-QA** [comment]
Shorten for tensortRT LLM is also needed.


![Image](https://github.com/user-attachments/assets/f1d5895e-26c0-4b58-9f57-52251509b7ed)

**Comment by Van-QA** [comment]
Adding sample metadata.yaml for the configuration  https://huggingface.co/cortexso/mistral/blob/main/metadata.yaml

**Comment by imtuyethan** [comment]
deprecated
