### ISSUE TITLE
bug: Missing models in UI (0.5.2-573 Jan x Cortex) 

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/jan#3262]
### #

- [ ] I have searched the existing issues

### Current behavior

0.5.2 Jan shows 4 available models for GPT
<img width="1347" alt="image" src="https://github.com/user-attachments/assets/72959fea-d805-4632-8415-db0260c24be7">

0.5.2-573 only shows 2 models
<img width="706" alt="image" src="https://github.com/user-attachments/assets/73a70625-e2de-4cc6-9177-e3ff187aa83b">

### Minimum reproduction step

1. Go to Models page, search for "GPT"
2. Only 2 GPT models appear

### Expected behavior

I expect it to show the 4 GPT models as available in model.yaml and cortex models list

### Screenshots / Logs

Uploading Screen Recording 2024-08-05 at 4.15.16 PM.mov…
- Nightly v573 only shows 2 GPT models
- Despite model.yaml files and cortex models list showing all 4 GPT models
- New Jan shows 4 GPT models

### Jan version

0.5.2-573

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by gabrielle-ong** [comment]
FYI - Screen recording of reproduction is uploading. I'm not able to screenshot the error on nightly 573 now because of other bugs

**Comment by micisse** [comment]
Same problem, but my models folder contains quite a lot of stuff, some models installed by default or automatically in v0.5.2. I don't know if it's definitive for the next version, but you can no longer define a **custom path**. In v0.5.2, I use a custom path for the jan folder, not the default path.

v0.5.2 - custom path

https://github.com/user-attachments/assets/15636a85-37cb-47b3-b13d-adc550d2b189

**v0.5.2-573 shows zero models**

![Capture d’écran_2024-08-05_19-48-10](https://github.com/user-attachments/assets/ff5a4229-f7e2-4629-b215-1382f226f954)

**Comment by Van-QA** [comment]
Resolved as of Jan v0.5.2-578
