### ISSUE TITLE
bug: Mac: not initializing cortex server (0.5.2-573)

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/jan#3263]
### #

- [x] I have searched the existing issues

### Current behavior

1. Jan x Cortex stuck on loading screen, Err connection refused. Due to cortex not running

[fix]
3. Manually Run cortex on command line
4. Jan is initialized and working as expected

### Minimum reproduction step

see video

### Expected behavior

Expect Cortex server to be started automatically by Jan

### Screenshots / Logs

Uploading Screen Recording 2024-08-05 at 5.34.28 PM.mov…
[cortex.log](https://github.com/user-attachments/files/16493893/cortex.log)

### Jan version

0.5.2-573

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by micisse** [comment]
Maybe related on Linux (.AppImage) https://github.com/janhq/jan/issues/3016#issuecomment-2268939957

**Comment by gabrielle-ong** [comment]
Realise the video upload failed -
https://github.com/user-attachments/assets/f45bfd04-67e8-4f85-b5aa-3bca7815d9dc

- The issue is that cortex was didnt start automatically.
- Might be different issue from @micisse - yours seems to be "theres another instance of the app running" which I've had on windows, more to do with killing the existing processes on 1337. I will create another issue to link here
- Side note on `http://localhost:1337/v1 is not accessible`: @Van-QA to our previous convo about changing that user message because they should go to that site via browser. It's the correct end point for Jan but shouldnt be access by browser

**Comment by micisse** [comment]
@Van-QA In fact, I had launched the app from my desktop (click on .AppImage), and when it didn't work, I went to the issues to see if there was a ticket related to this problem, and I came across this ticket. I then tried to launch the cortex from the terminal while the app was open on "**Waiting for cortex...**" and it displayed "_another instance of Jan is running_". But even when I reboot my PC (no more instances open) and launch the app as usual (**nightly** version), I still get "**Waiting for cortex**" and neither **http://localhost:1337/api** nor **http://localhost:1337/api** is accessible. The app remains open on "**Waiting for cortex**". @gabrielle-ong I had mentioned that I had killed the process and/or port 1337 in my previous comment (_lsof ..._). The problem may be linked to the same source, but I don't think it's any different.

**Comment by louis-jan** [comment]
Jan should access 127.0.0.1 instead of localhost

<img width="545" alt="Screenshot 2024-08-05 at 20 51 13" src="https://github.com/user-attachments/assets/d2cdec43-94fd-469f-8389-fef2f07bf9ce">

**Comment by gabrielle-ong** [comment]
Solved, Thanks @louis-jan!  
Similar to #3264 : 
~/[User]/.cortexrc should have apiServerHost as 127.0.0.1, not localhost

@micisse Could you check if that might be the same case for you? If not, please create a new issue and we can investigate further. May also be related to #3265: Dangling cortex & node processes which had the same solution. 

Side note - this nightly version (0.5.2-573, meant to be released as 0.6.0 next week)  is a different architecture to the current stable version 0.5.2. TLDR: we're separating Jan to use the backend API platform Cortex (https://github.com/janhq/cortex). hence there are definitely more bugs stable version - we're working on it! Thanks for testing out nightly and keep the feedback coming

**Comment by micisse** [comment]
@gabrielle-ong Everything looks smooth and simple from your side 🙃. On my side, **I didn't need to change anything, it was already good, the file already contained 127.0.0.1, not localhost**. I'll stick with the stable version and see if the next version fixes the problem, but the **nighly** version doesn't seem to work for me. I've always used the stable version, but this is a first for me with the **nightly** version.

![Capture d’écran_2024-08-05_18-51-28](https://github.com/user-attachments/assets/01bd1358-8858-4fc1-ac35-cc2dfd7fbae2)
![Capture d’écran_2024-08-05_18-48-39](https://github.com/user-attachments/assets/0cd807b0-8efc-4ff3-9afa-c9f88b9626cc)

**Comment by micisse** [comment]
In fact the settings are ok, no need to change anything. If you're here and the problem persists, after a new installation (going from **stable** to **nightly** or vice versa, _i use **.AppImage** on **Linux**_), delete the **.cortexrc** file and the **cortex folder** if they exist, close all instances or Jan processes if any and **reboot your machine**. This is how I was able to open my jan instance (nightly)
