### ISSUE TITLE
bug: is port 1337 in use? No (0.5.2-573)

### ISSUE THREAD

**Issue by gabrielle-ong** [janhq/jan#3264]
### #

- [ ] I have searched the existing issues

### Current behavior

Testing 0.5.2-573 for 0.6.0 release (Jan x Cortex) on Windows 11

Cortex is unable to start on port 1337 - despite no processes running on 1337.
AppData/Roaming/Jan/logs/main.log 

"Killing processes on port 1337"
"No processes on port 1337"
"Is port 1337 in use?"

![Screenshot 2024-08-05 213655](https://github.com/user-attachments/assets/2161951f-c99d-4305-b8c1-f631cfd966d1)

### Minimum reproduction step

see video comments

### Expected behavior

Expect Cortex to start and run on port 1337
Expect Jan to move past loading screen after Cortex process starts

### Screenshots / Logs

[cortex.log](https://github.com/user-attachments/files/16498533/cortex.log)
[main.log](https://github.com/user-attachments/files/16498530/main.log)

### Jan version

0.5.2-573 nightly

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [ ] Linux

### Environment details

Windows 11
AMD Ryzen 9 with NVIDIA RTX 4070
RAM: 32GB

**Comment by louis-jan** [comment]
@gabrielle-ong could you please help open `C: \Users \gabri\AppData\Local\Programs \jan \resources\bin\cortex.exe` manually?

**Comment by gabrielle-ong** [comment]
Doesnt respond with cortex server running,
And when I start Jan, the cortex child process exits
![image](https://github.com/user-attachments/assets/f6142d09-e6f0-43ac-b6ea-1190edcadaf1)

**Comment by louis-jan** [comment]
@gabrielle-ong please wait for the result, don't open Jan yet. It will try to kill any running processes.

**Comment by louis-jan** [comment]
Also @gabrielle-ong could you please upload the `.cortexrc` file here as well

**Comment by gabrielle-ong** [comment]
.cortexrc

**Comment by louis-jan** [comment]
Ah, the apiServerHost should be 127.0.0.1 instead of localhost, I think Mark fixed it recently. Could you please swap them out manually for now?

**Comment by gabrielle-ong** [comment]
> @gabrielle-ong please wait for the result, don't open Jan yet. It will try to kill any running processes.
It exited on its own after about 30s

**Comment by gabrielle-ong** [comment]
Solved, thanks @louis-jan! fixing .cortexrc worked
