### ISSUE TITLE
feat: Lazy loading for threads history

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3269]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

1. Restart Jan (nightly) Jan v0.5.2-574
2. Land in Chat
3. Threads take a long time to load (10 seconds+++)
4. Or something else is taking a long time to load?

### Describe the solution

My thread history is quite long at this point. Maybe we can lazy load
But the start up delay could also be due to something else...

### What is the motivation / use case for changing the behavior?

Better restart experience.

**Comment by louis-jan** [comment]
Addressed. But reverted
