### ISSUE TITLE
feat: Left Pane should be collapsible to the side

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#327]
**Brief Overview**
- I primarily use Jan as a always-on app, that helps me with writing, thinking etc
- I use Magnet to snap it to the Right side of my screen
- I want to toggle the Left Pane (similar to Obsidian, VSCode)
- Only have a Chat UI

<img width="769" alt="image" src="https://github.com/janhq/jan/assets/101145494/e1682f90-719c-4430-b28c-91eb1b3ac72b">

**Comment by 0xSage** [comment]
done
