### ISSUE TITLE
feat: Models should download to a user-defined Directory

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#328]
**Problem**
- We currently download models to an app directory (e.g. `Application Support` for Mac)
- Problems
   - User cannot add/delete or copy/paste their own models in
   - Very dependent on our UI, which will take 1-2 months to stabilize
- We should consider downloading models to a user-defined directory in `~` or `/documents`
   - User can import their own models
   - We would have to develop a simple feature to scan the folder, and populate the DB
   - Alternatively show the model w/o metadata, and say that it was picked up from the folder

**Comment by 0xSage** [comment]
Dupe of #359

**Comment by 0xSage** [comment]
wont do. see ADR 5
