### ISSUE TITLE
feat: Jan x Cortex support move Jan data folder 

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3282]
This feature is required to bypass the issue where users have special characters in the file path.
Screenshot from the old Jan version
![image](https://github.com/user-attachments/assets/747ec52b-35e2-4201-94b7-208d504ea93a)

**Comment by micisse** [comment]
> ![Capture d’écran_2024-08-07_19-32-37](https://github.com/user-attachments/assets/a019a535-319c-4332-9cf8-e9a8917182e1)

And also for users who want to use a different path for "**Jan Data Folder**". **(Downloaded) Models are often heavy, and keeping them on the main disk can quickly overload a disk**. You can therefore use an **external disk** or something different from the default path. https://github.com/janhq/jan/issues/3262#issuecomment-2269623836
