### ISSUE TITLE
bug: Wrong UX with model selection

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3286]
Bugs:
1. My previous API key for Anthropic is gone after the migration although the migration was successful
2. I can still select any cloud model although i haven't input any API key yet? Also the UI of settings icon placement is wrong. (See below video)

https://github.com/user-attachments/assets/b59d0c5d-8868-4de9-b630-9e34871fcba5

Expected behavior: Models should be disable til i insert API key. The settings icon placement should be next to the model provider only.
Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=1801-124138&t=HKUMfsb5l88Od0W7-4

![Image](https://github.com/user-attachments/assets/45bf1db1-e4b8-441d-9182-88b73545a0af)

**Comment by urmauur** [comment]
@Van-QA number 2 is done
