### ISSUE TITLE
design: Plugin-base approach App Design

### ISSUE THREAD

**Issue by drakehere** [janhq/jan#329]
### UI Service Description 

**Side-Ribbon: Apps**

- This is a protected area, for Apps
- Apps can define Left Panel, Center, and Right Panel
- We will only have 1 App for now (no need to build this abstraction yet)
- Future: Server mode (see LMStudio), Art Studio (Stable Diffusion)

**Side-Ribbon: Global Settings**

- These will all open in a modal
- Currently: Model Store, Running Models
- Currently: User Login, Settings

**Main Window and Right Panel**

- These will mainly be session-based
- See Obsidian's plugin guide

**UI API for Plugins**

- See Obsidian's plugin guide for best practices
- e.g. Model Store plugin -> Registers "Global Settings" Icon, defines what will show up in the Modal
- e.g. Model Runner plugin -> Inference Parameters

**Comment by drakehere** [comment]
Daniel's idea:[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBemc0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7d902802c7d4e9f9a149595fd713588b3db2b1f3/Danielidea.png)

**Comment by 0xSage** [comment]
this was done
