### ISSUE TITLE
feat: Rewrite Jan starting loading pop-up modal

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3292]
Replace this one:

![Image](https://github.com/user-attachments/assets/fff2a2b5-7f76-4998-b128-09b1a7ea6854)

To this:

![Image](https://github.com/user-attachments/assets/32f7cf2e-4f14-4c72-9fb6-26493137da79)
![Image](https://github.com/user-attachments/assets/a04dfd1e-9696-45d5-a7e5-594070ce8299)

Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=7400-50594&t=HKUMfsb5l88Od0W7-4

**Comment by 0xSage** [comment]
@urmauur is this fixed? I think your PR didn't autoclose this issue

**Comment by 0xSage** [comment]
no longer relevant
