### ISSUE TITLE
feat: Provider Extension - GitHub

### ISSUE THREAD

**Issue by nikiluk** [janhq/jan#3296]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Add support of the GitHub models from https://github.com/marketplace/models

![image](https://github.com/user-attachments/assets/fe29054c-9371-49e9-93bf-2c9c994edece)

### Describe the solution

The solution will allow adding one of the GitHub models to the Jan environment

Prerequisites:
```
BACKGROUND:
GIVEN User has created a personal access token in GitHub as described in the GitHub models documentation
AND the user has activated access to the models here https://github.com/marketplace/models
```

Scenario:
```
WHEN the user visits Jan Settings
THEN the user will see GitHub in the list
AND the user will be able to enter their PAT
AND use the model from GitHub models
```

### What is the motivation / use case for changing the behavior?

Motivation is to support new ways of accessing the models

**Comment by dan-homebrew** [comment]
Closing in favor of #3786
