### ISSUE TITLE
feat: Keyboard Shortcuts

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#330]
**Problem**
- I don't use the mouse
- Jan requires me to use the mouse

**Feature Request**
- `cmd+enter` to send message
- `cmd+n` to create new convo window
- `cmd+f` focus into search bar in active page/view
- `cmd+k` search for chat history, models, plugins
- ?

**Comment by 0xSage** [comment]
CMD+K is usually a search function

**Comment by 0xSage** [comment]
it seems we already support cmd+enter. coolness

**Comment by dan-jan** [comment]
Closed thanks to @urmauur!
