### ISSUE TITLE
bug: Chat message box loses focus after CMD + tab

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#3301]
### #

- [ ] I have searched the existing issues

### Current behavior

When switching back to the Jan app using CMD + tab, the chat message box often loses focus. This causes issues because any typing after switching back may result in unintended actions like trying to open a file instead of typing a message.

### Minimum reproduction step

CMD + tab while chatting with AI.

### Expected behavior

Ensure that the chat message box automatically regains focus when cmd+tab'ing back into the app.

### Screenshots / Logs

.

### Jan version

0.5.2

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Understand user's use case where they want to copy paste quickly from some other places to Jan app. However, this is not a standard implementation for apps, can try use other apps to find out :). I'll close this ticket and would suggest users to use `Quick Ask` feature once we decouple it.
