### ISSUE TITLE
bug: Advanced settings has responsive issue?

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3302]
Missing buttons for this item

![Image](https://github.com/user-attachments/assets/51386c49-bb12-4498-b41f-2ae974f071eb)

**Comment by namchuai** [comment]
This issue is fixed.

**Comment by Van-QA** [comment]
Resolved

![Image](https://github.com/user-attachments/assets/142a816d-89f2-4120-af15-03416ddc2a38)
