### ISSUE TITLE
Discussion: Jan cloud native - download model progress on web

### ISSUE THREAD

**Issue by nam-john-ho** [janhq/jan#331]
**Motivation**
Bring download model progress on Explore Models tab and My Model tab to the Web version. This feature already implemented on the Desktop version. 
![Screenshot 2023-10-12 at 11 26 15](https://github.com/janhq/jan/assets/146448941/ca6b7048-3df3-49c1-87db-138d6b6e037f)
![Screenshot 2023-10-12 at 11 26 01](https://github.com/janhq/jan/assets/146448941/c9cb2d86-114f-4c16-8bb7-fa25e06985c4)
**Challenges**
 Status Quo: In desktop version, download process easy to interact with render process via IPC call
Web version: 
* Check process via http polling or web-socket.
* Change web code-base to adapt both IPC and http call.

**Discussion**

* Http server: an API to check downloading progress of model file.
* Web: Call Api to server to check progress using http polling , then update on UI
* Update web code-base to work with both both IPC and http polling

**Comment by louis-jan** [comment]
Since #358, now you can add events and sync download progress between plugin (renderer) & app 

Scoped at Plugin Level instead of Web App Level

Plugin:
index.ts polls status from module (IPC / HTTP) -> emit new progress event
App: 
subscribe to progress event and update UI

**Comment by 0xSage** [comment]
solved?
