### ISSUE TITLE
feat: [UX improvement] Add model selection option in `Assistant tab` in right sidebar

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3313]
- Add model selection option in Assistant tab
- When users click on `Settings icon` next to model selection -> open `Model Settings` tab (similar UX to model settings in input field)

Figma: 
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=1847-39527&t=hE2obwrOWU7yD3uF-4

![Image](https://github.com/user-attachments/assets/8d13dbbf-53fb-4b4a-9e0b-2de725141515)

**Comment by imtuyethan** [comment]
Can we have bigger menu here, it's ok for the modal to be big & override, width = 300px

![Image](https://github.com/user-attachments/assets/1cdd8e81-373e-487d-9f64-baa6f5ae0ee0)
![Image](https://github.com/user-attachments/assets/89d3ec5b-5f26-4410-ae07-cc39834c61b2)

@urmauur

**Comment by Van-QA** [comment]
Deprecated
