### ISSUE TITLE
bug: `My Models` Missing logos & settings icons next to cloud providers

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3315]
## Bugs:
- [ ] Missing icon next to cloud providers
- [ ] Missing logos for these engines 

![Image](https://github.com/user-attachments/assets/1323cbc5-c418-49d4-a766-db1aeaa3b3b2)

## Correct one should be:

Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=5303-15482&t=e9fwuvNXHWa7smFl-4

![Image](https://github.com/user-attachments/assets/d8039f26-60fe-443e-9411-af16105ab4ef)

**Comment by Van-QA** [comment]
@urmauur some logo are missing


![Image](https://github.com/user-attachments/assets/42529cbd-bbae-41a2-a8d2-70a5de6da253)

**Comment by imtuyethan** [comment]
Deprecated based on the latest v.0.6 alignment
