### ISSUE TITLE
bug: show model size & bad subtitle copy

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3317]
### #

- [ ] I have searched the existing issues

### Current behavior

<img width="693" alt="image" src="https://github.com/user-attachments/assets/c8f3dd1f-d4db-4045-9fe6-9779a385177a">

It is a regression that we don't show model size anymore. So which size model is user installing by default?

### Minimum reproduction step

see screenshot

### Expected behavior

1. add back (default) model size
2. fix copy "Download models to use them locally and offline."

### Screenshots / Logs

see attached

### Jan version

583

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
deprecated
