### ISSUE TITLE
epic: Extensions pages (UI only)

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3321]

**Comment by Van-QA** [comment]
potentially related to https://github.com/janhq/jan/issues/3134

**Comment by urmauur** [comment]
@dan-homebrew @imtuyethan can i clarify this ticket? is this ticket related to https://github.com/janhq/jan/issues/3134 ? cc @Van-QA

**Comment by imtuyethan** [comment]
> @dan-homebrew @imtuyethan can i clarify this ticket? is this ticket related to #3134 ? cc @Van-QA

Don't work on it yet, have not finalized, let me move it out of sprint

**Comment by imtuyethan** [comment]
Deprecated
