### ISSUE TITLE
feat: Windows should `default` solid theme

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3324]
https://discord.com/channels/1107178041848909847/1271369175318925332

**Comment by urmauur** [comment]
@Van-QA this is related to https://github.com/janhq/jan/issues/3084 and https://github.com/janhq/jan/issues/3093

**Comment by Van-QA** [comment]
Tested and looking good on Jan 0.5.3-619

**Comment by imtuyethan** [comment]
Related https://github.com/janhq/jan/issues/3628
