### ISSUE TITLE
epic: V0.6.0 Migration Wizard

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3325]
https://discord.com/channels/1107178041848909847/1149558035971321886/1271379014203998249

This is the new migration screens, since migration logs are not always necessary to show so i hide it in a dropdown.

Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=7465-73264&t=VU8rTIkBKXFb3X7S-4

**Comment by imtuyethan** [comment]
This is the updated designs 🎉
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=7465-73264&t=VU8rTIkBKXFb3X7S-4

![Screenshot 2024-08-09 at 4 39 23 PM](https://github.com/user-attachments/assets/b0c650ce-9167-4ffb-a523-4a216df09b8b)

![Screenshot 2024-08-09 at 4 36 39 PM](https://github.com/user-attachments/assets/14d1c110-11e7-4c03-8898-b7e3c0eba7a4)

![Screenshot 2024-08-09 at 4 39 18 PM](https://github.com/user-attachments/assets/332134b4-db55-415a-b7f5-d97d3d0c6d0c)

**Comment by Van-QA** [comment]
Depr‌ecated after Jan x Cortex r‌ollback

**Comment by imtuyethan** [comment]
#3365

**Comment by dan-homebrew** [comment]
I am deprecating this issue as we are no longer doing a Cortex Platform migration
