### ISSUE TITLE
epic: Simplify Jan + Cortex folder locations

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3329]
Right now, we write to multiple file locations (even for logs)
We should explore simplifying this
![image](https://github.com/user-attachments/assets/b53d7fc1-55ca-42d7-99f3-04d96a1915d8)

https://discord.com/channels/1107178041848909847/1271333287138299934/1271358825911550024

**Comment by louis-jan** [comment]
Update: 
~.janrc,  ~/library/Logs are no longer available since we reverted jan x cortex PR

**Comment by louis-jan** [comment]
Remain:
~/jan - Default Jan Data Folder 
~/Library/Application\ Support/jan - Electron App
~/ Library/Caches/jan - App Auto Updater - Checking for the possibility of a move

**Comment by louis-jan** [comment]
Update: 
`~/Library/Caches/jan` is not configurable from Auto Updater, it's hard coded 

See:
- https://github.com/electron-userland/electron-builder/blob/8e6c17124cdc523620a66efaf871ef8d335c0f49/packages/electron-updater/src/AppAdapter.ts

- https://github.com/electron-userland/electron-builder/issues/4769

**Comment by louis-jan** [comment]
To investigate: 
- Jan data folder setting default to `/Application\ Support/jan`

**Comment by louis-jan** [comment]
cc @irfanpena for the docs update.

**Comment by irfanpena** [comment]
@louis-jan to confirm, is this correct?
![Screenshot 2024-08-28 102734](https://github.com/user-attachments/assets/b79fc078-c7a1-4d6b-953c-3c15ff90db63)

**Comment by Van-QA** [comment]
![Image](https://github.com/user-attachments/assets/e5cad168-42f6-401a-8aa7-a8424b5b8cac)

tested and looking good on Jan v0.5.2-615

**Comment by Van-QA** [comment]
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3, feel free to get back to us if any concern
