### ISSUE TITLE
feat: Model engines are collapsable within model selection dropdown

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3331]
# In Model Menu in Threads
Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=7480-134479&t=VU8rTIkBKXFb3X7S-4

- Cloud model: Show icon `+` is users haven't input any API key
- Default to: Expand models that users have downloaded or insert API key while collapse the rest. 

![Screenshot 2024-08-09 at 6 08 43 PM](https://github.com/user-attachments/assets/1491074d-31d4-415e-a29e-25c44ea4d13b)

# In `My Models` page
Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=5303-14532&t=hUj1k73d2gxmAfY4-4
- Default to: Expand models that users have downloaded or insert API key while collapse the rest. 

![Screenshot 2024-08-14 at 5 40 07 PM](https://github.com/user-attachments/assets/ffb2e7e1-0cf1-4aee-808c-6b556a12807f)

**Comment by Van-QA** [comment]
@urmauur, the dropdown icon is overlapping with the scroll bar, not sure if this is expected or not, thank you

![Image](https://github.com/user-attachments/assets/e41a29e6-8414-447d-a71b-20b908f87374)
