### ISSUE TITLE
bug: Model card should have default download button

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3332]
How it should be: 
- Should have default download button at top
- For the list of versions, the default one should have download button in `primary` color while the rest are `neutral gray`
- The default one should also have `default` tag next to it 

![Image](https://github.com/user-attachments/assets/ab3f0c28-a136-4543-949d-0eea35859cef)

Moreover:

![Image](https://github.com/user-attachments/assets/99e9398d-a5b9-4460-827e-43a79f9bc6a9)

Correct hover interaction: 
Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=7480-134565&t=VU8rTIkBKXFb3X7S-4
![Image](https://github.com/user-attachments/assets/8f4d0a1f-9d20-4deb-baba-e10e8f4f77c8)

(Sorry guys! This was my fault for forgetting to create hover stage! So sorry!!)

**Comment by Van-QA** [comment]
Deprecated since the revert of Jan x Cortex
