### ISSUE TITLE
bug: UI issues (Batch 2)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3333]
Thanks @urmauur for the first batch! Here's the 2nd batch, i'll try my best to include as much as i could before Monday (12 Aug)!! 

These are just small nitpicks on the current UI (font, color, alignment, etc).

https://www.figma.com/design/nWgBmwxaZ2CVrJT6CIoiGO/QA-Jan-x-Cortex?node-id=15-381&t=9zNoCi9XFryG102G-4

![Screenshot 2024-08-12 at 11 55 06 AM](https://github.com/user-attachments/assets/1162e16b-ccc6-4a08-9daa-380660ea9cac)

**Comment by Van-QA** [comment]
Moved back to in progress since No.1 related to datetime does not resolved @urmauur 
![image](https://github.com/user-attachments/assets/8980bb81-22c1-4bdd-8a92-eac88f223208)
