### ISSUE TITLE
feat: simple authentication plugin

### ISSUE THREAD

**Issue by nam-john-ho** [janhq/jan#334]
**Problem**
Using Jan on a web browsers without authentication is insecure.
**Success Criteria**
Create a simple authentication plugin that allows users to log in to Jan using their username and password.
**Discussion**
* A default username and password will be created when Jan runs for the first time.
* User will be ask for changing username/password

![Screenshot 2023-10-12 at 15 43 20](https://github.com/janhq/jan/assets/146448941/797d501b-1358-4144-bb93-f0e97651c32c)

**Comment by louis-jan** [comment]
Since you are working on Cloud Native, would like to reassign @namchuai.

cc @dan-jan

**Comment by 0xSage** [comment]
closing as a wont do for now
