### ISSUE TITLE
bug: Mistral 7b results in `Unexpected end of JSON input`

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3361]
### #

- [x] I have searched the existing issues

### Current behavior

https://discord.com/channels/1107178041848909847/1271124876530290760

When attempting to run the Mistral model locally without internet, the user receives an "Unexpected end of JSON input" error message. The app is unable to start the model successfully.

### Minimum reproduction step

1. Install Jan version 0.5.2
2. Attempt to run the Mistral 7B model locally (Model ID: mistrala/mistral-7b-instruct-v0.2)
3. Observe the error message in the chat interface

### Expected behavior

The Mistral model should load and run successfully without internet connection, allowing the user to interact with it.

### Screenshots / Logs

![Screenshot 2024-08-13 at 2 41 30 PM](https://github.com/user-attachments/assets/d7bfae08-561d-4570-9acc-af5e35ff60da)

### Jan version

0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment details

-

**Comment by Van-QA** [comment]
Reproducibl‌e and need investigation from dev tea‌m
![image](https://github.com/user-attachments/assets/a9d00a4c-3eca-41f8-8a88-87df9e77f5ce)

**Comment by imtuyethan** [comment]
## Tested on:
- [x] Mac:
> Operating System: MacOS Sonoma 14.2
Processor: Apple M2
RAM: 16GB

> Operating System: MacOS Ventura 13.3.1
Processor: Apple Intel
RAM: 8GB

 ## Result:

**Comment by dan-homebrew** [comment]
![Image](https://github.com/user-attachments/assets/925e6887-52d3-4f5a-b655-e1e9d45ea238)

Actually, this issue is quite straightforward - the user was trying to run the base model itself, and not the GGUF needed for llama.cpp
