### ISSUE TITLE
bug: Can't add Hugging Face model

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3362]
### #

- [X] I have searched the existing issues

### Current behavior

https://discord.com/channels/1107178041848909847/1270016772145418240

When attempting to add HuggingFace models to Jan, the user can see the model information but no download buttons appear. This prevents the user from adding the model to Jan.

### Minimum reproduction step

- Open Jan version 0.5.2 or 0.5.2-573 (nightly build)
- Navigate to the model import section
- Paste the HuggingFace model URL: https://huggingface.co/RichardEkhov/cognitivecomputations_-_dolphin-2.9.2-qwen2-7b-gguf
- Observe that model information is displayed, but no download buttons are available

### Expected behavior

When a valid HuggingFace model URL is entered, Jan should display the model information along with download buttons for the available versions, allowing the user to add the model to Jan.

### Screenshots / Logs

![gguf](https://github.com/user-attachments/assets/a9b7b9ff-2a90-4c6b-863f-639eb6a5b027)

### Jan version

 0.5.2 or 0.5.2-573 (nightly build)

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Environment details

-

**Comment by louis-jan** [comment]
Hmm due to weird folder structure of the model repo

**Comment by louis-jan** [comment]
I think that's something to do with app responsiveness, which Faisal already addressed in another issue.

![Image](https://github.com/user-attachments/assets/ca059720-a585-4a94-92e5-b10a3a4c490f)

**Comment by louis-jan** [comment]
DUP #3181?
