### ISSUE TITLE
Awesome work!! Keep it up :)

### ISSUE THREAD

**Issue by artknight** [janhq/jan#3364]
Hey, sorry to post it here as I did not see any way to contact you. I really like your work, so I am going to feature it in the tomorrow's issue of my my daily newsletter,  https://dailysandbox.com

**Comment by imtuyethan** [comment]
> Hey, sorry to post it here as I did not see any way to contact you. I really like your work, so I am going to feature it in the tomorrow's issue of my my daily newsletter, https://dailysandbox.com

Hey huge thanks for trying us out!!
Please contact us on Discord: https://discord.com/invite/FTk2MvZwJH
