### ISSUE TITLE
feat: Provider Extension - OpenAI

### ISSUE THREAD

**Issue by dontevenblink** [janhq/jan#3370]
## Goal
- Support OAI api models
- Users can see available models in hub
- Users can chat with available models, given the right model parameters

### Original User Issue

**Add support for GPT-4o Mini**

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Jan does not support openAI's GPT-4o Mini. 

### Describe the solution

Add support for GPT-4o Mini.

### What is the motivation / use case for changing the behavior?

GPT-4o mini is openAI's most cost-efficient small model that’s smarter and cheaper than GPT-3.5 Turbo.

**Comment by louis-jan** [comment]
Related issue:
https://github.com/janhq/jan/issues/3374

**Comment by imtuyethan** [comment]
Scoped in Jan v0.6.0 uses Cortex Extension

**Comment by dan-homebrew** [comment]
Closed in favor of #3786
