### ISSUE TITLE
feat: Anthropic prompt caching

### ISSUE THREAD

**Issue by khromov** [janhq/jan#3372]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

-

### Describe the solution

By using Anthropic prompt caching, longer chats with a lot of context are substantially cheaper:
https://www.anthropic.com/news/prompt-caching 

### What is the motivation / use case for changing the behavior?

-

**Comment by louis-jan** [comment]
DUP: #3320

**Comment by imtuyethan** [comment]
Close as duplicated with #3320
