### ISSUE TITLE
feat: Settings - Support new Cortex extension / 3 new engines with config

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3380]
- Add Cortex to models provider, 1 new extension that support 3 engines (cortex.llamacpp, cortex.tensortRT, cortex.onnx) to extensions tab
- My models: Separate group of models for Cortex extension (x3 engines) and previous Nitro engines
- Hardware acceleration: remain the same - global settings
- ENH: Disabled engines should not be visible from Jan hub

**Comment by 0xSage** [comment]
dupe of #3376
