### ISSUE TITLE
feat: users can configure and opt out of services

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#34]
Current: Jan monorepo is opinionated and heavy with many services, many of which are not critical to the individual enthusiast
e.g. keycloak, minio, services noncritical to the inferencing

Users may not love the many containers, lengthy scaffold time, or they may just not like the particular 3rd party integration tools that we chose.

Ideal: Let's make such services and their respective 3rd integrations hot swappable. 

Rough design:
- Services can be turned off via a config yaml in base repo
- Can we turn off the entire app backend if users don't want to persist data?
- [optional] services can be swapped for a different 3rd party provider endpoint, e.g. aws s3 -> gcp store

**Comment by namchuai** [comment]
@0xSage , as discussed with @louis-jan , this issue should be postponed later.

**Comment by 0xSage** [comment]
👍👍

**Comment by 0xSage** [comment]
going in this dir with plugins. closing
