### ISSUE TITLE
[v0.5.2-590] Automatically naming threads doesn't work

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3408]
Automatically naming threads doesn't work

https://github.com/user-attachments/assets/15db85b7-45a1-42c8-a313-cb19c8bc9d86

Model used: Gemma 7B
Jan v0.5.2-590
Operating System: MacOS Sonoma 14.2
Processor: Apple M2
RAM: 16GB

**Comment by louis-jan** [comment]
Some models do not work really well with the instructions, so the thread title response does not meet the constraints. (Or our instruction prompt is not good enough).
