### ISSUE TITLE
feat: Use latest nitro when releasing new Jan version

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/jan#343]
**Problem**
- Nitro inside Jan is easily outdated and need manual copy/ paste which is not good

**Success Criteria**
- No manual steps.
- On every new Jan release, new version of Nitro gets embedded with proper usage.

**Additional context**
- The latest build is here: https://github.com/janhq/nitro/releases/tag/v0.1.1

**Comment by hiento09** [comment]
Hey, I am going to modify the CI for inference-plugin to pull a specific version of nitro as it's prebuild binary. Will do it this week.

**Comment by hiento09** [comment]
Resolved in https://github.com/janhq/jan/pull/524
