### ISSUE TITLE
feat: Settings - Allow turning ON/OFF scroll bar visible by default or only on hover / scroll 

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3438]
**Describe the bug**

**Expected behavior**

> Auto-hide Scroll Bars
> Turn this ON to hide scrollbars by default, and only appears when hovering or scrolling (reload needed).

**Screenshots**
![image](https://github.com/user-attachments/assets/909ec5ca-622f-4cfa-8668-82b126b78362)

**Comment by urmauur** [comment]
checking our code base, currently this is not yet doable bc no all scroll using ScrollArea component, so i need check all screen and component using ScrollArea first, and since it's part of setting, i need design also how in setting looks like cc @imtuyethan @Van-QA i'll move into icebox

**Comment by 0xSage** [comment]
wont do, given all of our backlog
