### ISSUE TITLE
feat: Assistants have Persistent Memory

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#344]
**Problem**
- Now Jan bot do not know what me as the user talked with the bot before

**Success Criteria**
- It remembers and can answer me correctly

**Additional context**

**Comment by 0xSage** [comment]
@vuonghoainam can you elaborate on the recommended solution? Are you referring to giving bots "long term" memory, i.e. through indexing historical convo data somewhere, rather than just the context window?

**Comment by 0xSage** [comment]
I get it now. We want assistants to retain previous conversation `threads`. Neat!

This lends itself to our file-based approach where: 

/assistants
    /homework-helper
        /threads                # conversation that needs to be remembered
/threads                        # 1 time conversations that can be forgotten
