### ISSUE TITLE
bug: Cannot import model

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3444]
### #

- [X] I have searched the existing issues

### Current behavior

I tried using it this morning after remembering that it was installed. I updated to the latest version, then tried to add a GGUF I had already downloaded, but it wouldn't complete and didn't provide a useful error message. So, I un-installed it.

<img width="790" alt="Screenshot 2024-08-23 at 6 35 05 PM" src="https://github.com/user-attachments/assets/e345c2ca-2d14-4f5c-a9e2-60600ae57400">

### Minimum reproduction step

-

### Expected behavior

-

### Screenshots / Logs

-

### Jan version

-

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Environment details

-

**Comment by marknguyen1302** [comment]
hi @imtuyethan , do we have any further information about this issue? I tried on Mac and Windows and it still works, so this may be this is in the old version.

**Comment by kalle07** [comment]
NO new version on windows 10 updated today 

![grafik](https://github.com/user-attachments/assets/08a7f6d3-d2eb-4673-aea7-c90482d4f9ad)


restart JAN  BUT no models on local device

**Comment by kalle07** [comment]
last update last month all ok, and still working WEBui

no i try update (update_wizard_windows.bat)


(e:\text-generation-webui\installer_files\env) e:\text-generation-webui>git pull
error: cannot lock ref 'refs/remotes/origin/dependabot/pip/dev/gradio-eq-4.42.star': Unable to create 'E:/text-generation-webui/.git/refs/remotes/origin/dependabot/pip/dev/gradio-eq-4.42.star.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
From https://github.com/oobabooga/text-generation-webui
 ! [new branch]        dependabot/pip/dev/gradio-eq-4.42.star -> origin/dependabot/pip/dev/gradio-eq-4.42.star  (unable to update local ref)

(e:\text-generation-webui\installer_files\env) e:\text-generation-webui>

**Comment by Van-QA** [comment]
@Enchante503 we resolved the issue in Jan nightly 0.5.2-618, after released, this will become Jan 0.5.3 stable,
For now, you can try the nightly build via https://discord.com/channels/1107178041848909847/1277949165049221202/1278263799325130752

**Comment by Van-QA** [comment]
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3, feel free to get back to us if any concern
