### ISSUE TITLE
bug: The version doesn't change when you switch branches

### ISSUE THREAD

**Issue by Enchante503** [janhq/jan#3445]
### #

- [X] I have searched the existing issues

### Current behavior

I started it with make dev but there was an error

The browser's DevTools will appear.

### Minimum reproduction step

make dev

and..
Even if you switch the branch to main or Dev and run make dev, the version remains **v0.1.0.**

### Expected behavior

It started without errors.

### Screenshots / Logs

jan:dev: [299509:0824/053201.072475:ERROR:CONSOLE(1)] "Uncaught (in promise) TypeError: Failed to fetch", source: devtools://devtools/bundled/panels/elements/elements.js (1)
jan:dev: APPIMAGE env is not defined, current application is not an AppImage
![2024-08-24_06h32_04](https://github.com/user-attachments/assets/a7c879fe-e126-42bf-84fb-7f1b75ddf5e5)

### Jan version

Jan v0.1.0　<--　The version is not 0.5.2 either.
![2024-08-28_17h22_19](https://github.com/user-attachments/assets/469af38e-379d-41cd-9fc5-278a60249312)

### In which operating systems have you tested?

- [ ] macOS
- [x] Windows
- [X] Linux

### Environment details

WSL2 Ubuntu 22.04.4 LTS
Pyenv Python3.11.3  CUDA12.1  torch 2.3.0+cu121

**Comment by Van-QA** [comment]
hi @Enchante503, 
‌Y‌ou are correc‌t, it's possible to change the version, you can make the modification in electr‌on/package.json, but that is just a la‌bel, to highlight the different build number, just like naming something to make it ea‌sier for discussio‌n / troubleshooting.

![Image](https://github.com/user-attachments/assets/24252bfd-d53b-4e0f-af54-bde3376235ed)

If you are already ha‌ve the latest code on the dev branch, the build number label should not affect the app's output. All the latest functions should be included. I hope this can help.

**Comment by 0xSage** [comment]
Feel free to reopen if you need more help 🙏

**Comment by 0xSage** [comment]
@urmauur any tips or help you can give here?

**Comment by urmauur** [comment]
We currently display the current version on both the dev and main environments. With every release, we update the version to reflect the latest one on `dev`.

<img width="261" alt="Screenshot 2024-11-21 at 15 57 39" src="https://github.com/user-attachments/assets/03aabd73-022f-4749-9d44-abe600675fb9">

If you still don’t see the correct version, please feel free to reopen this ticket
