### ISSUE TITLE
bug: [When I open it in a browser I get an error]

### ISSUE THREAD

**Issue by Enchante503** [janhq/jan#3447]
### #

- [ ] I have searched the existing issues

### Current behavior

When I open http://localhost:3000 in my browser, I get an error

### Minimum reproduction step

After launching, open http://localhost:3000 in your browser.

### Expected behavior

Use jan in your browser
If you open it in Chrome, you can use the translation and other features.

### Screenshots / Logs

![2024-08-24_14h01_09](https://github.com/user-attachments/assets/21c1d9f0-2c5f-4313-951d-458500640553)

### Jan version

Jan v0.1.0

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

### Environment details

WSL2　Ubuntu 22.04.4 LTS
Chrome

**Comment by Van-QA** [comment]
Hey there! Thanks for trying out Jan. 

We've actually decided to deprecate Jan On-premise. Sorry for any confusion this might have caused.

We're focusing our efforts on improving the main Jan application to better serve our users. If you're looking for alternative solutions, you might want to check out Cortex (https://github.com/janhq/cortex) for headless AI operations.
Appreciate you taking the time to report this. Let us know if you have any other questions! 🙏
