### ISSUE TITLE
feat: Recommendation for user running models

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/jan#345]
**Problem**
- It's hard to prepare `Recommended for your hardware` feature per machines
- We are hard coding on https://github.com/janhq/models for mem required

**Success Criteria**
- Calculate automatically given current machine spec (what we can get from `monitoring plugin` and model spec

**Additional context**
- https://huggingface.co/spaces/Vokturz/can-it-run-llm/tree/main

**Comment by 0xSage** [comment]
Closing as its a part of new spec/designs
