### ISSUE TITLE
feat: Provider Extension - OpenRouter

### ISSUE THREAD

**Issue by Editquest** [janhq/jan#3452]
## Goal
- Support OpenRouter as a remote provider 
- Available OR models should show up in Hub

## Original User Request

- [X] I have searched the existing issues

### Current behavior

Is there a way to get it show the list of model's available and be able to pick one?

{
  "sources": [
    {
      "url": "https://openrouter.ai"
    }
  ],
  "id": "open-router-auto",
  "object": "model",
  "name": "OpenRouter",
  "version": "1.0",
  "description": " OpenRouter scouts for the lowest prices and best latencies/throughputs across dozens of providers, and lets you choose how to prioritize them.",
  "format": "api",
  "settings": {},
  "parameters": {
    "max_tokens": 1024,
    "temperature": 0.7,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "author": "OpenRouter",
    "tags": [
      "General",
      "Big Context Length"
    ]
  },
  "engine": "openrouter"
}

### Minimum reproduction step

its on Auto

### Expected behavior

Auto

### Screenshots / Logs

{
  "sources": [
    {
      "url": "https://openrouter.ai"
    }
  ],
  "id": "open-router-auto",
  "object": "model",
  "name": "OpenRouter",
  "version": "1.0",
  "description": " OpenRouter scouts for the lowest prices and best latencies/throughputs across dozens of providers, and lets you choose how to prioritize them.",
  "format": "api",
  "settings": {},
  "parameters": {
    "max_tokens": 1024,
    "temperature": 0.7,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0
  },
  "metadata": {
    "author": "OpenRouter",
    "tags": [
      "General",
      "Big Context Length"
    ]
  },
  "engine": "openrouter"
}

Would switching to work:
import requests
import json

response = requests.post(
  url="https://openrouter.ai/api/v1/chat/completions",
  headers={
    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
    "HTTP-Referer": f"{YOUR_SITE_URL}", # Optional, for including your app on openrouter.ai rankings.
    "X-Title": f"{YOUR_APP_NAME}", # Optional. Shows in rankings on openrouter.ai.
  },
  data=json.dumps({
    "model": "openai/gpt-3.5-turbo", # Optional
    "messages": [
      { "role": "user", "content": "What is the meaning of life?" }
    ]
    
  })
)

### Jan version

Jan v0.5.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

### Environment details

N/A

**Comment by Van-QA** [comment]
![image](https://github.com/user-attachments/assets/dde92687-afa2-40f9-9ca6-df07b0be99b2)
![image](https://github.com/user-attachments/assets/5ea43fab-6b65-462c-8383-a9706a764954)
We introduced a new field to input the model, please check it out via Jan nightly
https://github.com/janhq/jan?tab=readme-ov-file#download
Feel free to get back to us if any issue

**Comment by Van-QA** [comment]
Reopen this to cover the openrouter models selection

**Comment by bogorad** [comment]
please allow for multiple, comma-separated model names!

**Comment by 0xSage** [comment]
related #3505

**Comment by dan-homebrew** [comment]
Closing in favor of #3786
