### ISSUE TITLE
bug: Weird vector database toggle and no time-weighted retrieval action

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#3460]
### #

- [X] I have searched the existing issues

### Current behavior

It shows that the Vector Database can be toggled on or off, but actually it cannot.

### Minimum reproduction step

1. Go to Settings
2. Turn on Experimental Feature
3. Back to the Thread
4. Toggle on Retrieval
5. See the issue

### Expected behavior

The toggle actually belong to Time-Weighted retrieval - not vector database which is disabled

### Screenshots / Logs

<img width="1239" alt="Screenshot 2024-08-26 at 14 34 35" src="https://github.com/user-attachments/assets/8f08d644-b07e-4340-8c0e-6d47f17aaaf5">

### Jan version

0.5.2-608

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Van-QA** [comment]
![Image](https://github.com/user-attachments/assets/454aa7e4-8a02-48ee-9d4b-57d20e5cc0b2)

tested on Jan v0.5.2-619

**Comment by Van-QA** [comment]
Jan 0.5.3 is released to stable version of Jan app: https://github.com/janhq/jan/releases/tag/v0.5.3, feel free to get back to us if any concern
