### ISSUE TITLE
feat: Using command Key for Shortcut Badges 

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3464]
**Summary**: Enable a feature where holding the "Command" key displays shortcut badges on all actionable items, making shortcuts more discoverable and reducing the need to memorize them.

**Description**: When users hold the "Command" key, show shortcut badges on buttons and menu items. This will make it easier for users to learn and use keyboard shortcuts, improving overall efficiency and usability.

**Comment by 0xSage** [comment]
This will break basic functionality like navigating text. 
e.g. cmd+ < moves 
left 1 word

**Comment by 0xSage** [comment]
apps typically have a shortcut combo, e.g. cmd+alt+p or something. That said, not critical.
