### ISSUE TITLE
bug: UI when RAG & Tools do not support remote models other than OpenAI

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3472]
**Description:**

The Tools tab is currently accessible when using remote models, despite the fact that these models (with the exception of OpenAI) do not support tool usage. This creates confusion for users and can lead to unexpected behavior.

**Steps to reproduce:**

1. Configure Jan with a remote model provider (excluding OpenAI).
2. Navigate to the Jan interface.
3. Click on the "Tools" tab.

**Expected behavior:**

The "Tools" tab should be hidden or disabled when using remote models that do not support tool functionality.

**Actual behavior:**

The "Tools" tab is visible and accessible, even though it is not functional with the selected remote model.
![image](https://github.com/user-attachments/assets/78c607c1-ce97-4f20-bc05-5cf202836401)

- User confusion: Users may mistakenly believe they can use tools with remote models, leading to frustration when they encounter errors or unexpected results.

**Proposed solution:**

- Implement logic to dynamically hide or disable the "Tools" tab based on the selected model type.
- Display a clear message to users explaining that tools are not supported with the current remote model.

> Not supported for this model 

- Consider hiding the upload button (with Retrieval ON)

**Additional context:**

This issue arises because the current implementation does not differentiate between model types when displaying the "Tools" tab. A solution should be implemented to ensure that the tab is only visible and functional with models that support the desired tool functionality.

**Comment by 0xSage** [comment]
Yikes, this should be a design decision no? Hiding tools tab is really flakey , buggy UX

**Comment by imtuyethan** [comment]
Finalize as discussed here: https://discord.com/channels/1107178041848909847/1149558035971321886/1277898971624374273
