### ISSUE TITLE
[UI updates] Add tabs to model selection

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3475]
Specs: https://www.notion.so/jan-ai/UI-updates-New-model-selection-once-cortex-models-are-populated-e89230e05a82457f85c4e194be8bb926?pvs=4

Figma: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=7480-134479&t=tP4XUtyZk6tTrQHR-4

------
# Objectives
Once we populate Cortex models in Hub (Jan 0.5.2 with Cortex platform extensions), model selection in threads should be updated & categorized accordingly.

# Key user stories
- Users should be able to differentiate between:
    - Models from Cortex extension (built-in models)
    - Hugging Face models
    - Legacy models (old model run by Nitro extension, populated before Jan v0.6.0)
- Users should be able to differentiate between On-device models & Cloud models easily

![Image](https://github.com/user-attachments/assets/59e9b94e-8348-4e3c-8250-6063a656d771)

**Comment by jan** [comment]
@imtuyethan wrong Jan, but have a great day!

**Comment by imtuyethan** [comment]
> @imtuyethan wrong Jan, but have a great day!

HAHA sorry!
