### ISSUE TITLE
epic: Change Jan API server to use cortex.cpp

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3487]
## Goal 

- Jan has "always-on" cortex.cpp process
- Jan's API server screens do not require user to "start server", it should be running as long as Jan is running

## Tasklist

- Designs
- Eng impact (any changes?)

## Original Spec
```
Specs: https://www.notion.so/jan-ai/API-Server-API-Logs-a105e72c0114434aa566f976c543eb8c?pvs=4

We will need to update the API server UI, to reflect the "always-on" API server in Cortex.
```

**Comment by dan-homebrew** [comment]
Merging into #3825
