### ISSUE TITLE
chore: Jan.ai - Features & Platform pages

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#351]
## Objective

- Platform section https://jan.ai/platform
- Should be hidden if we don't have time to complete it
- Homepage features should link to `https://jan.ai/features/*`

## Tasks

- [ ] Platform
    - [ ] Jan Desktop
    - [ ] Jan Mobile
    - [ ] Jan Server
- [ ] Features (i.e. Plugins)
    - [ ] Model Management
    - [ ] Data 
    - [ ] Inference (i.e. Nitro)
    - [ ] System Monitoring
    - [ ] Themes

**Comment by 0xSage** [comment]
direction has changed
