### ISSUE TITLE
feat: Double click/F2 to edit title

### ISSUE THREAD

**Issue by Naith123** [janhq/jan#3511]
### #

- [X] I have searched the existing issues

### Background

I found it slightly unintuitive to not be able to double click or use F2 to edit the title of chats.

### Feature request

Enable [double click] and/or [F2 when clicked on window] to open UI prompt to edit the title of a chat

**Comment by 0xSage** [comment]
Can take care of this along with #3017

**Comment by imtuyethan** [comment]
- Closed as dup / sub-task of https://github.com/janhq/jan/issues/4255
