### ISSUE TITLE
bug: Default instruction from ~/jan/assistants/jan/assistant.json no longer work on linux

### ISSUE THREAD

**Issue by eregnier** [janhq/jan#3515]
### #

- [X] I have searched the existing issues

### Current behavior

default instructions are no longer read from the configuration file when launching a new thread on linux.
I tried to remove the  ~/jan file, remove my .AppImage file and install it from deb source (with today latest version) then fill again the "instructions" field in ~/jan/assistant/jan/assistant.json . Nothing work. I have to copy / paste my instructions from one thread to another instead of just spawning a new thread and go with my "all purpose for my needs" dev instructions.

Thank you for this tool, it is awesome.

By the way, this default assistant behavior is poorly documented (or I my searched does not match this feature documentation easily) , I had to search in github issues to find a way to do this basic (at least for me) thing.

### Minimum reproduction step

do a fresh install under ubuntu by removing the ~/jan folder
fill "instructions" field in the assistant.json file
run jan
-> no default instructions are displayed anymore

![image](https://github.com/user-attachments/assets/da2f47b8-7eb3-4446-93a4-f79514b6b49a)

### Expected behavior

instruction field is filled with the value I wrote in assistant.json file

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/68cd4b59-12e3-42ad-8fb3-1720756edb18)
![image](https://github.com/user-attachments/assets/cc3abe36-795d-4c1f-9f5a-b7e498db6515)

### Jan version

0.5.3

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Environment details

Ubuntu 24.04.1 LTS
Intel I7 CPU gen 13
32Go Memory

**Comment by Van-QA** [comment]
The issue is reproducible, modifying Jan's Instructions does not save to the assistant.json, and vice vesa, value from assistant.json does not display to instruction.
Need to confirm whether this is the expected behavior. ⚠️ 
Current behaviors: the instructions only saved into threads.json
![image](https://github.com/user-attachments/assets/fc83c0c5-f0b3-4660-bae8-a62b193ee71a)

**Comment by imtuyethan** [comment]
## Tested on 
> VM 117 Ubuntu

## Result
I changed the instructions in the assistant.json file and saved it. Then I quit Jan & opened Jan again to see the instruction was not saved to the threads level. I opened the assistant.json file again & saw that the new instruction was still saved.
 
![Screenshot 2024-10-01 at 10 06 23 PM](https://github.com/user-attachments/assets/247fb2bf-a9a7-480f-851b-9b1bce91efa8)

**Comment by louis-jan** [comment]
Hi @imtuyethan, you need to create a new thread to see the new changes applied, as the old thread already contains persisted assistant metadata.

**Comment by imtuyethan** [comment]
Tested again, it worked, thank you
