### ISSUE TITLE
feat: Improve default instruction system

### ISSUE THREAD

**Issue by eregnier** [janhq/jan#3516]
### #

- [X] I have searched the existing issues

### Background

I have to set my default instruction in a file by hand (this is not really an issue for me as I am technical) but the default instruction for all next thread is not well documented (at least this is my feeling), and I find this is a very basic thing common LLM users need.

### Feature request

I would appreciate to be able to set the default instruction for all my futures new threads from jan settings.
As developper, I have a very common default prompt that works in most cases, and I like to fire a thread and just get typing my question.

### Proposed Implementation

V1 : in settings pannel, add a field that let user fill a default prompt, this will be the value that is filled each time in instruction pannel on all new threads.

V2 : add a kind of quick default instruction list user can add / remove named instructions (a key for the name, a value for the prompt), then from a new thread, the user can choose one instruction from the list he created.

V2.1 : let user choose a default instruction from the list which will fill automatically the instruction on new thread.

### Additional Notes

thank you for considering this feature request.

**Comment by imtuyethan** [comment]
Thanks @eregnier for the request! We actually have implemented a settings for this, it's in experimental mode for now, you can turn it on in `Advanced Settings` 


https://github.com/user-attachments/assets/4c0fb5d7-3fd5-420c-9cfb-4c641f6dae79

**Comment by eregnier** [comment]
I works perfectly. thanks :+1:
