### ISSUE TITLE
feat: Graceful failure for model loading (not `Something's Amiss` Error)

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3517]
### #

- [x] I have searched the existing issues

### Background

I'm always frustrated when users encounter vague "Something's Amiss" errors that don't provide actionable information, especially for common issues like VRAM limitations when loading large models. This leads to confusion and extra support requests.

### Feature request

Implement improved error handling in Jan. 
Some issues that potentially cause this error:
- [ ] OOO (VRAM) https://discord.com/channels/1107178041848909847/1279214570346512425
- [ ] [to be updated]

### Proposed Implementation

Based on the lates discussion, it's current pending collecting crash report from users #ana

**Comment by 0xSage** [comment]
Part of a longer discussion here https://github.com/orgs/janhq/projects/5/views/47?pane=issue&itemId=78540537

**Comment by imtuyethan** [comment]
We have bubbled all errors now
