### ISSUE TITLE
bug: GPT-4 doesn't support vision & file search in Jan

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3520]
### #

- [X] I have searched the existing issues

### Current behavior

https://discord.com/channels/1107178041848909847/1279700963439022090
Users are unable to use file-related features in Jan, including GPT-4 Vision capabilities (image analysis) and document upload for RAG (Retrieval-Augmented Generation), despite having added their OpenAI API key and selecting the GPT-4 model. These functionalities should be available but appear to be non-functional.

### Minimum reproduction step

1. Add OpenAI API key to Jan
2. Select GPT-4 model
3. Attempt to send an image for analysis
4. Attempt to upload a document (e.g., PDF) for RAG

### Expected behavior

Jan should be able to:
- Process images using GPT-4's vision capabilities
- Allow document uploads for RAG
- Provide responses or allow for questions about the uploaded content

### Screenshots / Logs

<img width="1043" alt="Screenshot 2024-09-02 at 5 44 24 PM" src="https://github.com/user-attachments/assets/4582c359-b248-4770-95c1-89adb6e4fd4a">

### Jan version

v0.5.3

### In which operating systems have you tested?

Operating System: Pop!_OS 22.04
KDE Plasma Version: 5.24.7
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 6.9.3-76060903-generic (64-bit)
Graphics Platform: X11
Processors: 16 × 13th Gen Intel® Core™ i5-13500H
Memory: 15.3 GiB of RAM
Graphics Processor: Mesa Intel® Graphics

Btw, I have a dedicated Nvidia 4060 as well.

**Comment by 0xSage** [comment]
related #3505

**Comment by imtuyethan** [comment]
Close this ticket as dup?

**Comment by 0xSage** [comment]
> discussions: Remote API Extension #3505

Leave it open bc: 
1. We haven't really impl RAG yet
2. We don't know RAG will work with remote endpoints

**Comment by imtuyethan** [comment]
OpenAI GPT-4o model’s vision capability is enabled:

<img width="846" alt="Screenshot 2024-12-17 at 11 01 18 AM" src="https://github.com/user-attachments/assets/14aad83e-b1c9-42d3-8e5c-927ac2b50210" />
