### ISSUE TITLE
bug: Custom instructions not working for Anthropic models in Jan app

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3528]
### #

- [X] I have searched the existing issues

### Current behavior

Custom instructions for Anthropic models (specifically tested with Claude 3.5 Sonnet) are not being applied properly in the Jan app. When custom instructions are set, the model's responses seem to completely ignore them. 

### Minimum reproduction step

1. Open the Jan app
2. Set custom instructions for a Claude model (e.g., Claude 3.5 Sonnet)
3. Start a new conversation or thread
4. Observe that the model's responses do not reflect the custom instructions

### Expected behavior

The Claude model should incorporate and follow the custom instructions in its responses.

### Screenshots / Logs

<img width="529" alt="Screenshot 2024-09-02 at 6 49 43 PM" src="https://github.com/user-attachments/assets/b6a8d993-9922-402f-925c-3d0398ae9915">

### Jan version

v0.5.3

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

### Environment details

- Jan app (version number to be specified)
- Tested with Claude 3.5 Sonnet model
- Date of occurrence: September 1, 2024

**Comment by Van-QA** [comment]
Closed as duplicated, please follow up using https://github.com/janhq/jan/issues/3513
