### ISSUE TITLE
feat: Prompt user to download model, if no models are available

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3537]
# Problem
When there's no model detected

**Current behavior:** 
We default a cloud model and show API key error, which is not cool.

**Expected behavior:**
We should show that no model is available & recommend users to download one. 

# Design

**Condition to have this flow:** `0 models` + `has at least 1 old thread`
This case likely happen when:
    - e.g. User deletes the `/models` folder from filesystem
    - e.g. User manually deletes all models

_Side Note: Factory Reset is not applied to this case because after Factory Reset, all threads & models are gone -> show starter screen #3217 ._

Figma link: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8124-71826&m=dev

### Scenario 1: User create a new thread

- Show `You don't have any model` & `Explore Hub` button
- User can't collapse this input box til they have selected a model (hide the collapse icon)

<img width="562" alt="Screenshot 2024-11-27 at 6 18 55 PM" src="https://github.com/user-attachments/assets/1addb867-b3fb-4a71-afed-a82fc805185d">

### Scenario 2: User clicks on an old thread

- Default back to this case #3385 

## Tasklist
- [x] Designs @imtuyethan 
- [x] UI Implementation @urmauur 

## Related Issues
- #3385

**Comment by dan-homebrew** [comment]
Merging into https://github.com/janhq/jan/issues/3385

**Comment by dan-homebrew** [comment]
@imtuyethan I am moving this issue into Sprint 20, as @urmauur may be able to get to it this sprint. 

- Can you reply to this thread with the Wireframes for the "no models" scenario?
- We can clear the designs async
- We can queue it for @urmauur next week, and schedule for v0.5.5 release

**Comment by imtuyethan** [comment]
^ Updated the description with new design @dan-homebrew

**Comment by dan-homebrew** [comment]
![Uploading image.png…]()

**Comment by imtuyethan** [comment]
Updated design: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8124-71826&t=t7FOVtMEOSg7nFsJ-4

![Uploading Screenshot 2024-09-17 at 8.28.10 AM.png…]()

cc @dan-homebrew

**Comment by imtuyethan** [comment]
Updated design:
https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8124-71826&t=Eu48etLJ7eAZ5FDp-4

**Condition to have this flow:** `0 models` + `has at least 1 old thread`
This case likely happen when users delete all of their models manually. 

_Side Note: Factory Reset is not applied to this case because after Factory Reset, all threads & models are gone -> show starter screen._

---

# User flows & scenarios

### Scenario 1: User create a new thread
<img width="687" alt="Screenshot 2024-11-08 at 2 44 45 PM" src="https://github.com/user-attachments/assets/7d0ed1cb-0323-4a3f-b41c-d6f4577c49b8">


### Scenario 2: User click on an old thread
Default to #3385

**Comment by imtuyethan** [comment]
@dan-homebrew 

## Updated design
Figma link: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8124-71826&t=Q6vGpmYu9WVyCdDJ-4

<img width="668" alt="Screenshot 2024-11-18 at 2 12 13 PM" src="https://github.com/user-attachments/assets/e860a228-621e-40d1-bf22-04f3a8b8c0ff">

## User flow
### 1. When user creates a new thread
<img width="723" alt="Screenshot 2024-11-18 at 2 18 10 PM" src="https://github.com/user-attachments/assets/0f7288c7-5211-4b60-9a59-9985f9f7ac79">

<img width="738" alt="Screenshot 2024-11-18 at 2 17 11 PM" src="https://github.com/user-attachments/assets/e270e304-6dbf-4dac-92de-8a9d3b4e1fa0">

### 2. When user clicks on any old/existing thread
Default back to this case: https://github.com/janhq/jan/issues/3385

**Comment by imtuyethan** [comment]
@urmauur Update the copy to be correct too:
`You don't have any model`

![Screenshot 2024-12-19 at 6 27 08 PM](https://github.com/user-attachments/assets/6a2a05b9-b639-4333-8379-685c5fb2172e)
<img width="889" alt="Screenshot 2024-12-19 at 6 27 03 PM" src="https://github.com/user-attachments/assets/a01c5ca6-1380-48d6-8071-7bf794505008" />
