### ISSUE TITLE
planning: Users Want Advanced RAG

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3550]
Can we explain user needs in detail 

Top User Requests
- Multi format: (PDF, CSV)
- Multi file upload

Link
-

**Comment by 0xSage** [comment]
Sorry lets use Github Discussions instead for product & feature discs: https://github.com/orgs/janhq/discussions/categories/feature-requests

**Comment by imtuyethan** [comment]
Dup #3499

**Comment by imtuyethan** [comment]
One note from the 0.5.7 Release QA #3818 

---
## Wrong UI of RAG feature (Not urgent, we can fix this later when we improve this feature!):

<img width="927" alt="Screenshot 2024-10-16 at 10 03 46 PM" src="https://github.com/user-attachments/assets/4adafda4-4a0c-4cee-8e46-0a8d027016ea">

**Correct UI:** 
https://www.figma.com/design/ytn1nRZ17FUmJHTlhmZB9f/Jan-App-(1st-version)?node-id=783-43738&t=qhUfC7x5HPV38sei-4

(The design link is also super outdated - it is our old UI)

![Screenshot 2024-10-16 at 10 07 10 PM](https://github.com/user-attachments/assets/77587a73-b53b-49a5-8d81-ee3257361462)

## RAG just doesn't work 
<img width="1000" alt="Screenshot 2024-10-16 at 10 10 09 PM" src="https://github.com/user-attachments/assets/a774e5fb-ebf2-4821-8639-bb1ad34f333e">

<img width="1002" alt="Screenshot 2024-10-16 at 10 10 34 PM" src="https://github.com/user-attachments/assets/dcfb6b9c-7a90-475a-a590-d4644f509807">

**Comment by imtuyethan** [comment]
- Closed as dup of https://github.com/janhq/cortex-internal/issues/20
