### ISSUE TITLE
test: pre-download model and run basic test on different hardware

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3556]
- [ ] pre-download tinyllama from minio, (@hiento09)
- [ ] on different OS, start the model, send message, and verify no error
- [ ] verify token speed: `not lower than X t/s`
- [ ] apply the test run on multiple hardware / engine

Notes:
- Run on PR: on 3 OS 
- Run twice per week: on all hardware supported (the list to be provided soon)

**Comment by Van-QA** [comment]
hi @dan-homebrew, please help me review this test, thank you

**Comment by dan-homebrew** [comment]
Deprecated in favor of Archiving in favor of #3632
