### ISSUE TITLE
roadmap: Enhance Jan Installer and Uninstaller

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3557]
## Blocker
- Cortex refactor
- #3690 

## Questions
- Will Jan also package & distribute via all the formats that Cortex does?
- What is the install UX? Are we using OS level installers to make installation UX better?
- What is the uninstall UX?
- Will Jan have nightly, release, and a prerelease? (see 2861) 

## Related issues 
- [x] #2985 
- [x] https://github.com/janhq/jan/issues/3939
- [x] #1654
- [x] Different distributions for Jan Stable, Jan Beta and Jan Nightly
- [x] #4175

cc @dan-homebrew

**Comment by 0xSage** [comment]
More or less bottomed out. Closing this disc in favor of issues that track this

**Comment by dan-homebrew** [comment]
Imho, Mac uninstall = better documentation
