### ISSUE TITLE
bug: Dropping GGUF metadata when creating `model.yaml` for Model Downloaded via URL

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3558]
**Describe the bug**
When downloading the HF GGUF model via URL import from the model hub, the model is using default settings instead of the correct settings. The fixed context length is set to 2048, the prompt template is incorrect, and there is an issue with the stop word. However, importing GGUF directly seems to resolve these issues.

**Steps to reproduce**
1. Download the HF GGUF model from the model hub using URL import.
2. Check the settings for context length, prompt template, and stop word.
3. Compare the settings with the correct settings for the GGUF model.

**Expected behavior**
The HF GGUF model downloaded via URL import should have the correct settings for context length, prompt template, and stop word, matching the settings when GGUF is imported directly.

**Additional context**
The issue seems to be specific to downloading the HF GGUF model via URL import from the model hub. Importing GGUF directly does not exhibit the same issue with default settings.

Comparing model.json, the GGUF direct import in on the right 
![image](https://github.com/user-attachments/assets/1a5d44a2-98ef-496c-9c00-4c63100e2b9a)

**Comment by 0xSage** [comment]
@Van-QA what do you mean by "correct settings" 

There are a few settings: 
In order of increasing priority

1. Default for Jan application (determined by us as a fall back)
2. Settings from GGUF binary metadata (determined by og model author)
3. Settings we manually set in model.yamls (which should override the above)

**Comment by Van-QA** [comment]
hi @0xSage, c‌urrently, via impor‌ting from HF URL, ‌Jan is only ‌applying #1 (default settings) w‌ithout considering #2 (author settings)

**Comment by imtuyethan** [comment]
Related:
https://discord.com/channels/1107178041848909847/1285644275119423538
https://discord.com/channels/1107178041848909847/1286662241671970826

**Comment by imtuyethan** [comment]
LGTM 

![Screenshot 2024-10-01 at 8 02 42 PM](https://github.com/user-attachments/assets/d346d802-3cbe-4e7a-8076-311b2eb22f8d)
