### ISSUE TITLE
feat: Local API server - Should allow view / copy model id in model dropdown list

### ISSUE THREAD

**Issue by Van-QA** [janhq/jan#3559]
Description:
The current model ID is not visible in the local API server, making it challenging for users to efficiently create API requests. 

Proposed Solution:
Implement a way to view / copy model ID on the API server page, making it easier for users to reference and incorporate into their requests.
- Should cover for when the local API server are running / not running 
Benefits:
Improved user experience: A concise model ID display will make it easier for users to quickly and accurately build their requests, enhancing overall productivity.
![image](https://github.com/user-attachments/assets/2bc4c6ad-3d3f-4479-9388-c77c69007513)

**Comment by 0xSage** [comment]
@imtuyethan do we have a ticket/epic tracking the API Server UI revamp?

I think there are a lot of small nits like this one that need to be incorporated. This one can be merged into it.

**Comment by 0xSage** [comment]
Wont do, they should use playground for this, which already creates the full request objs
