### ISSUE TITLE
feat: Provider Extension - DeepSeek

### ISSUE THREAD

**Issue by zxnie** [janhq/jan#3583]
### #

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

Requesting support for DeepSeek's API, it's really an underrated model, surprise me everyday.
It has a chat model and a code model.

### Describe the solution

API doc: https://platform.deepseek.com/api-docs/api/deepseek-api
Chat completion API: https://platform.deepseek.com/api-docs/api/create-chat-completion

### Teachability, documentation, adoption, migration strategy

Add a new entry for supported platforms.

### What is the motivation / use case for changing the behavior?

Same as main description. The DeepSeek chat web does not keep conversations, there's only one conversation for each models chat and code, the user can choose to keep history or clear the history and that's it. Using it with Jan can help to give a unified AI experience.

**Comment by dan-homebrew** [comment]
Closed in favor of https://github.com/janhq/jan/issues/3786
