### ISSUE TITLE
feat: Support for Reflection-Llama-3.1-70B

### ISSUE THREAD

**Issue by waldobeest** [janhq/jan#3586]
### #

- [X] I have searched the existing issues

### Background

There is no Reflection model in jan. This is a high end model, but will prove to be a ground breaking model in open source. 

### Feature request

Add support for auto downloading and running:
mattshumer/Reflection-Llama-3.1-70B
https://huggingface.co/mattshumer/Reflection-Llama-3.1-70B

**Comment by dan-homebrew** [comment]
This aged poorly 😿

**Comment by dan-homebrew** [comment]
Closing as Reflection is really a Remote API
