### ISSUE TITLE
feat: keyboard navigation

### ISSUE THREAD

**Issue by DenisGorbachev** [janhq/jan#3587]
### #

- [X] I have searched the existing issues

### Background

I'd like to execute actions using keyboard.

### Feature request

Would you accept a pull request adding keyboard shortcuts to the following actions:

* Go to next/previous thread
* Go to next/previous message in the current thread
* Edit current message (if it's a user message)
* Regenerate current message (if it's an assistant message)
* Copy current message
* Delete current message

?

**Comment by imtuyethan** [comment]
Closed as a sub-task of https://github.com/janhq/jan/issues/4255
