### ISSUE TITLE
feat: Custom icon of application 

### ISSUE THREAD

**Issue by toropanov** [janhq/jan#3598]
### #

- [X] I have searched the existing issues

### Background

Perhaps I'm the only one, but I find that the current application icon doesn't quite align with the design standards of macOS. Could you please add the option to change the icon to custom ones or provide different variations?

### Feature request

 Add the option to change the icon to custom ones or provide different variations

**Comment by 0xSage** [comment]
@toropanov Do you mean this icon: 
<img width="378" alt="image" src="https://github.com/user-attachments/assets/22dc70e6-55c1-4533-baa0-241c6d8ab1ae">

or the assistant icon?

1. Assistant icon is an open issue: #2894 
2. App icon is likely not changing for the time being  - apologies

**Comment by kra-mo** [comment]
I understand not wanting to change the logo, but at least putting the app icon it on a background to make it adhere to macOS guidelines would make sense, wouldn't it?

Something like this:

![Jan](https://github.com/user-attachments/assets/92f81796-55ea-41fd-94e7-4b97fbc6c86d)
