### ISSUE TITLE
milestone: v0.5.4 release with bug fixes

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3599]
## Release Date
Sep 16, 2024

## Scope
https://github.com/janhq/jan/milestone/66

This update focuses on stability improvements and bug fixes to enhance your experience with Jan. Here's what's new:

### Enhancement
- **Downloaded Models directly from Threads**: You can download model directly from model selector in Threads.
-  **Jan's New Starter Screen**: We've implemented a new starter screen to improve the onboarding experience for new users.

### Bug Fixes
- Addressed slower inference on CPU in Jan 0.5.3.
- Solved the "model can't start / The specified module could not be found" error.
- Resolved Phi-3 models failing to start with outdated versions.
- Fixed inconsistent model performance warnings between Model Hub and Thread view.
- Corrected persistence issues with new threads' instruction settings when switching to old threads.
- Fixed empty string issues on the input slider right panel.
- Other small bug fixes...

**Comment by 0xSage** [comment]
@louis-jan are the issues linked above correct? Are we missing anything quite critical to make it into this milestone

**Comment by imtuyethan** [comment]
On my end: 
- We should remove Phi-3 model group: https://github.com/janhq/jan/issues/3608
- https://github.com/janhq/jan/issues/3606 (Will be fixed on the next nightly version)

**Comment by 0xSage** [comment]
I suggest also searching for labels: 
1. p0
2. [p1 & bug](https://github.com/janhq/jan/issues?q=is%3Aissue+is%3Aopen+label%3A%22P1%3A+important%22+label%3A%22type%3A+bug%22)
