### ISSUE TITLE
bug: Model fails to start and shows incorrect status on Ubuntu

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3625]
### Jan version

v0.5.3-625

### Describe the Bug
- The first message sent to the model result in no response or action 
- Upon sending a second message, the status incorrectly showed `Stopping model...` instead of `Starting model...`

![scsc](https://github.com/user-attachments/assets/60b52345-631d-4569-9295-6e0cbe1568cf)

App log:
![Screenshot 2024-09-10 at 10 05 43 PM](https://github.com/user-attachments/assets/ba812dcd-f0af-4bec-b397-0bbb49edcab1)

### What is your OS?
121 (test-ubuntu-app-cpu-1)
OS: Ubuntu 22.04.5 LTS (Jammy Jellyfish)
CPU: 2x Intel(R) Xeon(R) Silver 4214 processors
RAM: 16GiB System Memory
Storage: 268GB QEMU HARDDISK

**Comment by dan-homebrew** [comment]
Tagging to Sprint 20 and v0.5.4

**Comment by imtuyethan** [comment]
@louis-jan This bug happened when i tested on VM:

121 (test-ubuntu-app-cpu-1)
OS: Ubuntu 22.04.5 LTS (Jammy Jellyfish)
CPU: 2x Intel(R) Xeon(R) Silver 4214 processors
RAM: 16GiB System Memory
Storage: 268GB QEMU HARDDISK

**Comment by imtuyethan** [comment]
This ticket cannot be reproduced for now because the machine was crash

**Comment by louis-jan** [comment]
No disk space left, the extensions could not be installed.

![Image](https://github.com/user-attachments/assets/819795c5-cef6-4b9b-b496-b88634e80f7b)

**Comment by louis-jan** [comment]
And yes, there is a Docker process running on port 3928.
![Image](https://github.com/user-attachments/assets/5df322f5-824c-4fa5-b33c-3e56a8e849c6)

**Comment by louis-jan** [comment]
Someone is running a Jan server in the background, which is causing a side effect and unexpected behavior.

This package is deprecated btw.

<img width="378" alt="Screenshot 2024-09-16 at 14 00 25" src="https://github.com/user-attachments/assets/e7da4030-0eac-46e0-8abf-920d7e9ab329">
