### ISSUE TITLE
bug: Can't really see Jan on Windows

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3628]
### Jan version

v0.5.3-628

### Describe the Bug

Can't really see Jan on Window because it has no shadow or border

![Screenshot 2024-09-11 at 12 17 53 PM](https://github.com/user-attachments/assets/2b91ed99-a2b2-45ad-8875-7d35a4d5eec3)
![Screenshot 2024-09-11 at 12 17 58 PM](https://github.com/user-attachments/assets/6e343a1d-3ee6-426e-9786-ec5e9b45ff90)

### What is your OS?
- OS: Windows 11 Pro (Version 23H2, build 22631.4037)
- CPU: AMD Ryzen Threadripper PRO 5955WX (16 cores)
- RAM: 32 GB
- GPU: NVIDIA GeForce RTX 3090
- Storage: 599 GB local disk (C:)

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by urmauur** [comment]
@imtuyethan related my comment on https://github.com/janhq/jan/issues/3093#issuecomment-2345461949

**Comment by imtuyethan** [comment]
Closed as it is our VM issue

**Comment by dan-homebrew** [comment]
I can verify that Border and Shadows show up in 0.5.3, it did not in 0.5.2
![image](https://github.com/user-attachments/assets/70e155ae-36d0-425a-bf59-9c00660efcbf)
