### ISSUE TITLE
epic: Jan supports TensorRT-LLM Models

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3637]
## Goal 

- Jan supports TensorRT-LLM models

## Prereqs

- https://github.com/janhq/cortex.cpp/issues/1152
- janhq/jan-internal#5 (tag-based TensorRT-LLM models)

## Tasklist

- TensorRT-LLM Settings page
- Hub has models with TensorRT-LLM tags (compiled, etc)

**Comment by gabrielle-ong** [comment]
Closing all open TensorRT-LLM stories, the upstream team is not focusing on tensorrt-llm on windows
Parent issue here: https://github.com/janhq/cortex.cpp/issues/1742
