### ISSUE TITLE
feat: users can choose which model(s) to chat with

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#364]
**Problem**
Thanks to @louis-jan 's PR: https://github.com/janhq/jan/pull/361

Users can chat with multiple models (gpt via API + a locally running model)

We should let users choose which model(s) they are chatting with

**Success Criteria**
- Users can choose a model to chat with
- Users can select multiple models to chat with (local + api), or even (local + local if it fits on ram)

See designs:
![image](https://github.com/janhq/jan/assets/69952136/8e6398c9-110c-49c7-b58e-564f037b4347)

**Additional context**

**Comment by 0xSage** [comment]
@louis-jan who is best to pick up this issue later?

**Comment by louis-jan** [comment]
> @louis-jan who is best to pick up this issue later? Can you help assign. I noticed you more or less have the core logic implemented, i.e. where you had 2 models simultaneously respond to 1 user query

@namchuai can take ownership of this (assigned), and I will support the ability to enable/disable providers

**Comment by louis-jan** [comment]
this enhancement will also address #386

**Comment by 0xSage** [comment]
Closing this as our UI is undergoing significant change. We can reopen in the future.
