### ISSUE TITLE
bug: Divider line disappears when switching to Threads tab

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3641]
### Jan version

0.5.3-628

### Describe the Bug

When switching to the Threads tab on macOS, the divider line between the thread list and the main chat area disappears.

### Steps to Reproduce

1. Open Jan on macOS
2. Switch to the Threads tab
3. Observe the UI

### Screenshots / Logs

https://github.com/user-attachments/assets/eb41817b-4e20-4c46-b8a2-68b885959415

Operating System: MacOS Ventura 13.3.1
Processor: Apple Intel
RAM: 8GB

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by urmauur** [comment]
related to #3642

**Comment by imtuyethan** [comment]
No longer an issue on my end
