### ISSUE TITLE
bug: Input text overlaps model settings

### ISSUE THREAD

**Issue by phill52** [janhq/jan#3647]
### Jan version

Jan v0.5.3

### Describe the Bug

When inputting large bodies of text, the text overlaps with the settings buttons, obstructing it and making it harder to click. 

### Steps to Reproduce

1. Open a new chat
2. Ensure the model settings are enabled in the input box
3. Put a large enough body of text that the input box stops scaling
4. Scroll up and down

### Screenshots / Logs

<img width="1260" alt="SCR-20240912-pvot-2" src="https://github.com/user-attachments/assets/7d78d19b-9d25-42a4-885b-d7f5d8527c78">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Thanks a bunch for reporting this @phill52.
This bug can be reproduced on my end:
https://github.com/user-attachments/assets/d117f569-7886-475c-80a8-cb9d860261ef

We will fix this in the next release.
