### ISSUE TITLE
idea: add support for OpenAI o1-preview and o1-mini

### ISSUE THREAD

**Issue by fulvio-m** [janhq/jan#3652]
### Problem Statement

OpenAI has recently released new high-reasoning models called 'o1-preview' and 'o1-mini' that are not available in Jan.

### Feature Idea

OpenAI has recently released new high-reasoning models called 'o1-preview' and 'o1-mini'.
It would be beneficial to have these models available in the Jan app.

These new models could potentially enhance the app's capabilities for tasks requiring advanced reasoning and problem-solving.

Here's the blog post about the announcement: https://openai.com/index/introducing-openai-o1-preview/

**Comment by RONNCC** [comment]
#3659
