### ISSUE TITLE
chore: Fix Jan's red deployments

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3653]
## Goal 

- We should not have a red Deployment
- We will be very strict about broken/red builds in the future

## Resources

![Image](https://github.com/user-attachments/assets/d7a38f3b-77b5-4bb5-ad68-68824e45b8a2)

**Comment by hiento09** [comment]
Resolved
![image](https://github.com/user-attachments/assets/d3f3aa16-0052-402d-992b-c484799a0891)
