### ISSUE TITLE
idea: Badges to show what a model is capable of in models list

### ISSUE THREAD

**Issue by erayerdin** [janhq/jan#3656]
### Problem Statement

![image](https://github.com/user-attachments/assets/8b644354-5b49-4221-bb00-8f8eb652f984)

This list shows model's size, whether it can run on the local machine and the button to download.

### Feature Idea

Would be extra better if it showed what the model is capable of. For example badges like [text-only] or [multi-modal] etc.

**Comment by imtuyethan** [comment]
A part of https://github.com/janhq/jan/issues/3461

**Comment by imtuyethan** [comment]
- Close this & move it to https://github.com/janhq/jan/issues/3910 as a sub-task
- Eventually we should show models with multimodal capabilities badges like `vision`, `speech`, see updated design here: https://github.com/janhq/jan/issues/4170
