### ISSUE TITLE
bug: mac everytime i open the jan.app it just keeps jumping for few minutes and then opens

### ISSUE THREAD

**Issue by khanakia** [janhq/jan#3657]
### Jan version

v0.5.3

### Describe the Bug

Every time I close and reopen the app it takes around 1-2 minutes to open

It started happening in recent updates in the older version it was fine

![Screenshot 2024-09-13 at 6 51 09 PM](https://github.com/user-attachments/assets/8c16a5d4-3f82-452f-9f1d-67becaed1075)

### Steps to Reproduce

Just launch the app in Mac OSX Arm

### Screenshots / Logs

https://www.youtube.com/watch?v=7lRYIk6vDcY

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by khanakia** [comment]
It seems like it's trying to update itself on every load

**Comment by imtuyethan** [comment]
Thanks for reporting this @khanakia 
@urmauur Will take a look & improve the current UX, possibly adjusting the window electron to load after the dom content is ready

**Comment by khanakia** [comment]
No, the problem is not to load the Electron window after the dom content is ready.

Every time I open the jan.app, the icon jumps around 1-2 minutes and then it's opened.

It was working fine in the older versions.

**Comment by dan-homebrew** [comment]
> No, the problem is not to load the Electron window after the dom content is ready.
> 
> Every time I open the jan.app, the icon jumps around 1-2 minutes and then it's opened.
> 
> It was working fine in the older versions.

Yeah, I don't think this is a DOM issue. Let's assign it to @louis-jan to take a deeper dive. Do you mind sharing your logs (or emailing them to hello@jan.ai?)

https://jan.ai/docs/data-folder#logs

**Comment by imtuyethan** [comment]
@khanakia It seems like you have downloaded the wrong version for your Mac. If you're on Mac Intel, please choose Intel version.
Download the right version here: https://jan.ai/download

**Comment by khanakia** [comment]
> @khanakia It seems like you have downloaded the wrong version for your Mac. If you're on Mac Intel, please choose Intel version. Download the right version here: https://jan.ai/download

No I am using ARM and I just reinstalled it again to confirm same issue.

**Comment by khanakia** [comment]
> hello@jan.ai

I just emailed please check I mentioned the GitHub issue in subject

**Comment by dan-homebrew** [comment]
@louis-jan @imtuyethan: I've forwarded the email to you guys, let's take a look at this in Sprint 21

**Comment by 0xSage** [comment]
Any ideas @louis-jan ?

**Comment by louis-jan** [comment]
> Any ideas [@louis-jan](https://github.com/louis-jan) ? P1 issue if you are able to repro 🙏

I was unable to reproduce it. @khanakia, that would be great to have your help on trying to start a model and sharing the log again. I would like to see the process log after that (there will be more information attached in the log then).

I will be testing on an Intel machine tomorrow as well, I might be able to reproduce then.

**Comment by khanakia** [comment]
I already sent the log to email `hello@jan.ai` on Sep 18, 2024.

 However, the app seems to be working fine now. It's better than before, but it still takes around 5-7 seconds now.
 
 maybe I am ok with this now

**Comment by louis-jan** [comment]
Oh oops, thanks @khanakia. I suspect the OS was attempting to allocate some resources (page in/page out), but I will try simulating a couple of scenarios.

**Comment by imtuyethan** [comment]
@TC117 Please help me reproduce.

**Comment by khanakia** [comment]
@imtuyethan the issue doesn't seem to exist anymore. the app is working fine now

**Comment by imtuyethan** [comment]
Thanks @khanakia!
