### ISSUE TITLE
bug: API responds with "Request body is too large"

### ISSUE THREAD

**Issue by manikandanma17** [janhq/jan#3673]
### Jan version

0.5.3

### Describe the Bug

I'm trying to integrate OpenAI LLMs like, gpt-4-turbo, gpt-4o...etc to integrate with LaVague-QA framework for Test Automation. While LaVague is sending request to the LLM running in Jan.AI is responding with "Request body is too large" error.

### Steps to Reproduce

1.Download the LLM gpt-4-turbo OR gpt-4o using Jan.AI interface
2.Make an API call to LLM (gpt-4-turbo OR gpt-4o) 
3.Observe the response returned "Request body is too large"
Note: Attaching the API request body.

### Screenshots / Logs

[request_content.txt](https://github.com/user-attachments/files/17013804/request_content.txt)

<img width="1504" alt="Screenshot 2024-09-16 at 6 52 04 PM" src="https://github.com/user-attachments/assets/982d626a-1a36-4385-a2d8-0c4746f96aa9">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
@manikandanma17 if possible, can you let me know what kind of prompt you sent?
High chances are the prompts or input texts being sent to the model were very large, it might exceed the API's size limits.

Here's an example of a long input sent to GPT & it cannot respond:
![Screenshot 2024-09-18 at 7 35 04 PM](https://github.com/user-attachments/assets/7f3f908d-89bb-4b5f-815c-fb60f00cb0c4)

**Comment by manikandanma17** [comment]
@imtuyethan Kindly find the prompt attached, this is what being sent by us.  
[request_content.txt](https://github.com/user-attachments/files/17045237/request_content.txt)

**Comment by imtuyethan** [comment]
@louis-jan seems like our API server is limiting something?

**Comment by imtuyethan** [comment]
<img width="452" alt="Screenshot 2024-09-23 at 2 40 11 PM" src="https://github.com/user-attachments/assets/e8d7d6ef-23bf-4395-afd0-64448180efa7">

Yeah i was trying to reproduce with Phi-3 mini & got the same results, thanks for the clarification.

**Comment by louis-jan** [comment]
This build addresses the issue
https://github.com/janhq/jan/actions/runs/11009473024

**Comment by imtuyethan** [comment]
Ran into a different error when testing this, will KIV for now 

![Screenshot 2024-10-01 at 9 57 32 PM](https://github.com/user-attachments/assets/5c3a0816-709f-4e8b-8e88-f89be1d06e10)

**Comment by imtuyethan** [comment]
I tested again on my Mac using the same curl:
Seems like your image is too big @manikandanma17.
We have improved the error handling instead so it's clearer. 

![Screenshot 2024-10-02 at 12 41 29 PM](https://github.com/user-attachments/assets/9e4ac46b-3a89-444e-90f9-b68cd4c20da5)
