### ISSUE TITLE
idea: Jan API documentation is missing

### ISSUE THREAD

**Issue by Peepersoak** [janhq/jan#3675]
### Problem Statement

I'm trying to figure out if it's possible to connect to a jan local server, then while searching I found this sample code that let's you connect to jan using api, image below, not sure if it's working tho I just assume it is. But this one is using the Mistral model which is a remote api, so I got curious if it's possible to do this but using a non-remote model, but for some reason I can't find the documentation for this

![image](https://github.com/user-attachments/assets/4638805f-8906-4358-a81e-f7db1706af6a)

### Feature Idea

Add a documentation for connecting to a local jan server using api only so that we can connect to it programmatically, like creating new threads with it's own settings and instructions, connecting to existing threads and continuing the chats

**Comment by 0xSage** [comment]
You can see documentation after starting server in teh ui: 

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/c4f67454-ab1a-4f34-855b-390dabe21ce3">

Here: http://localhost:1337/static/index.html
