### ISSUE TITLE
bug: Debian install breaks due to 'error creating hard link: Invalid cross-device link'

### ISSUE THREAD

**Issue by josepgl** [janhq/jan#3692]
### Jan version

0.5.4

### Describe the Bug

Hard links break install when `/opt/` is on a different partition.

### Steps to Reproduce

1. Have more than one partition. (In my case I have partitions for `/` and `/home`.)
2. Have `/opt` and `/usr` in different partitions. (In my case I use a symbolic link `/opt` -> `/home/opt`)
3. Attempt to install jan with `sudo dpkg -i jan-linux-amd64-0.5.4.deb`.

### Screenshots / Logs

$ sudo dpkg -i jan-linux-amd64-0.5.4.deb 
(Reading database ... 421073 files and directories currently installed.)
Preparing to unpack jan-linux-amd64-0.5.4.deb ...
Unpacking jan (0.5.4) ...
dpkg: error processing archive jan-linux-amd64-0.5.4.deb (--install):
 error creating hard link './opt/Jan/resources/app.asar.unpacked/icons/512x512.png': Invalid cross-device link
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for mailcap (3.70+nmu1) ...
Errors were encountered while processing:
 jan-linux-amd64-0.5.4.deb

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
@josepgl Thanks for reporting, can you give more information on how to reproduce this bug?

**Comment by josepgl** [comment]
@imtuyethan I have included the steps to reproduce in the description.

For more information, this issue is with two files:

- opt/Jan/resources/app.asar.unpacked/icons/512x512.png
- opt/Jan/resources/app.asar.unpacked/icons/icon-tray@2x.png

I would suggest to use symbolic links if you are trying to avoid having them duplicated.

Let me know if you need more info.

**Comment by imtuyethan** [comment]
Thanks for reporting this issue @josepgl.

Jan is an Electron-based application. You've identified a known problem that affects not just Jan, but many Electron-based applications packaged as .deb files, particularly when installed on systems where /opt is on a separate partition. The packaging process creates hard links, which fail when crossing device boundaries (i.e., different partitions or drives).

My proposed workaround for this is: Use the Appimage (portable build) instead. 

The long-term solution would involve working with the electron-builder community to address the issue at its source, which could take months, unfortunately.

Similar reported issues:
https://github.com/electron-userland/electron-builder/issues/5721
https://github.com/LN-Zap/zap-desktop/issues/2089
https://github.com/beekeeper-studio/beekeeper-studio/issues/593

**Comment by josepgl** [comment]
@imtuyethan Nice finding.

I didn't expect it to be an issue with electron since I have installed other electron based applications and this is the first time I find this issue. Hopefully they fix it eventually.

Since I prefer to use the deb package I just chose to repack it with my fix, and now I'm enjoying Jan.

Thanks for this great application.

**Comment by boscopakho** [comment]
export USE_HARD_LINKS=false

it's helpful for me
