### ISSUE TITLE
bug: A broken thread.json could break the entire thread list

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#3693]
### Jan version

0.5.4

### Describe the Bug

When the thread.json file is corrupted or contains invalid JSON, it causes the entire thread list to become inaccessible (empty list). This issue is critical as it disrupts the user experience by preventing access to all threads.

Please refer to the discussion for more context:
https://discord.com/channels/1107178041848909847/1285798898161418260

### Expected Behavior
The application should handle the corrupted thread.json gracefully. It should either:

1. Skip the corrupted entries and continue to load the rest of the threads.
2. Display an error message indicating the issue with the specific file, without crashing the entire thread list.

### Actual Behavior
The application fails to load any threads, displaying an error or crashing due to the corrupted thread.json.

### Possible Solution
Implement error handling for JSON parsing in the thread loading functionality. Ensure that:

The application can detect and skip over corrupted JSON entries.
A user-friendly error message is displayed, indicating the problem with the thread.json file.

### Steps to Reproduce

1. Create a thread
2. Manually edit the JSON, remove any comma
3. Save the corrupted file.
4. Attempt to load the thread list in the application (by pressing Ctrl + Shift + R)

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
Tested on my mac, the error handling is so much better now.
When i tried to edit the threads json file, it changed the entire JSON file to `red` as error warning.
When i got back to threads & hit `Ctrl + Shift + R`, the previous threads that i edited the json file is gone.

![Screenshot 2024-10-01 at 9 39 14 PM](https://github.com/user-attachments/assets/95946d69-84fe-4fea-8608-7740d1a036a4)
