### ISSUE TITLE
bug: Can't run model `Deepseek Coder 33B Instruct` - Check out what's wrong with VM 114

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3703]
### Jan version

0.5.4-641

### Describe the Bug

- I cannot run `Deepseek Coder 33B Instruct` (~18GB), even when turned on GPU acceleration or not.

https://github.com/user-attachments/assets/f8808b78-f416-4314-837c-f7e76f4d8eaa

Here's my app logs: 

![Screenshot 2024-09-19 at 4 29 43 PM](https://github.com/user-attachments/assets/f9f1745e-0913-4064-8c2b-679a6c18b039)

### Steps to Reproduce
1. Download `Deepseek Coder 33B Instruct`
2. Try to use it in threads

>   114 (windows-dev-tensorRT-LLM)
OS: Windows 11 Pro (Version 23H2, build 22631.4037)
CPU: AMD Ryzen Threadripper PRO 5955WX (16 cores)
RAM: 32 GB
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
Storage: 599 GB local disk (C:)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### Related Issue
https://github.com/janhq/jan/issues/3662

**Comment by louis-jan** [comment]
Same issue when running with the latest version of llama.cpp. Switching to a another quantization repository.

![Image](https://github.com/user-attachments/assets/fc823ff2-b792-49aa-9f3e-92fdcea456f7)

**Comment by imtuyethan** [comment]
## Tested on
>   114 (windows-dev-tensorRT-LLM)
OS: Windows 11 Pro (Version 23H2, build 22631.4037)
CPU: AMD Ryzen Threadripper PRO 5955WX (16 cores)
RAM: 32 GB
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
Storage: 599 GB local disk (C:)

## Result
I still cannot run this model


https://github.com/user-attachments/assets/dafaceaa-3ac5-4d04-bcea-2970cb7260c8

**Comment by louis-jan** [comment]
Oh weird, I can run on a single RTX 3060. Let's back to it with the log file later. 
![Image](https://github.com/user-attachments/assets/667ea8b7-7c05-4422-b610-3c5fc1aee037)

**Comment by imtuyethan** [comment]
Need @hiento09 to figure out what is wrong with VM 114:

![Uploading Screenshot 2024-10-02 at 12.46.09 PM.png…]()

**Comment by imtuyethan** [comment]
Closing as model was corrupted
