### ISSUE TITLE
feat: Roll out `Save instruction for new threads` as a stable feature

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3704]
### Problem Statement

Currently `Save instruction for new threads` is under experimental mode:
<img width="540" alt="Screenshot 2024-09-19 at 6 45 06 PM" src="https://github.com/user-attachments/assets/a910219f-ef00-436f-b693-be9ba576dc9d">

### Feature Idea

I think this feature is small & stable; we should roll it out to a stable release.

**Comment by 0xSage** [comment]
@imtuyethan possible to thoroughly QA this once it's in nightly? 🙏

**Comment by imtuyethan** [comment]
Tested on my Mac, works wonder.
