### ISSUE TITLE
idea: Improve code block UX in streaming responses

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3713]
### Problem Statement

https://discord.com/channels/1107178041848909847/1286613318659997697
Currently, users face several issues when trying to copy code blocks during streaming responses:
- Markdown formatting problems, especially with lists
- Can't copy code while the response is still streaming
- Copy icon is too small and hard to click

### Feature Idea

- [x] Investigate and fix markdown formatting issues
- [x] Enable copying of code blocks mid-stream, similar to ChatGPT's functionality
- [x] Increase the size of the copy icon to improve clickability
- [x] Implement a mechanism to properly register click events during streaming updates?
- [x] https://github.com/janhq/jan/issues/3990

### Design
Code block design 

https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8910-70486&t=lR7dmL29vsk85Zf5-4

<img width="882" alt="Screenshot 2024-11-04 at 4 32 54 PM" src="https://github.com/user-attachments/assets/18358c2a-6008-4e39-83af-71e9429ce89b">

**Comment by imtuyethan** [comment]
<img width="524" alt="Screenshot 2024-09-23 at 11 16 37 AM" src="https://github.com/user-attachments/assets/19397ea8-9a9f-4e26-b4bc-b776343c2987">

**Comment by imtuyethan** [comment]
<img width="429" alt="Screenshot 2024-11-01 at 4 52 40 PM" src="https://github.com/user-attachments/assets/15aa8c4f-2ca8-41a6-91a5-df1c92e59aaf">

**Comment by imtuyethan** [comment]
I still can't copy code while the response is still streaming:

https://github.com/user-attachments/assets/342e5acc-510f-4335-a3c5-ad83bf762f94

**Comment by urmauur** [comment]
@imtuyethan it's should fix, on this PR https://github.com/janhq/jan/pull/4061 help me test again
