### ISSUE TITLE
idea: Add Claude Prompt Caching Support to Jan

### ISSUE THREAD

**Issue by kvn8888** [janhq/jan#3715]
### Problem Statement

Using an API to access Claude without requiring a $20/month Claude Pro subscription saves users money in the long run. However, this benefit diminishes whenever users enter long context multi-turn conversations with Claude, especially with file uploads

### Feature Idea

By integrating Anthropic's newer prompt caching feature, the response latency and cost for users could be dramatically reduced. Users may engage with longer multi turn conversations without starting a new thread and losing context. Cached prompts can be an optional feature that costs 90% less compared to uncached prompts per API call

**Comment by Boscop** [comment]
Yes 100%, @imtuyethan please prioritize this 🙂

Btw, related (partial dup): https://github.com/janhq/jan/issues/3320

**Comment by imtuyethan** [comment]
Awesome @kvn8888 We will try to prioritize it!

**Comment by imtuyethan** [comment]
@0xSage Please consider closing this as a dup of #3320. Then we will follow up on #3320.

**Comment by dan-homebrew** [comment]
I am merging this into #3786, which will be part of our bigger refactor of Remote APIs into Cortex backend
