### ISSUE TITLE
bug: LLM model fails to downlad, can still "be used"

### ISSUE THREAD

**Issue by Jazza-231** [janhq/jan#3727]
### Jan version

0.5.4

### Describe the Bug

Models occasionally do not download correctly, but still report a "use" button, indicating that it was downloaded successfully, but the models can not be ran.

### Steps to Reproduce

1. Open Jan
2. Attempt to download a model from the Hub
3. Use an app blocking software like glasswire to block the access to jan, simulating a loss of internet connection
4. Model will report as a failed or cancelled download in the top right
5. Model will show as downloaded and have a "use" button
6. Attempt to run the model, it will fail, sometimes with no error message

### Screenshots / Logs

[app.log](https://github.com/user-attachments/files/17107349/app.log)

https://github.com/user-attachments/assets/b4577616-aa30-43de-960c-792d52fb18d8

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by dan-homebrew** [comment]
@louis-jan I think we should focus on the shift from Jan to cortex.cpp, which will solve this issue. However, tagging this here for you to take a quick look - if there's a quick way to solve it for existing users, I'm open to fixing it in 0.5.5.

**Comment by louis-jan** [comment]
Thanks @dan-homebrew. For now, we'll aim to provide a more gracious error message instead. I'll leave the rest, such as hash checking, downloading, and resuming, to the cortex.cpp shift.

**Comment by imtuyethan** [comment]
Can't reproduce on 0.5.4-650 
LGTM
