### ISSUE TITLE
bug: LaTeX rendering issue 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3740]
### Jan version

0.5.4

### Describe the Bug

https://discord.com/channels/1107178041848909847/1289604811121102868
Jan has issues with properly displaying mathematical content. When inline mathematical statements (enclosed within single $ delimiters) are used, the output duplicates the expression. This affects the readability and accuracy of mathematical content in Jan's responses.

### Steps to Reproduce

1. Open Jan
2. Start a conversation about a math-related topic
3. Ask Jan to provide an explanation that includes LaTeX mathematical notation
4. Observe the response, paying attention to inline math expressions (those enclosed in single $ signs)

### Screenshots / Logs

![dwsx](https://github.com/user-attachments/assets/9a962840-696e-4248-9f42-e224ed5094a7)

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by louis-jan** [comment]
@imtuyethan Please see this https://discord.com/channels/1107178041848909847/1289605380493545642

This is not formatted as Markdown KaTex, but a raw text.

**Comment by 0xSage** [comment]
![Image](https://github.com/user-attachments/assets/e382455e-2099-4296-beae-397798b11b6f)
fixed
