### ISSUE TITLE
bug: Weird bug when stopping the model

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#375]
**Describe the bug**

**To Reproduce**
1. Go to Jan App and Start Model
2. Click on Stop model

**Expected behavior**
Just stop normall

**Screenshots**
![image](https://github.com/janhq/jan/assets/22268502/a0ede791-2936-4bc0-857a-55671f2ee01e)

on MacOS

**Comment by louis-jan** [comment]
@namchuai @hiento09 known issue, GitHub rate limiting. Component did unmount but the process is still functioning. He led to My Models from Explore. 

Poll from npm repo instead of GitHub should help.
