### ISSUE TITLE
feat: Show model ID in Local API Server

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3752]
## Problem Statement
This request was requested a long time ago by a user on Discord. 
It's currently frustrating not to see the model ID when running a local API server. User often has to go to `My Models` page to check out & copy from there; however, it's too cumbersome, & Jan doesn't provide model IDs for cloud models. 

## Feature Idea

Allow user to view & copy model ID directly on the Local API Server page.

Figma link: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=8805-32668&t=JTNzU847ugGdPdo9-4

<img width="695" alt="Screenshot 2024-10-31 at 3 07 59 PM" src="https://github.com/user-attachments/assets/5abcc75e-7e74-4866-bf9c-008e4e725ed2">

**Comment by baraich** [comment]
@imtuyethan, I am working on the issue. In the mean time, you can assign the issue to me. Thanks in advance.

**Comment by baraich** [comment]
@imtuyethan Can you please steps to reproduce the issue. When I am trying the Local API Server, I am able to see `id` property.

![image](https://github.com/user-attachments/assets/667461d0-24f2-4f08-b580-490f9f13ee5d)

**Comment by imtuyethan** [comment]
> [@imtuyethan](https://github.com/imtuyethan), I am working on the issue. In the mean time, you can assign the issue to me. Thanks in advance.

That would be awesome! Thanks a lot! @baraich

**Comment by imtuyethan** [comment]
> [@imtuyethan](https://github.com/imtuyethan), I am working on the issue. In the mean time, you can assign the issue to me. Thanks in advance.

@baraich I've added the design, in case you still want to work on it :')

**Comment by urmauur** [comment]
<img width="512" alt="Screenshot 2024-10-31 at 13 51 39" src="https://github.com/user-attachments/assets/dc5dfcba-5446-4adc-9b2d-62fade2a1b36">
<img width="495" alt="Screenshot 2024-10-31 at 13 51 51" src="https://github.com/user-attachments/assets/ce6abf56-e0ce-4186-b1d5-4a89b8c7dcd8">

there are some discussion
1. Run Jan on a Linux VM, start a server then connect from clients can not copy over from VM to host machine or client machines 
2. Copy element inside a disabled input which is not good UX also

@imtuyethan send back to need design, let me know if design ready

**Comment by imtuyethan** [comment]
@urmauur I have updated the design accordingly

**Comment by imtuyethan** [comment]
@urmauur I have updated the design, this copy tooltip is not necessary anymore, please remove: 

![Screenshot 2024-11-05 at 11 04 08 PM](https://github.com/user-attachments/assets/ed32d111-7420-4411-a359-09c5924927fc)

**Comment by imtuyethan** [comment]
Looks great! @urmauur 1 last nitpick from me, so sorry :"<

Let's make the whole field clickable for copying instead of just the copy icon:

<img width="379" alt="Screenshot 2024-11-06 at 6 15 32 PM" src="https://github.com/user-attachments/assets/f5e0f3cb-0f94-4748-bac6-e904bc9f9968">
