### ISSUE TITLE
bug: Misc chat UI issues

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3759]
### Jan version

0.5.4-652

### Describe the Bug
1. The text should expand til it fills the field 100%
<img width="448" alt="Screenshot_2024-10-02_at_3 55 15_PM" src="https://github.com/user-attachments/assets/0dc7aea5-58db-436d-90a5-499d3a99c20a">

2. Import modal still shows up after i click use model
https://github.com/user-attachments/assets/e601bc78-1b59-48a7-9bfb-c5c13b50f18e

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by 0xSage** [comment]
Let's avoid assigning to eng until we've fully scoped out the issue. 
I'm assigning this issue to me, so I can figure out what exactly needs to be done

**Comment by imtuyethan** [comment]
Sorry @urmauur sorry to keep nitpicking on this, but I still find it a bit odd:

https://github.com/user-attachments/assets/34db7367-9f8a-4dab-875c-a7427dcc8e27

Here’s how I think it could be improved:

	•	The box should dynamically adjust to fit the content.
	•	Set a maximum width for the box. Once the content exceeds the limit, it should be truncated with an ellipsis (“abc…”).

**Comment by imtuyethan** [comment]
This issue will be fixed here: https://github.com/janhq/jan/pull/3802
