### ISSUE TITLE
bug: Unsupported Parameter Errors for model `o1-mini` & `o1-preview` 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3771]
### Jan version

0.5.6

### Describe the Bug

When using model `o1-mini` & `o1-preview`, the system shows that parameters such as stop and temperature are not supported, and the default values seem to be enforced. This has been reported both in Discord and within the Jan UI.

<img width="833" alt="Screenshot 2024-10-06 at 12 35 23 PM" src="https://github.com/user-attachments/assets/538c8bc7-f7a0-4e57-ad6d-20ad4439b1b6">

### Steps to Reproduce

	1.	Select the OpenAI `o1-mini` & `o1-preview` 
	2.	Execute a prompt.

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by 0xSage** [comment]
Related #3505

**Comment by louis-jan** [comment]
Related #3786

**Comment by louis-jan** [comment]
Duplicate #3745 - Closing

**Comment by imtuyethan** [comment]
All GPT models work well except for `o1-mini` & `o1-preview`:

Uploading Screen Recording 2024-11-18 at 5.30.11 PM.mov…

**Comment by louis-jan** [comment]
@imtuyethan Please refer to https://github.com/janhq/jan/issues/3745. Your case is more about the fact that you don’t have access to o1-mini and o1-preview, which is likely at least Tier 3. See more in Developer Console.

**Comment by imtuyethan** [comment]
@louis-jan Got it, i'll close this one as resolved & open a separate ticket for error handling.
