### ISSUE TITLE
idea: In-chat search.

### ISSUE THREAD

**Issue by SimplyProgrammer** [janhq/jan#3772]
### Problem Statement

When I have longer chats, it becomes quite tedious to scroll and navigate around...

### Feature Idea

It would be great to have an in-chat search after pressing Ctrl+F similar to browser-based ChatGPT that would search for a given word in the current chat...
![image](https://github.com/user-attachments/assets/a4adcd64-3cd8-41a4-ada2-ae6e579c0374)

**Comment by imtuyethan** [comment]
Duplicated with https://github.com/janhq/jan/issues/3648
