### ISSUE TITLE
question: Documentation on Server mode functionality

### ISSUE THREAD

**Issue by PeterTucker** [janhq/jan#3776]
### Jan version

v0.5.6

### Describe the Bug

Not sure if this is a bug or feature request. Is there a way to use my home PC running JAN as a OpenAI server and connect remotely to it from my laptop using another JAN instance running on my laptop as a client? I see this under the server section:
![image](https://github.com/user-attachments/assets/32ee0bbc-d2bd-424d-8b4b-1b2bce70922b)

... but how does one link to it from another less powerful machine(laptop) running Jan? How do they generate access tokens? Is this even possible? I don't see any information in the documentation to tell me if JAN has this functionality, but I do see the server section which would infer that it's possible.

... An alternative to this would be the server can show the chat portion of the UI to a browser. Sort of like how like TabbyML's playground works.

### Steps to Reproduce

N/A

### Screenshots / Logs

N/A

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by 0xSage** [comment]
You can follow the steps here: https://jan.ai/docs/remote-models/openai

And run Jan API server on the powerful PC, and then run Jan's UI in the less powerful PC. 

Jan's server endpoint should be openai compatible. Feel free to reopen the issue ro come in or discord for more troubleshooting!
