### ISSUE TITLE
bug: Missing Docker configuration files.

### ISSUE THREAD

**Issue by PeterTucker** [janhq/jan#3778]
### Jan version

v0.5.6

### Describe the Bug

Looks like the Docker version of Jan was removed, however the readme stil talks about how to setup docker. Can we get a reason why the docker version was removed?

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by ksaadDE** [comment]
So is it some unnamed "insecurity" or "Jan Hosted"? 

https://github.com/orgs/janhq/discussions/3863

I'm confused but the communication is odd. Docker is "secure and stable". But if your app is not, its probably not Docker’s fault.

**Comment by PeterTucker** [comment]
I can't close this, but just letting you all know I've moved on from Jan. A JAN developer can close this issue if they want.
