### ISSUE TITLE
idea: let users create many new empty threads

### ISSUE THREAD

**Issue by du82** [janhq/jan#3784]
### Problem Statement

I'm frustrated when the app tells me to reuse threads instead of creating new ones. This is completely arbitrary since its all hosted on my machine, and I want to be able to create them without any limits. Currently the feature looks for "New Thread" anywhere in the title, which is problematic because I name them New Thread1, New Thread2, etc.. so I always have to delete them for no reason.

### Feature Idea

Remove the limit of three empty threads.

**Comment by imtuyethan** [comment]
@du82 Hi there! Can you elaborate on your problem. Jan allows you to create a new thread as soon as your latest new thread has any changes (whether you chat with model or modify the settings), this prevents empty threads piles up (which was an issue raised by other users), and I believe this is way better UX?

In this video, i created new thread, chat with LLMs, then i rename the thread to "New Thread" & i can continue create new thread:

https://github.com/user-attachments/assets/81a31c8e-ec4c-4fe7-be79-ae9388408c9b
