### ISSUE TITLE
chore: move Jan Docs back into Jan Repo

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3787]
## Goal

- I would like Docs to return to being a 1st class citizen of Repo
- Docs are likely to be AI-generated from the codebase
- Engineers using continue.dev can @docs to get context

## Tasklist

- Decide if we are using submodule or shifting entire repo in
- Submodule has pros (e.g. less builds) and cons (e.g. bad UX for newbie engs)

**Comment by hiento09** [comment]
FYI @urmauur , @louis-jan , @imtuyethan

**Comment by hiento09** [comment]
In my opinion, we should merge everything into one repo. Submodules are also a good idea; however, they would still require the dev team to create PRs in two places, which is less convenient.

**Comment by hiento09** [comment]
Added @urmauur here to update all the website links, i.e. when user visits jan.ai/cortex/homebrew, adn clicks the "edit this page"
