### ISSUE TITLE
feat: Settings Page UI Extension 

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#3789]
## Goal: 
- Extensions builders can register a new page in Settings
- Builders can register multimodal sections & fields in each settings, e.g. text, file selector
- Inspo: e.g. https://docs.obsidian.md/Plugins/User+interface/Settings
- Each Extension should register its own page
<img width="707" alt="Screenshot 2024-04-15 at 8 50 37 AM" src="https://github.com/janhq/jan/assets/89722390/e0014f75-d04f-438b-800e-8dc01a30a403">

## Specs
https://www.notion.so/jan-ai/Programmable-Settings-UI-a736082e7105404e8ef99c3049984a50?pvs=4

## Designs
https://www.figma.com/file/DYfpMhf8qiSReKvYooBgDV/Jan-App-(version-2)?type=design&node-id=2426-208178&mode=design
```

**Comment by dan-homebrew** [comment]
I am combining this into #2718
