### ISSUE TITLE
idea: AVX1/AVX2 architecture compatibility and CUDA support

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3794]
### Problem Statement
https://discord.com/channels/1107178041848909847/1292969836539809872

Jan’s current GPU mode includes CUDA support with AVX2 architecture, but some users with AVX1 or other architecture setups are experiencing issues with GPU mode. There’s a need to expand compatibility beyond AVX2, ensuring that CUDA can run smoothly on a wider range of CPU architectures.
- AVX2 support is bundled with CUDA in the current builds.
- Some users with AVX1 architecture or other non-AVX2 systems face issues with running GPU mode, often requiring manual intervention or workarounds.

### Feature Idea
Consider adding additional optimizations and bundling for other architectures, ensuring that CUDA can run on a variety of CPU setups...

**Comment by 0xSage** [comment]
Jan will ship with avx variants. 
Pending cortex refactor

**Comment by imtuyethan** [comment]
> Jan will ship with avx variants. Pending cortex refactor

Should we move this ticket to Cortex repo?

**Comment by dan-homebrew** [comment]
This should be addressed by https://github.com/janhq/cortex.cpp/issues/1416
