### ISSUE TITLE
bug: llama 7B on llama.cpp on Apple Silicon is responding at 4 tokens per minute

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#38]
What's the issue?

Env: Mac M1 Pro arm64

Solution: un-dockerize llama.cpp, so we can use Metal

**Comment by 0xSage** [comment]
drake/petra/dan were also experiencing the same on their respective macs

**Comment by drakehere** [comment]
Screen recording of this issue: https://www.loom.com/share/2bfaa05768834f5dbd45eac571f6bc7a?sid=9a17f120-96be-4ac0-984b-a3401d632785

Macbook with M1 Pro, 16GB Memory
