### ISSUE TITLE
chore: no loading indicator when starting a model from My Model page

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#380]
## Problem
When I start a model from My Models page, the button appearance is not updated (at least grayed out), I thought I misclicked or the function is not working. I will click over and over again.

## Solution
Grayed out the start button should work
Better to have loading indicator

**Comment by 0xSage** [comment]
Expectation: 

- Bottom status bar shows: "starting model" see figma: https://www.figma.com/file/JdK7cNIBeVdYeHxKiYeWtk/JAN---Web?type=design&node-id=3026-6625&mode=design&t=hwKNMP6dfwurmMP2-0
- Button shows some sort of loading indicator to register user intent
