### ISSUE TITLE
idea: [UI enhancement] System monitor should not cover input box

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3812]
## Problem

The System Monitor panel overlaps with the input box, preventing users from entering text or interacting with the input field while monitoring system performance. 

#### Current screen
<img width="1060" alt="Screenshot 2024-10-16 at 12 21 15 AM" src="https://github.com/user-attachments/assets/bd769b76-6062-4f9b-9599-ba049c2dd822">

## Design enhancement

- The user should be able to view the System Monitor and interact with the input box simultaneously without obstruction.
- Adjust the layout to ensure the input box remains accessible when the System Monitor is open.

Figma link: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=3374-136665&t=HuIkDs0IEqCDB7SY-4 

<img width="713" alt="Screenshot 2024-10-28 at 10 23 55 AM" src="https://github.com/user-attachments/assets/2f1f77c6-166b-48e3-9d8c-d20b6ea42cf7">

**Comment by urmauur** [comment]
@imtuyethan might 700 not latest build 699 work on well on my side
 ![Image](https://github.com/user-attachments/assets/71f568bc-5cc9-46a5-93e6-561573edff5e)

**Comment by imtuyethan** [comment]
@urmauur When i click on input box, it should not close the system monitor panel. The point of this feature is to allow users using threads & monitor the performance at the same time. 

 https://github.com/user-attachments/assets/c0216784-11df-4e7b-b86a-b9d89dfbbfa2
