### ISSUE TITLE
idea: [UX enhancement] Improve the animation of response generation 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3820]
### Problem Statement

The current response generation is very laggy & "epileptic":

https://github.com/user-attachments/assets/21be575e-85b5-425d-aab0-eb3503894ab9

Meanwhile, if you take a look at chatGPT desktop app, its generation animation is more calming: 

https://github.com/user-attachments/assets/6c8be9f9-284f-4ade-91a6-fd879fa926b3

### Feature Idea

 Make the animation of response generation more calming.

**Comment by urmauur** [comment]
I’ll close this. I already implemented an approach like this: https://nextjs-omega-five-46.vercel.app/. However, the animation depends on tokens. When the token response is slow, the animation lags and takes a longer duration to complete

cc @imtuyethan @louis-jan
