### ISSUE TITLE
chore: Structure Icebox in Github Projects

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3840]
## Structure

- Important vs. Urgent (Eisenhower Matrix)

## Bugs

- Recommend Urgent/Important bugs

## Features

- Recommend Important/Urgent

**Comment by imtuyethan** [comment]
# Bugs
## Urgent
Directly affect user retention rate: 
- #3771 (affect all OpenAI's users right now)
- #3745 (affect all OpenAI's users right now)
## Important
- Some issues in #3818 that Eng are not committed to deliver in 0.5.7.
- #3774 
- #3811 
- #3679 
- 
---

# Enhancement
Enhancement to the current feature set that addresses user's needs & improve user experience. 

## P0 
The following enhancement can solve several bug reports:
- #3537 
- #3385 
- https://github.com/janhq/jan/issues/3619 (a community-built feature, no one in the team knows what it does).


## P1
- #3320 (considering Anthropic reaches >20M users now, this could increase Jan's retention by allowing Claude users save more money by using Anthropic models in Jan).
- https://github.com/janhq/jan/issues/3519
- #3688 
- #3752 
- https://github.com/janhq/jan/issues/3536



## P2
- #3775 
- #3814 
- #3738 
- #3812 
- #3758 
-
---

# Features
## P0
P0 features are what @dan-homebrew and @0xSage already laid out:
- #3690 
- #3786
- #3735 
- https://github.com/janhq/jan/issues/3550 (To resolve tons of reported bugs & user requests around RAG)
- https://github.com/janhq/jan/issues/3633
- https://github.com/janhq/jan/issues/3461
- #3773 
- https://github.com/janhq/jan/issues/3632 (Better QA process please!)

## P1
Apart from P0 features, here are some features that tons of user are begging to have in Jan: 

- #3503 (Currently we still use Umami to track DAU, but we didn't publicly explain it. Users come to us for privacy solution & they are asking why their data is sending to Umami).
- Multi-modal Support (vision, voice) https://github.com/janhq/jan/issues/3488
- https://github.com/janhq/jan/issues/3529
- https://github.com/janhq/jan/issues/3648

**Comment by dan-homebrew** [comment]
Question: should we have the following Selectors in our Project: 

- Type: Bug, Feature, Enhancement
- Importance: p0, p1, p2
- Urgency: Urgent
