### ISSUE TITLE
bug: Context length value is not updated when model settings changes

### ISSUE THREAD

**Issue by thonore75** [janhq/jan#3842]
### Jan version

0.5.6-663

### Describe the Bug

When changing model from the Model tab of a Thread, the context length value is not correct

### Steps to Reproduce

See video

### Screenshots / Logs

https://github.com/user-attachments/assets/0a8d8008-b005-4f5e-a0e1-0cbd38ca639d

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Can reproduce on my end. 
@louis-jan Can we have a quick fix for 0.5.7?

<img width="1157" alt="Screenshot 2024-10-21 at 6 55 51 PM" src="https://github.com/user-attachments/assets/f10e8fc0-3838-4062-b170-6a8335fcc9d6">

**Comment by imtuyethan** [comment]
Works well in 0.5.6-678
