### ISSUE TITLE
feat: Should be able to stop the inference

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#385]
**Problem**
Sometimes the inference has issue, i want to stop it half way through

**Success Criteria**
Have a stop button like chatGPT

<img width="1491" alt="image" src="https://github.com/janhq/jan/assets/22268502/ff93408e-41c6-4319-a279-a89ad444c77f">

**Comment by 0xSage** [comment]
It seems Nitro already supports this. https://github.com/janhq/jan/issues/141

Hopefully a quick implementation!

**Comment by louis-jan** [comment]
Updated inference module. #677

from UI
```ts
pluginManager.get<InferencePlugin>(PluginType.Inference).stopInference()
```

**Comment by louis-jan** [comment]
Added in this PR:
https://github.com/janhq/jan/pull/717
