### ISSUE TITLE
bug: The multimodal model does not support image file uploads.

### ISSUE THREAD

**Issue by ahs95** [janhq/jan#3855]
### Jan version

v0.5.6

### Describe the Bug

I am experiencing an issue uploading image files to the multimodal model "llava-v1.5-13b-Q2_K.gguf". The model only accepts PDF documents for upload, preventing me from uploading images.
Operating System: Windows 11

### Steps to Reproduce

1. Import [model](https://huggingface.co/PsiPi/liuhaotian_llava-v1.5-13b-GGUF) from Hugging Face to Jan app.
2. Download the quantization (2-bit) model named "llava-v1.5-13b-Q2_K.gguf". 
3. Then start to use the model by clicking the use button. 

### Screenshots / Logs

<img width="574" alt="Screenshot 2024-10-21 204414" src="https://github.com/user-attachments/assets/1e4732f1-ecd6-4659-a3fb-8f661c903254">

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Related to https://github.com/janhq/jan/issues/3849

**Comment by louis-jan** [comment]
Hi @ahs95 Vision model import is not supported yet. It requires two GGUF files to work. I see that you imported just the chat model, but there is still the clip model.

**Comment by louis-menlo** [comment]
Hi @OrinZ, I believe it was mistakenly closed without linking to the new ticket.

Here is the roadmap of this: 
https://github.com/menloresearch/jan/issues/4898

**Comment by louis-menlo** [comment]
This feature is very important, and planned to have proper support in 0.5.19

**Comment by OrinZ** [comment]
Oh, that's great to hear! Thank you for clarifying. Looking forward to it; appreciate everyone's efforts 😄
