### ISSUE TITLE
bug: Incorrect hyperlink for `Martian` under `Settings` > `Model Providers` > `Martian`

### ISSUE THREAD

**Issue by Haleshot** [janhq/jan#3856]
### Jan version

Jan v0.5.6

### Describe the Bug

The hyperlink for Martian under **Settings > Model Providers > Martian** is incorrect. The link currently points to an outdated page and results in a 404 error, leading to user confusion.  

- **Broken link**:  
  [https://docs.withmartian.com/martian-model-router/api-reference/get-chat-completions](https://docs.withmartian.com/martian-model-router/api-reference/get-chat-completions)  
  When clicked, it shows "_Page not found. The page you are looking for doesn't exist._"

### Steps to Reproduce

1. Open the **Jan.ai framework GUI**.  
2. Navigate to **Settings** > **Model Providers** > **Martian**.  
3. In the **Martian** section, under **Chat Completions Endpoint**, click the provided link.  
4. You will be redirected to a 404 error page.

- The Martian section content contains:
  - **API Key**:  
    "The Martian API uses API keys for authentication. Visit your API Keys page to retrieve the API key you'll use in your requests."
  - **Insert API Key**
  - **Chat Completions Endpoint**:  
    "The endpoint to use for chat completions. See the Martian API documentation for more information."

The hyperlink for Martian under **Settings > Model Providers > Martian** is incorrect. The link currently points to an outdated page and results in a 404 error, leading to user confusion.  

- **Broken link**:  
  [https://docs.withmartian.com/martian-model-router/api-reference/get-chat-completions](https://docs.withmartian.com/martian-model-router/api-reference/get-chat-completions)  
  When clicked, it shows "_Page not found. The page you are looking for doesn't exist._"

### **Expected Behavior**  
The link should direct users to the correct Martian API documentation, where they can find details on integrating Martian with their codebase.

The correct link should be:  
[https://docs.withmartian.com/martian-model-router/getting-started/quickstart-integrating-martian-into-your-codebase](https://docs.withmartian.com/martian-model-router/getting-started/quickstart-integrating-martian-into-your-codebase).

This page has integration instructions with different language/platform options such as OpenAI Python, Node, cURL, LangChain Python, and LangChain JS.

### Screenshots / Logs

- Incorrect hyperlink
![image](https://github.com/user-attachments/assets/a7b91e39-92be-41ca-875c-40eaa694e074)

- Possible hyperlink redirection now:
![image](https://github.com/user-attachments/assets/52fceadf-e808-4406-ad9a-f375b7c5274e)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Thanks @Haleshot Such a detailed bug report. 
It is wrong link indeed.

![Screenshot 2024-10-22 at 5 58 12 PM](https://github.com/user-attachments/assets/bba752ac-34ff-4e4c-b933-e45acc340b36)

@urmauur Please help replace this link with this: https://docs.withmartian.com/martian-model-router/getting-started/quickstart-integrating-martian-into-your-codebase

<img width="966" alt="Screenshot 2024-10-22 at 6 00 50 PM" src="https://github.com/user-attachments/assets/4ffae180-23d4-4ff6-818b-353b5459adcd">

**Comment by imtuyethan** [comment]
Fix in 0.5.6-678

**Comment by Haleshot** [comment]
> Fixed in 0.5.6-678

That was fast! Thanks!
