### ISSUE TITLE
idea: Request for more cloud providers (Google AI Studio, Together API, AI Horde)

### ISSUE THREAD

**Issue by Anthonyg5005** [janhq/jan#3859]
### Problem Statement

I don't really need Jan for local stuff as I already use a different inference framework but I like how I can use cloud models with it. There just isn't support for all the different apis I want to mess with.

### Feature Idea

Some I think I'd like to see:
- Google AI studio
- Together API
- AI Horde

There's probably a couple more that would be nice to have.

**Comment by dan-homebrew** [comment]
Closing in favor of #3786
