### ISSUE TITLE
bug: model not stopping when users `stop` the model

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#386]
Can be reproduced easily by following the video

https://github.com/janhq/jan/assets/22268502/5b480d18-a425-4ba6-bda6-e4ffffe96d6d

**Comment by namchuai** [comment]
@tikikun , The model is loaded again, when you click on a conversation.

cc @louis-jan

**Comment by namchuai** [comment]
This has been fixed in #458. Switching between model will now asking confirmation from user, instead of automatically loading those model into Nitro.
