### ISSUE TITLE
bug: Remove `OpenAI GPT 4 with Vision (Preview)` as it is deprecated

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3864]
### Jan version

0.5.6-666

### Describe the Bug
The model is deprecated as stated here: 
https://platform.openai.com/docs/deprecations

Please remove this model from Jan:
<img width="1114" alt="Screenshot 2024-10-22 at 11 58 10 PM" src="https://github.com/user-attachments/assets/3c955727-d21e-449b-b086-56ebc2430327">

**Comment by imtuyethan** [comment]
It does not show on Mac & Linux anymore but it still shows on Window:

> 118 (test-windows-app-1-activated)
> OS: Windows 11 Pro (Version 23H2, build: 22631.4037)
> CPU: Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
> RAM: 16.0 GB

![Screenshot 2024-11-05 at 11 31 17 PM](https://github.com/user-attachments/assets/a12e5018-b49f-45d3-8b1a-e4d7b484af87)

**Comment by urmauur** [comment]
@imtuyethan remove model.json would just work for new installation, existing users will still see, currently no other solution  cc @louis-jan
