### ISSUE TITLE
idea: Ability to rearrange and group chat list

### ISSUE THREAD

**Issue by J-Siu** [janhq/jan#3871]
### Problem Statement

I am testing Jan and creating more and more chat like following🤦‍♂️
![Screenshot 2024-10-23 at 05 15 48](https://github.com/user-attachments/assets/a1b50958-f57c-4a49-920c-5a9aaba86a44)

### Feature Idea

It will be nice if we can rearrange the chat list order, and even group them in tree.

**Comment by imtuyethan** [comment]
related: https://github.com/janhq/jan/issues/3133
