### ISSUE TITLE
bug: AMD RX 7900 XTX Incompatibility Even with Vulkan Mode Enabled

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3874]
### Jan version

0.5.6-675

### Describe the Bug

The AMD RX 7900 XTX graphics card does not seem to be compatible, even when Vulkan mode is enabled. Expected behavior is full compatibility with Vulkan mode, but the software does not run or displays issues that indicate a lack of proper support for this GPU.

### Steps to Reproduce

	1.	Install the AMD RX 7900 XTX in the system.
	2.	Enable Vulkan mode within the software.
	3.	Attempt to run the software or use specific features that require GPU support.
	4.	Observe any errors, crashes, or performance issues.

### Screenshots / Logs

https://discord.com/channels/1107178041848909847/1291349506604138600

### What is your OS?

- [ ] MacOS
- [X] Windows
- [X] Linux

**Comment by dan-homebrew** [comment]
Let's handle this as part of #3913, and we can test it as part of the Engine Management abstraction
