### ISSUE TITLE
idea: Support Multi-part GGUF Models

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3879]
### Problem Statement

- Attempting to load a multi-part GGUF model results in errors.
- Error handling is currently insufficient, providing unclear feedback to the user.

https://github.com/user-attachments/assets/81ea8521-21e6-4343-88ee-a57f62386f06

### Feature Idea

1. Full Model Support: Implement the ability to load and use multi-part GGUF models without errors.
2. Improved Error Handling: If full support is not immediately feasible, enhance error handling to provide clear messages that multi-part models are not supported.

_Instead of fixing the error handling, i think it would be best to support Multi-part GGUF Models._

**Benefits**

- Expands compatibility with a broader range of GGUF models.
- Improves user experience by eliminating confusion and errors related to multi-part models.

**Comment by SugarRayLua** [comment]
@SugarRayLua (aka Myte on discord) discussed with @louis-jan today on discord.

**Comment by imtuyethan** [comment]
Add another user story: <img width="456" alt="Screenshot 2024-11-26 at 10 12 26 AM" src="https://github.com/user-attachments/assets/09f91b0f-c51a-4a4b-8839-3c410215c2d6">

**Comment by imtuyethan** [comment]
Closed as dup: https://github.com/janhq/jan/issues/4254

**Comment by SugarRayLua** [comment]
@imtuyethan, wonderful, thanks, I'll try it out!

**Comment by imtuyethan** [comment]
> @imtuyethan, wonderful, thanks, I'll try it out!

@SugarRayLua I closed as a duplicate ticket, we haven't implemented it, please follow up with this ticket instead: https://github.com/janhq/jan/issues/4254
