### ISSUE TITLE
bug: Handle edge cases around syntax highlighting feature in input box

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3884]
### Jan version

0.5.7

### Describe the Bug
#3739 
The input box with markdown support has intermittent issues where markdown formatting sometimes works as expected and other times it doesn’t. This inconsistency creates confusion for users who rely on markdown for formatting their input.

### Steps to Reproduce

1.  Open Threads
2. Input this in markdown: 
```txs
console.log()
```
3. See that sometimes it works, sometime it doesn't

### Screenshots / Logs

![Screenshot 2024-10-25 at 2 48 41 PM](https://github.com/user-attachments/assets/edb55f51-50a2-41be-b353-65c7a563e97a)
![Screenshot 2024-10-25 at 2 48 29 PM](https://github.com/user-attachments/assets/f17022de-55c2-4cb2-b54a-26ce3b2c4eb2)

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
https://discord.com/channels/1107178041848909847/1149558035971321886/1299607048849195028

![Screenshot 2024-10-27 at 10 46 01 PM](https://github.com/user-attachments/assets/0f298736-68d3-4cd2-81da-6e467b1c2637)

**Comment by imtuyethan** [comment]
@urmauur I tested it again
- This time the default font is our normal font
- However, once i paste a code block > delete it > the default font becomes coding font again


https://github.com/user-attachments/assets/03c950ef-cf41-4e8b-b625-3405787d53c8

**Comment by urmauur** [comment]
> @urmauur I tested it again
> 
> * This time the default font is our normal font
> * However, once i paste a code block > delete it > the default font becomes coding font again
> 
>  Screen.Recording.2024-10-29.at.8.21.00.PM.mov

@imtuyethan Thanks for testing! Here’s the new buildhttps://github.com/janhq/jan/actions/runs/11577718123

**Comment by imtuyethan** [comment]
@urmauur 
It loses highlight when i enter new line:

https://github.com/user-attachments/assets/6c105d7a-2605-4a9c-9849-cb41a915e0e8

**Comment by urmauur** [comment]
> @urmauur It loses highlight when i enter new line:
> 
>  Screen.Recording.2024-11-06.at.11.33.26.PM.mov

thats expected, code block should be with start and close triple backtick,

**Comment by imtuyethan** [comment]
@urmauur 
- It loses highlight when i click randomly
- Also the colors are kinda hard to see, can we pick something darker/easier to see


https://github.com/user-attachments/assets/1172068b-5c45-4eec-b347-bd0d2592217f

**Comment by urmauur** [comment]
> @urmauur
> 
> * It loses highlight when i click randomly
> * Also the colors are kinda hard to see, can we pick something darker/easier to see
> 
>  Screen.Recording.2024-11-06.at.11.37.49.PM.mov

ok will take a look 

please help me define the color for light mode

here for dark more 

```
.hljs-comment,
.hljs-quote {
  color: #d4d0ab;
}

/* Red */
.hljs-variable,
.hljs-template-variable,
.hljs-tag,
.hljs-name,
.hljs-selector-id,
.hljs-selector-class,
.hljs-regexp,
.hljs-deletion {
  color: #ffa07a;
}

/* Orange */
.hljs-number,
.hljs-built_in,
.hljs-builtin-name,
.hljs-literal,
.hljs-type,
.hljs-params,
.hljs-meta,
.hljs-link {
  color: #f5ab35;
}

/* Yellow */
.hljs-attribute {
  color: #ffd700;
}

/* Green */
.hljs-string,
.hljs-symbol,
.hljs-bullet,
.hljs-addition {
  color: #abe338;
}

/* Blue */
.hljs-title,
.hljs-section {
  color: #00e0e0;
}

/* Purple */
.hljs-keyword,
.hljs-selector-tag {
  color: #dcc6e0;
}

```

**Comment by imtuyethan** [comment]
@urmauur I think the current palette has some similar colors / hard for the eyes to identify, here's my suggestion:

## Light mode 
```
.hljs-comment { color: #6e7781 }      /* Gray */
.hljs-variable { color: #cf222e }     /* Red */
.hljs-number { color: #bc4c00 }       /* Orange */
.hljs-attribute { color: #b58407 }    /* Yellow */
.hljs-string { color: #116329 }       /* Green */
.hljs-title { color: #0550ae }        /* Blue */
.hljs-keyword { color: #8250df }      /* Purple */
```
## Dark mode 

```
.hljs-comment { color: #8b949e }      /* Light gray */
.hljs-variable { color: #ff7b72 }     /* Light red */
.hljs-number { color: #f0883e }       /* Light orange */
.hljs-attribute { color: #ffa657 }    /* Light yellow */ 
.hljs-string { color: #7ee787 }       /* Light green */
.hljs-title { color: #79c0ff }        /* Light blue */
.hljs-keyword { color: #d2a8ff }      /* Light purple */
```
