### ISSUE TITLE
planning: Migrate Threads, Messages to Cortex, deprecates Conversation Extension

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#3904]
## Goal 

- Jan shifts Conversations state to Cortex for management
- Deprecate Conversations Extension

## Tasklist

- [ ] https://github.com/janhq/cortex.cpp/issues/1567
- [ ] Jan migration and extensive QA testing

**Comment by louis-jan** [comment]
According to this:
https://github.com/janhq/cortex.cpp/issues/1567#issuecomment-2444740659

There would be many conclusions that affect Jan's UX such as:

Threads are now coupled with model settings, which introduces a bad UX where users get their model restarted every time they switch to a new thread, even with the same model. 

1. Moving model configurations to per-model settings would be beneficial. Those settings have a global affect.
2. Assistants are clearly defined. Where users can have more than one assistant persona (instructions + parameters).

**Comment by dan-homebrew** [comment]
> As a new user to this space, it's quite hard to get thread's parameters and settings. The Writing Assistant Persona (instructions and parameters) and Model Capability Settings (more about hardware explanations) would help onboard users better.

Can you elaborate a bit more about: 
- Writing Assistant Persona: is this an Assistant?
- Model Capability Settings: is this a FAQ? Or an assistant meant to teach the user how to use Jan Settings?

**Comment by louis-jan** [comment]
ah @dan-homebrew I just mean 
1. Thread's Inference Parameters such as `temperature, frequency penalty, presence penalty` are quite incomprehensible. Move those to `Assistant` would make building an assistant persona easier to get.
2. Modifying Thread's settings parameters, such as context window and ngl, cause a bad UX. Move to per-model settings might help. From there we add more hardware detection information such as the recommended GPU layers load and context length based on their device specs -> Global effect per model, not per thread.

**Comment by dan-homebrew** [comment]
> ah @dan-homebrew I just mean
> 
> 1. Thread's Inference Parameters such as `temperature, frequency penalty, presence penalty` are quite incomprehensible. Move those to `Assistant` would make building an assistant persona easier to get.
> 2. Modifying Thread's settings parameters, such as context window and ngl, cause a bad UX. Move to per-model settings might help. From there we add more hardware detection information such as the recommended GPU layers load and context length based on their device specs -> Global effect per model, not per thread.

Got it. Can you proceed to make the recommendations for how we can break down the Assistants, Threads/Messages, and Models endpoints (and the related data structures). I think it's better we bite the bullet and move to the correct data structures

**Comment by louis-jan** [comment]
Update: 

Scoped down for frontend: 

- Route requests to the backend. Since then, all migrations can be done afterward in one place (backend).

**Comment by dan-homebrew** [comment]
Completed: 

- https://github.com/janhq/jan/issues/3895
- #3909

**Comment by louis-jan** [comment]
Attached: (Jan Frontend and QA)
- https://github.com/janhq/jan/issues/4288
