### ISSUE TITLE
planning: Jan Simple UI Fixes

### ISSUE THREAD

**Issue by dan-menlo** [janhq/jan#3906]
## Goal 

- Fix simple UI issues over next few weeks while Cortex is refactoring
- @imtuyethan to propose

**Comment by imtuyethan** [comment]
# UI bugs
- [ ] https://github.com/janhq/jan/issues/3884
- [ ] https://github.com/janhq/jan/issues/3883
- [ ] https://github.com/janhq/jan/issues/3864

# UIUX Enhancement List
### Small issues
- [ ] https://github.com/janhq/jan/issues/3752
- [ ] https://github.com/janhq/jan/issues/3882
- [ ] https://github.com/janhq/jan/issues/3812
- [ ] https://github.com/janhq/jan/issues/3885
- [ ] https://github.com/janhq/jan/issues/3881
- [ ] https://github.com/janhq/jan/issues/3850
- [ ] https://github.com/janhq/jan/issues/3820
- [ ] https://github.com/janhq/jan/issues/3815
- [ ] https://github.com/janhq/jan/issues/3810
- [ ] https://github.com/janhq/jan/issues/3713

### Bigger issues
- [ ] https://github.com/janhq/jan/issues/3537 (related to many bugs reported)
- [ ] https://github.com/janhq/jan/issues/3385 (related to many bugs reported)
- [ ] https://github.com/janhq/jan/issues/3811
- [ ] https://github.com/janhq/jan/issues/3738
- [ ] https://github.com/janhq/jan/issues/3676
- [ ] https://github.com/janhq/jan/issues/3519

**Comment by imtuyethan** [comment]
All proved, will follow up with individual tickets instead.
