### ISSUE TITLE
bug: downloaded model inactive

### ISSUE THREAD

**Issue by Lisawithyou** [janhq/jan#3907]
### Jan version

0.5.7

### Describe the Bug

I downloaded a tiny llm from the huggingface website through a url, and imported it to Jan AI. However, after trying starting the model multiple times, it still is inactive. 

### Screenshots / Logs

![Jan_3WhNIZAGkI](https://github.com/user-attachments/assets/8fa378a7-4832-46c2-b4f3-9b1a56ff99ce)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by No-Face-the-3rd** [comment]
I updated recently after I got done for the day and am having something that sounds along these lines, but notably, my downloaded model that takes longer to load becomes active, while my smaller, snappier models go to starting then back to Inactive. I opened the developer tools and it appears to think it's aborted. 

`            if (!pendingModelLoad && abortable) {
                return Promise.reject(new Error("aborted"));
            }`

My guess is that it's expecting there to be a pending load, but it's so small that it's done before that check, so it thinks it was aborted? Granted, it could be that it was aborted for some reason I am not finding. I was just trying to do a cursory peruse to see if I could figure out potentially why it was no longer working.

**Comment by Lisawithyou** [comment]
> I updated recently after I got done for the day and am having something that sounds along these lines, but notably, my downloaded model that takes longer to load becomes active, while my smaller, snappier models go to starting then back to Inactive. I opened the developer tools and it appears to think it's aborted.
> 
> ` if (!pendingModelLoad && abortable) { return Promise.reject(new Error("aborted")); }`
> 
> My guess is that it's expecting there to be a pending load, but it's so small that it's done before that check, so it thinks it was aborted? Granted, it could be that it was aborted for some reason I am not finding. I was just trying to do a cursory peruse to see if I could figure out potentially why it was no longer working.

I really have no idea. Sorry.

**Comment by louis-jan** [comment]
Hi @Lisawithyou that is an outdated model that is not supported, you can find a newer quantized version here.
https://huggingface.co/bartowski/Phi-3-mini-4k-instruct-GGUF

> llama_model_load: error loading model: error loading model hyperparameters: key not found in model: phi3.attention.sliding_window
> llama_load_model_from_file: failed to load model
