### ISSUE TITLE
bug: The entire LLama family is not working 

### ISSUE THREAD

**Issue by SimplyProgrammer** [janhq/jan#3915]
### Jan version

0.5.7

### Describe the Bug

The issue is de facto identical to the [one](https://github.com/janhq/jan/issues/3241) I posted couple of months ago, only problem is that now all of the LLama models are refusing to start with oftentimes no reason given at all...
The only notable difference is that now it is happening after updating from 0.5.6->0.5.7. In 0.5.6, it worked without problems.

### Steps to Reproduce

The video pretty much describes it perfectly, this was right after I downloaded the models from Jan's Model Explorer...

https://github.com/user-attachments/assets/749cc0d8-0412-428d-be28-59748c8378ca

### Screenshots / Logs

I have downloaded the cortex Apis in settings that LLamas are dependent on, as always after the Jan update, the only problem is that this time it did not really do much :/
![image](https://github.com/user-attachments/assets/7a7cf5b4-79e2-423b-b5e1-a2c2d1f504f4)

If we are speaking about logs, I would love to provide them, the only problem is that my /jan/logs/ folder is empty, like there is nothing present even after performing the actions shown in the video...

I have the same hw. PC as mentioned in the old issue post.

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Hi, thanks for reporting this! Quick check, were you be able to run any other models or it's just Llama? @SimplyProgrammer

**Comment by SimplyProgrammer** [comment]
Hi.
Yes I have tried installing and using also "Qwen2.5 14B Instruct Q4" and it is not starting either, so the issue does not seem to be specific to Llama family of models... I can try a specific model if you would like to...
Also my specs are:
Full system and CPU info:
![image](https://github.com/user-attachments/assets/c1f4088e-6c94-45eb-a553-2c63d67a674a)
64GB of DDR4
RTX 3080 Ti with 12GB of VRAM

**Comment by louis-jan** [comment]
Hi @SimplyProgrammer could you please help check the engines/[win-cuda] in the Jan data folder and share the file list here. There should be a couple of dll files.

**Comment by SimplyProgrammer** [comment]
I am afraid that I have no such a file...
This is ~/jan:
![image](https://github.com/user-attachments/assets/0a0d2782-763a-479b-ba2a-5a568ced0d82)

And this is the Jan installation:
![image](https://github.com/user-attachments/assets/f9c8d294-4a62-433b-93fe-6d96090be7d9)
locals and resources does not seem to be related...

**Comment by louis-jan** [comment]
@SimplyProgrammer Please try the latest version of app 0.5.8 and see if the issue persists.

**Comment by SimplyProgrammer** [comment]
Hello, again.
Yes, sry...
Indeed in 0.5.9 it works as before, both 3.1 and 3.2 models...
