### ISSUE TITLE
bug: Inconsistent sidebar transparency behavior between theme settings

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3933]
### Jan version

0.5.7

### Describe the Bug

The sidebar's transparency behavior is inconsistent and doesn't respect theme settings correctly:

- When using "Joi Dark and Solid" theme, the sidebar remains transparent
- When switching to "Translucent" theme and making the window "too small", the sidebar becomes fully solid
- The transparency issue persists even when explicitly using Solid mode in theme settings

https://github.com/user-attachments/assets/a3a11efe-9e63-4478-bfa8-ec500266d60e

### Steps to Reproduce

1. Go to Options > Appearance
2. Set theme to "Joi Dark and Solid"
3. Observe that sidebar remains transparent
4. Change theme settings to "Translucent"
5. Resize window to smaller size
6. Observe that sidebar becomes fully solid, which shouldn't happen in translucent mode

### Screenshots / Logs

-

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Works wonder on Mac, but on Window & Linux, the issue persist:

Window:

> 118 (test-windows-app-1-activated)
> OS: Windows 11 Pro (Version 23H2, build: 22631.4037)
> CPU: Intel(R) Xeon(R) Silver 4214R CPU @ 2.40GHz
> RAM: 16.0 GB
> System type: 64-bit operating system, x64-based processor

![Image](https://github.com/user-attachments/assets/16e1133b-e204-4935-a934-260d1528c628)

Linux:

> 107 (test-ubuntu-app-cpu-2)
> OS: Ubuntu 22.04.4 LTS (64-bit)
> CPU: Intel Xeon(R) Silver 4214R @ 2.40GHz (16 cores)
> RAM: 256.0 GiB1234
> GPU: llvmpipe (LLVM 15.0.7, 256 bits)

![Image](https://github.com/user-attachments/assets/be83e950-549e-4276-af94-cfad25f022f1)

**Comment by urmauur** [comment]
@imtuyethan ah since it's change from jan data folder themes, u need test for existing user update version, it will migrate the theme, 
if new user / fresh install, it's fine  

<img width="907" alt="Screenshot 2024-11-05 at 23 45 07" src="https://github.com/user-attachments/assets/539acde2-9b1d-436a-b64c-7acd7a1d02e9">

**Comment by imtuyethan** [comment]
Looks great on all OS-es
