### ISSUE TITLE
idea: [UI] Simplify system monitor display

### ISSUE THREAD

**Issue by J-Siu** [janhq/jan#3945]
### Problem Statement

Currently (as of 0.5.7), system monitor is a popup and cover up the input box and lower part of the conversation window. To continue the conversation, one have to close the system monitor.

![Screenshot 2024-11-04 at 08 01 45](https://github.com/user-attachments/assets/859f147a-f049-4f26-93a9-09917b53258d)

### Feature Idea

Suggestion:
Instead of pop up, just display the info in the status bar, and user click the "<" ">" to activate and deactivate. Like following:

When deactivate:

![Screenshot 2024-11-04 at 08 15 52](https://github.com/user-attachments/assets/1d3dd5c7-b0d6-4102-9939-967ce8938fd2)

When activate:

![Screenshot 2024-11-04 at 08 01 41](https://github.com/user-attachments/assets/f763ea3f-dbb1-4021-943d-17a608eafe3b)

**Comment by J-Siu** [comment]
Or even remove the text "System Monitor" and use the monitor icon to open and close the system info. No need to add "<" ">".

**Comment by imtuyethan** [comment]
Duplicated:
https://github.com/janhq/jan/issues/3812
https://github.com/janhq/jan/issues/3882

**Comment by dan-homebrew** [comment]
Thanks @J-Siu - we'll work this into our existing refactor of System Monitor. Appreciate your ideas!
