### ISSUE TITLE
bug: Model Download is stuck if I quit or go offline with Jan

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#396]
**Describe the bug**

- I am unable to continue downloading models for Jan, after quitting Jan while a download is in progress
- Stuck on the following screen
![image](https://github.com/janhq/jan/assets/101145494/e1f5f8f6-3c19-4bb8-b494-2cd5a2fd3449)

**To Reproduce**
1. Start downloading a model
2. Quit Jan or lose internet connection
3. Try to download a new model

**Expected behavior**
- I should be able to pause, cancel and restart download

**Screenshots**
See above

**Desktop (please complete the following information):**
 - OS: Mac M2 Max, 64GB, Ventura 13.3
 - v0.2.0

**Additional context**

**Comment by louis-jan** [comment]
@namchuai since you are working on revamping Model Management mechanism (file based manifest). Let's give it a shot, if not possible to do, let's keep the app alive on dock (similar to obsidian, ...) unless user force quit

**Comment by the-vampiire** [comment]
i dont see these anywhere in the current UI (v0.5.15). my model was stuck downloading and i couldt not find anywhere to "continue". i tried re-downloading it and it erased the 96% progress i had and started over :[
