### ISSUE TITLE
idea: Allow 8192 tokens on Claude 3.5

### ISSUE THREAD

**Issue by darkBuddha** [janhq/jan#3973]
### Problem Statement

The UI has the old value, 4096, fixed and doesn't allow to enter the correct value 8192

https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table

### Feature Idea

Allow custom values or correct the max. value

**Comment by imtuyethan** [comment]
related #3505

**Comment by louis-jan** [comment]
@urmauur the same fix as OpenRouter #4026

**Comment by imtuyethan** [comment]
Fixed:

![Image](https://github.com/user-attachments/assets/150e4f1a-6783-4763-b060-cb41b3df5ea2)
