### ISSUE TITLE
bug: Invalid API Key Error in Existing Chat Sessions with Claude 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3986]
### Jan version

0.5.7

### Describe the Bug

Users encounter "Invalid API key" errors in existing chat sessions despite having valid API credentials and sufficient usage credits. The error occurs after approximately 711 tokens of chat history but does not affect newly created chat sessions.
https://discord.com/channels/1107178041848909847/1290808756254281798
https://discord.com/channels/1107178041848909847/1305172260306419783

### Steps to Reproduce

1. Start a chat session with Claude 3.5 Sonnet
2. Continue conversation until reaching approximately 711 tokens
3. Receive an "empty" message from Jan
4. Observe "Invalid API key" error message

### Screenshots / Logs

-

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] #3987

**Comment by matteocelani** [comment]
We are experiencing the same issue described in this bug report. The "Invalid API key" error occurs similarly in our existing chat sessions with Claude.

<img width="1495" alt="Screenshot 2024-11-22 alle 15 00 24" src="https://github.com/user-attachments/assets/27218a75-3d08-41e0-bcc1-1ad83bd03d22">

We're available to provide additional information if needed to help resolve this bug.

**Comment by imtuyethan** [comment]
https://github.com/user-attachments/assets/c17a32c8-c276-4d95-a0ef-eeb68082b540
