### ISSUE TITLE
bug: [UI Bug] Another markdown in input box issue

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3988]
### Jan version

0.5.7-719

### Describe the Bug

<img width="577" alt="Screenshot 2024-11-11 at 10 07 53 AM" src="https://github.com/user-attachments/assets/c90c56e3-5b59-48fd-ac7e-33d8ad0a6359">

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
This one too,
The colors are so random:

<img width="563" alt="Screenshot 2024-12-03 at 10 09 46 AM" src="https://github.com/user-attachments/assets/e2571aad-65ce-46b7-8a01-68e950bbad3d">

**Comment by urmauur** [comment]
Based on the latest discussion with @imtuyethan , we observed user behavior and concluded that highlighting code inline in the chat input box is an unnecessary feature. However, we will still allow text formatting like bold and italic. Users will be able to type code blocks by using the backticks for starting and closing, and we will render those as code blocks in the user’s message.
