### ISSUE TITLE
bug: [UI Bug] Code block - Copy icon alignment issue

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#3990]
### Jan version

0.5.7 - 719

### Describe the Bug

Copy icon alignment issues:

<img width="934" alt="Screenshot 2024-11-11 at 11 40 20 AM" src="https://github.com/user-attachments/assets/4ec21749-b701-4a21-9c7f-514fe34fd664">

### Steps to Reproduce

Tell model to send you a blank code block

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by urmauur** [comment]
@imtuyethan FYI since we have new code block UI, should be include on this -> https://github.com/janhq/jan/issues/3713

**Comment by imtuyethan** [comment]
@urmauur It hides the copy icon though there is still text inside:

https://github.com/user-attachments/assets/48f22773-c613-4015-b74d-24db54c75fc0
