### ISSUE TITLE
bug: Pasting multiline text into chat window creates extra element that shifts UI

### ISSUE THREAD

**Issue by ity-alex** [janhq/jan#3992]
### Jan version

0.5.7

### Describe the Bug

When pasting any text longer than two lines into the chat text input field, an extra element appears and shifts the UI. It moves the upper chat content so that the topmost text is not visible anymore. Pasting shorter texts does not trigger this.

### Steps to Reproduce

1. Create a new chat window
2. Paste text that is longer than two lines (find attached)

```
test (this was pasted, and is more than two lines long) test (this was pasted, and is more than two lines long) test (this was pasted, and is more than two lines long) test (this was pasted, and is more than two lines long) test (this was pasted, and is more than two lines long) test (this was pasted, and is more than two lines long)
```

### Screenshots / Logs

<img width="915" alt="grafik" src="https://github.com/user-attachments/assets/0bfa16d9-37a2-4d31-9197-73d15692329b">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by urmauur** [comment]
Thanks we already fix for next relase 

https://discord.com/channels/1107178041848909847/1304859545759125554
