### ISSUE TITLE
model: Support Qwen2.5 Coder (14b 32b)

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#4000]
[ ] Convert 14b
[ ] Convert 32b

**Comment by imtuyethan** [comment]
@hahuyhoang411 Is this one included in v0.5.8?

**Comment by imtuyethan** [comment]
Added: 

![Screenshot 2024-11-12 at 11 06 32 PM](https://github.com/user-attachments/assets/1497de26-03b6-4095-9e16-0f54b8a28556)

**Comment by hahuyhoang411** [comment]
awesome thanks @imtuyethan
