### ISSUE TITLE
bug: App closes when switching between GPU devices on Linux

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4002]
### Jan version

0.5.7-724

### Describe the Bug

Jan crashes/closes automatically when switching between GPU devices (NVIDIA GeForce RTX 3090 and llvmpipe) in settings. Manual restart is required to continue using the app after GPU switch.

I can't record screen when using VM Linux but here's a screenshot:
![Screenshot 2024-11-12 at 11 06 32 PM](https://github.com/user-attachments/assets/08e8ed26-4446-43ec-9458-cab06fc6c812)

**Expected Behavior**
- Jan should handle GPU device switching gracefully
- App should remain open while applying new GPU settings
- If restart is required, show a prompt asking user to restart

### Steps to Reproduce

1. Open Jan
2. Go to Settings
3. Turn on GPU acceleration, under "Choose device(s)", click to open GPU selection dropdown
4. Switch between "NVIDIA GeForce RTX 3090" and "llvmpipe (LLVM 17.0.6, 256 bits)"
5. App closes automatically
6. Need to manually open Jan again to continue using it

### Screenshots / Logs

> VM 117 
> OS: Ubuntu server (test-ubuntu-2404-1)
> GPU: NVIDIA GeForce RTX 3090
> Secondary Graphics: llvmpipe (LLVM 17.0.6, 256 bits)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by louis-jan** [comment]
Sus, that’s a legacy failure app reload issue on Linux from older versions. Investigating
