### ISSUE TITLE
bug: HTTP Proxy feature is broken

### ISSUE THREAD

**Issue by zhuxindong** [janhq/jan#4017]
### Jan version

v0.5.8

### Describe the Bug

```log
models down load failed。request time out POST：http://127.0.0.1:39291/vi/models/pull
```
- I'm sure my network is OK, I had set a correct https proxy.
- On version 0.5.7,it works correctly。
![image](https://github.com/user-attachments/assets/f80d3e22-a5a4-453e-bf41-58f828d65a4c)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Update: HTTP Proxy feature is broken in 0.5.8. On it.

**Comment by dan-homebrew** [comment]
@gabrielle-ong Please follow up and create Cortex.cpp issue. Let's hotfix Cortex in a 1.0.3 release to fix this ASAP, and potentially do a quick follow-up for Jan early next week.

**Comment by imtuyethan** [comment]
Works fine on my end:

![Screenshot 2024-11-20 at 10 18 54 PM](https://github.com/user-attachments/assets/9337c825-bfea-4dba-90e7-bd0fe2f8f10f)

**Comment by sami1112279** [comment]
models down load failed。request time out POST：http://127.0.0.1:39291/vi/models/pull
