### ISSUE TITLE
bug: document upload is broken on version 0.5.8

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#4023]
### Jan version

0.5.8

### Describe the Bug

When uploading document, I don't see any request was made on /embeddings endpoint. After that, the app stuck at generating response.

After investigation, the root cause is that the Assistant Extension is outdated with the latest Cortex endpoints. There was a configuration that routed to an old Nitro instance.

See `timeWeightedVectorStore` configs which are hard coded

![Screenshot 2024-11-15 at 10 52 15](https://github.com/user-attachments/assets/af40f0ea-2a4d-4d31-a9f8-0dd166d954f0)

### Steps to Reproduce

1. Start a new chat 
2. Upload a pdf document
3. See the error

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/5d602a1a-beda-4385-a467-edc9ee85fa25)

## Proposed solution
- Update configs to match the latest cortex-server instance.

## Future enhancement
- Run a fixed embedding models such as Nomic by default to serve `/embeddings` endpoint.
- The selected GUI model is for chat operations only.

### What is your OS?

- [x] MacOS
- [x] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Can upload now, though the responses were rubbish, but that's another separate issue.
