### ISSUE TITLE
bug: Model download process is interrupted but recorded as successful in cortex.db

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#4024]
### Jan version

0.5.8

### Describe the Bug

The model downloader reports success and insertion into cortex.db, misleading users into thinking the download is complete. This can result in a failed download or a corrupted file preventing model execution.

The issue was found in cortex.cpp and has been fixed in this PR: https://github.com/janhq/cortex.cpp/pull/1665

Here’s the discussion thread about the issue, a user encountered it multiple times:
Ref: https://discord.com/channels/1107178041848909847/1306466735993389138

## Root cause
cortex.cpp marked as downloaded, but it wasn’t.

## Solution for the fix
Update cortex.cpp to check for the model file download before inserting it. This will allow Jan to pull the information accordingly.

### Steps to Reproduce

1. Download a model
2. Interrupt the internet connection
3. See the error

### Screenshots / Logs

![59491](https://github.com/user-attachments/assets/8634759b-8c6b-48e6-a9ae-a3a327b5b50e)

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by louis-jan** [comment]
Users are attempting a workaround to delete the erroneous records in cortex.db in the meanwhile.

**Comment by imtuyethan** [comment]
Can't reproduce the issue on my end:


https://github.com/user-attachments/assets/65c08f10-7a92-46ff-85e4-9272ea5d715b
