### ISSUE TITLE
feat: update inference-cortex-extension to work with the new engine management of cortex.cpp

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#4025]
### Problem Statement

NOTES: This update is marked as important, even though it doesn’t introduce any new enhancements to the current stable version. However, it will allow updates to the cortex.cpp version from Jan. This means that hotfixes from cortex.cpp can be delivered on newer versions of Jan.

According to this update from cortex.cpp (https://github.com/janhq/cortex.cpp/issues/1416), Jan needs to update the engine folder structure and execute the command cortex.cpp to set the using variant (or default) for a specific engine.

### Feature Idea

This update including: 
- Download scripts should decompress engine artifacts to their corresponding folders.
- Engine artifacts should be named in a manner that reflects the variants of the engine. 
- Ensure that the cortex.cpp server is running before allowing the user to start the model. Then, set the default engine variant accordingly.

## Folder structure
- Jan/data/extensions/@janhq/inference-cortex-extension     // LEGACY
   - bin (where engines are downloaded, as before)                 // LEGACY
       - engines
         - cortex.llamacpp
            - mac-amd64
              - engine_files…
            - mac-arm64
              - engine_files…
          - cortex-server
          
## Cortex extension life-cycle
- Extension Launch -> Boot cortex.cpp -> Health check -> Get System Information -> Set default llama.cpp engine variant

## Related issues
- https://github.com/janhq/cortex.cpp/issues/1416
- https://github.com/janhq/cortex.cpp/issues/1660

**Comment by louis-jan** [comment]
Related issues: 

https://github.com/janhq/jan/issues/4094
https://github.com/janhq/cortex.cpp/issues/1684

**Comment by imtuyethan** [comment]
Pending UI

**Comment by louis-jan** [comment]
@imtuyethan We can use 4128 for proper specs, as this one is for integrating the previous version release.
