### ISSUE TITLE
bug: Cannot use models outside the list

### ISSUE THREAD

**Issue by lv333ming** [janhq/jan#4028]
### Jan version

0.5.8

### Describe the Bug

Models not in the list cannot be displayed on my model. That is to say, I can only use the models in the list and cannot use third-party models on jan.

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Discussion here: There are a couple of cases in the discussion: 
1. Importing a multipart GGUF model which is not supported
2. Mismatch folder name and model id here https://github.com/janhq/jan/issues/4015
https://discord.com/channels/1107178041848909847/1149558035971321886/1307199735840378971

**Comment by imtuyethan** [comment]
Hi @lv333ming, thanks for spending time reporting. 
Quick follow-up questions to help us better debug your issue:

1. Can you share an example of a model not showing up on your list? Specifically:
   - What's the model name/type? It is possibly better to send us the model link. 
   - Where did you download it from? Did you try to manually import it? How did you do so?

Let me know these details and we'll help get this sorted 👍

**Comment by imtuyethan** [comment]
That PR is not related @urmauur

**Comment by imtuyethan** [comment]
Closed as not enough info, please update the latest Jan version (0.5.11) & let us know soon! @lv333ming
