### ISSUE TITLE
idea: Plain-Text support for Attachments

### ISSUE THREAD

**Issue by Palace4Software** [janhq/jan#4036]
### Problem Statement

If I want to attach a .txt file, I always have to convert it into a PDF and then pass it on to Jan.
This takes time.

In addition, Jan can only convert the PDF into a readable format very slowly, especially if the PDF is very large.

### Feature Idea

If I could attach the file directly as a .txt, Jan could not only process it faster, but the processing of the attachment would also be much faster.

**Comment by imtuyethan** [comment]
related https://github.com/janhq/cortex-internal/issues/20

**Comment by imtuyethan** [comment]
Closed as dup
