### ISSUE TITLE
bug: After reallocating data folder models continue downloading on the original(default) folder

### ISSUE THREAD

**Issue by jordipala** [janhq/jan#4037]
### Jan version

0.5.8

### Describe the Bug

Alfter reallocating data folder models continue downloading on the original(default) folder

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
@jordipala I can't reproduce this bug with my mac, can I get more information on what OS did you encountered this issue? Is it Mac, Windows or Linux?

**Comment by louis-jan** [comment]
CC @imtuyethan. I think this issue is due to the failed relocation problem, which is addressed in version 0.5.9. I attempted to relocate the app data folder, and it successfully downloaded to a new location.

**Comment by imtuyethan** [comment]
Can't reproduce this on my end with `0.5.9-750`
