### ISSUE TITLE
bug: [UI bug] Improper line breaking in response text

### ISSUE THREAD

**Issue by jeremyckahn** [janhq/jan#4039]
Hello, I love Jan! It seems that the 0.5.8 release introduced a CSS issue in response output.

> I believe this commit introduced improper line breaking in response text. Please see "excess" and "mansion" in this screenshot:
> 
> 
> 
> ![Screenshot of improper line breaking](https://github.com/user-attachments/assets/3cd90ab9-f781-47f6-8baa-a22bc8d5d1f6)
> 
>  

 _Originally posted by @jeremyckahn in [23764ca](https://github.com/janhq/jan/commit/23764caedf71b906c5e665bc8a1701e5574abe4a#commitcomment-149187087)_

**Jan version**: v.0.5.8

**OS**: Linux

**Comment by imtuyethan** [comment]
Works normally now: 

![Screenshot 2024-11-20 at 3 52 42 PM](https://github.com/user-attachments/assets/8df44bc7-a085-48c0-a466-8fa3d5b2d9fd)
