### ISSUE TITLE
bug: [Cohere] Command-R Model Not Found Error

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4054]
### Jan version

0.5.8

### Describe the Bug

https://discord.com/channels/1107178041848909847/1308513246030069800

The system is failing to load the "command-r" model through the Cohere API, despite successful API key validation through Postman. The server starts successfully but cannot locate the required model.

Error message
```
20241119 18:30:03.894029 UTC 469941 INFO  Please load your model - main.cc:117
20241119 18:30:40.904110 UTC 470002 WARN  Error: Model not found: command-r - model_service.cc:732
```

Need to check and update the V2 endpoint URL.

### Steps to Reproduce

1. Start server (listens on 127.0.0.1:39291)
2. Attempt to load command-r model
3. Error occurs despite valid API key

### Screenshots / Logs

[cortex.log](https://github.com/user-attachments/files/17827082/cortex.log)
Device: M1 Mac
API Version: V2 endpoint
Date: November 20, 2024
Service: Cortex v1.0.2

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Oh, I just realized that we defined the wrong model parameters, which only allow 4096 tokens as input. However, the weird thing is that the error message didn’t appear.

**Comment by imtuyethan** [comment]
I don't have API key to test right now, let's close this first & open another one if there's any report.
