### ISSUE TITLE
bug: "files.filter is not a function" in model-management-plugin

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#406]
**Describe the bug**
When clicking on "Explore Models", I encountered the following two pop-up errors. 

<img width="1551" alt="image" src="https://github.com/janhq/jan/assets/101145494/595fa5ce-822c-4889-a534-01b134f80cf7">

<img width="1555" alt="image" src="https://github.com/janhq/jan/assets/101145494/03552200-5c5e-4799-894c-4b2ec92100ef">

**To Reproduce**
1. Go to "Explore Models" 
2. See error pop-up 1
3. See error pop-up 2

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac M2 64GB RAM
 - Version v0.2.0

**Additional context**

**Comment by namchuai** [comment]
This issue won't happen anymore since we are using a CDN for providing model list.
