### ISSUE TITLE
idea: Pop-up Analytics opt-in after X mins of usage

### ISSUE THREAD

**Issue by eckartal** [janhq/jan#4060]
## Overview

- Full invisibility could negatively impact the app's performance and reliability
- I think we should implement limited opt-out options that exclude system info data but retain anonymous analytics

### Tracked by default

- App Opens
- System Info (App version, OS, CPU, GPU, and RAM)

Opt-out options available for `System Info Collection`

**Comment by imtuyethan** [comment]
Closed as dup of: https://github.com/janhq/jan/issues/3119
