### ISSUE TITLE
bug: [0.5.8-731] Model failed to load - error: cannot create directories...

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4062]
### Jan version

0.5.8-731

### Describe the Bug

I encountered this problem:

![Screenshot 2024-11-21 at 1 15 31 AM](https://github.com/user-attachments/assets/9a30fe1a-e432-4c42-a188-2dd681e4d6c2)

### Steps to Reproduce

1. Download Jan for linux (deb)
2. Download model Llama 3.2 1B
3. Use model > See error

### Screenshots / Logs
VM 117 (test-ubuntu-24-0401)

[app.log](https://github.com/user-attachments/files/17835090/app.log)
[cortex.log](https://github.com/user-attachments/files/17835093/cortex.log)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by eumelzocker** [comment]
FYI: This is not fixed with v0.5.9 on Windows. I switched to v0.5.7 and everything works fine.
