### ISSUE TITLE
bug: [0.5.8-731] Model failed to load - Failed to fetch error

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4063]
### Jan version

0.5.8-731

### Describe the Bug

I still encountered the famous `Failed to fetch` issue:

![Screenshot 2024-11-21 at 1 28 27 AM](https://github.com/user-attachments/assets/e9842687-c55e-4652-b038-6781981688fe)

### Steps to Reproduce

1. Download Llama 3.1 8B Instruct Q4
2. Attempt to run the model
3. See issue

### Screenshots / Logs

VM 117 (test-ubuntu-24-0401)
[app.log](https://github.com/user-attachments/files/17835212/app.log)
[cortex.log](https://github.com/user-attachments/files/17835216/cortex.log)

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
https://github.com/user-attachments/assets/74d3377b-816b-40c4-947b-fa2a4186917c

**Comment by louis-jan** [comment]
Same rootcause #4062

**Comment by eumelzocker** [comment]
FYI: This is not fixed with v0.5.9 on Windows. I switched to v0.5.7 and everything works fine.
