### ISSUE TITLE
bug: Jan Data Folder relocation issues

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4081]
### Jan version

0.5.8

### Describe the Bug

Data folder relocation functionality is not working as expected, here are multiple bug scenarios:
- [ ] 1. Failed relocations create duplicate folders in new directory
- [ ] 2. Models continue downloading to original folder after relocation https://github.com/janhq/jan/issues/4037
- [ ] 3. System moves unrelated personal files when relocating Jan data folder that are not part of Jan Data Folder. For ex:
```
One time I accidentally changed my data folder to a wrong location (e.g., Desktop), the folders were everywhere on Desktop & when I tried to change to a different directory, it moved/duplicated my personal folders in Desktop to the new directory too, even when they are not part of Jan Data Folder.
```
- [ ] 4. https://discord.com/channels/1107178041848909847/1308176479489622146
```
- User tried to change Jan Data Folder location to a different directory
- After that, when they opened the application, Jan started deleting their personal files in the same directory?
```
<img width="772" alt="Screenshot 2024-11-20 at 1 19 39 PM" src="https://github.com/user-attachments/assets/2b661210-903a-48d3-a23e-336e2a522604">

### Steps to Reproduce

1. Attempt to relocate Jan Data Folder to a new location
2. Observe that relocation fails
3. Check if app functions properly after attempted relocation

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by louis-jan** [comment]
@imtuyethan please help me update latest issues on 0.5.9, there are a couple of changes.

**Comment by imtuyethan** [comment]
Tested with 0.5.9-750

Data folder relocation functionality is not working as expected, here are multiple bug scenarios:
- [ ] 1. Failed relocations create duplicate folders in new directory
- [ ] 2. Models continue downloading to original folder after relocation https://github.com/janhq/jan/issues/4037
- [ ] 3. System moves unrelated personal files when relocating Jan data folder that are not part of Jan Data Folder. For ex:
```
One time I accidentally changed my data folder to a wrong location (e.g., Desktop), the folders were everywhere on Desktop & when I tried to change to a different directory, it moved/duplicated my personal folders in Desktop to the new directory too, even when they are not part of Jan Data Folder.
```
- [ ] 4. https://discord.com/channels/1107178041848909847/1308176479489622146
```
- User tried to change Jan Data Folder location to a different directory
- After that, when they opened the application, Jan started deleting their personal files in the same directory?
```

**Comment by louis-jan** [comment]
> Tested with 0.5.9-750
> 
> Data folder relocation functionality is not working as expected, here are multiple bug scenarios:
> 
> * [x]  1. Succeed to relocations create duplicate folders in new directory
> * [ ]  2. Models continue downloading to original folder after relocation [bug: After reallocating data folder models continue downloading on the original(default) folder #4037](https://github.com/janhq/jan/issues/4037)
> * [ ]  3. System moves unrelated personal files when relocating Jan data folder that are not part of Jan Data Folder. For ex:
> 
> ```
> One time I accidentally changed my data folder to a wrong location (e.g., Desktop), the folders were everywhere on Desktop & when I tried to change to a different directory, it moved/duplicated my personal folders in Desktop to the new directory too, even when they are not part of Jan Data Folder.
> ```
> 
> * [ ]  4. https://discord.com/channels/1107178041848909847/1308176479489622146
> 
> ```
> - User tried to change Jan Data Folder location to a different directory
> - After that, when they opened the application, Jan started deleting their personal files in the same directory?
> ```

3. System moves unrelated personal files when relocating Jan data folder that are not part of Jan Data Folder. For ex:
@imtuyethan the first time you decide to select Desktop as Jan Data Folder, it should warn you already on that. 

When you select the entire Desktop directory as Jan Data Folder, it doesn’t know which files it generates since extensions can write files there. You specifically specify this folder for Jan Data.

![CleanShot 2024-11-27 at 09 16 18](https://github.com/user-attachments/assets/56c29942-796e-47dd-a8f9-e6ee2f77d5db)

4. I think that is what they scared of, not actual behavior, we don't delete old data folder as I remember
> You may accidentally delete your other personal data when uninstalling the app in the future. Are you sure you want to proceed with this folder? Please review your selection carefully.

**Comment by imtuyethan** [comment]
That makes sense, thanks @louis-jan

**Comment by Denthemanace** [comment]
Hi, I have recently started using Jan, and the same error persists. "Unable to relocate the data folder". Apple is know for premium storage costs, so external SSD storage is vital for Apps like this that use huge GB checkpoint models. Can't get it to work, will wait for a fix. Just downloaded 3 models and 20GB is used already?
