### ISSUE TITLE
bug: App log cleanup settings inconsistency

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4085]
### Jan version

0.5.9

### Describe the Bug

- Clean app log interval only applies to Jan app logs
- Cortex.cpp log settings exist but aren't reflected

### Steps to Reproduce

1. Check log cleanup settings in Jan
2. Compare with cortex.cpp log management

**Comment by louis-jan** [comment]
Ah, it’s just a false alarm from me. Currently, it would also clean the text.log file.

**Comment by imtuyethan** [comment]
After i click `Clean logs`, the whole log folder is gone.
