### ISSUE TITLE
bug: Model parameters display unrounded decimal values

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4087]
### Jan version

0.5.8-734

### Describe the Bug

Parameters imported from cortex.cpp showing raw decimal values (0.699, 0.949) instead of properly rounded numbers.

![Screenshot 2024-11-22 at 12 01 26 AM](https://github.com/user-attachments/assets/f9f8b154-ffdb-4057-a0c1-0e36075f762a)

### Steps to Reproduce

1. Open model settings
2. Check Temperature and Top P sliders
3. Observe unrounded decimals in value display

**Comment by louis-jan** [comment]
This is a known issue from cortex.cpp. cc @nguyenhoangthuan99 @gabrielle-ong

**Comment by louis-jan** [comment]
Linked issue https://github.com/janhq/cortex.cpp/issues/1734

**Comment by imtuyethan** [comment]
This issus persists:

<img width="329" alt="Screenshot 2024-12-01 at 2 12 05 PM" src="https://github.com/user-attachments/assets/7bb42106-ab3a-4f08-bbdd-44a8685af3c3">

**Comment by imtuyethan** [comment]
It's not super critical, should not block 0.5.10 release, i'll move this to 0.5.11 @louis-jan, thank you

**Comment by imtuyethan** [comment]
Fixed:

<img width="815" alt="Screenshot 2024-12-02 at 3 15 28 PM" src="https://github.com/user-attachments/assets/75e8ba66-5b68-438c-a84b-b092e790c48f">
