### ISSUE TITLE
bug: Model size not displaying when download from Hugging Face [cortex.cpp downloader]

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4091]
### Jan version

0.5.8-736

### Describe the Bug

When downloading models from Hugging Face, the model size is not displayed in the UI:

![Screenshot 2024-11-22 at 12 12 07 AM](https://github.com/user-attachments/assets/db79a05e-4f78-4972-8098-9db9c7b1b652)

### Steps to Reproduce

1. Search for models on HuggingFace, then download a quantized version.
2. Observe model list in Jan UI.
3. Note that some models like RWKV show "-" for size while others display size (e.g., Zephyr shows 2.77GB)

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by louis-jan** [comment]
The problem appears to be related to the cortex.cpp file downloading an update. We are taking a look at this.

**Comment by namchuai** [comment]
PR: https://github.com/janhq/cortex.cpp/pull/1725

**Comment by louis-jan** [comment]
Awesome, thanks @namchuai

**Comment by imtuyethan** [comment]
Self-imported model is still missing model size on my end:

![Image](https://github.com/user-attachments/assets/850fe4a7-6c75-49a9-ab6b-9169e0fef418)

**Comment by imtuyethan** [comment]
![Image](https://github.com/user-attachments/assets/a96b0a43-ad4c-4bf8-996e-fcfe138ebe0a)
