### ISSUE TITLE
bug: Failed to load CLIP model?

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4092]
### Jan version

0.5.8-734

### Describe the Bug

CLIP model fails to load with error: `Failed to load model with ID "llava-7b". clip_model_load failed to load CLIP model from /Users/hanoi/.jan/models/llava/clip_tokenization_openai/openai Does the file exist?`

**Context (from dev):**
- Known legacy issue where clip model doesn't download but chat model marks as complete
- Issue occurs when clicking use button too quickly after download
- Vision models will be migrated to Cortex soon

<img width="504" alt="Screenshot 2024-11-21 at 7 33 15 PM" src="https://github.com/user-attachments/assets/1a0a70ce-c5d0-45d3-93df-17042e9c8b8d">

<img width="755" alt="Screenshot 2024-11-21 at 7 33 01 PM" src="https://github.com/user-attachments/assets/43b2710e-10d8-423b-a3b7-c9afc2f85a7e">

### Steps to Reproduce

1. Launch Jan
2. Attempt to load LLaVA 7B model
3. Observe error message about CLIP model failing to load

### Screenshots / Logs

- Apple M2
- 16 GB RAM
- MacOS Sonoma 14.2 (23C64)

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
This error seems strange. The clip model isn’t defined in model.json. Users likely customized it, which is incompatible.

> Failed to load model with ID "llava-7b". clip_model_load failed to load CLIP model from /Users/hanoi/.jan/models/llava/clip_tokenization_openai/openai Does the file exist?
