### ISSUE TITLE
bug: Hide Vulkan option for users who don't have GPU 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4093]
### Jan version

0.5.8-736

### Describe the Bug

Vulkan engine option is visible and can be enabled on systems without a GPU. Users who turn it on without having a GPU will see this error: 
```
Could not load engine llama-cpp: Could not load library 'C:\Users\jan\AppData\Local\Programs\jan-nightly\resources\app.asar.unpacked\shared\engines\cortex.llamacpp\windows-amd64-vulkan\v0.1.39\engine.dll
```

![Screenshot 2024-11-22 at 12 18 30 AM](https://github.com/user-attachments/assets/11f6534a-ee28-4bd7-9532-a82fa89ec4b0)

=> Vulkan option should be hidden on systems without GPU capability

### Steps to Reproduce

1. Launch Jan on a system without GPU
2. Go to Model > Engine Settings
3. Enable Vulkan option
4. Attempt to start model

### What is your OS?

- [ ] MacOS
- [X] Windows
- [X] Linux

**Comment by louis-jan** [comment]
Feature build:
https://github.com/janhq/jan/actions/runs/12176682058

**Comment by imtuyethan** [comment]
Fixed:

![Screenshot 2024-12-10 at 8 47 19 AM](https://github.com/user-attachments/assets/675163c4-78a6-4998-95f3-5b2a8a49d440)
