### ISSUE TITLE
Git submodule update error

### ISSUE THREAD

**Issue by juzblazin** [janhq/jan#41]
Need to install xcode command line tool

**Comment by juzblazin** [comment]
![Screenshot 2023-09-05 at 11 21 21](https://github.com/janhq/jan/assets/8923971/1ad73737-069d-451c-bbd5-35028a4f59ab)

**Comment by 0xSage** [comment]
yep lets just add it as a requirement via the readme

**Comment by 0xSage** [comment]
@Its-Alamin-H

**Comment by louis-jan** [comment]
dep: #30
