### ISSUE TITLE
bug: White screen issues [Memory Leak]

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4102]
### Jan version

0.5.9

### Describe the Bug

<img width="531" alt="Screenshot 2024-11-23 at 4 09 17 PM" src="https://github.com/user-attachments/assets/814a5ca2-4be7-4abb-91af-fa268d3231d5">

Happens when: 
1. When Jan is started for the first time or when a model is loaded for the first time
2. When performing other operations while Jan is running
3. When Jan generates a response that is too long

### Steps to Reproduce

_@imtuyethan: I cannot reproduce this issue on my end but here's some basic info:_

1. Initial Setup:
   - Start Jan for the first time OR
   - Load a model for the first time
   -> Result: Software not running error, white screen appears

2. During Operation:
   - Start Jan
   - Perform other operations while Jan is running
   -> Result: White screen appears

3. Long Responses:
   - Start Jan
   - Ask a question that requires a lengthy response
   -> Result: White screen appears and application crashes

### Screenshots / Logs

https://discord.com/channels/1107178041848909847/1149558035971321886/1309646228086063144

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Reproducible React-Markdown memory leak issue. Long responses crash eventually.

![Image](https://github.com/user-attachments/assets/0e8fc5eb-5c64-48f6-ace5-108f1a06058f)

**Comment by louis-jan** [comment]
Investigating, the issue persists after the initial attempt at fixing it.

**Comment by imtuyethan** [comment]
Using @louis-jan thread folder that can reproduce the issue earlier: 
[jan_1732511451.zip](https://github.com/user-attachments/files/17946255/jan_1732511451.zip)

Can't reproduce anymore:
<img width="1078" alt="Screenshot 2024-11-28 at 4 46 44 PM" src="https://github.com/user-attachments/assets/bac3ce7b-6fa3-400a-8ea3-11021b38b790">
