### ISSUE TITLE
bug: [0.5.9] Model failed to start - Failed to fetch [Locale issue - German]

### ISSUE THREAD

**Issue by Gesun66** [janhq/jan#4107]
Dear JAN Team,

The new version Jan 0.59 causes problems on all my computers. I can no longer load any LLMs at all, neither on my laptop nor on my desktop PC. I can only solve the problem by reverting to the previous version 0.58. Then everything works perfectly again. Please fix the error, it is a great program and the best I know.

Best regards

Michael
![error](https://github.com/user-attachments/assets/142c1619-d7c2-47f1-8034-9bcd84cbba3a)

**Comment by imtuyethan** [comment]
Hi @Gesun66 We just found out that this could be a locale issue. If you set the OS language to Germany, it could reproduce the issue. Can you help confirm if that is true? Otherwise, we will proceed with this fix direction.
