### ISSUE TITLE
bug: Investigate `failed to fetch` issues on 0.5.9

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4111]
### Jan version

0.5.9

### Describe the Bug

- https://discord.com/channels/1107178041848909847/1309610446751400037
- https://discord.com/channels/1107178041848909847/1309560792009674832
- https://github.com/janhq/jan/issues/4107
- https://github.com/janhq/jan/issues/4048

Multiple users are reporting consistent "Failed to fetch" errors when attempting to load models in Jan v0.5.9. The issue appears to affect both local GGUF models and prevents any LLMs from loading. Users have reported this is a regression from v0.5.8, where models loaded successfully.

**Impact**
- Affects multiple users across different systems
- Prevents loading of any LLMs
- Forces users to revert to v0.5.8 as a workaround
- Issue appears consistent rather than intermittent

**Detailed Logs**
```
2024-11-22T19:51:14.316Z [CORTEX]:: Spawning cortex subprocess...
2024-11-22T19:51:14.317Z [CORTEX]:: Spawn cortex at path: C:\Users\tth-1\AppData\Roaming\Jan\data\extensions\@janhq\inference-cortex-extension\dist\bin\cortex-server.exe
2024-11-22T19:51:14.317Z [APP]::Starting process: C:\Users\tth-1\AppData\Roaming\Jan\data\extensions\@janhq\inference-cortex-extension\dist\bin\cortex-server.exe --start-server --port 39291 --config_file_path C:\Users\tth-1\AppData\Roaming\Jan\data\.janrc --data_folder_path C:\Users\tth-1\AppData\Roaming\Jan\data

[ERROR] Could not start server: 2

2024-11-22T19:51:15.271Z [APP]::Process exited with code 0
2024-11-22T19:51:15.271Z [APP]::Restarting process in 5000ms (Attempt 1/5)
```
**Key Error Pattern**
The logs show the Cortex server failing to start with error code 2, followed by automatic restart attempts. The issue appears to be related to the Cortex server initialization rather than individual model loading.

### Steps to Reproduce

1. Install or update to Jan v0.5.9
2. Attempt to load any model (local GGUF or cloud models)
3. Observe "Failed to fetch" error message
4. Error appears consistently across different machines and model types

### Screenshots / Logs

**One of the reported devices:**
- OS: Windows 11 Pro (10.0.22631)
- CPU: 11th Gen Intel i9-11900KF @ 3.50GHz (16 cores)
- RAM: 32GB (Total: 34220601344 bytes, Free: 25615065088 bytes)
- GPU: NVIDIA GeForce RTX 4070 (12GB VRAM)
- NVIDIA Driver: 566.14
- CUDA: Version 12
- Architecture: x86_64
- CPU Instructions: AVX512
- Engine Variant: windows-amd64-avx512

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
We don't support multipart GGUF yet, #3879 
> Marck R confirms same issue affecting 2-part models like nemotron

**Comment by louis-jan** [comment]
Update: 2 & 3: Locale issue from cortex.cpp. drogonframework header builder

**Comment by imtuyethan** [comment]
https://discord.com/channels/1107178041848909847/1310723384132239477
<img width="470" alt="Screenshot 2024-11-26 at 2 05 15 PM" src="https://github.com/user-attachments/assets/b787001e-e2de-4251-861b-1f3bcf03ba1d">

**Comment by imtuyethan** [comment]
https://discord.com/channels/1107178041848909847/1310842645328695346
