### ISSUE TITLE
bug: Jan defaults to a remote model even when i downloaded some local models 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4114]
### Jan version

0.5.9

### Describe the Bug

I install Jan app fresh. Download some local models from Starter Screen, after finish downloading at least 1 local model, Jan defaults to a remote model & show API key error upon sent message, which is super confusing. 

**Expected behavior:**
Once any local model has been downloaded from Starter Screen, default to use it. 

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by urmauur** [comment]
https://github.com/janhq/jan/pull/4083

**Comment by imtuyethan** [comment]
Fixed:
<img width="1076" alt="Screenshot 2024-11-26 at 10 53 22 PM" src="https://github.com/user-attachments/assets/3f6ba0aa-176a-4e6f-974d-f32c1b1994c9">

**Comment by imtuyethan** [comment]
Wait I just realized it set model to `Mistral 7B` even though i downloaded `Llama 3.2` & `Qwen2.5`
<img width="1058" alt="Screenshot 2024-11-26 at 11 00 09 PM" src="https://github.com/user-attachments/assets/c9817d57-5b03-4382-b8e1-66b2a9128afc">

**Comment by imtuyethan** [comment]
It's still not fixed yet:

https://github.com/user-attachments/assets/6e499623-8787-4b8d-a91a-eebd4f45f66c

**Comment by imtuyethan** [comment]
Fixed:

![Image](https://github.com/user-attachments/assets/a9258e25-126e-413e-b95e-d33e9b2d6ec4)
