### ISSUE TITLE
feat: Update Jan’s client request to adapt API changes from Cortex

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#4123]
According to the latest update on engine variant updates from cortex.cpp (https://github.com/janhq/cortex.cpp/issues/1684), Jan should update their request to work with the latest change.

Expected Results:
1. Jan sends an engine variant configuration request on launch or a settings update.
2. Use a POST request body instead of query parameters.
3. After updated cortex.cpp binary, function the same.

**Comment by imtuyethan** [comment]
@louis-jan Any idea how I can test this hic?
