### ISSUE TITLE
bug: Inference gets stuck, and Memory Usage is > than other applications

### ISSUE THREAD

**Issue by dan-homebrew** [janhq/jan#4124]
## Goal 

From WiseFarAI in Discord: 

There still seem to be a few bugs regarding generation. It is often stuck on generating a response for far too long. It also seems like the memory usage is higher than I am used to with using other LLM applications. I've also seen that after a bit of context >3K - answers seem to take a long time and I am not used to that at all.

Also, after a while on 0.5.9 chatting on a local model, the UI seems to crash and just shows a translucent screen.  I have to force close and reopen the app to fix it

![Image](https://github.com/user-attachments/assets/376f79e7-baa9-4712-8094-7a1188c81603)

**Comment by louis-jan** [comment]
@dan-homebrew 
Transferred to Jan, and dup here https://github.com/janhq/jan/issues/4102
