### ISSUE TITLE
bug: [Whole app lost rendering while loading a long conversation]

### ISSUE THREAD

**Issue by SkipM4** [janhq/jan#4140]
### Jan version

0.5.9

### Describe the Bug

I've installed Jan 0.5.9 3 days ago to use GPT-4o help vue web app developing
but as I ask more questions and GPT gives me more answers(includes html&css code)
Jan app would suddenly turn into a blank blur window and not respond to any actions,only to close it and lost the latest answer from ChatGPT
I've tried change app themes,turn on/off GPU acceleration,turn on/off Vulkan support,not solving the problem

### Steps to Reproduce

Go to 'Thread'
Create a conversation with GPT-4o
Send some html/vue/css code to GPT and request it to improve it
After about 50 conversations the bug may reproduce

### Screenshots / Logs

![图片](https://github.com/user-attachments/assets/cf1509e9-da43-4f0e-9211-180f14a5c4ee)

![图片](https://github.com/user-attachments/assets/22c19740-7c0f-4b66-aa50-7b9a2f827160)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by SkipM4** [comment]
and the logs
[app.log](https://github.com/user-attachments/files/17932467/app.log)
[cortex.log](https://github.com/user-attachments/files/17932469/cortex.log)

**Comment by imtuyethan** [comment]
This is a known issue that we will fix in v0.5.10
Dup #4102
