### ISSUE TITLE
enhancement: Better error handing for remote models when there's no internet connection

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4142]
### Problem Statement
Currently, when there's no wifi, and user selects a remote model to use, it shows `Failed to fetch`:

<img width="463" alt="Screenshot 2024-11-27 at 6 29 42 PM" src="https://github.com/user-attachments/assets/40366e1a-11bb-4779-9ee4-743ccfce87d0">

### Enhancement
Better error handling:

`No internet connection. Switch to an on-device model or check connection.`

**Comment by louis-jan** [comment]
@imtuyethan @urmauur how about existing threads that already selected remote models? Users can still attempt to send messages anw.

**Comment by imtuyethan** [comment]
> @imtuyethan @urmauur how about existing threads that already selected remote models? Users can still attempt to send messages anw.

There's a separate ticket to handle that: 
- https://github.com/janhq/jan/issues/3385
- https://github.com/janhq/jan/issues/3537
