### ISSUE TITLE
bug: [UI bug] Stop word input - Expand the words to the size of the whole right sidebar

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4154]
### Jan version

0.5.10

### Describe the Bug

Related to #4088 

There are redundant spaces while the word box could be expanded to fit the whole sidebar or fit 2 word boxes at the same time: 

<img width="447" alt="Screenshot 2024-11-28 at 5 18 43 PM" src="https://github.com/user-attachments/assets/0c86aedc-86e2-479c-a195-99472af7a565">

https://github.com/user-attachments/assets/0df9ec9c-7946-413e-92de-b3eceb1027a4

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by urmauur** [comment]
<img width="415" alt="Screenshot 2024-12-05 at 13 39 10" src="https://github.com/user-attachments/assets/0d002b3d-c5bb-4d26-aa77-cd1b5bdea2c8">

It’s expected since we have a set minimum width for truncating words, so it will depend on the length of the next word

@imtuyethan
