### ISSUE TITLE
bug: Failed to fetch error when killing Cortex process in Task Manager

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4155]
### Jan version

0.5.9-751

### Describe the Bug

When users force-kill the Cortex process in Windows Task Manager and immediately try to send a message in Jan's UI, they receive a "failed to fetch" error. This indicates that Jan is not gracefully handling cases where the Cortex process is terminated unexpectedly.

### Steps to Reproduce

1. Open Jan application
2. Open Windows Task Manager
3. Find and end the Cortex process
4. Immediately try to send a message in Jan's chat interface
5. Observe "failed to fetch" error appears

### Screenshots / Logs

https://github.com/user-attachments/assets/628a3e0a-d0d0-425b-9446-eb01869236a3

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Available for testing on the latest nightly build - 764

**Comment by imtuyethan** [comment]
Fixed: 

https://github.com/user-attachments/assets/b3aaef77-549e-477e-a451-27f69ee9d4fb
