### ISSUE TITLE
bug: OpenRouter stream error response not properly handled

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4162]
### Jan version

v0.5.9

### Describe the Bug

https://discord.com/channels/1107178041848909847/1311432092927660042
When using the OpenRouter extension with specific model choices (mistralai/mistral-large-2407), the app doesn't properly handle OpenRouter's streaming error responses. Instead of showing a proper error message in the UI, it displays a generic "Something's wrong. Access troubleshooting assistance now." dialog.

The specific error from OpenRouter (max tokens limit exceeded: 102399 > 921) is not being properly parsed and displayed to the user because it's coming as a stream error instead of a JSON response.

### Steps to Reproduce

1. Configure OpenRouter extension settings
2. Try to use the model "mistralai/mistral-large-2407"
3. Make a request to https://openrouter.ai/api/v1/chat/completions
4. Observe the generic error dialog instead of the actual OpenRouter error message

### Screenshots / Logs

<img width="814" alt="Screenshot 2024-11-29 at 3 46 17 PM" src="https://github.com/user-attachments/assets/12258eb9-5cc2-4bd8-9e8e-a2c34d61e870">

<img width="783" alt="Screenshot 2024-11-29 at 3 46 31 PM" src="https://github.com/user-attachments/assets/7d7f9b88-7a41-4019-a7ed-4ce85c378dce">

> Device specs
> - OS: Windows 10 Pro
> - CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
> - GPU: GeForce GTX 1080 Ti
> - RAM: Total Mem: 34312163328

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
Available for testing on the latest nightly build - 764
