### ISSUE TITLE
bug: Interrupted threads causes Invalid API key error with Anthropic API

### ISSUE THREAD

**Issue by suda** [janhq/jan#4165]
### Jan version

0.5.9

### Describe the Bug

If the assistant is stopped before any tokens are being outputted, the rest of the thread keeps throwing `Invalid API key` error. The `messages.jsonl` gives more context:

```
messages.5: all messages must have non-empty content except for the optional final assistant message
```

### Steps to Reproduce

1. Start a new thread using the Anthropic API
2. Send a message
3. Immediately stop the generation before any tokens are added
4. Next message should fail with  `Invalid API key` error

### Screenshots / Logs

```jsonl
{"id":"01JDT0QMP9D91QW5Q1BSMB5JQD","thread_id":"jan_1732814439","role":"user","status":"ready","created":1732818752201,"updated":1732818752201,"object":"thread.message","content":[{"type":"text","text":{"value":"Hello","annotations":[]}}]}
{"id":"01JDT0QMQJ9N0H5NXNZA3P7V9R","thread_id":"jan_1732814439","type":"Thread","role":"assistant","content":[],"status":"stopped","created":1732818752242,"updated":1732818752242,"object":"thread.message"}
{"id":"01JDT0R1P8R27PQPGCF94016CT","thread_id":"jan_1732814439","role":"user","status":"ready","created":1732818765512,"updated":1732818765512,"object":"thread.message","content":[{"type":"text","text":{"value":"Hi","annotations":[]}}]}
{"id":"01JDT0R1QJEX38FF5498R62RFP","thread_id":"jan_1732814439","type":"Thread","role":"assistant","content":[{"type":"text","text":{"value":"messages.5: all messages must have non-empty content except for the optional final assistant message","annotations":[]}}],"status":"error","created":1732818765554,"updated":1732818765554,"object":"thread.message","error_code":"invalid_request_error"}
```

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Can reproduce with `Jan v0.5.9-753`:

<img width="1363" alt="Screenshot 2024-12-01 at 11 39 03 AM" src="https://github.com/user-attachments/assets/f666fd5e-9a0e-4504-a18c-8444cf659fec">

**Comment by louis-jan** [comment]
Available for testing on the latest nightly build - 764

**Comment by imtuyethan** [comment]
Fixed:

<img width="719" alt="Screenshot 2024-12-04 at 8 06 31 PM" src="https://github.com/user-attachments/assets/81ff4ca4-1d5d-415a-8af5-ab71aa7bc411">
