### ISSUE TITLE
bug: Ordered list is off-screen

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#4169]
### Jan version

0.5.9

### Describe the Bug

As the latest markdown renderer attempted to align the ordered list based on its content (left-aligned), it’s great to see that all the list contents are well-aligned. However, this alignment has a side effect: all the order indexes are now off-screen. For instance, index 1000001 will only display 1.

### Steps to Reproduce

Refer to the screenshots for the example prompts.

### Screenshots / Logs

![CleanShot 2024-11-30 at 19 20 53](https://github.com/user-attachments/assets/2fbb6aeb-01c2-4b8b-aa97-13020656ad05)

### What is your OS?

- [x] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Fixed:

<img width="394" alt="Screenshot 2024-12-09 at 10 33 18 PM" src="https://github.com/user-attachments/assets/91502147-2a0a-46ab-b51d-f278bfa2e336">
