### ISSUE TITLE
bug: Chat window doesn't auto-scroll to show the end of the message

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4178]
### Jan version

0.5.9-757

### Describe the Bug

It automatically scrolls, but it doesn't scroll to the end of the response, I need to manually scroll down to see the `copy` `regenerate` & `delete` functions:

https://github.com/user-attachments/assets/bf6309ef-ebbe-4859-a97e-8933465dd7d5

### Steps to Reproduce

1. Start a conversation
2. Observe the behaviour

### What is your OS?

- [X] MacOS
- [X] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
@louis-jan can cover for @urmauur with this when he's on leave

**Comment by louis-jan** [comment]
> @louis-jan can cover for @urmauur with this when he's on leave

Yeah, let me take over this

**Comment by louis-jan** [comment]
Available for testing on the latest nightly build

**Comment by imtuyethan** [comment]
Fixed:

<img width="733" alt="Screenshot 2024-12-04 at 7 57 28 PM" src="https://github.com/user-attachments/assets/460bcd5d-e25f-4555-bed2-d4705c5e9e2f">

**Comment by TC117** [comment]
![Image](https://github.com/user-attachments/assets/06d92532-ba42-4a48-a924-c4a80e06965f)
