### ISSUE TITLE
bug: Model starting state not visible when switching to threads screen

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4179]
### Jan version

0.5.9-757

### Describe the Bug

When starting a model from the My Models page and switching to the threads screen, there is no visual indication that the model is in the process of starting up. This lack of loading state feedback makes it unclear whether the model is actually initializing or not.

### Steps to Reproduce

1. Open Jan on Linux
2. Go to My Models page
3. Click to start a model
4. Switch to the threads screen immediately after
5. Observe: No loading/starting state is shown

### Screenshots / Logs

# On Linux
I started a model from `My Models` page:
![Screenshot 2024-12-02 at 3 44 21 PM](https://github.com/user-attachments/assets/f8474cf5-fa84-4904-af1c-b5f4a722487c)

However on `Threads` screen it doesn't show the loading component:

![Screenshot 2024-12-02 at 3 44 46 PM](https://github.com/user-attachments/assets/3c8a90ee-ba84-4bd0-8d9f-9ab1de5e86c6)

# On Mac
It shows normally:
<img width="1107" alt="Screenshot 2024-12-02 at 3 46 26 PM" src="https://github.com/user-attachments/assets/8264fce5-9836-47e8-aae2-c80f778646bd">

<img width="1098" alt="Screenshot 2024-12-02 at 3 46 17 PM" src="https://github.com/user-attachments/assets/b8ba8cac-cf4a-487c-95c2-33ca57b341fa">

### What is your OS?

- [x] MacOS
- [ ] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
It happens on Mac too:


https://github.com/user-attachments/assets/671bf3fa-3c7e-4988-b185-1ed7bb6272c6

**Comment by louis-jan** [comment]
@imtuyethan You chose a different model than the one selected in the thread.
![Image](https://github.com/user-attachments/assets/200face0-64e6-4fe2-a0c8-81055bfa0108)

**Comment by louis-jan** [comment]
@imtuyethan close as discussed

**Comment by imtuyethan** [comment]
Fixed:

https://github.com/user-attachments/assets/90d1b754-c258-4400-a90a-7b736bf5a496
