### ISSUE TITLE
feat: enable `continue` button for when LLM responses exceed token limit

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#418]
**Describe the bug**
LLM responses seem to terminate prematurely, do we have a max reply token setting somewhere?
EDIT: Mistral likely limited to 512?

**To Reproduce**
1. Use Mistral 7b instruct
2. Ask Mistral 7b to generate 100 names similar to "Thinking Machines"
3. Mistral will generate 63 or so
4. Ask Mistral to continue
5. Mistral generates the remaining 100

**Expected behavior**
Mistral should generate the full 100

**Screenshots**
<img width="1445" alt="image" src="https://github.com/janhq/jan/assets/101145494/e5e38f10-6aaa-4413-9639-0cc506481aef">

<img width="1443" alt="image" src="https://github.com/janhq/jan/assets/101145494/9d0404af-53df-40af-8831-2240162ad8b2">

**Desktop (please complete the following information):**
 - OS: Mac M2 64GB RAM
 - Version v0.2.0

**Additional context**

**Comment by louis-jan** [comment]
@vuonghoainam I saw your latest update already define context length = 2048 {ctx_len: 2048}, which seem pretty good. But the issue still exists. Let's investigate this somewhere this week

**Comment by 0xSage** [comment]
@imtuyethan can you check if this issue still exists? Closing if not

**Comment by imtuyethan** [comment]
Just checked, still happens on my end. 

cc @vuonghoainam @louis-jan @0xSage 

https://github.com/janhq/jan/assets/89722390/a398fc78-461d-48e8-a75a-3e3d7abfe7fb

**Comment by louis-jan** [comment]
I will check this

**Comment by vuonghoainam** [comment]
The way this one should work is that user can click on the button to keep generating more. The default behavior of LLM is to stop once the token limit reaches. See `ChatGPT` UI

**Comment by louis-jan** [comment]
Same result with other testing tools. Good suggestion @vuonghoainam. Do you know the indicator for displaying this button? Specifically, how can we determine from the response when the message has reached the token limit (count the tokens)?

**Comment by louis-jan** [comment]
Converted this to a feature request

**Comment by dan-jan** [comment]
@louis-jan I'm going to shift this to "Jan as the Default Assistant", and we'll re-file issue as a "Continue" button.

**Comment by imtuyethan** [comment]
Closed this as it's deprecated, we have `max token` in threads settings now.
