### ISSUE TITLE
bug: Width is too narrow in desktop UI 

### ISSUE THREAD

**Issue by InconsolableCellist** [janhq/jan#4187]
### Jan version

jan-linux-x86_64-0.5.9.AppImage

### Describe the Bug

The width of the output text is too small

![image](https://github.com/user-attachments/assets/e2f23acb-084a-41df-a5e2-99bb284c3b6a)

This is caused by the CSS: 

```
.max-w-\[700px\] {
    max-width: 700px;
}
```

In my instance this is created by the presumably auto-generated `file:///tmp/.mount_jan-liY70uga/resources/app.asar/renderer/_next/static/css/86c7155b5705f354.css`

Setting the width to `100%` or removing the rule fixes the issue

Constraining the width of the code block may look aesthetically pleasing to some people (perhaps?) but it's a major pain when interacting with code.

### Steps to Reproduce

1. Interact with a model such that it generates a code block with long lines of text
2. Note that you have to horizontally scroll the code block even when there's sufficient space on either side to otherwise contain it

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
@InconsolableCellist You can expand & collapse the width if you want, I don't see what's the issue?

**Comment by imtuyethan** [comment]
- Related: https://github.com/janhq/jan/issues/3509.
Closed as duplicated, will follow up with https://github.com/janhq/jan/issues/3509 instead.
