### ISSUE TITLE
bug: Stop button got stuck with inference abort error

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4202]
### Jan version

0.5.9-761

### Describe the Bug

I encountered an abort error while making parameter changes during active inference generation. The stop button got stuck after that, preventing normal termination of the process.

### Steps to Reproduce

It was random, i can't reproduce again, here are some further info:
- Occurred while modifying parameters during active generation
- Parameters were being adjusted during active generation

What happened:
1. Abort error displayed
2. Stop button became unresponsive
3. The generation process could not be terminated normally

### Screenshots / Logs

<img width="896" alt="Screenshot 2024-12-03 at 4 35 33 PM" src="https://github.com/user-attachments/assets/97eb3e2b-b788-4ef9-9db5-344c4cfd1efb">

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by louis-jan** [comment]
@vansangpfiev As we performed a temporary workaround provided by the client. We can check the pending request on start/stop later.

**Comment by imtuyethan** [comment]
can't reproduce on `0.5.11-824`

**Comment by imtuyethan** [comment]
Can reproduce again on Linux `VM 117`:

While the model is generating response, attempt to edit the parameter -> model stops generation but stop button got stuck.

<img width="676" alt="Screenshot 2024-12-26 at 4 22 45 PM" src="https://github.com/user-attachments/assets/42c6fde5-eada-40ff-bafe-5a557b7984ba" />

**Comment by imtuyethan** [comment]
Fixed in `Jan v0.5.12-rc2-beta`
