### ISSUE TITLE
bug: [0.5.10] Unable to start OLMo-2-1124-13B-Q8_0.gguf

### ISSUE THREAD

**Issue by derpina-ai** [janhq/jan#4204]
### Jan version

Jan v0.5.10

### Describe the Bug

Unable to start OLMo-2-1124-13B-Q8_0.gguf

### Steps to Reproduce

Download OLMo-2-1124-13B-Q8_0.gguf - https://huggingface.co/allenai/OLMo-2-1124-13B-GGUF/blob/main/OLMo-2-1124-13B-Q8_0.gguf
Start model.
Unable to start model.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/2d98d2e6-c6ac-4489-a5f0-538f8124653c)

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by derpina-ai** [comment]
Just wanted to know if there is some special feature missing in Jan in order to run this model, if it's not supported, just let me know, thank you.

**Comment by imtuyethan** [comment]
@derpina-ai Quick check, you can't run this model at all or it failed sometimes? Can you send you logs here, thank you!

<img width="1142" alt="Screenshot 2024-12-04 at 4 57 48 PM" src="https://github.com/user-attachments/assets/52fce45d-def8-4850-a8e5-3168b953b0c5">

**Comment by imtuyethan** [comment]
Sorry this model has a different architecture which Jan currently doesn't support. The error message could be clearer however it takes greater effort for us to do correct error handling than support more architectures. We will try to support more model architectures in the future!
