### ISSUE TITLE
bug: [0.5.10 & olders] Empty title when using special characters

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4208]
### Jan version

0.5.10 & olders

### Describe the Bug

https://discord.com/channels/1107178041848909847/1307915350406467664/1313467218239160461

Dialog title becomes empty/disappears when title contains special characters or non-Latin text.

### Steps to Reproduce

1. Create new chat with special characters/non-Latin text in title
3. Observe empty title field

### Screenshots / Logs

<img width="545" alt="Screenshot 2024-12-03 at 9 25 49 PM" src="https://github.com/user-attachments/assets/82a98c3d-fa7d-44f7-ae64-be6476006193">

### What is your OS?

- [x] MacOS
- [x] Windows
- [x] Linux

**Comment by imtuyethan** [comment]
![Image](https://github.com/user-attachments/assets/59b01050-ae75-40cb-9a74-93231f5d8cc2)

**Comment by TC117** [comment]
![Image](https://github.com/user-attachments/assets/873ce38d-61a5-4cc9-9120-72ec525b59af)
