### ISSUE TITLE
bug: [0.5.10] max_tokens value inconsistency between Jan UI and json file

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4209]
### Jan version

0.5.10

### Describe the Bug

https://discord.com/channels/1107178041848909847/1307915350406467664/1313467218239160461
Jan UI shows 4096 max tokens while thread.json and Cortex logs show 32768. GUI slider constraint doesn't persist to storage.

### Steps to Reproduce

1. Open Jan with Qwen2.5 Coder 14B Instruct
2. Check max_tokens in GUI (4096)
3. Compare with thread.json (32768)
4. Verify Cortex logs (32768)

### Screenshots / Logs

<img width="772" alt="Screenshot 2024-12-03 at 9 43 26 PM" src="https://github.com/user-attachments/assets/798133cf-eaf7-4efd-a708-1fb9d1273924">
<img width="786" alt="Screenshot 2024-12-03 at 9 43 34 PM" src="https://github.com/user-attachments/assets/0bdccaf5-14c7-4c7f-9e1c-1c7c66ffb24a">

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
![Image](https://github.com/user-attachments/assets/a3ad1b49-36ee-41c8-a4ac-18b4d9e1eb1d)
![Image](https://github.com/user-attachments/assets/84b598b8-5873-49c0-92d0-08746338834d)

**Comment by TC117** [comment]
0.5.10-767 - win 11 ✅ 
![Image](https://github.com/user-attachments/assets/5ec3a837-aafe-42eb-ad77-07faab3789b0)
