### ISSUE TITLE
feat: Jan automatically detects CUDA support on windows and linux for Nitro

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/jan#422]
**Problem**
- Currently the default built nitro binaries supports NVIDIA, there is no fallback. If the machine does not have CUDA installed properly, nitro will fail.

**Success Criteria**
- Automatically check CUDA installed to use respective Nitro binaries
- Support for Windows and Linux

**Additional context**
- https://github.com/janhq/jan/blob/main/plugins/inference-plugin/module.ts#L35
- Check if CUDA installed, we can use the simplest way is to check if `nvidia-smi` or `nvcc` succeeds, else there is no CUDA installed.

**Comment by hiento09** [comment]
I fixed this bug in https://github.com/janhq/jan/pull/451
