### ISSUE TITLE
idea: check update every [duration] only

### ISSUE THREAD

**Issue by eregnier** [janhq/jan#4221]
### Problem Statement

(almost) daily updates break my flow (and I have to deal with it on all my computers)

### Feature Idea

Hi team,

First, thank you again for this sofware I use daily on all my computers, it's awesome

However, almost every day on my computers jan ask me to self update. This is a great news, however because jan looks stable in it's core usages (ask llm things, get streamed response, select new llm to test...), I would enjoy a feature in the app parameters that lets me choose the frequency of jan update check. 

In my case, I really think I don't need more than one update a month (and maybe it's a good default) because as I said, I already have all what I need and the next month update will bring cool stuff I'll have a month to discover.

The fact is that update system is currently based on the following flow :
 - launch the app
 - start new page to ask a thing
 - get a blocking popup in the middle that break my flow and choose between delay things I would like to do, but I don't really care now or apply immediately, wait for download, wait for restart, wait for update window then resume my broken dev flow.

I hope you'll understand and share my point. Having a lot of frequent update looks like a good thing for a software, however, current update flow is annoying to me and can be (I think) fixed easily the way I suggest (or with an other update management implementation)

Thank you for you work, it's awesome !

Eric.

**Comment by imtuyethan** [comment]
Sounds like you're using nightly version, which is supposed to release new version everyday & super unstable, nightly version is used for testing purposes only. 
Please download stable version here: https://jan.ai/download
