### ISSUE TITLE
feat: Chat to Doc with local LLM - nitro

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/jan#423]
**Problem**
- The PR #362 supported chat to doc with openai/ azure openai
- We still need to support Nitro powered LLM in place

**Success Criteria**
- Create a bot with local downloaded model
- Chat with it seamlessly

**Additional context**
None

**Comment by 0xSage** [comment]
closing as specs have changed a bit
we can create a new issue for the embeddings/files stuff later on
