### ISSUE TITLE
bug: Wrong `max_tokens`, preventing users from using some remote models

### ISSUE THREAD

**Issue by khanakia** [janhq/jan#4238]
### Jan version

v0.5.11

### Describe the Bug

App broke Immediately after update. Now with every new thread it takes `8192` as max tokens

and now I have to adjust the token back to `4096` every time I create a new thread

### Steps to Reproduce

- Update the app to the latest version
- Select the GPT 4 Turbo as your model

### Screenshots / Logs

![Screenshot 2024-12-05 at 9 28 40 PM](https://github.com/user-attachments/assets/6a76b053-b1c6-409e-a8a7-1656b89b26a4)

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by khanakia** [comment]
@dan-homebrew  
Is there any update it's so irritating and it's preventing me from using the Jan app daily

I believe so many users are facing the same issue and a CRITICAL one


https://github.com/user-attachments/assets/f1e571b8-9463-4213-a19f-dd60866b0424

**Comment by imtuyethan** [comment]
Thanks for reporting @khanakia. We'll take a look & let you know ASAP.

**Comment by imtuyethan** [comment]
@louis-jan It happened specifically with `GPT 3.5 Turbo` & `GPT 4 Turbo`

**Comment by imtuyethan** [comment]
Seems like it happened with some remote models from other provider as well:

<img width="969" alt="Screenshot 2024-12-09 at 2 41 32 PM" src="https://github.com/user-attachments/assets/db570869-c519-479e-83ea-c547ca682e22">

**Comment by imtuyethan** [comment]
@louis-jan Still the same on my end:

<img width="778" alt="Image" src="https://github.com/user-attachments/assets/050f6886-dfab-4325-a5d6-90dc75c8c46a" />

**Comment by louis-jan** [comment]
@imtuyethan Please create a new thread or switch between models to reflect the new settings. Old threads have model parameters persisted.

**Comment by louis-jan** [comment]
> Seems like it happened with some remote models from other provider as well:
> 
> <img alt="Screenshot 2024-12-09 at 2 41 32 PM" width="969" src="https://private-user-images.githubusercontent.com/89722390/393745317-db570869-c519-479e-83ea-c547ca682e22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0MTI4MjcsIm5iZiI6MTczNDQxMjUyNywicGF0aCI6Ii84OTcyMjM5MC8zOTM3NDUzMTctZGI1NzA4NjktYzUxOS00NzllLTgzZWEtYzU0N2NhNjgyZTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA1MTUyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiNzgwNDY4NTFkYWRhYTQ2MTVmZjk2NWUwMGU1OWJlYmY2YTI2YjU0ZGE3ZTE0Nzc2ZGQ2YWI0ZDQwY2UwZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HvQRlTvPPzpi8-tN4T2-r7DxNwPc5QN994FO42-STAI">

This model is no longer supported, you definitely have this model from previous version. Please delete this model.json file.

**Comment by imtuyethan** [comment]
I see GPT3.5 Turbo is still on their model page @louis-jan https://platform.openai.com/docs/models/gp

<img width="671" alt="Screenshot 2024-12-18 at 9 50 14 AM" src="https://github.com/user-attachments/assets/0604f28c-9695-41e5-b6a8-3ccb1a265c5d" />

**Comment by imtuyethan** [comment]
Created new thread works

**Comment by khanakia** [comment]
The issue is still not fixed

I tried to update the Jan.app but it says I am already up to date `Jan Version v0.5.11`

**Comment by khanakia** [comment]
@imtuyethan when are you going to launch a new release? it is so irritating to use the Jan.app daily with this bug

**Comment by khanakia** [comment]
@imtuyethan  Jan just released a new version v0.5.12 but the bug is still there
