### ISSUE TITLE
bug: performance issue when pasting long content into the chat input box.

### ISSUE THREAD

**Issue by urmauur** [janhq/jan#4239]
### Jan version

0.5.11

### Describe the Bug

When users attempt to paste lengthy text into the chat input box, the application experiences a noticeable lag or freezes temporarily. This performance issue may be caused by inefficient handling of large text inputs, such as real-time processing or rendering operations in the background.

Expected Behavior:
The input box should handle pasting large text seamlessly, with no noticeable lag or performance degradation.

### Steps to Reproduce

1. Open the application.
2. Copy a large block of text (e.g., several pages or thousands of words).
3. Paste the copied text into the chat input box.
4. Observe any delays, freezing, or unresponsiveness in the application.

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
https://github.com/user-attachments/assets/84ec0f7b-69b5-4f37-bbbc-f81348e53907

**Comment by TC117** [comment]
Checked on Win 11, v0.5.11-778 ✅ 

https://github.com/user-attachments/assets/bf658aed-2892-4aa6-a208-45078a47d8ad
