### ISSUE TITLE
[spike] Jan UIKit

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#424]
## Description

App now can just register functions and triggered by application.
After refactored to App instance #403 we need to give more access to UI system.

- App can register ribbon actions to set active view (right panel view)
- App can define it view & style

![Image](https://github.com/janhq/jan/assets/133622055/6feefa7e-a325-4af8-a0f3-2bd5f6e24970)

## Tasks

- [ ] UIKit by @urmauur 
- [ ] UIKit in Figma @imtuyethan

**Comment by louis-jan** [comment]
https://github.com/janhq/jan/blob/main/adr/adr-004-UI-Service.md

**Comment by louis-jan** [comment]
This will take 2-3 sprints, for now will prepare for the layout and refactoring first cc @urmauur

**Comment by 0xSage** [comment]
Deprecated.
