### ISSUE TITLE
bug: [DESCRIPTION] Can't upload image to claude sonnet

### ISSUE THREAD

**Issue by blake41** [janhq/jan#4243]
### Jan version

0.5.10

### Describe the Bug

When I click on the attachment button image is greyed out and when i mouse over it it says "This feature only supports multimodal models". If I drag and drop an image it says "We do not support this file type"

There must be a setting somewhere that is telling Jan that claude sonnet is NOT multimodal even thought it IS multimodal.

### Steps to Reproduce

Click on attachment, drag and drop an image onto the chat window

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Hi @blake41, Currently, the vision feature is experimental and only supports local or OpenAI models. See here: https://github.com/orgs/janhq/discussions/3524

Sorry for the inconvenience!
