### ISSUE TITLE
bug: Model `Groq Llama 3.1 70b Versatile` is deprecated - remove it as an option

### ISSUE THREAD

**Issue by shanecandoit** [janhq/jan#4244]
### Jan version

0.5.11

### Describe the Bug

I can choose the model "Groq Llama 3.1 70b Versatile".
When I try to chat it, it complains it is deprecated.
When I look at groqs site: https://console.groq.com/docs/models it says that model is deprecated.

### Steps to Reproduce

1. Click to open the right pane (this button looke like a right arrow in a box)
2. Click Model tab
3. Set your api key for groq
4. choose the model "Groq Llama 3.1 70b Versatile"
5. try to send it a message

using model "Groq Llama 3.2 90b Text Preview" works fine.
local models also work fine.

btw i searched issues for "3.1 70b" and deprecate and didn't find anything, not sure how good the search is.

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Let's remove this model:

![Screenshot 2024-12-09 at 2 46 51 PM](https://github.com/user-attachments/assets/793c6dc0-1e7f-4f14-8511-f9762b3e73dc)

**Comment by louis-jan** [comment]
It's removed, in case you have it persisted from previous version, please kindly remove after updated

**Comment by imtuyethan** [comment]
<img width="1136" alt="Screenshot 2024-12-18 at 9 45 31 AM" src="https://github.com/user-attachments/assets/db08ab8c-2ae7-42d0-a845-240ac215caad" />
