### ISSUE TITLE
bug: Crash when Install on MacOS Sequoia

### ISSUE THREAD

**Issue by aldinokemal** [janhq/jan#4245]
### Jan version

v0.5.11

### Describe the Bug

I had no problems with the previous version, but when I attempted to update, I experienced a crash as shown in the photo below.

### Steps to Reproduce

Install v0.5.11

### Screenshots / Logs

<img width="283" alt="Screenshot 2024-12-07 at 6 13 25 PM" src="https://github.com/user-attachments/assets/b15bcc08-df64-46eb-84d4-375598d86e79">

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by hiento09** [comment]
Hi @aldinokemal , could you share more information about your macOS version in the 'About This Mac' section like this? I'm unable to reproduce the issue on my local machine. Thank you!

<img width="281" alt="image" src="https://github.com/user-attachments/assets/11e47bec-c704-481c-bd7f-ddee471f6363">

**Comment by aldinokemal** [comment]
Hi @hiento09 
This is my macos detail
<img width="348" alt="image" src="https://github.com/user-attachments/assets/8d4f463c-15fd-4feb-ad09-fc38e65ace4c">

**Comment by aldinokemal** [comment]
Hey @hiento09, that's weird. After restarting my device, I was able to upgrade to 0.5.11. Sorry for any confusion!

**Comment by hiento09** [comment]
No problem, thank you @aldinokemal !
