### ISSUE TITLE
bug: Markdown component crashes when rendering specific code block

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#4247]
### Jan version

0.5.11

#### Issue Description
The Markdown component crashes when attempting to render a specific code block. This results in the application throwing an error and becoming unresponsive.

#### Steps to Reproduce
1. Pass the following markdown content to the chat input and send:

```php

<?php
include "config.php";
// Connecting to the database
try {
    $dsn = "pgsql:host={$dbConfig['host']};port={$dbConfig['port']};dbname={$dbConfig['dbname']}";
} catch (PDOException $e) {
    die("Database connection error: " . $e->getMessage());
}

// Function to find email addresses
function findEmails($content) {
    $emails = [];
    
    // Search for emails in mailto links
    preg_match_all('/<a[^>]+href="mailto:([^"]+)"[^>]*>/i', $content, $mailto_matches);
    if (!empty($mailto_matches[1])) {
        $emails = array_merge($emails, $mailto_matches[1]);
    }
    
    // Search for emails in text
    preg_match_all('/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/', $content, $text_matches);
    if (!empty($text_matches[0])) {
        $emails = array_merge($emails, $text_matches[0]);
    }
    
    // Remove duplicates and invalid emails
    $emails = array_unique($emails);
    $validated_emails = array_filter($emails, function($email) {
        return filter_var($email, FILTER_VALIDATE_EMAIL);
    });
    
    return implode(', ', $validated_emails);
}
echo "Processing completed\n";
?>
   ```

3. Observe the application behavior.

#### Expected Behavior
The Markdown component should render the code block properly without any crashes.

#### Actual Behavior
The application crashes with the following error:
```
[failed to execute `createElement` on `Document`.]
```
---

https://discord.com/channels/1107178041848909847/1315534163121537074

### Screenshots / Logs

<img width="1582" alt="image" src="https://github.com/user-attachments/assets/787682bb-6ee8-4670-9de0-2967132ff58e">

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
https://github.com/user-attachments/assets/24ef0a88-8839-4d30-9d01-8b2cceea11c2
