### ISSUE TITLE
bug: If I scroll up it keeps autoscrolling so I have to fight with it or wait for it to finish

### ISSUE THREAD

**Issue by 55Cancri** [janhq/jan#4253]
### Jan version

v0.5.11

### Describe the Bug

If I scroll up, it should stop autoscrolling during the stream. if I scroll back down, it should continue autoscrolling again. Here's an example https://www.youtube.com/watch?v=GIIuG5_kyow

### What is your OS?

- [x] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Yes this should be the correct way @urmauur

**Comment by imtuyethan** [comment]
Solved.
