### ISSUE TITLE
enhancement: Token speed should be shown at the bottom of the response

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#4258]
## Goal 

- We should persist token/speed per message
- We should capture what hardware, model settings etc that we used, that led to that tok/s
- This is important for our hardware benchmarks in the future

## Problem Statement

Currently, the token speed is shown at the top of the response area. This creates a usability issue when responses are long because:
- Users have to scroll back up to see the generation speed
- Can't monitor performance while reading the bottom of a long response
- Token speed info gets hidden as more text is generated

## Design
Move the token speed indicator to the bottom of the response area.

Figma link: https://www.figma.com/design/DYfpMhf8qiSReKvYooBgDV/Jan-App-(3rd-version)?node-id=672-20055&t=jDIGxWIJHozkLIAG-4

![Screenshot 2024-12-11 at 5 32 43 PM](https://github.com/user-attachments/assets/787d3e03-d0b0-4b67-ba90-4a68ee479a13)

**Comment by imtuyethan** [comment]
@urmauur Sorry Faisal, we changed the scope of this ticket yesterday, we want to persist the token/speed per message too:

<img width="773" alt="Screenshot 2024-12-17 at 9 35 00 AM" src="https://github.com/user-attachments/assets/017aee78-2860-4f9e-b31b-930e1a0849e4" />

**Comment by louis-jan** [comment]
> @urmauur Sorry Faisal, we changed the scope of this ticket yesterday, we want to persist the token/speed per message too:
> 
> <img alt="Screenshot 2024-12-17 at 9 35 00 AM" width="773" src="https://private-user-images.githubusercontent.com/89722390/396329818-017aee78-2860-4f9e-b31b-930e1a0849e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0Mjk0OTMsIm5iZiI6MTczNDQyOTE5MywicGF0aCI6Ii84OTcyMjM5MC8zOTYzMjk4MTgtMDE3YWVlNzgtMjg2MC00ZjllLWIzMWItOTMwZTFhMDg0OWU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDA5NTMxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjZDY5ZDgyZTNiZWQ0NzBkMWY4M2Q5MTMwZmNlODQ5OTExZjBkOWFhOTQ0MDk4N2IxYWQyOTBiMDQwNWIxYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QWwECXE9AYldBczQgzzRcyfMWft9tIDJDjHsDju-6dI">

WUT, that is not an OpenAI message metadata

**Comment by imtuyethan** [comment]
https://discord.com/channels/1107178041848909847/1239846009258119178/1318525447771918397

**Comment by urmauur** [comment]
Based on internal discussions, we will not implement RN persist token/speed per message. The scope of this ticket is limited to the UI level only @imtuyethan @dan-homebrew cc @louis-jan
