### ISSUE TITLE
bug: Cortext API not working (or instructions are unclear)

### ISSUE THREAD

**Issue by lineality** [janhq/jan#4264]
### Jan version

 Jan v0.5.11

### Describe the Bug

The JAN system with GPU is blazing fast!!! And a whole 12gb gguf model will run in 13gb CUDA... astounding and great.
(I've tried but can't get this performance directly out of llama.cpp (though llama.cpp can run larger models and just put a few layers into GPU).

But...when trying to get this performance via ~endpoint-api through cortext-api, I can't get any connection to the /v1/chat/completions etc. endpoint with post requests with curl or with python requests. I see the ping from curl, but it does nothing (no model thinking, no model output, instant empty response). no errors. 

### Steps to Reproduce

Follow the cortext api instructions.

### Screenshots / Logs

Will try to add these later (I know they are important)

SPecs:

# System Details Report
---

## Report details
- **Date generated:**                              2024-12-11 20:36:49

## Hardware Information:
- **Hardware Model:**                              Dell Inc. Precision 7780
- **Memory:**                                      128.0 GiB
- **Processor:**                                   13th Gen Intel® Core™ i7-13850HX × 28
- **Graphics:**                                    Intel® Graphics (RPL-S)
- **Graphics 1:**                                  NVIDIA RTX 3500 Ada Generation Laptop GPU
- **Disk Capacity:**                               1.0 TB

## Software Information:
- **Firmware Version:**                            1.17.0
- **OS Name:**                                     Ubuntu 24.04.1 LTS
- **OS Build:**                                    (null)
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.8.0-50-generic

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by lineality** [comment]
e.g. curl -X 'POST' \
  'http://127.0.0.1:1337/v1/chat/completions' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "messages": [
    {
      "content": "You are a helpful assistant.",
      "role": "system"
    },
    {
      "content": "Hello!",
      "role": "user"
    }
  ],
  "model": "tinyllama-1.1b",
  "stream": true,
  "max_tokens": 2048,
  "stop": [
    "hello"
  ],
  "frequency_penalty": 0,
  "presence_penalty": 0,
  "temperature": 0.7,
  "top_p": 0.95
}'

(and yes I installed and tested tinyllama to use this given test example to test with)

**Comment by lineality** [comment]
```
Server Logs
Open LogsClear
2024-12-11T02:24:37.014Z [SERVER]::Debug: Starting JAN API server...

2024-12-11T02:24:47.151Z [SERVER]::Debug: JAN API listening at: http://127.0.0.1:1337

2024-12-11T02:24:54.744Z [SERVER]::{"reqId":"req-1","res":{},"req":{"method":"POST","url":"/v1/chat/completions","hostname":"127.0.0.1:1337"},"msg":"incoming request"}

2024-12-11T02:24:54.763Z [SERVER]::{"reqId":"req-1","res":{"statusCode":200},"req":{},"msg":"request completed","responseTime":18.40278199315071}

2024-12-11T02:26:06.170Z [SERVER]::Debug: Server stopped

2024-12-11T02:38:26.552Z [SERVER]::Debug: Server stopped
```

**Comment by lineality** [comment]
[logs.zip](https://github.com/user-attachments/files/18104379/logs.zip)

**Comment by lineality** [comment]
Though it is kind of backwards, getting a working cli/py api-interface (rest-endpoint-api or otherwise) would be....so useful for making architectures. The frontend of Jan may be the most fashionable selling point for low-code-no-code folks, but the jan's backend for running models (if you can really do ONNX et al) is maybe the best in town. ...but how to get at that backend... (directly use Nitro?)  I don't know anything else that can put a whole 10gb gguf model into a 10gb cuda gpu and run it at blinding speed... (with the CPU just twiddling thumbs doing nothing). And when phones have 8gb gpu (in a few years) and you can run an 8gb gguf on edge that fast.... that changes the game.

**Comment by imtuyethan** [comment]
Thanks @lineality We'll take a look

**Comment by louis-jan** [comment]
Hi @lineality, In the request, there's a stop word "hello" that means the response will stop immediately if it contains that word and likely to return nothing.
