### ISSUE TITLE
bug: Duplicate Event Trigger on Enter Key with CJK Composition in Chat Input

### ISSUE THREAD

**Issue by cuhong** [janhq/jan#4267]
### Jan version

0.5.11

### Describe the Bug

When entering text using CJK (Chinese, Japanese, Korean) input methods in the chat input field, pressing the Enter key triggers events twice. This occurs because the event is fired both for the finalized composed string and for the composing character. This results in duplicate submissions or unintended behavior in the application.

### Steps to Reproduce

1. Focus on the chat input field.
2. Use a CJK input method (such as Pinyin for Chinese, Hiragana for Japanese, or 2-Set Korean for Korean).
3. Start composing a CJK character in the input field.
4. While the character is still composing, press the Enter key.
5. Observe that the event is triggered twice: once for the composed character and once for the composition process.

### Screenshots / Logs

![image](https://github.com/user-attachments/assets/e4f1d2b3-f775-4efa-91ec-11b3b1f20d65)

"The input '안녕하세요' should be entered as a single query, but it is split into '안녕하세' and '요'."

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
Thanks for reporting @cuhong We'll take a look

**Comment by imtuyethan** [comment]
Can't reproduce with `0.5.11-808`
