### ISSUE TITLE
No "no GPU offload" option? 

### ISSUE THREAD

**Issue by Xpolo29** [janhq/jan#4271]
### Jan version

0.5.7

### Describe the Bug

Hey nice work! I just wanted to know how to load a model completely on RAM since the gpu offload option has 1 layer as minimum, but for igpu vram and ram is fused and offloading actually decrease inference speed (at least in my case)

Could you change the minimum to 0 please? Or maybe that's already possible? Thanks! 

### Steps to Reproduce

Load a model
Go to parameters side panel on the right
Searfh for gpu offload slider
Try to put 0 

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by imtuyethan** [comment]
@Xpolo29 Thanks for creating the ticket! If you don't want to utilize your GPU, turn it off in `Advanced Settings` > Hardware section.
