### ISSUE TITLE
bug: chat and stop

### ISSUE THREAD

**Issue by kalle07** [janhq/jan#4286]
### Jan version

0.5.11

### Describe the Bug

i choose a good GGUF model 
i start a chat all is fine
but if the answer is too long i press STOP
so the text output is stop
BUT the GPU is used until the textoutput (maybe in background) has ended sometimes one minute with a RTX4060

### What is your OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

**Comment by imtuyethan** [comment]
We have never supported it, here's the tracking ticket: https://github.com/janhq/jan/issues/2842

**Comment by kalle07** [comment]
you can see it in GPU-Z a very VERY use ful tool 
i repeat that error with 10 models !

**Comment by louis-jan** [comment]
Related issue https://github.com/janhq/jan/issues/4202
