### ISSUE TITLE
bug: [DESCRIPTION]

### ISSUE THREAD

**Issue by testaccount1432** [janhq/jan#4340]
### Jan version

-

### Describe the Bug

{
  "messages": [
    {
      "role": "system",
      "content": "you are a helpful assistant",
      "name": "assistant"
    },
    {
      "role": "user",
      "content": "tell me a joke",
      "name": "user"
    },
    {
      "role": "string",
      "content": "string",
      "name": "string",
      "refusal": "string",
      "audio": {
        "id": "string"
      },
      "tool_calls": [
        {
          "id": "string",
          "type": "string",
          "function": {
            "name": "string",
            "arguments": "string"
          }
        }
      ]
    },
    {
      "role": "string",
      "content": "string",
      "tool_call_id": "string"
    }
  ],
  "model": "llama3.2-3b-instruct",
  "stream": false,
  "max_tokens": 4096,
  "max_completion_tokens": 0,
  "stop": [
    "End"
  ],
  "frequency_penalty": 0.2,
  "presence_penalty": 0.6,
  "temperature": 0.8,
  "top_p": 0.95,
  "modalities": [
    "text"
  ],
  "audio": {
    "voice": "string",
    "format": "mp3"
  },
  "store": false,
  "metadata": {
    "type": "conversation"
  },
  "logit_bias": {
    "15496": -100,
    "51561": -100
  },
  "logprobs": false,
  "top_logprobs": 0,
  "n": 1,
  "response_format": {
    "type": "text"
  },
  "seed": 123,
  "service_tier": "string",
  "stream_options": null,
  "tools": [
    {
      "type": "function",
      "function": {
        "description": "string",
        "name": "qcim4Xn1dSo-yTNpxxTFDus56ZfhaX8FCuPyAyVO3zWT04VsC5FmzmTK1",
        "parameters": {},
        "strict": false
      }
    }
  ],
  "tool_choice": "none",
  "parallel_tool_calls": true,
  "user": "string",
  "dynatemp_range": 0,
  "dynatemp_exponent": 0,
  "top_k": 0,
  "min_p": 0,
  "tfs_z": 0,
  "typ_p": 0,
  "repeat_last_n": 0,
  "repeat_penalty": 0,
  "mirostat": true,
  "mirostat_tau": 0,
  "mirostat_eta": 0,
  "penalize_nl": true,
  "ignore_eos": true,
  "n_probs": 0,
  "min_keep": 0
}

### Steps to Reproduce

-

### Screenshots / Logs

-

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [ ] Linux

**Comment by testaccount1432** [comment]
[response_1735210001852.json](https://github.com/user-attachments/files/18252172/response_1735210001852.json)

**Comment by imtuyethan** [comment]
{
  "messages": [
    {
      "role": "system",
      "content": "you are a helpful assistant",
      "name": "assistant"
    },
    {
      "role": "user",
      "content": "tell me a joke",
      "name": "user"
    }
  ],
  "model": "llama3.2-1b-instruct",
  "stream": true,
  "max_tokens": 4096,
  "max_completion_tokens": 0,
  "stop": [
    "<|eot_id|>"
  ],
  "frequency_penalty": 0.2,
  "presence_penalty": 0.6,
  "temperature": 0.8,
  "top_p": 0.95
  
}
