### ISSUE TITLE
right mouse button does not work

### ISSUE THREAD

**Issue by FranBar1966** [janhq/jan#4346]
### Jan version

0.5.11

### Describe the Bug

The right mouse button does not work, when clicking nothing happens, I have tested in version 5.11 and 5.12 beta. I'm using Linux Mint with 6.11.10-1-liquorix-amd64 kernel

### What is your OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

**Comment by FranBar1966** [comment]
Sorry I forgot to say that I'm using X11 KDE Plasma 5.27.11, maybe it's relevant.

**Comment by imtuyethan** [comment]
Thanks @FranBar1966, this is a feature request, it is scheduled here: https://github.com/janhq/jan/issues/1101
