### ISSUE TITLE
bug: Switch between conversations, same messages history

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#435]
## Problem 

After awhile, switching between conversations stop working

https://github.com/janhq/jan/assets/133622055/14e2a54e-a050-4698-98b6-24e8535c2bde

**Comment by louis-jan** [comment]
Reproduce: 
- Open app 
- Go to conversations, select any conversation
- Go back then go to My Models, stop the model, start again
- Go back then go to conversations again, its broken

**Comment by louis-jan** [comment]
First attempt:
- For now we will not constraint what conversations belong to which model, all conversations will just use the current active model. 
cc @namchuai

**Comment by namchuai** [comment]
Fixed in #458
