### ISSUE TITLE
bug: [0.5.12] Download failed - Failed to fetch - Can not download any model

### ISSUE THREAD

**Issue by melgherbi** [janhq/jan#4368]
### Jan version

0.5.12

### Describe the Bug

I installed the app on my mac, tried to download a model but I got every time the error : "Download failed. Failed to fetch."

Error happen on all models 

### Steps to Reproduce

1. Download the DMG for mac osx 
2. Install it and run well
3. tried to download at least the first model llama 3.2 1B Instruct Q8
4. Got error  "Download failed. Failed to fetch."
5. Tried other versions of llama
6. Got every time error "Download failed. Failed to fetch."
7. same error for the others models when trying to download

### What is your OS?

- [X] MacOS
- [ ] Windows
- [ ] Linux

**Comment by qlkv** [comment]
I got the same for literally anything I do in Jan after the latest update yesterday. I regret I updated the version.

**Comment by imtuyethan** [comment]
Thanks for reporting @qlkv @melgherbi Can you send us logs so we can investigate further?

**Comment by melgherbi** [comment]
Please find my logs @imtuyethan 
[app.log](https://github.com/user-attachments/files/18280276/app.log)


Meanwhile, I tried yesterday, on another mac M series, with the 0.5.11 version of Jan, and all worked fine.

**Comment by imtuyethan** [comment]
Thanks @melgherbi we're actively triaging here: https://discord.com/channels/1107178041848909847/1314078497441841182

**Comment by louis-jan** [comment]
> Please find my logs @imtuyethan [app.log](https://github.com/user-attachments/files/18280276/app.log)
> 
> Meanwhile, I tried yesterday, on another mac M series, with the 0.5.11 version of Jan, and all worked fine.

Ops! @melgherbi, Jan supports macOS 12 or higher only. You are trying to run on a MacOS 10.x right? So it should be the same on both versions.

**Comment by louis-jan** [comment]
Hi @qlkv, could you please share the app logs? This will help us investigate the issue and fix it if possible.

**Comment by melgherbi** [comment]
Thanks @louis-jan 

Indeed, on m2 running sequoia, it's running flawlessly.
