### ISSUE TITLE
perf: jan-data-connector-agent SEVERE log

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#44]
What is a data-connector-agent in the first place?
Should we name this service better for users?

Separately: 
I know we haven't enabled otel, so maybe we can do something to disable this log. It makes for a very spammy install experience.

Can we: 
- turn if off?
- disable the log?
- lower the log severity?
TBD

```sh
jan-data-connector-agent-1  | {"timestamp":"2023-09-05T05:50:26.171Z","sequence":128,"loggerClassName":"org.jboss.logmanager.Logger","loggerName":"io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter","level":"SEVERE","message":"Failed to export spans. The request could not be executed. Full error message: Failed to connect to localhost/127.0.0.1:4317","threadName":"OkHttp http://localhost:4317/...","threadId":84,"mdc":{},"ndc":"","hostName":"8ca47fbf537b","processName":"super-connector.jar","processId":1}

```

**Comment by louis-jan** [comment]
This is a known bug, observing
https://github.com/hasura/graphql-engine/issues/9735
