### ISSUE TITLE
Documentation: Jan's system files and folders

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#443]
## Objective

- Document system folders used by Jan
- Allow users and community to "hard reset" Jan in case we have a corrupted install in the future

## Todos

- [ ] System Folders used by Jan
- [ ] "Hard Uninstall" instructions (e.g. delete files)
- [ ] Windows
- [ ] Mac
- [ ] Linux

## Resources

Note
**~/Library/Application Support**
<img width="875" alt="image" src="https://github.com/janhq/jan/assets/101145494/2d8e7907-e69a-440c-8d8a-194ad4785ae4">

**~/Library/caches**
- `jan-electron-updater`
- `jan.ai.app`
- `jan.ai.app.ShipIt`

<img width="709" alt="image" src="https://github.com/janhq/jan/assets/101145494/dc2f6479-6840-4473-9701-7bea8574d3dc">

**Comment by 0xSage** [comment]
closing, done
