### ISSUE TITLE
bug: Docusaurus style bug

### ISSUE THREAD

**Issue by vuonghoainam** [janhq/jan#460]
**Describe the bug**
- We are working on #450 for next release, however the rendered markdown on docusaurus seems buggy. 

**To Reproduce**
1.  `cd docs`
2. Click on `docs/docs/docs/overview/architecture.md` and see the preview (working fine)
3. `yarn start` and go to [Localhost Docusaurus architecture overview](http://localhost:3001/docs/overview/architecture)

**Expected behavior**
- Render perfectly fine on Docusaurus

**Screenshots**
  - Markdown preview on VScode
![Screenshot 2023-10-26 at 10 28 22 AM](https://github.com/janhq/jan/assets/22463238/7e9996ea-c22f-4adc-b730-32c03ad2c933)
  - Markdown preview on Docusaurus (bug)
<img width="974" alt="image" src="https://github.com/janhq/jan/assets/22463238/5b2321ed-35f5-46f0-b3ea-5dd5f2ae08f6">

**Desktop :**
 - OS: Mac
 - Browser: chrome
 - Version: 118.0 (arm64)

**Additional context**
None

**Comment by 0xSage** [comment]
fixed, thank you @urmauur
