### ISSUE TITLE
perf: indicate when all services are ready, print the ports and services

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#47]
When services are ready, signal to the user that Jan is ready to use. 

Log to stdout: 
- 👋 Jan is ready!
- This table from README

Service | URL | Credentials
-- | -- | --
Keycloak | http://localhost:8088 | Admin credentials are set via the environment variables KEYCLOAK_ADMIN and KEYCLOAK_ADMIN_PASSWORD
app-backend (hasura) | http://localhost:8080 | Admin credentials are set via the environment variables HASURA_GRAPHQL_ADMIN_SECRET in file conf/sample.env_app-backend
web-client | http://localhost:3000 | Users are signed up to keycloak, default created user is set via conf/keycloak_conf/example-realm.json on keycloak with username: username, password: password
llm service | http://localhost:8000 |  
sd service | http://localhost:8001 |

**Comment by louis-jan** [comment]
I think this is when a bash script should take its place instead.

**Comment by louis-jan** [comment]
dep: #30
