### ISSUE TITLE
bug: Cannot start the model 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#476]
- I clicked on “Start model” **llama-2-13b-chat.gguf.q4_0.binv1.0.0**
- Returned to chat → Switched model
- Then returned to my models, saw **openhermes-2-mistral-7b.Q5_K_M.ggufv1.0.0** is still active

https://github.com/janhq/jan/assets/89722390/c2a45427-781e-4991-be25-2b01525cc4c6

**Comment by louis-jan** [comment]
this is expected
