### ISSUE TITLE
bug: Model names are different in some places

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#477]
**In confirmation pop-up it shows:** 
<img width="579" alt="Screenshot 2023-10-27 at 10 12 58 AM" src="https://github.com/janhq/jan/assets/89722390/d6d3abe3-e1ec-4741-a147-782f925ab096">

**Meanwhile the models i have are:**
<img width="1249" alt="Screenshot 2023-10-27 at 10 13 13 AM" src="https://github.com/janhq/jan/assets/89722390/94b8375a-bc8b-4881-9675-a9d5f8f02d1a">

**Suggestion from Nicole:** 
Don't immediately ask users to change models when users switch conversations.

**Comment by louis-jan** [comment]
Its addressed by @namchuai

**Comment by namchuai** [comment]
should we closed this issue? @louis-jan
