### ISSUE TITLE
bug: Cannot toggle off some plugins

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#479]
Cannot toggle off some plugins & some plugins even turn back on if I toggle other plugins off: 
https://github.com/janhq/jan/assets/89722390/819fe555-dc0f-406c-9c08-0dc594e20282

**Suggestion:** 
Disable the plugins that cannot be turned off.

**Comment by louis-jan** [comment]
I will fix these, will add a warning or so (user definitely will be still able to uninstall)
