### ISSUE TITLE
bug: Cannot delete conversation

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#483]
Jan version: 0.2.3
Device: Mac Air M2 16GB

**What i did:** 
- Tried to delete all conversations
- It directed me back to the home screen after I deleted all
- Clicked on 'Chat' and still saw some conversations left

https://github.com/janhq/jan/assets/89722390/c23e85e6-9371-4ca3-b1b7-1c30ba5e61ab

**Comment by imtuyethan** [comment]
Still happens with version 0.3.0

**Comment by namchuai** [comment]
This issue is happening with pouchdb. We are going to replacing it. I will move this to finish after we finish migrating to file-based approach
