### ISSUE TITLE
bug: download new version should show in status bar

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#486]
**Describe the bug**
Users should get visual feedback that Jan app is updating

**To Reproduce**
1. Restart app (after new app release)
2. Download new version
<img width="513" alt="image" src="https://github.com/janhq/jan/assets/69952136/cc0c27e1-61c2-4749-a5ec-fdd24d0d81fa">
3. Expect status bar to show downloading
<img width="855" alt="image" src="https://github.com/janhq/jan/assets/69952136/032d78c9-ef52-4845-a9ed-f97f99b516c6">
4. Nothing looks to be happening. Are we downloading in background?

**Expected behavior**
Expect to show in status bar. We used to show this?
<img width="855" alt="image" src="https://github.com/janhq/jan/assets/69952136/e2c57f27-136d-4df4-9aed-c1248d9a53f9">

**Screenshots**

**Desktop (please complete the following information):**
 - OS: mac m1
- version: upgrading from 0.2.3

**Additional context**

**Comment by louis-jan** [comment]
Fixed

![Image](https://github.com/janhq/jan/assets/133622055/a0828c29-8682-466c-bc27-b4138d480eb8)
![Image](https://github.com/janhq/jan/assets/133622055/72c9647c-f636-4cc2-831e-272e7ee4d6d9)
