### ISSUE TITLE
feat: Desktop App Analytics

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#493]
## Todos

- Figure out the Funnel @tikikun 

## Todos

- [ ] Designs
- [ ] Implementation

**Problem**
- At Jan we need to measure some key metrics - @dan-jan pls add (e.g: Number of installation, Number of uninstallation, Time user use Jan everyday)
- This feature needs opt-in which means user can disable it, but enable by default with clear notice

**Success Criteria**
- Integration as Core plugin to track, have option to disable this
- Dashboard on Jan that updates everyday on Eng call
- Ability to track user installation with sources (e.g From Meetup HCMC on Oct 27)

**Additional context**
None

## Copied over from: 

The idea is: 
- We can plug analytics-extension in to define analytics module
- User can opt-out via UI
- Track important actions / features in app

**Comment by dan-jan** [comment]
Merging https://github.com/janhq/internal/issues/11 into this issue

## Objective

- Analytics that is protects our user's privacy, yet provides us enough DAU/MAU, Retention data to track traction and make good product decisions
- Make decisions on what data we should collect
- Should ideally be in a system module (opt-in)
- Needs UX flow to allow user to opt-in
- See https://data.syncthing.net for inspiration
- Should our Analytics dashboard be public, like Syncthing?

Should be separate from Crash Reports (i.e. default on).

**Comment by imtuyethan** [comment]
After syncing up with @tikikun, we got:
- Jan tracking dashboard: https://app.posthog.com/shared/piUcjWGI7AIcKA45_pECj_SMfNFATg
- Nitro track dashboard: https://app.posthog.com/shared/piUcjWGI7AIcKA45_pECj_SMfNFATg

Further steps:
- Add custom tracking event to download button on Jan.ai (right now, we can only auto-capture the big button, cannot track which devices they download) @urmauur 
- @tikikun @hiento09 will improve SEO 

Tracking plan for Jan app (cc @urmauur for early research)
- Active users
- Locations
- Version usage
- Feature Usage
- Platform usage

**Comment by imtuyethan** [comment]
Sub-ticket for @urmauur: https://github.com/janhq/jan/issues/727

**Comment by imtuyethan** [comment]
Some extra information
[

![Image](https://github.com/janhq/jan/assets/89722390/4f487d11-6995-4f7d-a8dd-f3f62c2d16a6)

](url)
https://posthog.com/questions/can-posthog-cross-desktop-in-app-events-to-web-based-user-sessions-with-utm-parameters-assigned

**Comment by imtuyethan** [comment]
Duplicate ticket: https://github.com/janhq/internal/issues/68

**Comment by imtuyethan** [comment]
for @namchuai $ @louis-jan to implement posthog to Jan app

**Comment by imtuyethan** [comment]
As we already implemented posthog to desktop app, close this.

**Comment by 0xSage** [comment]
Deprecating this issue in favor of #1232 , as we dont intend to track any identifying or behavioral metrics going forward
