### ISSUE TITLE
Profile & optimize CI test time consuming

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#505]
## Problem
- CI tests now build for distribution, take quite long to build (build for publishing, all packages type such as dmg, pkg, zip...), build for "dir" should work (only app file, ready to test)
- Disable auto update since we will build for "dir" eventually, it will fail the CI
- Extract plugins to app data before loading app

**Comment by hiento09** [comment]
resolved in https://github.com/janhq/jan/pull/521
