### ISSUE TITLE
bug: Chat UI is not consistent 

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#506]
**Describe the bug**
Chat UI is not consistent.

**To Reproduce**
1. Start 2-3 new conversations
2. Chat using different models in these conversations
4. See UI bug

**Expected behavior**
UI should be consistent.

**Screenshots**
- Recording: 
https://github.com/janhq/jan/assets/89722390/133fa652-2e14-4e2a-9dde-3b8b5444f60a
- Screenshots
<img width="1190" alt="Screenshot 2023-10-31 at 6 02 59 PM" src="https://github.com/janhq/jan/assets/89722390/1ad19c1d-79d9-46f6-b7d0-aba8c054690a">
<img width="1194" alt="Screenshot 2023-10-31 at 6 03 18 PM" src="https://github.com/janhq/jan/assets/89722390/2c2388bd-d694-4f25-9973-5fdcb54e9f0e">

**Desktop:**
 - Mac Air M2 16GB
 - Version 0.3.0

**Comment by urmauur** [comment]
@louis-jan @imtuyethan i'll ignore the issue on border bellow of text message first, bc i can't reproduce and after @imtuyethan test again weird we are good, lets keep note issue on border bellow text message, until we can reproduce
