### ISSUE TITLE
Video for Nvidia LLM Day

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#519]
_Do something simple, like adapt a video template. If we can build up the competency to do this (i.e. videos), even better._ 
_In general, a 10-20s video would do, we don't have that many features._

**Main points:** 
Personal AI that runs on your computer
Private and offline, your data never leaves your machine
No subscription fees, the AI runs on your computer
Extendable via App and plugin framework

**Ashley's bookmarks:**
https://motionarray.com/after-effects-templates/clean-website-promo-1178904/ (easy to input content)
https://motionarray.com/after-effects-templates/windows-opener-1256984/ (this one could show off 'characters' in a broader sense -> many personal AI in 1 folder etc...)
https://motionarray.com/after-effects-templates/soft-cloth-website-promo-1133960/ (can use this one if we want to downplay the UI a bit and focus on the big picture content)

**Daniel's bookmarks:**
https://motionarray.com/after-effects-templates/stylish-website-promo-85477
https://motionarray.com/after-effects-templates/fantasy-device-mockup-kit-1161315
https://motionarray.com/after-effects-templates/laptop-presentation-149187
https://motionarray.com/after-effects-templates/animated-laptop-mockup-584261
https://motionarray.com/after-effects-templates/stylish-website-promo-v3-930614

Dan: Btw, you will notice in the ones I bookmarked, there is the notion of Hardware + Software. 
Being able to run AI on our own computers is a key product feature for us, useful to emphasize that (people will then naturally run it on cloud, etc)

**Comment by dan-jan** [comment]
Migrating issue to https://github.com/janhq/chores/issues/1
