### ISSUE TITLE
feat: Jan.ai download button should change based on OS

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#543]
## Issue

- https://jan.ai does not change based on operating system
- I visited it on Windows and it still showed the Mac download button

<img width="1067" alt="image" src="https://github.com/janhq/jan/assets/101145494/04daf7ca-1ada-4fad-83d9-4da3f76c8d80">

## Task

- [ ] Homepage is in `/docs/src/pages/index.js`
- [ ] Need to switch button based on OS

**Comment by Vikram-2004** [comment]
Sir can you review my changes. This is my firt time contributing.

**Comment by louis-jan** [comment]
Fixed with #551. New issue tracked here #568
