### ISSUE TITLE
docs: Update Social OG image for https://jan.ai

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#547]
## Tasks

- [ ] Update social og:image with updated tagline
- [ ] Bugfix why Discord shows very outdated image (see below)

## Discord Bug

Discord shows a very old OG image: 
<img width="491" alt="image" src="https://github.com/janhq/jan/assets/101145494/52009e55-5e3d-4268-a7ce-2b1fcc5aadc2">

However, Facebook Debugger shows the updated image:
<img width="1146" alt="image" src="https://github.com/janhq/jan/assets/101145494/fdf1a3ce-b054-48d1-8517-276a17bdcfa5">

**Comment by imtuyethan** [comment]
Will update along with issue #26 https://github.com/janhq/internal/issues/26

**Comment by imtuyethan** [comment]
It's discord cache
