### ISSUE TITLE
[feat] Plugin class - register settings

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#556]
## Problem
- Plugin now does not able to register any settings (e.g. API Key)
- The previous implementation is just a hack around plugin function registering

## Action Items
- Plugin base class define register function (JanPlugin)
- From inherited plugin class will just need to: 
```ts
class PluginSample extends JanPlugin {
    onload {
       this.registerSetting({})
   }
}
```

## Related work
- Plugin export as class instead of function

**Comment by louis-jan** [comment]
To discuss: 
- Should it be App preferences instead? 

e.g. 
- OpenAI Plugin => App register setting UIs -> get input -> create plugin instance? (constructor)

**Comment by 0xSage** [comment]
@louis-jan is this issue still relevant?

Note: 
- Settings is not a module, its more a combination of what is declared across modules, no? e.g. in the `model.json` `assistant.json` files
- Some settings should customizable within each `thread` by the end user

**Comment by louis-jan** [comment]
Its no longer relevant @0xSage. Yes settings is not available for modules, only for assistants / apps level
