### ISSUE TITLE
bug: Jan web detects my Apple Silicon M2 as Intel

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#568]
**Describe the bug**
- I'm seeing Intel download option as default when accessing to Jan.ai website even using Apple Silicon M 

**Screenshots**
<img width="550" alt="Screenshot 2023-11-08 at 12 12 28" src="https://github.com/janhq/jan/assets/133622055/c323f98b-e1ec-4fd9-9400-f87a83561a85">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Browser & Safari

Related fix: #551

**Comment by louis-jan** [comment]
cc @Vikram-2004

**Comment by Vikram-2004** [comment]
I will try to solve this issue as soon as possibe..

**Comment by dan-jan** [comment]
I encountered this issue as well. 

![Image](https://github.com/janhq/jan/assets/101145494/fc5d06be-e7ca-4608-8dc3-b3329dfce58c)

PS: Thanks @Vikram-2004 for your contribution!!

**Comment by louis-jan** [comment]
Fixed

**Comment by louis-jan** [comment]
Still exist on prod, will check with the deployment status

**Comment by 0xSage** [comment]
> Still exist on prod, will check with the deployment status

Works for me though (both chrome and safari). @louis-jan do you need to clear cache?

**Comment by louis-jan** [comment]
yeah I just got confirmed from Faisal, @0xSage. It does not work on Safari, and will jump to Intel option after a couple of seconds.

**Comment by louis-jan** [comment]
Anw, it's a very weird issue and it seems like Apple should address this instead of us. Let's close this issue 🙏
