### ISSUE TITLE
bug: Cannot use keyboard except for shortcut button

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#583]
**Describe the bug**
I cannot use my keyboard after hitting shortcut button.

https://github.com/janhq/jan/assets/89722390/4933c3db-ef75-4cf4-b499-bd217861c153

https://github.com/janhq/jan/assets/89722390/df887b3b-6a13-4ac4-810d-4cc5ee9eec72

**To Reproduce**
1. Open Jan
2. Type "command + E" to open My Models
3. Continue to hit the "down button" on the keyboard to choose a model 

or

1. Open Jan
2. Type "command + J" to open Search
3. Continue to hit the "down button" on the keyboard to choose one of the suggestions

**Expected behavior**
I should be able to continue using keyboard once I use the keyboard shortcut.

**Desktop (please complete the following information):**
 - Mac Air 16GB Ventura
 - Version Jan 0.3.1

**Comment by urmauur** [comment]
confirm with @imtuyethan work well on production
