### ISSUE TITLE
feat: when i close Jan, it should still be active on my Macbook app bar

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#584]
**Describe the bug**
When I close Jan, it should still be active on my MacBook app bar. App closing is different from app quitting. See POE desktop app as an example:

https://github.com/janhq/jan/assets/89722390/52276c85-808b-4a43-821b-386b9a5ea31f

**To Reproduce**
1. Open Jan
2. Hit the "x" icon to close Jan

**Expected behavior**
When I hit close Jan, Jan app should still be active on the app bar until I quit the app. 

**Desktop:**
 - Mac Air 16GB Ventura
 - Version Jan 0.3.1

**Comment by louis-jan** [comment]
That's a good one, will add this back

**Comment by louis-jan** [comment]
Edit: 

This is a feature request and @linhtran174 will own this.

**Comment by dan-jan** [comment]
@imtuyethan I'm not 100% sure if this is the correct behavior, at least until we have "background" functionality (i.e. in-line summoning of AI)

**Comment by louis-jan** [comment]
@dan-jan @imtuyethan also user can pin our app on the dock, pretty much the same function but less engineering effort.
