### ISSUE TITLE
bug: Buttons are missing in My Models page

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#585]
**Describe the bug**
Buttons are missing in My Models page.
<img width="1193" alt="Screenshot 2023-11-11 at 10 55 06 AM" src="https://github.com/janhq/jan/assets/89722390/426e3584-07f7-4a3a-9580-6c528c89dc0b">

https://github.com/janhq/jan/assets/89722390/d6c8651d-311b-4af6-a517-16267c220707

**To Reproduce**
1. Open Jan app
2. Go to "My Models" Page
3. See the bug

**Desktop:**
 - Mac Air 16GB Ventura
 - Version Jan 0.3.1

**Comment by urmauur** [comment]
@louis-jan @imtuyethan i got this experience also, since we save cache when you select primary color and i remove several color, this is should be resolve when you try select again Primary color on setting

**Comment by urmauur** [comment]
confirm with @imtuyethan this is not issue
