### ISSUE TITLE
bug: Cannot start chat although my model is active

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#586]
**Describe the bug**
I cannot start chat although my model is active.

https://github.com/janhq/jan/assets/89722390/6872e837-e1ba-4e31-9e3a-b5ea05c84bd1

**To Reproduce**
1. Open Jan
2. "Command + E" to open my models
3. Use mouse to select one of the models in my model
4. It shows the model is active 
5. Go to "Chat" 
6. See the bug

**Expected behavior**
I should be able start chat once my model is active.

**Desktop:**
 - Mac Air 16GB Ventura
 - Version Jan 0.3.1

**Comment by louis-jan** [comment]
CC: @vuonghoainam, this is where the model load status should be implemented. I will use this issue for the implementation.

**Comment by louis-jan** [comment]
Fixes: #618
