### ISSUE TITLE
bug: Error occurred: Failed to fetch

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#587]
**Describe the bug**
Cannot chat with Error: Failed to fetch

https://github.com/janhq/jan/assets/89722390/8b75ba43-8c80-47d7-998c-70ca4a00a3b1

https://github.com/janhq/jan/assets/89722390/74e332f1-707d-4b2e-9449-61bca219defb

**To Reproduce**
1. Go to 'chat'
2. Click on 'old conversations'

**Desktop (please complete the following information):**
 - Mac Air 0.3.1 Ventura
 - Version Jan 0.3.1

**Comment by dan-jan** [comment]
I encountered the same issue: 
![image](https://github.com/janhq/jan/assets/101145494/2cc336c8-c447-4341-ba59-ef83cbdea277)

**Comment by louis-jan** [comment]
I encountered this very often. Will work with Alan on this.

**Comment by dan-jan** [comment]
I encounter this issue when switching models:

- Starting model2 with model1 working
- Switching convos where active model is different

On another note, we should have a standardised banner or toast for model loading/unloading. I think allowing the user to have system observability helps with expectation management and debugging
