### ISSUE TITLE
bug: duplicated messages (in-memory state / html issue) 

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#591]
**Describe the bug**
Messages are cloned from the other convo, despite what convo I'm in, switching between them will see this

<img width="1316" alt="Screenshot_2023-11-11_at_13 54 46" src="https://github.com/janhq/jan/assets/133622055/f4d9367a-4384-46e2-ae7b-4bb72de95260">

copy this to appData/conversations to reproduce
[conversations.zip](https://github.com/janhq/jan/files/13324741/conversations.zip)

models: wizard coder & mistral

**Comment by louis-jan** [comment]
Root cause: 
Known issue, message id could be duplicated (since we use unix timestamp as id), it sends twice when pressing enter with Vietnamese message (ascii characters some how repeating the send action)

**Comment by dan-jan** [comment]
I encountered the same issue, 
![image](https://github.com/janhq/jan/assets/101145494/32bd58ff-ef10-473b-8882-5e0e80380a39)

**Comment by louis-jan** [comment]
Fixed
