### ISSUE TITLE
designs: edge cases & stateful handling btw models, assistants, and threads

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#601]
Nicole: I think there are a lot of edge cases & stateful designs from our new refactoring plans that we haven't discussed yet. Please feel free to post them here, e.g. 

What happens when users delete a model, but not an assistant that uses it?
Users  delete assistant but can still see hold thread history. What does the design look like?
Users can switch models before starting a thread, but cannot swtich after convo has started. What do designs look like?

**Comment by imtuyethan** [comment]
From a user POV:

- **When users delete a model, but not an assistant that uses it**: Should not delete the assistant, but instead ask the users to pick any other model to run it, it's better if they can keep the existing prompts without having to set up everything again (in case they delete the model by mistake & have many assistants used the same model etc).

- **Users delete assistant but can still see hold thread history**: May i ask what is the original purpose of this? 
	- For database history: If this is the case, should not show on UI.
	- Showcase that users can have multiple assistants within 1 big thread: If this is the case, should have a separate app (of section) for it, and it should not show previous threads history from individual assistants, seems confusing. 
	- For users to backup/look back on history data: If this is the case, we could have a separate archive sections for deleted threads.

- **Users can switch models before starting a thread, but cannot switch after convo has started:** 
	- Make it clear in assistant creating/configuring steps
	- Once an assistant is set up, model field should show as information field

**Comment by 0xSage** [comment]
@imtuyethan your latest designs should reflect these edge case states

**Comment by dan-jan** [comment]
I would ignore all Assistants stuff for now, and just focus on Jan as the default Assistant. 

- There's too much to figure out = paralysis
- Let's move on what we do know (Jan as the default Assistant), and figure out Assistant in the next week

**Comment by imtuyethan** [comment]
This issue will be updated along with https://github.com/janhq/internal/issues/47
