### ISSUE TITLE
chore: refactor data structure

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#614]
**Problem**
- Since converting 'Product' to 'Model', we've encountered issues with redundant duplication.
- There are duplicated Conversation types (core/web).
- Message types are duplicated (RawMessage, ChatMessage, Messages, NewMessageResponse).
- Unused fields such as model type, updatedAt, senderUid, messageType, messageSenderType...
...
- Such duplication issues are causing confusion, both in working with new features and in onboarding new members

**Comment by 0xSage** [comment]
Related: 
- https://jan.ai/docs/modules/models
- @vuonghoainam 's pending specs on models and chats
