### ISSUE TITLE
feat: yarn build scripts automatically check platform

### ISSUE THREAD

**Issue by linhtran174** [janhq/jan#619]
**Problem**
As the first team member to encounter build problem with `jan` on Windows when following our `README.md`, I want to make the build command OS-independent so that we don't need to add OS-specific instruction in the README.md. There will be many people gave up trying out if they dont success the first time they build. 

**Success Criteria**
`yarn build:plugins` and `yarn build` will succeed on either platforms

**Current solution**
Utilize this https://www.npmjs.com/package/run-script-os

**Comment by 0xSage** [comment]
Thank you for the detailed issue description. Very clear what we're solving for.
