### ISSUE TITLE
feat: Re-structure the installation docs 

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#632]
**Problem**
It would be beneficial to have a clearer and concise structure in the installation documentation. Installation should focus on only installation and setup part only. 

Other parts will be re-written and moved to the QuickStart section including Tutorial, Settings, Tips and Tricks (activating GPU), etc (Mentioned in issue #633)

**Success Criteria**

The installation documentation requires revisions to improve its clarity. Any spelling, grammar, punctuation, or format style errors should also be corrected during this process.
- [x] Linux
- [x] Mac
- [x] Windows

Successful installation documentation is characterized by clear and concise instructions, covering all necessary steps accurately and consistently. It should be accessible to users of varying technical backgrounds, and enable users to easily verify a successful installation.

**Additional context**

**Comment by hieu-jan** [comment]
#664

**Comment by 0xSage** [comment]
If this is done, please close this issue @hieu-jan
