### ISSUE TITLE
docs: intro/quickstart

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#633]
**Problem**
As we have re-structuring the installation docs #632, other parts will be re-written and moved to the QuickStart section including Tutorial, Settings, Tips and Tricks (activating GPU), Keyboard shortcut

**Success Criteria**
Documentation is characterized by clear and concise instructions. It's important to include instructions along with images in the documentation.

**Additional context**

**Comment by 0xSage** [comment]
If this is done, please close this issue @hieu-jan
