### ISSUE TITLE
feat: Jan Repo issue template should have a Docs template

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#635]
Can we create a Docs template in Jan repo, with the relevant tags for Documentation?
- Docs aren't really chores
- Docs aren't really features

That way, release notes will have separate section for Docs. We can also differentiate docs contributions from actual codebase contributions.

**Comment by hiento09** [comment]
![Image](https://github.com/janhq/jan/assets/136591877/4bbe0c29-9c4e-4ee5-beb4-f6c08b427c37)

We already have that for Jan @dan-jan , let me create the same label for Nitro

**Comment by hiento09** [comment]
Oh, actually I configured Nitro repo the same way, already have it. I am going to close this issue.

![Image](https://github.com/janhq/jan/assets/136591877/426f5f21-219c-4ec1-b7b0-72ff07b859ea)
