### ISSUE TITLE
docs: Choosing and Downloading their first model

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#639]
## Objective

- First-time users of local AI are usually very confused and intimidated by choosing and downloading their first model
- This requires knowledge of their own hardware, as well as models (e.g. 7b, 34b, 70b models)
- Our docs should both educate the user on
   - Models (and how they work)
   - Hardware

**Hieu**
- @hieu-jan should use this exercise to level up his knowledge of local AI models and how they work

## Tasking

- I would like @hieu-jan to be responsible for this. Good exercise to onboard him and sharpen understanding of Local AI
- I'd like @hahuyhoang411 to help level @hieu-jan up
- We may refactor some of this into a "LLM Course" in the future

## Key Knowledge

> Note: This is NOT an outline, but a list of objectives for the reader to learn from this Doc. 
> Some of it may not be part of the "Choose or Download your first model", but -> into the LLM Course

**"Tree of Knowledge" for Models**
- "What are models?"
    - "Models" are AI programs that they can download and run on their own computer
    - Models have different capabilities, knowledge, "responses", personalities (e.g. training data)
    - Models have different sizes (diff. between 3b, 7b, 34b, 70b, and ChatGPT as a 175b model) 
    - Models are .bin files that Jan helps you run on your computer (just start with for llama.cpp)
- How do you run these models?
    - Reference llama.cpp, exllama, etc
    - Reference different model formats (transformers, llama.cpp, etc)
- What is quantization?
    - What are these q2, q3, q4 etc? 
    - What happens when I quantize?
- Where can I find these models?
    - What is Huggingface? 
    - How do we download models from Huggingface?
    - What are alternative sites?

**How do I choose a Model?**
- They need to choose a model based on the hardware they have
    - How RAM and VRAM relate to Models
    - How models work under the hood (i.e. loaded into memory)
- How to choose a model
    - What is your purpose? (e.g. role playing, storytelling, logical reasoning?)
    - What is the hardware you have? (if you only have 8gb RAM, you only can choose 3b model)
    - Recommended "first" model
    
**How things can break**
- What happens when things go wrong?
    - Why can't I load Falcon 180b into a 8gb Macbook?
    - Why can't I load a Pytorch model that isn't in Llama.cpp format?

**Comment by hieu-jan** [comment]
The outcome docs of this task will be added under the QuickStart section, as a part of #633

**Comment by hahuyhoang411** [comment]
Hey, this gonna be a big discussion. Let's move it to hackmd for more productive work.

https://hackmd.io/@YrBrGDBIRmq7x9V3eAa3Nw/H1jWfPE4p/edit

**Comment by dan-jan** [comment]
> Hey, this gonna be a big discussion. Let's move it to hackmd for more productive work. @hieu-jan feel free to set up a call with me. I can help you to understand all of these
> 
> https://hackmd.io/@YrBrGDBIRmq7x9V3eAa3Nw/H1jWfPE4p/edit

Thanks @hahuyhoang411!
