### ISSUE TITLE
bug: Error: Timeout

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#642]
**Describe the bug**
App shows error: Timeout

https://github.com/janhq/jan/assets/89722390/9ed06ac5-a141-4c27-bde8-b85daf6fa5c1

**To Reproduce**
1. Start clicking around
2. Suddenly error appears

**Desktop (please complete the following information):**
 - Mac Air 16GB Ventura
 - Version: 0.3.2

**Comment by louis-jan** [comment]
🫨

**Comment by imtuyethan** [comment]
@louis-jan
Please bare with me through the clip, the error will show up when I just start clicking around. 
One more thing that it took me 3 times to open developer view (no idea why).

https://github.com/janhq/jan/assets/89722390/c6f330d3-0e64-487b-9a9b-089950d6af04

**Comment by louis-jan** [comment]
Thanks for the information. @imtuyethan. I will check it now

**Comment by imtuyethan** [comment]
Additional info: I have not been able to use Jan ever since because I cannot start any model: 
https://github.com/janhq/jan/assets/89722390/65b41bc2-cc8c-40a8-acc1-0bcc5fd6bfa1

**Comment by louis-jan** [comment]
This was our first attempt to debug with @imtuyethan: The app couldn't spawn the Nitro process as there were no network calls afterwards. However, manually opening Nitro works, which indicates the problem is on the app's side.

**Comment by louis-jan** [comment]
Replaced by Nitro process exit message.
