### ISSUE TITLE
bug: [Chat screen] Small download button at the corner is not clickable sometimes

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#643]
**Describe the bug**
[Chat screen] Small download button at the corner is not clickable sometimes

https://github.com/janhq/jan/assets/89722390/393bdfff-0e89-41b6-951f-71e0cd3131a4

**To Reproduce**
1. Deactivate all models
2. Go to 'Chat'
2. Click on any chat history
3. See the download button the the top right corner
4. Try to click on the button & see error

**Expected behavior**
It should be clickable if my mouse still hovers over the button

**Desktop (please complete the following information):**
 - Mac Air 16GB Ventura
 - Version 0.3.2

**Comment by louis-jan** [comment]
🫨
