### ISSUE TITLE
bug: GGUFv1 model is deprecated, please try another model

### ISSUE THREAD

**Issue by hieu-jan** [janhq/jan#645]
**Describe the bug**
After downloading `llama-2-13b-chat.gguf.q4_0.bin` and starting the model. I got the message `GGUFv1 model is deprecated, please try another model`. Is that a normal situation as this model is deprecated? 

If it's not a bug, should we have an additional feature for users reporting the deprecated model?

**To Reproduce**
1. Downloading `llama-2-13b-chat.gguf.q4_0.bin`
2. Starting the model

**Screenshots**
![image](https://github.com/janhq/jan/assets/150573299/121b597c-cefc-436f-8842-7fc498a01d2d)

**Desktop (please complete the following information):**
 - OS: Macbook Pro M1
 - Version: Jan 3.0.2

**Additional context**

**Comment by louis-jan** [comment]
We are working on Model Catalog to take down all of these deprecated models. Thanks for reporting @hieu-jan

**Comment by louis-jan** [comment]
@hieu-jan its updated, The 'bhlim' model has been removed. The replacement model should work: Llama-2-7B-Chat-GGUF
