### ISSUE TITLE
bug: Line heights in Docs is for list elements is till off

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#651]
**Describe the bug**
- Line heights in Docusaurus are still too large between `li` elements
- This makes our docs difficult to read, especially given that it is information-dense
- A lot of information hidden below fold/requires scroll, poor information density or glance-ability

## Resources

Comparison of Docusaurus and our current jan.ai

![image](https://github.com/janhq/jan/assets/101145494/17a2ad03-6d45-4492-9e2c-2eced5d9b506)

![image](https://github.com/janhq/jan/assets/101145494/c044d5ff-62a7-4984-9c51-740d3f5d49ac)

**Comment by urmauur** [comment]
Fixed with this PR https://github.com/janhq/jan/pull/658, i'll implement on Nitro docs @dan-jan
