### ISSUE TITLE
bug: [Jan website] Update footer & spacing between sections

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#661]
- Update footer:
<img width="1470" alt="Screenshot 2023-11-19 at 11 23 17 PM" src="https://github.com/janhq/jan/assets/89722390/9119d4bb-23fd-4288-8787-470793b5a87c">

-> Result:
<img width="1428" alt="Screenshot 2023-11-19 at 11 27 05 PM" src="https://github.com/janhq/jan/assets/89722390/57a1d0d9-dd97-4960-bbdb-50b569628ffb">

- Adjust spacing between sections:
<img width="681" alt="Screenshot 2023-11-19 at 11 35 56 PM" src="https://github.com/janhq/jan/assets/89722390/1db03874-f589-43c1-8f1f-c61f104bc165">

<img width="478" alt="Screenshot 2023-11-19 at 11 33 29 PM" src="https://github.com/janhq/jan/assets/89722390/746c86f4-7d22-47d8-ab4d-9ed67e58b7e4">

<img width="814" alt="Screenshot 2023-11-19 at 11 35 31 PM" src="https://github.com/janhq/jan/assets/89722390/2e16e067-b0bc-4710-87f2-431ed92537a2">

**Comment by urmauur** [comment]
@imtuyethan already on pre release you can check this https://pre-release.jan.ai/
