### ISSUE TITLE
feat: [Design] import models via Huggingface URL

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#678]
# Jan Model Importer extension

Jan builds "importers" for users to seamlessly import models from a single URL.

We currently only provide this for [TheBloke models on Huggingface](https://huggingface.co/TheBloke) (i.e. one of the patron saints of llama.cpp), but we plan to add more in the future.

Currently, pasting a Huggingface link in the Explore Models page will fire an importer, resulting in an:
- Nicely-formatted model card
- Fully-annotated `model.json` file

**Comment by imtuyethan** [comment]
for review: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=2188-218505&mode=design&t=P76QcZnZBvoxZEgk-4
