### ISSUE TITLE
docs: API Reference for Threads, Messages, Assistants

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#686]
- assistants (hiro has specs)
- threads (nicole)
- messages (nicole)
- chats (TBA)

**Comment by hahuyhoang411** [comment]
This is done in PR https://github.com/janhq/jan/pull/679

**Comment by 0xSage** [comment]
Related PR: https://github.com/janhq/jan/pull/681

**Comment by 0xSage** [comment]
fixed
