### ISSUE TITLE
bug: Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#692]
<img width="912" alt="image" src="https://github.com/janhq/jan/assets/69952136/7962ff54-6a93-416f-8988-463ddc848bd3">

To repro: 
1. Use Jan for a while
2. New thread
3. Chat
4. See this screen

Machine: mac m1 16gb

**Comment by vuonghoainam** [comment]
oh, I remember @louis-jan 's demo a while ago

**Comment by louis-jan** [comment]
yeah that's when frontend app is crashed @vuonghoainam

**Comment by louis-jan** [comment]
It seems like chat summary / inference issue, which has been addressed. Will keep an eye on this
