### ISSUE TITLE
bug: (Nitro) Falcon 180B on Windows yields segmentation faults

### ISSUE THREAD

**Issue by linhtran174** [janhq/jan#696]
**To Reproduce**
Runs Nitro CPU version - latest 0.1.8
Open Jan and start model falcon 180B 

**Screenshots**
![image](https://github.com/janhq/jan/assets/8022780/8275c03e-e186-4c66-a19a-f6f7385b9c24)

**Desktop (please complete the following information):**
 - OS: Windows
 - RAM: 128GB

**Additional context**

**Comment by louis-jan** [comment]
@linhtran174 I will try replace this model today

**Comment by louis-jan** [comment]
this model is outdated, we are adding neutral-intel-chat-7b here
https://github.com/janhq/models/pull/13
