### ISSUE TITLE
bug: update app should show `in progress` again

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#710]
**Describe the bug**
We got rid of the app update downloading status bar, so we do see how logn it takes apps to update. The app just appears frozen

**To Reproduce**
1. Open old version
2. Click download new version
3. App "freezes" for up to 1 minute 
4. Get restart prompt

**Expected behavior**
See download progress, so I dont think something went wrong and quit the app

**Desktop (please complete the following information):**
 - OS: mac m1
 - Version: 0.3.2, 0.3.1

**Additional context**

**Comment by louis-jan** [comment]
Let me fix
