### ISSUE TITLE
Jan new landing page

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#724]
Previous request from @dan-jan:
I think Chatbox does this very well. We should learn from them and adapt. 

## Ideas

- Hero image: should show some special feature (e.g. code block?)
- Tagline: should be very succinct? (like Chatbox/LMStudio?)
- "Book a Demo" <- call to action

## Github

- Hero images in light mode and dark mode
- Previews show cool features (e.g. Table, Code block, LateX)
- Download links directly in README (is there a way to auto-update using CI/CD? Ask @hiento09)

![Image](https://github.com/janhq/internal/assets/101145494/7802b5c5-c16d-4b26-9de6-5ce6fa91cf8f)

## Homepage

- Does not depend on "UI" to detect the OS (fails sometimes)
- Hero image shows it in action
- Download section at top of screen

![Image](https://github.com/janhq/internal/assets/101145494/9b9df0e5-0a70-4b5e-85e1-3c50d444e8f1)

New sketch layout for Jan web from @dan-jan: https://app.excalidraw.com/l/kFY0dI05mm/3CoxMiq1pOT

**Comment by imtuyethan** [comment]
Official design link: https://www.figma.com/file/M1ARCQL19Ill0hN2EOR4tI/Jan-Website?type=design&node-id=806-28652&mode=design

**Comment by dan-jan** [comment]
Completed - great job guys!
