### ISSUE TITLE
epic: Jan Mobile (Connect to Homeserver)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#728]
## Issues

https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+Mobile%22

## Questions

- Jan Mobile should also support local models?
- Jan Mobile should be able to access a server running on Jan Desktop
- Jan iOS and Android extensions?
- Use Capacitor?
- Should we have a sync framework? (similar to Obsidian?)

## Legacy Task

**Problem**
Jan has a mobile app shell which points to a Desktop or Server-side instance of Jan

**Success Criteria**
- Users can download Jan Mobile on Android & iOS
- Users can point app to server backend
- Users can do simple auth / basic security check (maybe just username/pw)

**Subtasks**
- [x] #918 
- [ ] #921 

**Not in Scope**
- [ ] #1181 i.e. models run on mobile device

**Additional context**
- This is a highly requested user feature

**Comment by imtuyethan** [comment]
Moving to Notion specs til it is confirmed: https://www.notion.so/jan-ai/Jan-Mobile-bfffbeab6c794e06b2444bfbbbc47958?pvs=4
