### ISSUE TITLE
epic: Jan Core is independent of Electron

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#729]
## Linked Milestone

https://github.com/janhq/jan/milestone/35

## Objective

- Decoupling Jan from Electron
- Jan can be run server-side by a large enterprise
    - Staff of large enterprise can access Jan by going to internal URL
    - Jan can run server-side (non-desktop)
    - Extensions continue to run effectively

## Todos

- Discussion on Clean Architecture: #798 
- [x] Base code for server side - mirroring most components from electron app, trimming down unnecessary components 
- [x] #768
- [x] #765
- [x] #766
- [x] #767
- [ ] #778 
- [x] #916 
- [x] #920 
- [x] #765 
- [x] #766 
- [x] #767 
- [x] #1117 

Jan Enterprise
- Electron independent
- Self-hostable chatGPT
- IT Dept hosting on powerful opus
- multi user, authentication, etc.

Variations: 
- on prep
- on gaas
- 

Variations; 
- cloud native
- inference queue
- multi users

**Comment by dan-jan** [comment]
@linhtran174 I appreciate you adding the issues to the Todo, really helps us track progress on this!

**Comment by dan-jan** [comment]
@linhtran174 @louis-jan FYI, I am renaming this Epic so the intended outcome is clearer

**Comment by linhtran174** [comment]
Thanks Dan

**Comment by dan-jan** [comment]
Epic transferred to @louis-jan @namchuai, with @0xSage @hieu-jan supporting on docs.

**Comment by dan-jan** [comment]
@linhtran174 Can you add any other issues that you have linked to this task here?

**Comment by linhtran174** [comment]
Sure I've just updated

**Comment by dan-jan** [comment]
@namchuai @louis-jan @nicole I have renamed "Jan Server MVP" to "Jan Core is independent of Electron", to make this a deliverable epic that is on the roadmap for:

- Jan Core
- Jan Enterprise (i.e. cloud native, server = we are using "enterprise" for now to refer to this)

**Comment by namchuai** [comment]
This one is finished with @louis-jan 's PR #1210

**Comment by 0xSage** [comment]
Amazing work 🙏
