### ISSUE TITLE
feat: `File` Support for Threads and Assistants

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#733]
## Questions

- Is there automatic RAG for Threads?
- How do we define whether memory is persistent? (i.e. thread-level memory, or Assistant remembers everything you told them)
- How do we store files? (in /assistant/files? or in /files)? 
- How does this tie to RAG?

## Legacy Task

**Problem**
- Assistants can't use document based knowledge

**Success Criteria**
- Users can upload docs/data to create assistants
- Users can upload docs/data within convo threads

**Additional context**
- Pending Specs: needs to be thought through clearly

**Comment by louis-jan** [comment]
@hiro-v could you please own this. I think we better to have only 1 assignee / epic / feat
