### ISSUE TITLE
Assistants interact with each other via async Events

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#734]
**Problem**
- Assistants can't respond to each other
- Assistants themselves don't have an API framework

**Success Criteria**
- Assistants can emit events
- Assistants can respond to other event hooks

**Additional context**
- Pending Specs

**Comment by 0xSage** [comment]
@hiro-v is this `done` or `wont do`. 
Depending on the above, please also `close with comment`

**Comment by louis-jan** [comment]
According to the latest update, now assistants or extensions can: 
- Register engines.
- Register models.
- Register actions.
- Use any engine.
- Use any action (e.g. retrieval action)
via Core SDK

This update reduces the complexity of event handlers, allowing for better control of logic flow.

We will update the documents after they are fully aligned #2451.

Consider to close this and use #2451 to track the issue.
