### ISSUE TITLE
bug: Experimental Mode doesn't work

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#747]
**Describe the bug**
I'm not sure what `experimental mode` in settings is. I assumed it would download prereleases, but it doesn't do anything. 

**To Reproduce**
https://www.loom.com/share/3f233032d3ad4c52bc90ec2f0c15e3b7

**Expected behavior**
I expected that the system would start autoupdating for pre-releases

**Screenshots**
https://www.loom.com/share/3f233032d3ad4c52bc90ec2f0c15e3b7

**Desktop (please complete the following information):**
 - OS: mac m1 16gb
 - Version: 0.3.2

**Additional context**

**Comment by louis-jan** [comment]
@0xSage experimental mode is feature toggle, its to hide under-testing/dev features (since we go with trunk-based). Its not related to pre-release or release which is electron-updater would handle itself (pull latest release only)

**Comment by 0xSage** [comment]
> @0xSage experimental mode is feature toggle, its to hide under-testing/dev features (since we go with trunk-based). Its not related to pre-release or release which is more about electron-updater mechanism (pull latest release only)

Got it thanks. Is the toggle supposed to be sticky? The issue still exists where if I toggle on, it doesn't stay this way

**Comment by louis-jan** [comment]
> > @0xSage experimental mode is feature toggle, its to hide under-testing/dev features (since we go with trunk-based). Its not related to pre-release or release which is more about electron-updater mechanism (pull latest release only)
> 
> Got it thanks. Is the toggle supposed to be sticky? The issue still exists where if I toggle on, it doesn't stay this way

Its addressed in 0.3.3
