### ISSUE TITLE
epic: Jan's UIKit and Design System

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#758]
## Epic

https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Jan+UIKit+and+Brand+Guide%22

## Objective

- We should have a simple "Bootstrap" CSS UIKit
- This enables Design and UI Engineering to move in tandem, very quickly

Note: This is different from #757 (refers to the UI Framework for Extensions)

**Comment by dan-jan** [comment]
From @imtuyethan in Discord: 

(1) Here's the app wireframes & flow: https://www.figma.com/file/2eoGQYUj5pcxyr7RYieTaF/Jan-App-(Sandbox)?type=design&node-id=709%3A3952&mode=design&t=7utn27YVOeJ7AqQz-1
(2) Here's the app recreation file I've been working on with the new components & lib we discussed last night: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App-Official-(WIP)?type=design&node-id=0%3A1&mode=design&t=I9XMQ5E3d19bmHqC-1
(3) Design system: [https://www.figma.com/file/Js8MF76jMQ99fDwtnOT8pA/⚫%EF%B8%8F--Design-System?type=design&node-id=30%3A1229&mode=design&t=FNCn6FmX4sSvDp5Z-1](https://www.figma.com/file/Js8MF76jMQ99fDwtnOT8pA/%E2%9A%AB%EF%B8%8F--Design-System?type=design&node-id=30%3A1229&mode=design&t=FNCn6FmX4sSvDp5Z-1)

**Comment by imtuyethan** [comment]
Closed this for now as it's an ongoing roadmap, not an epic.
