### ISSUE TITLE
epic: Keyboard Shortcuts, Search and Quick Switcher

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#760]
/WIP Spec

- Quick Switcher allows opening of Assistants and Models
- How do we do full-text search on a local fs? (or is this mainly just quick switcher for now?)
- Behavior when creating a new Thread

Benchmark to https://docs.obsidian.md/Plugins/User+interface/Commands

## Related

- #795

**Comment by dan-jan** [comment]
Context from @tikikun on Hotkeys:

![Image](https://github.com/janhq/jan/assets/101145494/020ee242-12a3-40d4-a5bd-e3eeaf4fc432)

**Comment by imtuyethan** [comment]
Moving this to Notion til it is confirmed: https://www.notion.so/jan-ai/Jan-Hotkeys-Keyboard-Shortcut-9df14165c11d487e906e899e72d86ba9?pvs=4
