### ISSUE TITLE
epic: Support Intel as Inference Engine

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#761]
WIP Spec
- Need to figure out if BigDL or Intel Extensions are separate
- Have Extensions for each inference engine
- `model.json` should have an `engine: intel-bigdl` or `engine: intel-transformers` 

## Resources

Intel BigDL
https://github.com/intel-analytics/BigDL

Intel Extension for Transformers
https://medium.com/intel-analytics-software/efficient-streaming-llm-with-intel-extension-for-transformers-runtime-31ee24577d26

**Comment by 0xSage** [comment]
outdated issue
