### ISSUE TITLE
feat: revamp thread screen

### ISSUE THREAD

**Issue by urmauur** [janhq/jan#774]
**Problem**
![image](https://github.com/janhq/jan/assets/10354610/0daaa7ac-2b6c-4696-9229-9c1f3ee1aa31)

**Success Criteria**
- Thread screen is default screen
- Screen blank state when user have not any model
- Change create thread using icon instead of button
- Update ribbon menu icon 
- Update Message toolbar height when user typing long message
- Add default avatar placeholder
- Update message action toolbar
- Update right panel visual to latest design on FIgma
- New component select or dropdown

**Additional context**
[Figma Link](https://www.figma.com/file/2eoGQYUj5pcxyr7RYieTaF/Jan-App-(Sandbox)?type=design&node-id=709-3952&mode=design&t=ocDCqNeoqtuwl9pB-0)

**Comment by louis-jan** [comment]
Done ✅
