### ISSUE TITLE
feat: Extension should be able to register its own settings

### ISSUE THREAD

**Issue by louis-jan** [janhq/jan#776]
**Problem**
- Extension now could not able to register settings. New inference extensions require credentials to work with endpoints.

**Success Criteria**
- From a extension class
```ts
interface OAISettings {
  key?: string | undefined
}

const DEFAULT_SETTINGS: Partial<OAISettings> = {
  key: "xxx-yyyy",
};

class OAIExtension extends JanExtension {
   settings: OAISettings

   onLoad() { 
      this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
   }
}
```

**Additional context**
User should be able to update settings from setting page > extensions > oai extension > settings

Base Extension class should have a default implementation of 
```ts
// Read extension data from json file 
function loadData()

// Write extension data to json file
function saveData(data: object)
```

Q: Web & Mobile compatibility?
A: inject localStorage module (session based) instead of `fs`  for these platforms

**Further update**
- Settings can be updated via registered commands / setting tabs (UIFramework constraint)

**Comment by dan-jan** [comment]
Thanks - I think this will be a great way to start work on https://github.com/janhq/jan/issues/757

**Comment by imtuyethan** [comment]
Design for dynamic extension settings:
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App-(version-1)?type=design&node-id=6999-89915&mode=design&t=IhyPYt0bZS0kM65Y-4

<img width="908" alt="Screenshot 2024-03-28 at 1 10 57 PM" src="https://github.com/janhq/jan/assets/89722390/ac219baa-dfa4-41b9-972c-fcdc96d37338">

**Comment by Van-QA** [comment]
1. Extension group name should be in upper case for all text :x:, see Figma design above 
![image](https://github.com/janhq/jan/assets/64197333/e2292863-e2d8-4e86-9030-1cf7014811cb)

2. Inconsistent in the hyperlink text: Groq Documentation and OpenAI documentation :x:
<img width="798" alt="image" src="https://github.com/janhq/jan/assets/64197333/919526c8-044d-48f6-a320-97834087eca1">
<img width="749" alt="image" src="https://github.com/janhq/jan/assets/64197333/fdfb3fa0-cff9-415f-aa98-3636836358e3">

**Comment by Van-QA** [comment]
3. API key placeholder should contain prefix of the sample key:
- openAI: sk-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
- Groq: gsk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
![image](https://github.com/janhq/jan/assets/64197333/e08b4302-21e1-4ed9-ae79-b8c36acccef4)

**Comment by Van-QA** [comment]
Testing and the main feature is working Jan v0.4.10-365 ✅ 
But there is an issue with the manually imported remote model https://jan.ai/docs/remote-inference/generic-openai.
- Imported remote model using existing engine
- Imported remote model using the new engine

Dev team will need to investigate and include those cases in the fix. 
Many thanks @louis-jan @namchuai

**Comment by Van-QA** [comment]
looking good on Jan v0.4.10-367 ✅
