### ISSUE TITLE
feat: Support multipart GGUF models

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#779]
**Problem**
Normally we only have 1 model path for each GGUF. However, when using a big model like Goliath 120B we will have 2 paths for A and B parts. So how can we config our model.json?

Example of `model.json`:

```
{
  "source_url": "https://huggingface.co/TinyLlama/TinyLlama-1.1B-Chat-v0.6/blob/main/ggml-model-q4_0.gguf",
  "id": "tinyllama-1.1b",
  "object": "model",
  "name": "TinyLlama Chat 1.1B"
}
```

-> Only 1 model path.

**Success Criteria**
Appropriate model.json file to handle multi paths model.

**Additional context**
Handle multiple GGUF: https://github.com/ggerganov/llama.cpp/issues/1503

**Comment by 0xSage** [comment]
@hahuyhoang411 the team has already thought of how to handle this. 

`assets` property will point to multiple files. 
https://jan.ai/specs/models/#example
