### ISSUE TITLE
feat: Data Persistence for Settings

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#780]
Where do we persist Settings parameters? 
- Look at VSCode and Obsidian, should we persist in a .jan?
- https://code.visualstudio.com/docs/getstarted/settings

**Comment by 0xSage** [comment]
Is this done already @louis-jan ? I see janroot/settings folder. Pls close if so.

**Comment by louis-jan** [comment]
Yeah that's correct @0xSage
