### ISSUE TITLE
bug: WizardCoder-13b unable to generate code snippet

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#787]
**Describe the bug**
Wizard-13b failed to reply, then generated code snippet without code block

**To Reproduce**

<img width="1654" alt="image" src="https://github.com/janhq/jan/assets/101145494/629948a7-3b25-46e2-aa07-e6a4b74f7cb4">

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version: 0.3.3

**Additional context**

**Comment by hahuyhoang411** [comment]
Also the Neural Chat with Json format/ code blocks too. It seems like this is a UI render problems.

![image](https://github.com/janhq/jan/assets/64120343/fdb35fd5-fb93-4f53-b3da-8e2e37c4ce9c)

**Comment by louis-jan** [comment]
Seems fine on the latest update, let's recheck on 0.4.0 (once its ready) & attach compressed thread files for debugging.

![Screenshot 2023-12-01 at 15 43 36](https://github.com/janhq/jan/assets/133622055/89ae9caa-38eb-4656-b285-8c19f1b2d0d8)

**Comment by louis-jan** [comment]
I encountered the issue on different models, this not about the code formatter but model could return plain response (same on other apps). Assistants with good instructions could help.

**Comment by hahuyhoang411** [comment]
Great job @louis-jan

**Comment by louis-jan** [comment]
root cause: user_prompt & ai_prompt are empty in model.json. Same result when running on nitro manually 

"user_prompt": "",
"ai_prompt": ""
