### ISSUE TITLE
bug: model.metadata.properties should not be required

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#789]
**Describe the bug**
<img width="729" alt="image" src="https://github.com/janhq/jan/assets/69952136/4d933b22-8762-4a88-b538-6961c5c3f72b">

Same issue for metadata.avatarURL

**To Reproduce**
Delete some properties in model.json for downloaded model

**Expected behavior**
Handle null properties, UI should just show an empty state component

**Desktop (please complete the following information):**
 - Version: Dev build as of 30 Nov

**Additional context**

**Comment by louis-jan** [comment]
Deprecated (latest main). We are no longer access this maxRamRequired
