### ISSUE TITLE
Discussion: Add base model in `model.json`

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#790]
**Motivation**
Continue the discussion from @vuonghoainam 

Fyi: Some ppl only know llama2 but nothing else as it’s the only commercially available model they can use. Even though I saw some fine tuned models there based on llama2 but it’s the fact that I know but they dont
Adding something similar to HF added for ‘base model’ would help, or even adding base chat model

Adding 1 field at 1st level in model.json file as “base_model”: “meta/llama-2” would make sense

**Discussion**
Where do I put the value in the `model.json` now? below `model name` or inside `metadata`?
1. Below `name`
```
    "source_url": "...",
    "id": "...",
    "object": "...",
    "name": "...",
    
```
2. Or inside `metadata`:
```
    "parameters": {
      "max_tokens": ...
    },
    "metadata": {
      "author": "...",
      "tags": [...],
      "size": ...,
       "base_model": "llama-2"
    }
```

Please give comments so I can update this PR soon: https://github.com/janhq/jan/pull/775

**Comment by namchuai** [comment]
@louis-jan , could you please leave your comment here? Thank you!

**Comment by louis-jan** [comment]
It would be great to put additional informations like this into metadata.

**Comment by louis-jan** [comment]
Oops, sorry, this is quite complicated now since #840 we'd have many sections of parameters

**Comment by 0xSage** [comment]
Metadata it is. FYI @hahuyhoang411 
Closing this ticket.
