### ISSUE TITLE
feat: Use shortcut in search panel should close the search panel

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#795]
# Jan v0.3.3 Windows

**Problem**
I open the search bar and see the recommendation `Ctrl + ,` to open Settings Panel. However, I used the shortcut `Ctrl + ,` It changed to the Settings Panel but still opened the Search Panel. 

**Success Criteria**
When I use `Ctrl + ,` in Search Panel it should close the Search Panel and navigate to Settings Panel.

**Additional context**
Picture here:
![image](https://github.com/janhq/jan/assets/64120343/bb4e7cbf-edb3-4d96-823b-644810b2e4fa)

**Comment by dan-jan** [comment]
This is now deprecated
