### ISSUE TITLE
Discussion: Jan to fully adopt Clean Architecture

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#798]
## Motivation
- @louis-jan's suggestion to go Clean is great.
- We have leaky abstractions, a result of legacy features. This can be (slowly) refactored over time. 
- This is a proposal for longer term refactoring work.

## Possible directory structure for Jan SDK
```js
// @janhq/core: platform agnostic, local-first
// ------------
core/
    common/
        global.ts                              // Global constants, errors/exceptions, enums, etc.
        base___.ts
    ai-api/                                         // The AI api, the assistant framework, OpenAI compatible 
        models/
            entity.ts                           // Defines object, e.g. `const model = {id, desc, params}`
            api.ts.                              // Defines the interface, e.g. `const createModel`
            events.ts                         // Defines event enums on model obj
            constants.ts                    // Optional, if there are a lot of constants/global vars?
            index.ts                           // export ./*
        assistants/
        threads/

    // Other names: `jsl: Jan stdlib`, `origami`, 'helpers', 'wrappers', 'utils', `j-template-l`
    infra-api/                                              // Our local-first, cross-platform, application framework. Wraps stdlib.
        fsHelper/	                         // currently `fs.ts` impl, e.g. `writeFile`
        requestHelper/                  // Wrapper for `std.request`
        eventsHelper/

// @janhq/nativeos: native OS specific controls/gestures/menus (taken out of core)
native-api/
    menuContextManager/           // e.g. openFileExplorer -> shell.openPath()
    updater/                                    // Another example.
    systemSetting/                         // e.g. setting darkmode

//  Actual implementation code, injected at runtime
// ------------
extensions (implements ai-api)/                              // 3rd party extensions mostly go here
    assistants/                            // Assistant controller logic, i.e. `assistant.json`
    models/
    threads/

infra (implements infra-api)/
    common-implementations/
        fsHelper/
             fs.ts
    desktop-implementation/
        handler.ts      // Or adapter.ts: just imports common/fs
        menuContextManager/
    server-implementation/                                // Handles fs, fileManager/fm.writeFile
         handler.ts     / Or adapter.ts: just imports common/fs
    mobile-implementation/
```

## `/core`

**Principles**
- Core, aka `@janhq/core`, is the Jan SDK, which can be used to build extensions.
- Core has no `io` concerns (this is where we currently have leaky abstractions)
- Core has no framework concerns (we also have leaky abstractions here)
- Core should only care about ExtensionBase, not `assistants-extension` (leaky abstractions)
- The actual implementations for `core sdk` are injected at runtime, per `dependency inversion principle`. This means we can route to implementations inside of `/infrastructure` at runtime and not worry about infra at all at this level.

**Organization**

TODO

## `nativeos`

- Core is compatible across browser, serverside, desktop, any framework
- Nativeos are for specific os stuff

```javascript
// @janhq/nativeos: native OS specific controls/gestures/menus
// ------------
native/
	utils/        // Desktop only library
		menuContextManager/   // e.g. openFileExplorer -> shell.openPath()
		updater        // Another example.
		systemSetting  // haha, darkmode
```

## `/extensions`

**Principles**
- Implement controller logic
- Built it once, runs anywhere
- Extensions import `utils` (std wrappers)

**Organization**

```javascript
extensions/        // 3rd party extensions mostly go here
    assistants/      // Assistant controller logic, i.e. `assistant.json`
        index.ts.     // Single file, entrypoint
```

## `/infrastructure`

**Principles**
- Contains the infrastructure-specific implementations on Jan SDK
    - Framework-level: `electron`, `capacitor`, `web-only`
    - Adapter/driver-level: `fs`, `sqlite` (we should add `fsAPI` to `coreAPI`)
    - Adapter/driver-level: `oauth`, `saml`
- Define the cascading default behavior at runtime, i.e. how to determine what framework and drivers are available.

**Organization**

```sh
infrastructure/
    # Frameworks
    electron/               # Same as current, but keep the impls to Native-OS features only
    server/                  # Cloud Native only implementations
    capacitor/             # Future consideration

    common/              # Adapters, drivers, devices commonly used across frameworks
        fs/                        # Implements fs
        fsManager/
        identity/              # Future consideration
```

## Desktop mode with server

Given our 15 Dec goal, there should be 3 options/modes to run Jan in: 

- `default`: I want to only run Electron process(es), not Fastify: our current implementation.
- `serverside-only`: I want to run only Fastify, not Electron/main-process: our /server implementation
- `fancy`: I want both desktop app & local port: but it routes everything to fastify/a single process
    - Lets have `/web/dependecy-injection.js` for `fancy` mode, indicating what is routed and what is not

## Ref
- [Main inspo]( https://github.com/jasontaylordev/CleanArchitecture/tree/main/src)

## Next steps
- #797 
- TODO: Create ticket for each component / refactoring traunche

**Comment by louis-jan** [comment]
According to TCA, there is no need to provide @janhq/common module. Common will provide all of the Use Cases, which should only the business logic, no 3rd framework import, the repo framework would be injected automatically. The structure above is the correct version.

@linhtran174 is moving /common to /core/common, `fs` framework will be injected by the application (web / node), e.g. via `global`

**Comment by dan-jan** [comment]
I have refactored this to be part of #729

**Comment by 0xSage** [comment]
@louis-jan There's no `janhq/common` module. It is just a folder to contain base definitions - it doesn't export. Actual modules like `assistant` or `threat` implements the base interface and then is actually exported. It's just a code organization point. 

I'm gonna close this disc bc: 
1. It's a outdated / incorrect in some parts
2. You've already done parts of it
3. I'll be creating separate discussions on remaining questions
