### ISSUE TITLE
bug: many jan.ai pages are not indexed

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#805]
**Describe the bug**
This is a major SEO issue, also affects nitro.jan.ai

![image](https://github.com/janhq/jan/assets/69952136/8ddf0f33-cd63-4769-aee1-960bdc6e2706)

Not limited to these issues ^

**To Reproduce**
1. https://search.google.com/search-console/index?resource_id=sc-domain%3Ajan.ai&hl=en

**Expected behavior**
- No page index errors.
- All pages are crawlable
- Correct sitemap.xml

**Comment by 0xSage** [comment]
Actually, this issue is blocking our algolia search application as well. fyi @dan-jan  https://docusaurus.io/docs/search#using-algolia-docsearch

**Comment by 0xSage** [comment]
Hey @hieu-jan is this done? Feel free to close if so, thank you

**Comment by hieu-jan** [comment]
@0xSage Yes, the solutions have already implemented. sitemap.xml are correct and also submitted a list of removal requests for issued url. The re-validation progress already starts, it needs to take few days to weeks for getting the new results. I will monitor when new results are available and added additional fixes for each cases.
