### ISSUE TITLE
docs: table of definitions and explanations for end user

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#815]
Refer to https://github.com/janhq/jan/issues/754

**Pages**
- TBH

**Success Criteria**
- To support the UX design

@hahuyhoang411 would appreciate if you can lend a hands on this? since you've made the nitro docs for most of the parameters (but need a bit more explanation so that it's easier to understand for normal users)

**Comment by hahuyhoang411** [comment]
I add the table here

cc @imtuyethan 

https://hackmd.io/@janhq/H1LPvNPHa
