### ISSUE TITLE
feat: curate recommended models

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#820]
**Problem**
What happened to mistral & llama2? Those were my gotos. Our current default model list now is long but kind of obscure

And the good models are missing the right quants for my machine

**Success Criteria**
- Add back mistral & llama 2 (with 3 quant options) 
- Remove at least 5 random models that are not as popular and don't work very well
- Add quants for a few of the models currently provided, that are popular in the community.
- We have 9 models over 24GB ram. This is excessive.  
- We have 4 models under ~2Gb, this is also excessive

**Additional context**

**Comment by hahuyhoang411** [comment]
Working on this PR https://github.com/janhq/jan/pull/829

**Comment by hahuyhoang411** [comment]
This is merged with new version
