### ISSUE TITLE
feat: Add inference engine - NVIDIA triton inference server and TRT-LLM

### ISSUE THREAD

**Issue by hiro-v** [janhq/jan#821]
**Problem**
I have an existing NVIDIA triton inference server with TensorRT-LLM as backend. I want to use that model within Jan

**Success Criteria**
- Inference engine for nvidia Triton inference server - `nvidia-inference-engine-trt-llm/engine.json`
- Setup script and docs for setting up both and connection
- `model.json` for llama2-7b

**Additional context**
- #814 
- #816

**Comment by vuonghoainam** [comment]
Diagram illustrating Jan integration with NVIDIA Inference cluster
![Untitled Diagram-Page-9](https://github.com/janhq/jan/assets/22463238/9af72c48-7926-40e5-b973-96fd3e97c821)
