### ISSUE TITLE
feat: revamp Hub screen

### ISSUE THREAD

**Issue by urmauur** [janhq/jan#823]
**Success Criteria**
[Figma](https://www.figma.com/file/2eoGQYUj5pcxyr7RYieTaF/Jan-App-(Sandbox)?type=design&node-id=1184-19786&mode=design&t=JDnemt2AVuIn4MAP-0)

**Additional context**
Revamp `explore models` to `hub` screen

**Comment by louis-jan** [comment]
Done ✅
