### ISSUE TITLE
epic: Jan should quantize models and publish them on HF

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#826]
- Jan now has some compute resources in our officelab
- We can start quantizing models and publishing them on HF
    - How should we complement TheBloke?
    - Redundancy within the community?
- We can also start experimenting with new techniques
    - Merge Models
- Long-term, we can also do download mirror for Jan
    - Currently, HF downloads may be slow for Asia
    - We can operate as a "mirror" (similar to Apt package mirrors)

**Comment by tikikun** [comment]
> What are the hardware requirements to do this? May be good to sync with @hiento09.

Normally it won't require anything special in particular, but someone need to test the merge script first before jumping to conclusion.

**Comment by tikikun** [comment]
Link to mergekit for everyone referrence:

https://github.com/cg123/mergekit

**Comment by hahuyhoang411** [comment]
This DARE method is also a good approach https://github.com/yule-BUAA/MergeLM/tree/main .

**Comment by hahuyhoang411** [comment]
Will working on this https://github.com/janhq/jan/issues/828

**Comment by hahuyhoang411** [comment]
We have a repo to convert the model to GGUF here: https://github.com/janhq/model-converter
