### ISSUE TITLE
feat: Devide model hub into size section (small, medium, big)

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#835]
**Problem**
Right now the model hub is comprised of multiple models but all the type jammed together regardless of their size, for very big model like 70B model probably i will not be to touch it ever. Very hard for navigation.
<img width="1251" alt="image" src="https://github.com/janhq/jan/assets/22268502/b12ef51d-23ed-46f0-8366-1dae07920cf1">

**Success Criteria**
Can have multiple different sections for size of the models like small, medium and big

**Comment by imtuyethan** [comment]
will be solved along with this issue: https://github.com/janhq/jan/issues/850
