### ISSUE TITLE
feat: add a button to restart inference service to resolve edge case 

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#837]
**Problem**
As hard as we try, there will always be issues with inference service in the tiniest edge case (some time upstream repo has memory leak issue or some low level issue we might not know) and the inference service will crash in the background. We will try the hardest to avoid this situation but giving user a choice to restart this process is needed to avoid them having to resort to quitting the app.

**Success Criteria**
A red button to restart inference service will be useful for these edge cases.
ex:
"Restart Inference Extension"

**Comment by imtuyethan** [comment]
This ticket will be included in https://github.com/orgs/janhq/projects/5/views/26?pane=issue&itemId=48581704
I'll make sure to include Alan's info. Will close this as duplicated.
