### ISSUE TITLE
feat: improve ordering of hub page

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#839]
**Problem**
Right now the ordering of model is not controlled by any particular logic makes it hard to browse and download model
**Success Criteria**
Implement ordering with below tags and order
 Recommended -> Small -> Medium -> Tiny - > Large
 
**Additional context**
Eventually we will have hardware recommendation system, but right now we need to get the UX down a bit to make sure user can use good model in recommended section, then small and medium models are most what mac can run. Tiny is not good in quality, large is not suitable for most computer.

**Comment by louis-jan** [comment]
Sorting by Recommended is enabled on the latest main, will be on the next nightly build. Small > Medium > Tiny > Large seems a random order mechanism. Is there any information in this?

**Comment by hahuyhoang411** [comment]
I discribe what he was meant in this issue. https://github.com/janhq/jan/issues/848
