### ISSUE TITLE
fix: chat UI last message received is glitchy

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#84]
To repro: 
1. have a few conversations, wait for responses to complete
2. toggle back and forth btw chats
3. see the last ai reply rerender each time. 
4. strange

https://www.loom.com/share/c15febd4c81b42738a165ea4e5cf1d77

**Comment by drakehere** [comment]
I've created a duplicated issue: https://github.com/janhq/jan/issues/119

Please help me to delete the issue 119, I don't have permission to delete.

**Comment by namchuai** [comment]
thanks @0xSage .

@louis-jan , this seems like our enhancement for the text looks more smooth (StreamTextMessage). I will check it.

**Comment by namchuai** [comment]
The issue is fixed after refactor and apply jotai. PR: https://github.com/janhq/jan-web/pull/87
Video: https://drive.google.com/file/d/1BwE6VMapwJr-4o04YqjPyLZX8F9QYCcz/view

**Comment by 0xSage** [comment]
@namchuai is this fixed? if so, pls close this issue
