### ISSUE TITLE
bug: Deepseek coder 1.3B doesn't work on Jan app

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#841]
**Desktop:**
 - OS: Windows
 - Version: Jan v0.3.3.18
 
**Describe the bug**
Deepseek coder 1.3B doesn't work on Jan app while it works fine on Nitro server

**To Reproduce**
1. Go to `Model Hub` download Deepseek Coder 1.3B
2. Start chatting with it
3. See error

**Expected behavior**
It should response as normal

**Screenshots**
Example result when using Deepseek 1.3b in Nitro
```
{
  "choices": [
    {
      "finish_reason": null,
      "index": 0,
      "message": {
        "content": "<jupyter_code>\n# Fibonacci series implementation using recursion\ndef fib(n):\n    if n <= 1:\n        return n\n    else:\n        return fib(n-1) + fib(n-2)\n\n# Driver code\nprint(fib(8))\n<jupyter_output>\n<empty_output>\n",
        "role": "assistant"
      }
    }
  ],
  "created": 1701687606,
  "id": "qeKmj6lya0rTugXDbfxt",
  "model": "_",
  "object": "chat.completion",
  "system_fingerprint": "_",
  "usage": {
    "completion_tokens": 86,
    "prompt_tokens": 81,
    "total_tokens": 167
  }
}
```

Image:
![image](https://github.com/janhq/jan/assets/64120343/f457739f-54c6-4fad-b22d-3e59dffb8bd7)

Jan bug:
https://github.com/janhq/jan/assets/64120343/28cb1c6f-59cb-4a3d-80f9-74e84dab44f6

**Comment by louis-jan** [comment]
Remove this model, will add back with proper model settings
