### ISSUE TITLE
bug: manually downloading models

### ISSUE THREAD

**Issue by sherif414** [janhq/jan#842]
**Describe the bug**
manually downloading  a model  - through other sources than the gui - and then moving it to "C:\Users\<username>\jan\models" doesn't work and the model isn't detected.
i tried it with `mistral-7b-instruct-v0.1.Q4_0.gguf`

**Comment by louis-jan** [comment]
@sherif414 here is the correct model folder structure: 
```md
└── models
     ├── mistral-7b-instruct-v0.1.Q4_0.json (Modelfile with "state": "ready" in the json body)
     └── mistral-7b-instruct-v0.1.Q4_0.gguf 
```

**Comment by dan-jan** [comment]
@linhtran174 @tikikun This seems to be due to the Windows folder structure. Can we triage and fix it in 0.4.1?

**Comment by linhtran174** [comment]
@sherif414: Can you try putting a wrapping folder like  `/models/mistral-7b-instruct-v0.1.Q4/`, and put the `.gguf` file inside.
Also make a `model.json` file similar to this https://github.com/janhq/jan/blob/main/models/mistral-ins-7b-q4/model.json, and adding another property {"state": "ready"} to the `model.json`

**Comment by sherif414** [comment]
it works as expected on v0.4.

**Comment by louis-jan** [comment]
Awesome @sherif414.
