### ISSUE TITLE
Discussion: questions around Server implementation and refactoring

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#845]
Related #798 

## Q: Given this refactoring, can Jan be run in the following modes:
1. `electron-only`: I want to only run Electron with ipcMain process, not Fastify, i.e. is what we currently have still an option going forward?
1. `server-only`: I want to only run Fastify server process(es), not Electron.
1. `dual`: I want both desktop app & local port: routes to single process
    - Can we have a `/web/dependecy-injection.js` for `dual` mode, what is routed to and what is not

- What's the current implementation enabling?
- In `dual` mode, what is the lifecycle of a user request (e.g. createAssistant)? 

```
User -- useCreateAssistant--> ElectronHandler --> POST?
User -- useCreateAssistant--> POST?
```

## Q: Can the shared logic be refactored out between Electron and Server implementations: 

i.e. 

Can this: 
`electron/handlers/fs.ts`
```js
  ipcMain.handle(
    'writeFile',
    async (event, path: string, data: string): Promise<void> => {
      try {
        await fs.writeFileSync(join(userSpacePath, path), data, 'utf8')
      } catch (err) {
        console.error(`writeFile ${path} result: ${err}`)
      }
    }
  )
```

Refactor into this: 
```js
infra/
    common/
        fs.ts
    electron/
        ___.ts/
    fastify-server/
        ___.ts/
    express-server/           // future possibility
        ... // import fs from common
```

Where Electron and Server share the same `common/fs.ts` implementation.
```js
import writeFile from /common

// infra/electron/adapter/fs.ts (or whatever path/filename)
ipcMain.handle('writeFile', writeFile)

// infra/server/adapter/fs.ts (or whatever path/filename)
export async function writeFile() { writeFile }
```

## Q: Can the api endpoints be auto generated? We're defining the entities anyway
```js
// infra/server/index.ts
// One-time-macro to auto generate API routes e.g. `CRUD /createAssistant` from `/core`
// This means users can add additional endpoints via extensions (without explicit definition)

import assistant from janhq/core

fastify.createEndpointsFor(assistant)
```

**Comment by louis-jan** [comment]
@linhtran174 is implementing this way

**Comment by 0xSage** [comment]
Good stuff. Is it in fact less work/maintenance long term? OR more work?

**Comment by louis-jan** [comment]
@0xSage less work/maintenance long term for sure

**Comment by louis-jan** [comment]
Since #948, we even removed `fs` handler. IPC & REST routes are proxied automatically @0xSage 
```ts
import writeFile from /common

// infra/electron/adapter/fs.ts (or whatever path/filename)
ipcMain.handle('writeFile', writeFile)

// infra/server/adapter/fs.ts (or whatever path/filename)
export async function writeFile() { writeFile }
```

**Comment by 0xSage** [comment]
Good stuff. Closing as this is addressed
