### ISSUE TITLE
bug: The tag description doesn't fully display

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#847]
**Describe the bug**
Some tags of the models don't display fully

**Screenshots**
<img width="692" alt="Screenshot 2023-12-05 at 14 12 15" src="https://github.com/janhq/jan/assets/64120343/aa0b53c4-368c-4006-ae93-3335c26dc695">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Jan v0.3.3.20

**Additional context**
There are 2 options:
- Shorten the tags
- Fix the UI

Please discuss for the best outcome.

**Comment by urmauur** [comment]
@hahuyhoang411 for confirmation i'll work on this resolve with UI

**Comment by hahuyhoang411** [comment]
Thank you @urmauur

**Comment by louis-jan** [comment]
I think @hahuyhoang411 already hacked by removing a tag. That could be a fix in the next release.

**Comment by urmauur** [comment]
ok i'll work when `v.0.4.0` @louis-jan and thanks @hahuyhoang411 for quick fix
