### ISSUE TITLE
epic: Improved Hub Experience for Models

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#850]
## Motivation
To address user feedback and enhance the Hub experience by improving model recommendations, refining filtering options, and providing clearer model version visibility.

## Specs 
Major user stories:
1. **Recommended Models by Hardware:**
   - As a user, I want to receive model recommendations tailored to my hardware specifications for optimal performance.

2. **Filtering Models by Attributes:**
   - As a user, I need to filter models based on tags, supported tools, maximum model size, parameters, and computer RAM compatibility.

3. **Filtering Downloaded Models:**
   - As a user, I want the ability to filter out models that I have already downloaded for more streamlined browsing.

4. **Hardware-Based Recommended Starter List:**
   - As a user, I expect a recommended starter list of models aligned with my hardware capabilities to kickstart my exploration.

5. **Efficient Model Search:**
   - As a user, I should be able to search for models by their name, ID, author, or URL, ensuring ease of discovery.

6. **Model Grouping with Version Information:**
   - As a user, I want models and their different versions displayed within the same group, simplifying model version comparisons and selections.

## Design
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1699-105656&mode=design&t=78l4n8TLR3sJeIAn-4

![Image](https://github.com/janhq/jan/assets/89722390/6bddc8e9-80e1-4416-ade8-dbc8f283ea0a)

## Tasklist
Design: @imtuyethan 
- [x] #1008 
- [x] #1205 

Development:  
- [ ] @urmauur FE #1386 
- [ ] @louis-jan @namchuai BE #1387 
- [ ] @hahuyhoang411 Metadata #1388

**Comment by hahuyhoang411** [comment]
@imtuyethan This issue address for the category on the Hub too.

Related task: https://github.com/janhq/jan/issues/839

**Comment by hahuyhoang411** [comment]
Realated task: Featured model https://github.com/janhq/jan/issues/860

**Comment by dan-jan** [comment]
I also think we should have nicer cover images for Models, e.g. 


Mistral: Paris, "Malayalam MN"
![Image](https://github.com/janhq/jan/assets/101145494/54185dd7-ebc5-4b40-9e84-e52fea477a79)


OpenHermes Neuralchat 7b "Major Mono Display"
![Image](https://github.com/janhq/jan/assets/101145494/405869cb-1819-4ae3-8966-8da1b368f05c)

**Comment by hahuyhoang411** [comment]
Related: https://github.com/janhq/jan/issues/897

**Comment by imtuyethan** [comment]
HUB REVAMP

Figma link: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=479-21691&mode=design&t=uV0D1oQLPoF6kzy2-4

Changes that address all the feedbacks & comments:
- 2 features model to get started
- List all models with sticky navs, and allow users to sort by "All models, Recommended, Downloaded" as well as quick selection of model type and parameters on the left side panel
- Changes in model card based on the current data we have right now & shortcomings: 
![Image](https://github.com/janhq/jan/assets/89722390/22aaa4a3-a5a1-4a53-9664-83426cdecb6e)

Preview: 


![Image](https://github.com/janhq/jan/assets/89722390/af755835-2db1-4a34-bbc1-d00d674bfea1)


![Image](https://github.com/janhq/jan/assets/89722390/8e6262fa-f2ae-4a93-a68b-0e7921dec8fb)

**Comment by imtuyethan** [comment]
Daniel:
I'd like to give a bit more context on the "Hub". This is a product that I'd like to get right: I believe we have a good chance to dominate this segment, and fill the gaps left by other teams. 

I've briefly looked through the updated wireframes and wanted to provide more context: 

epic: Jan Hub allows users to discover, import and download Models (and Assistants)
https://github.com/janhq/jan/issues/850

Big Picture
Hub is intended as a long-term "store". This is very important and will likely be our monetization lever
I want to focus us on getting a best-in-class Model Discovery, Downloading and Running experience
We will likely have PMfit in the early days, by being able to offer the latest models very quickly (e.g. run Starling on Jan!)

User Stories
User can browse, discover, import and download Models
User can import Models from Huggingface by pasting the Huggingface link => see Metadata, download
User can see an ordered list of recommended models
Ordered list should have useful headers (e.g. "good starter model"), that guide the user
[Eng to note]Jan should be able to update the Recommended Model list remotely (i.e. download additional model.jsons)

Design Constraints
Jan's UI should be easily adaptable to Desktop/Server, and Mobile
Look at Obsidian for a good example of a Desktop UI that adapts easily to Mobile (i.e. Left Drawer, Right Drawer)

Long-term User Stories
You should design with these longer-term directions in mind:
Hub will expand to have multiple "product types": Models (including remote), Assistants, Tools, Extensions
Hub will allow users to "publish" Assistants, Tools, Extensions
Hub will allow for automatic routing of revenue to AI creators


--------


 think we also need to think through the UX and IA of Jan very clearly. 

Ollama is extremely simple, maintainable = very clear, simple UX
Windows Store is more full-featured

I would recommend we take a very Ollama-like approach, with bias to simplicity, and add to it over the years.

One major difference we have we have vs. Ollama:

Jan: "Model + Quantization" as a model
Ollama: "Model" -> can pick quantization

We will need to be careful and check to see if it continues to be the best abstraction.

**Comment by dan-jan** [comment]
Feedback from user: 
https://www.reddit.com/r/LocalLLaMA/comments/18pyul4/comment/ketw7vp/?utm_source=share&utm_medium=web2x&context=3

**Comment by imtuyethan** [comment]
Archive Daniel's original comments - @imtuyethan to work on the latest specs:


## Kanban

https://github.com/orgs/janhq/projects/5/views/7?filterQuery=milestone%3A%22Improved+Hub+Experience+for+Models%22+

**Problem**
- Hub is currently a poorly-ordered list of models that user has to go through
- We should have a better way of structuring it, such that it feels more "appstore"-like, and less initimidating to a new user

## Ideas
- Hub has "Best-of" lists, e.g. [LLM Leaderboard](https://huggingface.co/collections/open-llm-leaderboard/llm-leaderboard-best-models-652d6c7965a4619fb5c27a03)
- Sorting
- Starter Models ("get started"), e.g. NeuralChat 7b models that are a fast download
- Recommender Algorithm? 
- Content should be centered in screen (vs. stretched too wide)
- Animations when scrolling/loading

As an aside, I find that it's difficult to download the larger models due to Huggingface server timing out. This should be a consideration in recommending models. It's better to get user to download a fast, quick model and get them using it quickly. 

## Related Tasks

- https://github.com/janhq/jan/issues/848
- https://github.com/janhq/jan/issues/835
- #871 
- #777 
- #786 
- #936 
- #1008 
- #1205 
- #1008 
- [ ] Recommended Models should pull from remote, auto-update when Jan is launched
- @tikikun's comment: https://github.com/janhq/jan/pull/829#issuecomment-1838035448

**Comment by 0xSage** [comment]
@imtuyethan gentle reminder to `close` Github issues because they remain open even if you move them to `done`
