### ISSUE TITLE
bug: Nightly Build has a "No published versions on Github" error

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#851]
**Describe the bug**
- See title
- Unclear to me if it is actually a bug, or if it's just something we have a failed if/else check for

**To Reproduce**
1. Download Nightly Build
2. Start Nightly Build

**Screenshots**
<img width="1197" alt="image" src="https://github.com/janhq/jan/assets/101145494/24d86f7a-bad2-4534-a37b-1e7ccd34fdbe">

**Desktop (please complete the following information):**
 - Version: Nightly Build 

**Additional context**

**Comment by louis-jan** [comment]
This is related to nightly build, once we moved to use tag as a single nightly build. This would be addressed automatically.
