### ISSUE TITLE
bug: MacOS can't run model

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#852]
Jan v0.3.3.20 MacOS

**Describe the bug**
I can't use any models in new Jan app

**To Reproduce**
1. Download v0.3.3.20
2. Download any models
3. Use the model
4. Start new convo and see error

**Screenshots**
<img width="1022" alt="Screenshot 2023-12-05 at 14 55 26" src="https://github.com/janhq/jan/assets/64120343/097dea03-6d28-4a95-a9ba-31ae201a9048">

**Comment by louis-jan** [comment]
Wrong app architecture. Redownload works
