### ISSUE TITLE
bug: UI bugs in Hub for v0.4

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#853]
**Describe the bug**
- Hub hero UI does not scale to full-width, larger screen widths
- See screenshots below

**Screenshots**
<img width="1800" alt="image" src="https://github.com/janhq/jan/assets/101145494/42f402aa-deed-4030-ad02-806766627b20">

**Desktop (please complete the following information):**

**Additional context**

**Comment by louis-jan** [comment]
Its addressed - Please try the latest nightly build today: 

https://discord.com/channels/1107178041848909847/1148534730359308298/1181441344758091809

**Comment by louis-jan** [comment]
Related issue #844
