### ISSUE TITLE
docs: add a changelog tab in blog style

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#86]
requirement: 
- Add `Changelog` as the last-left-tab on the nav bar
- Use Docusaurus blog feature to do this https://docusaurus.io/docs/blog 
- Hint: you should not be installing anything new!

**Comment by Its-Alamin-H** [comment]
I am trying to turn off the does mode for Changelog but it's saying: [ERROR] ValidationError: "docs" is not allowed.
![image](https://github.com/janhq/jan/assets/88797912/4958b648-4cb3-4a06-8f72-b297c808a183)

This is why the changelog is now look like a docs
![image](https://github.com/janhq/jan/assets/88797912/82df6168-6772-4fba-bf8c-868969c192c0)
