### ISSUE TITLE
feat: thread names to give better idea of conversation context

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#865]
**Problem**
User have to delete the text `New thread` before changing the name of the thread.

**Success Criteria**
User can edit the name right away

**Additional context**
We can approach it like the `instructions` text box.

Image:
<img width="123" alt="Screenshot 2023-12-05 at 22 43 13" src="https://github.com/janhq/jan/assets/64120343/cccb39b4-a7a7-4cee-8f5a-5df4e1fe0c57">

**Comment by dan-jan** [comment]
I think this should be part of larger story, where we have a ChatGPT-like feature which "names" the Thread based on the users' initial prompt

**Comment by 0xSage** [comment]
this was done via #1994
