### ISSUE TITLE
bug: tell users they cannot change the model after starting a thread with `Jan-default-assistant

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#866]
**Describe the bug**
It doesn't show model loading when i switch model, and the app is really lagging

https://github.com/janhq/jan/assets/89722390/0264472c-f4fd-4a34-8623-a090afac28fa

**To Reproduce**
1. Go to 'Threads'
2. Click on 'Model' on right panel
3. Change model

**Expected behavior**
See the correct flow here: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=150-5789&mode=design&t=IqgZVdfQhNwc9FrQ-4
<img width="914" alt="Screenshot 2023-12-06 at 1 55 55 AM" src="https://github.com/janhq/jan/assets/89722390/98fae55e-58ba-4595-ae83-821c9ffd05f7">

**Desktop (please complete the following information):**
 - Mac Air 16GB Ventura
 - Version 0.4

**Comment by hahuyhoang411** [comment]
@imtuyethan can you try 7B model to see whether it's laggy or not? Maybe because 13B Q5 need ~12GB RAM so it caused lag
cc @louis-jan

**Comment by louis-jan** [comment]
great find @hahuyhoang411, also we would just start model on message send, otherwise user could spam the model loading

**Comment by louis-jan** [comment]
otherwise, we can disable model switch on model starting

**Comment by imtuyethan** [comment]
Synced up with @louis-jan on this:
When users switch model on the right panel: Click on model to see model list -> Choose a model on that list -> Start loading model (while loading model, users cannot choose anymore til the model they selected is downloaded).

See flow: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=150-5789&mode=design&t=IqgZVdfQhNwc9FrQ-4

**Comment by 0xSage** [comment]
I'm pivoting this issue back into a design task. 

@imtuyethan lets have a simple hover over popup that just shows users they cannot change the model after the conversation has started.

**Comment by imtuyethan** [comment]
# Design changes
[New flow - Figma link](https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=837-107611&mode=design&t=kDV5n2PeEWVksXAx-4)

### Problem:
Currently (v0.4.2), we disable the model field in right panel because UX changed, users are not allowed to change model once they start a threads, while:
- It should be a text field instead of a disable dropdown box
- Users may be confused because the model selection is hidden in right panel along with lots of different settings, users could be missed it when they start a new threads & forget to change model. 

### My proposed changes:
#### If users have an active model
- When they start a new threads, they will see what model is currently associated with the new threads:
![Image](https://github.com/janhq/jan/assets/89722390/e299df9f-a444-4200-a4df-0d97055b595e)
- And they can change it before starting the threads:


![Image](https://github.com/janhq/jan/assets/89722390/35672746-f2ce-4b76-bcb1-a520d10780f3)

- Or start the threads right away if they intent to continue with the active model, and the model info on right panel is info field - cannot be changed:


![Image](https://github.com/janhq/jan/assets/89722390/a1184859-8134-4265-b2d2-d21e60b8e32f)



This way, users are `well-informed`.

#### If users don't have any active model:
Ask for model choices before starting (same as old flow, but duplicate the model component outside of right panel for better visibility).


![Image](https://github.com/janhq/jan/assets/89722390/fcd59f92-8fd3-4662-a502-481f51e3a2ac)

**Comment by 0xSage** [comment]
@imtuyethan lets refine this a bit more before sending to eng. Can do so in our daily pm sync

**Comment by imtuyethan** [comment]
@louis-jan 
Design update for today's release: Added a tooltip saying `To change model, please start a new threads`


![Image](https://github.com/janhq/jan/assets/89722390/9a48b031-5a4f-449e-9ccc-05bec3bd5708)
