### ISSUE TITLE
bug: The retry button is not working properly

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#868]
**Problem**
The current app won't delete the old one when using `retry` button. And moreover, it's keep autonomously continue chatting and behave like both users and assistant

**Success Criteria**
It will delete old response and response the previous users message only

**Additional context**
Video:

https://github.com/janhq/jan/assets/64120343/53e90e76-5dc7-4343-aef9-4782513313ba

**Comment by louis-jan** [comment]
Resolved
