### ISSUE TITLE
bug: Linux Install Issues

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#875]
WIP, will add more as I go through

## Main Issue

- After installing Jan, starting Jan = no Jan Window appeared

## Other Issues

Needs updated Metadata (gets shown in Software Install)
![image](https://github.com/janhq/jan/assets/101145494/63758ea6-148f-428a-b6a2-1b43b87848c7)
![image](https://github.com/janhq/jan/assets/101145494/21430bc4-cbad-47c6-8584-5361d51da76b)

Needs instructions on how to wipe old legacy installations
![image](https://github.com/janhq/jan/assets/101145494/f870ca2a-13c0-46fd-b498-f4eafa2591cf)
![image](https://github.com/janhq/jan/assets/101145494/f5086e34-02c9-483c-8277-a8ff983cdaf3)

Dan's note: I resolved using
```
sudo apt uninstall jan-electron
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Version: v0.4

apt install failed, but `dpkg -i` succeeded
![image](https://github.com/janhq/jan/assets/101145494/8ec38be4-e403-4649-8b36-f0a2280084cb)

**Additional context**

**Comment by hiento09** [comment]
Related issue https://github.com/electron/electron/issues/40461
