### ISSUE TITLE
docs: Overview

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#88]
## Overview

- Jan needs an "overview" to explain what we are trying to do
- This will be sent to potential customers, partners
- Include Roadmap?
- How does this differ from "Getting Started"? (should Getting Started just be a docs.jan.ai/guides/getting-started?)

## Inspirations

- Rocketpool "Overview" is quite good
- https://docs.rocketpool.net/overview/

**Comment by 0xSage** [comment]
closing in favor of an actual homepage
