### ISSUE TITLE
feat: Option to cancel model starting operation

### ISSUE THREAD

**Issue by linhtran174** [janhq/jan#880]
**Problem**
When model took too long to load and consumes all CPU, it causes my PC to be laggy and I want to cancel that operation right away.
The options I have now are:
- Wait for the model to complete loading, and stop model 
- Delete model 

![image](https://github.com/janhq/jan/assets/8022780/7f7595bf-fdc6-4208-b7ce-2da56a1b3253)

**Comment by dan-jan** [comment]
@linhtran174 I'm going to move this to 0.4.1. This can be shipped easily with a simple "cancel" button in the Model Loading UI

**Comment by linhtran174** [comment]
@urmauur: Can you help adding a "cancel" button that replace "start model" button after clicking start? Also later please show me the entry to that code so I can integrate with extension logic

**Comment by linhtran174** [comment]
Added a draft: Add button & reuse stopModel ops for cancelling. It's not working properly yet @louis-jan said it's not super important in this release so I switch to other bugs

**Comment by urmauur** [comment]
@louis-jan i saw the cancel is already on @namchuai PR
