### ISSUE TITLE
bug: Navigating to Latest Convo does not show Convo

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#882]
**Describe the bug**
Navigating to the Latest Convo does not show the Convo

**To Reproduce**
1. Create a new thread and have a conversation
2. Exit the thread to a previous thread (historical)
3. Click on the thread in (1)
4. See a "How can I help you" waving hand, instead of the converasation (however preview still available in left panel)

**Expected behavior**

- I should have been able to see the conversation. 

**Screenshots**

![image](https://github.com/janhq/jan/assets/101145494/04c9b53a-9f7e-4501-b38f-9830c65d2f3d)

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Version v0.4.0

**Additional context**

**Comment by louis-jan** [comment]
2 possible root causes found: 
- Thread messages.jsonl is broken due to delete message action does not add a line break (resolved 0.4.1)
- Streaming message is not persisted in background (on-going)
