### ISSUE TITLE
bug: Running neural-chat-7b consuming 100% CPU

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#887]
Issue from @linhtran174 
Running neural-chat-7b consuming 100% CPU, model not started, been running for more than 2 mins now. GPU not utilized 😢. 
Update: It works, just too slow. Token speed at 0.03/s

![image](https://github.com/janhq/jan/assets/89722390/038f6dd8-6805-47d6-9c9d-6b168f8c5721)

**Comment by tikikun** [comment]
Will be resolved with hardware optimization issue

**Comment by tikikun** [comment]
@vuonghoainam resolved with hotfix
