### ISSUE TITLE
feat: Are we missing the title for each section in the Hub?

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#897]
**Problem**
The Hub right now sorts in a logic but when the users look at our Hub with all of the number of model size (7b, 13b, 33b,...) is a little bit tricky for them.

**Success Criteria**
Can we have a title for each model size? some what like
- Featured:
  - model A
  - model B
- 7B:
  - model 1
  - model 2
- 13B:
  - model 1
  - model 2

**Additional context**
This is image demonstrated what I meant

<img width="849" alt="Screenshot 2023-12-07 at 14 17 45" src="https://github.com/janhq/jan/assets/64120343/d7d86de9-4e63-4ee8-bb7f-6537f3f30bda">

**Comment by hahuyhoang411** [comment]
It's up to you 2 @urmauur and @imtuyethan

**Comment by hahuyhoang411** [comment]
and we need a section for "Other language" model too. (like for SEA, for chinese, ...)

**Comment by imtuyethan** [comment]
@hahuyhoang411 there are too many duplicate tickets for this

**Comment by imtuyethan** [comment]
Can you include it in here" https://github.com/orgs/janhq/projects/5?pane=issue&itemId=46599875 @hahuyhoang411

**Comment by hahuyhoang411** [comment]
Closed it and include to the main one
