### ISSUE TITLE
feat: Where should we place the subtag?

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#898]
**Problem**
We are missing the subtags for:
- Is it suitable for the users to use model (RAM usage,...)
- And what is the model good for
  - Coding
  - General usage
  - Role-playing

**Success Criteria**
We should have a subtag some where in the model card to clarify it.

**Additional context**
Image of simple thought:

<img width="834" alt="Screenshot 2023-12-07 at 14 25 19" src="https://github.com/janhq/jan/assets/64120343/46dbf23e-72de-44c2-985f-ad3eae99baac">

**Comment by hahuyhoang411** [comment]
Again it's up for you 2 to chose the best design for it @urmauur , @imtuyethan .

**Comment by imtuyethan** [comment]
Update along with https://github.com/janhq/jan/issues/850

**Comment by hahuyhoang411** [comment]
Closed this and move to the big convos
