### ISSUE TITLE
blogs: ultimate guides to X

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#90]
We will invest in long-term guides as part of docs site: 
- High quality educational resources, vs. "fast food" social media posts
- Target Enterprise customers who want to understand technical depth
- Save people the time of having to trawl through r/localllama, Discords for quality information

## Possible Guides
- Ultimate guide to Generative AI
- Ultimate guide to Local AI
- Ultimate guide to LLMs
- Ultimate guide to StableDiffusion

## Inspirations

- https://zapier.com/resources/guides
- https://posthog.com/tutorials
- https://gpus.llm-utils.org/nvidia-h100-gpus-supply-and-demand/

**Comment by dan-jan** [comment]
Hey @Its-Alamin-H I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/janai-64facd7c57cd740d4d0afeae/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_

**Comment by 0xSage** [comment]
Closing this in favor of more specific posts later. On topics with verified interest.
