### ISSUE TITLE
feat: Give users Prompt suggestions

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#901]
I created a hackmd to store all of the draft system prompt. Please add more topic and assistant/character you want to play in the comments so that I can create more.

https://hackmd.io/verrdaBWT-ykB9oc_CM_lw

**Comment by hahuyhoang411** [comment]
After researching, I think we need a way to parse the *character card* for roleplaying if users need.

Reference: janitorai

**Comment by imtuyethan** [comment]
deprecated
