### ISSUE TITLE
feat: Copy button for code block

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#908]
**Problem**
We haven't had a copy button for the code block yet. The only way to copy is copy the whole message.

**Success Criteria**
Only copy the text between triple backticks (```)

**Additional context**
The example of copy button:

<img width="580" alt="Screenshot 2023-12-08 at 11 22 04" src="https://github.com/janhq/jan/assets/64120343/834b8942-a585-432f-9831-a3c83a00dfc7">

**Comment by 0xSage** [comment]
From my issue: 

**Problem**
Users can't easily copy code answers

**Success Criteria**
A clear and concise description of what you want to happen.

**LLM responds with a code block**
User hovering over codeblock should see option to copy codeblock
Clicking copy, copies only the code, not the entire LLM response.
Additional context
Add any other context or screenshots about the feature request here.
