### ISSUE TITLE
epic: support AMD using Vulkan

### ISSUE THREAD

**Issue by tikikun** [janhq/jan#913]
**Problem**
There is no build for AMD now on windows GPU

**Success Criteria**
Good performance for AMD GPU user on windows

## Out of Scope
- ROCm support

## Subtasks
- [x] #1608 
- [x] Support with Vulkan - https://github.com/janhq/jan/pull/2056
- [x] https://github.com/janhq/nitro/issues/323 - test with RoCM

**Comment by tikikun** [comment]
https://rocm.docs.amd.com/projects/install-on-windows/en/latest/reference/system-requirements.html

**Comment by tikikun** [comment]
list of supported amd gpus

**Comment by jalberto** [comment]
will be great to have linux support too, as rocm works in Linux

**Comment by 0xSage** [comment]
Increasingly highly requested by users

**Comment by Christianb233** [comment]
it seems that there is no ROCm installation for GPU AMD Radeam RX6600M :-( ; so I am not able to run jan.ai on GPU :-(

**Comment by 0xSage** [comment]
@tikikun you're tackling this issue already? How are we approaching it? Wanna do a quick share during standup

**Comment by tikikun** [comment]
hi @0xSage we have built the amd image already but have no gpu to test

**Comment by alexandre-hemery** [comment]
Hey, did you find an AMD GPU yet?

**Comment by alexandre-hemery** [comment]
Hey @tikikun, did you find an AMD GPU yet?

**Comment by Soddentrough** [comment]
Happy to volunteer if testers are needed. I can test with RDNA3 & 2.

**Comment by 0xSage** [comment]
@hiento09 to take this on during @hiro-v leave

**Comment by jalberto** [comment]
I am happy to test in a RX 7600

**Comment by louis-jan** [comment]
Experimental feature: 0.4.7

**Comment by Van-QA** [comment]
Closing this and handling [epic: nitro AMD ROCm GPU support janhq/nitro#323](https://github.com/janhq/nitro/issues/323) in a separate epic
