### ISSUE TITLE
bug: Windows: "Close, Minimize, Maximize Button" are missing from UI

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#929]
Close, Minimize, Maximize Button are missing from the UI on Windows

![image](https://github.com/janhq/jan/assets/101145494/538e3c63-6e07-46bc-87c0-02cb18a931d4)

OS: Windows.

**Comment by dan-jan** [comment]
@linhtran174 I'm reassinging this task to you

**Comment by linhtran174** [comment]
Resolved, but I mistakenly pushed to branch of another issue #928
