### ISSUE TITLE
Add hover state to Left Panel shortcuts

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#93]
Migrated from Linear: 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFYrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--15c0ea55d5e52ac733589805ac24fd6663668767/image.png)

**Comment by namchuai** [comment]
#160
