### ISSUE TITLE
feat: users can tell which are remote models (like openai api) in the UI

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#936]
**Problem**
We need a few UI states, now that we're incorporating remote models (like openai gpts):
- local model vs remote model
- when users are offline, what do we show them
- how are model parameters different?
- where do users input api key?

**Comment by imtuyethan** [comment]
Epic: https://github.com/orgs/janhq/projects/5/views/25?sliceBy%5Bvalue%5D=imtuyethan&pane=issue&itemId=47526877

**Comment by 0xSage** [comment]
@imtuyethan FYI for future reference, when a design is approved, please help to: 
1. Remove: needs designs label
2. Add: needs specs label
3. Assign to me

Thanks!

**Comment by imtuyethan** [comment]
No longer relevant. Close now.
