### ISSUE TITLE
bug: Only show message queue when users enter their second message

### ISSUE THREAD

**Issue by imtuyethan** [janhq/jan#939]
**Problem:** 
Right now, when users enter their first message, Jan shows "Message queue" message right away:

https://github.com/janhq/jan/assets/89722390/36a792be-3b9a-452e-98af-d914007935d0

### If the thread uses the same model as the current active model: Users send message & receive response normally
<img width="953" alt="Screenshot 2023-12-11 at 3 31 13 PM" src="https://github.com/janhq/jan/assets/89722390/603bac30-c1e1-4a43-954c-60329ceaf65d">

### If the thread uses a different model
- Once users enter the first message -> send that message + start model:
![Input message](https://github.com/janhq/jan/assets/89722390/d98b28b6-58aa-4ba8-a35d-f0e5d62609e8)
_(Inputing message)_

![Starting model](https://github.com/janhq/jan/assets/89722390/6b52e9e7-35eb-4aba-a6d3-785483dadfb2)
_(Message sent + starting model)_ 

- When model is starting, we **will not** disable the input field, if users continue to input...
![Continue inputing message](https://github.com/janhq/jan/assets/89722390/548c10d8-7428-48f5-8f48-23ab7c241d9d)
- Once they click send, it cannot be sent and show "message queue" status:
![Message queue](https://github.com/janhq/jan/assets/89722390/65adf028-8070-4d6d-ac69-bee6d7af1f50)

_**_Note that the "message queue" message should disappear after 3 seconds, and if users type send again while model is still starting -> show that message again_**_

Figma flow: https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=549-43054&mode=design&t=59imhnuCTJu4oesf-4

**Comment by urmauur** [comment]
@imtuyethan  CMIIW in your video you don't have active model, so that why you got `Message queue`

**Comment by imtuyethan** [comment]
> @imtuyethan CMIIW in your video you don't have active model, so that why you got `Message queue`

Yes, what i mean is that if i don't have active model, it should start the model without showing message "Message Queue". You can read the flow i typed out.

**Comment by louis-jan** [comment]
Sorry @urmauur, let us align on this issue for the appropriate fix. Might #886 is the one should be done before this.

**Comment by 0xSage** [comment]
KIV'ing this for the future when we do allow model switching in **existing threads**
