### ISSUE TITLE
Jan should use Responsive TailwindUI layout

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#94]
## Overview
- Currently web version is not compatible with mobile device
- Self-css to follow design - should utilize tailwindui layout

## Ideal Deliverable

- UI should be "polished" (i.e. "paid" software)
- UX should be similar to ChatGPT

## Resources
- Multi column layout: https://tailwindui.com/components/application-ui/application-shells/multi-column#component-65815af4357dfdcf9be55c390221c5fb
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2FEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--da802f589440da147f768b4b25474196cf3b4525/Screenshot%202023-09-10%20at%2011.03.44%20PM.png)

- Right pane slide overs: https://tailwindui.com/components/application-ui/overlays/slide-overs#component-4d1d575bd79eef81afc9a4f2e1900ecb
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa2VEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--54bb70c6e96c627c1a2c321f0f13aa4128aa3ed7/image.png)

- Settings page: https://tailwindui.com/components/appl
- ication-ui/page-examples/settings-screens
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa1dEIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f0cfe9485f69083e39b374034556943ee2b7fb58/Screenshot%202023-09-10%20at%2011.02.56%20PM.png)

## Tasking

- @drakehere to work with @namchuai

**Comment by 0xSage** [comment]
Closing this issue as new designs more or less reflect tailwind
