### ISSUE TITLE
Discussion: Llama.cpp concurrency model 

### ISSUE THREAD

**Issue by linhtran174** [janhq/jan#959]
**Motivation**
I'm putting this here as a draft. I have thoughts that aren't translating to anything doable yet so I leave it here to focus on other bugs without forgetting it.

The story is that we have a bug that cause 100% CPU loading models on some machine, and that was due to multithreading was not properly considered by llama.cpp, especially on newer-gen CPUs with separate efficient and performant cores. (TODO: Link related llama.cpp discussions here). Llama.cpp suggests setting the thread count = performant core count in this care and we incorporated it and for now fixed the problem. 

However as engineers I think it's still good to keep questions on llama.cpp concurrency model, so that we can accumulate clues while operating our Jan app, and refine it to be closer to the ground truth (comprehending all of llama.cpp bits and pieces - which is not feasible right now). `concurrency model` sounds confusing, so I'll explain more below. 

Basically I want to know how llama.cpp handle its smallest executable unit, which to my current knowledge I assume to be a `thread`. I want to distinguish `thread` in llama.cpp execution model from platform specific implementation of threads, with multiple layers of stuffs from hardware vendor like Intel's hyperthreading, to OS level `threads`. Llama.cpp threads may expect the CPU cache/ memory to be of certain size, with certain speed/latency, no pre-emption. Where as actual threads provided may subject to scheduling, pre-emption, shared cache/ memory, etc. 
I think the recent performance bugs in this view is the mismatch between llama.cpp threading model and actual thread model provided by the platform. Setting the thread count = core count is a heuristic which alleviate the problem, but if we can match the threading model on both ends then we can always optimize execution to the max. Matching both ends might be redundant though, as llama.cpp can also change to support a platform directly. 

**Discussion**

**Alternatives**

**Resources**

**Comment by tikikun** [comment]
You can get some insights from kobold as a windows first application : https://github.com/LostRuins/koboldcpp

That's being said, given the pace and the speed of the delivery we need and the complexity of ggml as a whole, it will be challenging to do this.

**Comment by linhtran174** [comment]
Yeah I know. Will take a look at the example. Thank you for the insights!

**Comment by tikikun** [comment]
Our highest priority now is to go with low effort option and can have effects soon to improve windows ux in general, since time is very critical right now.

**Comment by tikikun** [comment]
So an exact time estimation for this will help very much
