### ISSUE TITLE
feat: User can see elapsed time for each AI inference request

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#96]
## Overview

- Similar to Perplexity https://labs.perplexity.ai/
- We would have this for each AI query

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWQrIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--efde79a6c632621308aa99ee4ab3c7030177af9a/image.png)

## Additional Ideas

- We can have a ShareGPT equivalent, where we publish the (a) model, (b) infrastructure type, and (c) response times for the model.
- Could be very useful for benchmarking hardware performance, model choice (e.g. 7b, 34b, 70b), and inference speed

**Comment by 0xSage** [comment]
Closing this as our UI is undergoing significant change. We can reopen in the future.
