### ISSUE TITLE
epic: Autogenerate Swagger API Docs and Entity Types

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#968]
## Specs

https://www.notion.so/jan-ai/Autogenerate-Swagger-Documentation-and-Entity-Types-b5ef2170a5fe4e8693e6857202b0036c?pvs=4

**Comment by louis-jan** [comment]
@Inchoker would own this, he has an interesting technique to solve it. cc @Van-QA

**Comment by louis-jan** [comment]
It's completed from Cortex side.
