### ISSUE TITLE
bug: CPU usage increase when regenerating on Windows

### ISSUE THREAD

**Issue by hahuyhoang411** [janhq/jan#970]
Jan Windows v0.4.0-40
CPU: i7-12700
CUDA: 12.3 Driver Version: 545.92
RAM 32GB

**Describe the bug**
The CPU goes up to 90-100% after regenerating response

**To Reproduce**
1. Use a local model
2. Create new chat with it
3. Stop the response of the LLM (click on `Stop` button)
4. Regenerate the response (`click on `Regenerate` button) -> See error

**Screenshots**
Normally it takes about 40-50% CPU
![image](https://github.com/janhq/jan/assets/64120343/c4f7ca71-5257-4242-b815-24c8e658a44e)

After stopping and regenerating it's up to 90-100% CPU
![image](https://github.com/janhq/jan/assets/64120343/a0f6cd54-66d4-49d0-8a0e-69ebf0c8c852)

**Comment by louis-jan** [comment]
@hahuyhoang411 could you please retry again, I don't see this issue on my end. 
Also: 
App will just fetch CPU usage periodically (every 5s), so: 
You would see a cached CPU til next update, please generate a long response to measure

**Comment by louis-jan** [comment]
Confirmed. Close now
