### ISSUE TITLE
docs: how to import a model you downloaded (and modify the `model.json`)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#973]
**Motivation:** 
- We technically support all gguf models
- Users might feel their options are only limited to what's in the Hub
- I want to be able to tell my friends, "hey you can run your custom_model_merge.gguf on Jan, here's a guide" rather than helping them step by step (current situation)
- The hub should show this tooltip somewhere. (import custom model) button links to this page or something. Can work with @imtuyethan on this part

**Pages**
- https://jan.ai/guides/models/import-models

**Success Criteria**
Content that should be covered
- Downloading Models
  - which format, which size, etc. keep this part short - link out to other pages if needed
- Importing Model into Jan via UI
- Customizing Model via UI
- Importing Model into Jan via filesystem (directly adding the model.json)
  - This UX needs some thinking. 
  - Should we give them a commadn line script?
  - Just show screenshots on how to drag and drop?
  - Really think through this
- List of bugs/ideas discovered as a result of the QA and doc process

**Additional context**
Examples, reference pages, resources

**Comment by hahuyhoang411** [comment]
I draft it here: https://hackmd.io/OMZbdgTZRt2XdZ6l8jH5WQ

will refine tmr morning for the merge

**Comment by 0xSage** [comment]
Done, courtesy @hahuyhoang411 . Please feel free to directly create a PR next time (not a hackmd)
