### ISSUE TITLE
docs: How to kill orphaned Nitro processes on Windows

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#977]
## Objective

- Jan sometimes runs into issues where there is an orphaned Nitro process (e.g. due to force-exit of Jan)
- We should include `README` docs for common troubleshooting, e.g. how to find and kill Nitro processes
    - For Windows
    - For Mac/Linux

## Related Issues

- https://github.com/janhq/jan/issues/972
- https://github.com/janhq/jan/issues/976

**Comment by vuonghoainam** [comment]
This has been fixed with Jan release 0.4.1 for Windows and tested ok on 3 platforms (windows, macosx and linux)
