### ISSUE TITLE
feat: Ubuntu Software Install potentially unsafe

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#987]
## Objective

- [ ] Description should be updated, including Project Website
- [ ] Code signing for Ubuntu?

![image](https://github.com/janhq/jan/assets/101145494/8548a93d-8d48-45a4-9695-ad52dfb9ac71)

**Comment by hiento09** [comment]
I am going to close this since our app is not published to Ubuntu Software center, We provided an `.AppImage` to help run our app on multi linux os.
