### ISSUE TITLE
feat: Threads should show "Jan using <model_name>" instead of "Assistant"

### ISSUE THREAD

**Issue by dan-jan** [janhq/jan#989]
Note: This is a Product discussion, not confirmed as an issue yet.

## Objective

- Threads view should educate the user on Jan as an Assistant, but also show the model name
- I would like to propose us have the Assistant reply as "Jan using <model-name>", instead of Assistant
- This enables us to push "Jan" as a default Assistant

## Screenshots

![image](https://github.com/janhq/jan/assets/101145494/e08eb509-1184-4b09-b179-fb961fa9e599)

**Comment by imtuyethan** [comment]
We also need to find a way to create Thread Titles, ChatGPT style - right now everything just says "New Thread"

**Comment by 0xSage** [comment]
I think users like editting thread titles. If not, then we're also tracking #979
