### ISSUE TITLE
epic: Better Design abstraction for Remote AI (and Engineering abstraction)

### ISSUE THREAD

**Issue by 0xSage** [janhq/jan#994]
**Problem**
<img width="1128" alt="image" src="https://github.com/janhq/jan/assets/69952136/c7321478-21e7-4893-8990-78d375967927">

- It's not clear to users they need to add an API key to chat with remote models. 
- It's not clear to users the diff btw remote vs local model.
- Right now it just looks like its broken. 

**Success Criteria**
1. RightPanel should indicate this model is not set up yet. Let's try the label `API key needed`
2. We should somehow link the user to settings > models to set it up
<img width="454" alt="image" src="https://github.com/janhq/jan/assets/69952136/6c1353cb-478b-4e42-98df-81b774aeaa40">

**Additional context**

**Comment by imtuyethan** [comment]
## Design
https://www.figma.com/file/ytn1nRZ17FUmJHTlhmZB9f/Jan-App?type=design&node-id=1190-33531&mode=design&t=hHvTFu6BxvZx3oQh-4


![Image](https://github.com/janhq/jan/assets/89722390/caa0834f-e338-48e8-bda0-3364443a1505)

**Comment by imtuyethan** [comment]
Archive original comment from @0xSage 
**Problem**
<img width="1128" alt="image" src="https://github.com/janhq/jan/assets/69952136/c7321478-21e7-4893-8990-78d375967927">

- It's not clear to users they need to add an API key to chat with remote models. 
- It's not clear to users the diff btw remote vs local model.
- Right now it just looks like its broken. 

**Success Criteria**
1. RightPanel should indicate this model is not set up yet. Let's try the label `API key needed`
2. We should somehow link the user to settings > models to set it up
<img width="454" alt="image" src="https://github.com/janhq/jan/assets/69952136/6c1353cb-478b-4e42-98df-81b774aeaa40">

**Additional context**
Add any other context or screenshots about the feature request here.

**Comment by kha84** [comment]
I looked through the UI mockups and I can see there's one thing is missing - to allow user to specify it's own URL, for OpenAI-compatible models. Like for instance I do have a model running on my server via  oobabooga (it provides OpenAI-compatible API out of the box) or via ollama+LiteLLM. And I want to be able to chat with that model from Jan - for that I need to be able to add a remotely inferenced model with OpenAI-compatible API on a custom URL.

**Comment by imtuyethan** [comment]
> I looked through the UI mockups and I can see there's one thing is missing - to allow user to specify it's own URL, for OpenAI-compatible models. Like for instance I do have a model running on my server via oobabooga (it provides OpenAI-compatible API out of the box) or via ollama+LiteLLM. And I want to be able to chat with that model from Jan - for that I need to be able to add a remotely inferenced model with OpenAI-compatible API on a custom URL.

Thanks for flagging this @kha84. I'll ad this user story as well!

**Comment by dan-jan** [comment]
I am sunsetting this issue in favor for a more holistic redesign of the "Provider" abstraction:

https://www.notion.so/jan-ai/Provider-Abstraction-for-Local-and-Remote-AI-d54448ad5ce34cb2845d986870b9395e?pvs=4
